### ISSUE TITLE
I can not register PJSUA2 to asterisk using IPv6 Scope-ID

### ISSUE THREAD

**Issue by maccadoo** [pjsip/pjproject#2294]
I have confirmed that IPv4 can be connected without any problems.
But, IPv6 can not.

Server Debian10
Asterisk 16.6.1

Client Ubuntu 18.04.4
PJSIP 2.10

ID 1921
PASS abcdefg
IPv6 Scope-ID [2100:a:a::1:1]
Port 5160

Execute a command
./pjsua-x86_64-unknown-linux-gnu --log-file=~/log.txt --log-level=6 --id=sip:1921@[2100:a:a::1:1] --registrar=sip:[2100:a:a::1:1]:5160 --realm=asterisk --username=1921 --password=abcdefg --ipv6

LOG
08:12:41.721         os_core_unix.c !pjlib 2.10-dev for POSIX initialized
08:12:41.722         sip_endpoint.c  .Creating endpoint instance...
08:12:41.722                  pjlib  .select() I/O Queue created (0x55ba68886510)
08:12:41.722         sip_endpoint.c  .Module "mod-msg-print" registered
08:12:41.722        sip_transport.c  .Transport manager created.
08:12:41.722           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
08:12:41.722           pjsua_core.c  .Error creating log file: No such file or directory [status=120002]
08:12:41.722           pjsua_core.c  Shutting down, flags=0...
08:12:41.722           pjsua_core.c  PJSUA state changed: CREATED --> CLOSING
08:12:41.722           pjsua_call.c  .Hangup all calls..
08:12:41.722          pjsua_media.c  .Call 0: deinitializing media..
08:12:41.722          pjsua_media.c  .Call 1: deinitializing media..
08:12:41.722          pjsua_media.c  .Call 2: deinitializing media..
08:12:41.722          pjsua_media.c  .Call 3: deinitializing media..
08:12:41.722           pjsua_pres.c  .Shutting down presence..
08:12:42.731           pjsua_core.c  .Destroying...
08:12:42.731          pjsua_media.c  .Shutting down media..
08:12:42.731         sip_endpoint.c  .Module "mod-msg-print" unregistered
08:12:42.731                timer.c  .Dumping timer heap:
08:12:42.731                timer.c  .  Cur size: 0 entries, max: 3070
08:12:42.731         sip_endpoint.c  .Endpoint 0x55ba6887b778 destroyed
08:12:42.731           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
08:12:42.731           pjsua_core.c  .PJSUA destroyed...

ID not recognized to PJSUA2
SO, I have that ID is not IPv6 Scope-ID
Execute a command
./pjsua-x86_64-unknown-linux-gnu --log-file=~/log.txt --log-level=6 --id=sip:1921@2100:a:a::1:1 --registrar=sip:[2100:a:a::1:1]:5160 --realm=asterisk --username=1921 --password=abcdefg --ipv6 

LOG
08:11:02.060         os_core_unix.c !pjlib 2.10-dev for POSIX initialized
08:11:02.064         sip_endpoint.c  .Creating endpoint instance...
08:11:02.065                  pjlib  .select() I/O Queue created (0x557c85a9c510)
08:11:02.065         sip_endpoint.c  .Module "mod-msg-print" registered
08:11:02.065        sip_transport.c  .Transport manager created.
08:11:02.065           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
08:11:02.066     pjsua_app_config.c  Error: invalid SIP URL 'sip:1921@2100:a:a::1:1' in local id argument
08:11:02.066           pjsua_core.c  Shutting down, flags=0...
08:11:02.066           pjsua_core.c  PJSUA state changed: CREATED --> CLOSING
08:11:02.066           pjsua_call.c  .Hangup all calls..
08:11:02.066          pjsua_media.c  .Call 0: deinitializing media..
08:11:02.066          pjsua_media.c  .Call 1: deinitializing media..
08:11:02.066          pjsua_media.c  .Call 2: deinitializing media..
08:11:02.066          pjsua_media.c  .Call 3: deinitializing media..
08:11:02.066           pjsua_pres.c  .Shutting down presence..
08:11:03.073           pjsua_core.c  .Destroying...
08:11:03.073          pjsua_media.c  .Shutting down media..
08:11:03.073         sip_endpoint.c  .Destroying endpoint instance..
08:11:03.073         sip_endpoint.c  .Module "mod-msg-print" unregistered
08:11:03.073        sip_transport.c  .Destroying transport manager
08:11:03.073                timer.c  .Dumping timer heap:
08:11:03.073                timer.c  .  Cur size: 0 entries, max: 3070
08:11:03.073         sip_endpoint.c  .Endpoint 0x557c85a91778 destroyed
08:11:03.073           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
08:11:03.073           pjsua_core.c  .PJSUA destroyed...

It seems that the ID was recognized but the register was not recognized.
How do I separate port and IP without using IPv6 Scope-ID in registers?

The following was written on this link
https://trac.pjsip.org/repos/wiki/IPv6
Although in the SIP ABNF grammar an IPv6 may or may not be enclosed in square brackets ([ and ] characters), in pjsip all IPv6 addresses will be represented without the square brackets, for consistency. This means pjsip will remove the square brackets, if they are present, during parsing process, and will enclose the address with square brackets as necessary when pjsip prints the Ipv6 address in a packet for transmission. When application inspects a message component that contains IPv6 address, it will always find it without the enclosing brackets. 

Can you change it to recognize square blocks?

**Comment by sauwming** [comment]
I tested it here and it seems to work (no error in pjsua sample app).
I believe this should have been fixed by #2266.

Closing the issue for now. Please let us know if this is not the case.
