### ISSUE TITLE
How to decode DVI4 RTP payload type?

### ISSUE THREAD

**Issue by MohseniBigBoy** [pjsip/pjproject#2298]
I want to decode DVI4 but I don't know which library should I use.

**Comment by sauwming** [comment]
We don't support DVI4 and it seems that [RFC 7007](https://tools.ietf.org/html/rfc7007) has removed the recommendation for its support.
If you still wish however, you can implement it yourself by adding it in pjmedia-codec (have a look at our existing audio codec implementation for reference).

**Comment by MohseniBigBoy** [comment]
Do you know a proper reference for its implementation? I can not find any independent RFC about this codec. I can convert dvi4 to adpcm for an audio file but when I use the code to decode RTP payload, the result audio has noise!
I use [this](https://github.com/dbry/adpcm-xq) code.

**Comment by sauwming** [comment]
Unfortunately I don't. Googling around also gives the same result that you already more or less know.
