### ISSUE TITLE
Generate some dll or Wrapper for c #

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2302]
@sauwming Hello, i wanted to know if there was any possibility or if you had any way of being able to generate a wrapper or some dll based on PJSUA app, that the truth is the best I've seen, and I wanted to know if there was any way to generate a dll or a wrapper. Or if there is any way I can generate it, can you tell me.

Thank you I will wait for your answer

**Comment by sauwming** [comment]
Duplicate of #2299.
Please avoid opening new issues for same/similar topics. Thanks.
