### ISSUE TITLE
Generate dll 

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2305]
Hello, I wanted to know if there was any possibility or if I had any way to generate a wrapper or some dll based on the PJSUA application, that the truth is the best I've seen, and I wanted to know if it was any way to generate a dll or a container without having to use swig or some other technology.
Thank you i wait for your answer

**Comment by sauwming** [comment]
You can try the wiki: https://trac.pjsip.org/repos/wiki/BuildingDLL
