### ISSUE TITLE
Genterate a dll 

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2314]
Hello again, I tried to use this method that is there but which of all the projects that pjsip has in general are some 43, and I wanted to know which of all those is where I have to work to be able to generate the dll without using swig , I also wanted to know if there is any tutorial or guide that is a bit more precise since I tried to use the one you passed me and it didn't work, in case it helps you I am using version 2.10 and visual studio 2019. Thanks and sorry for the inconvenience

**Comment by IvyMasterDiego** [comment]
another question, there is a file that is in this link https://trac.pjsip.org/repos/wiki/BuildingDLL#no1
which is ".diff" in which I don't know what to do with it, and I wanted to know what it is for, thank you very much

**Comment by trengginas** [comment]
I tested building .dll here using the above [guide](https://trac.pjsip.org/repos/wiki/BuildingDLL). and it succeeded using VS2015.  On static library, we need to link with libpjroject. Haven't tried if it is the same when using dll though. 
Here are the steps to build libpjproject dll:
1. config_site.h modification
```
#define PJ_DLL  1
#ifdef _LIB
#    define PJ_EXPORTING 1
#endif
```
2. Projects file modification
Change project default (Configuration Properties > General > Configuration Type) to Dynamic Library (.dll). `

To build libpjproject's dll you wouldn't need to use the patch on the doc, as it is already included on the latest version.

**Comment by IvyMasterDiego** [comment]
I did not work that way of compiling since I do not know which project as I said I have to compile it that way or if it is the complete solution.
If you have somewhere out there already the project generated in DLL would be much easier for both you and me.
Thank you.

**Comment by nanangizz** [comment]
Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.
