### ISSUE TITLE
pjsua_call.c  .Incoming Request msg INVITE/cseq=2477 (rdata0x10884bb30) Assertion failed: (pjsua_var.acc_cnt!=0), function pjsua_acc_find_for_incoming, file ../src/pjsua-lib/pjsua_acc.c, line 2990.

### ISSUE THREAD

**Issue by Rushang08** [pjsip/pjproject#2316]
**Describe the bug**
[iOS]Application getting a crash when PJSIP receives a call while disconnecting from asterisks.
 
**To Reproduce**

1. Put disconnect asterisks method on did enter background. 
2. Goes to the background and do call at the time. 

I have a 5-year-old PJSIP version and also I am not able to update new pjsip to my existing project.

**Comment by trengginas** [comment]
Try updating the library. If you still having issue, provide us with the information required from the issue template. To update the library, refer to #2315
