### ISSUE TITLE
[iOS] Opus 1.3 with PJSIP 2.10 Sample project

### ISSUE THREAD

**Issue by ludivinefafournoux** [pjsip/pjproject#2318]
**Describe the bug**
When I want to run the sample project for iOS with opus included I have this error:
`Undefined symbols for architecture arm64:
  "_opus_decode", referenced from:
      _codec_decode in libpjmedia-codec.a(opus.o)
      _codec_recover in libpjmedia-codec.a(opus.o)
  "_opus_repacketizer_out", referenced from:
      _codec_encode in libpjmedia-codec.a(opus.o)
  "_opus_repacketizer_get_nb_frames", referenced from:
      _codec_parse in libpjmedia-codec.a(opus.o)
      _codec_encode in libpjmedia-codec.a(opus.o)
  "_opus_encode", referenced from:
      _codec_encode in libpjmedia-codec.a(opus.o)
  "_opus_encoder_get_size", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
  "_opus_decoder_get_size", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
  "_opus_repacketizer_out_range", referenced from:
      _codec_parse in libpjmedia-codec.a(opus.o)
  "_opus_repacketizer_get_size", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
  "_opus_repacketizer_cat", referenced from:
      _codec_parse in libpjmedia-codec.a(opus.o)
      _codec_encode in libpjmedia-codec.a(opus.o)
  "_opus_encoder_ctl", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
      _codec_modify in libpjmedia-codec.a(opus.o)
  "_opus_encoder_init", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
  "_opus_decoder_init", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
  "_opus_packet_get_nb_samples", referenced from:
      _codec_parse in libpjmedia-codec.a(opus.o)
  "_opus_repacketizer_init", referenced from:
      _codec_open in libpjmedia-codec.a(opus.o)
      _codec_parse in libpjmedia-codec.a(opus.o)
      _codec_encode in libpjmedia-codec.a(opus.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

but I did the step 3 of iOS script and I have this:
`Architectures in the fat file: opus.framework/opus are: x86_64 i386 armv7 armv7s arm64 `

I did `export ARCH="-arch arm64"` before `./configure-iphone` 

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version:  MacOS Catalina with Xcode Version 11.3 (11C29)]
- PJSIP
  - version: 2.10
  - related third party libraries & versions: Opus 1.3

**Smartphone (please also complete the following information):**

- Devices: iPhone 6 iOS 12.4.5

**Comment by trengginas** [comment]
To build with Opus support, refer to https://trac.pjsip.org/repos/ticket/1904.
You need to make sure that you provided the correct opus library path when invoking the `configure-iphone` command.
And make sure that it is usable from `configure-iphone` output.
```
checking for OPUS installations..
Using OPUS prefix... [absolute-path-to]/opus-dev-lib/
checking opus/opus.h usability... yes
checking opus/opus.h presence... yes
checking for opus/opus.h... yes
checking for opus_repacketizer_get_size in -lopus... yes
OPUS library found, OPUS support enabled
```
If you don't see these lines, you have provided the wrong path/wrong opus library.
Check `config.log` for more detail information.

If the library is built successful, to run the sample app you would need to include opus library on the xcode project.

**Comment by ludivinefafournoux** [comment]
Yes I had these lines. But I didn't include opus library on the xcode project, you're right. I'll try.

**Comment by ludivinefafournoux** [comment]
@trengginas Do you know where I have to include opus library ?

**Comment by ludivinefafournoux** [comment]
I added libopus.a to the project.
Now I have `ld: library not found for -lopus`

**Comment by trengginas** [comment]
have you updated the library search path?

**Comment by ludivinefafournoux** [comment]
@trengginas thanks i've added it !
