### ISSUE TITLE
How to play a wav on a conference

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2319]
Hello, I am trying to play a wav in the call using the conferences, and after connecting the ports I do not get options to play the Wav or play file. Is there any way to do this, if you have any way you can pass it to me step by step, I am using the project called "pjsua".

Thank you.

**Comment by trengginas** [comment]
You can use `play-file`  command argument for pjsua to play wav file. This will create a wav player port which afterwards you can connect it to other ports. To check available ports, use in-app command `cl`. To connect the ports, use in-app command `cc`

Note:
Please refrain using label `type:bug` on query like this.

**Comment by IvyMasterDiego** [comment]
Try using, `play-file` and what it does is that it gives me an error when using this command or input in the pjsua console, is there any way to do it or method, within the code?

note: The label is automatic, it doesn't give me the option to remove it, thanks;)

**Comment by nanangizz** [comment]
Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.
