### ISSUE TITLE
pjsua_call_make_call   Check that account is valid

### ISSUE THREAD

**Issue by mingyuejingque** [pjsip/pjproject#2323]
https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua-lib/pjsua_call.c#L799

    /* Check that account is valid */
    PJ_ASSERT_RETURN(acc_id>=0 || acc_id<(int)PJ_ARRAY_SIZE(pjsua_var.acc),
		     PJ_EINVAL);

    /* Check that account is valid */
    PJ_ASSERT_RETURN(acc_id>=0 &&  acc_id<(int)PJ_ARRAY_SIZE(pjsua_var.acc),
		     PJ_EINVAL);

     ||    &&

**Comment by trengginas** [comment]
could you provide the context? The above assertion is to check that the account is valid.

**Comment by trengginas** [comment]
Right, the check should be using "&&" instead of "||". Perhaps you can create a new pull request for this?
