### ISSUE TITLE
How to compile this project with g++ rather than gcc?

### ISSUE THREAD

**Issue by wshhja** [pjsip/pjproject#2326]
**Is your feature request related to a problem? Please describe.**
Compile this project on a Linux like system, no tool-chain

**Describe the solution you'd like**
Is there any configure option can be added to use g++ rather than gcc

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by trengginas** [comment]
you can try using `CC=g++ ./configure` to use g++. Don't think it would work though.
any reason you want to use g++ instead gcc? we use g++ to build c++ code

**Comment by wshhja** [comment]
> you can try using `CC=g++ ./configure` to use g++. Don't think it would work though.
> any reason you want to use g++ instead gcc? we use g++ to build c++ code

Yes, i have tried to using "export CC=g++",but it can not work though.
I use the pjsip by c++,but it report error:undefine reference to `XXXX`. I tried to add extern "C"{} block also,however, it doesn't work.

**Comment by trengginas** [comment]
We use pjsua2 API (C++ code) as a wrapper to pjsua API (C code). You can see the [Makefile](https://github.com/pjsip/pjproject/blob/master/pjsip/build/Makefile) as a reference.

Since you are using C++, consider using pjsua2 API instead?

**Comment by wshhja** [comment]
Thanks for help! Is there any configuration to avoid generating dynamic link?

**Comment by nanangizz** [comment]
Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.
