### ISSUE TITLE
A logo please ? 

### ISSUE THREAD

**Issue by rgarrigue** [pjsip/pjproject#2327]
Hi there

Here's an unusual request I guess : could you please come up with a logo ? A bit like [SIP.js logo](https://www.callstats.io/hubfs/Callstats-August2018/Images/sip-js.png) for example ? Would be easier to include in presentation slides ! 

Best regards,

**Comment by sauwming** [comment]
The image on the top left corner of www.pjsip.org is our logo. The only thing is that it has no text. So you can put the text PJSIP before or after it, like this:
http://google.com/search?q=pjsip+logo
