### ISSUE TITLE
a problem with dtls handshake on pjsip 2.8 with openssl 1.1

### ISSUE THREAD

**Issue by tangxiangpi** [pjsip/pjproject#2333]
![image](https://user-images.githubusercontent.com/18000558/76061242-117c3880-5fbe-11ea-8779-fcc9d4ec1678.png)

**Comment by sauwming** [comment]
PJSIP 2.8 is rather old and there has been a lot of fixes re: DTLS since then. Please update to the latest version 2.10 and let us know if the issue persists.
