### ISSUE TITLE
Add configure flag for what swig modules to build

### ISSUE THREAD

**Issue by alerque** [pjsip/pjproject#2335]
Right now the SWIG makefile makes a big assumption about what the user wants to build:

https://github.com/pjsip/pjproject/blob/68e5350335e5d7d4aeaab7f22cfaf2f5eb8f4bc0/pjsip-apps/src/swig/Makefile#L10

If you build swig at all (on a non-mobile platform), it assumes you _must_ want both python and java modules. This is not always the case. For Arch Linux right now we are only building and packaging the python bindings, and the build cannot be run without patching this Makefile.

The issue is compounded by this make syntax:

https://github.com/pjsip/pjproject/blob/68e5350335e5d7d4aeaab7f22cfaf2f5eb8f4bc0/pjsip-apps/src/swig/Makefile#L25-L30

Having multiple targets with one recipe like this and recursively calling make are both independently problematic, combined I'm pretty sure this is the source of some build inconsistencies. It's hard to figure what the developer expected to have happen here, but I suspect what actually happens is not what was expected and that it ever works at all is a side effect.

**Comment by nanangizz** [comment]
Right, currently for default it assumes things, but you can use `make python` to build only Python module.

**Comment by alerque** [comment]
Thanks @nanangizz. That does in fact work, I was kind of blinded by the layers of hackery in the PKGBUILD I inherited. The recent typo fixes to the make file seem to be enough to make everything work with normal commands and no patches now. When the next release cycle happens I'll cleanup the [stable Arch packaging](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pjproject) to be like the [VCSH version](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pjproject-git) that is much cleaner now.
