### ISSUE TITLE
support oauth2.0?

### ISSUE THREAD

**Issue by tangxiangpi** [pjsip/pjproject#2338]
i found some code use credential.oauth,but no code to set credential.oauth,so do we support oauth2.0? i set register scheme to Bearer,but no effect

**Comment by nanangizz** [comment]
OAuth is currently not supported (yet) and we don't have a plan for this in the short term. The existing OAuth code is only for parsing in the server side (https://github.com/pjsip/pjproject/issues/2148).

We'll take this issue as enhancement request (so adjusted the issue label) and leave it opened for now.

Ref:
https://datatracker.ietf.org/doc/draft-ietf-sipcore-sip-token-authnz/
