### ISSUE TITLE
Win32/x64 compile path for users without access to Visual Studio?

### ISSUE THREAD

**Issue by surfrock66** [pjsip/pjproject#2346]
I am a linux developer that works in a Windows environment.  I am supporting a transition to a sip client which we need customize; the SIP client requires pjproject.  We do not have a Visual Studio license and are attempting to build this using just the msbuild tools.  I want to document the environment I've built, then describe the challenges I'm at to hopefully get a path forward.  A "free" compile toolchain on Windows seems like it would be a benefit overall for the project, hence my verbosity with what I'm doing.  Full Disclosure; I know very little about compiling on/for windows and have no exposure to the visual studio environment, solution format, and include system.

This is a Windows 10 1809 computer.  We have installed the following (some of this was installed for another project and may be unnecessary but I am trying to capture the state as it is right now):
- Windows 8.1 SDK: https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/
- OpenSSL-Win32: https://slproweb.com/products/Win32OpenSSL.html (Installed to C:\Code.OpenSSL\)
- Msbuild command line (from visual studio build tools): https://visualstudio.microsoft.com/downloads/?q=build+tools (Installed to C:\VSBuildTools\)

The following individual components were selected and installed from the "Visual Studio Build Tools 2019 - 16.4.6" component installer:
- .NET Framework 4.6 targeting pack
- .NET Framework 4.6.1 targeting pack
- .NET Framework 4.8 SDK
- NuGet targets and build tasks
- Text Template Transformation
- C++ 2019 Redistributable Update
- C++ CMake tools for Windows
- C++ Universal Windows Platform runtime for v142 build tools
- C++ Windows XP Support for VS 2017 (v141) tools [Deprecated]
- C++/CLI support for v141 build tools (14.16)
- MSVC v140 - VS 2015 C++ build tools (v14.00)
- MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.24)
- Windows Universal CRT SDK
- C++ AddressSanitizer (Experimental)
- Testing tools core features - Build Tools
- C++ Build Tools core features
- C++ core features
- Visual Studio SDK Build Tools Core
- Windwos 10 SDK (10.0.18362.0)
- Windows Universal C Runtime

I added the following to the system PATH (I believe some are redundant):
- C:\VSBuildTools\MSBuild\Current\Bin
- C:\Code.OpenSSL\OpenSSL-Win32\lib
- C:\Code.OpenSSL\OpenSSL-Win32\include
- C:\VSBuildTools\VC\Tools\MSVC\14.24.28314\bin
- C:\VSBuildTools\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64
- C:\VSBuildTools\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x86
- C:\VSBuildTools\VC\Tools\MSVC\14.24.28314\bin\Hostx86\x64
- C:\VSBuildTools\VC\Tools\MSVC\14.24.28314\bin\Hostx86\x86
- C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
- C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt

I created a system environment variable for LIB:
- C:\Code.OpenSSL\OpenSSL-Win32\lib

I created a system environment variable for INCLUDE:
- C:\Code.OpenSSL\OpenSSL-Win32\include

The latest release of pjproject was downloaded and extracted to C:\Code.PJSIP\.  Our config_site.h has only the following line:
`#define PJ_HAS_SSL_SOCK 1`

I then ran the following in Powershell:
```
cd C:\Code.PJSIP\
MSBuild.exe /p:useenv=true /p:Platform=x64 /p:Configuration=Release .\pjproject-vs14.sln 
```

This produced the following error:
```
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 3/13/2020 2:25:20 PM.
Project "C:\Code.PJSIP\pjproject-vs14.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
ValidateProjects:
  The project "python_pjsua" is not selected for building in solution configuration "Release|x64".
  The project "pjsua_cli_wp8_comp" is not selected for building in solution configuration "Release|x64".
  The project "swig_java_pjsua2" is not selected for building in solution configuration "Release|x64".
Project "C:\Code.PJSIP\pjproject-vs14.sln" (1) is building "C:\Code.PJSIP\pjlib\build\pjlib.vcxproj" (2) on node 1 (default targets).
InitializeBuildStatus:
  Touching ".\output\pjlib-x86_64-x64-vc14-Release\pjlib.tlog\unsuccessfulbuild".
ClCompile:
  C:\VSBuildTools\VC\Tools\MSVC\14.24.28314\bin\Hostx64\x64\CL.exe /c /I../include /Zi /nologo /W4 /WX- /sdl- /O2 /D _LIB /D NDEBUG /D WIN64 /D PJ_WIN64=1 /D PJ_M_X86_64=1 /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inlin
  e /Fo".\output\pjlib-x86_64-x64-vc14-Release\\" /Fd".\output\pjlib-x86_64-x64-vc14-Release\pjlib.pdb" /FR".\output\pjlib-x86_64-x64-vc14-Release\\" /Gd /TC /errorReport:queue ..\src\pj\ssl_sock_ossl.c
  ssl_sock_ossl.c
C:\Code.PJSIP\pjlib\include\pj/compat/size_t.h(28): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory [C:\Code.PJSIP\pjlib\build\pjlib.vcxproj]
```

There are more errors below this, but this is the first thing I'm dealing with.  I have the file located here: "C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt" and "C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" which I have included in the path, but the compiler can't find it and I'm not sure why.

I have also attempted the following but get a similar error with the same file: 
`MSBuild.exe /p:useenv=true /p:Platform=win32 /p:Configuration=Release .\pjproject-vs14.sln `

Any help is appreciated.

**Comment by sauwming** [comment]
You can probably try the suggestions recommended in Microsoft forums, which can be found here:
https://www.google.com/search?q=windows+sdk+include+path+stddef

**Comment by sauwming** [comment]
FYI, we also use msbuild on our CI machine in #2344 and it seems to work. So, you can use this as an example as well as the above suggestion, and I'm going to close the issue for now.
