### ISSUE TITLE
Why ALLOW_DELAYED_INITIALIZATION is not enabled by default?

### ISSUE THREAD

**Issue by landsv** [pjsip/pjproject#2347]
**Describe the bug**
With default ALLOW_DELAYED_INITIALIZATION set to 0 iOS OpenGL will return error during creation when app is in the background, for example when answering on a locked phone using CallKit.

**To Reproduce**

1. accept a call on locked iPhone using CallKit
2. press video button
3. app opens with not working video

**Expected behavior**
Video should work when call is accepted in background. 

**Logs/Screenshots**
`ios_opengl_dev.c  .......Failed to initialize iOS OpenGL because we are in background
 vid_port.c  .......Closing OpenGL renderer..
 pjsua_vid.c  .....Stopping video stream..`

**iPhone:**
- iOS 13
- PJSIP
  - version: 2.10

**Comment by sauwming** [comment]
That's because it's not recommended to start video when app is not in foreground. It won't work anyway and will waste clock resources. Your application can enable video as soon as it detects that it's brought into the foreground, or upon the user clicking "video camera" button.

**Comment by landsv** [comment]
incoming video stream is also destroying, how to enable it later when the app is back to foreground?

**Comment by sauwming** [comment]
When in background, app can reject the video call by setting vid_cnt to 0
when answering the call. Then when moving to the fg, it can reinvite with
video enabled.
