### ISSUE TITLE
The error in compiling swig_java_pjsua2 in Microsoft Visual Studio 2015 and Microsoft Visual Studio 2010 is as follows.

### ISSUE THREAD

**Issue by wangwangwawng** [pjsip/pjproject#2349]
The error in compiling swig_java_pjsua2 in Microsoft Visual Studio 2015 and Microsoft Visual Studio 2010 is as follows.
24>------ 已启动生成: 项目: swig_java_pjsua2, 配置: Debug x64 ------
24>  Performing Custom Build Tools
24>  **************************************************************
24>   - Make sure 'swig' and 'javac' locations are in your PATH environment vars.
24>   - Make sure Java SDK header file directories
24>     (e.g: C:\Program Files (x86)\Java\jdk1.7.0_79\include and C:\Program Files (x86)\Java\jdk1.7.0_79\include\win32)
24>     are in your MSVC header search path
24>  **************************************************************
24>  Building pjsua2.dll to ..\lib\
24>  子目录或文件 ..\lib\org\pjsip\pjsua2 已经存在。
24>  Building sample app
24>  javac: 找不到文件: ..\lib\..\test.java
24>  用法: javac <options> <source files>
24>  -help 用于列出可能的选项
24>  javac: 找不到文件: ..\lib\..\sample.java
24>  用法: javac <options> <source files>
24>  -help 用于列出可能的选项
24>  **************************************************************
24>   After the build completed succesfully, try to run the test app, e.g:
24>   java -cp D:\projects\pjproject\pjsip-apps\src\swig\java\output -Djava.library.path="D:\projects\pjproject\pjsip-apps\src\swig\java\output" org.pjsip.pjsua2.app.sample
24>  **************************************************************
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 2。
========== 生成: 成功 23 个，失败 1 个，最新 0 个，跳过 0 个 ==========

**Comment by sauwming** [comment]
I'm sorry, but can you explain what the error is?

**Comment by wangwangwawng** [comment]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe”已退出，代码为 2。
The above is the error message you see

**Comment by sauwming** [comment]
I am not familiar with the error. But perhaps you can take a look at the build on our CI machine for reference in https://github.com/pjsip/pjproject/pull/2344.
