### ISSUE TITLE
Interface for direct media manipuation with PJSUA2

### ISSUE THREAD

**Issue by malarinv** [pjsip/pjproject#2352]
I am looking for a way to manipulate media by capture and playback of audio frames using callbacks with PJSUA2 on python3.7 or higher.

 I looked for it in the Faqs but it seem, it requires working with implementing pjmedia_struct [1] which isn't possible for me as the rest of my pipeline is written in python and there is no high level interface for doing it using pjsua2. I am looking for a high level interface in pjsua2 

There is an old [mailing list thread](http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2013-March/036303.html)  that provides a patch to do. It still works albeit with many bugs. It uses the legacy pjsua-python bindings. The bugs cases unpredictable frame capture failures on some calls and race conditions when handling multiple audio calls, and unreliable in general.

It is a requirement for dynamically responding based on spoken audio.

**Comment by trengginas** [comment]
you should try using ```on_aud_prev_play_frame()```/```on_aud_prev_rec_frame()``` from ```pjsua_media_config```. Note that you may need to add the python interface yourself

**Comment by malarinv** [comment]
@trengginas. Thanks for your response. But the `on_aud_prev_play_frame`  interface doesn't give me any way to distinguish the frame associated with each call during a multiple call scenario i believe. Atleast the `pjmedia_port_get_frame` interface gives me the mixed audio frames of all the stream which can be tracked per call. 

Anyways i'll try to port the media frame callback interface provided by [Tomáš Valenta's](http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2013-March/036303.html) patch to pjsua2.

**Comment by nicolaipre** [comment]
@malarinv Did you manage to patch it to pjsua2? I am looking for the same, although I have been looking for an implementation for the legacy pjsua. 

I'm not sure if it can be helpful to you or not, but I found a different implementation I ported to Python 3: https://github.com/nicolaipre/python3-pjsip-memory-buffer. There are still some bugs in it though. 

As I am not experienced enough in low level programming, I made a new issue/feature request regarding this as well since I am sick of working on this problem and getting nowhere...

**Comment by malarinv** [comment]
@nicolaipre i'haven't yet started working on pjsua2, but i had managed to patch the legacy pjsua python interface to support audio frame callbacks in python3. you can find and example at https://github.com/malarinv/pjproject/blob/py37/pjsip-apps/src/python/samples/audio_cb.py
still yet to rebase against master.

**Comment by nicolaipre** [comment]
@malarinv Thank you for this. I will give it a try. Since the callback is sent in here and only a callback ID is returned: `g_acb_id = lib.create_audio_cb(AudioCB())`, how would one access the captured samples, or put frames?

Also, did you prefer threading using Python or not?

**Comment by kilianbreathnach** [comment]
There is another project which has included the Valenta patch in a python3 interface to pjsua:

https://github.com/ampledata/python3-pjsip/tree/tvalenta-patch-2.8

I am very interested in an implementation of this functionality too. I would love to participate in getting it to a reliable state, though I also don't have much low level experience in handling the kinds of issues you mention. Which of these projects is the best place to start, i.e. closest to being stable for use?

I think it would be great if the audio callback could accept frames of the type found in the [PyAV project](
https://github.com/PyAV-Org/PyAV), which is a set of bindings to libav libraries. It seems this is possible with the Valenta patch if the frame is formatted as a string, though I think that may add some overhead.

**Comment by semwal0808** [comment]
@malarinv  and @nicolaipre hey guys i am working on pjsua2 in android ............... i want to directly put buffer into call stream so that i can send buffer in certain port to the call................can i use above code for it or i have to do something else?

**Comment by malarinv** [comment]
@semwal0808  the interface might have changed see https://github.com/pjsip/pjproject/pull/3569 above
