### ISSUE TITLE
Play a wav on an active call

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2354]
Hello, I am trying to play a wav directly to an already active call and at the moment of doing so the console is showing me this error. Could someone tell me what to do to avoid this error or bug?

`wav_player.c  pjmedia_wav_player_set_eof_cb() is deprecated. Use pjmedia_wav_player_set_eof_cb2() instead.`

**Comment by forca83** [comment]
it is a warning (not bug or error). somewhere in your code you use pjsip-call: pjmedia_wav_player_set_eof_cb()

So, and now the api does recommend you to use a new method for it:
pjmedia_wav_player_set_eof_cb2()

**Comment by IvyMasterDiego** [comment]
But, I am using 2 and it is still giving me that alert or warning, what can I do then.

I imagined that it could be something like this, that I was using a wrong method, but I am using the one that is still giving me the same error.
