### ISSUE TITLE
AKAv2 authentication framework

### ISSUE THREAD

**Issue by Bjoe** [pjsip/pjproject#2358]
In my investigation of #2357 I found this line
https://github.com/pjsip/pjproject/blob/6bbd5ed66a2bd4ea9d35770226a2fd97773001f3/pjsip/src/pjsua-lib/pjsua_acc.c#L2730

I was a little wondering how this can work. It was introduced with this 28f673a1d498fc587045f0c59caf9ab1109a7d0c commit

**Comment by trengginas** [comment]
I think it meant that the code on the block is no operation/will not be executed. Any concern related to this?

**Comment by Bjoe** [comment]
No I didn't get into any trouble, it is only confusing me during my investigation of `PJ_ETOOMANY`.

See this as a "review finding"/hint, because I see a define
https://github.com/pjsip/pjproject/blob/28f673a1d498fc587045f0c59caf9ab1109a7d0c/pjsip/include/pjsip/sip_config.h#L624-L626
and maybe there is a missing `#ifdef PJSIP_HAS_DIGEST_AKA_AUTH` for this?

But anyways I will close this issue if you like.
