### ISSUE TITLE
pjsip_resolve() issue when return more than one resolved address 

### ISSUE THREAD

**Issue by calanor** [pjsip/pjproject#2364]
My dns return more than one resolved IPV4 address ([#2071](https://github.com/pjsip/pjproject/issues/2071) ) and pjsip create a transport with the first IP returned and an arbitrary free source port. This source port its reflected in Via header and in the register contact:

>05:51:59.879    tsx03AF08DC  Sending Request msg REGISTER/cseq=28001 (tdta01049A74) in state Null
05:51:59.879  sip_resolve.c  .DNS resolver not available, target 'sip.testserver.com:0' type=TCP will be resolved with getaddrinfo()
05:51:59.880  sip_resolve.c  .Target 'sip.testserver.com:0' type=TCP resolved to '10.1.64.22:5060' type=TCP (TCP transport)
05:51:59.880  sip_resolve.c  .Target 'sip.testserver.com:0' type=TCP resolved to '10.1.68.22:5060' type=TCP (TCP transport)
05:51:59.880   pjsua_core.c  .TX 670 bytes Request msg REGISTER/cseq=28001 (tdta01049A74) to TCP 10.1.64.22:5060:
REGISTER sip:sip.testserver.com;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 10.112.224.196:52504;rport;branch=z9hG4bKPj5714f949ee50440c90a12265d8fba0ee;alias
Max-Forwards: 70
From: <sip:4444444444@sip.testserver.com>;tag=4cf0a69c2cd64592b0c1e93f72fa6249
To: <sip:4444444444@sip.testserver.com>
Call-ID: 4b4415ed7ad445f1a47407023d027c9f
CSeq: 28001 REGISTER
Supported: outbound, path
Contact: <sip:4444444444@10.112.224.196:52504;transport=TCP;ob>;reg-id=1;+sip.instance="<urn:uuid:00000000-0000-0000-0000-00007a5cb7fa>"
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0

But, sometime sip_resolver return the same IP addresses but with different order and create a new TCP client transport with a different source port. The re-registration uses the new resolved ip:port but not reflected in Contact that shows the old port.

>05:56:54.885    tsx03AF5124  Sending Request msg REGISTER/cseq=28002 (tdta01049A74) in state Null
05:56:54.885  sip_resolve.c  .DNS resolver not available, target 'sip.testserver.com:0' type=TCP will be resolved with getaddrinfo()
05:56:54.889  sip_resolve.c  .Target 'sip.testserver.com:0' type=TCP resolved to '10.1.68.22:5060' type=TCP (TCP transport)
05:56:54.889  sip_resolve.c  .Target 'sip.testserver.com:0' type=TCP resolved to '10.1.64.22:5060' type=TCP (TCP transport)
05:56:54.889   tcpc01088284  .TCP client transport created
05:56:54.889   tcpc01088284  .TCP transport 10.112.224.196:54399 is connecting to 10.1.68.22:5060...
05:56:54.889   pjsua_core.c  .TX 670 bytes Request msg REGISTER/cseq=28002 (tdta01049A74) to TCP 10.1.68.22:5060:
REGISTER sip:sip.testserver.com;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 10.112.224.196:54399;rport;branch=z9hG4bKPj94c8472ecc034483be801530b6d4f787;alias
Max-Forwards: 70
From: <sip:4444444444@sip.testserver.com>;tag=b282b1839f48477f995ade754f3c3924
To: <sip:4444444444@sip.testserver.com>
Call-ID: 4b4415ed7ad445f1a47407023d027c9f
CSeq: 28002 REGISTER
Supported: outbound, path
Contact: <sip:4444444444@10.112.224.196:52504;transport=TCP;ob>;reg-id=1;+sip.instance="<urn:uuid:00000000-0000-0000-0000-00007a5cb7fa>"
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0

Observe that the source TCP port changed from 52504 to 54399 in Via header, but in contact continue sending the old 52504 port.

From this moment, the pjsua client don't receive any INVITE, BYE, etc... because the ip port published its not valid.

getaddrinfo()  return the two IP with the same priority and weight.

Tested with pjsua built-in application in Windows 10 compiled with Visual Studio 2015.

**Comment by sauwming** [comment]
Yes, unfortunately if the order changes, that will happen.
One way to prevent this is by implementing the address resolution in the application layer instead, similar to what's described in https://trac.pjsip.org/repos/wiki/FAQ#dns-failover
