### ISSUE TITLE
Add setting to set Via address (`force_via` similar to `force_contact) to allow FQDN in VIA header

### ISSUE THREAD

**Issue by spape84** [pjsip/pjproject#2367]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to connect Microsoft Teams to pjsip. That is because pjsip doesn't put the FQDN like "ast.me.com" of the Asterisk machine into the VIA and CONTACT header of the SIP dialog. The "address" in those two headers is always replaced by an IP address.

**Describe the solution you'd like**
I'd like to see a variable for an endpoint I could set, which is always inserted into the CONTACT and VIA header instead of the corresponding IP. Some kind of "force_hostname = ast.me.com"

**Describe alternatives you've considered**
I tried to set external_signalling_address and external_media_address to the FQDN needed, but pjsip replaces those with the corresponding IP address. I've already built a pjsip for my asterisk, with a hard coded FQDN in the CONTACT and VIA header, but I think I am not the only one with the problem and I do not understand the pjsip project as much as I'd needed to propose a complete diff or pull-request.

**Additional context**
As there already is a variable to change the user name "contact_user" it seems pretty easy to add this function to pjsip. This is the only thing that prevents Microsoft Teams to connect to pjsip as a SIP trunk. So it would be great, if somebody could work on that... :-)

**Comment by sauwming** [comment]
For Contact headers, you can use `force_contact` setting. Unfortunately, there's no such setting for Via.

**Comment by spape84** [comment]
Exactly. That's why I'm asking for this enhancement. I suspect it could be easy to add this setting.
