### ISSUE TITLE
IMPROVEMENT IN THE VAD

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2371]
Hello I wanted to know if this functionality is available to use what is VOICE ACTIVE DETECTION, I saw that in the code it is but it comes out commented and as it no longer works in these new versions. I am using version 2.10 of PJSIP

What i want to do is play a wav when the vad is activated and according to my console the wav is playing before the vad reactivates or is activated again

So that it is understood a little better, what I am trying to do is that at the moment of saying "hi" or something he immediately plays the wav, and that if no audio is detected the call stays there not on hold but rather as on wait.

**Comment by sauwming** [comment]
Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.
