### ISSUE TITLE
pjsua_destroy() periodic crashed app 

### ISSUE THREAD

**Issue by ovcharenkoa** [pjsip/pjproject#2372]
**Describe the bug**
ios app, use static library pjsua 2.10 (2.9 has crash too)
after call pjsua_destroy() I got a break with "Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)" and records in my console:
...
pjsua_acc.c
.Acc 0: setting registration..
Assertion failed: (mutex), function pj_mutex_lock, file ../src/pj/oc_core_unix.c, line 1270

**To Reproduce**
unknown that need does before call pjsua_destroy().

**Expected behavior**
After call pjsua_destroy() need that never crashed the app.

**Logs/Screenshots**
pjsua_acc.c
.Acc 0: setting registration..
Assertion failed: (mutex), function pj_mutex_lock, file ../src/pj/oc_core_unix.c, line 1270

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: iOS 13.3.1 
- PJSIP
  - version: ...2.10
  - applied patch(es): no
  - `configure` script params: ...
  - `config_site.h` contents: 
#define PJ_CONFIG_IPHONE 1
#define PJ_HAS_IPV6 1
#define PJMEDIA_HAS_OPENH264_CODEC 1
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL_ES 1
#define PJMEDIA_VIDEO_DEV_HAS_IOS_OPENGL 1
#include <OpenGLES/ES3/glext.h>
#define PJSIP_INCLUDE_ALLOW_HDR_IN_DLG 0
#define PJMEDIA_ADD_RTPMAP_FOR_STATIC_PT 0
#define PJMEDIA_ADVERTISE_RTCP 0
#define PJMEDIA_ADD_BANDWIDTH_TIAS_IN_SDP 0
#define PJSIP_ENCODE_SHORT_HNAME 1
#define PJ_LOG_MAX_LEVEL 6
#include <pj/config_site_sample.h>

  - related third party libraries & versions: OpenSSL 1.1.2i

**Smartphone (please also complete the following information):**

- Device: iPhone X

**Additional context**

**Comment by sauwming** [comment]
Can you try with our sample app ipjsua and see if the problem is reproducible there and let us know the steps to do so?

**Comment by ovcharenkoa** [comment]
Unfortunately, I can't.

**Comment by ovcharenkoa** [comment]
Now reproduced after the next steps:
1. establish an outgoing call to any Sip Client (I used Linphoe 4.1.1)
2. activate video from iPhone
3. Relaunch app
4. try to connect to a SIP server (I used KAZOO), hostname doesn't resolve:
22:31:37.171 sip_resolve.c ..DNS resolver not available, target '.. domen name my srrver...' type=UDP will be resolved with getaddrinfo()
22:31:37.172 sip_resolve.c ..Failed to resolve 'iossoftphone.pbx-staging.velvetel.net': gethostbyname() has returned error (PJ_ERESOLVE)
22:31:37.172 tsx0x1080980a8 ..Failed to send Request msg REGISTER/cseq=3127 (tdta0x1080c5aa8)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))
22:31:37.172 tsx0x1080980a8 ..State changed from Null to Terminated, event=TRANSPORT_ERROR
22:31:37.172 pjsua_acc.c ....SIP registration failed, status=502 (gethostbyname() has returned error (PJ_ERESOLVE))
22:31:37.172 pjsua_acc.c ....Scheduling re-registration retry for acc 0 in 0 seconds..
2020-04-07 22:31:37.172702+0700 Velvetel[40766:11021635] dbg: updateUserState ip6 = pjsua_ipv6_use(rawValue: 1)
22:31:37.172 sip_reg.c .Error sending request: gethostbyname() has returned error (PJ_ERESOLVE)
22:31:37.172 pjsua_acc.c .Unable to create/send REGISTER: gethostbyname() has returned error (PJ_ERESOLVE) [status=70018]
5 After it need destroy PjSip library and create again for second attempt. But app got crash from call pjsua_destroy() method. Description see in ticket abbove.

**Comment by sauwming** [comment]
So is this with our sample app or your app?
1. I assume the call is audio-only at the beginning?
2. And here, you are adding video to the audio-only call? Or are you activating native iPhone video?
3. Can you elaborate what you mean by "relaunch app"? Press the Home button to go to the background and then activate the app back to the foreground? or are you restarting PJSIP?
4. The assertion seems unrelated to step 1-3 above. So if you only do this step without step 1-3 and trigger the ERESOLVE error, does the issue happen?

**Comment by ovcharenkoa** [comment]
My app.

**Comment by ovcharenkoa** [comment]
4. My app always prints error for case without crash (logs from lib v 2.9, because in lib v2.10 camera preview not shown in video call, and I rollback to 2.9 version):
11:58:51.410          sip_resolve.c  ..Failed to resolve '....domen name ...': gethostbyname() has returned error (PJ_ERESOLVE)
11:58:51.410         tsx0x120071ea8  ..Failed to send Request msg REGISTER/cseq=52012 (tdta0x1200c1aa8)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))
11:58:51.410         tsx0x120071ea8  ..State changed from Null to Terminated, event=TRANSPORT_ERROR
11:58:51.410            pjsua_acc.c  ....SIP registration failed, status=502 (gethostbyname() has returned error (PJ_ERESOLVE))
11:58:51.410            pjsua_acc.c  ....Scheduling re-registration retry for acc 0 in 1 seconds..
2020-04-08 11:58:51.411287+0700 Velvetel[64942:11218308] dbg: onRegState2
2020-04-08 11:58:51.413901+0700 Velvetel[64942:11218297] dbg: updateUserState ip6 = pjsua_ipv6_use(rawValue: 1)
11:58:51.414              sip_reg.c  .Error sending request: gethostbyname() has returned error (PJ_ERESOLVE)
11:58:51.414            pjsua_acc.c  .Unable to create/send REGISTER: gethostbyname() has returned error (PJ_ERESOLVE) [status=70018]
11:58:51.414        sip_transport.c  Transport udpv60x11fdbebe0 shutting down, force=0
2020-04-08 11:58:51.414892  dbg: updateUserState: disconnected with code = 502
2020-04-08 11:58:51.415594  dbg: registration end with status = 70018
2020-04-08 11:58:51.416120  dbg: try disconnect 1
11:58:51.416           pjsua_core.c  Shutting down, flags=0...
11:58:51.416           pjsua_core.c  PJSUA state changed: RUNNING --> CLOSING
2020-04-08 11:58:51.416555 dbg: disconnectUserPJSIP
2020-04-08 11:58:51.416938 dbg: onTransportState = pjsip_transport_state(rawValue: 2)
2020-04-08 11:58:51.417301 dbg: disconnectUserPJSIP pjsua_transport_close = 0
2020-04-08 11:58:51.418126 dbg: destroy pjsip - 1
2020-04-08 11:58:51.418510 dbg: destroy pool
/* call pjsua_destroy() here (successful) */ 
11:58:51.427           pjsua_call.c  .Hangup all calls..
11:58:51.427          pjsua_media.c  .Call 0: deinitializing media..
11:58:51.427          pjsua_media.c  .Call 1: deinitializing media..
11:58:51.427          pjsua_media.c  .Call 2: deinitializing media..
11:58:51.427          pjsua_media.c  .Call 3: deinitializing media..
11:58:51.427           pjsua_pres.c  .Shutting down presence..
11:58:51.428         tsx0x120071ea8  .Timeout timer event
11:58:51.428         tsx0x120071ea8  ..State changed from Terminated to Destroyed, event=TIMER
11:58:51.428        tdta0x1200c1aa8  ...Destroying txdata Request msg REGISTER/cseq=52012 (tdta0x1200c1aa8)
11:58:51.428         tsx0x120071ea8  .Transaction destroyed!
2020-04-08 11:58:51.428766 dbg: onTransportState = pjsip_transport_state(rawValue: 3)
11:58:51.429       udpv60x11fdbebe0  .SIP UDP transport destroyed
11:58:52.430           pjsua_core.c  .Destroying...
11:58:52.430          pjsua_media.c  .Shutting down media..
11:58:52.558            pjsua_vid.c  ..Destroying video subsystem..
11:58:52.558            pjsua_vid.c  ...Window 0: destroying..
11:58:52.558            pjsua_vid.c  ...Window 1: destroying..
11:58:52.558            pjsua_vid.c  ...Window 2: destroying..
11:58:52.558            pjsua_vid.c  ...Window 3: destroying..
11:58:52.558            pjsua_vid.c  ...Window 4: destroying..
11:58:52.558            pjsua_vid.c  ...Window 5: destroying..
11:58:52.558            pjsua_vid.c  ...Window 6: destroying..
11:58:52.558            pjsua_vid.c  ...Window 7: destroying..
11:58:52.558            pjsua_vid.c  ...Window 8: destroying..
11:58:52.558            pjsua_vid.c  ...Window 9: destroying..
11:58:52.558            pjsua_vid.c  ...Window 10: destroying..
11:58:52.558            pjsua_vid.c  ...Window 11: destroying..
11:58:52.558            pjsua_vid.c  ...Window 12: destroying..
11:58:52.558            pjsua_vid.c  ...Window 13: destroying..
11:58:52.558            pjsua_vid.c  ...Window 14: destroying..
11:58:52.558            pjsua_vid.c  ...Window 15: destroying..
11:58:52.559             vid_conf.c  ...Video conference bridge destroyed
11:58:52.560         sip_endpoint.c  .Destroying endpoint instance..
11:58:52.560      sip_transaction.c  .Stopping transaction layer module
11:58:52.560      sip_transaction.c  .Stopped transaction layer module
11:58:52.560         sip_endpoint.c  .Module "mod-unsolicited-mwi" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-pjsua-options" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-pjsua-im" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-pjsua-pres" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-pjsua" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-stateful-util" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-refer" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-mwi" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-presence" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-evsub" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-invite" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-100rel" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-ua" unregistered
11:58:52.560      sip_transaction.c  .Transaction layer module destroyed
11:58:52.560         sip_endpoint.c  .Module "mod-tsx-layer" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-msg-print" unregistered
11:58:52.560         sip_endpoint.c  .Module "mod-pjsua-log" unregistered
11:58:52.560        sip_transport.c  .Destroying transport manager
11:58:52.561         sip_endpoint.c  .Endpoint 0x123001aa8 destroyed
11:58:52.561           pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
11:58:52.561           pjsua_core.c  .PJSUA destroyed...
2020-04-08 11:58:52.562425 dbg: destroy pjsip - 2
2020-04-08 11:58:52.563601  dbg: connecting name=user_nijdgh password=4gehvks04r4b transport=
11:58:52.563         os_core_unix.c !pjlib 2.9 for POSIX initialized
2020-04-08 11:58:52.564022 dbg: try connect 1
2020-04-08 11:58:52.564445  dbg: createEndpoint pjsip - 1
2020-04-08 11:58:52.564936  dbg: create pjsip - 1
11:58:52.564                  pjlib  .select() I/O Queue created (0x12280b428)
11:58:52.565         sip_endpoint.c  .Module "mod-msg-print" registered
11:58:52.565           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
2020-04-08 11:58:52.565530 dbg: create pjsip - 2
11:58:52.566         sip_endpoint.c  .Module "mod-pjsua-log" registered
11:58:52.566         sip_endpoint.c  .Module "mod-tsx-layer" registered
11:58:52.566         sip_endpoint.c  .Module "mod-stateful-util" registered
11:58:52.566         sip_endpoint.c  .Module "mod-ua" registered
11:58:52.566         sip_endpoint.c  .Module "mod-100rel" registered
11:58:52.566         sip_endpoint.c  .Module "mod-pjsua" registered
11:58:52.566         sip_endpoint.c  .Module "mod-invite" registered
11:58:52.566        coreaudio_dev.c  .. dev_id 0: iPhone IO device  (in=1, out=1) 8000Hz
11:58:52.566        coreaudio_dev.c  ..core audio initialized
11:58:52.567                  pjlib  ..select() I/O Queue created (0x123004028)
11:58:52.567          speex_codec.c  ..Adjusting quality to 5 for uwb
11:58:52.567           conference.c  ..Creating conference bridge with 12 ports
11:58:52.567           Master/sound  ..Using delay buffer with WSOLA.
11:58:52.573            pjsua_vid.c  ..Initializing video subsystem..
11:58:52.573             vid_conf.c  ...Created video conference bridge with 32 ports
11:58:52.573           openh264.cpp  ...OpenH264 codec initialized
11:58:52.573           opengl_dev.c  ...OpenGL device initialized
11:58:52.573           darwin_dev.m  ...Darwin video initialized with 3 devices:
11:58:52.573           darwin_dev.m  ... 0: [Renderer] iOS - UIView
11:58:52.573           darwin_dev.m  ... 1: [Capturer] AVF - Front Camera
11:58:52.573           darwin_dev.m  ... 2: [Capturer] AVF - Back Camera
11:58:52.573         colorbar_dev.c  ...Colorbar video src initialized with 2 device(s):
11:58:52.573         colorbar_dev.c  ... 0: Colorbar generator
11:58:52.573         colorbar_dev.c  ... 1: Colorbar-active
11:58:52.573         sip_endpoint.c  .Module "mod-evsub" registered
11:58:52.573         sip_endpoint.c  .Module "mod-presence" registered
11:58:52.574                evsub.c  .Event pkg "presence" registered by mod-presence
11:58:52.574         sip_endpoint.c  .Module "mod-mwi" registered
11:58:52.574                evsub.c  .Event pkg "message-summary" registered by mod-mwi
11:58:52.574         sip_endpoint.c  .Module "mod-refer" registered
11:58:52.574                evsub.c  .Event pkg "refer" registered by mod-refer
11:58:52.574         sip_endpoint.c  .Module "mod-pjsua-pres" registered
11:58:52.574         sip_endpoint.c  .Module "mod-pjsua-im" registered
11:58:52.574         sip_endpoint.c  .Module "mod-pjsua-options" registered
11:58:52.574           pjsua_core.c  .1 SIP worker threads created
11:58:52.574           pjsua_core.c  .pjsua version 2.9 for iOS-13.3.1/arm-iPhone10,3/iOS-SDK initialized
11:58:52.574           pjsua_core.c  .PJSUA state changed: CREATED --> INIT
11:58:52.574           pjsua_core.c  PJSUA state changed: INIT --> STARTING
11:58:52.574         sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
11:58:52.574           pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
11:58:52.578           pjsua_core.c  SIP UDP socket reachable at 192.168.X.X:XXX
11:58:52.579         udp0x121819500  SIP UDP transport started, published address is 192.168.X.X:XXX
11:58:52.579            pjsua_acc.c  Adding account: id=sip:xxxx@domen.name
11:58:52.579            pjsua_acc.c  .Account sip:xxxx@domen.name added with id 0
2020-04-08 11:58:52.579450  dbg: createTransport pjsip - 2
2020-04-08 11:58:52.579832  dbg: try connect 3
11:58:52.579            pjsua_acc.c  Acc 0: setting registration..
11:58:52.580               endpoint  .Request msg REGISTER/cseq=35129 (tdta0x12201a8a8) created.
11:58:52.580         tsx0x12201c8a8  ..Transaction created for Request msg REGISTER/cseq=35130 (tdta0x12201a8a8)
11:58:52.580         tsx0x12201c8a8  .Sending Request msg REGISTER/cseq=35130 (tdta0x12201a8a8) in state Null
11:58:52.580          sip_resolve.c  ..DNS resolver not available, target 'domen.name:0' type=UDP will be resolved with getaddrinfo()
2020-04-08 11:58:52.580775+0700 Velvetel[64942:11218308] dbg: registration start
11:58:52.582          sip_resolve.c  ..Target 'domen.name:0' type=UDP resolved to 'XX9.1X5.XXX.XXX:XXX' type=UDP (UDP transport)

**Comment by kelf47** [comment]
I have the same problem. Did you figure out how to fix it?

**Comment by olegrussu1** [comment]
i am having same crash, any ideas how to fix?

**Comment by sauwming** [comment]
Since more people experience similar issues, it will be great if you can share with us your steps to reproduce the problem so we can replicate it here. If possible, try the same steps with our sample app ipjsua. If not, you need to help us identify what you do differently in your application which may cause the issue to appear.

**Comment by kelf47** [comment]
1.- UserA calls UserB.
2.- UserA's phone goes to background 
3.- UserA's phone goes to foreground, pjsua_destroy2 is called and then pjsua is initialized again.
4.- UserA calls UserB and the following exception is raised 

`Assertion failed: (mutex), function pj_mutex_lock, file ../src/pj/os_core_unix.c, line 1270. `

**Comment by olegrussu1** [comment]
i am curently integrating video calls , before it i did not have such issue. when i disable video (vid_cnt = 0) , it does not crash.  so steps are just to make video calls several times and it can crash on pjsua_destroy() randomly. testing on ios, using vp8 codec for video

**Comment by sauwming** [comment]
It's not clear that they are the same problems despite hitting the same assertion at the same place. In the original reporter's case, the assertion happens when sending registration, while in the later reports, it seems to happen during making a call and during the destroy() itself (?). The assertion simply means that a mutex has likely been destroyed when it's about to be used. So make sure that you're not using PJSIP whatsoever during the destroy and restart process until it's completed.

If the issue persists, can you please provide the PJSIP log (as text attachment), and the stack trace when the assertion occurred.

**Comment by kelf47** [comment]
Is there any way to assert there isn't any pending lock before restart? It's weird because the exception occurs once the pjsip is restarted and a new call is done, so if there's any lock it must be from the newly created instance. How it can be from the old one?

**Comment by kelf47** [comment]
Sorry I was calling pjsuadestroy 2 times. My fault.

**Comment by olegrussu1** [comment]
by your advice i tried it on pjsua ios sample and did not find this issue in it, so i believe the issue is somewhere in my app. thank you for your help.
