### ISSUE TITLE
VAD Performance

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2373]
Hello, I wanted to know two things how the VAD works in this project because I see that the vad does not work although there are labels for it, but I do not see that it works as a VAD should work so I had the doubt that this portion of code meant:

Mention that this part of the code is in the file `stream.c`

```
// This is no longer needed because each TYPE_NONE frame will
// be converted into zero frame above

/ * If VAD is temporarily disabled during creation, feed zero PCM frame
* to the codec.
* /
if (stream-> vad_enabled! = stream-> codec_param.setting.vad &&
stream-> vad_enabled! = 0 &&
frame-> type == PJMEDIA_FRAME_TYPE_NONE &&
samples_per_frame <= ZERO_PCM_MAX_SIZE)
{
pj_memcpy (& tmp_in_frame, frame, sizeof (pjmedia_frame));
frame = & tmp_in_frame;

tmp_in_frame.buf = NULL;
tmp_in_frame.size = samples_per_frame * 2;
tmp_in_frame.type = PJMEDIA_FRAME_TYPE_AUDIO;
}

```
I know at first it says that this is no longer necessary, but why is this no longer necessary?

**Comment by sauwming** [comment]
Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.

**Comment by IvyMasterDiego** [comment]
I already ask the questions by stackoverflow but no one answers me there, thanks then as no one answers I will continue to send my answers this way, thank you very much
