### ISSUE TITLE
option “--ipv6” in PJUSA doesn`t work

### ISSUE THREAD

**Issue by daxieabc** [pjsip/pjproject#2378]
**Describe the bug**
When i use command like: **./pjsua-x86_64-unknown-linux-gnu --ipv6 --no-tcp --null-audio sip:[fe80::250:56ff:fea1:3e1d]:5070** ,  i can call the ipv6 address  **fe80::250:56ff:fea1:3e1d** correctly.

But when i register on a sip server **sip:[fe80::250:56ff:fea1:2c52]** and use call, it doesn`t work.
Command like:  **./pjsua-x86_64-unknown-linux-gnu --ipv6 --no-tcp --null-audio --id sip:test3@[fe80::250:56ff:fea1:285] --registrar sip:[fe80::250:56ff:fea1:2c52] --username test3 --password test3 sip:[fe80::250:56ff:fea1:2c52]** , 
and i use "m" call **sip:[fe80::250:56ff:fea1:3e1d]:5070** , i find "c=In IP4 xxxx" in content. Also, my sip server returns 403 not relaying.

I dont know how to solve this problem. I’m very grateful if i can get answer.

**Expected behavior**
when i use command like **./pjsua-x86_64-unknown-linux-gnu --ipv6 --no-tcp --null-audio --id sip:test3@[fe80::250:56ff:fea1:285] --registrar sip:[fe80::250:56ff:fea1:2c52] --username test3 --password test3 sip:[fe80::250:56ff:fea1:2c52]** , i can get "c=In IP6 xxxx" in content.

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: [CentOS Linux release 7.6.1810 (Core)]
- PJSIP
  - version: 2.10
  - `config_site.h` contents: #define PJ_HAS_IPV6 1

**Comment by sauwming** [comment]
It's currently unsupported in our sample app, so you need to programmatically add such IPv6 account, bind it to IPv6 transport, and configure the media_use to IPV6 as well.
(https://trac.pjsip.org/repos/wiki/IPv6#appusingpjsua)

**Comment by daxieabc** [comment]
> It's currently unsupported in our sample app (due to #2216, which reverted #2198), so you need to programmatically add such IPv6 account, bind it to IPv6 transport, and configure the media_use to IPV6 as well.
> (https://trac.pjsip.org/repos/wiki/IPv6#appusingpjsua)



> It's currently unsupported in our sample app (due to #2216, which reverted #2198), so you need to programmatically add such IPv6 account, bind it to IPv6 transport, and configure the media_use to IPV6 as well.
> (https://trac.pjsip.org/repos/wiki/IPv6#appusingpjsua)

Thanks a lot!

**Comment by daxieabc** [comment]
> It's currently unsupported in our sample app (due to #2216, which reverted #2198), so you need to programmatically add such IPv6 account, bind it to IPv6 transport, and configure the media_use to IPV6 as well.
> (https://trac.pjsip.org/repos/wiki/IPv6#appusingpjsua)

Thanks a lot!

**Comment by henningw** [comment]
Just a note for future reader of this issue, "--ipv6" works now (at least registration) with 2.12.1 and the included pjsua.
