### ISSUE TITLE
Failed to protect SRTP under FIPS mode (OpenSSL 1.0.2u)

### ISSUE THREAD

**Issue by csguth** [pjsip/pjproject#2390]
**Describe the bug**
Can't hear anything when calling Windows X Macos. Also seen this calling Windows X RHEL or Ubuntu x Macos. It seems to work fine when calling Windows X Windows or Mac x Mac.

**To Reproduce**
1. Make pjsua enter fips mode in the very beginning of main function and link it against a fips capable openssl 1.0.2u
2. Make a Windows X Macos call using srtp enforced (2)
3. You'll see a lot of `Failed to unprotect SRTP, pkt size=72, err=authentication failure`

**Expected behavior**
Normal audio flow

**Desktop:**
- OS, Distribution & Version: MacOS Mojave (XCode 11.0) and Windows 10 (MSVC 2015)
- PJSIP
  - version: 2.10-dev (also fails on 2.8, which is the one I was using before deciding to test 2.10)
  - applied patch(es): 
```diff
diff --git a/pjsip-apps/src/pjsua/main.c b/pjsip-apps/src/pjsua/main.c
index 2baaf829..f125bacc 100644
--- a/pjsip-apps/src/pjsua/main.c
+++ b/pjsip-apps/src/pjsua/main.c
@@ -93,6 +93,18 @@ static void setup_signal_handler(void) {}
 
 int main_func(int argc, char *argv[])
 {
+    int rc, mode;
+
+    mode = FIPS_mode();
+    if(mode == 0)
+    {
+        rc = FIPS_mode_set(1);
+        if(rc == 0)
+        {
+            printf("Failed to set fips mode\n");
+        }
+    }
+    printf("Fips mode = %d\n", FIPS_mode());
     pj_status_t status = PJ_TRUE;
 
     pj_bzero(&cfg, sizeof(cfg));
```

**Comment by sauwming** [comment]
It seems that it's not a very popular usage and only available in a certain old release.

https://wiki.openssl.org/index.php/FIPS_mode()
`
The only current FIPS-capable release of OpenSSL is version 1.0.2. Calling the function from an application linked to OpenSSL versions 1.1.0 or 1.1.1 will always return 0, indicating non-FIPS mode, with an error code of CRYPTO_R_FIPS_MODE_NOT_SUPPORTED (0x0f06d065).
`
