### ISSUE TITLE
Add SIP Call-ID in PJSIP transaction start or even other place

### ISSUE THREAD

**Issue by vit1251** [pjsip/pjproject#2392]
Some call invetigate require Call-ID could you please add in new release instantiate new transaction with Call-ID information please.

**Comment by sauwming** [comment]
There is already a Call-ID header field as described in the [RFC] (https://tools.ietf.org/html/rfc3261#page-37). Can you be more specific as to where else you need it and why?

**Comment by sauwming** [comment]
PJSIP already does that, for example
```
INVITE sip:test@pjsip.org SIP/2.0
Via: SIP/2.0/TCP 19.74.137.243:58474;rport;branch=z9hG4bKPjGxXAx-VWsKerk5LcntWHLXwnIA-pgbX6;alias
Max-Forwards: 70
From: "Ming" <sip:test@pjsip.org>;tag=xEffpP-eg84BpMrkEoxWW2Z7AaBle6ZE
To: sip:test@pjsip.org
Contact: <sip:test@19.74.137.243:58474;transport=TCP;ob>
Call-ID: SEe6H0WZqELUVXC5b9knjS7nKEUs0nlC
```

Will close this issue. For further questions, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.

**Comment by vit1251** [comment]
This approach only works with a full screen of SIP messages in the log files. Usually full mode is enabled only during debugging, but in the production logging in short mode. Let's I show example:

```

```

Currently issue is feature request for extend classic logging message by call-id value.
