### ISSUE TITLE
plans to support H265？

### ISSUE THREAD

**Issue by mingyuejingque** [pjsip/pjproject#2393]
hello everyone：
         Does anyone know if there is any official plan to support h265？

**Comment by sauwming** [comment]
H265 was one of the items in our roadmap discussion, but eventually it wasn't included in  [release 2.11](https://github.com/pjsip/pjproject/milestone/75.) So the earliest is after that, but there's no definite plan yet.

**Comment by ohadts** [comment]
Any news on that?
