### ISSUE TITLE
where is the place that pjsip_rx_data *rdata is integrated into pjsip_inv_session *inv

### ISSUE THREAD

**Issue by bit8bang** [pjsip/pjproject#2397]
I'm always frustrated when the code error appears inside the sip server, and sometimes it is a segfault. Since I am not very clear about the specific code implementation of the entire process, please forgive my ability to understand the code.

The problem I encountered is that I can't reply to the ack of the invite event, because the parameter pjsip_inv_session * inv in the inv structure passed to the send_ack function in the callback function initialized by pjsip_inv_usage_init is null. I can't create pjsip_inv_create_ack and send pjsip_inv_send_msg

Can i know the place that pjsip_rx_data *rdata is integrated into pjsip_inv_session *inv through your guidance.

Thanks.

**Comment by sauwming** [comment]
Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.

**Comment by bit8bang** [comment]
> Currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.

Thanks
