### ISSUE TITLE
UWP pjsip failed to build (pjlib project)

### ISSUE THREAD

**Issue by 0gnj3n** [pjsip/pjproject#2399]
Error (active)	E0028	expression must have a constant value	pjlib	- ip_helper_generic.c	535	
Error (active)	E0028	expression must have a constant value	pjlib	- ip_helper_generic.c	536	

ip_helper_generic.c
```
    if (opt_.af != pj_AF_INET() && opt_.omit_deprecated_ipv6) {
	pj_sockaddr addrs[*p_cnt];                      ---------> error   line 535
	pj_sockaddr deprecatedAddrs[*p_cnt];   -------> erorr   line 536
	unsigned deprecatedCount = *p_cnt;  
```

**To Reproduce**

1. Set UWP platform in \build\vs\pjproject-vs14-api-def.props
2. Try to build pjlib 

**Expected behavior**
Build suceeded

**Desktop/Smartphone (please complete the following information):**

I am using WIN10 64 bit, Visual Studio 17 Version 15.9.21. WIN10 SDK 10.0.17763.0
PJSIP 2.10

config_site.h
```
#define PJMEDIA_HAS_VIDEO	        1
#define PJMEDIA_HAS_LIBYUV		1
#define PJMEDIA_HAS_OPENH264_CODEC	1
#define PJMEDIA_VIDEO_DEV_HAS_SDL       1
#define PJMEDIA_HAS_OPUS_CODEC 		1
#define PJMEDIA_HAS_SILK_CODEC		1
#define PJ_HAS_SSL_SOCK 1
#define PJMEDIA_HAS_WEBRTC_AEC   1
#define PJ_HAS_IPV6  1
#define PJMEDIA_SRTP_HAS_DTLS 1
```

**Comment by cowlinb6** [comment]
Has there been any resolution for this, as I'm having the same issue?

**Comment by 0gnj3n** [comment]
Nothing, 

> 
> 
> Has there been any resolution for this, as I'm having the same issue?

Nothing, I moved on from pjsip.

**Comment by trengginas** [comment]
This patch should fix the issue. Any feedback are welcome.

[patch_ip_helper_generic.zip](https://github.com/pjsip/pjproject/files/5534257/patch_ip_helper_generic.zip)

**Comment by sauwming** [comment]
Closed due to lack of follow up. If the issue persists, try with the latest version or with the patch provided.
