### ISSUE TITLE
Pjsip 2.10 crashes when running pjsua2_demo or making a real call.

### ISSUE THREAD

**Issue by Syirrus** [pjsip/pjproject#2401]
**The Problem**
When attempted to make a call (m) via the URL (i.e. sip:user@domain) or running the pjsua2_demo, I get the following error:
` pjsua-armv6l-unknown-linux-gnueabihf: ../src/pjmedia/conference.c:1895: get_frame: Assertion frame->size == conf->samples_per_frame * conf->bits_per_sample / 8' failed.
Aborted`

**To Reproduce**
1. run pjsua2_dmeo app without parameters or make a call (m) via URL. 
2. Error occurs.

**Expected behavior**
I'm expecting the demo to not crash with this error. When actually trying to call someone I get the same error. 

**Environment**
- Raspian armv6 on dietpi
- PJSIP
  - version: 2.10
  - configured with the following: ./configure && make dep && make && make install
  - `config_site.h` contents: no additions

**Smartphone (please also complete the following information):**
- Device: Raspberry Pi Zero W

**Additional context**
Everything compiled successfully and I have compiled multiple times.  The only reference I see to this issue was posted back in 2012 and the suggested patch has already been implemented in 2.10
http://lists.pjsip.org/pipermail/pjsip_lists.pjsip.org/2012-May/034967.html

The sound card and mic work in command line just fine.  
I'm using https://github.com/respeaker/seeed-voicecard

**Comment by sauwming** [comment]
You probably need to enable resampling or make sure that the sound device and conference's clock rates are the same to avoid resampling.

**Comment by luismartingil** [comment]
+1 Getting same error in a Centos8 box

```
sudo yum install -y alsa-lib alsa-lib-devel alsa-utils binutils boost-devel bzip2 gcc gcc-c++ libevent-devel make openssl-devel nv-codec-headers platform-python-devel python3-gevent
pushd /tmp
VER=2.10
wget -qO- https://github.com/pjsip/pjproject/archive/$VER.tar.gz | tar zxv
cd pjproject-*
export CFLAGS="$CFLAGS -fPIC" && ./configure --disable-libyuv
make dep
make
sudo make install
sudo cp /tmp/pjproject-*/pjsip-apps/bin/pjsua-x86_64-unknown-linux-gnu /usr/bin/pjsua
sudo cp /tmp/pjproject-*/pjsip-apps/bin/pjsystest-x86_64-unknown-linux-gnu /usr/bin/pjsystest
popd
sudo rm -rf /tmp/pjproject-*
```

**Versions**
```
$ make --version
GNU Make 4.2.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gcc --version
gcc (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (GCC) 9.2.1 20191120 (Red Hat 9.2.1-2)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cmake --version
cmake version 3.18.0-rc2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by gusmarucci** [comment]
I caught the same problem. I have googled and I found anything but this guy above saying "just resample it" (What a hack! How to do it mean resample it? What should I do to resample it?)

As far as I didn't find any suitable solution, I made a weird workarrond and belive me: It worked!

In C language, an assertion is when you make a test on a statement. It allows diagnostic information to be written to the standard error file. In other words, it can be used to add diagnostics in your C program.

What did I do? Simple! I just REMOVE the line of assertion's instruction. Worked fine with me.

If you would like to do the same, just go to source and change the conference.c file:

`cd ~/pjproject-2.10/pjmedia/src/pjmedia`

Go to the line 1895 and comment lines 1895 and 1896 just like below:

/* Check that correct size is specified.
    pj_assert(frame->size == conf->samples_per_frame *
                             conf->bits_per_sample / 8);
*/

Go to the line 2235 and do it the same until the line 2237

/* Check for correct size.
    PJ_ASSERT_RETURN( frame->size == conf->samples_per_frame *
                                     conf->bits_per_sample / 8,
                      PJMEDIA_ENCSAMPLESPFRAME);
*/

Once you do it, you must recompile everything and install it again.

Again: Of course it isn't the solution. While the developers don't make a definitive solution, you have an alternative.

**Comment by forca83** [comment]
on release builds, "asserts" shoud be removed outofthebox, by using a define in a header (more infos in pjsip-doc, how to build pjsip for "release purposes")

**Comment by Flole998** [comment]
Same issue here. Disabling those checks causes a super high load average, making the entire system go (almost) completely unresponsive. I prefer the abort in that case ;)

**Comment by engissa** [comment]
I'm facing the same issue on RPI, pjsip 2.1.0 works fine though

`14:33:37.309    pjsua_acc.c  ..Acc 0: Registration sent
14:33:37.309   pjsua_call.c  Making call with acc #0 to sip:inveeno@sip.linphone.org
14:33:37.309    pjsua_aud.c  .Set sound device: capture=-1, playback=-2
14:33:37.309    pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@8000/1/20ms
14:33:37.597     ec0x65c7d8  ...Speex AEC created, clock_rate=8000, channel=1, samples per frame=160, tail length=200 ms, latency=0 ms
myapp: ../src/pjmedia/conference.c:1895: get_frame: Assertion `frame->size == conf->samples_per_frame * conf->bits_per_sample / 8' failed.
14:33:37.598  pjsua_media.c  .Call 0: initializing media..
Aborted`

**Comment by tomas4TW** [comment]
Same, crash on my and demo app too  on ArchLinux x86_x64
`./src/pjmedia/conference.c:1894: get_frame: Assertion `frame->size == conf->samples_per_frame * conf->bits_per_sample / 8' failed.`

**Comment by stijncleynhens** [comment]
Having this same issue. Anybody already got a little further?
