### ISSUE TITLE
Assertion in WebRTC AEC on desktop when clock rate is higher than 16000 Hz

### ISSUE THREAD

**Issue by nanangizz** [pjsip/pjproject#2404]
Assertion line:
```../../webrtc/src/webrtc//modules/audio_processing/aec/aec_core.c:1765: WebRtcAec_ProcessFrames: Assertion `aec->num_bands == num_bands' failed.```

1. run pjsua app with parameter: `--snd-clock-rate=48000`
1. start sound device, e.g: `cc 0 0`
1. assertion occurs!

After investigation, there seem to be a bug in our AEC wrapper, it wrongly passes channel count to `WebRtcAec_Process()`, while it actually expects number of bands (number of bands is not channel count). The WebRTC expects that audio samples splitted into high bands and low band when clock rate is higher than 16000 Hz. The audio band splitting can be done via WebRTC [AudioBuffer](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/modules/audio_processing/audio_buffer.h).

Thanks to Marcus Froeschl, Thomas Hackl, and Arkadiusz Wroński for the reports.

**Comment by sauwming** [comment]
Will not fix this. User is advised to use the new addition WebRTC AEC3 instead.
