### ISSUE TITLE
PJSUA2 pjsua_conf_connect(id, sink.id), throw Invalid value or argument (PJ_EINVAL)

### ISSUE THREAD

**Issue by PLM-Sun** [pjsip/pjproject#2405]
When multiple calls come in at the same time, the calls needs to be connected to the WAV recording file.

The following questions occasionally arise.

System.ApplicationException: C++ pj::Error:
Title:       pjsua_conf_connect(id, sink.id)
Code:        70004
Description: Invalid value or argument (PJ_EINVAL)

Can you help me see why this is? Thank you very much

**Comment by sauwming** [comment]
You can debug it to see which value is invalid.

For further question, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.
