### ISSUE TITLE
Getting  * [pjsua2_wrap.cpp] Error 1 while installing  SWIG for the python

### ISSUE THREAD

**Issue by aditya123456** [pjsip/pjproject#2406]
**Describe the bug**
We I am trying to install SWIG for for python getting below error on Mac
/Applications/Xcode.app/Contents/Developer/usr/bin/make  -C python 
swig -I../../../../pjlib/include -I../../../../pjlib-util/include -I../../../../pjmedia/include -I../../../../pjsip/include -I../../../../pjnath/include -c++  -w312  -python -o pjsua2_wrap.cpp ../pjsua2.i
make[1]: swig: No such file or directory
make[1]: *** [pjsua2_wrap.cpp] Error 1
make: *** [python] Error 2

**To Reproduce**
 Git clone https://github.com/pjsip/pjproject.git
./configure
make dep && make clean && make
sudo make install 
cd pjsip-apps/src/swig
make
make install

**Expected behavior**
this should install the Python SWIG module to user’s site-packages directory
according to below doc
https://www.pjsip.org/docs/book-latest/html/intro_pjsua2.html

**Logs/Screenshots**
make
Applications/Xcode.app/Contents/Developer/usr/bin/make  -C python 
swig -I../../../../pjlib/include -I../../../../pjlib-util/include -I../../../../pjmedia/include -I../../../../pjsip/include -I../../../../pjnath/include -c++  -w312  -python -o pjsua2_wrap.cpp ../pjsua2.i
make[1]: swig: No such file or directory
make[1]: *** [pjsua2_wrap.cpp] Error 1
make: *** [python] Error 2

- OS, Distribution & Version: MacOS 10.15.2

**Comment by sauwming** [comment]
The error is self-explanatory: `swig: No such file or directory`.

Note that for further question, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.
