### ISSUE TITLE
Assertion failed: (neg->state == PJMEDIA_SDP_NEG_STATE_DONE)

### ISSUE THREAD

**Issue by nfranke** [pjsip/pjproject#2413]
**Describe the bug**
When making a call to some toll free numbers using Asterisk 16.9.0, while trying to bridge the call, I PJ crashes on the client side:

Assertion failed: (neg->state == PJMEDIA_SDP_NEG_STATE_DONE), function pjmedia_sdp_neg_modify_local_offer2, file ../src/pjmedia/sdp_neg.c, line 316.

**To Reproduce**

1. run pjsua app and register with asterisk
2. make a single call: "sip:8003161044@myasteriskserver.domain.tld"
3. app crashes while trying to bridge the audio

**Expected behavior**
I would expect the call to complete allow me to talk.

**Desktop/Smartphone (please complete the following information):**

- macOS 10.15.3
- PJSIP version: 2.10
 
aconfigure --prefix=/Users/franke/pjproject --exec-prefix=/Users/franke/pjproject --disable-video --disable-ssl

**Additional context**
If I comment out the PJ_ASSERT_RETURN the call completes successfully.

**Comment by sauwming** [comment]
Can you provide us the log (as file attachment) and the stack trace of the assertion?

**Comment by nfranke** [comment]
`* thread #10, stop reason = signal SIGABRT
  * frame #0: 0x00007fff6efde7fa libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff6f09bbc1 libsystem_pthread.dylib`pthread_kill + 432
    frame #2: 0x00007fff6ef65a1c libsystem_c.dylib`abort + 120
    frame #3: 0x00007fff6ef64cd6 libsystem_c.dylib`__assert_rtn + 314
    frame #4: 0x0000000100164243 pjsua-x86_64-apple-darwin19.3.0`pjmedia_sdp_neg_modify_local_offer2.cold.1 + 35
    frame #5: 0x0000000100091448 pjsua-x86_64-apple-darwin19.3.0`pjmedia_sdp_neg_modify_local_offer2 + 632
    frame #6: 0x000000010003ceb3 pjsua-x86_64-apple-darwin19.3.0`inv_check_sdp_in_incoming_msg + 499
    frame #7: 0x000000010003dde2 pjsua-x86_64-apple-darwin19.3.0`inv_on_state_early + 274
    frame #8: 0x000000010003cc0a pjsua-x86_64-apple-darwin19.3.0`mod_inv_on_tsx_state + 74
    frame #9: 0x0000000100070e69 pjsua-x86_64-apple-darwin19.3.0`pjsip_dlg_on_tsx_state + 153
    frame #10: 0x000000010006b496 pjsua-x86_64-apple-darwin19.3.0`tsx_set_state + 326
    frame #11: 0x000000010006c7b6 pjsua-x86_64-apple-darwin19.3.0`tsx_on_state_proceeding_uac + 742
    frame #12: 0x000000010006b8d3 pjsua-x86_64-apple-darwin19.3.0`pjsip_tsx_recv_msg + 131
    frame #13: 0x000000010006bff8 pjsua-x86_64-apple-darwin19.3.0`mod_tsx_layer_on_rx_response + 152
    frame #14: 0x000000010005ba2e pjsua-x86_64-apple-darwin19.3.0`pjsip_endpt_process_rx_data + 334
    frame #15: 0x000000010005b2ec pjsua-x86_64-apple-darwin19.3.0`endpt_on_rx_msg + 412
    frame #16: 0x00000001000619fc pjsua-x86_64-apple-darwin19.3.0`pjsip_tpmgr_receive_packet + 364
    frame #17: 0x0000000100065e8d pjsua-x86_64-apple-darwin19.3.0`on_data_read + 237
    frame #18: 0x0000000100149746 pjsua-x86_64-apple-darwin19.3.0`ioqueue_on_read_complete + 486
    frame #19: 0x0000000100143fbe pjsua-x86_64-apple-darwin19.3.0`ioqueue_dispatch_read_event + 766
    frame #20: 0x00000001001458cf pjsua-x86_64-apple-darwin19.3.0`pj_ioqueue_poll + 847
    frame #21: 0x000000010005b773 pjsua-x86_64-apple-darwin19.3.0`pjsip_endpt_handle_events2 + 147
    frame #22: 0x000000010002246b pjsua-x86_64-apple-darwin19.3.0`worker_thread + 107
    frame #23: 0x00000001001469c6 pjsua-x86_64-apple-darwin19.3.0`thread_main + 70
    frame #24: 0x00007fff6f09be65 libsystem_pthread.dylib`_pthread_start + 148
    frame #25: 0x00007fff6f09783b libsystem_pthread.dylib`thread_start + 15
[log.txt](https://github.com/pjsip/pjproject/files/4556198/log.txt)
`

**Comment by sauwming** [comment]
This issue happens because we're receiving a response to INVITE in the middle of UPDATE. The RFC doesn't seem to say as to what we should do in such situation, i.e. what happens if in [RFC 3311 call flow example](https://tools.ietf.org/html/rfc3311#section-8), (9) occurs after (5)? So any thought about this is welcome.

The patch below (also contains the SIPP script for reproducing the issue) will choose to ignore such response.
[update-inv-response-issue.txt](https://github.com/pjsip/pjproject/files/4562442/update-inv-response-issue.txt)

**Comment by nfranke** [comment]
That did fix the issue, thanks. Will that be merged into the next release?
