### ISSUE TITLE
SWIG PJSUA2 Call destructor exception

### ISSUE THREAD

**Issue by Truong-Thanh-Quang** [pjsip/pjproject#2416]
When Call object destructor, some time aception occured.

I am using pjsua2 to create call. After call connected, hangup. 
Do the sequence in a C# timer.
About hundred of calls, exception occured in pj_thread_this()

                   Calling pjlib from unknown/external thread. You must "
		   "register external threads with pj_thread_register() "
		   "before calling any pjlib functions.

Environment:
OS: Win10, 1909
VS2019, C# WinForm
pjsip 2.10

![Capture](https://user-images.githubusercontent.com/20198693/80798047-9b670d00-8bcd-11ea-9be6-cc9ae0a9cce1.PNG)

**Comment by sauwming** [comment]
Please refer to the doc here: https://www.pjsip.org/docs/book-latest/html/intro_pjsua2.html?highlight=garbage#problems-with-garbage-collection
