### ISSUE TITLE
swift wrapper

### ISSUE THREAD

**Issue by bmp123** [pjsip/pjproject#2435]
Hello, can anyone help integrate pjsip to swift project... Maybe some examples or wrappers library...

**Comment by sauwming** [comment]
We're planning to do this as well for the [current milestone](https://github.com/pjsip/pjproject/milestone/75). But there's no timeframe yet as to when this will be complete. In the meantime, you can check out another Github project (you can search in Google) of pjsip wrapper which seem to support Swift.
