### ISSUE TITLE
Duration of DTMF digits received via RTP

### ISSUE THREAD

**Issue by maxtruxa** [pjsip/pjproject#2436]
**Is your feature request related to a problem? Please describe.**
When receiving telephone events indicating DTMF digits via RTP, there is currently no way to determine the duration of the event. The DTMF callback of the stream is only called once when the first packet indicating the event is received. [Further packets are filtered](https://github.com/pjsip/pjproject/blob/a35a53b4d9da3fb95aa078170aa38b3eb1f43bbe/pjmedia/src/pjmedia/stream.c#L1716) to prevent duplicate indications of the same event (which is good obviously).
The downside of this behavior is that while the events duration might be continously extended via RTP, the application has no way of knowing that.

**Describe the solution you'd like**
**Solution 1:**
Add a new set of callbacks - similar to `on_dtmf_digit2` - throughout the stack that allows the application to get notified about "DTMF continuations".
**Solution 2:**
Add a flag (compile time or runtime?), indicating that the application expects the DTMF callback to be called everytime a new packet is received via RTP (effectively disabling the filtering done by RTP stream handling).

**Describe alternatives you've considered**
There is no alternative. We need some way to determine the duration of DTMF digits.

**Additional context**
Not really relevant, but:
Our application is more or less a PBX, sitting in front of other legacy (non-VoIP-aware) applications consuming the audio streams. The duration of DTMF digits is significant to those applications. Since the software has no concept of telehone-events, we are re-inserting the DTMF digits back into the audio stream.

I'm absolutely willing to work on this, but I don't want to invest time without knowing that a PR addressing this issue would be accepted.

**Comment by sauwming** [comment]
It sounds like a good idea. Please go ahead.
