### ISSUE TITLE
pjsua2_demo.cpp have no video use demo when prm.opt.videoCount=1?  

### ISSUE THREAD

**Issue by yuexiajiayan** [pjsip/pjproject#2437]
**pjsua2 have no video use api demo in c++ when  prm.opt.videoCount=1 .**
i'm try . but no successful

**Comment by sauwming** [comment]
pjsua2_demo is just a simple sample app. For video, you can use [vidgui](https://trac.pjsip.org/repos/wiki/Video_Users_Guide#vidgui).

For further questions, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.
