### ISSUE TITLE
Network changes : PJSIP_SC_SERVICE_UNAVAILABLE

### ISSUE THREAD

**Issue by steevoo** [pjsip/pjproject#2442]
I'm running application using pjsua2
The problem is that when my network changes from 3G to WIFI and call state  is ringing I got : 

> Software caused connection abort
> swigValue = 503
> swigName = "PJSIP_SC_SERVICE_UNAVAILABLE"

and the recipient didn't receive any notification about the end-of-call
its possible to keep call continue after ip change as its in in-call state  the call didn't disconnect
Thank you

**Comment by sauwming** [comment]
Please have a look at: https://trac.pjsip.org/repos/wiki/IPAddressChange-2.7

For further questions, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.
