### ISSUE TITLE
PJSUA demo code fails

### ISSUE THREAD

**Issue by InnovateAsterisk** [pjsip/pjproject#2448]
I have followed various guides to build PJSIP on a Raspberry Pi, and after some time i ws able to do so. I am using a Raspberry Pi 4B.

My Dependency list was: 
```
# apt-get install gcc make gcc binutils build-essential python-dev ffmpeg libsdl2-dev libssl-dev libopus-dev libopusfile-dev libmp3lame-dev libx264-dev  libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev libspeex-dev libspeexdsp-dev libgsm1-dev libvpx-dev libopencore-amrnb-dev libopencore-amrwb-dev libvo-amrwbenc-dev libglew-dev freeglut3 freeglut3-dev binutils-gold libgl-dev libopenh264-dev portaudio19-dev libv4l-dev
```
After:
```
# ./configure --enable-shared && make dep && make && make install
```

Testing installation:
```
$ ./confsample
07:47:50.348 os_core_unix.c !pjlib 2.10-dev for POSIX initialized
07:47:50.381     alsa_dev.c  Added sound device jack
07:47:50.385     alsa_dev.c  Added sound device pulse
07:47:50.929     alsa_dev.c  Added sound device default
07:47:51.207     alsa_dev.c  Added sound device playback
07:47:51.490     alsa_dev.c  Added sound device capture
07:47:51.767     alsa_dev.c  Added sound device dmixed
07:47:52.050     alsa_dev.c  Added sound device array
07:47:52.056     alsa_dev.c  Added sound device sysdefault:CARD=wm8960soundcard
07:47:52.339     alsa_dev.c  Added sound device dmix:CARD=wm8960soundcard,DEV=0
07:47:52.620     alsa_dev.c  Added sound device dsnoop:CARD=wm8960soundcard,DEV=0
07:47:52.621     alsa_dev.c  Added sound device hw:CARD=wm8960soundcard,DEV=0
07:47:52.623     alsa_dev.c  Added sound device plughw:CARD=wm8960soundcard,DEV=0
07:47:52.624     alsa_dev.c  Added sound device usbstream:CARD=wm8960soundcard
07:47:52.627     alsa_dev.c  ALSA driver found 13 devices
07:47:52.627     alsa_dev.c  ALSA initialized
07:47:52.627          pjlib  select() I/O Queue created (0x144cf64)
07:47:52.627   conference.c  Creating conference bridge with 2 ports
07:47:52.628   Master/sound  Using delay buffer with WSOLA.
07:47:52.628     alsa_dev.c  open_playback: Open playback device 'default'
07:47:52.910     alsa_dev.c  Opened device alsa(default) for playing, sample rate=44100, ch=1, bits=16, period size=5512 frames, latency=250 ms
07:47:52.910     alsa_dev.c  open_capture: Open capture device 'default'
07:47:52.918     alsa_dev.c  Opened device alsa(default) for capture, sample rate=44100, ch=1, bits=16, period size=5512 frames, latency=250 ms
07:47:52.919   conference.c  Sound device successfully created for port 0
07:47:52.919     alsa_dev.c !ca_thread_func(1610): Set thread priority for audio capture thread.
07:47:52.919     alsa_dev.c  Unable to increase thread priority, root access needed.
07:47:52.919   confsample.c !Unable to create WAV writer: Permission denied [code=120013]
confsample: ../src/pjmedia/conference.c:1903: get_frame: Assertion `frame->size == conf->samples_per_frame * conf->bits_per_sample / 8' failed.
Aborted
```

Most of your demo code results in the same.

Also:
```
$ ./vid_codec_test
07:54:18.111 os_core_unix.c !pjlib 2.10-dev for POSIX initialized
07:54:18.144     alsa_dev.c  Added sound device jack
07:54:18.148     alsa_dev.c  Added sound device pulse
07:54:18.685     alsa_dev.c  Added sound device default
07:54:18.957     alsa_dev.c  Added sound device playback
07:54:19.240     alsa_dev.c  Added sound device capture
07:54:19.517     alsa_dev.c  Added sound device dmixed
07:54:19.800     alsa_dev.c  Added sound device array
07:54:19.807     alsa_dev.c  Added sound device sysdefault:CARD=wm8960soundcard
07:54:20.089     alsa_dev.c  Added sound device dmix:CARD=wm8960soundcard,DEV=0
07:54:20.370     alsa_dev.c  Added sound device dsnoop:CARD=wm8960soundcard,DEV=0
07:54:20.371     alsa_dev.c  Added sound device hw:CARD=wm8960soundcard,DEV=0
07:54:20.373     alsa_dev.c  Added sound device plughw:CARD=wm8960soundcard,DEV=0
07:54:20.374     alsa_dev.c  Added sound device usbstream:CARD=wm8960soundcard
07:54:20.377     alsa_dev.c  ALSA driver found 13 devices
07:54:20.377     alsa_dev.c  ALSA initialized
07:54:20.377          pjlib  select() I/O Queue created (0x13bb7ec)
07:54:20.378   openh264.cpp  OpenH264 codec initialized
07:54:20.378          vpx.c  VPX codec initialized
Unable to open ../CiscoVT2people_320x192_12fps.yuv
```

I am building a Python3 project, however when I run your sample code, it crashes on the 
```Account > onRegState() call```

From your sample
```
# Subclass to extend the Account and get notifications etc.
class Account(pj.Account):
  def onRegState(self, prm):
      print "***OnRegState: " + prm.reason

# pjsua2 test function
def pjsua2_test():
  # Create and initialize the library
  ep_cfg = pj.EpConfig()
  ep = pj.Endpoint()
  ep.libCreate()
  ep.libInit(ep_cfg)

  # Create SIP transport. Error handling sample is shown
  sipTpConfig = pj.TransportConfig();
  sipTpConfig.port = 5060;
  ep.transportCreate(pj.PJSIP_TRANSPORT_UDP, sipTpConfig);
  # Start the library
  ep.libStart();

  acfg = pj.AccountConfig();
  acfg.idUri = "sip:test@pjsip.org";
  acfg.regConfig.registrarUri = "sip:pjsip.org";
  cred = pj.AuthCredInfo("digest", "*", "test", 0, "pwtest");
  acfg.sipConfig.authCreds.append( cred );
  # Create the account
  acc = Account();
  acc.create(acfg);
  # Here we don't have anything else to do..
  time.sleep(10);

  # Destroy the library
  ep.libDestroy()

#
# main()
#
if __name__ == "__main__":
  pjsua2_test()
```
If I limit the thread count to 0, it does the same thing.
```
ep_cfg.uaConfig.threadCnt = 0
```

**Expected behaviour**
I would expect your demo code to work.

**Desktop/Smartphone:**

- Raspbian, Buster:
- PJSIP
  - version: 2.10
  - `configure` script params: --enable-shared
  - `config_site.h` contents: 
#define PJMEDIA_AUDIO_DEV_HAS_ALSA      1
#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO 0
#define PJMEDIA_HAS_VIDEO       1
#define PJMEDIA_VIDEO_DEV_SDL_HAS_OPENGL	1
  - related third party libraries & versions:
./configure --enable-shared
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking target system type... armv7l-unknown-linux-gnueabihf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for ranlib... ranlib
checking for ar... ar
checking for pthread_create in -lpthread... yes
checking for puts in -lwsock32... no
checking for puts in -lws2_32... no
checking for puts in -lole32... no
checking for puts in -lwinmm... no
checking for puts in -lsocket... no
checking for puts in -lrt... yes
checking for sin in -lm... yes
checking for uuid_generate in -luuid... yes
checking for uuid_generate in -luuid... (cached) yes
checking for library containing gethostbyname... none required
Setting PJ_M_NAME to armv7l
checking memory alignment... 4 bytes (default)
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
Checking if floating point is disabled... no
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking assert.h usability... yes
checking assert.h presence... yes
checking for assert.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking linux/socket.h usability... yes
checking linux/socket.h presence... yes
checking for linux/socket.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in_systm.h usability... yes
checking netinet/in_systm.h presence... yes
checking for netinet/in_systm.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for netinet/ip.h... yes
checking netinet/tcp.h usability... yes
checking netinet/tcp.h presence... yes
checking for netinet/tcp.h... yes
checking ifaddrs.h usability... yes
checking ifaddrs.h presence... yes
checking for ifaddrs.h... yes
checking for getifaddrs... yes
checking semaphore.h usability... yes
checking semaphore.h presence... yes
checking for semaphore.h... yes
checking setjmp.h usability... yes
checking setjmp.h presence... yes
checking for setjmp.h... yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking stdio.h usability... yes
checking stdio.h presence... yes
checking for stdio.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking for sys/types.h... (cached) yes
checking sys/filio.h usability... no
checking sys/filio.h presence... no
checking for sys/filio.h... no
checking sys/sockio.h usability... no
checking sys/sockio.h presence... no
checking for sys/sockio.h... no
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking time.h usability... yes
checking time.h presence... yes
checking for time.h... yes
checking for unistd.h... (cached) yes
checking winsock.h usability... no
checking winsock.h presence... no
checking for winsock.h... no
checking winsock2.h usability... no
checking winsock2.h presence... no
checking for winsock2.h... no
checking for mswsock.h... no
checking ws2tcpip.h usability... no
checking ws2tcpip.h presence... no
checking for ws2tcpip.h... no
checking uuid/uuid.h usability... yes
checking uuid/uuid.h presence... yes
checking for uuid/uuid.h... yes
checking for net/if.h... yes
checking for localtime_r... yes
Setting PJ_OS_NAME to armv7l-unknown-linux-gnueabihf
Setting PJ_HAS_ERRNO_VAR to 1
Setting PJ_HAS_HIGH_RES_TIMER to 1
Setting PJ_HAS_MALLOC to 1
Setting PJ_NATIVE_STRING_IS_UNICODE to 0
Setting PJ_ATOMIC_VALUE_TYPE to long
checking if inet_aton() is available... yes
checking if inet_pton() is available... yes
checking if inet_ntop() is available... yes
checking if getaddrinfo() is available... yes
checking if sockaddr_in has sin_len member... no
checking if socklen_t is available... yes
checking if IPV6_V6ONLY is available... yes
checking if SO_ERROR is available... yes
checking if pthread_rwlock_t is available... yes
checking if pthread_mutexattr_settype() is available... no
checking if pthread_mutexattr_t has recursive member... no
checking ioqueue backend... select()
Building shared libraries... yes
checking sys/soundcard.h usability... yes
checking sys/soundcard.h presence... yes
checking for sys/soundcard.h... yes
checking linux/soundcard.h usability... yes
checking linux/soundcard.h presence... yes
checking for linux/soundcard.h... yes
checking machine/soundcard.h usability... no
checking machine/soundcard.h presence... no
checking for machine/soundcard.h... no
checking alsa/version.h usability... yes
checking alsa/version.h presence... yes
checking for alsa/version.h... yes
Checking sound device backend... alsa
Checking if small filter is disabled... no
Checking if large filter is disabled... no
Checking if Speex AEC is disabled...no
Checking if G.711 codec is disabled...no
Checking if L16 codec is disabled...no
Checking if GSM codec is disabled...no
Checking if G.722 codec is disabled...no
Checking if G.722.1 codec is disabled...no
Checking if Speex codec is disabled...no
Checking if iLBC codec is disabled...no
Checking if libsamplerate is enabled...no
Building libresample as shared library... no
checking for sdl2-config... /usr/bin/sdl2-config
checking SDL availability... 2.0.9
checking for pkg-config... pkg-config
checking ffmpeg packages...  libavdevice libavformat libavcodec libswscale libavutil
checking for enum AVPixelFormat... yes
checking for v4l2_open in -lv4l2... yes
checking OpenH264 usability... yes
checking VPX usability... yes
Skipping Intel IPP settings (not wanted)
checking for OpenSSL installations..
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for ERR_load_BIO_strings in -lcrypto... yes
checking for SSL_CTX_new in -lssl... yes
OpenSSL library found, SSL support enabled
checking for EVP_aes_128_gcm in -lcrypto... yes
OpenSSL has AES GCM support, SRTP will use OpenSSL
checking for OpenCORE AMR installations..
checking opencore-amrnb/interf_enc.h usability... yes
checking opencore-amrnb/interf_enc.h presence... yes
checking for opencore-amrnb/interf_enc.h... yes
checking for Encoder_Interface_init in -lopencore-amrnb... yes
OpenCORE AMR-NB library found, AMR-NB support enabled
checking vo-amrwbenc/enc_if.h usability... yes
checking vo-amrwbenc/enc_if.h presence... yes
checking for vo-amrwbenc/enc_if.h... yes
checking opencore-amrwb/dec_if.h usability... yes
checking opencore-amrwb/dec_if.h presence... yes
checking for opencore-amrwb/dec_if.h... yes
checking for D_IF_init in -lopencore-amrwb... yes
checking for E_IF_init in -lvo-amrwbenc... yes
OpenCORE AMR-WB library found, AMR-WB support enabled
checking for SILK installations..
checking SKP_Silk_SDK_API.h usability... no
checking SKP_Silk_SDK_API.h presence... no
checking for SKP_Silk_SDK_API.h... no
checking for SKP_Silk_SDK_get_version in -lSKP_SILK_SDK... no
checking for OPUS installations..
checking opus/opus.h usability... yes
checking opus/opus.h presence... yes
checking for opus/opus.h... yes
checking for opus_repacketizer_get_size in -lopus... yes
OPUS library found, OPUS support enabled
checking bcg729 usability... no
Checking if libyuv is disabled...no
Checking if libwebrtc is disabled...no
checking if select() needs correct nfds... no (default)
** Decided that select() doesn't need correct nfds (please check)
checking if pj_thread_create() should enforce stack size... no (default)
checking if pj_thread_create() should allocate stack... no (default)
** Setting non-blocking recv() retval to EAGAIN (please check)
** Setting non-blocking connect() retval to EINPROGRESS (please check)
aconfigure: creating ./config.status
config.status: creating build.mak
config.status: creating build/os-auto.mak
config.status: creating build/cc-auto.mak
config.status: creating pjlib/build/os-auto.mak
config.status: creating pjlib-util/build/os-auto.mak
config.status: creating pjmedia/build/os-auto.mak
config.status: creating pjsip/build/os-auto.mak
config.status: creating third_party/build/os-auto.mak
config.status: creating pjlib/include/pj/compat/os_auto.h
config.status: pjlib/include/pj/compat/os_auto.h is unchanged
config.status: creating pjlib/include/pj/compat/m_auto.h
config.status: pjlib/include/pj/compat/m_auto.h is unchanged
config.status: creating pjmedia/include/pjmedia/config_auto.h
config.status: pjmedia/include/pjmedia/config_auto.h is unchanged
config.status: creating pjmedia/include/pjmedia-codec/config_auto.h
config.status: pjmedia/include/pjmedia-codec/config_auto.h is unchanged
config.status: creating pjsip/include/pjsip/sip_autoconf.h
config.status: pjsip/include/pjsip/sip_autoconf.h is unchanged

- Device: Raspberry Pi 4B

**Additional context**
I am able to make and use pjsua with python2.7 with the sample code, and register, and make an audio call correctly... However I noticed your documentation said I'm not supposed to use PJSUA and must use PJSUA2, (with python 3.7), but like this I get a segfault/crash, and the code appears very unstable. Also I can't seem to establish a video call... there is limited to no documentation on this topic.

**Comment by InnovateAsterisk** [comment]
I have an update on this: the selection of the audio card was important. You need to start the app with the correct device id. Then you don't get this issue.

Now for the video... there isn't clear parameters documented for the video parameters. 
https://www.pjsip.org/pjsua.htm
This document appears outdated.

**Comment by InnovateAsterisk** [comment]
Video was problematic because OpenH264 was problematic/incompatible/broken.

**Comment by boudaliachanez** [comment]
@InnovateAsterisk excuse me, we are trying to make to pjsip on a  Raspberry Pi 4 and saw you were able to make it.
Our issue is with the make step, once we run it the prompt retrun this error:
_pjsua.c4433:1: error decalartion specifiers before 'init_pjsua'
4433 | init_pjsua(void)
Any help is much appreciated, Thanks in advance.

**Comment by boudaliachanez** [comment]
We've resolved the isssue.
