### ISSUE TITLE
Python2/3 Video Call example

### ISSUE THREAD

**Issue by InnovateAsterisk** [pjsip/pjproject#2449]
**Is your feature request related to a problem? Please describe.**
Samples are very few, and mostly in C++

**Describe the solution you'd like**
I am able to make and receive video calls with the pjsip-apps/bin/pjsua application, but my platform is python (2.7/3.7). Your sample: pjsip-apps/src/pygui/application.py works a treat too, but this application doesn't support video.

**Describe alternatives you've considered**
My only alternate is to use c++, but I don't know c++

**Additional context**
Please!

**Comment by ahmedFarouk2020** [comment]
Is it even possible to use video calls on python! After building, I tested the pjsua-x86_64-w64-mingw32.exe and video calls works fine but after creating the python extension using swig I still cannot use video calls and error message "Assertion failed: call->opt.vid_cnt == 0, file ../src/pjsua-lib/pjsua_call.c, line 682" appears after setting pj.CallOpParam.videoCount to 1.

I used pjsip doc for building using MSYS2.

I am waiting for responses
Thanks
