### ISSUE TITLE
trying to create a playlist

### ISSUE THREAD

**Issue by IvyMasterDiego** [pjsip/pjproject#2450]
**Describe the bug**
Hello, I am trying to use the playlist methods and sometimes they send the duplicate audio, and I would also like to know if they have any detailed example of the same thanks

**Comment by sauwming** [comment]
What sort of duplicate audio are you experiencing? Is it in the beginning of the file, randomly in the middle, at the end, or in between files? How long is the duplicated audio?

**Comment by IvyMasterDiego** [comment]
I already solved it thank you very much
