### ISSUE TITLE
PJSIP 2.10 - PyGui Crashes on Audio Call

### ISSUE THREAD

**Issue by another2020githubuser** [pjsip/pjproject#2455]
**Describe the bug**
Log Window says:
python3: ../src/pjmedia/conference.c:1895: get_frame: Assertion `frame->size == conf->samples_per_frame * conf->bits_per_sample / 8' failed.

**To Reproduce**
Start PyGui by running python3 application.py.  Show Log Window.
Add an account.
Add a buddy to that Account.
Right click on buddy and choose "Audio Call"
PyGui Crashes.  Log window displays text above.

**Expected behavior**
Audio call proceeds.

**Logs/Screenshots**
Here is the log window from PyGui
07:52:08.483   pjsua_pres.c  Adding buddy: [redacted]
07:52:08.485   pjsua_pres.c  .Buddy 1 added.
07:52:08.486   pjsua_pres.c  ..Buddy 1: updating presence..
07:52:08.633   pjsua_call.c  Making call with acc #0 to [redacted]
07:52:08.634    pjsua_aud.c  .Set sound device: capture=-1, playback=-2
07:52:08.635    pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@16000/1/20ms
07:52:08.635     alsa_dev.c  ...open_playback: Open playback device 'sysdefault:CARD=Headset'
07:52:08.650     alsa_dev.c  ...Opened device alsa(sysdefault:CARD=Headset) for playing, sample rate=16000, ch=1, bits=16, period size=341 frames, latency=149 ms
07:52:08.651     alsa_dev.c  ...open_capture: Open capture device 'sysdefault:CARD=Headset'
07:52:08.666     alsa_dev.c  ...Opened device alsa(sysdefault:CARD=Headset) for capture, sample rate=16000, ch=1, bits=16, period size=341 frames, latency=106 ms
07:52:08.667    ec0x1cfcf60  ...Creating Speex AEC
07:52:08.669    ec0x1cfcf60  ...Speex AEC created, clock_rate=16000, channel=1, samples per frame=320, tail length=200 ms, latency=0 ms
07:52:08.670   dlg0x1d9f874 !.UAC dialog created
python3: ../src/pjmedia/conference.c:1895: get_frame: Assertion `frame->size == conf->samples_per_frame * conf->bits_per_sample / 8' failed.
Aborted

**Desktop/Smartphone (please complete the following information):**
PyGui app as downloaded from GitHub
Reproduced on a Dell 6700 (Ubuntu 18.04) and a Raspberry Pi 3 (latest Raspbian)
- PJSIP
  - version: 2.10
  - applied patch(es): None
  - `configure` script params: ./configure --disable-video --disable-ffmpeg --disable-v4l2 -disable-libwebrtc
  - `config_site.h` contents: n/a
  - related third party libraries & versions: [e.g: OpenSSL 1.1.1b]

**Smartphone (please also complete the following information):**
n/a
- Device: [e.g. iPhone 6]
n/a
**Additional context**

**Comment by another2020githubuser** [comment]
Correction:
Reproduced on a Raspberry Pi 3 (latest Raspbian) ONLY.

**Comment by trengginas** [comment]
Cannot reproduce using 2.13.  Test using Raspberry Pi 4.
