### ISSUE TITLE
crash in pj_atomic_dec_and_get

### ISSUE THREAD

**Issue by tangxiangpi** [pjsip/pjproject#2456]
![image](https://user-images.githubusercontent.com/18000558/84109776-feae4f80-aa55-11ea-9db5-394447841ff1.png)
pjsip2.9
did nothing ,just open app 

#00 pc 001b480e /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pj_atomic_dec_and_get+3) [armeabi-v7a]
--
2 #01 pc 0012e105 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (regc_tsx_callback+824) [armeabi-v7a]
3 #02 pc 00144bd3 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (tsx_set_state+190) [armeabi-v7a]
4 #03 pc 001452e9 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (tsx_on_state_proceeding_uac+312) [armeabi-v7a]
5 #04 pc 00145469 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (tsx_on_state_calling+204) [armeabi-v7a]
6 #05 pc 0014677b /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pjsip_tsx_recv_msg+82) [armeabi-v7a]
7 #06 pc 001467f3 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (mod_tsx_layer_on_rx_response+90) [armeabi-v7a]
8 #07 pc 0013ae95 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pjsip_endpt_process_rx_data+232) [armeabi-v7a]
9 #08 pc 0013afb7 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (endpt_on_rx_msg+258) [armeabi-v7a]
10 #09 pc 0013e2f5 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pjsip_tpmgr_receive_packet+792) [armeabi-v7a]
11 #10 pc 001415a5 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (on_data_read+72) [armeabi-v7a]
12 #11 pc 001bb6d7 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (asock_on_data_read+366) [armeabi-v7a]
13 #12 pc 001b5bdb /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (ioqueue_on_read_complete+94) [armeabi-v7a]
14 #13 pc 001b3255 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (ioqueue_dispatch_read_event+292) [armeabi-v7a]
15 #14 pc 001b3e4f /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pj_ioqueue_poll+454) [armeabi-v7a]
16 #15 pc 0013ad01 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pjsip_endpt_handle_events2+90) [armeabi-v7a]
17 #16 pc 0011aa89 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (pjsua_handle_events+32) [armeabi-v7a]
18 #17 pc 0011aaad /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (worker_thread+16) [armeabi-v7a]
19 #18 pc 001b4795 /data/app/com.mye152--zDlYryj38nK8PbNwNrmSQ==/lib/arm/libvoip.so (thread_main+40) [armeabi-v7a]
20 #19 pc 0009c1b7 /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20) [armeabi-v7a]
21 #20 pc 00055657 /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30) [armeabi-v7a]

**Comment by tangxiangpi** [comment]
#62103 SIGSEGV(SEGV_MAPERR)
#00 pc 001b480e /data/app/com.mye152-HBEU9IvHQ_UPX7EifVp8_w==/lib/arm/libvoip.so (pj_atomic_dec_and_get+3) [arm

**Comment by sauwming** [comment]
Even though the user may not do anything yet, but your application definitely has done something. In this case, from the stack trace, it seems to have initiated a registration and received a response. You can check PJSIP log to see more details (if you need to put the log in this issue, please upload it as a text attachment).

Also it's helpful to test with our sample app for the same scenario (i.e. registration flow) and compare the difference.

**Comment by tangxiangpi** [comment]
[](url)
[core_20200609.xlog.log](https://github.com/pjsip/pjproject/files/4750550/core_20200609.xlog.log)
i open app at 13:10:14.414 and crash at 13:10:12.011,and i reopen app at 13:10:14.414

**Comment by tangxiangpi** [comment]
> Even though the user may not do anything yet, but your application definitely has done something. In this case, from the stack trace, it seems to have initiated a registration and received a response. You can check PJSIP log to see more details (if you need to put the log in this issue, please upload it as a text attachment).
> 
> Also it's helpful to test with our sample app for the same scenario (i.e. registration flow) and compare the difference.

see  my answer please

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
