### ISSUE TITLE
Imposible to create `pjmedia_stereo_port` with options

### ISSUE THREAD

**Issue by goro-gh** [pjsip/pjproject#2460]
If StereoPort with `PJMEDIA_STEREO_DONT_DESTROY_DN` option is created, `pjmedia_convert_channel_1ton()` asserts with

```
../include/pjmedia/stereo.h:132: pjmedia_convert_channel_1ton: Assertion `options == 0' failed.
```

**Comment by trengginas** [comment]
> PJMEDIA_STEREO_DONT_DESTROY_DN

Thanks for the report.
Could you test the patch?

[patch_stereo_port.txt](https://github.com/pjsip/pjproject/files/4809716/patch_stereo_port.txt)
