### ISSUE TITLE
Publish Python binding wheel on PyPI

### ISSUE THREAD

**Issue by miso-belica** [pjsip/pjproject#2461]
Hi, thanks for the library. I am the Python developer and recently started using your library. After some trial&error and reading your documentation I got the library working. But it was not easy to get started and also if I create the real app there is not a clear way how to state the pjsua2 dependency. There are more people struggling with this as you can see for example in [StackOverflow: how to install pjsua2](https://stackoverflow.com/questions/53736284/how-to-install-pjsua2-packages-for-python). It would be nice to have the standard way to depend on the library. Thanks for considering this.

**Is your feature request related to a problem? Please describe.**
It's not easy to specify Python dependency on pjsua2 in `setup.py`/`requirements.txt` file.

**Describe the solution you'd like**
Please, create and publish the [wheel package](https://pythonwheels.com/) on PyPI for all supported platforms. GitHub has CI action template for publishing to PyPI.

**Describe alternatives you've considered**
I have a Docker file building/installing the library, but the dependency is not visible, I need an extra compiler and other tools to build it (on Windows this is a tough thing) and it's not easy to upgrade it. GitHub has dependabot that would automatically upgrade the dependency if the new version is published. Also, Docker has its own problem with soundcard detection.

**Additional context**
Here is my Dockerfile.

```dockerfile
FROM python:3.8.3

WORKDIR /app
RUN apt update && apt install -y vim swig default-jdk libasound2-dev alsa-utils dkms pulseaudio

RUN curl -L https://github.com/pjsip/pjproject/archive/2.10.zip -o f.zip && unzip -q f.zip && rm f.zip
COPY config_site.h "pjproject-2.10/pjlib/include/pj/config_site.h"
RUN cd "pjproject-2.10/" && ./configure --enable-shared && make dep all install && ldconfig
RUN cd "pjproject-2.10/pjsip-apps/src/swig" && make && make install

WORKDIR /app/src
```

**Comment by sauwming** [comment]
It's now available in #3225!
