### ISSUE TITLE
G729 inclusion OSX

### ISSUE THREAD

**Issue by gbfarah** [pjsip/pjproject#2465]
Hi All,

I have two issues that I would appreciate feedback on. The end game is I want to get G729 working with PJSIP  2.10 on the latest version of the MAC (I am not fussed with which 729 library to use)

Problem 1 

I was previously using an older version of PJSIP (2.1.0) built on OSX Mavericks and successfully built this to use 64bit IPP libraries at the time with G729.  When trying to build the latest pjsip version (2.10) with the same IPP libraries I am hitting  the link issue below as per https://trac.pjsip.org/repos/ticket/2029 . What I found peculiar is that older PJSIP 2.1.0 successfully builds on the latest version of the MAC with the libraries "as is" with no issues. 

As per the above URL  states that the link issue is because the IPP libraries were built using IPP compiler . It does beg the question why the previous version of PJSIP doesn't have this issue while the latest does. I would really like to avoid recompiling IPP libraries as the process is time consuming and filled with trial and error. To build this previously took a couple of weeks of trial and error with little support from Intel on the matter.... 

Link error:
Undefined symbols:
  "_USC_G728_Fxns", referenced from:
      _ipp_codec in libpjmedia-codec-x86-64-apple-darwin9.8.0.a(ipp_codecs.o)
  "_USC_G729AFP_Fxns", referenced from:
      _ipp_codec in libpjmedia-codec-x86-64-apple-darwin9.8.0.a(ipp_codecs.o)
  "_USC_AMRWB_Fxns", referenced from:
      _ipp_codec in libpjmedia-codec-x86-64-apple-darwin9.8.0.a(ipp_codecs.o)

Problem 2

As an alternative to the above I thought to try and build  bcg729 .. I have successfully built it using CMAKE  and followed instruction as per https://trac.pjsip.org/repos/ticket/2029 on the OSX machine (and verifed that it is a 64 bit library). When setting up pjsip ./configure it doesn't recognize the library (bcg has built both a static .a file and dylib)... When forcing the PJSIP make to look in the appropriate location and enabling BCG729 in config_site.h, everything builds but linker fails 

I am hitting the issue that PJSIP does not recognize the library with error below       

Undefined symbols for architecture x86_64:
"_pjmedia_codec_bcg729_init", referenced from:
_pjmedia_codec_register_audio_codecs in libpjmedia-codec-x86_64-apple-darwin18.5.0(audio_codecs.o)
ld: symbol(s) not found for architecture x86_64

**Comment by nanangizz** [comment]
We deprecated IPP support (cannot really remember the reason, perhaps IPP dropped the audio codecs in recent versions?).

Re: link error, the missing symbol should be defined in `pjmedia/src/pjmedia-codec/bcg729.c`, perhaps you'd need to rebuild (make clean  + re-configure). If issue persists, please try to check `pjmedia/build/os-auto.mak`.

**Comment by nanangizz** [comment]
Currently issues are for bug report only. Please use other means (mailing list or StackOverflow) for further questions.

**Comment by gbfarah** [comment]
Thanks for the followup.  With respect to deprecation of the IPP I couldn't find any documentation or reference to it being deprecated. It is a little strange given the codec (and its build) hasn't changed. I can successfully build PJSIP2.1.0 with the codec as built. Its a shame that this support wasn't simply carried forward.

I will try your suggestion in relation bcg729. Thanks again

**Comment by gbfarah** [comment]
Hi Nanang,

I thought  I would give some feedback with reference to https://trac.pjsip.org/repos/ticket/2029 . It appears that on MAC using the --with-bcg729 or --with-bcg option (the reference does both) actually has no effect with both failing to find bcg729. It was found that run 'make install' for bcg729 which place appropriate libraries in /usr/local/lib meant the standard ./configure without options found the libraries
