### ISSUE TITLE
callee not audible / muted during call

### ISSUE THREAD

**Issue by imanpeeman** [pjsip/pjproject#2473]
**Describe the bug**
2 persons (A and B) are calling and talking at the same time or just after each other. After a few seconds, B isn't able to hear A, A has to 'shout' to get their voice audible again. 

see attached wireshark where the issue occurs in the beginning. the audio is also on a low volume level on the network.

I've already tried to disable the SIMPLE_AGC in conference.c, also put the minlevel to 128, but without any effect. Putting the loglevel to 6 didn't provide any reasonable log output. Checking all the issues fixed in 2.8, 2,9 and 2.10 I couldn't find any related issue. 

**Expected behavior**
The voice of the callee is not 'muted' based on my voice, but always loud and clear. When using same sipaccount and test with e.g. Linphone this behavior doesn't occur.

**Logs/Screenshots**
wireshark trace:
[callNoAudibleCallee.zip](https://github.com/pjsip/pjproject/files/4837388/callNoAudibleCallee.zip)

**Smartphone**

- OS, Android 8/9/10 (e.g. samsung xCover4 (s))
- PJSIP
  - version: 2.7.1 / React native
  -   - `configure` script params: ...
  - `config_site.h` contents: ...
  - related third party libraries & versions: 
SWIG swig-3.0.7
OPENSSL openssl-1.0.2g
OPENH264 v1.7.0

**Smartphone (please also complete the following information):**

- Device: Samsung xCover 4(s)

**Additional context**
used from the react-native-pjsip package

**Comment by sauwming** [comment]
- Try to disable any audio processing, such as EC, VAD, to find out which component causes the voice reduction.
- Loopback the local audio, just to make sure that the issue doesn't already come from the input signal itself.
- Try with different codecs, to make sure that it's not a codec specific issue.

**Comment by Sjmao** [comment]
我在小米手机上 只能听到对方的声音 ，我说的话 他们听不见 ，打开免提 才可以让他们听见

**Comment by Sjmao** [comment]
是 媒体管理模式的问题 我的问题已解决 谢谢

**Comment by imanpeeman** [comment]
It turns out that it is related to the EC mode. We've changed to webRTC + Noise supression = mode 131. This solves our issue.
