### ISSUE TITLE
pjmedia_sdp_session exposed to modification by sip session timer callback because of missing clone operation

### ISSUE THREAD

**Issue by mneuhauser** [pjsip/pjproject#2475]
Sorry, I do not know how to reproduce this with pjsip only - the problem was discovered with Asterisk: https://issues.asterisk.org/jira/browse/ASTERISK-28973

The sip session timer callback timer_cb() in pjsip/src/pjsip-ua/sip_timer.c retrieves a pjmedia_sdp_session using pjmedia_sdp_neg_get_neg_local() and stores it in tdata->msg->body. This leads to a problem when the pjmedia_sdp_session is modfied by some dialog module (correct terminology?) using the tdata pool (Asterisk NAT fixup of IP address): the next time the same pjmedia_sdp_session is used (i.e., on the 2nd refresh), the  modified data is corrupted because the tdata pool was released (packet was transmitted) and was reused and changed.
Comparing the code in timer_cb():
```c
    if (status == PJ_SUCCESS) {
        status = pjsip_create_sdp_body(tdata->pool, 
                                (pjmedia_sdp_session*)offer, &body);
        tdata->msg->body = body;
    }
```
with code in pjsip/src/pjsip-ua/sip_inv.c::pjsip_inv_update():
```c
    /* Attach SDP body */
    if (offer) {
        sdp_copy = pjmedia_sdp_session_clone(tdata->pool, offer);
        pjsip_create_sdp_body(tdata->pool, sdp_copy, &tdata->msg->body);
    }
```
led me to the change proposed in https://issues.asterisk.org/jira/browse/ASTERISK-28973, i.e., clone the sdp in timer_cb() using the tdata->pool to isolate from changes:
```c
    if (status == PJ_SUCCESS) {
        status = pjsip_create_sdp_body(tdata->pool, 
                                pjmedia_sdp_session_clone(tdata->pool, offer), &body);
        tdata->msg->body = body;
    }
```

**Comment by sauwming** [comment]
May I create a Pull Request for this, or would you want to do it yourself?

**Comment by mneuhauser** [comment]
Yes, please do it.
