### ISSUE TITLE
register in diffrent threads may cause  regc_cb function not called

### ISSUE THREAD

**Issue by tangxiangpi** [pjsip/pjproject#2479]
![QQ截图20200705153613](https://user-images.githubusercontent.com/18000558/86527980-a2b0dc80-bed6-11ea-8e45-633194017f79.png)

you can find log from 09:11:12.425

**Comment by tangxiangpi** [comment]
[com.chinamye.iOS_20200705.xlog.log](https://github.com/pjsip/pjproject/files/4874570/com.chinamye.iOS_20200705.xlog.log)

**Comment by tangxiangpi** [comment]
I know the reason. For example, A and B register SIP in different threads. A registers first and then responds to 401. After 401(regc->has_tsx will be set to false), B starts to register. The registration request of B may be dropped by pjsip cancle (SIP registration error: object is busy), and the cancle is in regc at the same time regc_cb will set acc->regc of callback app to null, although A registered successfully later，and then app will not know the registration status of SIP

**Comment by sauwming** [comment]
Sorry for not responding earlier. As the issue may no longer be valid now,
please try with the latest version, and reopen if the issue persists.
