### ISSUE TITLE
make fails if dir has a space in name

### ISSUE THREAD

**Issue by maxhallhatesm3** [pjsip/pjproject#2480]
**Describe the bug**

**To Reproduce**

1. clone repo into dir that has a space character somewhere in its abs path.

**Expected behavior**
Make suceeds.

**Logs/Screenshots**
```
jd@jd pjproject % make dep && make clean && make
build.mak:2: /Users/jd/w/dead: No such file or directory
build.mak:2: beef/tools/silk/pjproject/version.mak: No such file or directory
make: *** No rule to make target `beef/tools/silk/pjproject/version.mak'.  Stop.
jd@jd pjproject %        
```

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: macOS Catalina 
- PJSIP
  - version: 10.15.4
**Additional context**
I am changing the path for build just wanted to give you heads.

**Comment by trengginas** [comment]
Thanks for the report. Can confirm that this is a bug. The output of ```pwd``` from aconfigure script is not escaped
