### ISSUE TITLE
Cross Compilation Fails

### ISSUE THREAD

**Issue by M-SydAhmed** [pjsip/pjproject#2483]
**Describe the bug**
I am trying to cross compile this source code for ARM processor. I am using CodeSourcery compiler. I set CC to point my cross compiler and built. But it is failing with following error.
`output/pjsua2-test-arm-elf-linux-gnu/main.o: file not recognized: File format not recognized
collect2: ld returned 1 exit status
`
**To Reproduce**

- Download this source code as zip file and unzip in home folder.

- set CC variable as below
`export CC="$HOME/CodeSourcery/Sourcery_CodeBench_Lite_for_ARM_GNU_Linux/bin/arm-none-linux-gnueabi-gcc"`

- Go to unzipped directory and run below commands
`./configure --disable-video --disable-libwebrtc --host=arm-elf-linux
make dep && make`

**Expected behavior**
Cross compilation should work.

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: Ubuntu 16.04
- PJSIP
  - version: 
  - applied patch(es): 
  - `configure` script params: ...
  - `config_site.h` contents: ...

**Additional context**
I had doubt in cross compiler tool. Which cross compiler tool should you suggest for cross compile for ARM

@sauwming Can you provide me the download link which can cross compile successfully for ARM? Additonally, without --disablelibwebrtc flag, am getting `emmintrin.h: No such file or directory` error. Is it known issue in PJSIP source code?

**Comment by colorhacker** [comment]
how to solve？

**Comment by tangm421** [comment]
when crosscompile with arm-hisiv400-linux-gcc, this problems still exist in release 2.13.
