### ISSUE TITLE
config issue: incoming call  can't answer . pjsua_core.c  ....TX 342 bytes Response msg 603/INVITE/cseq=1594263627 (tdta0x2c1700c8) to UDP 192.168.1.119:5060: SIP/2.0 603 Decline

### ISSUE THREAD

**Issue by kuodehai** [pjsip/pjproject#2484]
Hi @sauwming @Perry Ismangil
  
**Is your feature request related to a problem? Please describe.**
incoming call can't answer call
 pjsua_core.c  ....TX 342 bytes Response msg 603/INVITE/cseq=1594263627 (tdta0x2c1700c8) to UDP 192.168.1.119:5060:
SIP/2.0 603 Decline

[putty_sip_client_inoming_answer -11.log](https://github.com/pjsip/pjproject/files/4896074/putty_sip_client_inoming_answer.-11.log)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trengginas** [comment]
From the log you hang up the call:
===
10:53:07.261           pjsua_call.c !Call 0 hanging up: code=0..
===
