### ISSUE TITLE
Memory leak(s) in Pjsua2

### ISSUE THREAD

**Issue by Hexik** [pjsip/pjproject#2486]
PJSIP 2.10

A. Memory leak in class Call, memory allocated at call.cpp line 886 is not deleted.

1. run pjsua2_demo app with valgrind: valgrind --tool=memcheck ./pjsua2_demo
2. memory leak is detected
==27746== LEAK SUMMARY:
==27746==    definitely lost: 928 bytes in 1 blocks

Solution:
Free memory pointed by Call::medias[] in Call destructor

B. Memory leak in Buddy::create()
memory allocated at presence.cpp line 135 is not deleted.

Solution:
not so easy as it is unclear who is responsible (memory owner) of the pj_cfg.user_data

**Comment by sauwming** [comment]
Thanks for the report.

A. Call:medias[] is supposed to be freed in processStateChange() when call is disconnected, here:
https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua2/call.cpp#L940

If it doesn't happen, it indicates that the Call object is deleted, or program is terminated, before call is disconnected.

B. BuddyUserData is deleted in the destructor ~Buddy, here:
https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua2/presence.cpp#L108

If it doesn't happen, it means that the Buddy object is perhaps never deleted.
