### ISSUE TITLE
pjsua_recorder_create() / add video support

### ISSUE THREAD

**Issue by alexey1312** [pjsip/pjproject#2487]
**Is your feature request related to a problem? Please describe.**
pjsua_recorder_create() сan write only audio in wav container.

**Describe the solution you'd like**
add support video format and other container (.mov/mp4 for ios)

**Describe alternatives you've considered**
Linphone library...

**Additional context**
-

**Comment by sauwming** [comment]
For audio, we also support mp3. For video, yes, we can only read avi at the moment and unfortunately, have no plan to support other formats in the foreseeable future.

**Comment by alexey1312** [comment]
ok, do you have a plan to support write video in future?

**Comment by sauwming** [comment]
It is one of our wish list items to do avi recording. But there's no plan to do it in the near future, definitely not for the next release (2.11) for sure.
