### ISSUE TITLE
Wrong video from front camera under Android

### ISSUE THREAD

**Issue by zbyte** [pjsip/pjproject#2491]
My application for Android use pjsua2 via swig. I also build test swig application **pjsip-apps\src\swig\java\android**. My app and test app have the same problem: video from me has no right proportions and has artifacts on the sides of the video - black bars.
How it looks you can see the link: https://photos.app.goo.gl/CCpaM1GFkH6idknYA
The same picture, only stretched out, is shown in another side.
Tested on many devices with different versions android.

**To Reproduce**

1. build pjsua2 test app for android  **pjsip-apps\src\swig\java\android**
1. make two video calls to: `sip:abc` and `sip:xyz`
1. video in preview `sip:abc` and incoming video `sip:xyz` show with black bars on the side.

**Expected behavior**
Video in preview and incoming video on other side has right proportions and not have artifacts

**Logs/Screenshots**
[screenshot with problem](https://lh3.googleusercontent.com/pw/ACtC-3cj8TcrBcsQM4QTDReF7n7j0gJpef9KhAn3Tt4Ko9MUYFLexnJnkRPZ2mjYruqTZgp_J2ZqipJP61T3GmxiK_Vd3YtPQk5WhzlSAPJ_NGdSI8JoxU4MrVZfKH3tJv7c7WM8xhvd0xbQD36ybF2FAJJj_g=w527-h936-no?authuser=0)

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version:
  - Android 6
  - Android 8
  - Android 10
- PJSIP
  - version: 2.9
  - applied patch(es): no
  - `configure` script params: run configure-android
  - `config_site.h` contents: ...
  - related third party libraries & versions: OpenH264 2.1.0, OpenSSL 1.0.2g

**Smartphone (please also complete the following information):**

- Device: Xiaomi mi 5x, Honor 10, Samsung galaxy S10

**Additional context**
no

**Comment by sauwming** [comment]
If the endpoints have different resolutions (camera and display) and/or orientation (portrait/landscape), there's bound to be some scaling/stretching and black bars. This is to be expected.

**Comment by olegrussu1** [comment]
hello. i did notice that black lines appear only when i set orientation 270 degrees(portrait on android). Is there a way to get rid of black lines in portrait mode on android?
i set orientation by method
pjsua_vid_dev_set_setting(PJMEDIA_VID_DEFAULT_CAPTURE_DEV, PJMEDIA_VID_DEV_CAP_ORIENTATION, &orientation,
                                     PJ_TRUE)
