### ISSUE TITLE
"vid acc autorx off" not functional

### ISSUE THREAD

**Issue by AmeerGaafar** [pjsip/pjproject#2494]
pjsua does not respect "vid acc autorx off". Incoming video is shown anyway. A related issue is that due to this (not excluding other reasons) it is only possible to run pjsua within an X session if user wants to establish video calls. Since pjsua is not a GUI application, it should be possible to establish video calls without needing a graphic environment. In that case, outgoing video should proceed normally while incoming video should be ignored, or maybe written to a file/stream.

**To Reproduce**
1. run pjsua with valid vcapture device
2. execute 'vid acc autorx off'
3. attempt a video call from a remote user agent to this agent. I used LinPhone for iOS, and LinPhone for OSX.
4. answer the call with 200
4. The Rx video window will open. It should have not done so..

Testing was done on a Raspberry Pi 4, Buster, and PjSip 2.10..

Context:
A video doorbell. In this scenario we are not interested in rendering resident video to guest at the door. In fact there is no screen at all at the door. It would make more sense to setup this as a _normal_ linux service that does not require X to run.

**Comment by sauwming** [comment]
Right, this is similar to #2187 (Delay the creation of video capture until it is needed), but for the other direction (i.e. video renderer).

Unfortunately I'm currently working on another PR and won't be able to revisit this until after I'm done with that.

Also, I change the issue type to enhancement since I don't think it's a bug. As the doc says, autorx will only hide incoming video but doesn't prevent the creation of video renderer, so this is more of an enhancement request.

**Comment by phillipkujawa** [comment]
@sauwming any update on this? Using the latest PJSIP and I keep getting SIGFAULT on video calls with `autorx off`

21:53:48.424 os_core_unix.c !pjlib 2.11-dev for POSIX initialized
21:53:48.427 sip_endpoint.c  .Creating endpoint instance...
21:53:48.428          pjlib  .select() I/O Queue created (0x204d470)
21:53:48.428 sip_endpoint.c  .Module "mod-msg-print" registered
21:53:48.428 sip_transport.  .Transport manager created.
21:53:48.428   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
21:53:48.429 sip_endpoint.c  .Module "mod-pjsua-log" registered
21:53:48.429 sip_endpoint.c  .Module "mod-tsx-layer" registered
21:53:48.429 sip_endpoint.c  .Module "mod-stateful-util" registered
21:53:48.429 sip_endpoint.c  .Module "mod-ua" registered
21:53:48.429 sip_endpoint.c  .Module "mod-100rel" registered
21:53:48.429 sip_endpoint.c  .Module "mod-pjsua" registered
21:53:48.429 sip_endpoint.c  .Module "mod-invite" registered
21:53:48.527     alsa_dev.c  ..ALSA driver found 22 devices
21:53:48.527     alsa_dev.c  ..ALSA initialized
21:53:48.527          pjlib  ..select() I/O Queue created (0x205f62c)
21:53:48.537    pjsua_vid.c  ..Initializing video subsystem..
21:53:48.537   openh264.cpp  ...OpenH264 codec initialized
21:53:48.537          vpx.c  ...VPX codec initialized
21:53:48.539     v4l2_dev.c  ...Video4Linux2 has 1 devices
21:53:48.554      sdl_dev.c !SDL_Init() error: No available video device
21:53:48.555 colorbar_dev.c !...Colorbar video src initialized with 2 device(s):
21:53:48.555 colorbar_dev.c  ... 0: Colorbar generator
21:53:48.555 colorbar_dev.c  ... 1: Colorbar-active
21:53:48.555 sip_endpoint.c  .Module "mod-evsub" registered
21:53:48.555 sip_endpoint.c  .Module "mod-presence" registered
21:53:48.555 sip_endpoint.c  .Module "mod-mwi" registered
21:53:48.555 sip_endpoint.c  .Module "mod-refer" registered
21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-pres" registered
21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-im" registered
21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-options" registered
21:53:48.555   pjsua_core.c  .1 SIP worker threads created
21:53:48.555   pjsua_core.c  .pjsua version 2.11-dev for Linux-5.10.60/armv7l/glibc-2.28 initialized
21:53:48.555   pjsua_core.c  .PJSUA state changed: CREATED --> INIT
21:53:48.555 sip_endpoint.c  Module "mod-default-handler" registered
21:53:48.556   pjsua_core.c  SIP UDP socket reachable at 192.168.1.23:5060
21:53:48.556   udp0x206cbc0  SIP UDP transport started, published address is 192.168.1.23:5060
21:53:48.556    pjsua_acc.c  Adding account: id=<sip:192.168.1.23:5060>
21:53:48.556    pjsua_acc.c  .Account <sip:192.168.1.23:5060> added with id 0
21:53:48.556    pjsua_acc.c  Modifying account 0
21:53:48.556    pjsua_acc.c  Acc 0: setting online status to 1..
21:53:48.556     tcptp:5060  SIP TCP listener ready for incoming connections at 192.168.1.23:5060
21:53:48.556    pjsua_acc.c  Adding account: id=<sip:192.168.1.23:5060;transport=TCP>
21:53:48.556    pjsua_acc.c  .Account <sip:192.168.1.23:5060;transport=TCP> added with id 1
21:53:48.556    pjsua_acc.c  Modifying account 1
21:53:48.556    pjsua_acc.c  Acc 1: setting online status to 1..
21:53:48.556   pjsua_core.c  PJSUA state changed: INIT --> STARTING
21:53:48.557 sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
21:53:48.557   pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
21:53:48.557         main.c  Ready: Success



You have 0 active call
>>> vid enable
21:53:51.821 pjsua_app_lega  Video will be enabled in next offer/answer
>>> vid dev list 
21:54:13.620 pjsua_app_comm  Video device list:
21:54:13.621 pjsua_app_comm  3 device(s) detected:
21:54:13.621 pjsua_app_comm   -1 mmal service 16.1 [v4l2][capture] (default capture device)
21:54:13.621 pjsua_app_comm      Supported capabilities: format
21:54:13.621 pjsua_app_comm      Supported formats: I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2 ...
21:54:13.621 pjsua_app_comm    0 mmal service 16.1 [v4l2][capture] 
21:54:13.621 pjsua_app_comm      Supported capabilities: format
21:54:13.621 pjsua_app_comm      Supported formats: I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2 ...
21:54:13.621 pjsua_app_comm    1 Colorbar generator [Colorbar][capture] 
21:54:13.621 pjsua_app_comm      Supported capabilities: format
21:54:13.621 pjsua_app_comm      Supported formats: YUY2, UYVY, YVYU, RGBA, RGB24, BGRA, YV12, I420, I422, I420JPG, I422JPG
21:54:13.622 pjsua_app_comm    2 Colorbar-active [Colorbar][capture] 
21:54:13.622 pjsua_app_comm      Supported capabilities: format
21:54:13.622 pjsua_app_comm      Supported formats: YUY2, UYVY, YVYU, RGBA, RGB24, BGRA, YV12, I420, I422, I420JPG, I422JPG
>>> vid acc show
21:54:58.410 pjsua_app_comm  Account 1:
  RX auto show:     0
  TX auto transmit: 1
  Capture dev:      -1
  Render dev:       -2



21:57:23.078    pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
21:57:23.078   inv0x138901c  ....SDP negotiation done: Success
21:57:23.079  pjsua_media.c  .....Call 0: updating media..
21:57:23.079  pjsua_media.c  .......Media stream call00:0 is destroyed
21:57:23.079    pjsua_aud.c  ......Audio channel update..
21:57:23.079 strm0xb5208d7c  .......VAD temporarily disabled
21:57:23.079 strm0xb5208d7c  .......Encoder stream started
21:57:23.079 strm0xb5208d7c  .......Decoder stream started
21:57:23.079  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
21:57:23.079  pjsua_media.c  .......Media stream call00:1 is destroyed
21:57:23.079    pjsua_vid.c  ......Video channel update..
21:57:23.113 vstenc0xb520e3  .......Encoder stream started
21:57:23.113 vstdec0xb520e3  .......Decoder stream started
21:57:23.113    pjsua_vid.c  .......Setting up RX..
21:57:23.113    pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=-1
21:57:23.113    pjsua_vid.c  .........Window 0: destroying..
21:57:23.113  pjsua_media.c  ......pjsua_vid_channel_update() failed for call_id 0 media 1: Invalid video device (PJMEDIA_EVID_INVDEV)
21:57:23.113    pjsua_vid.c  .......Stopping video stream..
21:57:23.115  pjsua_media.c  .......Media stream call00:1 is destroyed
21:57:23.115  pjsua_media.c  ......Error updating media call00:1: Invalid video device (PJMEDIA_EVID_INVDEV)
21:57:23.115    pjsua_app.c  .....Call 0 media 0 [type=audio], status is Active
21:57:23.115    pjsua_aud.c  .....Conf connect: 3 --> 0
21:57:23.115   conference.c  ......Port 3 (sip:phillip1992@sip.telnyx.com) transmitting to port 0 (default)
21:57:23.116    pjsua_aud.c  .....Conf connect: 0 --> 3
21:57:23.116   conference.c  ......Port 0 (default) transmitting to port 3 (sip:phillip1992@sip.telnyx.com)
21:57:23.116    pjsua_app.c  .....Call 0 media 1 [type=video], status is Error
21:57:23.130 strm0xb5208d7c !Resetting jitter buffer in stream playback start
21:57:23.705 strm0xb5208d7c  VAD re-enabled
21:57:26.053   pjsua_core.c  .RX 1297 bytes Response msg 200/INVITE/cseq=21092 (rdata0x139901c) from TCP 192.76.120.10:5060:

--end msg--
21:46:52.707    pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
21:46:52.707   inv0x1bcd01c  ....SDP negotiation done: Success
21:46:52.707  pjsua_media.c  .....Call 0: updating media..
21:46:52.707  pjsua_media.c  .......Media stream call00:0 is destroyed
21:46:52.707    pjsua_aud.c  ......Audio channel update..
21:46:52.707 strm0xb5108d7c  .......VAD temporarily disabled
21:46:52.707 strm0xb5108d7c  .......Encoder stream started
21:46:52.708 strm0xb5108d7c  .......Decoder stream started
21:46:52.708  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
21:46:52.708  pjsua_media.c  .......Media stream call00:1 is destroyed
21:46:52.708    pjsua_vid.c  ......Video channel update..
21:46:52.760 vstenc0xb510e3  .......Encoder stream started
21:46:52.760 vstdec0xb510e3  .......Decoder stream started
21:46:52.760    pjsua_vid.c  .......Setting up RX..
21:46:52.760    pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=524293
Error: signal 11

**Comment by hudongyue1** [comment]
> @sauwming any update on this? Using the latest PJSIP and I keep getting SIGFAULT on video calls with `autorx off`
> 
> ```
> 21:53:48.424 os_core_unix.c !pjlib 2.11-dev for POSIX initialized
> 21:53:48.427 sip_endpoint.c  .Creating endpoint instance...
> 21:53:48.428          pjlib  .select() I/O Queue created (0x204d470)
> 21:53:48.428 sip_endpoint.c  .Module "mod-msg-print" registered
> 21:53:48.428 sip_transport.  .Transport manager created.
> 21:53:48.428   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
> 21:53:48.429 sip_endpoint.c  .Module "mod-pjsua-log" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-tsx-layer" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-stateful-util" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-ua" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-100rel" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-pjsua" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-invite" registered
> 21:53:48.527     alsa_dev.c  ..ALSA driver found 22 devices
> 21:53:48.527     alsa_dev.c  ..ALSA initialized
> 21:53:48.527          pjlib  ..select() I/O Queue created (0x205f62c)
> 21:53:48.537    pjsua_vid.c  ..Initializing video subsystem..
> 21:53:48.537   openh264.cpp  ...OpenH264 codec initialized
> 21:53:48.537          vpx.c  ...VPX codec initialized
> 21:53:48.539     v4l2_dev.c  ...Video4Linux2 has 1 devices
> 21:53:48.554      sdl_dev.c !SDL_Init() error: No available video device
> 21:53:48.555 colorbar_dev.c !...Colorbar video src initialized with 2 device(s):
> 21:53:48.555 colorbar_dev.c  ... 0: Colorbar generator
> 21:53:48.555 colorbar_dev.c  ... 1: Colorbar-active
> 21:53:48.555 sip_endpoint.c  .Module "mod-evsub" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-presence" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-mwi" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-refer" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-pres" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-im" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-options" registered
> 21:53:48.555   pjsua_core.c  .1 SIP worker threads created
> 21:53:48.555   pjsua_core.c  .pjsua version 2.11-dev for Linux-5.10.60/armv7l/glibc-2.28 initialized
> 21:53:48.555   pjsua_core.c  .PJSUA state changed: CREATED --> INIT
> 21:53:48.555 sip_endpoint.c  Module "mod-default-handler" registered
> 21:53:48.556   pjsua_core.c  SIP UDP socket reachable at 192.168.1.23:5060
> 21:53:48.556   udp0x206cbc0  SIP UDP transport started, published address is 192.168.1.23:5060
> 21:53:48.556    pjsua_acc.c  Adding account: id=<sip:192.168.1.23:5060>
> 21:53:48.556    pjsua_acc.c  .Account <sip:192.168.1.23:5060> added with id 0
> 21:53:48.556    pjsua_acc.c  Modifying account 0
> 21:53:48.556    pjsua_acc.c  Acc 0: setting online status to 1..
> 21:53:48.556     tcptp:5060  SIP TCP listener ready for incoming connections at 192.168.1.23:5060
> 21:53:48.556    pjsua_acc.c  Adding account: id=<sip:192.168.1.23:5060;transport=TCP>
> 21:53:48.556    pjsua_acc.c  .Account <sip:192.168.1.23:5060;transport=TCP> added with id 1
> 21:53:48.556    pjsua_acc.c  Modifying account 1
> 21:53:48.556    pjsua_acc.c  Acc 1: setting online status to 1..
> 21:53:48.556   pjsua_core.c  PJSUA state changed: INIT --> STARTING
> 21:53:48.557 sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
> 21:53:48.557   pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
> 21:53:48.557         main.c  Ready: Success
> 
> 
> 
> You have 0 active call
> >>> vid enable
> 21:53:51.821 pjsua_app_lega  Video will be enabled in next offer/answer
> >>> vid dev list 
> 21:54:13.620 pjsua_app_comm  Video device list:
> 21:54:13.621 pjsua_app_comm  3 device(s) detected:
> 21:54:13.621 pjsua_app_comm   -1 mmal service 16.1 [v4l2][capture] (default capture device)
> 21:54:13.621 pjsua_app_comm      Supported capabilities: format
> 21:54:13.621 pjsua_app_comm      Supported formats: I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2 ...
> 21:54:13.621 pjsua_app_comm    0 mmal service 16.1 [v4l2][capture] 
> 21:54:13.621 pjsua_app_comm      Supported capabilities: format
> 21:54:13.621 pjsua_app_comm      Supported formats: I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2 ...
> 21:54:13.621 pjsua_app_comm    1 Colorbar generator [Colorbar][capture] 
> 21:54:13.621 pjsua_app_comm      Supported capabilities: format
> 21:54:13.621 pjsua_app_comm      Supported formats: YUY2, UYVY, YVYU, RGBA, RGB24, BGRA, YV12, I420, I422, I420JPG, I422JPG
> 21:54:13.622 pjsua_app_comm    2 Colorbar-active [Colorbar][capture] 
> 21:54:13.622 pjsua_app_comm      Supported capabilities: format
> 21:54:13.622 pjsua_app_comm      Supported formats: YUY2, UYVY, YVYU, RGBA, RGB24, BGRA, YV12, I420, I422, I420JPG, I422JPG
> >>> vid acc show
> 21:54:58.410 pjsua_app_comm  Account 1:
>   RX auto show:     0
>   TX auto transmit: 1
>   Capture dev:      -1
>   Render dev:       -2
> 
> 
> 
> 21:57:23.078    pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
> 21:57:23.078   inv0x138901c  ....SDP negotiation done: Success
> 21:57:23.079  pjsua_media.c  .....Call 0: updating media..
> 21:57:23.079  pjsua_media.c  .......Media stream call00:0 is destroyed
> 21:57:23.079    pjsua_aud.c  ......Audio channel update..
> 21:57:23.079 strm0xb5208d7c  .......VAD temporarily disabled
> 21:57:23.079 strm0xb5208d7c  .......Encoder stream started
> 21:57:23.079 strm0xb5208d7c  .......Decoder stream started
> 21:57:23.079  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
> 21:57:23.079  pjsua_media.c  .......Media stream call00:1 is destroyed
> 21:57:23.079    pjsua_vid.c  ......Video channel update..
> 21:57:23.113 vstenc0xb520e3  .......Encoder stream started
> 21:57:23.113 vstdec0xb520e3  .......Decoder stream started
> 21:57:23.113    pjsua_vid.c  .......Setting up RX..
> 21:57:23.113    pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=-1
> 21:57:23.113    pjsua_vid.c  .........Window 0: destroying..
> 21:57:23.113  pjsua_media.c  ......pjsua_vid_channel_update() failed for call_id 0 media 1: Invalid video device (PJMEDIA_EVID_INVDEV)
> 21:57:23.113    pjsua_vid.c  .......Stopping video stream..
> 21:57:23.115  pjsua_media.c  .......Media stream call00:1 is destroyed
> 21:57:23.115  pjsua_media.c  ......Error updating media call00:1: Invalid video device (PJMEDIA_EVID_INVDEV)
> 21:57:23.115    pjsua_app.c  .....Call 0 media 0 [type=audio], status is Active
> 21:57:23.115    pjsua_aud.c  .....Conf connect: 3 --> 0
> 21:57:23.115   conference.c  ......Port 3 (sip:phillip1992@sip.telnyx.com) transmitting to port 0 (default)
> 21:57:23.116    pjsua_aud.c  .....Conf connect: 0 --> 3
> 21:57:23.116   conference.c  ......Port 0 (default) transmitting to port 3 (sip:phillip1992@sip.telnyx.com)
> 21:57:23.116    pjsua_app.c  .....Call 0 media 1 [type=video], status is Error
> 21:57:23.130 strm0xb5208d7c !Resetting jitter buffer in stream playback start
> 21:57:23.705 strm0xb5208d7c  VAD re-enabled
> 21:57:26.053   pjsua_core.c  .RX 1297 bytes Response msg 200/INVITE/cseq=21092 (rdata0x139901c) from TCP 192.76.120.10:5060:
> 
> --end msg--
> 21:46:52.707    pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
> 21:46:52.707   inv0x1bcd01c  ....SDP negotiation done: Success
> 21:46:52.707  pjsua_media.c  .....Call 0: updating media..
> 21:46:52.707  pjsua_media.c  .......Media stream call00:0 is destroyed
> 21:46:52.707    pjsua_aud.c  ......Audio channel update..
> 21:46:52.707 strm0xb5108d7c  .......VAD temporarily disabled
> 21:46:52.707 strm0xb5108d7c  .......Encoder stream started
> 21:46:52.708 strm0xb5108d7c  .......Decoder stream started
> 21:46:52.708  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
> 21:46:52.708  pjsua_media.c  .......Media stream call00:1 is destroyed
> 21:46:52.708    pjsua_vid.c  ......Video channel update..
> 21:46:52.760 vstenc0xb510e3  .......Encoder stream started
> 21:46:52.760 vstdec0xb510e3  .......Decoder stream started
> 21:46:52.760    pjsua_vid.c  .......Setting up RX..
> 21:46:52.760    pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=524293
> Error: signal 11
> ```



> @sauwming any update on this? Using the latest PJSIP and I keep getting SIGFAULT on video calls with `autorx off`
> 
> ```
> 21:53:48.424 os_core_unix.c !pjlib 2.11-dev for POSIX initialized
> 21:53:48.427 sip_endpoint.c  .Creating endpoint instance...
> 21:53:48.428          pjlib  .select() I/O Queue created (0x204d470)
> 21:53:48.428 sip_endpoint.c  .Module "mod-msg-print" registered
> 21:53:48.428 sip_transport.  .Transport manager created.
> 21:53:48.428   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
> 21:53:48.429 sip_endpoint.c  .Module "mod-pjsua-log" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-tsx-layer" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-stateful-util" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-ua" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-100rel" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-pjsua" registered
> 21:53:48.429 sip_endpoint.c  .Module "mod-invite" registered
> 21:53:48.527     alsa_dev.c  ..ALSA driver found 22 devices
> 21:53:48.527     alsa_dev.c  ..ALSA initialized
> 21:53:48.527          pjlib  ..select() I/O Queue created (0x205f62c)
> 21:53:48.537    pjsua_vid.c  ..Initializing video subsystem..
> 21:53:48.537   openh264.cpp  ...OpenH264 codec initialized
> 21:53:48.537          vpx.c  ...VPX codec initialized
> 21:53:48.539     v4l2_dev.c  ...Video4Linux2 has 1 devices
> 21:53:48.554      sdl_dev.c !SDL_Init() error: No available video device
> 21:53:48.555 colorbar_dev.c !...Colorbar video src initialized with 2 device(s):
> 21:53:48.555 colorbar_dev.c  ... 0: Colorbar generator
> 21:53:48.555 colorbar_dev.c  ... 1: Colorbar-active
> 21:53:48.555 sip_endpoint.c  .Module "mod-evsub" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-presence" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-mwi" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-refer" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-pres" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-im" registered
> 21:53:48.555 sip_endpoint.c  .Module "mod-pjsua-options" registered
> 21:53:48.555   pjsua_core.c  .1 SIP worker threads created
> 21:53:48.555   pjsua_core.c  .pjsua version 2.11-dev for Linux-5.10.60/armv7l/glibc-2.28 initialized
> 21:53:48.555   pjsua_core.c  .PJSUA state changed: CREATED --> INIT
> 21:53:48.555 sip_endpoint.c  Module "mod-default-handler" registered
> 21:53:48.556   pjsua_core.c  SIP UDP socket reachable at 192.168.1.23:5060
> 21:53:48.556   udp0x206cbc0  SIP UDP transport started, published address is 192.168.1.23:5060
> 21:53:48.556    pjsua_acc.c  Adding account: id=<sip:192.168.1.23:5060>
> 21:53:48.556    pjsua_acc.c  .Account <sip:192.168.1.23:5060> added with id 0
> 21:53:48.556    pjsua_acc.c  Modifying account 0
> 21:53:48.556    pjsua_acc.c  Acc 0: setting online status to 1..
> 21:53:48.556     tcptp:5060  SIP TCP listener ready for incoming connections at 192.168.1.23:5060
> 21:53:48.556    pjsua_acc.c  Adding account: id=<sip:192.168.1.23:5060;transport=TCP>
> 21:53:48.556    pjsua_acc.c  .Account <sip:192.168.1.23:5060;transport=TCP> added with id 1
> 21:53:48.556    pjsua_acc.c  Modifying account 1
> 21:53:48.556    pjsua_acc.c  Acc 1: setting online status to 1..
> 21:53:48.556   pjsua_core.c  PJSUA state changed: INIT --> STARTING
> 21:53:48.557 sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
> 21:53:48.557   pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
> 21:53:48.557         main.c  Ready: Success
> 
> 
> 
> You have 0 active call
> >>> vid enable
> 21:53:51.821 pjsua_app_lega  Video will be enabled in next offer/answer
> >>> vid dev list 
> 21:54:13.620 pjsua_app_comm  Video device list:
> 21:54:13.621 pjsua_app_comm  3 device(s) detected:
> 21:54:13.621 pjsua_app_comm   -1 mmal service 16.1 [v4l2][capture] (default capture device)
> 21:54:13.621 pjsua_app_comm      Supported capabilities: format
> 21:54:13.621 pjsua_app_comm      Supported formats: I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2 ...
> 21:54:13.621 pjsua_app_comm    0 mmal service 16.1 [v4l2][capture] 
> 21:54:13.621 pjsua_app_comm      Supported capabilities: format
> 21:54:13.621 pjsua_app_comm      Supported formats: I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, I420, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2, YUY2 ...
> 21:54:13.621 pjsua_app_comm    1 Colorbar generator [Colorbar][capture] 
> 21:54:13.621 pjsua_app_comm      Supported capabilities: format
> 21:54:13.621 pjsua_app_comm      Supported formats: YUY2, UYVY, YVYU, RGBA, RGB24, BGRA, YV12, I420, I422, I420JPG, I422JPG
> 21:54:13.622 pjsua_app_comm    2 Colorbar-active [Colorbar][capture] 
> 21:54:13.622 pjsua_app_comm      Supported capabilities: format
> 21:54:13.622 pjsua_app_comm      Supported formats: YUY2, UYVY, YVYU, RGBA, RGB24, BGRA, YV12, I420, I422, I420JPG, I422JPG
> >>> vid acc show
> 21:54:58.410 pjsua_app_comm  Account 1:
>   RX auto show:     0
>   TX auto transmit: 1
>   Capture dev:      -1
>   Render dev:       -2
> 
> 
> 
> 21:57:23.078    pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
> 21:57:23.078   inv0x138901c  ....SDP negotiation done: Success
> 21:57:23.079  pjsua_media.c  .....Call 0: updating media..
> 21:57:23.079  pjsua_media.c  .......Media stream call00:0 is destroyed
> 21:57:23.079    pjsua_aud.c  ......Audio channel update..
> 21:57:23.079 strm0xb5208d7c  .......VAD temporarily disabled
> 21:57:23.079 strm0xb5208d7c  .......Encoder stream started
> 21:57:23.079 strm0xb5208d7c  .......Decoder stream started
> 21:57:23.079  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
> 21:57:23.079  pjsua_media.c  .......Media stream call00:1 is destroyed
> 21:57:23.079    pjsua_vid.c  ......Video channel update..
> 21:57:23.113 vstenc0xb520e3  .......Encoder stream started
> 21:57:23.113 vstdec0xb520e3  .......Decoder stream started
> 21:57:23.113    pjsua_vid.c  .......Setting up RX..
> 21:57:23.113    pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=-1
> 21:57:23.113    pjsua_vid.c  .........Window 0: destroying..
> 21:57:23.113  pjsua_media.c  ......pjsua_vid_channel_update() failed for call_id 0 media 1: Invalid video device (PJMEDIA_EVID_INVDEV)
> 21:57:23.113    pjsua_vid.c  .......Stopping video stream..
> 21:57:23.115  pjsua_media.c  .......Media stream call00:1 is destroyed
> 21:57:23.115  pjsua_media.c  ......Error updating media call00:1: Invalid video device (PJMEDIA_EVID_INVDEV)
> 21:57:23.115    pjsua_app.c  .....Call 0 media 0 [type=audio], status is Active
> 21:57:23.115    pjsua_aud.c  .....Conf connect: 3 --> 0
> 21:57:23.115   conference.c  ......Port 3 (sip:phillip1992@sip.telnyx.com) transmitting to port 0 (default)
> 21:57:23.116    pjsua_aud.c  .....Conf connect: 0 --> 3
> 21:57:23.116   conference.c  ......Port 0 (default) transmitting to port 3 (sip:phillip1992@sip.telnyx.com)
> 21:57:23.116    pjsua_app.c  .....Call 0 media 1 [type=video], status is Error
> 21:57:23.130 strm0xb5208d7c !Resetting jitter buffer in stream playback start
> 21:57:23.705 strm0xb5208d7c  VAD re-enabled
> 21:57:26.053   pjsua_core.c  .RX 1297 bytes Response msg 200/INVITE/cseq=21092 (rdata0x139901c) from TCP 192.76.120.10:5060:
> 
> --end msg--
> 21:46:52.707    pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
> 21:46:52.707   inv0x1bcd01c  ....SDP negotiation done: Success
> 21:46:52.707  pjsua_media.c  .....Call 0: updating media..
> 21:46:52.707  pjsua_media.c  .......Media stream call00:0 is destroyed
> 21:46:52.707    pjsua_aud.c  ......Audio channel update..
> 21:46:52.707 strm0xb5108d7c  .......VAD temporarily disabled
> 21:46:52.707 strm0xb5108d7c  .......Encoder stream started
> 21:46:52.708 strm0xb5108d7c  .......Decoder stream started
> 21:46:52.708  pjsua_media.c  ......Audio updated, stream #0: PCMU (sendrecv)
> 21:46:52.708  pjsua_media.c  .......Media stream call00:1 is destroyed
> 21:46:52.708    pjsua_vid.c  ......Video channel update..
> 21:46:52.760 vstenc0xb510e3  .......Encoder stream started
> 21:46:52.760 vstdec0xb510e3  .......Decoder stream started
> 21:46:52.760    pjsua_vid.c  .......Setting up RX..
> 21:46:52.760    pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=524293
> Error: signal 11
> ```
Has your problem been solved? I meet the same problem as you. My computer do not have renderer device.

**Comment by sauwming** [comment]
Not planned.
