### ISSUE TITLE
A possible bug in RTCP XR module

### ISSUE THREAD

**Issue by ml16685** [pjsip/pjproject#2496]
Hello,

I suspect there is a bug in RTCP XR module of not taking into account part of discard/lost packets statistics.

As I see, we report discard/lost events to RTCP XR module in pjmedia_rtcp_rx_rtp2()
For example,

/* Report RTCP XR about packet losses */
for (i=seq_st.diff-1; i>0; --i) {
   pjmedia_rtcp_xr_rx_rtp(&sess->xr_session, seq - i,
  1,    /* lost    */
  0,    /* dup     */
  0,    /* discard */
  -1,    /* jitter  */
  -1, 0);    /* toh     */
}

But one more part of discard/lost statistics is collected inside jitter buffer in "pjmedia_jbuf" structure by updating the following fields:

struct pjmedia_jbuf
{
    ...
    unsigned    jb_lost; /**< Number of lost frames.    */
    unsigned    jb_discard; /**< Number of discarded frames.    */
}

But I cannot find in code how this data is taken into account by RTCP XR module.
Pjproject version we are currently using is 2.7, but as I have checked 2.10 behaves the same.

Am I missing something or it is a bug in RTCP XR module?

**Comment by sauwming** [comment]
They're different. RTCP is to provide data/stats about the RTP packets, while jitter buffer is a temporary buffer to help reduce/eliminate jitter and it has its own internal stats. So for example, jitter buffer can intentionally discard frames to achieve better latency and this won't count in RTCP stats. You can check this in jitter buffer state instead using the API pjmedia_jbuf_get_state().

**Comment by ml16685** [comment]
Please note that the issue is about extended RTCP XR statistics, not the regular RTCP. 

In the related RFC 3611 there is a description of the RTCP XR fields,  where among others 
there is the field 'discard_rate' which includes packets discarded by jitter.
For a detailed description of the field see section "4.7.1.  Packet Loss and Discard Metrics".

So, basing on this RFC, I see that jitter statistics should be taken into account when preparing
extended RTCP XR report.

**Comment by sauwming** [comment]
You're right. There are some features/info that we haven't implemented as our RTCP XR implementation is currently still a subset of what's described in the RFC (https://trac.pjsip.org/repos/wiki/PJSIP-Datasheet).

**Comment by ml16685** [comment]
Just wanted to mention that it is actually a bug, because 'discard_rate'  is among already supported RTCP XR fields:

https://trac.pjsip.org/repos/ticket/513

which means that its content should be in full compliance with RFC 3611.
But as long as we do not take into account the jitter statistics,  the content of the field is not quite correct.
