### ISSUE TITLE
`Make dep` error on windows 10 using git bash. MinGW

### ISSUE THREAD

**Issue by MaksimDanilov** [pjsip/pjproject#2497]
Trying to compile pjsip 2.10, but getting this error on webrtc lib dependency      
```sh
else \
        echo 'err:' >> .libwebrtc-x86_64-pc-mingw32.depend; \
        rm -f .libwebrtc-x86_64-pc-mingw32.depend; \
        exit 1; \
     fi; \
   fi; \
done;
/usr/bin/sh: -c: строка 1: unexpected end of file
```
This error reproduced if you replace rules.mak depend target with only for loop.

**Comment by amneiht** [comment]
you can configure with --disable-libwebrtc options 
if you use msys2 , make dep and make allways error . buts every everything is good
