### ISSUE TITLE
The pjsua tests Python scripts are written in Python 2

### ISSUE THREAD

**Issue by Apteryks** [pjsip/pjproject#2499]
**Describe the bug**
The pjsua tests Python scripts are written in Python 2, which is no longer supported.

**To Reproduce**
Run `make selftest` with Python 3.
Errors about mixed whitespace indentation and syntax errors occur upon running the runall.py and related scripts.

**Expected behavior**
The tests scripts should run with Python 3, as Python 2 is obsolete and EOL.

Running autopep8 and 2to3 on the Python scripts mostly resolve the situation, with the exception of some bytes occurrences which must be converted to str using decode('utf-8').

**Comment by sauwming** [comment]
True, but porting it seems like an unnecessary hassle considering it's just for testing purposes.
