### ISSUE TITLE
flaky round_robin_test test

### ISSUE THREAD

**Issue by Apteryks** [pjsip/pjproject#2500]
**Describe the bug**
The round_robin_test sometimes fails because of a hit rate tolerance (6% actual vs max 5% expected). See the log excerpt below.

**To Reproduce**
Run `make selftest`, multiple times until the problem is triggered.

**Expected behavior**
Test should always pass.

**Logs/Screenshots**
```
16:02:35.705  Performing round-robin/load-balance test..
16:02:35.713  ..Server 1.1.1.1: weight=3%, hit 3% times
16:02:35.713  ..Server 2.2.2.2: weight=65%, hit 70% times
16:02:35.713  ..Server 3.3.3.3: weight=32%, hit 26% times
16:02:35.713  ..Server 4.4.4.4: weight=0%, hit 0% times
16:02:35.713 ..round_robin_test() error 20: hit rate difference for server 3.3.3.3 (-6%) is more than tolerable allowance (5%)
```

**Desktop**

- OS: GNU Guix
- PJSIP version 2.10

**Comment by sauwming** [comment]
Tolerance improved in https://github.com/pjsip/pjproject/commit/cc2198c27804fecca4b498b2f83a93b2f3381ee6
