### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by karimhm** [pjsip/pjproject#2502]
It would be really nice if `pjsip` is available as a [Swift Package](https://developer.apple.com/documentation/swift_packages) as this would simplify the integration of the library inside iOS/Mac/Apple TV projects without the need to invoke custom scripts or install custom build tools.

The way I think this should be done is through a Custom Github pipeline that gets invoked after each release. This does not need any modification to the project structure or files, only one single file `Package.swift` needs to be added to the root of the repo. 

For more information please take a look at [Distributing Binary Frameworks as Swift Packages](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages)

**Comment by sauwming** [comment]
Thanks for the suggestion. We did consider similar things in the past, such as creating CocoaPods or packaging PJSIP as framework, but in the end, decided that the current system is adequate.
