### ISSUE TITLE
Incorrect assertion behavior of PJ_ASSERT_RETURN

### ISSUE THREAD

**Issue by ErrReporter** [pjsip/pjproject#2508]
**Describe the bug**
https://github.com/pjsip/pjproject/blob/32153443e7452ff790e4ef04ef5c1834b9da3e2a/pjlib/include/pj/assert.h#L64-L67

Note that the `if` block can proceed only if the `expr` is evaluated to false, which also suggests `pj_assert(expr)` must fail. The return statement is never explored.

**To Reproduce**
The macro `PJ_ASSERT_RETURN` is used everywhere. It is easy to trigger the crash.

**Expected behavior**
Fix the macro

**Logs/Screenshots**
N/A

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: Arch Linux
- PJSIP
  - version: master
  - applied patch(es): No
  - `configure` script params: default
  - `config_site.h` contents: empty
  - related third party libraries & versions: OpenSSL 1.1.1b

**Smartphone (please also complete the following information):**

N/A

**Additional context**
N/A

**Comment by sauwming** [comment]
That's actually the intended behaviour. When assertion is disabled (such as in release mode), the macro will return error and let the program continue.

For more details: https://trac.pjsip.org/repos/wiki/FAQ#assert
