### ISSUE TITLE
Incorrect error code assertion

### ISSUE THREAD

**Issue by ErrReporter** [pjsip/pjproject#2509]
**Describe the bug**

`status` shall never be `PJ_SUCCESS` because of the assertion:

https://github.com/pjsip/pjproject/blob/32153443e7452ff790e4ef04ef5c1834b9da3e2a/pjlib/src/pj/activesock.c#L453

**To Reproduce**
Examine the code.

**Expected behavior**
The status can be `PJ_SUCCESS`.

**Logs/Screenshots**
N/A
**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: N/A
- PJSIP
  - version: master
  - applied patch(es): N/A
  - `configure` script params: N/A
  - `config_site.h` contents: N/A
  - related third party libraries & versions: N/A

**Smartphone (please also complete the following information):**

N/A

**Additional context**
N/A

**Comment by sauwming** [comment]
If the flag contains PJ_IOQUEUE_ALWAYS_ASYNC, pj_ioqueue_recv() (and recv_from() ) must never return PJ_SUCCESS, hence the assertion.
