### ISSUE TITLE
Using WebSocket as a transport protocol

### ISSUE THREAD

**Issue by karimhm** [pjsip/pjproject#2512]
Is it possible to add a way to connect to a SIP server via WebSocket instead of the raw TCP/UDP socket. 
This is defined in [RFC 7118](https://tools.ietf.org/html/rfc7118) and most popular SIP servers support it.

Reference links:
- [Kamailio WebSocket Module](https://www.kamailio.org/docs/modules/stable/modules/websocket.html)
- [OpenSIPS WebSocket module](https://opensips.org/docs/modules/3.1.x/proto_ws.html)
- [Configuring Asterisk for WebRTC Clients](https://wiki.asterisk.org/wiki/display/AST/Configuring+Asterisk+for+WebRTC+Clients)

**Comment by avesus** [comment]
Does OpenSIPS team endorse any client-side library? I heard [JsSip](https://github.com/versatica/JsSIP) is great.

**Comment by sauwming** [comment]
Yes, it is possible, but you have to implement the WebSocket transport yourself. Several of our users have done so, thus you can check them for reference.

**Comment by moradi-morteza** [comment]
> Yes, it is possible, but you have to implement the WebSocket transport yourself. Several of our users have done so, thus you can check them for reference.

can you mention some of implemented sample link?
I could not find any thing.
thanks
