### ISSUE TITLE
Crash On IOS 13.5.1 on Answering incoming call.

### ISSUE THREAD

**Issue by dheerajkatarya** [pjsip/pjproject#2514]
<img width="1231" alt="Screen Shot 2020-08-18 at 10 52 44 PM" src="https://user-images.githubusercontent.com/12449021/90597256-91c9db00-e1a5-11ea-8a8a-2b6d79e34d13.png">

**Comment by sauwming** [comment]
Sorry for not responding earlier. As the issue may no longer be valid now,
Please try with the latest version, and reopen if the issue persists.
