### ISSUE TITLE
The ping mechanism in pjsua2. Connection lost detection

### ISSUE THREAD

**Issue by sergey-zubkov** [pjsip/pjproject#2519]
Hello guys. Thanks for your work!

I'm trying to create an app on c# and I use pjsua2. The library works great

I cant understand how to implement the following feature: I need to receive an event when sip server is down. 
I've heard that I need to send method "OPTIONS" to check the server state, but I don't know how to do that.

I use:
- AccountConfig with login and pass.
- UDP transport
- If I turn off my asterix server (or network connection) my app doesn't receive disconnection event. 

I've tried to use "udpKaIntervalSec to catch "connection lost" event but it didn't work.

Could you please direct me to the right direction to detect connection lost state?

**Comment by sauwming** [comment]
You can use `pjsip_endpt_create_request()` and `pjsip_endpt_send_request()` to send the `OPTIONS`.
