### ISSUE TITLE
(pjnath)Improve support for RFC6156 and IPv6->IPv4 support

### ISSUE THREAD

**Issue by AmarOk1412** [pjsip/pjproject#2520]
https://tools.ietf.org/html/rfc6156 describes IPv6-to-IPv4 relaying that is not supported for now by PJSIP. (Which only supports IPv6-IPv6 and v4-v4), cf https://github.com/pjsip/pjproject/commit/4b6835c9b818eb8a434d35beccd5faa1b684533b#diff-ac1368e61901910d40e2661f8e489435

**Describe the solution you'd like**
The application should be able to ask for IPv4 relayed candidates on a IPv6-only network to be able to have communication between IPv6-only to IPv4-only network via a TURN server supporting RFC6156 (ex coturn with 2 relay-addr)

**Comment by sauwming** [comment]
Not planned
