### ISSUE TITLE
PJMEDIA_EAUD_INVDEV Issue

### ISSUE THREAD

**Issue by krishnastvSMSC** [pjsip/pjproject#2532]
Hello Team,
We are facing issue with "  pjsua_aud.c  .Error retrieving default audio device parameters: Invalid audio device (PJMEDIA_EAUD_INVDEV) [status=420004]"
The steps we did :  
   1.Git clone the pjsip from repository with tag 2.10     
2.Added config_site.h with

`#ifndef config_site_h
#define config_site_h
#define PJ_CONFIG_IPHONE 1
#include <pj/config_site_sample.h>
#endif /* config_site_h */`

  3.change directory to pjsip directory 
  4../configure-iphone.       
  5. make dep && make clean && make.  
  6. Now we open the iPhone project and the run the app(Build Successfully)
Now we did implementation for sip account registration and call initiation     
1. Sip Registration :  
`
- (int)registerToServer:(NSString *)domian username:(NSString *)username passwd:(NSString *)passwd
{
    
    [[NSNotificationCenter defaultCenter] addObserver: self
                                             selector: @selector(reachabilityChanged:)
                                                 name: kReachabilityChangedNotification object: nil];
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(activateSoundDevice) name:@"incomingcallEnableSound" object:nil];
    
    
    internetReach = [Reachability reachabilityForInternetConnection];
    [internetReach startNotifier];
    [self updateWithReachability: internetReach];
    
    pjsua_acc_id acc_id;
    pj_status_t status;
    
    /* Create pjsua first! */
    NSLog(@"--------pjsua first");
    status = pjsua_create();
    if (status != PJ_SUCCESS) {
        error_exit("Error in pjsua_create()", status);
        return -1;
    }
    
    /* Init pjsua */
    {
        pjsua_config cfg;
        pjsua_logging_config log_cfg;
        
        pjsua_config_default(&cfg);
        cfg.cb.on_incoming_call = &on_incoming_call;
        cfg.cb.on_call_media_state = &on_call_media_state;
        cfg.cb.on_call_state = &on_call_state;
        cfg.cb.on_transport_state = &onTransportStateChanged;
        cfg.cb.on_ip_change_progress =  &onIpChangeProgress;
        
        
        
        pjsua_logging_config_default(&log_cfg);
        log_cfg.console_level = 4;
        
        status = pjsua_init(&cfg, &log_cfg, NULL);
        if (status != PJ_SUCCESS)
        {
            error_exit("Error in pjsua_create()", status);
            return -1;
        }
    }
    /* Add UDP transport. */
    {
        pjsua_transport_config cfg;
        
        pjsua_transport_config_default(&cfg);
        cfg.port = 0;
        status = pjsua_transport_create(PJSIP_TRANSPORT_TCP, &cfg, NULL);
        if (status != PJ_SUCCESS)
        {
            error_exit("Error in pjsua_init()", status);
            return -1;
        }
    }
    /* Initialization is done, now start pjsua */
    status = pjsua_start();
    if (status != PJ_SUCCESS)
    {
        error_exit("Error starting pjsua", status);
        return -1;
    }
    /* Register to SIP server by creating SIP account. */
    {
        NSString *ID = [NSString stringWithFormat:@"sip:%@@%@",username,domian];
        NSString *reg_uri = [NSString stringWithFormat:@"sip:%@",domian];
        
        pjsua_acc_config cfg;
        pjsua_acc_config_default(&cfg);
        //cfg.id = pj_str([ID UTF8String]);
        cfg.id = pj_str((char *)[ID UTF8String]);
        cfg.reg_uri = pj_str((char *)[reg_uri UTF8String]);
        cfg.cred_count = 1;
        cfg.cred_info[0].realm = pj_str("*");
        cfg.cred_info[0].scheme = pj_str("digest");
        cfg.cred_info[0].username = pj_str((char *)[username UTF8String]);
        cfg.cred_info[0].data_type = PJSIP_CRED_DATA_PLAIN_PASSWD;
        cfg.cred_info[0].data = pj_str((char *)[passwd UTF8String]);
        
        cfg.proxy_cnt = 1;
        cfg.proxy[0] = pj_str((char *)[reg_uri UTF8String]);
        
        cfg.sip_stun_use = PJSUA_STUN_USE_DEFAULT;
        cfg.media_stun_use = PJSUA_STUN_USE_DEFAULT;
        
        cfg.allow_via_rewrite = PJ_TRUE;
        cfg.ip_change_cfg.shutdown_tp = PJ_TRUE;
        cfg.ip_change_cfg.hangup_calls = PJ_FALSE;
        cfg.ip_change_cfg.reinvite_flags = PJSUA_CALL_REINIT_MEDIA;
        cfg.contact_use_src_port = PJ_TRUE;
        
        
        
        //        cfg.vid_in_auto_show = PJ_TRUE;
        //        cfg.vid_out_auto_transmit = PJ_TRUE;
        
        status = pjsua_acc_add(&cfg, PJ_TRUE, &acc_id);
        
        if (status != PJ_SUCCESS)
            
        {
            error_exit("Error adding account", status);
            return -1;
        }
    }
    return 0;
}`

Mean while we written callbacks for require once    
2. to make a call we implemented like this

`- (void)configureAudioSession {
    NSError *audioSessionCategoryError;
    [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:&audioSessionCategoryError];
    NSLog(@"Setting AVAudioSessionCategory to \"Play and Record\"");

    if (audioSessionCategoryError) {
        NSLog(@"Error setting the correct AVAudioSession category");
    }

    // set the mode to voice chat
    NSError *audioSessionModeError;
    [[AVAudioSession sharedInstance] setMode:AVAudioSessionModeVoiceChat error:&audioSessionModeError];
    NSLog(@"Setting AVAudioSessionCategory to \"Mode Voice Chat\"");

    if (audioSessionModeError) {
        NSLog(@"Error setting the correct AVAudioSession mode");
    }
}
- (BOOL)activateSoundDevice {
    NSLog (@"audiosession");
    [self configureAudioSession];
    [self checkCurrentThreadIsRegisteredWithPJSUA];
    pjsua_set_no_snd_dev();
    pj_status_t status;
    status = pjsua_set_snd_dev(PJMEDIA_AUD_DEFAULT_CAPTURE_DEV, PJMEDIA_AUD_DEFAULT_PLAYBACK_DEV);
    if (status == PJ_SUCCESS) {
        return YES;
    } else {
        char statusmsg[PJ_ERR_MSG_SIZE];
        pj_strerror(status, statusmsg, sizeof(statusmsg));
        return NO;
    }
}
- (void) makeCall:(NSString *)callname domain:(NSString *)domian
{
    [self activateSoundDevice];
    NSString *ID = [NSString stringWithFormat:@"sip:%@@%@",callname,domian];
    pjsua_call_id current_call = 0;
    pj_str_t tmp;
    tmp = pj_str((char *)[ID UTF8String]);
    pjsua_call_make_call(current_acc, &tmp, NULL, NULL,
                         NULL, &current_call);
    
}`

As per instructions, before initiating a call we configure our Audiosession and set the pjsip no device set and again set the devices with (-1,-1). 
As we read that this issue is fixed in 2.8 release as per the reference link [https://github.com/pjsip/pjproject/issues/2075](https://github.com/pjsip/pjproject/issues/2075).
But still we are facing issues.
System Configuration:     Macbook Pro(macOS Catalina - v10.15.6)
After our search we got [https://stackoverflow.com/questions/16483635/pjsip-new-call-error-unable-to-find-default-audio-device-pjmedia-eaud-nodef](https://stackoverflow.com/questions/16483635/pjsip-new-call-error-unable-to-find-default-audio-device-pjmedia-eaud-nodef)

as per the description we need libasound2-dev, but it is not available for download for Mac os. 
Please help us to get out of this issue quickly.

Thank you.

**Comment by krishnastvSMSC** [comment]
Hi Team,

Can anyone help me to resolve this issue .

Thank you

**Comment by sauwming** [comment]
Sorry for not responding earlier. As the issue may no longer be valid now, I will close this.
