### ISSUE TITLE
iOS arm64e support

### ISSUE THREAD

**Issue by efendizadeh** [pjsip/pjproject#2533]
In case of building for apple arm64e arch configurer for ios throws errror with message unsupported arch

Solution is to check ARCH_VAL in configure-iphone script and if this equal to arm64e set this variable to arm64 to respect --host param for aconfigure script. This aproach gives to use -arch arm64e parameter for CFLAGS 

patch is attached
[add_iphone_arm64e_support.patch.zip](https://github.com/pjsip/pjproject/files/5298433/add_iphone_arm64e_support.patch.zip)

**Comment by ismangil** [comment]
Thank you - please submit this as a pull request then we can review it.

**Comment by sauwming** [comment]
Patch merged in #2537 .
