### ISSUE TITLE
Configure for  iOS SDK

### ISSUE THREAD

**Issue by krishnastvSMSC** [pjsip/pjproject#2536]
**Describe the bug**
For Mac OS unable to find libasound2-dev

**To Reproduce**
1. Downloaded V2.10 and added config_site.h with iPhone SDK
2.While making calls got error as 
_pjsua_aud.c  ..Error retrieving default audio device parameters: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) [status=420006]_

Call connected but no media transfer. 

**Expected behavior**
Media has to transfer for both the sides.

**Desktop/Smartphone (please complete the following information):**

- OS, Mac OS 10.15.7
- PJSIP
  - version: 2.10
  - `config_site.h` contents: ... 
`#ifndef config_site_h
#define config_site_h

#define PJ_CONFIG_IPHONE 1
#include <pj/config_site_sample.h>
#endif /* config_site_h */`

**Smartphone (please also complete the following information):**

- Device: iPhone 6,iPhone 7 Plus

**Comment by nicorobine** [comment]
I ran into the same problem, did you solve this problem?

**Comment by sauwming** [comment]
Please try with the latest version and reopen if the issue persists.
