### ISSUE TITLE
pjsua rtp port range

### ISSUE THREAD

**Issue by aleh4d** [pjsip/pjproject#2540]
In pjsua command line it is possible to define the base port to to try for RTP with --rtp-port=N  
However on firewalls they open ranges of ports, which have the upper limit for port
Is it possible also to limit the upper poet range from command line or is it possible to do by making a change in code?
Can you advice me where I could limit the upper port in code and make a custom compilation for myself?

**Comment by andrecurvello-controlid** [comment]
Hello,
Any news on that topic?

**Comment by sauwming** [comment]
Please check `pjsua_acc_config.rtp_cfg.port_range`.
