### ISSUE TITLE
build error:videodev.c:(.text+0x58): undefined reference to `pjmedia_dshow_factory'

### ISSUE THREAD

**Issue by netyuchangfa** [pjsip/pjproject#2541]
os:ubuntu14
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
intall ffmpeg and x264.....
enable video:
./pjlib/include/pj/config_site.h
#define PJMEDIA_HAS_VIDEO         1
//#define PJMEDIA_HAS_OPENH264_CODEC 1
//#define PJMEDIA_HAS_LIBYUV  1
#define PJMEDIA_VIDEO_DEV_HAS_SDL       1
#define PJMEDIA_VIDEO_DEV_HAS_DSHOW     1
#define PJMEDIA_HAS_FFMPEG         1
#define FF_INPUT_BUFFER_PADDING_SIZE 32

   ./configure --with-sdl   --with-ffmpeg 
   make dep
   make

/home/netyu/pjproject/pjmedia/lib/libpjmedia-videodev-x86_64-unknown-linux-gnu.a(videodev.o): In function `pjmedia_vid_dev_subsys_init':
videodev.c:(.text+0x58): undefined reference to `pjmedia_dshow_factory'
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/pjmedia-test-x86_64-unknown-linux-gnu] Error 1
make[2]: Leaving directory `/home/netyu/pjproject/pjmedia/build'
make[1]: *** [pjmedia-test-x86_64-unknown-linux-gnu] Error 2
make[1]: Leaving directory `/home/netyu/pjproject/pjmedia/build'
make: *** [all] Error 1

**Comment by sauwming** [comment]
DirectShow is for Windows. You shouldn't enable it on Linux.
