### ISSUE TITLE
G729 support under Android

### ISSUE THREAD

**Issue by illyaevseev** [pjsip/pjproject#2542]
**Describe the bug**
Unable to add G729 support for Android build

**To Reproduce**
1. $ git clone https://github.com/pjsip/pjproject.git
2. Add to pjlib/include/pj/config_site.h:
#define PJ_CONFIG_ANDROID 1
#define PJMEDIA_HAS_BCG729 1
#include <pj/config_site_sample.h>
3. $ export ANDROID_NDK_ROOT=<NDK path>
4. $ TARGET_ABI=arm64-v8a APP_PLATFORM=android-29 ./configure-android --use-ndk-cflags --enable-bcg729 2>&1 | grep bcg729
Checking if bcg729 is disabled... **yes**

**Expected behavior**
Checking if bcg729 is disabled... **no**

**Desktop/Smartphone (please complete the following information):**
OS: Debian Testing bullseye (Linux gaby 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux)
PJSIP: 2.10, latest cloned

**Smartphone (please also complete the following information):**
- Android Emulator 
- LG G6

[configure.log](https://github.com/pjsip/pjproject/files/5339241/configure.log)

**Comment by sauwming** [comment]
Please check https://github.com/pjsip/pjproject/issues/2029, in case you haven't.

**Comment by illyaevseev** [comment]
**To Reproduce**

mkdir ~/bcg729 && cd bcg729

git clone https://github.com/BelledonneCommunications/bcg729.git jni

evil@gaby:~/bcg729$ "$ANDROID_NDK_ROOT/build/ndk-build" APP_ABI=arm64-v8a APP_PLATFORM=android-29
[arm64-v8a] Compile        : bcg729 <= LP2LSPConversion.c
[arm64-v8a] Compile        : bcg729 <= LPSynthesisFilter.c
[arm64-v8a] Compile        : bcg729 <= LSPQuantization.c
[arm64-v8a] Compile        : bcg729 <= adaptativeCodebookSearch.c
[arm64-v8a] Compile        : bcg729 <= codebooks.c
[arm64-v8a] Compile        : bcg729 <= computeAdaptativeCodebookGain.c
[arm64-v8a] Compile        : bcg729 <= computeLP.c
[arm64-v8a] Compile        : bcg729 <= computeWeightedSpeech.c
[arm64-v8a] Compile        : bcg729 <= decodeAdaptativeCodeVector.c
[arm64-v8a] Compile        : bcg729 <= decodeFixedCodeVector.c
[arm64-v8a] Compile        : bcg729 <= decodeGains.c
[arm64-v8a] Compile        : bcg729 <= decodeLSP.c
[arm64-v8a] Compile        : bcg729 <= decoder.c
[arm64-v8a] Compile        : bcg729 <= encoder.c
[arm64-v8a] Compile        : bcg729 <= findOpenLoopPitchDelay.c
[arm64-v8a] Compile        : bcg729 <= fixedCodebookSearch.c
[arm64-v8a] Compile        : bcg729 <= gainQuantization.c
[arm64-v8a] Compile        : bcg729 <= interpolateqLSP.c
[arm64-v8a] Compile        : bcg729 <= postFilter.c
[arm64-v8a] Compile        : bcg729 <= postProcessing.c
[arm64-v8a] Compile        : bcg729 <= preProcessing.c
[arm64-v8a] Compile        : bcg729 <= qLSP2LP.c
[arm64-v8a] Compile        : bcg729 <= utils.c
[arm64-v8a] Compile        : bcg729 <= cng.c
[arm64-v8a] Compile        : bcg729 <= dtx.c
[arm64-v8a] Compile        : bcg729 <= vad.c
[arm64-v8a] StaticLibrary  : libbcg729.a

evil@gaby:~/bcg729$ cp obj/local/arm64-v8a/libbcg729.a ~/lib/bcg729/

evil@gaby:~/bin/pjproject$ ls -lah ~/lib/bcg729/
итого 560K
drwxr-xr-x 2 evil evil 4,0K окт 12 18:15 .
drwxr-xr-x 3 evil evil 4,0K окт 12 18:15 ..
-rw-r--r-- 1 evil evil 549K окт 12 21:30 libbcg729.a

evil@gaby:~/bin/pjproject$ TARGET_ABI=arm64-v8a APP_PLATFORM=android-29 ./configure-android --with-bcg729=/home/evil/lib/bcg729 2>&1 | grep bcg729
Using bcg729 prefix... /home/evil/lib/bcg729
checking bcg729 usability... **no**

**Expected behavior**
checking bcg729 usability... **yes**

**Comment by sauwming** [comment]
From the info you provided, it seems you copied it to an incorrect path. Read the instructions again, and check the config.log for more details to find out where the configure expects to find the header and library files.

**Comment by aenonGit** [comment]
I have the same problem, I have set the proper path in `--with-bcg729=correct/path/to/lib` inside the `lib` dir there is the `.a` library. But is always says `checking bcg729 usability... no`.

And by the way the docs has a missing `/` in the ndk command

... and ... where should we find the `config.log` ?

**Comment by illyaevseev** [comment]
**... and ... where should we find the config.log ?**
in a project root

**But it always says checking bcg729 usability... no**
After settings in projects move attached file to pjproject root directory, replace <PROJECT_NAME> to your project name and run. 
[build.txt](https://github.com/pjsip/pjproject/files/5415396/build.txt)

**Comment by aenonGit** [comment]
I already do that, there has to be something wrong either in the path or in the lib

**Comment by aenonGit** [comment]
fixed, I had the include files in a useless nested directory

it was `BCG_DIR/include/bcg729/bcg729/*.h` instead of `BCG_DIR/include/bcg729/*.h`
