### ISSUE TITLE
Incorrect copying of destination info when creating CANCEL

### ISSUE THREAD

**Issue by RalfKubis** [pjsip/pjproject#2544]
In an attempt to find the cause of a memory corruption in Asterisk I found this in 

*pjsip/src/pjsip/sip_util.c* in function *pjsip_endpt_create_cancel(...)*:

```
    /* Copy the destination host name from the original request */
    pj_strdup(
            cancel_tdata->pool
        ,   &cancel_tdata->dest_info.name
        ,   &req_tdata->dest_info.name
        );

    /* Finally copy the destination info from the original request */
    pj_memcpy(
            &cancel_tdata->dest_info
        ,   &req_tdata->dest_info
        ,   sizeof(req_tdata->dest_info)
        );
```

Here, **cancel_tdata->dest_info.name** receives a deep-copy.
But the subsequent call to **pj_memcpy()** makes it shallow again, now unintentionally referencing the wrong memory.

My intermediate Hack around this was:

```
    pj_memcpy(
            &cancel_tdata->dest_info
        ,   &req_tdata->dest_info
        ,   sizeof(req_tdata->dest_info)
        );

    cancel_tdata->dest_info.name.ptr  = 0;
    cancel_tdata->dest_info.name.slen = 0;

    /* Copy the destination host name from the original request */
    pj_strdup(
            cancel_tdata->pool
        ,   &cancel_tdata->dest_info.name
        ,   &req_tdata->dest_info.name
        );
```

but I'm sure You'll handle this in a more elegant way.
I'm sorry not to be able to provide a test scenario, since it was a random find by code review.

The symptom I had in Asterisk was uninitialized data in the host-part of the URI of all my CANCEL requests.

Null-bytes in the string led to ISP-triggered hangups of the TCP-connection to a trunk of "Telekom Deutschland", and thereby a loss of my registration. In other cases, without null-bytes, but other garbage, the CANCEL-request was ignored with an error reply, leading to continuous ringing on the called side.

But there was another issue in the Asterisk code, which, I believe, was the major cause for this.

**Comment by seanbright** [comment]
Just reversing the two statements seems like it would fix the problem. I don't know why zeroing out `cancel_tdata->dest_info.name` first would be necessary.

**Comment by RalfKubis** [comment]
Indeed.

In case *src->size* is zero, the implementation of *pj_strdup(..)* leaves *dst->ptr* at its undefined value instead of zeoring it out. Guess I disliked this due to potential, unintended and unnoticed de-refs.

But you're right.

**Comment by sauwming** [comment]
Good catch. Created PR #2546 for this.

I changed the issue title as well to make it more descriptive about what the issue is.
