### ISSUE TITLE
sometime  pjmedia-SDL video window not closed after over call unable to release camera

### ISSUE THREAD

**Issue by netyuchangfa** [pjsip/pjproject#2554]
version:pjsua v2.10
version: v4l-utils-1.20.0  
version: SDL2-2.0.12
After over call,sometime the pjmedia-SDL video window not quit...and the video device still opened unable to release camera

02:09:35.844             vid_conf.c  Port 1 (vstdec0x7f4b5406e058) stop transmitting to port 0 (SDL renderer)
02:09:35.844             vid_conf.c  Port 1 (vstdec0x7f4b5406e058) transmitting to port 0 (SDL renderer)
02:09:36.715              sdl_dev.c !Stopping sdl video stream
02:09:36.809              sdl_dev.c  Starting sdl video stream
02:09:37.270             vid_conf.c  Port 1 (vstdec0x7f4b5406e058) stop transmitting to port 0 (SDL renderer)
02:09:37.270             vid_conf.c  Port 1 (vstdec0x7f4b5406e058) transmitting to port 0 (SDL renderer)
02:09:37.271              sdl_dev.c  Stopping sdl video stream
02:09:37.271              sdl_dev.c  Starting sdl video stream
02:09:37.366             vid_conf.c !Port 1 (vstdec0x7f4b5406e058) stop transmitting to port 0 (SDL renderer)
02:09:37.366             vid_conf.c  Port 1 (vstdec0x7f4b5406e058) transmitting to port 0 (SDL renderer)
02:09:37.654             vid_conf.c !Port 1 (vstdec0x7f4b5406e058) stop transmitting to port 0 (SDL renderer)
02:09:37.654             vid_conf.c  Port 1 (vstdec0x7f4b5406e058) transmitting to port 0 (SDL renderer)
02:10:07.398           sound_port.c  EC suspended because of inactivity
02:10:08.280     tcpc0x7f4b5c04f818 !TCP transport destroyed normally

**Comment by netyuchangfa** [comment]
some time local dont need see video, set it "sendonly",under the circumstances how to edit source code build pjsua program?thanks very much!!

**Comment by netyuchangfa** [comment]
howto replace default "sendrecv" to “sendonly”?
Thanks very much!

**Comment by sauwming** [comment]
Currently the issue page is for bug report or feature request only.
