### ISSUE TITLE
How can I understand that the remote party is stopped its video in pjsip

### ISSUE THREAD

**Issue by erhnby** [pjsip/pjproject#2555]
For an iOS application, I need to know that when the remote party is stopped its video for an existing call. Is there any API or event that triggered by pjsip library?

Thanks in advance for your help.

**Comment by Meonardo** [comment]
Did you try listen `on_call_media_event` from endpoint callback?
the `PJMEDIA_EVENT_WND_CLOSING || PJMEDIA_EVENT_WND_CLOSED` enums would help.

**Comment by sauwming** [comment]
Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
