### ISSUE TITLE
inv_check_secure_dlg() fails on 200 response to UPDATE

### ISSUE THREAD

**Issue by kultakangas** [pjsip/pjproject#2558]
Some clients (e.g. Linphone 4.2.3) respond to the UPDATE message with the 200 response lacking the Contact header which is mandatory for 2xx response to INVITE message but not for UPDATE. Regardless of what RFC considers mandatory in the context of the response to a target-refresh request, it is not up to the inv_check_secure_dlg() function to decide whether the header is mandatory, thus it should not fail in the situations when using the TLS transport and the said header it not present. I'm attaching the proposed patch to solve the issue.

```
diff --git a/pjsip/src/pjsip-ua/sip_inv.c b/pjsip/src/pjsip-ua/sip_inv.c
index a763764..05dca0e 100644
--- a/pjsip/src/pjsip-ua/sip_inv.c
+++ b/pjsip/src/pjsip-ua/sip_inv.c
@@ -3787,7 +3787,7 @@ static pj_bool_t inv_check_secure_dlg(pjsip_inv_session *inv,
        /* Check Contact header */
        c = (pjsip_contact_hdr*)
            pjsip_msg_find_hdr(msg,PJSIP_H_CONTACT, NULL);
-       if (!(c && c->uri && PJSIP_URI_SCHEME_IS_SIPS(c->uri)))
+       if (c && c->uri && !PJSIP_URI_SCHEME_IS_SIPS(c->uri))
            status = PJSIP_ESESSIONINSECURE;

        /* Check top Record-Route header */
```

**Comment by sauwming** [comment]
According to https://www.rfc-editor.org/rfc/rfc3311:
```
               Contact                 R              m
               Contact                1xx             o
               Contact                2xx             m
               Contact                3xx      d      o
               Contact                485             o
```
Contact is mandatory in UPDATE and its 2xx response.
