### ISSUE TITLE
Stuttering audio on very low power levels

### ISSUE THREAD

**Issue by GitHubIsShortOnUsernames** [pjsip/pjproject#2561]
At the end of get_frame() in conference.c, you're setting PJMEDIA_FRAME_TYPE_NONE if tx_level is zero. However, if I interpret this correctly, you're converting tx_level to an 8-bit value. As a result, very low audio levels at 16-bit are cut off, causing rather distracting stuttering of the noise floor.

Simply disabling that check solves the problem, though I don't know what purposes it serves and as such if that is the right way to fix it.

**Comment by sauwming** [comment]
The check in question seems to be:
```
    /* Return sound playback frame. */
    if (conf->ports[0]->tx_level) {
        TRACE_((THIS_FILE, "write to audio, count=%d", 
                           conf->samples_per_frame));
        pjmedia_copy_samples( (pj_int16_t*)frame->buf, 
                              (const pj_int16_t*)conf->ports[0]->mix_buf, 
                              conf->samples_per_frame);
    } else {
        /* Force frame type NONE */
        speaker_frame_type = PJMEDIA_FRAME_TYPE_NONE;
    }
```

No, the compiler won't cast/convert `tx_level` to 8-bit value.
```
    int val = 0xFF000000;
    if (val) {
        printf("val is true\n");
    } else {
        printf("val is false\n");
    }
```
