### ISSUE TITLE
When made a Outgoing VOIP Call and disconnect without receiving at the destinatoin side, it does not disconnect properly.

### ISSUE THREAD

**Issue by parthbarot10** [pjsip/pjproject#2562]
**11:31:51.843           pjsua_call.c  Hangup all calls..
11:31:51.843           pjsua_call.c  .Call 0 hanging up: code=0..
11:31:51.844      sip_transaction.c  ....Unable to register CANCEL transaction (key exists)
11:31:51.844           pjsua_call.c  ..Failed to send end session message: Object already exists (PJ_EEXISTS) [status=70015]**

**Comment by sauwming** [comment]
I am unable to reproduce this. Please provide more info about the scenario if the issue still persists in the latest version.
