### ISSUE TITLE
Unable to find default audio device in Virtual Machine env.

### ISSUE THREAD

**Issue by HelloSilicat** [pjsip/pjproject#2563]
Hi, I have some problems in running `pjsua` app within virtual machine env.

The env is Ubuntu 18.04 in MacOS Parallel Desktop Software. When I ran it and make a new call, the error ` Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) [status=420006]` was raised.

Could anyone give me a favor? or has anyone encountered similar problems？ Thanks :)

**Comment by HelloSilicat** [comment]
I have solvedit. Just install some packages: `sudo apt-get install libasound2-dev`

**Comment by ShajeedSk** [comment]
> I have solvedit. Just install some packages: `sudo apt-get install libasound2-dev`
I did installed the same package, but issue not resolved.
