### ISSUE TITLE
PJSUA Sample App Hang while closing audio

### ISSUE THREAD

**Issue by vs1785** [pjsip/pjproject#2574]
PJSUA Sample App hangs at disconnect and only thing i can do is Ctrl+C 

10:15:52.320    pjsua_app.c  ......Call 0 is DISCONNECTED [reason=200 (Normal call clearing)]
10:15:52.321 pjsua_app_comm  ......
  [DISCONNCTD] To: "1002" <sip:1002@164.90.227.55>;tag=g1mj5846F1ZDc
    Call time: 00h:00m:05s, 1st res in 6058 ms, conn in 6228ms
    #0 audio PCMA @8kHz, sendrecv, peer=-
       SRTP status: Not active Crypto-suite:
       RX pt=8, last update:00h:00m:05.799s ago
          total 0pkt 0B (0B +IP hdr) @avg=0bps/0bps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.000   0.000   0.000   0.000
       TX pt=8, ptime=20, last update:never
          total 0pkt 0B (0B +IP hdr) @avg=0bps/0bps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.000   0.000   0.000   0.000
       RTT msec      :   0.000   0.000   0.000   0.000   0.000
10:15:52.321  pjsua_media.c  ......Call 0: deinitializing media..
10:15:52.322  pjsua_media.c  ........Media stream call00:0 is destroyed
10:15:53.321    pjsua_aud.c  Closing sound device after idle for 1 second(s)
10:15:53.323    pjsua_app.c  .Turning sound device -1 -2 OFF
10:15:53.324    pjsua_aud.c  .Closing nokiaphone sound playback device and nokiaphone sound capture device

Please advise on how to troubleshoot this.

**Comment by vs1785** [comment]
Here is output with log level 6

`--end msg--
11:30:53.927  tsx0xb4a148a4  .......State changed from Trying to Completed, event=TX_MSG
11:30:53.927  dlg0xb4a00e34  ........Transaction tsx0xb4a148a4 state changed to Completed
11:30:53.927    pjsua_app.c  ......Call 0 is DISCONNECTED [reason=200 (Normal call clearing)]
11:30:53.927    pjsua_app.c  ......Call 0 disconnected, dumping media stats..
11:30:53.928 pjsua_app_comm  ......
  [DISCONNCTD] To: "1002" <sip:1002@164.90.227.55>;tag=022c7QyXXyUKK
    Call time: 00h:00m:24s, 1st res in 6375 ms, conn in 6553ms
    #0 audio PCMA @8kHz, sendrecv, peer=-
       SRTP status: Not active Crypto-suite:
       RX pt=8, last update:00h:00m:24.706s ago
          total 0pkt 0B (0B +IP hdr) @avg=0bps/0bps
          pkt loss=0 (0.0%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.000   0.000   0.000   0.000
       TX pt=8, ptime=20, last update:never
          total 0pkt 0B (0B +IP hdr) @avg=0bps/0bps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.000   0.000   0.000   0.000
       RTT msec      :   0.000   0.000   0.000   0.000   0.000
11:30:53.928  pjsua_media.c  ......Call 0: deinitializing media..
11:30:53.933  strm0x10caac4  ........JB summary:
  size=0/eff=0 prefetch=0 level=0
  delay (min/max/avg/dev)=0/0/0/0 ms
  burst (min/max/avg/dev)=0/0/0/0 frames
  lost=0 discard=0 empty=0
11:30:53.940  pjsua_media.c  ........Media stream call00:0 is destroyed
11:30:53.941  dlg0xb4a00e34  ......Session count dec to 3 by mod-invite
11:30:54.932    pjsua_aud.c  Closing sound device after idle for 1 second(s)
11:30:54.934    pjsua_app.c  .Turning sound device -1 -2 OFF
11:30:54.935    pjsua_aud.c  .Closing nokiaphone sound playback device and nokiaphone sound capture device

>>>>

`

I cannot do anything after this, only way to exit is using Ctrl+c

I face same problem with i use pjsua2 in my c++ test application. 

My command line arguments are --log-level=6 --app-log-level=6 --clock-rate=8000 --snd-clock-rate=8000 --no-vad 

My configure command for build is

./configure --disable-video --disable-ffmpeg --disable-v4l2 --disable-libwebrtc --enable-shared

I have tested this on latest master branch as well as on 2.10

Please help.

**Comment by sauwming** [comment]
What platform is this? And which sound device backend are you using?
I suggest to run your app under the debugger and see which function cause it to stuck.
Also try with another audio device (other than nokiaphone) if you can.

**Comment by vs1785** [comment]
I tried null audio device and it is not showing this problem. 

Platform is Raspberry Pi Zero W

I found that alsa_stream_stop is not called up. It seems there is some kind of deadlock or threading issue.

**Comment by vs1785** [comment]
So 

if (stream->pb_thread)  this condition is not getting fulfilled in alsa_stream_stop and it seems it is waiting for some thread.

**Comment by BrukArkady** [comment]
Hi @vs1785 ! I have the same problem. Have you solved this issue?
