### ISSUE TITLE
Are there any plans to add support for apple silicon？

### ISSUE THREAD

**Issue by qixin1106** [pjsip/pjproject#2580]
Are there any plans to add support for apple silicon？

**Comment by olegrussu1** [comment]
tested on m1 mac , there is no sound in call(no speaker, no microphone)

**Comment by sauwming** [comment]
Yes, we have supported M1 ARM64 architecture in #2591.
And I have been using PJSIP on Mac M1 ever since with no problem.

If you encounter sound issues, please have a look at this wiki first: https://trac.pjsip.org/repos/wiki/sound-problems

**Comment by nfranke** [comment]
I back-ported that patch to 2.10 locally and it does compile now.
