### ISSUE TITLE
How to use  ios pjsip Echo Cancellation？

### ISSUE THREAD

**Issue by MaYongXiao** [pjsip/pjproject#2592]
Hello, I have a problem using pjsip 2.10

iOS calls have obvious echoes, but I don't know how to set them in code. The following code was searched from the Internet, but it didn't work when I tested the call.

media_ config.ec_ options = PJMEDIA_ ECHO_ USE_ SW_ ECHO;

status = pjsua_ init(&config, &log_ config, &media_ config);

Can you give me some advice? thank you!

**Comment by sauwming** [comment]
What you are trying to do is using software EC, while on iOS, by default it should use the built-in hardware EC that has a much better performance. You can confirm it by checking from the log if it has the message `Using VoiceProcessingIO audio unit`.

Will close this as currently issue is for bug report or feature request only. For question, please use any other means such as StackOverflow.
