### ISSUE TITLE
Pass non-enumerated ciphers to openssl, i.e. SECLEVEL=n

### ISSUE THREAD

**Issue by naf419** [pjsip/pjproject#2594]
Users of pjlib cannot configure the openssl tls connections to change openssl "security level" other than by changing the system default. Within openssl, the "security level" specifies (among other things) the minimum certificate key length. This means to allow a pjlib-linked application to initiate a tls connection with a 1024-bit key, the only way is to lower security for the entire system. It would be better if pjlib could be configured in a way that it would pass the a cipher like the common "DEFAULT@SECLEVEL=1" when creating the openssl tls connection.

--Details--
Openssl provides atleast 3 ways to specify the security level: the openssl_conf config file, using SSL_set_security_level() and through SSL_set_cipher_list() via the special "@SECLEVEL=n" cipher:
- pjsip doesn't honor the OPENSSL_CONF environment variable to specify an application-specific configuration file, so the system default is always used (honoring OPENSSL_CONF would be *better* because the env variable doesn't affect the global config, but still not connection-by-connection specific)
- pjsip doesn't use SSL_set_security_level() (and probably shouldn't - its very openssl-specific)
- pjsip does use SSL_set_cipher_list(), but the cipher list is pre-verified to only contain items contained in the "ALL:COMPLEMENTOFALL" cipher list. This prevents using the special "@SECLEVEL=n" specifier. Not sure how to make that happen with the pjsip interface using an array of enumerated ciphers instead of the openssl string style (realizing that openssl isn't the only tls backend)

**Comment by sauwming** [comment]
We are open to any contribution for this :)
