### ISSUE TITLE
Unable to set OpusConfigiruation 

### ISSUE THREAD

**Issue by smsckothakiran** [pjsip/pjproject#2595]
**Describe the bug**
A unable to setCodecOpusConfig 

**To Reproduce**

CodecOpusConfig codecOpusConfig=new CodecOpusConfig();
                    codecOpusConfig.setBit_rate(2000);
                    codecOpusConfig.setSample_rate(16000);
                    codecOpusConfig.setChannel_cnt(2);
                    codecOpusConfig.setCbr(true);
                    codecOpusConfig.setPacket_loss(1);
mEndpoint.setCodecOpusConfig(codecOpusConfig);

**Expected behavior**
Opus config properties has to be set

**Logs/Screenshots**
java.lang.UnsatisfiedLinkError: No implementation found for void org.pjsip.pjsua2.pjsua2JNI.Endpoint_setCodecOpusConfig(long, org.pjsip.pjsua2.Endpoint, long, org.pjsip.pjsua2.CodecOpusConfig)

**Desktop/Smartphone (please complete the following information):** Android

- OS, Distribution & Version: [e.g. Ubuntu 18.04.5 LTS]
- PJSIP
  - version: ... 2.10
  - related third party libraries & versions: [e.g: OpenSSL 1.1.1b]

**Smartphone (please also complete the following information):**

- Device: All Android devices

**Comment by sauwming** [comment]
It looks like you haven't installed Opus. For further questions, please use any other means such as StackOverflow. Currently issue is for bug report or feature request only.
