### ISSUE TITLE
Maximum number of TCP connections

### ISSUE THREAD

**Issue by lodemenwwwww** [pjsip/pjproject#2597]
如果客户端超过64，pjsip就出错了
If the client exceeds 64, pjsip will fail
如何设置pjsip，可以满足1000个客户端的连接
How to set pjsip？ It can satisfy the connection of 1000 clients

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/specific-guides/perf_footprint/performance.html#how-to-configure-pjsip-to-serve-thousands-of-calls
