### ISSUE TITLE
Combination "pjmedia_mem_capture_set_eof_cb2() + pjmedia_mem_capture_get_size()" not work

### ISSUE THREAD

**Issue by heretic13** [pjsip/pjproject#2599]
From https://www.pjsip.org/pjmedia/docs/html/group__PJMEDIA__MEM__CAPTURE.htm

The documentation does not describe significant differences between the registered callbacks pjmedia_mem_capture_set_eof_cb () and pjmedia_mem_capture_set_eof_cb2 ().

At the moment (pjsip 2.10) the callback function registered with pjmedia_mem_capture_set_eof_cb2 () does not allow working correctly with mem capture port.

The documentation says "Register a callback to be called when no space left in the buffer."

In a real program, I make a call to pjmedia_mem_capture_get_size () inside a callback function.
The result is always 0 ("current size of the recorded data in the buffer" as the documentation says).

Very rarely, under debugging, I saw other numbers, but they did not correspond in any way with the real buffer size.

This problem is not observed when registering a function using pjmedia_mem_capture_set_eof_cb ().

Either you have errors in the library, or the documentation does not describe how the functions work.

**Comment by medvel** [comment]
I confirm the bug is still can be reproduced, i.e. pjmedia_mem_capture_set_eof_cb2 () doesn't work so I have to use deprecated pjmedia_mem_capture_set_eof_cb() which is working fine.

Is there a chance to fix the bug?

**Comment by medvel** [comment]
Is there any possibility to fix this bug? Does nobody use this functionality?

Thanks.

**Comment by sauwming** [comment]
When it's eof, the buffer is always full, so you don't need to call `pjmedia_mem_capture_get_size()`. The size is the same as the parameter you passed to `pjmedia_mem_capture_create()`.
