### ISSUE TITLE
Problems with remote A/V sync when encountering high jitter

### ISSUE THREAD

**Issue by fryjustinc** [pjsip/pjproject#2608]
**Describe the bug**
When encountering periods of high jitter, video will often get a large delay (1 sec to 6 sec). This is especially prevelant on video initialization in other words the video starts significantly out of sync upon first rendering. I see that vid_port.c contains logic for synchronization, however this is only triggered when you have an active port for rendering (Seems like this is only when playing local video? never a remote stream?). 

**To Reproduce**

1. run pjsip with high jitter connection, also especially obvious when the stream bandwidth is also high
2. make a video call and see that often there is a substantial delay.

**Expected behavior**
audio and video should remain in sync. 

**Logs/Screenshots**
If applicable, add screenshots PJSIP logs with verbosity level 5, packet capture (e.g: using Wireshark), audio/video recording, screenshot, etc.

**Desktop/Smartphone (please complete the following information):**

- Android 7
- PJSIP
  - version: 2.16
  - related third party libraries & versions: opus audio, vp8 video

**Smartphone (please also complete the following information):**

- replicated on a number of devices including android streaming boxes and google pixel 3xl

**Additional context**

**Comment by sauwming** [comment]
Should be fixed by #2886
