### ISSUE TITLE
Audio level of outgoing call reduced with >50% on incoming 2nd call

### ISSUE THREAD

**Issue by imanpeeman** [pjsip/pjproject#2610]
**Describe the bug**
Device A and B having a call. Device C is calling A. As soon as the invite of C is received by A the outgoing audio level of device A is reduced with >50%
![pjsipIncoming](https://user-images.githubusercontent.com/6469882/102468979-7dfa8c80-4052-11eb-90a3-03d87753b1eb.png)

**To Reproduce**
Devices having a call limit of 2 (otherwise attended forwarding doesn't work)
Device A registered 
Device B registered
Device A calling B
When call is established,
Device C calling A
On the invite the outgoing audio level of Device A is reduced with appx 50%

**Expected behavior**
Outgoing volume is not muted.

**Logs/Screenshots**

While our app accepts one call at once, when a sip call is active, it will reject an 2nd incoming call with an reject message. This is implemented on the 'mother application'. 
What I can see from the log files is that independent of the response of the 'upper application' the audio device is configured and all volumes are re-calculated.
As far as I can find in the code is the configuration of the audio device always done on the invite of a call. I couldn't find a way to avoid the configuration of the audio on the invite, and e.g. move the init of the audio device to the answer method.
I've also looked into the max_calls property of the pjsip lib, but while we do need attented transfer setting the limit to 1 is not an option.

[Ticket-272.zip](https://github.com/pjsip/pjproject/files/5708406/Ticket-272.zip)

In the Zip, a wireshark trace (RTP stream from ipaddress ...162 -> ..251 shows the reduction of the outgoing audio level
The logfile (of an other moment of the trace) shows the incoming 2nd call and the audio stuff happening

**Smartphone **

- OS, Android 10
- PJSIP
  - version: 2.7.4 (React-Native-PJSip)
  - Device: Samsung xCover 4s Android 10

**Additional context**
We're using the react-native library from https://github.com/datso/react-native-pjsip

**Comment by goro-gh** [comment]
Are you sure about pjsip 2.7.4 ? As far I know, there is no such release. Also, did you try to report at `react-native-pjsip` project? 

I use C and C++ interfaces of PjProject and cannot reproduce  such behavior on 2.7.2 and master branches.
