### ISSUE TITLE
PJSUA Auto answer with sip header

### ISSUE THREAD

**Issue by romkazor** [pjsip/pjproject#2611]
Many softphones or sip phones have a feature: auto answer when Call-Info header on SIP INVITE.
It would also be nice to add something like this:

```
Answer-Mode: Auto
P-Auto-Answer: normal
Alert-Info: Ring Answer
Alert-Info: Info=Alert-Autoanswer
Call-Info:\;Answer-After=0
Call-Info: answer-after=0
```

And it would be nice to add this not only to INVITE, but also on SIP NOTIFY with "Event: talk".
Thanks.

**Comment by sauwming** [comment]
You can implement this on app level
