### ISSUE TITLE
Compilation time error

### ISSUE THREAD

**Issue by zagzol** [pjsip/pjproject#2614]
**Describe the bug**
Compilation time error. If "#define PJMEDIA_HAS_VIDEO  1" is configured the 'make' command runs to the following error.

/usr/bin/ld: output/pjlib-test-armv7l-unknown-linux-gnueabihf/timer.o: in function `stress_worker':
timer.c:(.text+0x268): undefined reference to `pj_timer_heap_schedule_w_grp_lock_dbg'
/usr/bin/ld: output/pjlib-test-armv7l-unknown-linux-gnueabihf/timer.o: in function `bench_test':
timer.c:(.text+0x604): undefined reference to `pj_timer_heap_schedule_dbg'
/usr/bin/ld: output/pjlib-test-armv7l-unknown-linux-gnueabihf/timer.o: in function `timer_test':
timer.c:(.text+0x8ec): undefined reference to `pj_timer_heap_schedule_dbg'
/usr/bin/ld: timer.c:(.text+0x1084): undefined reference to `pj_timer_heap_schedule_dbg'

**To Reproduce**
Hardware: Raspberry 2b
OS: latest Raspbian
pjsip version: 2.10 downloaded from git at 26.12.2020 19:45 CET
latest FFMPEG with VPx codecs
pjsip configuration: ./configure --enable-shared --with-bcg729 --disable-webrtc
make dep runs correctly;
then make fails.

**Logs/Screenshots**
Check the config.log and ErrorMessage.txt please!
[config_site.h.txt](https://github.com/pjsip/pjproject/files/5743578/config_site.h.txt)
[config.log](https://github.com/pjsip/pjproject/files/5743570/config.log)
[ErrorMessage.txt](https://github.com/pjsip/pjproject/files/5743571/ErrorMessage.txt)

**Additional context**
I found only one similar issue on the net, but I can't see the solution. 
https://aur.archlinux.org/packages/pjsua/?O=0&PP=10
I don't see where should I add the -DPJ_TIMER_DEBUG=0 parameter

**Comment by sauwming** [comment]
Let us know if it still happens with the latest version.
