### ISSUE TITLE
Sip Register with pjsip

### ISSUE THREAD

**Issue by amneiht** [pjsip/pjproject#2616]
I am new in pjsip . In my project i want to use pjsip-ua lib (not pjsua) . Because i need  modify Invite message to send file , or do something , and i don't need make a call. How can I regieter to sip server with pjsip-ua or pjsip . please give me some demo code . Thanks

**Comment by dccan** [comment]
this link https://pjsip.pjsip.narkive.com/D1HJZu2f/registration-with-pjsip-lib-pjsip-regc-init will help you
the simplest way is using 5 function
````c
pjsip_regc_create();
pjsip_regc_init();
pjsip_regc_set_credentials();
pjsip_regc_register();
pjsip_regc_send();

````
but you should remember two thing
1.  all of uri has a sip uri format . Such as  sip:user@server[:host]
2. Allow header of the message is only PRACK . you should modify it with `pjsip_regc_add_headers` for your program work well
example:
````c
{
		pjsip_hdr hdr_list;
		pj_list_init(&hdr_list);
		pjsip_generic_string_hdr *allow;
		pj_str_t hname = pj_str("Accept");
		pj_str_t hvalue = pj_str("application/sdp");
		allow = pjsip_generic_string_hdr_create(amsip_manager_pool, &hname,
				&hvalue);

		pj_list_push_back(&hdr_list, allow);
		pjsip_generic_string_hdr *agent;
		pj_str_t uname = pj_str("Accept");
		pj_str_t uvalue = pj_str("text/plain");
		agent = pjsip_generic_string_hdr_create(amsip_manager_pool, &uname,
				&uvalue);

		pj_list_push_back(&hdr_list, agent);
		pjsip_generic_string_hdr *al;
		pj_str_t aname = pj_str("Allow");
		pj_str_t avalue = pj_str("INVITE, ACK, CANCEL, MSRP, MESSAGE, BYE");
		al = pjsip_generic_string_hdr_create(amsip_manager_pool, &aname,
				&avalue);

		pj_list_push_back(&hdr_list, al);
		pjsip_regc_add_headers(amsip->regc, &hdr_list);
	}
````
this code has some problem , but it work for me
