### ISSUE TITLE
The playback device set is ignored in the PJSUA_SND_DEV_SPEAKER_ONLY mode

### ISSUE THREAD

**Issue by VladimirVassiliev** [pjsip/pjproject#2621]
**Describe the bug**
The playback device set using the `setPlaybackDev()` function is ignored, if the `PJSUA_SND_DEV_SPEAKER_ONLY` mode is used.

I believe the problem is in the `open_snd_dev()` function in the `pjsua_aud.c`:

```
    if (speaker_only) {
	status = pjmedia_snd_port_create_player(pjsua_var.snd_pool,
						-1,
						param->base.clock_rate,
						param->base.channel_count,
						param->base.samples_per_frame,
						param->base.bits_per_sample, 
						0,
						&pjsua_var.snd_port);

    } else {
	status = pjmedia_snd_port_create2(pjsua_var.snd_pool,
					  param, &pjsua_var.snd_port);
    }
```
The second parameter passed to `pjmedia_snd_port_create_player()` should be `param->base.play_id` instead of -1.

**Comment by trengginas** [comment]
Fixed in #2651
