### ISSUE TITLE
Support more external libraries

### ISSUE THREAD

**Issue by lgbaldoni** [pjsip/pjproject#2625]
I'm packaging pjproject for openSUSE and wondered if more third_party libraries (namely resample, g7721, ilbc) could be replaced by system libraries. I'm willing to produce the patch myself, just asking if private functions are used or if they are otherwise entangled with pj sources.

Thanks

**Comment by sauwming** [comment]
Sorry if the response comes too late. We will gladly welcome the patch if you're still interested.
As far as I know, we only use the public APIs provided.

I will close this since it's created a while ago, but feel free to submit a PR when needed.
