### ISSUE TITLE
Build failure when compiling doing parallel compile with -j24

### ISSUE THREAD

**Issue by ewildgoose** [pjsip/pjproject#2626]
I'm seeing build failures on probably quite specific conditions (likely a race) building pjproject 2.10 with a parallel compile, ie make -j24

The background is that I'm building this for a number of platforms in chroots. The platforms are relatively similar, but I can only trigger the problem on an x86 chroot (I can't trigger it on an amd64 or qemu-arm chroot)

If looks as though there is a hidden dependency with libpjsua2 depending on the build of libpjsua ? That seems to be racing and the link is attempted before the other lib is built. I can fix my package manager (gentoo) to build with a single thread, but I wonder if there is a simple resolution to set a dependency between these libs in the makefile?

Snippet of the build log is below, would it be useful to see the complete build log?

...
gcc-ranlib ../lib/libpjsua2-i686-gentoo-linux-musl.a
make[2]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjsip/build'
make -f /var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/build/rules.mak APP=PJSUA2_LIB app=pjsua2-lib ../lib/libpjsua2.so
make[2]: Entering directory '/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjsip/build'
if test ! -d ../lib; then mkdir -p ../lib; fi
i686-gentoo-linux-musl-gcc -o ../lib/libpjsua2.so.2 \
     output/pjsua2-lib-i686-gentoo-linux-musl/account.o  output/pjsua2-lib-i686-gentoo-linux-musl/endpoint.o  output/pjsua2-lib-i686-gentoo-linux-musl/json.o  output/pjsua2-lib-i686-gentoo-linux-musl/persistent.o  output/pjsua2-lib-i686-gentoo-linux-musl/types.o  output/pjsua2-lib-i686-gentoo-linux-musl/siptypes.o  output/pjsua2-lib-i686-gentoo-linux-musl/call.o  output/pjsua2-lib-i686-gentoo-linux-musl/presence.o  output/pjsua2-lib-i686-gentoo-linux-musl/media.o -lpjsua -lpjsip-ua -lpjsip-simple -lpjsip -lpjmedia-audiodev -lpjmedia-videodev -lpjmedia-codec -lpjmedia -lpjnath -lpjlib-util -lpj  -lilbccodec -lg7221codec  -lsrtp2 -lgsm  -Wl,-O1 -Wl,--as-needed -lssl -lcrypto -luuid -lm -lrt -lpthread  -lasound   -L/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjlib/lib -L/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjlib-util/lib -L/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjnath/lib -L/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjmedia/lib -L/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjsip/lib -L/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/third_party/lib           -Wl,-O1 -Wl,--as-needed -Wl,-O1 -Wl,--as-needed  -lstdc++ -shared -Wl,-soname,libpjsua2.so.2
/usr/lib/gcc/i686-gentoo-linux-musl/9.3.0/../../../../i686-gentoo-linux-musl/bin/ld: cannot find -lpjsua
collect2: error: ld returned 1 exit status
make[2]: *** [/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/build/rules.mak:113: ../lib/libpjsua2.so.2] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjsip/build'
make[1]: *** [Makefile:266: libpjsua2.so] Error 2
make[1]: *** Waiting for unfinished jobs....
ln -sf libpjsua.so.2 ../lib/libpjsua.so
make[2]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjsip/build'
make[1]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.10/work/pjproject-2.10/pjsip/build'
make: *** [Makefile:14: all] Error 1
 * ERROR: net-libs/pjproject-2.10::gentoo failed (compile phase):
 *   emake failed
 *

**Comment by sauwming** [comment]
Should be fixed by #2426, which is for release 2.11
