### ISSUE TITLE
nohup ./pjsua --config-file ./filename &   

### ISSUE THREAD

**Issue by netyuchangfa** [pjsip/pjproject#2629]
version:v2.10
enabled video
use command    " ./pjsua --config-file ./filename  " , run it in front  run ok! 
but use command  "nohup  ./pjsua --config-file ./filename & "  run it in  background  error! then  rebuild it  disabled video ,run ok!

22:26:16.608                timer.c  .Dumping timer heap:
22:26:16.608                timer.c  .  Cur size: 2 entries, max: 3070
22:26:16.608                timer.c  .  Entries:
22:26:16.608                timer.c  .    _id   Id      Elapsed Source
22:26:16.608                timer.c  .    ----------------------------------
22:26:16.608                timer.c  .    4     0       10.582  ../src/pjsua-lib/pjsua_acc.c:2164
22:26:16.608                timer.c  .    2     1       290.582 ../src/pjsip-ua/sip_reg.c:845

**Comment by sauwming** [comment]
I tested it here on a Mac machine and didn't encounter any error. Video call worked fine, too.

**Comment by netyuchangfa** [comment]
@sauwming,  use ssh login your MAC machine and run "nohup ./pjsua --config-file ./filename &", i think it also error....

error:
 Cannot switch back to console from file redirection

this file  pjsua_app.c
......
defined(PJ_WIN32) && PJ_WIN32!=0						   
 if (freopen ("CONIN$", "r", stdin) == NULL) {					
#else						   
 if (1) {					
#endif							
puts("Cannot switch back to console from file redirection");							
menuin[0] = 'q';							
menuin[1] = '\0';						   
 } else
 {							
puts("Switched back to console from file redirection");							
continue;						   
 }						
}

**Comment by netyuchangfa** [comment]
i hope linux start then auto start pjsua progress..
echo "/root/pjsua --config-file /root/filename " >> /etc/rc.local
error:
Cannot switch back to console from file redirection

or :
ssh login linux system,  nohup ./pjsua --config-file ./filename &
the same error.
"Cannot switch back to console from file redirection"


pjsip-apps/src/pjsua/pjsua_app_legacy.c
pjlib-util/src/pjlib-util/cli_console.c
