### ISSUE TITLE
Video Conference: Low Bandwidth Grey Color Appear and Quick Disappear

### ISSUE THREAD

**Issue by Meonardo** [pjsip/pjproject#2634]
**Describe the bug**
Quick flash grey color in screen while using low-bandwidth network(upload/download both 4Mbps).

**To Reproduce**
1. the video from remote, 1280*720@20fps, avg-bitrate about 2Mbps;
2. simulate the bad network in macOS(by using Network Link Conditioner), set In/Out bandwidth to 4Mbps;
3. run client app in iOS simulator;
4. video codec: OpenH264 v2.1.1 .

**Expected behavior**
4Mbps bandwidth is good enough for the video conference, no other applications running in the background, the video suppose to be good without any greyish image.

**Logs/Screenshots**
Screenshots: 
Network Link Conditioner Settings:
![WX20210204-115135](https://user-images.githubusercontent.com/13954438/106842652-5f725280-66df-11eb-938a-34e20e644297.png)

![WX20210204-115634](https://user-images.githubusercontent.com/13954438/106843040-140c7400-66e0-11eb-9f18-9dc1852d05cf.png)

Logs:

> openh264.cpp !Unpacketize error: Ignored (PJ_EIGNORED)
openh264.cpp  Decode couldn't produce picture, input nframes=64, concatenated size=16436 bytes, ret=0
oh2640x1045fc6a0  Decoder returned non error free frame, ret=32
strm0x1050a1028  RTT value 184000 usec is normalized to 65535 usec
pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x1045fc748, epub=0x1050174a8
PJSUA callback: media event: IFRM
pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x1045fc748, epub=0x104497848
PJSUA callback: media event: IFRM
vstrm0x105016628 !Sending RTCP-FB PLI packet
strm0x1050a1028 !Jitter buffer empty (prefetch=0), plc invoked
openh264.cpp !Unpacketize error: Ignored (PJ_EIGNORED)
strm0x1050a1028 !Jitter buffer starts returning normal frames (after 2 empty/lost)
openh264.cpp !Decode couldn't produce picture, input nframes=62, concatenated size=16173 bytes, ret=0
oh2640x1045fc6a0 !Decoder returned non error free frame, ret=32
pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x1045fc748, epub=0x1050174a8
PJSUA callback: media event: IFRM
pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x1045fc748, epub=0x104497848
PJSUA callback: media event: IFRM
vstrm0x105016628 !Sending RTCP-FB PLI packet
openh264.cpp !Decode couldn't produce picture, input nframes=45, concatenated size=19687 bytes, ret=36
pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x1045fc748, epub=0x1050174a8
PJSUA callback: media event: IFRM
pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x1045fc748, epub=0x104497848
PJSUA callback: media event: IFRM
!Decoder returned non error free frame, ret=32
RTT value 98000 usec is normalized to 52467 usec

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: [e.g. macOS Big Sur, iOS 14.4]
- PJSIP
  - version: PJSIP 2.10
  - applied patch(es): [e.g: patches from issue/PR xyz]
  - `configure` script params: ...
  - `config_site.h` contents: `
#define PJ_CONFIG_IPHONE 1
#define PJ_HAS_IPV6 1
#define PJMEDIA_HAS_OPENH264_CODEC 1
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL 1
#define PJMEDIA_VIDEO_DEV_HAS_OPENGL_ES 1
#define PJMEDIA_VIDEO_DEV_HAS_IOS_OPENGL 1`
  - related third party libraries & versions: OpenSSL 1.1.1b, OpenH264 2.1.1

**Smartphone (please also complete the following information):**

- Device:  iPhone XR, iOS simulators.

**Additional context**
I use Wireshark to capture the RTP stream, no package lost only Seq Errs, but the log shows missing Keyframe.
Wireshark capture log:

[captured_video_audio.pcapng.zip](https://github.com/pjsip/pjproject/files/5923032/captured_video_audio.pcapng.zip)

I try to use early version of pjsip(2.8, 2.9) the grayish image never disappear.

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
