### ISSUE TITLE
Asterisk: chan_pjsip: Deadlock between sending response and transaction layer

### ISSUE THREAD

**Issue by asteriskauto** [pjsip/pjproject#2641]
**Describe the bug**
In some cases asterisk stops answering options/register, but answers invite, server is not under high load

**Logs/Screenshots**
logs are available at [asterisk bug tracker](https://issues.asterisk.org/jira/browse/ASTERISK-29286)

**Desktop/Smartphone (please complete the following information):**

- Ubunt 18.04, Asterisk 16.16
- PJSIP
  - version: 2.10
  - applied patch(es): -
  - `configure` script params:  Asteris configured with --pjproject-bundled --jansson-bundled

**Additional context**
Acording to asterisk developers conclusion - there is a bug with the pjproject/pjsip code itself.

**Comment by sauwming** [comment]
A solution that I can think of is to follow the one in #1646. Please find attached patch and let us know if it solves the issue.

[sip_transaction_patch.txt](https://github.com/pjsip/pjproject/files/5980884/sip_transaction_patch.txt)

**Comment by asteriskauto** [comment]
Hi, @sauwming. Could you please provide insctructions how I can correctly apply this path to asterisk?

**Comment by sauwming** [comment]
I'm not very sure, but if you can find the file `sip_transaction.c` of PJSIP within Asterisk, then you can apply the change to that file.

**Comment by asteriskauto** [comment]
ok, thank you, I'll write you about results

**Comment by asteriskauto** [comment]
Applied the patch, will inform you about results
