### ISSUE TITLE
Can't build PJSUA iOS Swift 

### ISSUE THREAD

**Issue by ilhamchp** [pjsip/pjproject#2644]
**Describe the bug**
I can't build PJSUA iOS Swift version. It always show me "Undefined symbol: _pjsua_vid_win_get_info" Anyone know how to fix this?

**To Reproduce**

1. export ARCH="-arch arm64"
2. export MIN_IOS="-miphoneos-version-min=12.1"
3. ./configure-iphone
4. make dep && make clean && make
5. Open PJSUA iOS Swift project from pjsip-apps/src/pjsua/ios-swift/
6. Change Signing Team to my account
7. Clean the build folder
8. Build

**Expected behavior**

I expect the build was success like the iOS Obj C version.

**Logs/Screenshots**
If applicable, add screenshots PJSIP logs with verbosity level 5, packet capture (e.g: using Wireshark), audio/video recording, screenshot, etc.

<img width="1512" alt="Screen Shot 2021-02-17 at 09 58 54" src="https://user-images.githubusercontent.com/34804048/108150197-dc9dbe80-7106-11eb-86cb-929915d70f19.png">

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: Mac OS Catalina 10.15.7
- PJSIP
  - version: 2.10
  - applied patch(es): Update RTP timestamp on inactive/paused video stream (#2640)
  - `configure` script params: ./configure-iphone
  - `config_site.h` contents:
  - #define PJ_CONFIG_IPHONE 1
  - #include <pj/config_site_sample.h>

**Smartphone (please also complete the following information):**

- Device: iPhone 11 (iOS 14.4)

**Comment by sauwming** [comment]
You need to enable video:
https://trac.pjsip.org/repos/wiki/Getting-Started/iPhone#VideoSupport
