### ISSUE TITLE
newbie of pjsip

### ISSUE THREAD

**Issue by ewall-cauc** [pjsip/pjproject#2664]
**Describe the bug**
i am newbie to pjsip library. so i read some documents about pjsua2, and decide dive into it. after i install and configure freeswitch,  i copy same code snippets into test.cpp as below. the endpoint register successful but no media session, although i type command origante user/1000 &echo(at freeswitch console) after register. from the pcap i capture found a lot of icmp port unreachable packets. and program not setup udp port listenning about rtp audio. i donnt know how it not work    

**To Reproduce**

1. make and run

**Expected behavior**
media session and echo normal 

**Logs/Screenshots**

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version:ubuntu 18.04
- PJSIP
  - version:2.7.1
 
**Additional context**
#include <iostream>
#include <pjsua2.hpp>
#include <signal.h>

class Call : public pj::Call {
public:
    Call(pj::Account &acc, int call_id = PJSUA_INVALID_ID) : pj::Call(acc, call_id) {}
    ~Call() {};
    virtual void onCallState(pj::OnCallStateParam &prm) {
        pj::CallInfo callInfo = getInfo();
        std::cout << __FUNCTION__ << ":" << callInfo.stateText << std::endl;
    };
    virtual void onCallMediaState(pj::OnCallMediaStateParam &prm) {
        pj::CallInfo callInfo = getInfo();
        pj::AudioMedia *audioMedia;
        std::cout << __FUNCTION__ << ":hasMedia:" << hasMedia() << std::endl;
        try {
            for (unsigned int i = 0; i < callInfo.media.size(); ++i) {
                std::cout << __FUNCTION__ << ":"
                          << callInfo.media[i].type << ":"
                          << (getMedia(i) == nullptr) << std::endl;
                if (callInfo.media[i].type == PJMEDIA_TYPE_AUDIO && getMedia(i)) {
                    audioMedia = pj::AudioMedia::typecastFromMedia(getMedia(i));
                    pj::AudDevManager &audDevManager = pj::Endpoint::instance().audDevManager();
                    audDevManager.getCaptureDevMedia().startTransmit(*audioMedia);
                    audioMedia->startTransmit(audDevManager.getPlaybackDevMedia());
                }
            }
        } catch (pj::Error &error) {
            std::cout << __FUNCTION__ << ":" << error.info() << std::endl;
        }
    }
};

class Account : public pj::Account {
public:
    std::vector<Call *> calls;
    ~Account() {
        for (auto it = calls.begin(); it != calls.end(); ) {
            delete (*it);
            it = calls.erase(it);
        }
    };
    virtual void onRegState(pj::OnRegStateParam &prm) {
        pj::AccountInfo ai = getInfo();
        std::cout << (ai.regIsActive ? "*** Register:" : "*** Unregister:")
                  << " code=" << prm.code << std::endl;
    };
    virtual void onIncomingCall(pj::OnIncomingCallParam &prm) {
        Call *pCall = new Call(*this, prm.callId);
        pj::CallOpParam callOpParam;
        callOpParam.statusCode = PJSIP_SC_OK;
        pCall->answer(callOpParam);
        calls.push_back(pCall);
    };
};

volatile bool forever_loop = true;

int main() {
    pj::Endpoint *ep = new pj::Endpoint;
    ep->libCreate();
    pj::EpConfig epCfg;
    epCfg.logConfig.consoleLevel = 0;
    epCfg.uaConfig.userAgent = "pjsua";
    epCfg.uaConfig.mainThreadOnly = true;
    ep->libInit(epCfg);
    pj::TransportConfig transCfg;
    transCfg.port = 5060;
    ep->transportCreate(pjsip_transport_type_e::PJSIP_TRANSPORT_UDP, transCfg);
    ep->libStart();
    pj::AccountConfig accCfg;
    accCfg.idUri = "sip:1000@default";
    accCfg.regConfig.timeoutSec = 6000;
    accCfg.regConfig.registrarUri = "sip:192.168.5.21";
    pj::AuthCredInfo cred("digest", "default", "1000", 0, "1234");
    accCfg.sipConfig.authCreds.push_back(cred);
    Account account;
    account.create(accCfg);
    signal(SIGINT, [](int) { forever_loop = false; });
    while (forever_loop) {
        try {
            ep->utilLogWrite(4, "main.cpp", "waiting for event.....");
            ep->libHandleEvents(10000);
        } catch (pj::Error &error) {
            ep->utilLogWrite(4, "main.cpp", error.info());
        } catch (...) {
            ep->utilLogWrite(4, "main.cpp", "..........");
            forever_loop = false;
        }
    }
    ep->libDestroy();
    delete ep;
    return 0;
}

**Comment by sauwming** [comment]
It's recommended to start with our sample apps first. If everything works fine there, then you can start writing your own app.

If you experience media issue with our sample app, check the wiki page:
https://trac.pjsip.org/repos/wiki/sound-problems

For further questions, please use any other means such as StackOverflow. Currently the issue page is for bug report or feature request only.
