### ISSUE TITLE
Meet with transaction assertation on retransmit

### ISSUE THREAD

**Issue by vit1251** [pjsip/pjproject#2665]
**Describe the bug**

```
pjproject/src/pjsip/pjsip/sip_transaction.c:3267: pj_status_t tsx_on_state_completed_uas(pjsip_transaction *, pjsip_event *): Assertion `event->type == PJSIP_EVENT_TX_MSG && event->body.tx_msg.tdata == tsx->last_tx' failed.
```

**To Reproduce**

1. Prepare network to 80% overloading
2. Make outgoing call

**Expected behavior**

Process complete.

**Desktop/Smartphone (please complete the following information):**

- Linux bases
- PJSIP
  - version: 2.10

**Additional context**

Overload network.

**Comment by sauwming** [comment]
There have been some changes in `sip_transaction`, and the assertion is no longer the same.
So please test with the latest revision, in particular the fix in #2350.

If the problem persists, please attach the PJSIP log and the stack trace of the assertion.
