### ISSUE TITLE
Leak memory for UPDATE method

### ISSUE THREAD

**Issue by roman6334** [pjsip/pjproject#2668]
if the device periodically sends UPDATE, then each update leak 28 byte memory.

**To Reproduce**
- I run two device client and server. Both device using PJSIP.
- The standard connection with INVITE occurs. It's ok.
- Then the communication session lasts more than 10 hours.
- Each 15 minutes send UPDATE and receive "200 OK". And each UPDATE leak 28 byte in memory.

**Embedded**
- PJSIP
  - version: 2.7.2

**Comment by roman6334** [comment]
I have new the details about leak of memory.
I dump all active pool of PJSIP.

First dump: dlg0x1949288:     **9328** of    10240 (91%) used
After 15 mituts and UPDATE message
Second dump: dlg0x1949288:     **9356** of    10240 (91%) used
Difference is 9356 - 9328 = 28 byte

Log read:
00:30:42.122   dlg0x1949288 !Refreshing session after 900s (expiration period=1800s)

This is sip_timer.c timer_cb function.

**Comment by sauwming** [comment]
Part of memory pool cannot be released, you can only release the entire pool. So growing usage in memory pool is quite normal.

**Comment by the-braveknight** [comment]
> I have new the details about leak of memory. I dump all active pool of PJSIP.
> 
> First dump: dlg0x1949288: **9328** of 10240 (91%) used After 15 minuts and UPDATE message Second dump: dlg0x1949288: **9356** of 10240 (91%) used Difference is 9356 - 9328 = 28 byte
> 
> Log read: 00:30:42.122 dlg0x1949288 !Refreshing session after 900s (expiration period=1800s) This log message in sip_timer.c timer_cb function.

For some reason, an outgoing call is dropping exactly after 900 seconds on iOS. Any ideas where to go from here?
