### ISSUE TITLE
 undefined reference to `pj_ice_strans_update_check_list'

### ISSUE THREAD

**Issue by jrch2k20** [pjsip/pjproject#2669]
**Describe the bug**
Compilation fails with 

/usr/bin/ld: output/pjnath-test-x86_64-unknown-linux-gnu/ice_test.o: in function `timer_new_cand':
ice_test.c:(.text+0xcc8): undefined reference to `pj_ice_strans_update_check_list'
/usr/bin/ld: ice_test.c:(.text+0xf31): undefined reference to `pj_ice_strans_update_check_list'
collect2: error: ld returned 1 exit status
make[2]: *** [/Peliculas/backup/Projects/x86_64/Sources/Build/pjproject/src/pjproject-2.11/build/rules.mak:125: ../bin/pjnath-test-x86_64-unknown-linux-gnu] Error 1

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: ArchLinux
- PJSIP
  - version: 2.11
  - applied patch(es): none
  - `configure` script params: --prefix=/usr \
    --with-external-speex \
    --with-external-srtp \
    --with-external-pa \
    --with-external-gsm \
    --enable-libsamplerate \
    --enable-shared \
    --enable-epoll \ 
  - `config_site.h` contents: 
#define PJ_DEBUG 0
#define PJ_TIMER_DEBUG 0
#define PJ_HAS_IPV6 1
  - related third party libraries & versions: latest is ArchLinux

GCC
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC)

**Comment by andreapier** [comment]
This also happens if target is `aarch64`.

**Comment by jrch2k20** [comment]
Probable fix, it seems to build fine as long as pjproject 2.10 is completely uninstalled first

**Comment by andreapier** [comment]
Yes, I can confirm this. Tried yesterday.

**Comment by sauwming** [comment]
The function is defined here:
https://github.com/pjsip/pjproject/blob/master/pjnath/src/pjnath/ice_strans.c#L1628

So yes, just make sure to clean, or realclean, the old build first.
