### ISSUE TITLE
你好，使用729协议拨号，呼出后会闪退，急求帮助

### ISSUE THREAD

**Issue by jj89757hhb** [pjsip/pjproject#2674]
15:06:03.218         inv0x158837ca8  ....SDP negotiation done: Success
15:06:03.218          pjsua_media.c  .....Call 0: updating media..
15:06:03.218          pjsua_media.c  .......Media stream call00:0 is destroyed
15:06:03.218            pjsua_aud.c  ......Audio channel update..
15:06:03.219        strm0x15784b628  .......VAD temporarily disabled
15:06:03.220        strm0x15784b628  .......Encoder stream started
15:06:03.220        strm0x15784b628  .......Decoder stream started
15:06:03.220          pjsua_media.c  ......Audio updated, stream #0: G729 (sendrecv)
15:06:03.221            pjsua_aud.c  .....Conf connect: 1 --> 0
15:06:03.221           conference.c  ......Port 1 (sip:18689364569@118.178.179.234:5170) transmitting to port 0 (iPhone IO device)
15:06:03.221            pjsua_aud.c  .....Conf connect: 0 --> 1
15:06:03.221           conference.c  ......Port 0 (iPhone IO device) transmitting to port 1 (sip:18689364569@118.178.179.234:5170)
Division Error var1=16383  var2=0

**Comment by sauwming** [comment]
This doesn't seem to be PJSIP issue.
`Division Error var1=16383 var2=0`
