### ISSUE TITLE
Negotiation for telephone-event not working if offered as /16000 first

### ISSUE THREAD

**Issue by FrankPfattheicher** [pjsip/pjproject#2675]
**Incoming calls are negotiated without telephone-events if offered as /16000**
Incoming calls that offer telephone-events as telephone-events/16000 first
and as telephone-events/8000 second with the same rtpmap are
negotiated WITHOUT any telephone-events, i.e. DTMF is not working.

**To Reproduce**

1. Place an incoming call which offers telephone-events as follows

```
INVITE sip:491111111111@xxx.xxx.xxx.xxx:52485;transport=udp SIP/2.0
To: <sip:491111111111@xxx.xxx.xxx.xxx>
From: <sip:492222222222@yyy.yyy.yyy.yyy>;tag=snl_3tM4jBPw0g
Call-ID: SEC11-301640a-401640a-1-y6qk2uicDNw9
CSeq: 1235 INVITE
Contact: <sip:492222222222@yyy.yyy.yyy.yyy:5060;maddr=yyy.yyy.yyy.yyy>
Via: SIP/2.0/UDP yyy.yyy.yyy.yyy:5060;branch=z9hG4bKSEC-301640a-401640a-1-hqkXC0k452
X-Siemens-Call-Type: Org-NWid-external-public
Content-Type: application/sdp
Content-Length: 282
Accept-Language: en;q=0.0
Allow: REGISTER, INVITE, ACK, BYE, CANCEL, NOTIFY, REFER, INFO
Session-Expires: 1800;refresher=uac
Min-SE: 1800
Supported: timer
Date: Tue, 23 Mar 2021 08:44:31 GMT
Max-Forwards: 50

v=0
o=- 0 0 IN IP4 217.0.26.165
s=on transit
c=IN IP4 10.100.1.21
t=0 0
m=audio 7882 RTP/AVP 8 101 101 18 0
b=AS:80
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/16000
a=rtpmap:101 telephone-event/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:0 PCMU/8000
```
**Expected behavior**
Due to only supproted /8000 codecs telephone-events should be negotiated as telephone-events/8000.

**Logs/Screenshots**
Currently the response is as follows:

```
SIP/2.0 200 OK
Via: SIP/2.0/UDP yyy.yyy.yyy.yyy:5060;received=yyy.yyy.yyy.yyy;branch=z9hG4bKSEC-301640a-401640a-1-hqkXC0k452
Call-ID: SEC11-301640a-401640a-1-y6qk2uicDNw9
From: <sip:492222222222@yyy.yyy.yyy.yyy>;tag=snl_3tM4jBPw0g
To: <sip:491111111111@xxx.xxx.xxx.xxx>;tag=eca59a744ff64a31b9cfcf06f5082b39
CSeq: 1235 INVITE
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Contact: <sip:491111111111@xxx.xxx.xxx.xxx:52485;ob>
Supported: replaces, 100rel, timer, norefersub
Session-Expires: 1800;refresher=uac
Require: timer
Content-Type: application/sdp
Content-Length:   260

v=0
o=- 3825481471 3825481472 IN IP4 xxx.xxx.xxx.xxx
s=pjmedia
b=AS:84
t=0 0
a=X-nat:0
m=audio 4052 RTP/AVP 8
c=IN IP4 xxx.xxx.xxx.xxx
b=TIAS:64000
a=rtcp:4053 IN IP4 xxx.xxx.xxx.xxx
a=sendrecv
a=rtpmap:8 PCMA/8000
a=ssrc:1791645131 cname:31c1466c7d775061
```

**Desktop/Smartphone (please complete the following information):**

- OS, Distribution & Version: Windows 10 LTSC 1809, Server 2019 1809
- PJSIP
  - version: 2.10
  - using C# with pjsip-pjsua2-cs 2.10.1

**Comment by FrankPfattheicher** [comment]
Add THISthis test case to show error:

if telephone-events are in order 8000 first, then 16000

```
			"a=rtpmap:101 telephone-event/8000\r\n"
			"a=rtpmap:101 telephone-event/16000\r\n"
```

the test succeeds.

If reordered as 16000 first, it fails.
```
			"a=rtpmap:101 telephone-event/8000\r\n"
			"a=rtpmap:101 telephone-event/16000\r\n"
```
This is not OK, due there is a audio codec with 8000 only, the events with 16000 should be ignored,



```
/* test 18: */
	{
		/*********************************************************************
		 * Ticket #2675: : Negotiation for telephone-event offered as /16000 first
		 */

		"Ticket #2088: Handle multiple telephone-event formats",
		2,
		{
		  {
			REMOTE_OFFER,
			/* Bob sends offer: */
			"v=0\r\n"
			"o=- 0 0 IN IP4 host.biloxi.example.com\r\n"
			"s=bob\r\n"
			"c=IN IP4 host.biloxi.example.com\r\n"
			"t=0 0\r\n"
			"m=audio 7882 RTP/AVP 8 101 101 18 0\r\n"
		  	"b=AS:80\r\n"
			"a=rtpmap:8 PCMA/8000\r\n"
			"a=rtpmap:101 telephone-event/16000\r\n"
			"a=rtpmap:101 telephone-event/8000\r\n"
			"a=rtpmap:18 G729/8000\r\n"
		  	"a=fmtp:18 annexb=no\r\n"
		  	"a=rtpmap:0 PCMU/8000\r\n"
			"",
		/* Alice initial capability: */
		"v=0\r\n"
		"o=alice 2890844526 2890844526 IN IP4 host.atlanta.example.com\r\n"
		"s=alice\r\n"
		"c=IN IP4 host.atlanta.example.com\r\n"
		"t=0 0\r\n"
		"m=audio 4000 RTP/AVP 0 100 96 98\r\n"
		"a=rtpmap:0 PCMA/8000\r\n"
		"a=rtpmap:100 Speex/8000\r\n"
		"a=rtpmap:96 telephone-event/8000\r\n"
		"a=rtpmap:98 telephone-event/16000\r\n"
		"",
		/* Alice's local SDP should be: */
		"v=0\r\n"
		"o=alice 2890844526 2890844527 IN IP4 host.atlanta.example.com\r\n"
		"s=alice\r\n"
		"c=IN IP4 host.atlanta.example.com\r\n"
		"t=0 0\r\n"
		"m=audio 4000 RTP/AVP 101 0\r\n"
		"a=rtpmap:0 PCMA/8000\r\n"
		"a=rtpmap:101 telephone-event/8000\r\n"
		"",
	  },
	  {
		LOCAL_OFFER,
		/* Alice updates offer */
		"v=0\r\n"
		"o=alice 2890844526 2890844528 IN IP4 host.atlanta.example.com\r\n"
		"s=alice\r\n"
		"c=IN IP4 host.atlanta.example.com\r\n"
		"t=0 0\r\n"
		"m=audio 4000 RTP/AVP 0 97 98 99\r\n"
		"a=rtpmap:0 PCMA/8000\r\n"
		"a=rtpmap:97 Speex/8000\r\n"
		"a=rtpmap:98 telephone-event/8000\r\n"
		"a=rtpmap:99 telephone-event/16000\r\n"
		"",
		/* Receive Bob's answer: */
		"v=0\r\n"
		"o=bob 2808844564 2808844563 IN IP4 host.biloxi.example.com\r\n"
		"s=bob\r\n"
		"c=IN IP4 host.biloxi.example.com\r\n"
		"t=0 0\r\n"
		"m=audio 3000 RTP/AVP 0 100\r\n"
		"a=rtpmap:0 PCMA/8000\r\n"
		"a=rtpmap:100 telephone-event/8000\r\n"
		"",
		/* Alice's local SDP should be: */
		"v=0\r\n"
		"o=alice 2890844526 2890844528 IN IP4 host.atlanta.example.com\r\n"
		"s=alice\r\n"
		"c=IN IP4 host.atlanta.example.com\r\n"
		"t=0 0\r\n"
		"m=audio 4000 RTP/AVP 0 98\r\n"
		"a=rtpmap:0 PCMA/8000\r\n"
		"a=rtpmap:98 telephone-event/8000\r\n"
		"",
	  }
	}
```

**Comment by sauwming** [comment]
Currently when searching for a certain rtpmap in the SDP, if there are multiple listed, we only consider the first one:

in `match_offer() sdp_neg.c`
```
		/* Get the rtpmap for the payload type in the master. */
		a = pjmedia_sdp_media_find_attr2(master, "rtpmap", 
						 &master->desc.fmt[i]);
```

So in this case, the rtpmap 101 will always return to whichever telephone event listed first.

**Comment by FrankPfattheicher** [comment]
@sauwming yes, that is the reason for this issue ...

It should select the best fit (even through the first is even not applicable at all).

**Comment by sauwming** [comment]
The thing is I'm not convinced that this is allowed by the RFC so I'm rather reluctant to fix it.

RFC 4566 (and 8866) says this:
```
For dynamic payload type assignments the "a=rtpmap:" attribute (see
      Section 6) SHOULD be used to map from an RTP payload type number
      to a media encoding name that identifies the payload format.
```
and
```
Up to one "a=rtpmap:" attribute can be defined for each media format specified.
```
Even though I can't find any statement that explicitly says it's forbidden, if my interpretation is correct, from the above I believe we can infer that one RTP payload number should map to one "rtpmap".

So my recommendation for now is to fix the remote and if that's not possible, handle it in the application level instead, such as by using pjsip module, to modify the SDP so that it's acceptable.

**Comment by FrankPfattheicher** [comment]
@sauwming  Ok, i see,
" fix the remote " is not possible due it is "all mobile phones" of germany,,,

There was no problem until March, 17 - maybe ther were updates to the mobile network(s) !???
Nobody will be able to answer that.

So i would like to fix it my own (pull request) or doing that "jsip module, to modify the SDP" thing.
Is there an example and/or description how to do that?a

**Comment by sauwming** [comment]
You can check https://github.com/johanlantz/pj-nat64 for a reference. It uses the module to replace IPv4 occurrences with IPv6 in the SDP. For your case though, it should be much simpler. You probably only need to change the topmost tel-event clock rate from 16000 to 8000.

**Comment by FrankPfattheicher** [comment]
@sauwming thanks for your advice, this approach is working for me (meanwhile).
https://github.com/FrankPfattheicher/pj-media-neg 

I would like to change this issue to a feature-request due it is a real world problem...
But have no idea to do that.

**Comment by sauwming** [comment]
Done. changed the issue type.

And glad you get it working.

**Comment by FrankPfattheicher** [comment]
Just found an other case not working...

![image](https://user-images.githubusercontent.com/921532/116420732-8b185b00-a83e-11eb-8d8e-a160905d7afc.png)

**Comment by FrankPfattheicher** [comment]
And another...

![image](https://user-images.githubusercontent.com/921532/116422108-b485b680-a83f-11eb-89d1-c8e7b92c8aaf.png)

**Comment by shiyuanyou** [comment]
> Just found an other case not working...
> 
> ![image](https://user-images.githubusercontent.com/921532/116420732-8b185b00-a83e-11eb-8d8e-a160905d7afc.png)

Hi, I'm having the same problem. Is there a good solution?

**Comment by plsappino** [comment]
Hi,
I am using version 2.12.1 & version 2.12.  I have found that for "incoming call", the DTMF tones are not working.  It looks like pjsip is processing them (as per logs) but they are not going out.  The DTMF tones are working fine for outgoing calls in these version.  This feature was working fine till 2.11 for both incoming & outgoing.  Something has changed between 2.11 & 2.12 by which DTMF for incoming calls are not working any more.

Easy to replicate:  Simply setup Call forwarding in Google Voice to your number which has pjsip.  Enable announcement feature in Google voice.  Now call that Google Voice number from any external number and speak your name when Google voice asks identification.  The call will be received on the pjsip side phone but when you press "1" it looks like pjsip is processing it but nothing happens.
Many banks initiate automated verification processes make calls to end user and have them enter code for verification.  If the receiving side phone has pjsip, it doesn't process the DTMF punched by the user.

Any insight as to what has changed will be helpful.

Thanks
Phil




> **Incoming calls are negotiated without telephone-events if offered as /16000** Incoming calls that offer telephone-events as telephone-events/16000 first and as telephone-events/8000 second with the same rtpmap are negotiated WITHOUT any telephone-events, i.e. DTMF is not working.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Place an incoming call which offers telephone-events as follows
> 
> ```
> INVITE sip:491111111111@xxx.xxx.xxx.xxx:52485;transport=udp SIP/2.0
> To: <sip:491111111111@xxx.xxx.xxx.xxx>
> From: <sip:492222222222@yyy.yyy.yyy.yyy>;tag=snl_3tM4jBPw0g
> Call-ID: SEC11-301640a-401640a-1-y6qk2uicDNw9
> CSeq: 1235 INVITE
> Contact: <sip:492222222222@yyy.yyy.yyy.yyy:5060;maddr=yyy.yyy.yyy.yyy>
> Via: SIP/2.0/UDP yyy.yyy.yyy.yyy:5060;branch=z9hG4bKSEC-301640a-401640a-1-hqkXC0k452
> X-Siemens-Call-Type: Org-NWid-external-public
> Content-Type: application/sdp
> Content-Length: 282
> Accept-Language: en;q=0.0
> Allow: REGISTER, INVITE, ACK, BYE, CANCEL, NOTIFY, REFER, INFO
> Session-Expires: 1800;refresher=uac
> Min-SE: 1800
> Supported: timer
> Date: Tue, 23 Mar 2021 08:44:31 GMT
> Max-Forwards: 50
> 
> v=0
> o=- 0 0 IN IP4 217.0.26.165
> s=on transit
> c=IN IP4 10.100.1.21
> t=0 0
> m=audio 7882 RTP/AVP 8 101 101 18 0
> b=AS:80
> a=rtpmap:8 PCMA/8000
> a=rtpmap:101 telephone-event/16000
> a=rtpmap:101 telephone-event/8000
> a=rtpmap:18 G729/8000
> a=fmtp:18 annexb=no
> a=rtpmap:0 PCMU/8000
> ```
> 
> **Expected behavior** Due to only supproted /8000 codecs telephone-events should be negotiated as telephone-events/8000.
> 
> **Logs/Screenshots** Currently the response is as follows:
> 
> ```
> SIP/2.0 200 OK
> Via: SIP/2.0/UDP yyy.yyy.yyy.yyy:5060;received=yyy.yyy.yyy.yyy;branch=z9hG4bKSEC-301640a-401640a-1-hqkXC0k452
> Call-ID: SEC11-301640a-401640a-1-y6qk2uicDNw9
> From: <sip:492222222222@yyy.yyy.yyy.yyy>;tag=snl_3tM4jBPw0g
> To: <sip:491111111111@xxx.xxx.xxx.xxx>;tag=eca59a744ff64a31b9cfcf06f5082b39
> CSeq: 1235 INVITE
> Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
> Contact: <sip:491111111111@xxx.xxx.xxx.xxx:52485;ob>
> Supported: replaces, 100rel, timer, norefersub
> Session-Expires: 1800;refresher=uac
> Require: timer
> Content-Type: application/sdp
> Content-Length:   260
> 
> v=0
> o=- 3825481471 3825481472 IN IP4 xxx.xxx.xxx.xxx
> s=pjmedia
> b=AS:84
> t=0 0
> a=X-nat:0
> m=audio 4052 RTP/AVP 8
> c=IN IP4 xxx.xxx.xxx.xxx
> b=TIAS:64000
> a=rtcp:4053 IN IP4 xxx.xxx.xxx.xxx
> a=sendrecv
> a=rtpmap:8 PCMA/8000
> a=ssrc:1791645131 cname:31c1466c7d775061
> ```
> 
> **Desktop/Smartphone (please complete the following information):**
> 
> * OS, Distribution & Version: Windows 10 LTSC 1809, Server 2019 1809
> * PJSIP
>   
>   * version: 2.10
>   * using C# with pjsip-pjsua2-cs 2.10.1



> Done. changed the issue type.
> 
> And glad you get it working.
