### ISSUE TITLE
Support OpenH264 version 2.x

### ISSUE THREAD

**Issue by nanangizz** [pjsip/pjproject#2677]
Currently officially we support OpenH264 up to v1.6 (see #1947), which is too old now.

**Comment by sauwming** [comment]
Tested here with OpenH264 2.1.1 and it seems to work fine on iOS and Mac.

**Comment by nanangizz** [comment]
2.1.1 seems to work fine too on Win32 (MSVC2005).

**Comment by sauwming** [comment]
So I believe we can close this.

**Comment by trengginas** [comment]
I have some issues in building 2.1.1 for android, specifically when using ndk-r19 or newer. 
Reference: 
- https://github.com/cisco/openh264/issues/3318
- https://github.com/cisco/openh264/pull/3261

However, the branch https://github.com/cisco/openh264/tree/openh264v2.1.0 was successfully built.

**Comment by nanangizz** [comment]
> I have some issues in building 2.1.1 for android, specifically when using ndk-r19 or newer.

Just FYI, for the win32 test, instead of building from source, actually I just took the binary from [here](https://github.com/cisco/openh264/releases/tag/v2.1.1) and the header files from [here](https://github.com/cisco/openh264/tree/v2.1.1/codec/api/svc).

**Comment by emretufekci** [comment]
As @trengginas mentioned for android only 2.1.1 branch works well which is not released.

As i mentioned here some results maybe confusing https://github.com/cisco/openh264/pull/3261#issuecomment-867728522
Also, this doc: https://trac.pjsip.org/repos/wiki/Getting-Started/Android tells us using `/Users/me/openh264/android/*.so` instead `/openh264/*.so` it's confusing cause there is no android folder in h264 anymore.

Good to mention about branch things or may be you can point this is as known issue.

**Comment by sauwming** [comment]
You can use the prebuilt binary provided instead, or is there any reason not to?

As for the directory, the doc only provided an example, the point is to copy the .so files.

**Comment by emretufekci** [comment]
So, following part is not big deal?

```
Configuring

To enable video, append this into config_site.h:

#define PJMEDIA_HAS_VIDEO 1

Specify third-party video libraries when invoking ./configure-android, e.g:

$ ./configure-android --with-openh264=/Users/me/openh264/android

Make sure openh264 is detected by ./configure-android:

...
Using OpenH264 prefix... /Users/me/openh264/android
checking OpenH264 availability... ok
...

```

or `--with-openh264=/Users/me/openh264/android` this part should include .so files?

**Comment by emretufekci** [comment]
When i using prebuilt binaries via this
`TARGET_ABI=arm64-v8a ./configure-android --use-ndk-cflags --with-ssl=$PWD/openssl-OpenSSL_1_1_1k`

Gives following error:
```
../src/pjmedia-codec/openh264.cpp:35:10: fatal error: 'wels/codec_api.h' file not found
#include <wels/codec_api.h>

```
Added following to the config_site.h
```
#define PJMEDIA_HAS_VIDEO 1
#define PJMEDIA_HAS_OPENH264_CODEC 1
```

**Comment by emretufekci** [comment]
I got the issue, .so file is enough actually, these config_site.h things only for gnu targets, sorry for disturbing you :)

**Comment by bukira** [comment]
how did you get it working on iOS? I cannot get it to work, please help me with the steps to get it working on iOS

**Comment by bukira** [comment]
> Tested here with OpenH264 2.1.1 and it seems to work fine on iOS and Mac.

HOW?

**Comment by BMatthai** [comment]
> > Tested here with OpenH264 2.1.1 and it seems to work fine on iOS and Mac.
> 
> HOW?

Unless I'm mistaken I think OpenH264 2.X support is in pjproject v 2.12 (unreleased). Current support is still OpenH264 1.6
