### ISSUE TITLE
Android: crash when accepting incoming call

### ISSUE THREAD

**Issue by JamesNickel** [pjsip/pjproject#2684]
I recently updated the library in my Android app from 2.9 to 2.10 and I've been using it with Asterisk.
In version 2.10 when the app accepts an incoming call, PJSIP throws a fatal error and the app crashes.
Version 2.9 was working fine and this error occurs only with version 2.10 no matter which Android version or Asterisk version would be.
The only error that PJSIP provides in the log is this:

```
../src/pjsip/sip_transaction.c:3267: pj_status_t tsx_on_state_completed_uas(pjsip_transaction *, pjsip_event *): assertion "event->type == PJSIP_EVENT_TX_MSG && event->body.tx_msg.tdata == tsx->last_tx" failed

Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 15952 (telecom.simotel), pid (telecom.simotel)
```

1- Build the library for Android with APP_PLATFORM=android-21 and ndk-22.0.7026061
2- Run the app on an Android device
3- Try to answer an incoming sip call

- OS, Distribution & Version: Android (10, 6 or any other)
- PJSIP
  - version: 2.10
  - applied patch(es): none
  - `configure` script params: default (same as [instructed](https://trac.pjsip.org/repos/wiki/Getting-Started/Android))
  - `config_site.h` contents: default (same as instructed)
```
  /* Activate Android specific settings in the 'config_site_sample.h' */
#define PJ_CONFIG_ANDROID 1
#include <pj/config_site_sample.h>
```
  - related third party libraries & versions: bcg729-1.1.1

- Device: Samsung A31, Samsung A5, and other devices as well

**Comment by sauwming** [comment]
Let us know if it still happens with the latest version
