### ISSUE TITLE
Setting custom TCP/TLS Port

### ISSUE THREAD

**Issue by andrwebb2020** [pjsip/pjproject#2694]
**Is your feature request related to a problem? Please describe.**
Id like to be able to control the port that pjsip registers with on TLS for cybersecurity reasons. When UDP transport is used the port it creates matches the pjsua_transport_config.port field, i.e. im able to set it to be 5060 and will see it register with that port on a pbx server. From my understanding when TCP and TLS transport is used and an account is registering, another TLS transport will be created on a random port number and I'm unaware of any way to control which port number is chosen. I.e. here it chooses 44685 when instead I would like it to be 5061 for example. 

```
19:46:05.974    pjsua_acc.c  Adding account: id="hFfFS6VpTz" <sip:201@10.10.90.7:5061;transport=tls>
19:46:05.975    pjsua_acc.c  .Account "hFfFS6VpTz" <sip:201@10.10.90.7:5061;transport=tls> added with id 0
19:46:05.975    pjsua_acc.c  .Acc 0: setting registration..
19:46:05.975  tlsc0x1f44a7c  ..TLS client transport created
19:46:05.976  tlsc0x1f44a7c  ..TLS transport 10.10.90.254:44685 is connecting to 10.10.90.7:5061...
19:46:05.976       endpoint  ..Request msg REGISTER/cseq=58533 (tdta0x1f464e4) created.
19:46:05.976   tsx0x1f474ec  ...Transaction created for Request msg REGISTER/cseq=58534 (tdta0x1f464e4)
19:46:05.976   tsx0x1f474ec  ..Sending Request msg REGISTER/cseq=58534 (tdta0x1f464e4) in state Null
19:46:05.976  sip_resolve.c  ...Target '10.10.90.7:5061' type=TLS resolved to '10.10.90.7:5061' type=TLS (TLS transport)
19:46:05.977   pjsua_core.c  ...TX 586 bytes Request msg REGISTER/cseq=58534 (tdta0x1f464e4) to TLS 10.10.90.7:5061:
REGISTER sip:10.10.90.7:5061;transport=tls SIP/2.0
Via: SIP/2.0/TLS 10.10.90.254:44685;rport;branch=z9hG4bKPj1ebb7ae4-56f7-4f9c-9381-26880b162a4b;alias
Max-Forwards: 70
From: "hFfFS6VpTz" <sip:201@10.10.90.7>;tag=8e06fbb6-401a-41b0-880f-7c2d6e2bdadd
To: "hFfFS6VpTz" <sip:201@10.10.90.7>
Call-ID: ba4c9ef1-894a-4f8b-b21d-de595fe11c1c
CSeq: 58534 REGISTER
User-Agent: Webb Phone
Contact: "hFfFS6VpTz" <sip:201@10.10.90.254:44685;transport=TLS>
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0
```

**Describe the solution you'd like**
Could there be some option added on the tcp_transport or pjlib or account config level to force the port to match the pjsua_transport_config.port field on TCP/TLS like it already does with UDP or an option to choose a range of allowable ones?

**Comment by sauwming** [comment]
The source port is selected and assigned by the OS and you can't change it.

What you can do is to create a listener at a designated port so you can accept incoming traffic to a certain port.
