### ISSUE TITLE
PJSIP with call audio capturing and streaming features

### ISSUE THREAD

**Issue by stealth-program** [pjsip/pjproject#2700]
I want to use pjsip java wrapper with discord client. So I need to get pcm frames and put pcm frames to audio stream (pcm bytes). Everyone needs this feature.
Moreover, there is some implementation of that feature: https://github.com/isabyr/pjsipstreamer . Unfortunately, this works only in plain c++ and Python, not Java. Can you please merge that feature in your master branch?

**Comment by sauwming** [comment]
True, this seems to be quite a popular request. Duplicate of #2352 so any update will be posted there instead.
