### ISSUE TITLE
[ANNOUNCE]: sipnagios, a Nagios Plugin to check Call Quality in SIP VoIP (compatible with checkmk, etc)

### ISSUE THREAD

**Issue by gmaruzz** [pjsip/pjproject#2702]
https://github.com/gmaruzz/sipnagios

Nagios Plugin to check Call Quality in SIP VoIP (compatible with checkmk, etc)

sipnagios implements the Nagios plugin API for monitoring and performance data.

sipnagios.c is a modification of the original siprtp.c sample in pjproject distribution. Supposedly, it works on Linux, Windows, and anywhere you can compile pjproject on.

It makes a call, checks all the various resulting values (mos, rtt, pdd, tta, jitter, packet loss, bytes and packets transferred, and so on). It verifies these values are included into acceptable, warning, or critical ranges.

If the call has gone well, sipnagios print performance data for Nagios graphs, and returns 0.

If the call fails, or if its measured values are not inside acceptable ranges, it exits with Nagios conventional WARNING or CRITICAL values.

**Comment by sauwming** [comment]
Thank you for the plugin. Currently the issue page is for bug report only.
