### ISSUE TITLE
There maybe a bug in file pjsua_vid.c

### ISSUE THREAD

**Issue by jiaxiaolong** [pjsip/pjproject#2704]
pjsip version is 2.10,
I ported pj to arm platform,segment fault in lookup_dev,I found it was because:
in funciton "pjsua_vid_channel_init(pjsua_call_media *call_med)"
	pjmedia_vid_dev_get_info(call_med->strm.v.rdr_dev, &info);
	call_med->strm.v.rdr_dev = info.id;

the variable info without initialization，,I printed info.id,the value was 2992052.

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
