### ISSUE TITLE
in ios,the vidio orientation is invalid

### ISSUE THREAD

**Issue by houhm** [pjsip/pjproject#2711]
in ios,the vidio orientation is invalid, the code call is showed below:

- (void)viewDidLoad
{
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.

    [[UIApplication sharedApplication] beginReceivingRemoteControlEvents];
    
    [[UIDevice currentDevice] beginGeneratingDeviceOrientationNotifications];
    [[NSNotificationCenter defaultCenter] addObserver:self
        selector:@selector(orientationChanged:)
        name:UIDeviceOrientationDidChangeNotification
        object:[UIDevice currentDevice]];
}
- (void)orientationChanged:(NSNotification *)note
{

#if PJSUA_HAS_VIDEO
    const pjmedia_orient pj_ori[4] =
    {
        PJMEDIA_ORIENT_ROTATE_90DEG,  /* UIDeviceOrientationPortrait */
        PJMEDIA_ORIENT_ROTATE_270DEG, /* UIDeviceOrientationPortraitUpsideDown */
        PJMEDIA_ORIENT_ROTATE_180DEG, /* UIDeviceOrientationLandscapeLeft,
                                         home button on the right side */
        PJMEDIA_ORIENT_NATURAL        /* UIDeviceOrientationLandscapeRight,
                                         home button on the left side */
    };
    static pj_thread_desc a_thread_desc;
    static pj_thread_t *a_thread;
    static UIDeviceOrientation prev_ori = 0;
    UIDeviceOrientation dev_ori = [[UIDevice currentDevice] orientation];
    int i;

    if (dev_ori == prev_ori) return;

    NSLog(@"Device orientation changed: %d", (int)(prev_ori = dev_ori));

    if (dev_ori >= UIDeviceOrientationPortrait &&
        dev_ori <= UIDeviceOrientationLandscapeRight)
    {
        if (!pj_thread_is_registered()) {
            pj_thread_register("ipjsua", a_thread_desc, &a_thread);
        }

        /* Here we set the orientation for all video devices.
         * This may return failure for renderer devices or for
         * capture devices which do not support orientation setting,
         * we can simply ignore them.
         */
        for (i = pjsua_vid_dev_count()-1; i >= 0; i--) {
           pj_status_t status =  pjsua_vid_dev_set_setting(i, PJMEDIA_VID_DEV_CAP_ORIENTATION,
                                      &pj_ori[dev_ori-1], PJ_TRUE);
            NSLog(@"orientation set status = %d",status);
        }
    }
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 3 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        [self localPreviewWithRect:self.view.bounds];
    });
    
#endif
}
- (UIView *)localPreviewWithRect:(CGRect)rect{
    
    
    pjsua_vid_win_id wids[PJSUA_MAX_VID_WINS];
    unsigned count = PJSUA_MAX_VID_WINS;
    pj_status_t status = pjsua_vid_enum_wins(wids,&count);
    if (status != PJ_SUCCESS ) {
        return nil;
    }
    pjsua_vid_win_id validWid = PJSUA_INVALID_ID;
    pjsua_vid_win_info winInfo;
    validWid = pjsua_vid_preview_get_win(PJMEDIA_VID_DEFAULT_CAPTURE_DEV);
    if (validWid != PJSUA_INVALID_ID) {
        pjsua_vid_win_get_info(validWid,&winInfo);
    }
    else{
        for (int i =0; i<count; i++) {
            pjsua_vid_win_info info;
            pj_status_t status = pjsua_vid_win_get_info(wids[i],&info);
            if (status == PJ_SUCCESS && info.is_native) {
                validWid = wids[i];
                winInfo = info;
                break;
            }
        }
    }
    
    if (validWid == PJSUA_INVALID_ID) {
        return nil;
    }
    UIView *preview = [self previewWithWid:validWid winInfo:winInfo  rect:rect];
    if (nil == preview) {
        return nil;
    }
    return preview;
    
}

- (UIView *)previewWithWid:(pjsua_vid_win_id)wid winInfo:(pjsua_vid_win_info)winInfo rect:(CGRect)rect{
    
    pjmedia_coord pos;
    pos.x = rect.origin.x;
    pos.y = rect.origin.y;
    pjmedia_rect_size rect_size;
    rect_size.h = rect.size.height;
    rect_size.w = rect.size.width;
    
    pj_status_t status = pjsua_vid_win_set_size(wid,&rect_size);
    if (status != PJ_SUCCESS) {
        return nil;
    }
    status = pjsua_vid_win_set_pos(wid,&pos);
    if (status != PJ_SUCCESS) {
        return nil;
    }
    
    UIView *view = (__bridge UIView *)winInfo.hwnd.info.ios.window;
    return view;
    
  
}

**Comment by sauwming** [comment]
Not sure what you mean by invalid video orientation. Please reopen and elaborate if the issue still persists.
