### ISSUE TITLE
Feature Request: ability for pjsua apps to efficiently detect source RTP address/port change

### ISSUE THREAD

**Issue by mscdex** [pjsip/pjproject#2714]
**Is your feature request related to a problem? Please describe.**
Currently pjsua users have to poll the list of media streams for a call to detect changes in the source RTP address/port. This is not very efficient.

**Describe the solution you'd like**
My suggestion is to either call the `on_call_media_state()` callback when such a change occurs or introduce a new callback for it.

**Describe alternatives you've considered**
Inefficient methods like polling

**Comment by sauwming** [comment]
This is not ideal, but you can try capturing the log `Remote RTP address switched to ...`
