### ISSUE TITLE
Header parsing can't account for new lines

### ISSUE THREAD

**Issue by InterLinked1** [pjsip/pjproject#2724]
**Describe the bug**

[2021-06-03 16:08:19] ERROR[24581]: pjproject: <?>:            sip_transport.c Error processing 559 bytes packet from UDP 75.162.77.127:5060 : PJSIP syntax error exception when parsing 'From' header on line 4 col 1: PJSIP syntax error exception when parsing 'To' header on line 5 col 1:

**To Reproduce**
A header with new lines before the end of the line will cause this error, e.g."

```REGISTER sip:something
 SIP/2.0
Via: SIP/2.0/UDP 1.1.1.1:5060;branch=z9hG4bK-851386C5;rport
From: <sip:something@example.com:5555
>;tag=1107561491
To: <sip:something@example.com:5555
>
```

Recognizing that this header is clearly malformed a little bit, and it's not pjproject's fault, it's rather problematic to reject these headers entirely as anything sending these requests is just rejected outright.

**Additional context**

Using with PJSIP with Asterisk 18.4.

**Comment by sauwming** [comment]
Unfortunately there's no way to differentiate which newline is a valid separator and which one should be ignored.
