### ISSUE TITLE
Change port RTP AUDIO / VIDEO PJSIP

### ISSUE THREAD

**Issue by ignacioinda** [pjsip/pjproject#2728]
I am currently on a VOIP project on Android, I am using PJSIP for my project. Due to a network requirement, I need to be able to define the fixed rtp ports for audio and video. I looked at all the documentation and came to the conclusion that this was impossible without editing the source code.
Therefore I was editing and compiling the shared library without progress.

in the file : 
` file -> pjsip/src/pjsua-lib/pjsua_core.c`
I found this
`#define DEFAULT_RTP_PORT	4000`
which allows me to change the lower limit of the random ports, but I can't define ports for each of the sockets

Any ideas how to get this?

**Comment by mingyuejingque** [comment]
pjsua_transport_config.port_range
