### ISSUE TITLE
pjlib-test failed at compliance_test_1()

### ISSUE THREAD

**Issue by gavinwu1028** [pjsip/pjproject#2733]
Hi, I am running pjlib-test and it stops at compliance_test_1(), the log is here
```
08:09:34.947 pjlib 2.11-dev for POSIX initialized
08:09:34.947 Running tcp_ioqueue_test()...
08:09:34.947 ..testing with concurency=1
08:09:34.947 ..select compliance test 0 (success scenario)
21:06:06.949 select() I/O Queue created (0x10464db4)
10:02:39.951 ..select compliance test 1 (failed scenario)
22:59:11.953 select() I/O Queue created (0x10464d74)
05:27:27.954 ...error: pj_ioqueue_poll() returned 2 (only expecting 1)
05:27:27.954 ....FAILED (status=-552)
```

The check failed at **if (status > pending_op)**
[Line 566](https://github.com/pjsip/pjproject/blob/master/pjlib/src/pjlib-test/ioq_tcp.c#L566)
```
    // Initialize remote address.
    pj_sockaddr_in_init(&addr, pj_cstr(&s, "127.0.0.1"), NON_EXISTANT_PORT);

    // Client socket connect()
    status = pj_ioqueue_connect(ckey1, &addr, sizeof(addr));
    if (status==PJ_SUCCESS) {
	// unexpectedly success!
	status = -30;
	goto on_error;
    }
    if (status != PJ_EPENDING) {
	// success
    } else {
	++pending_op;
    }

    callback_connect_status = -2;
    callback_connect_key = NULL;

    // Poll until we've got result
    while (pending_op) {
	pj_time_val timeout = {1, 0};

#ifdef PJ_SYMBIAN
	callback_call_count = 0;
	pj_symbianos_poll(-1, PJ_TIME_VAL_MSEC(timeout));
	status = callback_call_count;
#else
	status = pj_ioqueue_poll(ioque, &timeout);
#endif
	if (status > 0) {
            if (callback_connect_key==ckey1) {
		if (callback_connect_status == 0) {
		    // unexpectedly connected!
		    status = -50;
		    goto on_error;
		}
	    }

	    if (status > pending_op) {
		PJ_LOG(3,(THIS_FILE,
			  "...error: pj_ioqueue_poll() returned %d "
			  "(only expecting %d)",
			  status, pending_op));
		return -552;
	    }
```

And I found the [pj_ioqueue_connect()](https://github.com/pjsip/pjproject/blob/master/pjlib/src/pjlib-test/ioq_tcp.c#L531) in [ioqueue_common_abs.c ](https://github.com/pjsip/pjproject/blob/master/pjlib/src/pj/ioqueue_common_abs.c#L1196) will add two events(WRITEABLE_EVENT and EXCEPTION_EVENT) to the key if it using NON_EXISTANT_PORT.
So [pj_ioqueue_poll](https://github.com/pjsip/pjproject/blob/master/pjlib/src/pjlib-test/ioq_tcp.c#L555) will return 2 in this situation, 
but the pending_op is 1, so it will return an error and stop the pjlib-test.

should the pending_op be 2 or not?

**Comment by sauwming** [comment]
PJSIP has passed the CI test on multiple platforms. So let us know if this still happens with the latest version and the OS/platform the failure occurs.
