### ISSUE TITLE
Unable to disable outgoing audio device

### ISSUE THREAD

**Issue by ade** [pjsip/pjproject#2736]
**Describe the bug**
I am trying to make an application that accepts incoming video calls and plays back both video and audio, but:
I don't want to send any video or audio back to the caller at all. I also do not want and cannot request microphone permission from the user to enable the microphone device.

I've tried using these approaches:

1. endPoint.audDevManager().captureDev = pjsua_snd_dev_id.PJSUA_SND_NULL_DEV
2. endPoint.audDevManager().captureDev = pjsua_snd_dev_id.PJSUA_SND_NULL_DEV and endPoint.audDevManager().playbackDev = pjsua_snd_dev_id.PJSUA_SND_DEFAULT_PLAYBACK_DEV
3. endPoint.audDevManager().setSndDevMode(pjsua_snd_dev_mode.PJSUA_SND_DEV_SPEAKER_ONLY.toLong())

Using approach 1, video works but no sound is played back from remote.
Using approach 2, the app crashes with error:
Abort message: 'terminating with uncaught exception of type Swig::DirectorException: Title:       pjsua_conf_connect(id, sink.id)
Code:        420003
    Description: Audio subsystem not initialized (PJMEDIA_EAUD_INIT)
    Location:    ../src/pjsua2/media.cpp:220

Using approach 3, it depends, depending on when you call this. If you call it once after _endPoint.libStart()_, it works for **one** call but not for the second one (crashes with exact same error as approach 2 when accepting second call)

Workaround: I call **endPoint.audDevManager().setSndDevMode(pjsua_snd_dev_mode.PJSUA_SND_DEV_SPEAKER_ONLY)** just before accepting _every call_ - this seems to fix the issue for me, but feels like I am using it wrongly?

**Expected behavior**
When I set capture device to null I except to still be able to use the playback device as usual.
I also expect that PJSUA_SND_DEV_SPEAKER_ONLY setting is remembered since I set it on the endpoint's audio manager, it's not call or account-specific.

PJSUA2 2.11 on Android
Running on a OnePlus 7T

**Comment by sauwming** [comment]
Should be fixed by #2822
