### ISSUE TITLE
PJSUA2 media.cpp, not initialized value enc_ptime on CodecParam toPj()

### ISSUE THREAD

**Issue by DaniilKharin** [pjsip/pjproject#2738]
In /pjsip/src/pjsua2/media.cpp in method toPj() for CodecParam value enc_ptime not initialized and on some of Android devices be not zero

1. call pjsua2 method Endpoint.codecSetParam with any params
2. try to audio call
3. no audio, codec error

reproduse on Android 10 Go BQ 5047L Like,

**Comment by sauwming** [comment]
Thanks for the report. Fixed in #3037.
