### ISSUE TITLE
pjproject 2.11 epoll(): TCP/TLS transports not completing connect() operation when compiling against OpenSSL (>=1.1.0) and without EPOLLEXCLUSIVE

### ISSUE THREAD

**Issue by andreas-wehrmann** [pjsip/pjproject#2740]
**What's the problem?**
I recently upgraded my software package to use pjproject 2.11 (up from pjproject 2.10)
and noticed that TLS connections stopped working (OpenSSL 1.1.1k).
My app tries to register via a SIP TLS transport and this stopped working.

The last log statement related to the TLS connection is:

_tlsc0x7f3b300053b8  TLS transport 10.137.8.11:41599 is connecting to sip-provider.local:5061..._

When I do a network trace, I can see that the TCP connection is established,
but no data exchange happens whatsoever; it's just stuck there.
I found that pj doesn't seem to notice that the connection has been established
but found no explanation for this.

**What's special about my setup?**
I do not use the OpenSSL library provided by my Linux distribution,
but build my own version (stock version from openssl.org).

I ran a couple of tests and was able to reproduce this issue with the PJSUA app.
I noticed, that the problem does not seem to occur when building against the system provided libraries.

**Is there an OpenSSL version dependency?**
I made several builds against different OpenSSL versions: 1.0.2g, 1.1.0l and 1.1.1k
and found that 1.0.2g was working, but starting with 1.1.0 PJSUA app wasn't able to register via TLS,
because it wouldn't notice connection establishment.

**Steps to reproduce**
(My build environment is Ubuntu 16.04)

- Create source dir: _mkdir /home/user/pj_tls_problem_
- go there: _cd /home/user/pj_tls_problem_
- Download [OpenSSL 1.1.1k](https://www.openssl.org/source/openssl-1.1.1k.tar.gz) and put it in _/home/user/pj_tls_problem_
- Download [pjproject 2.11](https://github.com/pjsip/pjproject/archive/refs/tags/2.11.tar.gz) and put it in _/home/user/pj_tls_problem_
- build OpenSSL with the following commands:

```tar xvzf openssl-1.1.1k.tar.gz
cd openssl-1.1.1k
./config --prefix=/home/user/pj_tls_problem/build/openssl --openssldir=/etc/ssl no-shared no-comp no-dso no-dynamic-engine
make -j 5
make install_sw
cd ..
```

- build pjproject 2.11 against user provided OpenSSL version:

```cd pjproject-2.11
./configure --prefix=/home/user/pj_tls_problem/build/pjproject \
            --disable-shared \
            --enable-epoll \
            --disable-video \
            --disable-libsamplerate \
            --disable-libwebrtc \
            --with-ssl=/home/user/pj_tls_problem/build/openssl
make dep
make -j 5
```

- run PJSUA app and setup TLS account (in my case I'm registering against an Asterisk PBX and using a custom DNS server):

```
./pjsua-x86_64-unknown-linux-gnu --use-tls --nameserver=10.137.15.202 --registrar=sip:sip-provider.local\;transport=TLS --id=sip:sbc-test@sip-provider.local\;transport=TLS --username=sometosser --password=totallysecretstuff --realm=provider --log-level=6
```

- PJSUA app starts but will not register to the server (see log [log_pjsua_app_openssl111k_not_working.txt](https://github.com/pjsip/pjproject/files/6668630/log_pjsua_app_openssl111k_not_working.txt))

Here is the output when I build pjproject against OpenSSL 1.0.2g: 
[log_pjsua_app_openssl102g_working.txt](https://github.com/pjsip/pjproject/files/6668639/log_pjsua_app_openssl102g_working.txt)

**Comment by nappsoft** [comment]
I had a similar issue with newer SSL versions but only on some linux distributions what had to do with some new default settings in openssl.conf.

The following did the trick for me (alternatively you could change /etc/ssl/openssl.cnf, but I only wanted to change the behavior for PJSIP). But in the end you could have a completely different issue, however I use openssl 1.1.1k with Pjproject 2.11 on several Android, iOS, Windows, Mac OS and Linux without any issue

diff -ru pjproject-2.11/pjlib/src/pj/ssl_sock_ossl.c ../pjproject-2.11_64/pjlib/src/pj/ssl_sock_ossl.c
--- pjproject-2.11/pjlib/src/pj/ssl_sock_ossl.c	2021-03-17 08:34:46.000000000 +0100
+++ ../pjproject-2.11_64/pjlib/src/pj/ssl_sock_ossl.c	2021-03-24 16:00:13.985838673 +0100
@@ -1083,6 +1083,7 @@
 	    SSL_CTX_set_default_passwd_cb_userdata(ctx, cert);
 	}
 
+	SSL_CTX_set_security_level(ctx, 1);
 
 	/* Load certificate if one is specified */
 	if (cert->cert_file.slen) {

**Comment by andreas-wehrmann** [comment]
Thanks for the hint; it doesn't look like a config problem though.
The patch you suggested didn't help either.

My custom built openssl binary (the tool that is build from the OpenSSL sources) is able to connect just fine and I can see the handshake taking place; so there must be something wrong with PJ, specifically with the epoll backend
because when I switch to the classic "select()" backend, everything is working fine.

**Comment by andreas-wehrmann** [comment]
When I re-renable the epoll backend and #define _DONT_USE_EXCL_ONESHOT_ it starts working again.
The problem seems to be related to the oneshot logic introduced with https://github.com/pjsip/pjproject/commit/d3542d9143af597e8b7f9e6278b473ab2388adb1#diff-8eb1fa2287a2a26fdcad9412fbea3f85d7dc1bf1a76f6ee43bda7a63c80ab2d9

**Comment by andreas-wehrmann** [comment]
Ok, so I think I figured out what the problem is.
The problem doesn't affect TLS connections only but TCP connections in general.
If the epoll backend detects an OpenSSL version >= 1.1.0 and EPOLLEXCLUSIVE is not available,
it switches to EPOLLONESHOT, which seems to cause the problem.

The problem seems to be in this function: https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_epoll.c#L581

When calling pj_ioqueue_connect(), it calls ioqueue_add_to_set() twice, first for event WRITEABLE_EVENT and afterwards for EXCEPTION_EVENT; see here:
https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_common_abs.c#L1229
https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_common_abs.c#L1230

However, when EPOLLONESHOT is used, the second call to ioqueue_add_to_set() changes the event mask and EPOLLOUT is removed.
This is the reason, why the connection never completes, because epoll no longer checks for EPOLLOUT.

I a quick and dirty test, I removed the second call ioqueue_add_to_set(key->ioqueue, key, EXCEPTION_EVENT)
and lo and behold: the pjsua app connected and registered to the server.

What I don't understand is:
Why should the implementation specifics of an ioqueue backend depend on the OpenSSL version used?

Also: I haven't tested this with EPOLLEXCLUSIVE.

**Comment by sauwming** [comment]
Thanks for the detailed report and investigation, @andreas-wehrmann.

I don't think removing ` ioqueue_add_to_set(key->ioqueue, key, EXCEPTION_EVENT)` is the right fix since it's also used by other ioqueue backends. The problem seems to be in `ioqueue_add_to_set()` in `ioqueue_epoll.c`.

I'm not sure what the proper fix is, but maybe we should remove `#if USE_EPOLLONESHOT==0` below instead to avoid the redundancy (which eventually causes the removal of EPOLLOUT)?
```
#if USE_EPOLLONESHOT==0
    /* When not using EPOLLONESHOT, only rearm write event,
     * otherwise, rearm all events.
     */
    if (event_type == WRITEABLE_EVENT)
#endif
```

Perhaps @nanangizz has a better solution for this.

**Comment by andreas-wehrmann** [comment]
You're right, removing the call to `ioqueue_add_to_set(key->ioqueue, key, EXCEPTION_EVENT)` would be wrong.
When EPOLLONESHOT is enabled, any call to `ioqueue_add_to_set()` always sets the flags EPOLLIN and EPOLLERR but EPOLLOUT is only set when calling the function with WRITEABLE_EVENT.
So maybe EPOLLOUT should always be set also when the socket is still _connecting_?

https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_epoll.c#L596

Maybe like so?
`if (event_type == WRITEABLE_EVENT || key->connecting)`

**Comment by andreas-wehrmann** [comment]
You're right, removing the call to `ioqueue_add_to_set(key->ioqueue, key, EXCEPTION_EVENT)` would be wrong.
When EPOLLONESHOT is enabled, any call to `ioqueue_add_to_set()` always sets the flags EPOLLIN and EPOLLERR but EPOLLOUT is only set when calling the function with WRITEABLE_EVENT.
So maybe EPOLLOUT should always be set also when the socket is still _connecting_?

https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_epoll.c#L596

Maybe like so?
`if (event_type == WRITEABLE_EVENT || key->connecting)`

**Comment by nanangizz** [comment]
Yes, adding check for `key->connecting` looks good to me.

Btw, there is perhaps another issue: invoking `pj_ioqueue_recv*()` while sending operation is on progress may also causing removed `EPOLLOUT`. So perhaps we need to introduce a new flag for _sending_ operation (similar to _connecting_). So the patch is perhaps like this:

https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_epoll.c#L70
```
struct pj_ioqueue_key_t
{
    DECLARE_COMMON_KEY
    pj_bool_t		    sending; /* Flag for sending/connecting */
};
```

https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_epoll.c#L596

```
if (event_type == WRITEABLE_EVENT || key->sending) {
    ev.events |= EPOLLOUT;
    key->sending = PJ_TRUE;
}
```
https://github.com/pjsip/pjproject/blob/b88ba9be64a8334c2641488d19f2c17c75628875/pjlib/src/pj/ioqueue_epoll.c#L557

```
   key->sending = PJ_FALSE;
```

**Comment by andreas-wehrmann** [comment]
Whether EPOLLOUT is set, depends on whether the WRITEABLE_EVENT has been set or not, be it for connecting a socket or sending data. So maybe instead of calling the member _sending_ I would suggest something general like:

```
struct pj_ioqueue_key_t
{
    DECLARE_COMMON_KEY
    pj_bool_t	set_write_event; /* Flag to remember whether WRITEABLE_EVENT has been set for this ioqueue */
};
```

**Comment by nanangizz** [comment]
Btw, perhaps we can just use `key_has_pending_write/connect()` instead of introducing a new flag. Also, on concurrent send ops, `EPOLLOUT` should not be removed after the first event. Will try to create a patch and update you.

**Comment by andreas-wehrmann** [comment]
Thanks; avoiding the introduction of new flags is welcome.

**Comment by nanangizz** [comment]
Please check above PR, done few tests here, looks okay.

**Comment by andreas-wehrmann** [comment]
Seems okay, I tested EPOLLONESHOT and the "classic" variant, both work here.
I haven't tested EPOLLEXCLUSIVE though.

**Comment by randsoy** [comment]
If you  add --tls-verify-server, there is a problem (openssl 1.0.2)

**Comment by randsoy** [comment]
You ignored "The certificate is untrusted".
