### ISSUE TITLE
build webrtc-aec3-2  branch on win10 using vs2017

### ISSUE THREAD

**Issue by mingyuejingque** [pjsip/pjproject#2743]
try  to build  webrtc-aec3-2 branch in Win10 with vs2017, but there are no project configuration files (. Vcproj, *. Vcxproj).

copy other project configuration files from "libwebrtc", and remove all file in "Header Files", "Source Files", 
Then add webrtc manually_ Files in aec3 directory. 

Predefined several macros：
NOMINMAX
WEBRTC_WIN
WEBRTC_APM_DEBUG_DUMP=0

You can compile and generate libwebrtc_ aec3-x86_ 64-x64-vc14-debug.lib file，
But when using this Lib in pjmedia, an error will be reported, and the function cannot be found：

error LNK2019: 无法解析的外部符号 "public: __cdecl webrtc::SplittingFilter::SplittingFilter(unsigned __int64,unsigned __int64,unsigned __int64)" (??0SplittingFilter@webrtc@@QEAA@_K00@Z)，该符号在函数 "public: __cdecl webrtc::AudioBuffer::AudioBuffer(unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64,unsigned __int64)" (??0AudioBuffer@webrtc@@QEAA@_K0000@Z) 中被引用

无法解析的外部符号 "void __cdecl webrtc::cft1st_128_SSE2(float *)" (?cft1st_128_SSE2@webrtc@@YAXPEAM@Z)，该符号在函数 "private: void __cdecl webrtc::OouraFft::cft1st_128(float *)const " (?cft1st_128@OouraFft@webrtc@@AEBAXPEAM@Z) 中被引用

Do you have any configuration files for the project that can be successfully compiled?

Thanks！

**Comment by sauwming** [comment]
yes, it's still a work in progress.
I just pushed my local commit containing those project files, but I can't test it yet because my Visual Studio somehow refused to update despite numerous tries.

**Comment by mingyuejingque** [comment]
https://github.com/ewan-xu/AEC3

please see this repository,  It can successfully compile aec3
