### ISSUE TITLE
Access to TURN channel number in application

### ISSUE THREAD

**Issue by jubelpirat** [pjsip/pjproject#2744]
I am implementing an FPGA/ARM based media streaming system. I am trying to use pjnath to find connection routes, and if necessary establish a TURN-connection with channel bind. But instead of using the sockets / methods that pjnath provides for data transmission, I want to use the FPGA (between ETH PHY and ARM) for actual udp data transfer. I got all that running, pjnath is negotiating a connection between two devices. My problem is now: how can I access necessary information (especially TURN Channel Number) from pjnath to craft UDP packets in the FPGA? Is this even possible withou modifying the libs source?

**Comment by nanangizz** [comment]
Unfortunately yes, currently it is not possible to access STUN/TURN socket or session from ICE socket (ice_strans). A rather cleaner way is perhaps to have your own TURN socket implementation (turn_sock.c).
