### ISSUE TITLE
Unable to open sound dev

### ISSUE THREAD

**Issue by JWXIAN** [pjsip/pjproject#2749]
- OS, Distribution & Version:iOS14
- PJSIP
- version: 2.10
- applied patch(es): [e.g: patches from issue/PR xyz]
- `configure` script params: ...
- `config_site.h` contents: 
#define PJ_CONFIG_IPHONE 1
#define PJMEDIA_HAS_VID_TOOLBOX_CODEC 1
#define PJMEDIA_HAS_VIDEO 1
#include <pj/config_site_sample.h>

- related third party libraries & versions: [e.g: OpenSSL 1.1.1b]

**Smartphone (please also complete the following information):**

- Device:iPhone Xr

**Additional context**
11:16:41.119         sip_endpoint.c  .Module "mod-pjsua-log" registered
11:16:41.119         sip_endpoint.c  .Module "mod-tsx-layer" registered
11:16:41.119         sip_endpoint.c  .Module "mod-stateful-util" registered
11:16:41.119         sip_endpoint.c  .Module "mod-ua" registered
11:16:41.119         sip_endpoint.c  .Module "mod-100rel" registered
11:16:41.121         sip_endpoint.c  .Module "mod-pjsua" registered
11:16:41.122         sip_endpoint.c  .Module "mod-invite" registered
11:16:41.213        coreaudio_dev.c  .. dev_id 0: iPhone IO device  (in=1, out=1) 8000Hz
11:16:41.213        coreaudio_dev.c  ..core audio initialized
11:16:41.214                  pjlib  ..select() I/O Queue created (0x1061a0028)
11:16:41.222            pjsua_vid.c  ..Initializing video subsystem..
11:16:41.223          vid_toolbox.m  ...Video Toolbox codec initialized
11:16:41.223                  vpx.c  ...VPX codec initialized
11:16:41.223           opengl_dev.c  ...OpenGL device initialized
11:16:41.285           darwin_dev.m  ...Darwin video initialized with 3 devices:
11:16:41.285           darwin_dev.m  ... 0: [Renderer] iOS - UIView
11:16:41.285           darwin_dev.m  ... 1: [Capturer] AVF - 前置相机
11:16:41.285           darwin_dev.m  ... 2: [Capturer] AVF - 后置镜头
11:16:41.285         colorbar_dev.c  ...Colorbar video src initialized with 2 device(s):
11:16:41.285         colorbar_dev.c  ... 0: Colorbar generator
11:16:41.285         colorbar_dev.c  ... 1: Colorbar-active
11:16:41.286         sip_endpoint.c  .Module "mod-evsub" registered
11:16:41.286         sip_endpoint.c  .Module "mod-presence" registered
11:16:41.286         sip_endpoint.c  .Module "mod-mwi" registered
11:16:41.286         sip_endpoint.c  .Module "mod-refer" registered
11:16:41.287         sip_endpoint.c  .Module "mod-pjsua-pres" registered
11:16:41.287         sip_endpoint.c  .Module "mod-pjsua-im" registered
11:16:41.287         sip_endpoint.c  .Module "mod-pjsua-options" registered
11:16:41.287           pjsua_core.c  .1 SIP worker threads created
11:16:41.287           pjsua_core.c  .pjsua version 2.10 for iOS-12.4.4/arm-iPhone7,1/iOS-SDK initialized
11:16:41.287           pjsua_core.c  .PJSUA state changed: CREATED --> INIT
11:16:41.288             tcptp:5080  SIP TCP listener ready for incoming connections at 192.168.1.106:5080
11:16:41.288           pjsua_core.c  PJSUA state changed: INIT --> STARTING
11:16:41.288         sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
11:16:41.288           pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
11:16:41.288            pjsua_acc.c  Adding account: id=sip:iOS@192.168.1.106
11:16:41.289            pjsua_acc.c  .Account sip:iOS@192.168.1.106 added with id 0

11:16:41.439            pjsua_aud.c  .Set sound device: capture=-1, playback=-2
11:16:41.439            pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@16000/1/20ms
11:16:41.442        coreaudio_dev.c  ...Using VoiceProcessingIO audio unit
11:16:42.135            pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@44100/1/20ms
11:16:42.136        coreaudio_dev.c  ...Using VoiceProcessingIO audio unit
11:16:42.231            pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@48000/1/20ms
11:16:42.231        coreaudio_dev.c  ...Using VoiceProcessingIO audio unit
11:16:42.314            pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@32000/1/20ms
11:16:42.315        coreaudio_dev.c  ...Using VoiceProcessingIO audio unit
11:16:42.421            pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@16000/1/20ms
11:16:42.421        coreaudio_dev.c  ...Using VoiceProcessingIO audio unit
11:16:42.569            pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@8000/1/20ms
11:16:42.569        coreaudio_dev.c  ...Using VoiceProcessingIO audio unit
11:16:42.731            pjsua_aud.c  ..Unable to open sound dev

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.

**Comment by ShajeedSk** [comment]
14:55:03.928            pjsua_aud.c  ..Error retrieving default audio device parameters: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) [status=420006]
14:55:03.928          pjsua_media.c  .Call 0: deinitializing media..
14:55:03.928               call.cpp  pjsua_call_make_call(acc.getId(), &pj_dst_uri, param.p_opt, this, param.p_msg_data, &id) error: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) (status=420006) [../src/pjsua2/call.cpp:706]

**Comment by ShajeedSk** [comment]
I am facing same issue, with 2.14 version

**Comment by homepy** [comment]
We found that the user hide the APP to background, so "Unable to open sound dev".
Keep the APP running in the foreground.
