### ISSUE TITLE
stop native video preview on android devices

### ISSUE THREAD

**Issue by wangqingwen** [pjsip/pjproject#2751]
I am use pjproject2.1.0 on android devices,during hangup the video call ,the android_dev.c release function is not callback

**Describe the solution you'd like**
my project using the USB camera, I hope that during the video call,pull the USB camera out,then insert it,native video can be working

**Describe alternatives you've considered**

**Additional context**

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
