### ISSUE TITLE
Error "emmintrin.h: No such file or directory" when bulding on Yocto Linux (Debian GNU/Linux 10)

### ISSUE THREAD

**Issue by aleh4d** [pjsip/pjproject#2752]
Error 
"../../webrtc/src/webrtc//modules/audio_processing/aec/aec_core_sse2.c:15:10: fatal error: emmintrin.h: No such file or directory"

when bulding on Yocto Linux (Debian GNU/Linux 10) 

Please, provide build instructions for Yocto Linux

**Comment by sauwming** [comment]
Just disable it: ./configure --disable-libwebrtc
It's an optional component, for echo cancellation. You can use another EC backend such as Speex, if needed.

**Comment by aleh4d** [comment]
We need echo cancellation of very good quality,
1) can you tell if Speex has the same echo cancellation quality as WebRTC?
2) How to use Speex for EC? Doses in need additional options in compilation? 
3) Is it possible to compile PJSip with WebRTC for Yocto Linux?
