### ISSUE TITLE
pj_grp_lock_create does not follow documented ref_cnt behaviour

### ISSUE THREAD

**Issue by capickett** [pjsip/pjproject#2760]
### Describe the bug

In the documentation for [pj_grp_lock_create ](https://www.pjsip.org/docs/latest/pjlib/docs/html/group__PJ__GRP__LOCK.htm#gacfecdfab9f40cf249b32542fbe6e1d05), it notes...

> Initially the group lock will have reference counter of one.

However, when inspecting the code (https://github.com/pjsip/pjproject/blob/master/pjlib/src/pj/lock.c#L434), you'll find

```
status = pj_atomic_create(pool, 0, &glock->ref_cnt);
```

Which appears to set the reference count to 0 initially. This discrepancy can be found via local reproduction.

### Steps to reproduce

```
pj_grp_lock_t* lock;
pj_grp_lock_create(pool, nullptr, &lock);
pj_assert(pj_grp_lock_get_ref(lock) == 1); // Will fail
```

### PJSIP version

2.11

### Context

- Running on linux, though I suspect this might be platform agnostic

### Log, call stack, etc

```shell
Assertion `pj_grp_lock_get_ref(result->lock_) == 1' failed.
```
```

**Comment by nanangizz** [comment]
Ah you're right, the problem should be the documentation as all the application seem to already treat it as zero-initalized.

Thank you for the report.
