### ISSUE TITLE
call_disconnect() in pjsua_call.c not checking if tdata is NULL after calling pjsip_inv_end_session()

### ISSUE THREAD

**Issue by dbrichards** [pjsip/pjproject#2761]
### Describe the bug

The function _call_disconnect_() in _pjsua_call.c_ is not checking if _tdata_ is _NULL_ after calling _pjsip_inv_end_session_(). This causes the function _pjsip_inv_send_msg_() to assert when it is called at the bottom of _call_disconnect_().

It appears that _tdata_ is not checked in _on_retransmit_() in _sip_100rel_.c either after calling pjsip_inv_end_session().

And finally, _tdata_ is not checked in _perform_test_() in _inv_offer_answer_test_.c either after calling _pjsip_inv_end_session_().

### Steps to reproduce

Code inspection.

### PJSIP version

2.11

### Context

Linux

### Log, call stack, etc

```shell
N/A
```

**Comment by silentindark** [comment]
@trengginas Could you please take a look? I think that it can be related with other issue (https://github.com/pjsip/pjproject/issues/2641) which is present in asterisk. (asterisk bug tracker -> https://issues.asterisk.org/jira/browse/ASTERISK-29286)
