### ISSUE TITLE
iOS cannot use openh264

### ISSUE THREAD

**Issue by bukira** [pjsip/pjproject#2764]
### Describe the bug

I have followed the docs on using openh263 but the docs are too old for the current os, they are 5 or more years old

https://trac.pjsip.org/repos/ticket/1947
https://github.com/cisco/openh264/releases/tag/v1.6.0

Add libopenh264.a and iOS-SDK's libstdc++.dylib to your application project in Xcode.

libstc++.dlib is no longer part of Xcode since Xcode 9

When I try to compile openh264 I get cannot find libstc++.dlib  as its no longer there

I can do this 
 make OS="ios" ARCH=arm64 install -stdlib=libc++

which seems to create the libraries, but when I try to use in pjsip

./configure-iphone --with-openh264=/usr/local/openh264/lib/

I just keep getting 

Using OpenH264 prefix... /usr/local/openh264/lib/
checking OpenH264 usability... no

How do I support openh264 with current OS and Xcode 12

### Steps to reproduce

followed the docs

### PJSIP version

2.11

### Context

when trying to configure with openh264

### Log, call stack, etc

```shell
Using OpenH264 prefix... /usr/local/openh264/lib/
checking OpenH264 usability... no
```

**Comment by johanlantz** [comment]
![Screenshot 2021-07-30 at 21 52 52](https://user-images.githubusercontent.com/7461655/127705056-9d2eb7e8-2a00-454e-890d-c91e72465860.png)

**Comment by YuZebra** [comment]
> 

I have the same problem, can this be explained in detail?

**Comment by Truong-Thanh-Quang** [comment]
Folder structure:
/home/src/pjproject
/home/src/openh264

Build example for arm64:
    _cd /home/src/openh264
    make OS=ios ARCH=arm64 SDK_MIN=7.1 clean
    sudo make OS=ios ARCH=arm64 SDK_MIN=7.1 install

    cd /home/src/pjproject
    ARCH="-arch arm64" ./configure-iphone --with-openh264=/usr/local/
    make dep && make clean && make_

**Comment by YuZebra** [comment]
> Folder structure: /home/src/pjproject /home/src/openh264
> 
> Build example for arm64: _cd /home/src/openh264 make OS=ios ARCH=arm64 SDK_MIN=7.1 clean sudo make OS=ios ARCH=arm64 SDK_MIN=7.1 install cd /home/src/pjproject ARCH="-arch arm64" ./configure-iphone --with-openh264=/usr/local/ make dep && make clean && make_

This is helpful 

Using OpenH264 prefix... /usr/local/
checking OpenH264 usability... yes
