### ISSUE TITLE
iOS set buffer

### ISSUE THREAD

**Issue by bukira** [pjsip/pjproject#2765]
### Describe the bug

Buffer is too small

--end msg--
11:19:46.767        strm0x10a01d828  RTP decode error: Invalid RTP version (PJMEDIA_RTP_EINVER)
11:19:46.895           openh264.cpp !Frame size changed: 656x656 --> 1280x720
11:19:46.903      vstdec0x108037828  Error: not enough buffer for decoded frame (supplied=645504, required=1382400)
11:19:46.906             vid_conf.c  Port 1 (vstdec0x108037828) stop transmitting to port 0 (OpenGL renderer)
11:19:46.906             vid_conf.c  Port 1 (vstdec0x108037828) transmitting to port 0 (OpenGL renderer)
11:19:46.906       ios_opengl_dev.c  Stopping ios opengl stream
11:19:46.907       ios_opengl_dev.c  Starting ios opengl stream
11:19:46.907             vid_conf.c  Port 1 (vstdec0x108037828) transmitting to port 0 (OpenGL renderer)
11:19:46.948      vstdec0x108037828 !Error: not enough buffer for decoded frame (supplied=645504, required=1382400)

### Steps to reproduce

Use the iOS demo app with openh264 codec 2.1.1

### PJSIP version

2.11

### Context

when connecting to video stream

### Log, call stack, etc

```shell
--end msg--
11:19:46.767        strm0x10a01d828  RTP decode error: Invalid RTP version (PJMEDIA_RTP_EINVER)
11:19:46.895           openh264.cpp !Frame size changed: 656x656 --> 1280x720
11:19:46.903      vstdec0x108037828  Error: not enough buffer for decoded frame (supplied=645504, required=1382400)
11:19:46.906             vid_conf.c  Port 1 (vstdec0x108037828) stop transmitting to port 0 (OpenGL renderer)
11:19:46.906             vid_conf.c  Port 1 (vstdec0x108037828) transmitting to port 0 (OpenGL renderer)
11:19:46.906       ios_opengl_dev.c  Stopping ios opengl stream
11:19:46.907       ios_opengl_dev.c  Starting ios opengl stream
11:19:46.907             vid_conf.c  Port 1 (vstdec0x108037828) transmitting to port 0 (OpenGL renderer)
11:19:46.948      vstdec0x108037828 !Error: not enough buffer for decoded frame (supplied=645504, required=1382400)

I have tried setting the buffer as follows but it makes no difference

        /* Start pjsua */
        status = pjsua_start();
        
        let codec = strdup("H264, 4")
        var codec_id:pj_str_t = pj_str(codec);
        var param = pjmedia_vid_codec_param()
        pjsua_vid_codec_get_param(&codec_id, &param)
        
        /* Sending 1280 x 720 */
        param.enc_fmt.det.vid.size.w = 1280; //1280
        param.enc_fmt.det.vid.size.h = 720; //720
        
        param.dec_fmt.det.vid.size.w = 1280; //1280
        param.dec_fmt.det.vid.size.h = 720; //720
        
        /* Sending @30fps */
        param.enc_fmt.det.vid.fps.num   = 30;
        param.enc_fmt.det.vid.fps.denum = 1;
        
        param.dec_fmt.det.vid.fps.num   = 30;
        param.dec_fmt.det.vid.fps.denum = 1;
        
        /* Bitrate range preferred: 512-1024kbps */
        param.enc_fmt.det.vid.avg_bps = 512000;
        param.enc_fmt.det.vid.max_bps = 1024000;
        
        param.dec_fmt.det.vid.avg_bps = 512000;
        param.dec_fmt.det.vid.max_bps = 1024000;
        
        /* 3000/(1.001*2) fps for CIF */
        let cif = strdup("CIF")
        let two = strdup("2")
        param.dec_fmtp.param.1.name = pj_str(cif);
        param.dec_fmtp.param.1.val = pj_str(two);
        
        /* 3000/(1.001*1) fps for QCIF */
        let qcif = strdup("QCIF")
        let one = strdup("1")
        param.dec_fmtp.param.0.name = pj_str(qcif);
        param.dec_fmtp.param.0.val = pj_str(one);
        
        /* Can receive up to 1280×720 @30fps */
        let profile = strdup("profile-level-id")
        let xxxxx = strdup("42e033")
        param.dec_fmtp.param.0.name = pj_str(profile);
        param.dec_fmtp.param.0.val = pj_str(xxxxx);
        
        /* H263 specific maximum bitrate 512kbps */
        let maxBR = strdup("MaxBR")
        let rate = strdup("5120")
        param.dec_fmtp.param.0.name = pj_str(maxBR);
        param.dec_fmtp.param.0.val = pj_str(rate); /* = max_bps / 100 */
        
        param.ignore_fmtp =  pj_bool_t(PJ_TRUE.rawValue);

        pjsua_vid_codec_set_param(&codec_id, &param)
```

**Comment by AdMains** [comment]
I also encountered this problem  

**Describe the bug**
Steps to reproduce
Use the iOS demo app with openh264 codec 2.10
**PJSIP version**
2.10
**Context**
when connecting to video stream
**iOS version**
13.7

16:50:01.609      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:01.705      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:01.789      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:01.923      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:02.055      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:02.156      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:02.341      vstdec0x10f848428  Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:02.423      vstdec0x10f848428  Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:02.475      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)
16:50:02.555      vstdec0x10f848428 !Error: not enough buffer for decoded frame (supplied=460800, required=1228800)

**Comment by TechGuyVN** [comment]
can you find solutions, i got same issued here

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/specific-guides/video/users_guide.html#size-or-resolution
