### ISSUE TITLE
Rust binding

### ISSUE THREAD

**Issue by vit1251** [pjsip/pjproject#2766]
**Is your feature request related to a problem? Please describe.**

Use PJPROJECT inside Rust application.

**Describe the solution you'd like**

Start use one external binding like https://github.com/evangilo/pjsip-sys
or start new one inside pjproject.

**Describe alternatives you've considered**

Use some code generation bridge inside pjproject like Swig for Python.

**Additional context**

Search alternative for PJSUA2 for C++ code.

**Comment by sauwming** [comment]
Please check #3275
