### ISSUE TITLE
record mp3

### ISSUE THREAD

**Issue by manfer** [pjsip/pjproject#2773]
Sorry if this is not the correct place. Not sure where to ask.

I'm testing pjsua mp3 recording and I'm always getting PJ_ENOTSUP error from pjsua_aud.c.

In documentation says mp3 recording is only available on Win32. I tried both x64 and Win32 versions. Same result, same error.

In pjsua_aud.c I'm not able to figure out if there is mp3 support. I just see this code that makes me think it is not available,

https://github.com/pjsip/pjproject/blob/7d75682aed4e03b50b840471829f4617356072fb/pjsip/src/pjsua-lib/pjsua_aud.c#L1468-L1479

but I'm not familiarized with pjproject and not sure if I'm looking in correct code.

Is there mp3 recording on current pjsua versions?

By the way. Is there a better place to ask a question like this?

**Comment by manfer** [comment]
I finally found the reason in
https://trac.pjsip.org/repos/wiki/new_changes

> MP3 File Writer
> 
> Support for encoding/writing MP3 file (the MP3 file writer port) has been removed from PJMEDIA. If application wants this, it can get the original files from third_party/mp3 directory.

So, indeed, mp3 recording is not available in current version and has to be readded if needed.

I have tried readding the code on third_party/mp3 to pjmedia and pjmedia builds correctly but when I try to use the mp3 file writer in pjsua_aud.c I'm getting unresolved external symbol pjmedia_mp3_writer_port_create in pjsystest, pjsua and samples projects. So I'm stuck as I don't know how to resolve this link errors.

**Comment by manfer** [comment]
I finally understood how to add this correctly so the linker works properly. Anyway I had to edit third_party/mp3_writer.c changing,

https://github.com/pjsip/pjproject/blob/43d1bc90d7e569c3946ae165f3ab015031036d7d/third_party/mp3/mp3_writer.c#L401-L412

to,

```
static pj_status_t file_on_event(pjmedia_event *event,
                                 void *user_data)
{
    struct mp3_file_port *fport = (struct file_port*)user_data;


    if (event->type == PJMEDIA_EVENT_CALLBACK) {
	if (fport->cb2)
	    (*fport->cb2)(&fport->base, fport->base.port_data.pdata);
    }
    
    return PJ_SUCCESS;
}
```

**Comment by gbfarah** [comment]
I have been using legacy mp3_writer.c... have got everything working with blade encoding... I noticed that the on destroy method has an unusual issue (resulting in MP3 file header not being written properly)

MP3Err is actually returning 2 (invalid handle errror)...I know for a fact the file is correct... I also altered to do a copy to standard null terminated C string with no effect.....

Was this code ever verified for header write correctness. Would be great if we can get this working

```
/*
 * Close the port, modify file header with updated file length.
 */
static pj_status_t file_on_destroy(pjmedia_port *this_port)
{
    struct mp3_file_port *fport = (struct mp3_file_port*)this_port;
    pj_status_t status;
    unsigned long WriteSize;
    unsigned long MP3Err;


    /* Close encoder */
    MP3Err = BladeDLL.beDeinitStream(fport->mp3_stream, fport->mp3_buf, 
				     &WriteSize);
    if (MP3Err == BE_ERR_SUCCESSFUL) {
	pj_ssize_t bytes = WriteSize;
	status = pj_file_write(fport->fd, fport->mp3_buf, &bytes);
    }

    /* Close file */
    status = pj_file_close(fport->fd);

    /* Write additional VBR header */
    if (fport->mp3_option.vbr) {
	MP3Err = BladeDLL.beWriteVBRHeader(fport->mp3_filename.ptr);
    }


    /* Decrement DLL reference counter */
    deinit_blade_dll();

    /* Done. */
    return PJ_SUCCESS;
}
```
