### ISSUE TITLE
Windows ai_socktype check in pj_getaddrinfo

### ISSUE THREAD

**Issue by MingruiZhangW** [pjsip/pjproject#2787]
### Describe the bug

For release-2.11.

Currently on Windows 10 platform,

If we try to resolve hostname with ```pjsip_transport_type_e``` to be UDP, 

the ```getaddrinfo``` call in ```pj_getaddrinfo``` does not seem to change the ```ai_socktype``` within ```addrinfo```.

This will cause the check of  ```pj_SOCK_DGRAM``` or ```pj_SOCK_STREAM``` to fail.

https://github.com/pjsip/pjproject/pull/2619

### Steps to reproduce

Resolve a hostname by using  ```pj_getaddrinfo``` with PJSIP_TRANSPORT_UDP.

```PJ_ERESOLVE``` is returned.

### PJSIP version

2.11

### Context

Windows 10, 19042.1110

### Log, call stack, etc

```shell
N/A
```

**Comment by AmarOk1412** [comment]
> the getaddrinfo call in pj_getaddrinfo does not seem to change the ai_socktype within addrinfo

I think this is the case if the endpoint will both accept UDP + TCP. So ai_socktype will be 0.

cf

> A value of zero for ai_socktype indicates the caller will accept any socket type.

Source: https://docs.microsoft.com/en-us/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo

Imho, the check of ai_socktype should be removed, as not necessary and breaking resolution in some cases.

**Comment by MingruiZhangW** [comment]
https://github.com/pjsip/pjproject/pull/2788

Works fine now on my side,

Thanks!
