### ISSUE TITLE
sip session timers do not work when timers=always

### ISSUE THREAD

**Issue by prof-tech** [pjsip/pjproject#2792]
### Describe the bug

timers=originate in asterisk chan_sip are supposed to map to "timers=always" in pjsip. However, when set to **always** neither re-INVITE nor UPDATE is ever sent  by pjsip.

### Steps to reproduce

n/a

### PJSIP version

Asterisk bundled version 2.9

### Context

-the issue happens on Debian 10.4 running Asterisk 16.8 cert 8.
-make an outbound call
-call connects. wait 5 min and neither re-INVITE nor  UPDATE is ever sent by pjsip.
[telnyx]
type = aor
contact = sip:sip.telnyx.com\;transport=tls

[telnyx]
type = auth
username=myname
password=secretpw
realm=sip.telnyx.com

[telnyx]
type = endpoint
aors = telnyx
outbound_auth=telnyx
disallow=all
allow = ulaw
from_domain = callcentric.com
allow_transfer = no
direct_media=no
timers_sess_expires=600
timers=always

### Log, call stack, etc

```shell
n/a
```

**Comment by trengginas** [comment]
I tested here using pjsua app with `use-timer=3` option, and re-INVITE/UPDATE was sent as expected.

**Comment by prof-tech** [comment]
Thanks for checking. I will have to check in Asterisk to see if use-timer is being set. Hope it is that simple.

**Comment by prof-tech** [comment]
Can you tell me if the PJSIP_INV_SUPPORT_TIMER bit should be set when calling the AP function?
`if (!strcasecmp(var->value, "always")) {
		endpoint->extensions.flags |= PJSIP_INV_ALWAYS_USE_TIMER;`

**Comment by prof-tech** [comment]
Question; Would the "required" mode be use-timer=2?

**Comment by sauwming** [comment]
You can check the documentation:
https://www.pjsip.org/docs/latest/pjsip/docs/html/group__PJSUA__LIB__BASE.htm#gaf352829cc383112c4ce4da58a4d0b37e

Or try our sample app:
`pjsua --help`
