### ISSUE TITLE
Pjsip Crashes when app is in kill mode and accepts the incoming call

### ISSUE THREAD

**Issue by chiragchauhan1073** [pjsip/pjproject#2796]
### Describe the bug

App crashes frequently in kill mode while accepting incoming call. this happenes only in android 11. 
here is the crash log

PlayerBase::PlayerBase()
TrackPlayerBase::TrackPlayerBase()
D/AudioTrack: createTrack_l(16): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 716
W/libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
E/IAudioFlinger: createRecord returned error -1
E/AudioRecord: createRecord_l(0): AudioFlinger could not create record track, status: -1
E/libOpenSLES: android_audioRecorder_realize(0xb40000751b4b3020) error creating AudioRecord object; status -1
W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 8506 (Thread-82), pid 8406 (.main.xyz)

### Steps to reproduce

run pjsip
1. make call 
2. auto receive call in kill mode(foreground service)  android 11. 

### PJSIP version

2.11

### Context

Android Version 11.

### Log, call stack, etc

```shell
PlayerBase::PlayerBase()
TrackPlayerBase::TrackPlayerBase()
D/AudioTrack: createTrack_l(16): AUDIO_OUTPUT_FLAG_FAST denied by server; frameCount 0 -> 716
W/libOpenSLES: Conversion from OpenSL ES positional channel mask 0x4 to Android mask 0 loses channels
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x4, using default mask 0x10 based on channel count of 1)
E/IAudioFlinger: createRecord returned error -1
E/AudioRecord: createRecord_l(0): AudioFlinger could not create record track, status: -1
E/libOpenSLES: android_audioRecorder_realize(0xb40000751b4b3020) error creating AudioRecord object; status -1
W/libOpenSLES: Leaving Object::Realize (SL_RESULT_CONTENT_UNSUPPORTED)
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 8506 (Thread-82), pid 8406 (.main.xyz)
```

**Comment by trupizzza** [comment]
@bienpx224 Usually line below
E/AudioRecord: createRecord_l(0): AudioFlinger could not create record track, status: -1
Indicates that no RECORD_AUDIO permission is given to app when initializing incoming call

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
