### ISSUE TITLE
Getting raw audio frames in PJSUA2 Java

### ISSUE THREAD

**Issue by TheKinrar** [pjsip/pjproject#2808]
Hi. I could not find a definitive answer to this question, but I might have missed it, so sorry if it's the case!

I'm using the PJSUA2 Java bindings to make SIP audio calls, and ideally would like to process the audio in my code. From what I understand, I can either redirect the media to a device on my computer, or use an AudioMediaRecorder to save to a file, but what I'm looking for is a way to get the audio frames directly in my code and process it myself. Is that possible?

If not, I guess it must me possible using the lower-level C API, in which case I would be very thankful if I could be pointed in the right direction for that too!

Thanks!

**Comment by BaybaraEvgeny** [comment]
I already solved this problem. I use java bindings too. But it is secret for now, sorry)
