### ISSUE TITLE
Can't register to sip if username has "@" in string

### ISSUE THREAD

**Issue by gkissand** [pjsip/pjproject#2814]
### Describe the bug

My SIP provider uses usernames that include @ 
The full string (in chan_sip) is
register => +XXXXXXXXXX@sip.server.com:PASSWORD:+XXXXXXXXXX@sip.server.com@sip.server.com:5060
register => fromuser:secret:username@host
fromuser and username are +XXXXXXXXXX@sip.server.com
This works fine no problems here
When I try to migrate to res_pjsip it seems that it has a problem dealing with @ in username 
I tried to backslash \@ and tried to replace it with %40 (hex value) but again no luck
Provider told me that I send only the +XXXXXXXXXX part
I did not find any documetation neither a working example on this

### Steps to reproduce

create a sip trunk with @ at username

### PJSIP version

2.5.0

### Context

- Ubuntu 20.04
- Asterisk 16.2.1 (shipped with Ubuntu)
- pjsip version. Whatever is shipped with asterisk. No way to identify it. Should be 2.5.0
[mytrunk]
type=registration
retry_interval = 20
max_retries = 0
expiration = 120
transport = transport-udp
outbound_auth=mytrunk
server_uri=sip:sip.server.com:5060
client_uri=sip:+NNNNNNNN%40sip.server.com@sip.server.com:506

[mytrunk]
type=auth
auth_type=userpass
username=+NNNNNNNN%40sip.server.com
password=PASSWORD

### Log, call stack, etc

```shell
Not available right now
```

**Comment by LuggerMan** [comment]
Provider told me that I send only the +XXXXXXXXXX part
Listen to that pls.

**Comment by seanbright** [comment]
This is not a bug in pjproject. It may be a bug in Asterisk, but you should discuss on https://community.asterisk.org/ to confirm

**Comment by forca83** [comment]
same same here, can not do a call with pjsua_call_make_call(..), if username has a "@" inside:

`pjsua_call_make_call(..)
           - [sip:gordonfreeman@bar.org@10.1.63.6;transport=tcp] inviting. 
           - Making call with acc #0 to sip:gordonfreeman@bar.org@10.1.63.6;transport=tcp 
           - Unable to make call: Invalid Request URI (PJSIP_EINVALIDREQURI) [status=171042] `
       
same same with pjsua-app:
`16:13:28.679 pjsua_app_conf  Invalid SIP URI sip:gordonfreeman@bar.org@10.1.63.6`

please provide, how to use a "@" inside of username properly

tried with PJSIP version: 2.10, 2.11.1

**Comment by sauwming** [comment]
`@` is reserved character, you need to escape it.
Check: https://www.rfc-editor.org/rfc/rfc2396
