### ISSUE TITLE
Not fully correct video AMediaCodec decoder configuration

### ISSUE THREAD

**Issue by ArtsemKurantsou** [pjsip/pjproject#2831]
### Describe the bug

All of the video codec decoders in AMediaCodec implementation have *I420* as a `and_media_codec_data.prm->dec_fmt.id` is set in `add_codec`.
As a result SPS/PPS data won't be set to the AMediaCodec format in the `configure_decoder` function as `and_media_data->prm->dec_fmt.id == PJMEDIA_FORMAT_H264` will be always false

### Steps to reproduce

Build for Android and enable AMediaCodec
Start or accept an H264 video call with SPS/PPS data

### PJSIP version

2.11

### Context

Any Android device
PjSip 2.11+ build with AMediaCodec enabled 

### Log, call stack, etc

```shell
Not required
```

**Comment by trengginas** [comment]
You are correct, it should check enc_fmt instead. Could you please try the patch ?
[patch_vid_mediacodec_h264.txt](https://github.com/pjsip/pjproject/files/7224851/patch_vid_mediacodec_h264.txt)

**Comment by sauwming** [comment]
@riza, please create a PR for this.
