### ISSUE TITLE
Cross Compilation Fails on ubuntu20.04

### ISSUE THREAD

**Issue by zishucom** [pjsip/pjproject#2834]
### Describe the bug

usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: output/pjsua2-test-arm-elf-linux-gnu/main.o: Relocations in generic ELF (EM: 62)

/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: output/pjsua2-test-arm-elf-linux-gnu/main.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [/home/duma/Public/pjproject.doing/build/rules.mak:125: ../bin/pjsua2-test-arm-elf-linux-gnu] Error 1
make[2]: Leaving directory '/home/duma/Public/pjproject.doing/pjsip/build'
make[1]: *** [Makefile:286: pjsua2-test-arm-elf-linux-gnu] Error 2
make[1]: Leaving directory '/home/duma/Public/pjproject.doing/pjsip/build'
make: *** [Makefile:14: all] Error 1

### Steps to reproduce

1. ./configure --host=arm-elf-linux  CC=aarch64-linux-gnu-gcc --disable-libwebrtc --disable-libyuv 
2. make dep && make

### PJSIP version

2.11

### Context

- OS: Ubuntu20.04
-  aarch64-linux-gnu-gcc
- 

### Log, call stack, etc

```shell
no log~ 

it was happend at make
```

**Comment by zishucom** [comment]
i got the  "**file in wrong  format**"   Err:
```
$ file main.o 
main.o: ELF 64-bit LSB relocatable, x86-64,

$file other *.o
sip_uri.o: ELF 64-bit LSB relocatable, ARM aarch64,
```
so main.o is x86-64 format , but other .o files are ARM aarch64

but ....i still dont know how to solve that ( change the main.o file format)

**Comment by colorhacker** [comment]
how to solve

**Comment by sauwming** [comment]
Since the error happens in pjsua2-test, I think you can ignore it. Or just run `make lib` to build the library only.
