### ISSUE TITLE
Some DNS associated functions block main thread when the Internet connection is low

### ISSUE THREAD

**Issue by tiana890** [pjsip/pjproject#2835]
I am creating IOS application based on PJSIP. I initialize and start PJSIP in main thread, but sometimes occur situations when UI freezes because PJSIP blocks main thread. I've studied the docs and they say following:

"If you want to avoid any possibility of blocking operation by PJLIB (or any higher API layer such as PJMEDIA, PJNATH, PJSUA that usually calls PJLIB), instead of dispatching the task using GCD, the safest way is to create and manage your own thread pool and register that thread pool to PJLIB. Or alternatively, simply use PJSUA timer mechanism (with zero delay), see pjsua_schedule_timer()/pjsua_schedule_timer2() docs for more info."

But I can not understand how to use pjsua_schedule_timer()/pjsua_schedule_timer2() in this case. The descriptions of these functions do not contain information about this case. So my question is how to use PJSUA timer mechanism in PJSIP to save responsiveness of main thread? Or please tell me where can I ask this question? Because there is too few information in documentation.

**Comment by sauwming** [comment]
Check iOS pjsua swift sample app for an example.
