### ISSUE TITLE
Many function undefined when  pjsua_create  be calling 

### ISSUE THREAD

**Issue by zishucom** [pjsip/pjproject#2841]
### Describe the bug
Many errors same like following 
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /usr/local/PJSIP/lib/libpjmedia-codec-aarch64-unknown-linux-gnu.a(gsm.o): in function `gsm_codec_decode':
gsm.c:(.text+0xe8): undefined reference to `gsm_decode'

### Steps to reproduce

CFLAGS = -I/usr/local/PJSIP/include -DPJ_AUTOCONF=1  -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1

LIBS = -L/usr/local/PJSIP/lib \
       -lpjsua2-aarch64-unknown-linux-gnu \
       -lstdc++ \
       -lpjsua-aarch64-unknown-linux-gnu \
       -lpjsip-ua-aarch64-unknown-linux-gnu \
       -lpjsip-simple-aarch64-unknown-linux-gnu \
       -lpjsip-aarch64-unknown-linux-gnu \
       -lpjmedia-codec-aarch64-unknown-linux-gnu \
       -lpjmedia-aarch64-unknown-linux-gnu \
       -lpjmedia-videodev-aarch64-unknown-linux-gnu \
       -lpjmedia-audiodev-aarch64-unknown-linux-gnu \
       -lpjmedia-aarch64-unknown-linux-gnu \
       -lpjnath-aarch64-unknown-linux-gnu \
       -lpjlib-util-aarch64-unknown-linux-gnu \
       -lpj-aarch64-unknown-linux-gnu \
       #-lm -lrt -lpthread

### PJSIP version

2.11

### Context

Ubuntu 20.04
Arm
Aarch64-Linux-gnu

### Log, call stack, etc

```shell
No
```

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
