### ISSUE TITLE
Delayed call start with Android JNI driver

### ISSUE THREAD

**Issue by ichernev** [pjsip/pjproject#2849]
### Describe the bug

I'm running your sample android app (lib is build from latest master) on two devices, connecting them via Twilio SIP cloud. The issue is that when the devices are using `Android JNI` driver, the call start is delayed by an unknown/random amount (0-15s but could be more). When using `OpenSL ES Audio` it works flawlessly every single time.

### Steps to reproduce

1. Run sample app on two devices
2. Call the second device from the first device (or call both from a SIP provider, doesn't matter)
3. When using Android JNI the call start is delayed (i.e you don't hear the other party, the other party doesn't hear you), when using Open SL it always works from time 0. 

### PJSIP version

2.10 and latest master were tried

### Context

This issue has been reproduced on a number of different devices (5+), running Android 10 and above.

### Log, call stack, etc

```shell
I've tried to track this down, and the only thing consistent I observed, is that the first UDP (RTP) packet arrives when the call starts. So in some cases the RTP stream is not established until after a considerable time (5-15s), but that is never the case with Open SL.
```

**Comment by sauwming** [comment]
I am unable to reproduce this.

As the issue may no longer be valid now, please try with the latest version, and reopen if the issue persists.
