### ISSUE TITLE
Feature Request: add pjmedia mem_player function that resets its eof flag

### ISSUE THREAD

**Issue by mscdex** [pjsip/pjproject#2858]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, other than missing desired functionality.

**Describe the solution you'd like**
It would be nice to have a public function that resets pjmedia's mem_player `eof` flag back to `PJ_FALSE` if `eof > PJ_FALSE`. This will allow a mem_player that is set not to loop to be able to restart playback at a future time without having to destroy the current mem_player, create a new mem_player, attach it to the conf bridge, connect it to the same listeners, etc. The playback pointer is already rewound to the beginning, so it's just the `eof` that needs to be reset.

**Describe alternatives you've considered**
1. Make a copy of the mem_player struct in my project so I can cast the port to explicitly reset the `eof` flag. This is hacky but should be doable? Would need to maintain the layout of the struct in case it changes in the future.
2. Copy the mem_player implementation and add the feature myself. This is a bit extreme and would have the most maintenance burden considering it does some internal pjsip stuff, especially with the whole event subscription stuff, which could change down the road.

**Comment by sauwming** [comment]
Not planned. Please feel free to submit a patch/create a PR.
