### ISSUE TITLE
Should we check the result of PJ_POOL_ZALLOC_T?

### ISSUE THREAD

**Issue by Leonard76152** [pjsip/pjproject#2885]
### Describe the bug

Should we check the result of PJ_POOL_ZALLOC_T?

### Steps to reproduce

Should we check the result of PJ_POOL_ZALLOC_T?

### PJSIP version

2.10

### Context

Should we check the result of PJ_POOL_ZALLOC_T?

### Log, call stack, etc

```shell
Should we check the result of PJ_POOL_ZALLOC_T?
```

**Comment by sauwming** [comment]
If the allocation is from a pool that you know has enough free capacity, then it's not necessary (and you need to check the result of the pool creation instead).

Having said that, memory allocation failure is extremely rare nowadays, with the amount of memory as well as virtual memory that can be utilised by today's OS.

**Comment by Leonard76152** [comment]
Got it. Thanks!
