### ISSUE TITLE
A possible data race in the variable thread_tls_id?

### ISSUE THREAD

**Issue by ryancaicse** [pjsip/pjproject#2890]
### Describe the bug

The variable thread_tls_id is a shared variable.
https://github.com/pjsip/pjproject/blob/ea7105c222d657d3c1f7fb18ff9130450e2e40e6/pjlib/src/pj/os_core_unix.c#L149

A thread may run the method `pj_shutdown`.
https://github.com/pjsip/pjproject/blob/ea7105c222d657d3c1f7fb18ff9130450e2e40e6/pjlib/src/pj/os_core_unix.c#L269-L272

Another may run the method `thread_main`.
https://github.com/pjsip/pjproject/blob/ea7105c222d657d3c1f7fb18ff9130450e2e40e6/pjlib/src/pj/os_core_unix.c#L533-L538

Should a lock is put to guard them?

### Steps to reproduce

None

### PJSIP version

2.11

### Context

None

### Log, call stack, etc

```shell
None
```

**Comment by sauwming** [comment]
`pj_shutdown()` is supposed to be called at the very end, so all threads should have been stopped and destroyed.

**Comment by ryancaicse** [comment]
@sauwming Thanks for your reply.

Would it possible for the method `thread_main` is called multiple times by different threads and races with the variables `thread_tls_id` that is not locked.

**Comment by sauwming** [comment]
`thread_tls_id` is a read-only key and the value is not supposed to change during its lifetime (from its allocation using `pthread_key_create()` in `pj_thread_local_alloc()` until the shutdown `pj_thread_local_free()` that will call `pthread_key_delete()`).

**Comment by ryancaicse** [comment]
OK, Thank so much for your time!
