### ISSUE TITLE
[iOS] AudioComponentInstanceDispose sometimes hangs

### ISSUE THREAD

**Issue by mcpttdev** [pjsip/pjproject#2896]
### Describe the bug

Sometimes AudioComponentInstanceDispose does not return, causing the system to eventually deadlock. 

If that is the case, it is most likely an Apple issue but opening this ticket in case others encounter the same issue. One theory is that it happens if shutting down the sound device due to or during an audio interrupt. In our scenario we do see that one thread is in the process of shutting down the sound device and another thread is notified about an audio interrupt at the app layer. 

It also seems [Unity user encountered a similar problem ](https://forum.unity.com/threads/random-unknown-crashes-on-ios-15.1191784/)and their dumps also seems to be triggered by audio interrupts but it can be a coincidence of course.

### Steps to reproduce

This is hard to reproduce. One theory is that the timing between calling AudioComponentInstanceDispose and an audio interrupt might influence but it is just a guess at this point.

### PJSIP version

2.11.1

### Context

We have only seen this in iOS 15 which matches observations from the Unity thread but can't say 100% that it never happened in previous iOS versions since we have few clients deployed and the crash is fairly rare.

### Log, call stack, etc

```shell
Logs are shared with pjsip.

From the partial dumps below it appears as thread 0 times out due to a deadlock since pjsua_lock is still blocked by the call in thread 9 trying to shutdown the sound card (AudioComponentInstanceDispose).


Thread 0 name:
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001b72931a4 __ulock_wait + 8
1   libsystem_pthread.dylib       	0x00000001f06f4b00 _pthread_join + 452 (pthread_cancelable.c:290)
2   ios_sdk                 	        0x0000000105f2e300 pj_thread_join + 2106112 (os_core_unix.c:732)
3   ios_sdk                 	        0x0000000106060694 pjsua_stop_worker_threads + 3360404 (pjsua_core.c:850)
4   ios_sdk                 	        0x00000001060628f8 pjsua_destroy2 + 3369208 (pjsua_core.c:1872)
5   ios_sdk                 	        0x0000000105d43a90 sdk_stop_internal + 464 (sdk_core.c:342)
6   ios_sdk                  	        0x0000000105d445ec sdk_stop + 60 (sdk_core.c:360)
7   app                     	        0x000000010449fa90 closure #1 in AVManager.handleInterruption(_:) + 16 (AVManager.swift:101)
8   app                     	        0x000000010443e204 thunk for @escaping @callee_guaranteed () -> () + 48 (<compiler-generated>:0)
9   libdispatch.dylib             	0x00000001800c1914 _dispatch_call_block_and_release + 32 (init.c:1517)
10  libdispatch.dylib             	0x00000001800c3660 _dispatch_client_callout + 20 (object.m:560)
11  libdispatch.dylib             	0x00000001800d1b60 _dispatch_main_queue_callback_4CF + 944 (inline_internal.h:2601)
12  CoreFoundation                	0x0000000180409cd4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16 (CFRunLoop.c:1795)
13  CoreFoundation                	0x00000001803c3eac __CFRunLoopRun + 2540 (CFRunLoop.c:3144)
14  CoreFoundation                	0x00000001803d73b8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
15  GraphicsServices              	0x000000019bd6738c GSEventRunModal + 164 (GSEvent.c:2200)
16  UIKitCore                     	0x0000000182d776a8 -[UIApplication _run] + 1100 (UIApplication.m:3493)
17  UIKitCore                     	0x0000000182af67f4 UIApplicationMain + 2092 (UIApplication.m:5046)
18  app.                        	0x00000001044d22b8 main + 64 (AppDelegate.swift:11)
19  dyld                          	0x0000000104c6da24 start + 520 (dyldMain.cpp:876)
```

One of the pjsip worker threads processes a media update causing a shutdown of the sound device. In this case, only speaker was active so it is not related to trying to use the microphone (something that was mentioned in the Unity thread)
```
Thread 9:
0   libsystem_kernel.dylib        	0x00000001b7292ae4 __semwait_signal + 8
1   libsystem_c.dylib             	0x000000018b273f00 nanosleep + 216 (nanosleep.c:104)
2   libc++.1.dylib                	0x0000000198b6c820 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 84 (__threading_support:546)
3   libAudioToolboxUtility.dylib  	0x0000000199446d50 caulk::concurrent::guarded_lookup_hash_table<unsigned int, BaseOpaqueObject*, (caulk::concurrent::guarded_lookup_hash_table_options)0>::remove(unsigned int) + 184 (thread:386)
4   libAudioToolboxUtility.dylib  	0x000000019944a118 BaseOpaqueObject::~BaseOpaqueObject() + 68 (OpaqueObjectMgr.cpp:87)
5   libEmbeddedSystemAUs.dylib    	0x00000001bc056a04 AURemoteIO::~AURemoteIO() + 336 (OpaqueObjectMgr.h:181)
6   libEmbeddedSystemAUs.dylib    	0x00000001bc060040 ausdk::ComponentBase::AP_Close(void*) + 116 (ComponentBase.cpp:68)
7   AudioToolboxCore              	0x00000001930b46cc AudioComponentInstanceDispose + 88 (APComponent.mm:415)
8   ios_sdk                 	        0x0000000105fb7f7c ca_stream_destroy + 2670460 (coreaudio_dev.m:2281)
9   ios_sdk                 	        0x0000000105fb4b0c pjmedia_aud_stream_destroy + 2657036 (audiodev.c:625)
10  ios_sdk                 	        0x0000000105f8728c stop_sound_device + 2470540 (sound_port.c:352)
11  ios_sdk                 	        0x0000000105f87244 pjmedia_snd_port_destroy + 2470468 (sound_port.c:541)
12  ios_sdk                 	        0x00000001060778a4 close_snd_dev + 3455140 (pjsua_aud.c:2072)
13  ios_sdk                 	        0x000000010607bbbc pjsua_set_null_snd_dev + 3472316 (pjsua_aud.c:2259)
```
```

**Comment by linlingyun** [comment]
I think this is an iOS system's problem. We met this issue in Wwise too and it has become the top1 crash in our game. And since this is an Audio main thread waiting for iOS system to unlock the signal, so this will cause Audio main thread keep waiting .Therefore, when main thread try to cantact with Audio main thread, this crash happend.

**Comment by johanlantz** [comment]
@linlingyun thanks for providing more information. Some questions:
- Is your project using pjsip or do you see this issue in another context?
- Have your company opened any ticket with Apple?
- Can you confirm if this started to happen for you in iOS 15 or did you see it before as well?

**Comment by mcpttdev** [comment]
@linlingyun thanks for providing more information. Some questions:

Is your project using pjsip or do you see this issue in another context?
Have your company opened any ticket with Apple?
Can you confirm if this started to happen for you in iOS 15 or did you see it before as well?

**Comment by linlingyun** [comment]
- We are not using pjsip, we use Wwise as our sound Engine
- Sorry, I don't know what's "open ticket" means
- This crash happens in almost every iOS version
![image](https://user-images.githubusercontent.com/23370126/143850795-1c6fd0f2-1726-402a-aa2b-c89904edcaf1.png)

**Comment by johanlantz** [comment]
Thank you, that is very helpful. 
With "open ticket" I simply wanted to ask if your company had contacted Apple about this problem?

**Comment by linlingyun** [comment]
> Thank you, that is very helpful. With "open ticket" I simply wanted to ask if your company had contacted Apple about this problem?

They need a clear recurrence path, but we don't know how to recurrent it stable now.

**Comment by mcpttdev** [comment]
Yes, it is hard to reproduce.

Final question: There is no iOS 15 in your chart. Is the brown color iOS 15?

**Comment by linlingyun** [comment]
> Yes, it is hard to reproduce.
> 
> Final question: There is no iOS 15 in your chart. Is the brown color iOS 15?

Yes, the brown color part means "others". It's include iOS 15.

**Comment by mcpttdev** [comment]
Thank you. We will post here if we find a way to reproduce it.
