### ISSUE TITLE
PJSUA: Problem with outgoing calls

### ISSUE THREAD

**Issue by ogogon** [pjsip/pjproject#2898]
### Describe the bug

Colleagues, please tell me what has changed and what is my problem!

I took my code from about a year ago, that worked for me, and recompile it, updating the components of the operating system.

After that, the problems started - the outgoing call is initialized, but after I pick up the phone on the phone receiving the call, the call is canceled.
At the same time, strange messages appear on the application screen, clearly from the library:
```
warning: discarded first playback frame
warning: discarded first playback frame
warning: Auto-filling the buffer (your application is buggy and/or got xruns)
```

The code for making an outgoing call previously worked for me and is taken from the example:

```
pj_str_t uri = pj_str ("sip:100@pbx.mydomain.org");
status = pjsua_call_make_call (acc_id, &uri, 0, NULL, NULL, NULL);
if (status != PJ_SUCCESS)
      error_exit ("Error making call", status);
```
If I turned to the wrong address, then I ask you not to be angry with me, but to suggest where I could direct my question.

### Steps to reproduce

The code causing the error is given in the text of the describe, if necessary, I can provide more detailed information.

### PJSIP version

pjsip-2.11.1 

### Context

FreeBSD 12.2-RELEASE-p7 GENERIC amd64

### Log, call stack, etc

```shell
ogogon@ot:/usr/local/src/sipcc# ./sipcc 

  .oooooo..o ooooo ooooooooo.                       SIP console client.
 d8P'    `Y8 `888' `888   `Y88.
 Y88bo.       888   888   .d88'  .ooooo.   .ooooo.
  `"Y8888o.   888   888ooo88P'  d88' `"Y8 d88' `"Y8.
      `"Y88b  888   888         888       888               v.0.2.0.a2
 oo     .d8P  888   888         888   .o8 888   .o8
  8""88888P' o888o o888o        `Y8bod8P' `Y8bod8P'
 
      >X<           |||        `  ___  '       ,,,,,         ,,,,,
     (o o)         (o o)      -  (O o)  -     /(o o)\       /(o o)\
-ooO--(_)--Ooo-ooO--(_)--Ooo-ooO--(_)--Ooo-ooO--(_)--Ooo-ooO--(_)--Ooo-

BLF module included.
Simplex module included.
GPIO-USB module included.
GPIO-LPT module included.

05:46:55.677         os_core_unix.c !pjlib 2.11.1 for POSIX initialized
05:46:55.680         sip_endpoint.c  .Creating endpoint instance...
05:46:55.688                  pjlib  .select() I/O Queue created (0x8017363a8)
05:46:55.688         sip_endpoint.c  .Module "mod-msg-print" registered
05:46:55.688        sip_transport.c  .Transport manager created.
05:46:55.688           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
Transports: 1
    Transport 'ssl': 0.0.0.0:5080

Accounts: 0

Transport 'ssl' create.
SIPcc# call 600
warning: discarded first playback frame
warning: discarded first playback frame
Error making callSIPcc# warning: Auto-filling the buffer (your application is buggy and/or got xruns)

SIPcc#
```

**Comment by sauwming** [comment]
We need a more complete PJSIP log to understand the problem.
And the strange message you described is only about audio issue, it has nothing to do with the call cancellation itself.

Alternatively, you can use our sample app instead.

Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
