### ISSUE TITLE
Be lenient when receiving multiple SRTP crypto attribute lines in SDP answer

### ISSUE THREAD

**Issue by nanangizz** [pjsip/pjproject#2907]
Currently PJSIP will disable the media in this scenario with error code `PJMEDIA_SRTP_ESDPAMBIGUEANS`. [The standard](https://datatracker.ietf.org/doc/html/rfc4568#section-5.1.2) does prohibit multiple SRTP crypto attributes in the answer, but perhaps we can try to be lenient, e.g: check those crypto lines, if a matched crypto (and tag) is found, use it.

**Comment by sauwming** [comment]
Since the original report, there hasn't been any request about this. And since it's against the RFC and pertains to security, I'm rather reluctant to implement this.
