### ISSUE TITLE
call_disconnect() not checking if tdata is NULL after a successful call to pjsip_inv_end_session()

### ISSUE THREAD

**Issue by dbrichards** [pjsip/pjproject#2935]
### Describe the bug

The function _call_disconnect_() defined in _pjsua_call_.c is not verifying that _tdata_ != NULL after a successful call to _pjsip_inv_end_session_(). This causes the function _pjsip_inv_send_msg_() to assert when it is called in _call_disconnect_(). This check must be made because in certain cases _pjsip_inv_end_session_() can set _tdata_ to NULL and still return PJ_SUCCESS.  

Most places in PJSUA calling _pjsip_inv_end_session_() make this check, but several do not. Another case is in _on_retransmit_() in _sip_100rel_.c, and _perform_test_() in _inv_offer_answer_test_.c

### Steps to reproduce

I observed the assert when running a heavy random call load on my application. Unfortunately I cannot identify the exact call scenario that caused it. 

### PJSIP version

2.11

### Context

Centos 7.

### Log, call stack, etc

```shell
N/A
```

**Comment by silentindark** [comment]
@dbrichards I found your previous report (https://github.com/pjsip/pjproject/issues/2761) about this issue.
@sauwming @nanangizz Could you please take a look?

**Comment by sauwming** [comment]
Right, looks like the issue is valid.
Will create a PR for this.
