### ISSUE TITLE
1080p30fps h264 Support

### ISSUE THREAD

**Issue by reksi** [pjsip/pjproject#2945]
### Describe the bug

I made some changes to receive the 1080p h264 video on basic call. In order to send profile-level-id 428028 in SDP, I have set below changes to code.
Looks like, the 1080p decoding and rendering are not stable. Are there any supported limits to receive the maximum resolution and frame rate? Do you have additional suggestions for the below settings to increase the ability of pjsua?

_ffmpeg_vid_codecs.c_ (for ffmpeg with xh264)
```
#if PJMEDIA_HAS_FFMPEG_CODEC_H264
    {
	{PJMEDIA_FORMAT_H264, PJMEDIA_RTP_PT_H264, {"H264",4},
	 {"Constrained Baseline (level=40, pack=1)", 39}},
	0,
	{1920, 1080},	{30, 1},	2560000, 5872000,
	&h264_packetize, &h264_unpacketize, &h264_preopen, &h264_postopen,
	&pjmedia_vid_codec_h264_match_sdp,
	/* Leading space for better compatibility (strange indeed!) */
	{2, { {{"profile-level-id",16},    {"428028",6}},
	      {{" packetization-mode",19},  {"1",1}}, } },
    },
```
_openh264.cpp_ (for cisco openh264 v2.1.1)
```
#  define DEFAULT_WIDTH		1920
#  define DEFAULT_HEIGHT	1080
#else
#  define DEFAULT_WIDTH		1920
#  define DEFAULT_HEIGHT	1080
#endif

#define DEFAULT_FPS		30
#define DEFAULT_AVG_BITRATE	2560000
#define DEFAULT_MAX_BITRATE	5872000

#define MAX_RX_WIDTH		1920
#define MAX_RX_HEIGHT		1080
```
_vid_stream_
```
/* Default width and height for the renderer, better be set to maximum
 * acceptable size.
 */
#define DEF_RENDERER_WIDTH		    1920
#define DEF_RENDERER_HEIGHT		    1080
```
_vid_codec_util.c_
```
/* Default aspect ratio, if not specified */
#define DEFAULT_H264_RATIO_NUM	    16
#define DEFAULT_H264_RATIO_DENUM    9

{ 40, 243000,  8100,  20000 }, /*< level 28 */
```

#### offer from pjsua

> m=video 19902 RTP/AVP 97
> c=IN IP4 192.168.x.x
> b=TIAS:5872000
> a=rtcp:19903 IN IP4 192.168.x.x
> a=sendrecv
> a=rtpmap:97 H264/90000
> a=fmtp:97 profile-level-id=428028; packetization-mode=1
> a=ssrc:611747358 cname:638ffd145c790b90
> a=rtcp-fb:* nack pli

#### answer from term cisco sip client

> m=video 50670 RTP/AVP 126
> b=TIAS:5872000
> a=label:11
> a=answer:full
> a=extmap:14 http://protocols.cisco.com/timestamp#100us
> a=rtpmap:126 H264/90000
> a=fmtp:126 profile-level-id=428016;packetization-mode=1;max-mbps=490000;max-fs=8160;max-cpb=200;max-br=5000;max-smbps=490000;sar-supported=16;max-fps=6000
> a=content:main
> a=rtcp-fb:* nack pli
> a=trafficclass:conversational.video.immersive.aq:admitted

I got a black screen and the following logs. Saying missing iframe to decode picture,
#### Tested with openh264 v2.1.1

> 09:31:48.671   vstenc0x7f47b00293d8  .......Encoder stream started
> 09:31:48.671   vstdec0x7f47b00293d8  .......Decoder stream started
> 09:31:48.671            pjsua_vid.c  .......Setting up RX..
> 09:31:48.671            pjsua_vid.c  ........Creating video window: type=stream, cap_id=-1, rend_id=2
> 09:31:48.671             vid_port.c  .........Opening device SDL renderer [SDL] for render: format=I420, size=1920x1080 @45:1 fps
> 09:31:48.676   vstdec0x7f47b00293d8 !RTP status: badpt=0, badssrc=0, dup=0, outorder=0, probation=-1, restart=0
> 09:31:48.711             vid_port.c !.........Device SDL renderer [SDL] opened: format=I420, size=1920x1080 @45:1 fps
> 09:31:48.714             vid_conf.c  .........Added port 0 (SDL renderer)
> 09:31:48.714            pjsua_vid.c  .........stream window id 0 created for cap_dev=-1 rend_dev=2
> 09:31:48.714            pjsua_vid.c  .........Window 0 created
> 09:31:48.716             vid_conf.c  ........Added port 1 (vstdec0x7f47b00293d8)
> 09:31:48.717             vid_conf.c  ........Updating render state for port id 0 (1 sources)..
> 09:31:48.717             vid_conf.c  ........This port only has single source with matched format & size, no conversion needed
> 09:31:48.717             vid_conf.c  ........Port 1 (vstdec0x7f47b00293d8) transmitting to port 0 (SDL renderer)
> 09:31:48.717              sdl_dev.c  ........Starting sdl video stream
> 09:31:48.719             vid_conf.c  .......Added port 2 (vstenc0x7f47b00293d8)
> 09:31:48.719            pjsua_vid.c  .......Setting up TX..
> 09:31:48.719            pjsua_vid.c  ........Creating video window: type=preview, cap_id=1, rend_id=2
> 09:31:48.719             vid_port.c  .........Opening device Dummy video device (0x000B) [v4l2] for capture: format=I420, size=1920x1080 @30:1 fps
> 09:31:48.721             v4l2_dev.c  .........  mmap streaming initialized
> 09:31:48.721             vid_port.c  .........Device Dummy video device (0x000B) [v4l2] opened: format=I420, size=1920x1080 @30:1 fps
> 09:31:48.797             vid_conf.c  .........Added port 3 (Dummy video device (0x000B))
> 09:31:48.797             vid_port.c  .........Opening device SDL renderer [SDL] for render: format=I420, size=1920x1080 @30:1 fps
> 09:31:48.830             vid_port.c  .........Device SDL renderer [SDL] opened: format=I420, size=1920x1080 @30:1 fps
> 09:31:48.838           openh264.cpp !Decode couldn't produce picture, input nframes=21, concatenated size=22144 bytes, ret=0
> 09:31:48.841          pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x7f478402af58
> 09:31:48.841          pjsua_media.c  Sending video keyframe request via SIP INFO
> 09:31:48.841           pjsua_call.c  Call 0 sending INFO request..
> 09:31:48.868           openh264.cpp !Decode couldn't produce picture, input nframes=22, concatenated size=24558 bytes, ret=0

Send SIP INFO to request iframe and get 200 OK but keep failing

> 09:31:48.920      tsx0x7f4774002b88  .Incoming Response msg 200/INFO/cseq=28319 (rdata0x55cdc4c94828) in state Calling
> 09:31:48.920      tsx0x7f4774002b88  ..State changed from Calling to Completed, event=RX_MSG
> 09:31:48.920      dlg0x55cdc4c98618  ...Received Response msg 200/INFO/cseq=28319 (rdata0x55cdc4c94828)
> 09:31:48.920      dlg0x55cdc4c98618  ...Transaction tsx0x7f4774002b88 state changed to Completed
> 09:31:48.920      tsx0x7f4774002b88  Timeout timer event
> 09:31:48.920      tsx0x7f4774002b88  .State changed from Completed to Terminated, event=TIMER
> 09:31:48.920      dlg0x55cdc4c98618  ..Transaction tsx0x7f4774002b88 state changed to Terminated
> 09:31:48.920      tsx0x7f4774002b88  Timeout timer event
> 09:31:48.920      tsx0x7f4774002b88  .State changed from Terminated to Destroyed, event=TIMER
> 09:31:48.920     tdta0x7f4774000bc8  ..Destroying txdata Request msg INFO/cseq=28319 (tdta0x7f4774000bc8)
> 09:31:48.920      tsx0x7f4774002b88  Transaction destroyed!
> 09:31:48.938   vstenc0x7f47b00293d8 !Keyframe generated
> 09:31:48.939           openh264.cpp !Decode couldn't produce picture, input nframes=22, concatenated size=24436 bytes, ret=0
> 09:31:48.950    vstrm0x7f47b00293d8 !Sending RTCP-FB PLI packet
> 09:31:48.950          pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x7f478402af58
> 09:31:48.950          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:48.950          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:48.951            pjsua_app.c !Event IFRM
> 09:31:48.951            pjsua_app.c  Event IFRM
> 09:31:48.951            pjsua_app.c  Event IFRM
> 09:31:48.967           openh264.cpp !Decode couldn't produce picture, input nframes=23, concatenated size=24375 bytes, ret=0
> 09:31:48.980          pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x7f478402af58
> 09:31:48.980          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:48.980          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:48.981            pjsua_app.c !Event IFRM
> 09:31:48.981            pjsua_app.c  Event IFRM
> 09:31:48.981            pjsua_app.c  Event IFRM
> 09:31:49.016    vstrm0x7f47b00293d8 !Sending RTCP-FB PLI packet
> 09:31:49.016           openh264.cpp  Decode couldn't produce picture, input nframes=23, concatenated size=24290 bytes, ret=0
> 09:31:49.038           openh264.cpp !Decode couldn't produce picture, input nframes=22, concatenated size=24265 bytes, ret=0
> 09:31:49.057          pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x7f478402af58
> 09:31:49.057          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:49.057          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:49.058            pjsua_app.c !Event IFRM
> 09:31:49.058            pjsua_app.c  Event IFRM
> 09:31:49.058            pjsua_app.c  Event IFRM
> 09:31:49.075           openh264.cpp !Decode couldn't produce picture, input nframes=23, concatenated size=24202 bytes, ret=0
> 09:31:49.108           openh264.cpp  Decode couldn't produce picture, input nframes=22, concatenated size=24241 bytes, ret=0
> 09:31:49.110    vstrm0x7f47b00293d8 !Sending RTCP-FB PLI packet
> 09:31:49.110          pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x7f478402af58
> 09:31:49.110          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:49.110          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7f47841ef7f8, epub=0x55cdc4c42da8
> 09:31:49.115            pjsua_app.c !Event IFRM

#### Tested with ffmpeg x264, almost the same issue;

> 09:52:38.885    ffmpeg_vid_codecs.c  ffmpeg err -1094995529: Invalid data found when processing input
> 09:52:38.885   vstdec0x7f6b5002a278  codec decode() error: Bad or corrupted bitstream (PJMEDIA_CODEC_EBADBITSTREAM)
> 09:52:38.899          pjsua_media.c !Call 0: Media 1: Received media event, type=IFRM, src=0x7f6b5026d238, epub=0x7f6b50029ef8
> 09:52:38.899          pjsua_media.c  Sending video keyframe request via SIP INFO
> 09:52:38.899           pjsua_call.c  Call 0 sending INFO request..
> 09:52:38.914             vid_conf.c !.........Added port 3 (Dummy video device (0x000B))
> 09:52:38.914             vid_port.c  .........Opening device SDL renderer [SDL] for render: format=I420, size=1920x1080 @30:1 fps
> 09:52:38.917                 ffmpeg !h264: non-existing PPS 0 referenced
> 09:52:38.917                 ffmpeg  h264: decode_slice_header error
> 09:52:38.917                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.917                 ffmpeg  h264: decode_slice_header error
> 09:52:38.917                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.917                 ffmpeg  h264: decode_slice_header error
> 09:52:38.917                 ffmpeg  h264: decode_slice_header error
> 09:52:38.917                 ffmpeg  h264: no frame!
> 09:52:38.917    ffmpeg_vid_codecs.c  ffmpeg err -1094995529: Invalid data found when processing input
> 09:52:38.917   vstdec0x7f6b5002a278  codec decode() error: Bad or corrupted bitstream (PJMEDIA_CODEC_EBADBITSTREAM)
> 09:52:38.953                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.953                 ffmpeg  h264: decode_slice_header error
> 09:52:38.953                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.953                 ffmpeg  h264: decode_slice_header error
> 09:52:38.953                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.953                 ffmpeg  h264: decode_slice_header error
> 09:52:38.953                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.953                 ffmpeg  h264: decode_slice_header error
> 09:52:38.953                 ffmpeg  h264: non-existing PPS 0 referenced
> 09:52:38.953                 ffmpeg  h264: decode_slice_header error

When term cisco SIP client change camera vision, even if pjsua requested keyframe with SIP INFO, it can not decode the received frames and fire IFRM events. At least a lot of events cause deadlock.

> 09:52:41.053           pjsua_call.c !.Timed-out trying to acquire PJSUA mutex (possibly system has deadlocked) in pjsua_call_send_request
> 09:52:41.053          pjsua_media.c  Failed requesting keyframe via SIP INFO: Operation timed out (PJ_ETIMEDOUT)

Also, it frequently closes the port and stops transmitting to the SDL renderer.

> 15:06:41.840           pjsua_call.c !.Timed-out trying to acquire PJSUA mutex (possibly system has deadlocked) in pjsua_call_send_request
> 15:06:41.840          pjsua_media.c  Failed requesting keyframe via SIP INFO: Operation timed out (PJ_ETIMEDOUT)
> 15:06:41.840                event.c  Lost event IFRM from publisher [0x0x55df54f17da8] due to full queue.
> 15:06:41.840          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7fb47402b2a8, epub=0x7fb474029ef8
> 15:06:41.840          pjsua_media.c  Sending video keyframe request via SIP INFO
> 15:06:41.840           pjsua_call.c  Call 0 sending INFO request..
> 15:06:41.842            pjsua_app.c !Event IFRM
> 15:06:43.426             vid_conf.c !Failed (3300 time(s)) to put frame to port 0 [SDL renderer]!: Invalid operation (PJ_EINVALIDOP)
> 15:06:43.939           pjsua_call.c !.Timed-out trying to acquire PJSUA mutex (possibly system has deadlocked) in pjsua_call_send_request
> 15:06:43.939          pjsua_media.c  Failed requesting keyframe via SIP INFO: Operation timed out (PJ_ETIMEDOUT)
> 15:06:43.939          pjsua_media.c  Call 0: Media 1: Received media event, type=IFRM, src=0x7fb47402b2a8, epub=0x7fb474029ef8
> 15:06:43.939          pjsua_media.c  Sending video keyframe request via SIP INFO
> 15:06:43.939           pjsua_call.c  Call 0 sending INFO request..
> 15:06:43.943            pjsua_app.c !Event IFRM

### Steps to reproduce

running in container
exec pjsua --config-file /etc/pjsua.config --id=sip:blabla@test.com --no-udp --local-port=5060 --proxy="sip:1xx.xx.xx:5060;transport=TCP;hide;lr" sip:blabla@test2.com

using with Video4Linux (V4L) and alsa loopback devices
pjsua.config
--capture-dev=7
--playback-dev=8
--video
--vcapture-dev=1
--no-color
#--log-level=N Set log max level to N (0(none) to 6(trace)) (default=5)
--log-level=6
#--app-log-level=N Set log max level for stdout display (default=4)
--app-log-level=6
--auto-update-nat=0
--disable-stun

--dis-codec=GSM
--dis-codec=H263
--dis-codec=iLBC
--dis-codec=G722
--dis-codec=speex
--dis-codec=pcmu
--dis-codec=pcma
--dis-codec=opus
--add-codec=opus
--add-codec=pcmu
--add-codec=pcma
#--auto-keyframe=N Specify keyframe request interval (default: disabled)
--auto-keyframe=5
#--no-vad Disable VAD/silence detector (default=vad enabled)
--no-vad
#--ec-tail=MSEC Set echo canceller tail length (default=200)
--ec-tail=0
#--jb-max-size Specify jitter buffer maximum size, in frames (default=-1)
--jb-max-size=30
#--quality=N Specify media quality (0-10, default=8)
--quality=10
#--thread-cnt=N Number of worker threads (default:1)
--thread-cnt=8
--max-calls=1
--no-stderr
--log-file=/var/log/pjsua.log
--auto-answer=200
#Set maximum call duration (default:no limit)
--duration=86400
--stereo
--rtp-port=19900
--ip-addr=1xx.xx.xx

### PJSIP version

2.11

### Context

OS Debian GNU/Linux 10 (buster) 
SDL v2.0.9
ffmpeg version 4.1.8-0+deb10u1 Copyright (c) 2000-2021 the FFmpeg developers
openh264 v2.1.1

### Log, call stack, etc

```shell
41 [pjsua-builder 21/22] RUN cd pjproject   && ./configure   && make dep   && make
#41 sha256:b8e099485e41e10a54d1562d9555293989c5d0e702aa43cb8d6a45876c3ed8ff
#41 0.360 checking build system type... x86_64-unknown-linux-gnu
#41 0.384 checking host system type... x86_64-unknown-linux-gnu
#41 0.385 checking target system type... x86_64-unknown-linux-gnu
#41 0.386 checking for gcc... gcc
#41 0.412 checking whether the C compiler works... yes
#41 0.445 checking for C compiler default output file name... a.out
#41 0.447 checking for suffix of executables... 
#41 0.481 checking whether we are cross compiling... no
#41 0.518 checking for suffix of object files... o
#41 0.540 checking whether we are using the GNU C compiler... yes
#41 0.560 checking whether gcc accepts -g... yes
#41 0.580 checking for gcc option to accept ISO C89... none needed
#41 0.611 checking for g++... g++
#41 0.633 checking whether we are using the GNU C++ compiler... yes
#41 0.683 checking whether g++ accepts -g... yes
#41 0.769 checking for ranlib... ranlib
#41 0.770 checking for ar... ar
#41 0.771 checking for pthread_create in -lpthread... yes
#41 0.813 checking for puts in -lwsock32... no
#41 0.851 checking for puts in -lws2_32... no
#41 0.883 checking for puts in -lole32... no
#41 0.914 checking for puts in -lwinmm... no
#41 0.946 checking for puts in -lsocket... no
#41 0.978 checking for puts in -lrt... yes
#41 1.018 checking for sin in -lm... yes
#41 1.064 checking for uuid_generate in -luuid... yes
#41 1.105 checking for uuid_generate in -luuid... (cached) yes
#41 1.106 checking for library containing gethostbyname... none required
#41 1.146 Setting PJ_M_NAME to x86_64
#41 1.148 checking memory alignment... 8 bytes
#41 1.149 checking how to run the C preprocessor... gcc -E
#41 1.191 checking for grep that handles long lines and -e... /bin/grep
#41 1.193 checking for egrep... /bin/grep -E
#41 1.195 checking for ANSI C header files... yes
#41 1.295 checking for sys/types.h... yes
#41 1.322 checking for sys/stat.h... yes
#41 1.351 checking for stdlib.h... yes
#41 1.380 checking for string.h... yes
#41 1.408 checking for memory.h... yes
#41 1.440 checking for strings.h... yes
#41 1.469 checking for inttypes.h... yes
#41 1.500 checking for stdint.h... yes
#41 1.530 checking for unistd.h... yes
#41 1.558 checking whether byte ordering is bigendian... no
#41 1.626 Checking if floating point is disabled... no
#41 1.626 checking arpa/inet.h usability... yes
#41 1.655 checking arpa/inet.h presence... yes
#41 1.667 checking for arpa/inet.h... yes
#41 1.668 checking assert.h usability... yes
#41 1.693 checking assert.h presence... yes
#41 1.702 checking for assert.h... yes
#41 1.703 checking ctype.h usability... yes
#41 1.728 checking ctype.h presence... yes
#41 1.738 checking for ctype.h... yes
#41 1.739 checking errno.h usability... yes
#41 1.762 checking errno.h presence... yes
#41 1.772 checking for errno.h... yes
#41 1.773 checking fcntl.h usability... yes
#41 1.798 checking fcntl.h presence... yes
#41 1.807 checking for fcntl.h... yes
#41 1.808 checking linux/socket.h usability... yes
#41 1.833 checking linux/socket.h presence... yes
#41 1.841 checking for linux/socket.h... yes
#41 1.842 checking limits.h usability... yes
#41 1.866 checking limits.h presence... yes
#41 1.876 checking for limits.h... yes
#41 1.877 checking malloc.h usability... yes
#41 1.903 checking malloc.h presence... yes
#41 1.913 checking for malloc.h... yes
#41 1.914 checking netdb.h usability... yes
#41 1.940 checking netdb.h presence... yes
#41 1.952 checking for netdb.h... yes
#41 1.953 checking netinet/in_systm.h usability... yes
#41 1.978 checking netinet/in_systm.h presence... yes
#41 1.989 checking for netinet/in_systm.h... yes
#41 1.990 checking netinet/in.h usability... yes
#41 2.016 checking netinet/in.h presence... yes
#41 2.027 checking for netinet/in.h... yes
#41 2.028 checking for netinet/ip.h... yes
#41 2.050 checking netinet/tcp.h usability... yes
#41 2.076 checking netinet/tcp.h presence... yes
#41 2.088 checking for netinet/tcp.h... yes
#41 2.089 checking ifaddrs.h usability... yes
#41 2.115 checking ifaddrs.h presence... yes
#41 2.126 checking for ifaddrs.h... yes
#41 2.127 checking for getifaddrs... yes
#41 2.169 checking semaphore.h usability... yes
#41 2.193 checking semaphore.h presence... yes
#41 2.204 checking for semaphore.h... yes
#41 2.205 checking setjmp.h usability... yes
#41 2.231 checking setjmp.h presence... yes
#41 2.240 checking for setjmp.h... yes
#41 2.241 checking stdarg.h usability... yes
#41 2.266 checking stdarg.h presence... yes
#41 2.274 checking for stdarg.h... yes
#41 2.275 checking stddef.h usability... yes
#41 2.299 checking stddef.h presence... yes
#41 2.307 checking for stddef.h... yes
#41 2.308 checking stdio.h usability... yes
#41 2.333 checking stdio.h presence... yes
#41 2.343 checking for stdio.h... yes
#41 2.344 checking for stdint.h... (cached) yes
#41 2.345 checking for stdlib.h... (cached) yes
#41 2.346 checking for string.h... (cached) yes
#41 2.346 checking sys/ioctl.h usability... yes
#41 2.370 checking sys/ioctl.h presence... yes
#41 2.379 checking for sys/ioctl.h... yes
#41 2.380 checking sys/select.h usability... yes
#41 2.405 checking sys/select.h presence... yes
#41 2.414 checking for sys/select.h... yes
#41 2.415 checking sys/socket.h usability... yes
#41 2.441 checking sys/socket.h presence... yes
#41 2.452 checking for sys/socket.h... yes
#41 2.453 checking sys/time.h usability... yes
#41 2.478 checking sys/time.h presence... yes
#41 2.488 checking for sys/time.h... yes
#41 2.489 checking sys/timeb.h usability... yes
#41 2.514 checking sys/timeb.h presence... yes
#41 2.523 checking for sys/timeb.h... yes
#41 2.524 checking for sys/types.h... (cached) yes
#41 2.525 checking sys/filio.h usability... no
#41 2.550 checking sys/filio.h presence... no
#41 2.563 checking for sys/filio.h... no
#41 2.564 checking sys/sockio.h usability... no
#41 2.589 checking sys/sockio.h presence... no
#41 2.601 checking for sys/sockio.h... no
#41 2.602 checking sys/utsname.h usability... yes
#41 2.629 checking sys/utsname.h presence... yes
#41 2.638 checking for sys/utsname.h... yes
#41 2.639 checking time.h usability... yes
#41 2.664 checking time.h presence... yes
#41 2.673 checking for time.h... yes
#41 2.674 checking for unistd.h... (cached) yes
#41 2.675 checking winsock.h usability... no
#41 2.699 checking winsock.h presence... no
#41 2.712 checking for winsock.h... no
#41 2.712 checking winsock2.h usability... no
#41 2.738 checking winsock2.h presence... no
#41 2.751 checking for winsock2.h... no
#41 2.751 checking for mswsock.h... no
#41 2.768 checking ws2tcpip.h usability... no
#41 2.792 checking ws2tcpip.h presence... no
#41 2.805 checking for ws2tcpip.h... no
#41 2.806 checking uuid/uuid.h usability... yes
#41 2.831 checking uuid/uuid.h presence... yes
#41 2.842 checking for uuid/uuid.h... yes
#41 2.842 checking for net/if.h... yes
#41 2.863 checking for localtime_r... yes
#41 2.908 Setting PJ_OS_NAME to x86_64-unknown-linux-gnu
#41 2.910 Setting PJ_HAS_ERRNO_VAR to 1
#41 2.910 Setting PJ_HAS_HIGH_RES_TIMER to 1
#41 2.911 Setting PJ_HAS_MALLOC to 1
#41 2.911 Setting PJ_NATIVE_STRING_IS_UNICODE to 0
#41 2.911 Setting PJ_ATOMIC_VALUE_TYPE to long
#41 2.912 checking if inet_aton() is available... yes
#41 2.943 checking if inet_pton() is available... yes
#41 2.969 checking if inet_ntop() is available... yes
#41 2.995 checking if getaddrinfo() is available... yes
#41 3.023 checking if sockaddr_in has sin_len member... no
#41 3.045 checking if socklen_t is available... yes
#41 3.069 checking if IPV6_V6ONLY is available... yes
#41 3.095 checking if SO_ERROR is available... yes
#41 3.120 checking if pthread_rwlock_t is available... yes
#41 3.145 checking if pthread_mutexattr_settype() is available... no
#41 3.166 checking if pthread_mutexattr_t has recursive member... no
#41 3.187 checking ioqueue backend... select()
#41 3.187 Building shared libraries... no
#41 3.188 Building pjsua2 library and application... yes
#41 3.190 checking sys/soundcard.h usability... yes
#41 3.218 checking sys/soundcard.h presence... yes
#41 3.228 checking for sys/soundcard.h... yes
#41 3.228 checking linux/soundcard.h usability... yes
#41 3.254 checking linux/soundcard.h presence... yes
#41 3.264 checking for linux/soundcard.h... yes
#41 3.265 checking machine/soundcard.h usability... no
#41 3.289 checking machine/soundcard.h presence... no
#41 3.302 checking for machine/soundcard.h... no
#41 3.303 checking alsa/version.h usability... yes
#41 3.328 checking alsa/version.h presence... yes
#41 3.336 checking for alsa/version.h... yes
#41 3.337 Checking sound device backend... alsa
#41 3.338 Checking if small filter is disabled... no
#41 3.338 Checking if large filter is disabled... no
#41 3.338 Checking if Speex AEC is disabled...no
#41 3.339 Checking if G.711 codec is disabled...no
#41 3.339 Checking if L16 codec is disabled...no
#41 3.339 Checking if GSM codec is disabled...no
#41 3.340 Checking if G.722 codec is disabled...no
#41 3.340 Checking if G.722.1 codec is disabled...no
#41 3.340 Checking if Speex codec is disabled...no
#41 3.341 Checking if iLBC codec is disabled...no
#41 3.341 Checking if libsamplerate is enabled...no
#41 3.342 Building libresample as shared library... no
#41 3.342 checking for sdl2-config... /usr/bin/sdl2-config
#41 3.343 checking SDL availability... 2.0.9
#41 3.349 checking for pkg-config... pkg-config
#41 3.350 checking ffmpeg packages...  libavdevice libavformat libavcodec libswscale libavutil
#41 3.362 checking for enum AVPixelFormat... yes
#41 3.449 checking for v4l2_open in -lv4l2... yes
#41 3.683 checking OpenH264 usability... yes
#41 3.952 checking VPX usability... yes
#41 4.222 Skipping Intel IPP settings (not wanted)
#41 4.223 checking for OpenSSL installations..
#41 4.223 checking openssl/ssl.h usability... yes
#41 4.295 checking openssl/ssl.h presence... yes
#41 4.331 checking for openssl/ssl.h... yes
#41 4.331 checking for ERR_load_BIO_strings in -lcrypto... yes
#41 4.633 checking for SSL_CTX_new in -lssl... yes
#41 4.949 OpenSSL library found, SSL support enabled
#41 5.002 checking for EVP_aes_128_gcm in -lcrypto... yes
#41 5.312 OpenSSL has AES GCM support, SRTP will use OpenSSL
#41 5.313 checking for OpenCORE AMR installations..
#41 5.314 checking opencore-amrnb/interf_enc.h usability... no
#41 5.345 checking opencore-amrnb/interf_enc.h presence... no
#41 5.358 checking for opencore-amrnb/interf_enc.h... no
#41 5.358 checking for Encoder_Interface_init in -lopencore-amrnb... no
#41 5.414 checking vo-amrwbenc/enc_if.h usability... no
#41 5.441 checking vo-amrwbenc/enc_if.h presence... no
#41 5.453 checking for vo-amrwbenc/enc_if.h... no
#41 5.454 checking opencore-amrwb/dec_if.h usability... no
#41 5.478 checking opencore-amrwb/dec_if.h presence... no
#41 5.491 checking for opencore-amrwb/dec_if.h... no
#41 5.492 checking for D_IF_init in -lopencore-amrwb... no
#41 5.544 checking for E_IF_init in -lvo-amrwbenc... no
#41 5.597 checking for SILK installations..
#41 5.597 checking SKP_Silk_SDK_API.h usability... no
#41 5.622 checking SKP_Silk_SDK_API.h presence... no
#41 5.635 checking for SKP_Silk_SDK_API.h... no
#41 5.636 checking for SKP_Silk_SDK_get_version in -lSKP_SILK_SDK... no
#41 5.688 checking for OPUS installations..
#41 5.688 checking opus/opus.h usability... yes
#41 5.713 checking opus/opus.h presence... yes
#41 5.722 checking for opus/opus.h... yes
#41 5.723 checking for opus_repacketizer_get_size in -lopus... yes
#41 6.017 OPUS library found, OPUS support enabled
#41 6.018 checking bcg729 usability... no
#41 6.040 Checking if libyuv is disabled...no
#41 6.040 Checking if libwebrtc is disabled...no
#41 6.041 checking if select() needs correct nfds... no (default)
#41 6.041 ** Decided that select() doesn't need correct nfds (please check)
#41 6.041 checking if pj_thread_create() should enforce stack size... no (default)
#41 6.041 checking if pj_thread_create() should allocate stack... no (default)
#41 6.042 ** Setting non-blocking recv() retval to EAGAIN (please check)
#41 6.042 ** Setting non-blocking connect() retval to EINPROGRESS (please check)
#41 6.064 aconfigure: creating ./config.status
#41 6.153 config.status: creating build.mak
#41 6.167 config.status: creating build/os-auto.mak
#41 6.183 config.status: creating build/cc-auto.mak
#41 6.200 config.status: creating pjlib/build/os-auto.mak
#41 6.217 config.status: creating pjlib-util/build/os-auto.mak
#41 6.234 config.status: creating pjmedia/build/os-auto.mak
#41 6.250 config.status: creating pjsip/build/os-auto.mak
#41 6.266 config.status: creating third_party/build/os-auto.mak
#41 6.282 config.status: creating pjlib/include/pj/compat/os_auto.h
#41 6.294 config.status: creating pjlib/include/pj/compat/m_auto.h
#41 6.306 config.status: creating pjmedia/include/pjmedia/config_auto.h
#41 6.319 config.status: creating pjmedia/include/pjmedia-codec/config_auto.h
#41 6.331 config.status: creating pjsip/include/pjsip/sip_autoconf.h
```

**Comment by sauwming** [comment]
Sorry for not responding earlier. As the issue may no longer be valid now,
please try with the latest version, and reopen if the issue persists.
