### ISSUE TITLE
bdIMAD code lack Free license

### ISSUE THREAD

**Issue by jonassmedegaard** [pjsip/pjproject#2946]
### Describe the bug

The source file https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia-audiodev/bdimad_dev.c states copyright but no license. Corresponding file https://github.com/pjsip/pjproject/blob/master/third_party/bdsound/include/bdimad.h does not mention license either.

Please state the license for these files - preferable within the files themselves.

### Steps to reproduce

Look at the source code.

### PJSIP version

all

### Context

Source

### Log, call stack, etc

```shell
none
```

**Comment by sauwming** [comment]
Those files are just driver/wrapper files (which will not be included to be built unless user explicitly specifies `PJMEDIA_AUDIO_DEV_HAS_BDIMAD`) for PJSIP to be able to use bdsound. To know more and get the license for the dsound library itself, you need to contact them directly.
http://www.bdsound.com/support/category/bdimad/

**Comment by jonassmedegaard** [comment]
I understand the difference between a driver and some underlying code being driven by the driver, and that this code in question is "just driver/wrapper files".

The issue I raise is that the driver/wrapper files lack explicit license (and it is unclear how, if possible at all, to assume any indirect license for these driver/wrapper files).

I understand that the *effective* license when linking this code with code from bdsound may become different from any license granted for these driver/wrapper files - but that is not the issue I am raising here.

The issue I am raising here is the lack of license for code distributed on Github as part of a freely licensed project.
