### ISSUE TITLE
ice_session.c assertion 

### ISSUE THREAD

**Issue by scottishdeveloper** [pjsip/pjproject#2952]
### Describe the bug

During a call with a browser, such as Chrome via SIPjs:

Chrome can sometimes send a **single** mDNS entry in the SDP:

`a=candidate:1434301788 1 udp 2113937151 5f79d637-e3f5-42c2-b38b-d50a822e59f5.local 37519 typ host generation 0 network-cost 999`

If this is the only SDP candidate received, it will crash the application with an assertion:

https://github.com/pjsip/pjproject/blob/c9a75bed34158ac0644c5fba0f66c4f794e37124/pjnath/src/pjnath/ice_session.c#L2508

Of course, if there is more than **one** entry in the SDP, PJSIP will not crash with the assertion and ignore the entry **correctly**, since of course, it cannot translate an mDNS entry:

```        icetp01 !......Error: Invalid SDP "candidate" attribute (PJNATH_EICEINCANDSDP)```

Further information:

https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/
https://support.ipconfigure.com/hc/en-us/articles/360031237552-WebRTC-not-working-in-Google-Chrome-over-local-network-mDNS-

### Steps to reproduce

Send a single SDP entry to PJSIP, which is invalid (such as an mDNS entry) to crash it.

### PJSIP version

Master@Today

### Context

mDNS on Chrome

### Log, call stack, etc

```shell
2022-01-20 19:59:19.737 19872-19872/? A/DEBUG: Abort message: '../src/pjnath/ice_session.c:2493: pj_status_t pj_ice_sess_start_check(pj_ice_sess *): assertion "ice->clist.count > 0 || ice->is_trickling" failed'
```

**Comment by sauwming** [comment]
I tried it here and it seemed to work fine (no assertion):
```
10:37:12.675                icetp00 !Error: Invalid SDP "candidate" attribute (PJNATH_EICEINCANDSDP)
10:37:12.675                icetp00  Processing SDP: support ICE=1, common comp_cnt=1, ice_mismatch=1, ice_restart=0, local_role=Controlled, trickle=0
10:37:12.675                icetp00  Stopping ICE, reason=ICE ice_mismatch in remote offer
```

I'm not sure that I understand what you mean by `one entry` though. Because if I don't provide any other lines, PJSIP will fail with `Error parsing/validating SDP body: Invalid SDP origin line (PJMEDIA_SDP_EINORIGIN)` instead.

So can you provide us the complete SIP message that triggered the assertion?

**Comment by scottishdeveloper** [comment]
Thanks for testing Sauwming.

Here is a a full dialog from PJSIP, hope it helps:

Note that:

Device: **samsungs9** -> Android 10
Browser: **testweb** -> Chrome (Version 97.0.4692.71 (Official Build) (64-bit))

`
           pjsua_aud.c !Set sound device: capture=1, playback=1, mode=2
           pjsua_aud.c  .No changes in capture and playback devices
           pjsua_aud.c  Set sound device: capture=1, playback=1, mode=2
           pjsua_aud.c  .No changes in capture and playback devices
          pjsua_call.c  Making call with acc #0 to sip:testweb@192.168.0.90
           pjsua_aud.c  .Set sound device: capture=1, playback=1, mode=0
           pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@16000/1/20ms
     android_jni_dev.c  ...Creating Android JNI stream
     android_jni_dev.c  ...sampleFormat=2, channelInCfg=16, buffSize=1280, clockRate=16000
     android_jni_dev.c  ...Using audio input source : 1
     android_jni_dev.c  ...Audio record initialized successfully.
     android_jni_dev.c !Setting thread priority successful
     android_jni_dev.c !...Audio track initialized successfully.
     android_jni_dev.c !Setting thread priority successful
     android_jni_dev.c !...Android JNI stream started
         pjsua_media.c  .Call 0: initializing media..
               icetp00  ..Creating ICE stream transport with 2 component(s)
               icetp00  ...Comp 1: srflx candidate (tpid=64) starts Binding discovery
               icetp00  ...Comp 1/1: host candidate 192.168.0.11:4001 (tpid=64) added
    udprel0x7b1542a000  ...TURN client session created
    udprel0x7b1542a000  ...State changed Null --> Resolving
    udprel0x7b1542a000  ...State changed Resolving --> Resolved
    udprel0x7b1542a000  ...State changed Resolved --> Allocating
               icetp00  ...Comp 1/2: TURN relay candidate (tpid=128) waiting for allocation
               icetp00  ...Comp 2: srflx candidate (tpid=64) starts Binding discovery
               icetp00  ...Comp 2/1: host candidate 192.168.0.11:4039 (tpid=64) added
    udprel0x7ae184ec00  ...TURN client session created
    udprel0x7ae184ec00  ...State changed Null --> Resolving
    udprel0x7ae184ec00  ...State changed Resolving --> Resolved
    udprel0x7ae184ec00  ...State changed Resolved --> Allocating
               icetp00  ...Comp 2/2: TURN relay candidate (tpid=128) waiting for allocation
               icetp00  ...ICE stream transport 0x7c07a8c028 created
               icetp01  ..Creating ICE stream transport with 2 component(s)
               icetp01  ...Comp 1: srflx candidate (tpid=64) starts Binding discovery
               icetp01  ...Comp 1/1: host candidate 192.168.0.11:4057 (tpid=64) added
    udprel0x7ae1859c00  ...TURN client session created
    udprel0x7ae1859c00  ...State changed Null --> Resolving
    udprel0x7ae1859c00  ...State changed Resolving --> Resolved
    udprel0x7ae1859c00  ...State changed Resolved --> Allocating
               icetp01  ...Comp 1/2: TURN relay candidate (tpid=128) waiting for allocation
               icetp01  ...Comp 2: srflx candidate (tpid=64) starts Binding discovery
               icetp01  ...Comp 2/1: host candidate 192.168.0.11:4064 (tpid=64) added
    udprel0x7ae185e800  ...TURN client session created
    udprel0x7ae185e800  ...State changed Null --> Resolving
    udprel0x7ae185e800  ...State changed Resolving --> Resolved
    udprel0x7ae185e800  ...State changed Resolved --> Allocating
               icetp01  ...Comp 2/2: TURN relay candidate (tpid=128) waiting for allocation
               icetp01  ...ICE stream transport 0x7c07aa7028 created
         pjsua_media.c  ..Media index 0 selected for audio call 0
    stuntp0x7b15410000 !.STUN mapped address found/changed: 192.168.0.11:4057
               icetp01  .Comp 1: Binding discovery complete, srflx address is 192.168.0.11:4057
    stuntp0x7b1546c900  .STUN mapped address found/changed: 192.168.0.11:4001
               icetp00  .Comp 1: Binding discovery complete, srflx address is 192.168.0.11:4001
    udprel0x7b1542a000  .Retrying request with new authentication
    stuntp0x7ae17faf00  .STUN mapped address found/changed: 192.168.0.11:4039
               icetp00  .Comp 2: Binding discovery complete, srflx address is 192.168.0.11:4039
    udprel0x7ae184ec00  .Retrying request with new authentication
    udprel0x7ae1859c00  .Retrying request with new authentication
    stuntp0x7b15410100  .STUN mapped address found/changed: 192.168.0.11:4064
               icetp01  .Comp 2: Binding discovery complete, srflx address is 192.168.0.11:4064
    udprel0x7ae185e800  .Retrying request with new authentication
    udprel0x7b1542a000  .State changed Allocating --> Ready
               icetp00  ..Comp 1/1: TURN allocation (tpid=128) complete, relay address is 192.168.0.90:61911
    udprel0x7ae184ec00  .State changed Allocating --> Ready
               icetp00  ..Comp 2/1: TURN allocation (tpid=128) complete, relay address is 192.168.0.90:52005
    udprel0x7ae1859c00  .State changed Allocating --> Ready
               icetp01  ..Comp 1/1: TURN allocation (tpid=128) complete, relay address is 192.168.0.90:61847
    udprel0x7ae185e800  .State changed Allocating --> Ready
               icetp01  ..Comp 2/1: TURN allocation (tpid=128) complete, relay address is 192.168.0.90:49785
               icetp00  ICE session created, comp_cnt=2, role is Controlling agent
               icetp00  ICE nomination type set to regular
               icetp00  Candidate 0 added: comp_id=1, type=host, foundation=Hc0a8000b, addr=192.168.0.11:4001, base=192.168.0.11:4001, prio=0x7effffff (2130706431)
               icetp00  Candidate 1 added: comp_id=1, type=relay, foundation=Rc0a8005a, addr=192.168.0.90:61911, base=192.168.0.90:61911, prio=0xffffff (16777215)
               icetp00  Candidate 2 added: comp_id=2, type=host, foundation=Hc0a8000b, addr=192.168.0.11:4039, base=192.168.0.11:4039, prio=0x7efffffe (2130706430)
               icetp00  Candidate 3 added: comp_id=2, type=relay, foundation=Rc0a8005a, addr=192.168.0.90:52005, base=192.168.0.90:52005, prio=0xfffffe (16777214)
               icetp01  ICE session created, comp_cnt=2, role is Controlling agent
               icetp01  ICE nomination type set to regular
               icetp01  Candidate 0 added: comp_id=1, type=host, foundation=Hc0a8000b, addr=192.168.0.11:4057, base=192.168.0.11:4057, prio=0x7effffff (2130706431)
               icetp01  Candidate 1 added: comp_id=1, type=relay, foundation=Rc0a8005a, addr=192.168.0.90:61847, base=192.168.0.90:61847, prio=0xffffff (16777215)
               icetp01  Candidate 2 added: comp_id=2, type=host, foundation=Hc0a8000b, addr=192.168.0.11:4064, base=192.168.0.11:4064, prio=0x7efffffe (2130706430)
               icetp01  Candidate 3 added: comp_id=2, type=relay, foundation=Rc0a8005a, addr=192.168.0.90:49785, base=192.168.0.90:49785, prio=0xfffffe (16777214)
      srtp0x7b157d6800  SRTP uses keying method DTLS-SRTP
      srtp0x7b157d6c00  SRTP uses keying method DTLS-SRTP


pjsua_core.c  ...TX 2970 bytes Request msg INVITE/cseq=28996 (tdta0x7c07a650a8) to TLS 192.168.0.90:5061:

    INVITE sip:testweb@192.168.0.90 SIP/2.0
    Via: SIP/2.0/TLS 192.168.0.11:46627;rport;branch=z9hG4bKPj4cb3ed94-5a67-4dd0-bae7-0a5385c58179;alias
    Max-Forwards: 70
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90
    Contact: <sip:samsungs9@192.168.0.11:46627;transport=TLS;ob>;+sip.ice
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    CSeq: 28996 INVITE
    Route: <sip:192.168.0.90:5061;transport=tls;lr;port=5061>
    Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
    Supported: replaces, 100rel, timer, norefersub
    Session-Expires: 1800
    Min-SE: 90
    User-Agent: SecureCom-Android-PJSIP-2.11-dev
    Content-Type: application/sdp
    Content-Length:  2224
    
    v=0
    o=- 3851764278 3851764278 IN IP4 192.168.0.90
    s=pjmedia
    b=AS:621
    t=0 0
    a=X-nat:1
    m=audio 61911 UDP/TLS/RTP/SAVP 96 97 98 99 100 101 3 0 8 9 102 120 121 122 123
    c=IN IP4 192.168.0.90
    b=TIAS:64000
    a=rtcp:52005 IN IP4 192.168.0.90
    a=sendrecv
    a=rtpmap:96 opus/48000/2
    a=fmtp:96 maxplaybackrate=16000;sprop-maxcapturerate=16000;useinbandfec=1
    a=rtpmap:97 speex/8000
    a=rtpmap:98 speex/32000
    a=rtpmap:99 speex/16000
    a=rtpmap:100 AMR-WB/16000
    a=fmtp:100 octet-align=1
    a=rtpmap:101 iLBC/8000
    a=fmtp:101 mode=30
    a=rtpmap:3 GSM/8000
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:9 G722/8000
    a=rtpmap:102 AMR/8000
    a=fmtp:102 octet-align=1
    a=rtpmap:120 telephone-event/48000
    a=fmtp:120 0-16
    a=rtpmap:121 telephone-event/8000
    a=fmtp:121 0-16
    a=rtpmap:122 telephone-event/32000
    a=fmtp:122 0-16
    a=rtpmap:123 telephone-event/16000
    a=fmtp:123 0-16
    a=ssrc:1333346152 cname:5fac1d5b695dca02
    a=ice-ufrag:63e86ba0
    a=ice-pwd:6f1f0014239ce668413b4020
    a=candidate:Hc0a8000b 1 UDP 2130706431 192.168.0.11 4001 typ host
    a=candidate:Rc0a8005a 1 UDP 16777215 192.168.0.90 61911 typ relay raddr 192.168.0.11 rport 4030
    a=candidate:Hc0a8000b 2 UDP 2130706430 192.168.0.11 4039 typ host
    a=candidate:Rc0a8005a 2 UDP 16777214 192.168.0.90 52005 typ relay raddr 192.168.0.11 rport 4010
    a=rtcp-mux
    a=setup:actpass
    a=fingerprint:SHA-256 A9:7F:A0:9D:8E:C2:D4:D5:00:06:63:82:0A:03:EB:82:9E:AC:FE:1F:C7:69:26:53:4F:1A:73:37:D5:0B:42:0B
    m=video 61847 UDP/TLS/RTP/SAVP 97
    c=IN IP4 192.168.0.90
    b=TIAS:512000
    a=rtcp:49785 IN IP4 192.168.0.90
    a=sendrecv
    a=rtpmap:97 H264/90000
    a=fmtp:97 profile-level-id=42e01e; packetization-mode=1
    a=ssrc:759584528 cname:5fac1d5b695dca02
    a=ice-ufrag:38e6260a
    a=ice-pwd:19fb71f22f0b35e9643ae331
    a=candidate:Hc0a8000b 1 UDP 2130706431 192.168.0.11 4057 typ host
    a=candidate:Rc0a8005a 1 UDP 16777215 192.168.0.90 61847 typ relay raddr 192.168.0.11 rport 4004
    a=candidate:Hc0a8000b 2 UDP 2130706430 192.168.0.11 4064 typ host
    a=candidate:Rc0a8005a 2 UDP 16777214 192.168.0.90 49785 typ relay raddr 192.168.0.11 rport 4025
    a=rtcp-mux
    a=setup:actpass
    a=fingerprint:SHA-256 A9:7F:A0:9D:8E:C2:D4:D5:00:06:63:82:0A:03:EB:82:9E:AC:FE:1F:C7:69:26:53:4F:1A:73:37:D5:0B:42:0B
    
    --end msg--
    
pjsua_core.c  .RX 544 bytes Response msg 407/INVITE/cseq=28996 (rdata0x7b15437318) from TLS 192.168.0.90:5061:

    SIP/2.0 407 Proxy Authentication Required
    Via: SIP/2.0/TLS 192.168.0.11:46627;rport=46627;branch=z9hG4bKPj4cb3ed94-5a67-4dd0-bae7-0a5385c58179;alias;received=192.168.0.11
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90;tag=fd435612ecfb8c3f9e4a4acab18a3289.22579b77
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    CSeq: 28996 INVITE
    Proxy-Authenticate: Digest realm="192.168.0.90", nonce="YenpMmHp6AYscS+a6RW3Vgr19XkWaewG"
    Server: kamailio (5.4.0 (x86_64/linux))
    Content-Length: 0
    
    
    --end msg--
    
pjsua_core.c  ..TX 454 bytes Request msg ACK/cseq=28996 (tdta0x7b155790a8) to TLS 192.168.0.90:5061:

    ACK sip:testweb@192.168.0.90 SIP/2.0
    Via: SIP/2.0/TLS 192.168.0.11:46627;rport;branch=z9hG4bKPj4cb3ed94-5a67-4dd0-bae7-0a5385c58179;alias
    Max-Forwards: 70
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90;tag=fd435612ecfb8c3f9e4a4acab18a3289.22579b77
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    CSeq: 28996 ACK
    Route: <sip:192.168.0.90:5061;transport=tls;lr;port=5061>
    Content-Length:  0
    
    
    --end msg--
    
sip_auth_client.c  ....Digest algorithm is ""
pjsua_core.c  .......TX 3161 bytes Request msg INVITE/cseq=28997 (tdta0x7c07a650a8) to TLS 192.168.0.90:5061:

    INVITE sip:testweb@192.168.0.90 SIP/2.0
    Via: SIP/2.0/TLS 192.168.0.11:46627;rport;branch=z9hG4bKPj635a3e25-d23f-4c6d-bdaa-539fcb5c1a72;alias
    Max-Forwards: 70
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90
    Contact: <sip:samsungs9@192.168.0.11:46627;transport=TLS;ob>;+sip.ice
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    CSeq: 28997 INVITE
    Route: <sip:192.168.0.90:5061;transport=tls;lr;port=5061>
    Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
    Supported: replaces, 100rel, timer, norefersub
    Session-Expires: 1800
    Min-SE: 90
    User-Agent: SecureCom-Android-PJSIP-2.11-dev
    Proxy-Authorization: Digest username="samsungs9", realm="192.168.0.90", nonce="YenpMmHp6AYscS+a6RW3Vgr19XkWaewG", uri="sip:testweb@192.168.0.90", response="8f03bdb74f877cc66659333d1a5a7267"
    Content-Type: application/sdp
    Content-Length:  2224
    
    v=0
    o=- 3851764278 3851764278 IN IP4 192.168.0.90
    s=pjmedia
    b=AS:621
    t=0 0
    a=X-nat:1
    m=audio 61911 UDP/TLS/RTP/SAVP 96 97 98 99 100 101 3 0 8 9 102 120 121 122 123
    c=IN IP4 192.168.0.90
    b=TIAS:64000
    a=rtcp:52005 IN IP4 192.168.0.90
    a=sendrecv
    a=rtpmap:96 opus/48000/2
    a=fmtp:96 maxplaybackrate=16000;sprop-maxcapturerate=16000;useinbandfec=1
    a=rtpmap:97 speex/8000
    a=rtpmap:98 speex/32000
    a=rtpmap:99 speex/16000
    a=rtpmap:100 AMR-WB/16000
    a=fmtp:100 octet-align=1
    a=rtpmap:101 iLBC/8000
    a=fmtp:101 mode=30
    a=rtpmap:3 GSM/8000
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:9 G722/8000
    a=rtpmap:102 AMR/8000
    a=fmtp:102 octet-align=1
    a=rtpmap:120 telephone-event/48000
    a=fmtp:120 0-16
    a=rtpmap:121 telephone-event/8000
    a=fmtp:121 0-16
    a=rtpmap:122 telephone-event/32000
    a=fmtp:122 0-16
    a=rtpmap:123 telephone-event/16000
    a=fmtp:123 0-16
    a=ssrc:1333346152 cname:5fac1d5b695dca02
    a=ice-ufrag:63e86ba0
    a=ice-pwd:6f1f0014239ce668413b4020
    a=candidate:Hc0a8000b 1 UDP 2130706431 192.168.0.11 4001 typ host
    a=candidate:Rc0a8005a 1 UDP 16777215 192.168.0.90 61911 typ relay raddr 192.168.0.11 rport 4030
    a=candidate:Hc0a8000b 2 UDP 2130706430 192.168.0.11 4039 typ host
    a=candidate:Rc0a8005a 2 UDP 16777214 192.168.0.90 52005 typ relay raddr 192.168.0.11 rport 4010
    a=rtcp-mux
    a=setup:actpass
    a=fingerprint:SHA-256 A9:7F:A0:9D:8E:C2:D4:D5:00:06:63:82:0A:03:EB:82:9E:AC:FE:1F:C7:69:26:53:4F:1A:73:37:D5:0B:42:0B
    m=video 61847 UDP/TLS/RTP/SAVP 97
    c=IN IP4 192.168.0.90
    b=TIAS:512000
    a=rtcp:49785 IN IP4 192.168.0.90
    a=sendrecv
    a=rtpmap:97 H264/90000
    a=fmtp:97 profile-level-id=42e01e; packetization-mode=1
    a=ssrc:759584528 cname:5fac1d5b695dca02
    a=ice-ufrag:38e6260a
    a=ice-pwd:19fb71f22f0b35e9643ae331
    a=candidate:Hc0a8000b 1 UDP 2130706431 192.168.0.11 4057 typ host
    a=candidate:Rc0a8005a 1 UDP 16777215 192.168.0.90 61847 typ relay raddr 192.168.0.11 rport 4004
    a=candidate:Hc0a8000b 2 UDP 2130706430 192.168.0.11 4064 typ host
    a=candidate:Rc0a8005a 2 UDP 16777214 192.168.0.90 49785 typ relay raddr 192.168.0.11 rport 4025
    a=rtcp-mux
    a=setup:actpass
    a=fingerprint:SHA-256 A9:7F:A0:9D:8E:C2:D4:D5:00:06:63:82:0A:03:EB:82:9E:AC:FE:1F:C7:69:26:53:4F:1A:73:37:D5:0B:42:0B
    
    --end msg--
    
pjsua_core.c  .RX 416 bytes Response msg 100/INVITE/cseq=28997 (rdata0x7b15437318) from TLS 192.168.0.90:5061:

    SIP/2.0 100 trying -- your call is important to us
    Via: SIP/2.0/TLS 192.168.0.11:46627;rport=46627;branch=z9hG4bKPj635a3e25-d23f-4c6d-bdaa-539fcb5c1a72;alias;received=192.168.0.11
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    CSeq: 28997 INVITE
    Server: kamailio (5.4.0 (x86_64/linux))
    Content-Length: 0
    
    
    --end msg--
    
pjsua_core.c  .RX 622 bytes Response msg 180/INVITE/cseq=28997 (rdata0x7b15437318) from TLS 192.168.0.90:5061:

    SIP/2.0 180 Ringing
    Via: SIP/2.0/TLS 192.168.0.11:46627;received=192.168.0.11;rport=46627;branch=z9hG4bKPj635a3e25-d23f-4c6d-bdaa-539fcb5c1a72;alias
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90;tag=lbqgti03mg
    CSeq: 28997 INVITE
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    Supported: outbound
    User-Agent: SIP.js/0.20.0
    Record-Route: <sip:192.168.0.90:5062;transport=ws;r2=on;lr=on>
    Record-Route: <sip:192.168.0.90:5061;transport=tls;r2=on;lr=on>
    Contact: <sip:mfg3pssr@ul0q96is46gk.invalid;alias=192.168.0.10~52734~6;transport=ws>
    Content-Length: 0
    
    
    --end msg--   

icetp00  .Received an early check for comp 1
icetp01  .Received an early check for comp 1
dtls0x7b1558e000  Setting crypto [:SRTP_AES128_CM_SHA1_80:SRTP_AES128_CM_SHA1_32], errcode=0
dtls0x7b1558e000  DTLS-SRTP negotiation initiated as server
udprel0x7ae1859c00  sendto(): IP 192.168.0.10 has no permission, requesting it first..
icetp01  .Received an early check for comp 1

pjsua_core.c  .RX 2740 bytes Response msg 200/INVITE/cseq=28997 (rdata0x7b15437318) from TLS 192.168.0.90:5061:

    SIP/2.0 200 OK
    Via: SIP/2.0/TLS 192.168.0.11:46627;received=192.168.0.11;rport=46627;branch=z9hG4bKPj635a3e25-d23f-4c6d-bdaa-539fcb5c1a72;alias
    From: sip:samsungs9@192.168.0.90;tag=b16dc0e9-5bf8-4376-98d9-9003c9215b05
    To: sip:testweb@192.168.0.90;tag=lbqgti03mg
    CSeq: 28997 INVITE
    Call-ID: 94960d82-79b7-4304-9b82-6470bdeb2444
    Supported: outbound
    User-Agent: SIP.js/0.20.0
    Record-Route: <sip:192.168.0.90:5062;transport=ws;r2=on;lr=on>
    Record-Route: <sip:192.168.0.90:5061;transport=tls;r2=on;lr=on>
    Allow: ACK,BYE,CANCEL,INFO,INVITE,MESSAGE,NOTIFY,OPTIONS,PRACK,REFER,REGISTER,SUBSCRIBE
    Contact: <sip:mfg3pssr@ul0q96is46gk.invalid;alias=192.168.0.10~52734~6;transport=ws>
    Content-Type: application/sdp
    Content-Length: 2000
    
    v=0
    o=- 3842974343374833394 2 IN IP4 127.0.0.1
    s=-
    t=0 0
    a=msid-semantic: WMS e7b32256-080c-4097-acb7-f90a2cde3c8d
    m=audio 9 UDP/TLS/RTP/SAVP 96 0 8 9 120 121 122 123
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=candidate:1434301788 1 udp 2113937151 170ba328-8d0e-4023-879f-65d5b945007e.local 48905 typ host generation 0 network-cost 999
    a=ice-ufrag:eboQ
    a=ice-pwd:lYdEh0Y+JKiohU9Tr9l/NB0/
    a=ice-options:trickle
    a=fingerprint:sha-256 14:22:15:49:93:58:67:B2:94:B3:55:CA:FA:DD:7F:94:26:3B:07:C3:BC:54:45:FB:81:49:F3:F8:26:BD:FE:34
    a=setup:active
    a=mid:0
    a=sendrecv
    a=msid:e7b32256-080c-4097-acb7-f90a2cde3c8d 36a74dd1-546d-4fab-8777-a4e58eab8c72
    a=rtcp-mux
    a=rtpmap:96 opus/48000/2
    a=fmtp:96 minptime=10;useinbandfec=1
    a=rtpmap:0 PCMU/8000
    a=rtpmap:8 PCMA/8000
    a=rtpmap:9 G722/8000
    a=rtpmap:120 telephone-event/48000
    a=rtpmap:121 telephone-event/8000
    a=rtpmap:122 telephone-event/32000
    a=rtpmap:123 telephone-event/16000
    a=ssrc:982689665 cname:YCrkLyQp7ymwaAvG
    a=ssrc:982689665 msid:e7b32256-080c-4097-acb7-f90a2cde3c8d 36a74dd1-546d-4fab-8777-a4e58eab8c72
    a=ssrc:982689665 mslabel:e7b32256-080c-4097-acb7-f90a2cde3c8d
    a=ssrc:982689665 label:36a74dd1-546d-4fab-8777-a4e58eab8c72
    m=video 9 UDP/TLS/RTP/SAVP 97
    c=IN IP4 0.0.0.0
    a=rtcp:9 IN IP4 0.0.0.0
    a=candidate:1434301788 1 udp 2113937151 170ba328-8d0e-4023-879f-65d5b945007e.local 47658 typ host generation 0 network-cost 999
    a=ice-ufrag:34eB
    a=ice-pwd:KHgc5RfBosvr00Rh6pxxf6CA
    a=ice-options:trickle
    a=fingerprint:sha-256 14:22:15:49:93:58:67:B2:94:B3:55:CA:FA:DD:7F:94:26:3B:07:C3:BC:54:45:FB:81:49:F3:F8:26:BD:FE:34
    a=setup:active
    a=mid:1
    a=sendrecv
    a=msid:- 6619dbd1-6a10-44c5-9229-20c46656ac4e
    a=rtcp-mux
    a=rtpmap:97 H264/90000
    a=fmtp:97 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01e
    a=ssrc:180699074 cname:YCrkLyQp7ymwaAvG
    a=ssrc:180699074 msid:- 6619dbd1-6a10-44c5-9229-20c46656ac4e
    a=ssrc:180699074 mslabel:-
    a=ssrc:180699074 label:6619dbd1-6a10-44c5-9229-20c46656ac4e
    
    --end msg--

inv0x7c07aaa0a8  ....SDP negotiation done: Success
pjsua_media.c  .....Call 0: updating media..
pjsua_media.c  .......Media stream call00:0 is destroyed
icetp00  ......Error: Invalid SDP "candidate" attribute (PJNATH_EICEINCANDSDP)
icetp00  ......Processing SDP: support ICE=1, common comp_cnt=2, ice_mismatch=1, ice_restart=0, local_role=Controlling, trickle=0
icetp00  ......Warning: remote answer mismatch, but it does not reject our offer with 'ice-mismatch'. ICE negotiation may fail
icetp00  ......Error: Invalid SDP "candidate" attribute (PJNATH_EICEINCANDSDP)

A/libc: ../src/pjnath/ice_session.c:2493: pj_status_t pj_ice_sess_start_check(pj_ice_sess *): assertion "ice->clist.count > 0 || ice->is_trickling" failed
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27698 (Thread-100), pid 27511 (com.test.sip)

I/crash_dump64: performing dump of process 27511 (target tid = 27698)
A/libc: ../src/pjnath/ice_session.c:2493: pj_status_t pj_ice_sess_start_check(pj_ice_sess *): assertion "ice->clist.count > 0 || ice->is_trickling" failed
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27698 (Thread-100), pid 27511 (com.test.sip)

E/crash_dump64: unknown process state: t
A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: 'samsung/starltexx/starlte:10/QP1A.190711.020/G960FXXU7DTAA:user/release-keys'
A/DEBUG: Revision: '26'
A/DEBUG: ABI: 'arm64'
A/DEBUG: Timestamp: 2022-01-21 15:31:25+0100
A/DEBUG: pid: 27511, tid: 27698, name: Thread-100  >>> com.test.sip <<<
A/DEBUG: uid: 10845
A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
A/DEBUG: Abort message: '../src/pjnath/ice_session.c:2493: pj_status_t pj_ice_sess_start_check(pj_ice_sess *): assertion "ice->clist.count > 0 || ice->is_trickling" failed'
A/DEBUG:     x0  0000000000000000  x1  0000000000006c32  x2  0000000000000006  x3  0000007ae720f560
A/DEBUG:     x4  0000800000000000  x5  0000800000000000  x6  0000800000000000  x7  0000000000000018
A/DEBUG:     x8  00000000000000f0  x9  0000007c027e45e0  x10 0000000000000000  x11 0000000000000001
A/DEBUG:     x12 0000000000000010  x13 0000000061eac3bd  x14 00018a6cc0b1d8d6  x15 000026b17fb0c436
A/DEBUG:     x16 0000007c028b28c0  x17 0000007c0288f870  x18 0000007ae6400000  x19 00000000000000ac
A/DEBUG:     x20 0000000000006b77  x21 00000000000000b2  x22 0000000000006c32  x23 00000000ffffffff
A/DEBUG:     x24 0000007ae7213d50  x25 0000007ae7213d50  x26 0000007b0e4b5bfc  x27 00000000000fd000
A/DEBUG:     x28 0000007fd3a0dab0  x29 0000007ae720f610
A/DEBUG:     sp  0000007ae720f540  lr  0000007c02843330  pc  0000007c02843360
A/DEBUG: backtrace:
A/DEBUG:       #00 pc 0000000000083360  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: 220051b49364b1c2da3adf10c30832cc)
A/DEBUG:       #01 pc 0000000000083b14  /apex/com.android.runtime/lib64/bionic/libc.so (__assert2+36) (BuildId: 220051b49364b1c2da3adf10c30832cc)
A/DEBUG:       #02 pc 00000000003ede28  /data/app/com.test.sip-2e-DsGevDgYrebfrzuWCZg==/lib/arm64/libpjsua2.so (pj_ice_sess_start_check+228) (BuildId: cb94b6301d3c6d9e96e88f2040ea8f247c42c808)
A/DEBUG:       #03 pc 00000000003f76b8  /data/app/com.test.sip-2e-DsGevDgYrebfrzuWCZg==/lib/arm64/libpjsua2.so (pj_ice_strans_start_ice+372) (BuildId: cb94b6301d3c6d9e96e88f2040ea8f247c42c808)


`

**Comment by scottishdeveloper** [comment]
I tested your change, and it works as I would expect now (error is handled appropriately without assertion).
