### ISSUE TITLE
Compile iPhone project failed

### ISSUE THREAD

**Issue by YuZebra** [pjsip/pjproject#2966]
### Describe the bug

I do the make command, then I get the fail in this 

pjmedia/converter_libswscale.c:81:24: error: variable has incomplete type 'enum PixelFormat' enum AVPixelFormat srcFormat, dstFormat;
pjmedia/converter_libswscale.c:81:35: error: variable has incomplete type 'enum PixelFormat' enum AVPixelFormat srcFormat, dstFormat;

### Steps to reproduce

1. I added config_site.h according to the teaching content and make sure I have '#define PJMEDIA_HAS_VIDEO 1' in the file.
2. I also added '#define PJMEDIA_HAS_FFMPEG 1' 
3. After that I use command ' . /configure-iphone --with-ffmpeg=/opt/local ' to check, I confirm that my content has the following
checking ffmpeg packages... libavdevice libavformat libavcodec libswscale libavutil
4. command 'make'

### PJSIP version

2.11.1

### Context

build environment：mac os 11.4
ffmpeg version 4.4.1

### Log, call stack, etc

```shell
In file included from ../src/pjmedia/converter_libswscale.c:25:
../src/pjmedia/ffmpeg_util.h:54:16: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
                                             enum AVPixelFormat *pixel_format);
                                                  ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
../src/pjmedia/ffmpeg_util.h:56:51: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
pj_status_t PixelFormat_to_pjmedia_format_id(enum AVPixelFormat pf,
                                                  ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
In file included from ../src/pjmedia/converter_libswscale.c:26:
/opt/local/include/libswscale/swscale.h:128:31: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
int sws_isSupportedInput(enum AVPixelFormat pix_fmt);
                              ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
In file included from ../src/pjmedia/converter_libswscale.c:26:
/opt/local/include/libswscale/swscale.h:134:32: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
int sws_isSupportedOutput(enum AVPixelFormat pix_fmt);
                               ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
In file included from ../src/pjmedia/converter_libswscale.c:26:
/opt/local/include/libswscale/swscale.h:141:46: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
int sws_isSupportedEndiannessConversion(enum AVPixelFormat pix_fmt);
                                             ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
In file included from ../src/pjmedia/converter_libswscale.c:26:
/opt/local/include/libswscale/swscale.h:186:60: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
struct SwsContext *sws_getContext(int srcW, int srcH, enum AVPixelFormat srcFormat,
                                                           ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
In file included from ../src/pjmedia/converter_libswscale.c:26:
/opt/local/include/libswscale/swscale.h:295:66: warning: declaration of 'enum PixelFormat' will not be visible outside of this function [-Wvisibility]
                                        int srcW, int srcH, enum AVPixelFormat srcFormat,
                                                                 ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
../src/pjmedia/converter_libswscale.c:81:24: error: variable has incomplete type 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
                       ^
../src/pjmedia/converter_libswscale.c:81:10: note: forward declaration of 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
         ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
../src/pjmedia/converter_libswscale.c:81:35: error: variable has incomplete type 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
                                  ^
../src/pjmedia/converter_libswscale.c:81:10: note: forward declaration of 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
         ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
7 warnings and 2 errors generated.
make[2]: *** [output/pjmedia-arm64-apple-darwin_ios/converter_libswscale.o] Error 1
make[1]: *** [libpjmedia-arm64-apple-darwin_ios.a] Error 2
make: *** [all] Error 1
```

**Comment by sauwming** [comment]
We only support specific ffmpeg versions. Try using version 4.2 as the one used in our CI:
https://github.com/pjsip/pjproject/actions
(click any workflow, and check the ffmpeg CI job).

**Comment by YuZebra** [comment]
I use version 4.2 and is failed as same

I download form this
https://www.videohelp.com/software/ffmpeg/old-versions

And use this to check
./configure-iphone --with-ffmpeg=/Users/jerrylin/Downloads/ffmpeg-4.2-macos64-static

It is show this

Using ffmpeg prefix... /Users/jerrylin/Downloads/ffmpeg-4.2-macos64-static
checking for pkg-config... pkg-config
checking ffmpeg packages...  libavdevice libavformat libavcodec libswscale libavutil

Then I get the same issue

**Comment by YuZebra** [comment]
> We only support specific ffmpeg versions. Try using version 4.2 as the one used in our CI: https://github.com/pjsip/pjproject/actions (click any workflow, and check the ffmpeg CI job).

I use version 4.2 and is failed as same

I download form this
https://www.videohelp.com/software/ffmpeg/old-versions

And use this to check
./configure-iphone --with-ffmpeg=/Users/jerrylin/Downloads/ffmpeg-4.2-macos64-static

It is show this

Using ffmpeg prefix... /Users/jerrylin/Downloads/ffmpeg-4.2-macos64-static
checking for pkg-config... pkg-config
checking ffmpeg packages... libavdevice libavformat libavcodec libswscale libavutil

Then I get the same issue

**Comment by YuZebra** [comment]
> We only support specific ffmpeg versions. Try using version 4.2 as the one used in our CI: https://github.com/pjsip/pjproject/actions (click any workflow, and check the ffmpeg CI job).

I change my ffmpeg version to 4.2, I use ffmpeg -version check it.
Then I do it again, I still failed and have same issue when I use command 'make'

../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
../src/pjmedia/converter_libswscale.c:81:24: error: variable has incomplete type 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
                       ^
../src/pjmedia/converter_libswscale.c:81:10: note: forward declaration of 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
         ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
../src/pjmedia/converter_libswscale.c:81:35: error: variable has incomplete type 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
                                  ^
../src/pjmedia/converter_libswscale.c:81:10: note: forward declaration of 'enum PixelFormat'
    enum AVPixelFormat srcFormat, dstFormat;
         ^
../src/pjmedia/ffmpeg_util.h:42:26: note: expanded from macro 'AVPixelFormat'
#   define AVPixelFormat        PixelFormat
                                ^
7 warnings and 2 errors generated.
make[2]: *** [output/pjmedia-arm64-apple-darwin_ios/converter_libswscale.o] Error 1
make[1]: *** [libpjmedia-arm64-apple-darwin_ios.a] Error 2
make: *** [all] Error 1
