### ISSUE TITLE
pj_ice_sess_add_cand assertion

### ISSUE THREAD

**Issue by liviu-rolo** [pjsip/pjproject#2982]
### Describe the bug

pjsua-x86_64-unknown-linux-gnu: ../src/pjnath/ice_session.c:762: pj_ice_sess_add_cand: Assertion `comp_id <= ice->comp_cnt' failed.

### Steps to reproduce

I didn't reproduce it.

### PJSIP version

2.11-dev

### Context

Ubuntu 20.04

config_site.h
```
#define PJMEDIA_SRTP_HAS_DTLS 1
#define PJMEDIA_SRTP_HAS_SDES 1
#define PJSIP_MAX_PKT_LEN 12288
```

`--use-ice`
`--stun-srv stun.l.google.com:19302`
sometimes `--turn-srv` and `--turn-tcp.`

### Log, call stack, etc

```shell
17:50:25.413   stuntp0x7f1f1001f820  .STUN mapped address found/changed: 212.67.40.97:49250
17:50:25.413                icetp00  .Candidate 6 added: comp_id=1, type=srflx, foundation=Sac1e64de, addr=212.67.40.97:49250, base=172.30.100.222:4021, prio=0x6effffff (1862270975)
17:50:25.413                icetp00  .Comp 1: srflx address changed, srflx address is 212.67.40.97:49250
17:50:25.413   stuntp0x7f1f1004b620  .STUN mapped address found/changed: 212.67.40.97:19612
pjsua-x86_64-unknown-linux-gnu: ../src/pjnath/ice_session.c:762: pj_ice_sess_add_cand: Assertion `comp_id <= ice->comp_cnt' failed.
Error: signal 6:
./pjsua-x86_64-unknown-linux-gnu(+0x13d86)[0x561640905d86]
```

**Comment by sauwming** [comment]
I can't reproduce it here. I believe though that the latest ICE changes should fix this. Please reopen if the issue persists with the latest version.
