### ISSUE TITLE
Latest commit 4a5b55b6 fails to build on Debian 11 with "failed to convert GOTPCREL relocation"

### ISSUE THREAD

**Issue by MayamaTakeshi** [pjsip/pjproject#2997]
### Describe the bug

make output:
... ABRIDGED ...
/usr/local/src/git/pjproject/pjlib/build/../src/pj/ssl_sock_ossl.c:746:(.text+0x1fd5): relocation truncated to fit: R_X86_64_PC32 against `.bss'
/usr/local/src/git/pjproject/pjlib/build/../src/pj/ssl_sock_ossl.c:843:(.text+0x200b): relocation truncated to fit: R_X86_64_PC32 against `.bss'
/usr/local/src/git/pjproject/pjlib/build/../src/pj/ssl_sock_ossl.c:764:(.text+0x203f): relocation truncated to fit: R_X86_64_PC32 against `.bss'
/usr/local/src/git/pjproject/pjlib/build/../src/pj/ssl_sock_ossl.c:770:(.text+0x2059): additional relocation overflows omitted from the output
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
make[2]: *** [/usr/local/src/git/pjproject/build/rules.mak:125: ../bin/pjsua2-test-x86_64-unknown-linux-gnu] Error 1
make[2]: Leaving directory '/usr/local/src/git/pjproject/pjsip/build'
make[1]: *** [Makefile:286: pjsua2-test-x86_64-unknown-linux-gnu] Error 2
make[1]: Leaving directory '/usr/local/src/git/pjproject/pjsip/build'
make: *** [Makefile:14: all] Error 1

The problem doesn't happen with previous release 2.11.

### Steps to reproduce

Just try to build on Debian 11.

### PJSIP version

2.12

### Context

NA

### Log, call stack, etc

```shell
NA
```

**Comment by sauwming** [comment]
Please try with the latest version, and reopen if the issue persists.
