### ISSUE TITLE
PJSUA2: Structs as aggreates

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#2999]
If you want to use user-defined headers you need following code:
```cpp
SipHeader h;
h.hName = "X-Header";
h.hValue = "User header";
SipHeaderVector headers;
headers.push_back(h);
```

In modern C++ [following](https://en.cppreference.com/w/cpp/language/aggregate_initialization) would be possible, if `SipHeader` was an aggregate:
```cpp
SipHeaderVector headers{{"X-Header", "User header"}};
// e.g.
SipHeaderVector headers{{"X-Header", "User header"}, {"X-Header", "User header2"}, {"X-Header", "User header3"}};
```
and since C++20 even:
```cpp
SipHeaderVector headers{{.hName="X-Header", .hValue="User header"}};
```

More general: In PJSUA2 structs are most often non-aggregates, e.g. methods `toPj()` and `fromPj()` are private. Sometimes there are others. In my opinion, moving them out (from methods to function) would make much cleaner/nicer code possible in the applications.

PS (*update*): Currently, an application can use the following to at least bypass one step:
```cpp
45  struct header : public pj::SipHeader
  1 {
  2    header(std::string&& name, std::string&& value)
  3    {
  4       SipHeader::hName = std::move(name);
  5       hValue = std::move(value);
  6    };
  7 };
```
but it is a bad hack, since the solution shouldn't be to add new constructors.

**Comment by sauwming** [comment]
In some structs, fromPj() and toPJ() are actually public, so I believe they should be okay here. Besides, private member functions should be okay too, shouldn't it?

But the main obstacle IMO is the virtual member functions, especially for structs that inherit virtual base class `PersistentObject`. This can present major backward compatibility.
