### ISSUE TITLE
Detect OpenSSL using pkg-config

### ISSUE THREAD

**Issue by reddwarf69** [pjsip/pjproject#3013]
OpenSSL has provided a pkg-config file since forever, but pjproject's autoconf doesn't use it (as it does with gnutls).
I'm being left having to use --with-ssl=<path>, which is not a reliable alternative since it supposes the libraries are in `<path>/lib` when they may well be in `<path>/lib64`.

libpjproject.pc.in should probably use `Requires.private: openssl` in such a case.

**Comment by sauwming** [comment]
Currently we don't have any plan for this. Please feel free to provide a patch.
