### ISSUE TITLE
Pjsua: send dtmf  with SIP INFO

### ISSUE THREAD

**Issue by DomAsw15** [pjsip/pjproject#3014]
### Describe the bug

In SIP INFO application/dtmf-relay  after Duration=value a \r and a \n character are missing, seen in Wireshark.
I'm not sure, but that's what I've seen in all the literature on SIP INFO.

the file is : pjproject/pjsip/src/pjsua-lib/pjsua_call.c
	    pj_ansi_snprintf(body, sizeof(body),
			     "Signal=%c\r\n"
			     "Duration=%d",

`* Send DTMF digits to remote.
 */
PJ_DEF(pj_status_t) pjsua_call_send_dtmf(pjsua_call_id call_id,
 				       const pjsua_call_send_dtmf_param *param)
{
    pj_status_t status = PJ_EINVAL;    

    PJ_ASSERT_RETURN(call_id>=0 && call_id<(int)pjsua_var.ua_cfg.max_calls &&
		     param, PJ_EINVAL);

    PJ_LOG(4,(THIS_FILE, "Call %d sending DTMF %.*s using %s method",
    		       call_id, (int)param->digits.slen, param->digits.ptr,
		       get_dtmf_method_name(param->method)));

    if (param->method == PJSUA_DTMF_METHOD_RFC2833) {
	status = pjsua_call_dial_dtmf(call_id, &param->digits);
    } else if (param->method == PJSUA_DTMF_METHOD_SIP_INFO) {
	const pj_str_t SIP_INFO = pj_str("INFO");
	int i;

	for (i = 0; i < param->digits.slen; ++i) {
	    char body[80];
	    pjsua_msg_data msg_data_;

	    pjsua_msg_data_init(&msg_data_);
	    msg_data_.content_type = pj_str("application/dtmf-relay");

	    pj_ansi_snprintf(body, sizeof(body),
			     "Signal=%c\r\n"
			     "Duration=%d",
			     param->digits.ptr[i], param->duration);
	    msg_data_.msg_body = pj_str(body);

	    status = pjsua_call_send_request(call_id, &SIP_INFO, &msg_data_);
	}
    }`

### Steps to reproduce

1 run pjsua 
2 call  à softphone
3 send dtmf with * for SIP INFO

### PJSIP version

2.12

### Context

Os: Linux
Softphone : Linphone

### Log, call stack, etc

```shell
no log
```

**Comment by sauwming** [comment]
According to https://datatracker.ietf.org/doc/html/draft-kaplan-dispatch-info-dtmf-package-00#section-5.2

```
   Dtmf-relay-body = digit-line CRLF duration-line

   digit-line      = "Signal" EQUAL SP button
   button          = DIGIT / "A" / "B" / "C" / "D" / "*" / "#"

   duration-line   = "Duration" EQUAL SP msecs
   msecs           = 1*4(DIGIT)  ;100-5000 millisecs
```
Unfortunately, I can't find a newer or updated RFC for this.
