### ISSUE TITLE
CFLAGS and CXXFLAGS get mixed

### ISSUE THREAD

**Issue by reddwarf69** [pjsip/pjproject#3015]
### Describe the bug

https://github.com/pjsip/pjproject/blob/d27f79da11df7bc8bb56c2f291d71e54df8d2c47/build.mak.in#L238 puts APP_CFLAGS, which contains @CFLAGS@, into APP_CXXFLAGS.
If the CFLAGS happen to include something like `-std=gnu99`, you would get a C-specific flag when building a C++ file. g++ happens to ignore `-std=gnu99`, but clang refuses to take it and simply returns error.

### Steps to reproduce

`CXX=clang++ CFLAGS=-std=gnu99 ` should be everything you need.

### PJSIP version

2.12

### Context

Just building

### Log, call stack, etc

```shell
Just building
```

**Comment by sauwming** [comment]
You're right, unfortunately there doesn't seem to be an easy way to fix this because we can't seem to separate which CFLAGS can or cannot be included in the CXXFLAGS.

If you know a solution, please let us know.
