### ISSUE TITLE
[BUG]The fmtp processing function is defective. It is recommended to modify it

### ISSUE THREAD

**Issue by zbyslb** [pjsip/pjproject#3025]
### Describe the bug

In file stream_ common.c, the implementation of the function "pjmedia_stream_info_parse_fmtp" is defective. It cannot handle the case that the value of fmtp contains' = 'characters, such as: "a = fmtp: 100 profile-level-id = 42c01e; sprop-parameter-sets = z0lahtqhgusagwccg8ibcoa =, am48ga = =; packaging mode = 1; max br = 974".
The original implementation is:
PJ_DEF(pj_status_t) pjmedia_stream_info_parse_fmtp( pj_pool_t *pool,
						    const pjmedia_sdp_media *m,
						    unsigned pt,
						    pjmedia_codec_fmtp *fmtp)
{
    const pjmedia_sdp_attr *attr;
    pjmedia_sdp_fmtp sdp_fmtp;
    char *p, *p_end, fmt_buf[8];
    pj_str_t fmt;
    pj_status_t status;

    pj_assert(m && fmtp);

    pj_bzero(fmtp, sizeof(pjmedia_codec_fmtp));

    /* Get "fmtp" attribute for the format */
    pj_ansi_sprintf(fmt_buf, "%d", pt);
    fmt = pj_str(fmt_buf);
    attr = pjmedia_sdp_media_find_attr2(m, "fmtp", &fmt);
    if (attr == NULL)
	return PJ_SUCCESS;

    /* Parse "fmtp" attribute */
    status = pjmedia_sdp_attr_get_fmtp(attr, &sdp_fmtp);
    if (status != PJ_SUCCESS)
	return status;

    /* Prepare parsing */
    p = sdp_fmtp.fmt_param.ptr;
    p_end = p + sdp_fmtp.fmt_param.slen;

    /* Parse */
    while (p < p_end) {
	char *token, *start, *end;

	if (fmtp->cnt >= PJMEDIA_CODEC_MAX_FMTP_CNT) {
	    PJ_LOG(4,(THIS_FILE,
		      "Warning: fmtp parameter count exceeds "
		      "PJMEDIA_CODEC_MAX_FMTP_CNT"));
	    return PJ_SUCCESS;
	}

	/* Skip whitespaces */
	while (p < p_end && (*p == ' ' || *p == '\t')) ++p;
	if (p == p_end)
	    break;

	/* Get token */
	start = p;
	while (p < p_end && *p != ';' && *p != '=') ++p;
	end = p - 1;

	/* Right trim */
	while (end >= start && (*end == ' '  || *end == '\t' || 
				*end == '\r' || *end == '\n' ))
	    --end;

	/* Forward a char after trimming */
	++end;

	/* Store token */
	if (end > start) {
	    if (pool) {
		token = (char*)pj_pool_alloc(pool, end - start);
		pj_ansi_strncpy(token, start, end - start);
	    } else {
		token = start;
	    }
	    if (*p == '=')
		/* Got param name */
		pj_strset(&fmtp->param[fmtp->cnt].name, token, end - start);
	    else
		/* Got param value */
		pj_strset(&fmtp->param[fmtp->cnt++].val, token, end - start);
	} else if (*p != '=') {
	    ++fmtp->cnt;
	}

	/* Next */
	++p;
    }

    return PJ_SUCCESS;
}

ust be modified (not optional at all) to:
PJ_DEF(pj_status_t) pjmedia_stream_info_parse_fmtp( pj_pool_t *pool,
						    const pjmedia_sdp_media *m,
						    unsigned pt,
						    pjmedia_codec_fmtp *fmtp)
{
    const pjmedia_sdp_attr *attr;
    pjmedia_sdp_fmtp sdp_fmtp;
    char *p, *p_end, fmt_buf[8];
    pj_str_t fmt;
    pj_status_t status;

    pj_assert(m && fmtp);

    pj_bzero(fmtp, sizeof(pjmedia_codec_fmtp));

    /* Get "fmtp" attribute for the format */
    pj_ansi_sprintf(fmt_buf, "%d", pt);
    fmt = pj_str(fmt_buf);
    attr = pjmedia_sdp_media_find_attr2(m, "fmtp", &fmt);
    if (attr == NULL)
	return PJ_SUCCESS;

    /* Parse "fmtp" attribute */
    status = pjmedia_sdp_attr_get_fmtp(attr, &sdp_fmtp);
    if (status != PJ_SUCCESS)
	return status;

    /* Prepare parsing */
    p = sdp_fmtp.fmt_param.ptr;
    p_end = p + sdp_fmtp.fmt_param.slen;

    /* Parse */
    while (p < p_end) {
	char *token, *start, *end;

	if (fmtp->cnt >= PJMEDIA_CODEC_MAX_FMTP_CNT) {
	    PJ_LOG(4,(THIS_FILE,
		      "Warning: fmtp parameter count exceeds "
		      "PJMEDIA_CODEC_MAX_FMTP_CNT"));
	    return PJ_SUCCESS;
	}

	/* Skip whitespaces */
	while (p < p_end && (*p == ' ' || *p == '\t')) ++p;
	if (p == p_end)
	    break;

	/* Get token */
	start = p;
	while (p < p_end && *p != '=') ++p;
	end = p - 1;

	/* Right trim */
	while (end >= start && (*end == ' '  || *end == '\t' || 
				*end == '\r' || *end == '\n' ))
	    --end;

	/* Forward a char after trimming */
	++end;

	/* Store token */
	if (end > start) {
	    if (pool) {
		token = (char*)pj_pool_alloc(pool, end - start);
		pj_ansi_strncpy(token, start, end - start);
	    } else {
		token = start;
	    }
		pj_strset(&fmtp->param[fmtp->cnt].name, token, end - start);
	}

	++p;
	/* Get value */
	start = p;
	while (p < p_end && *p != ';') ++p;
	end = p - 1;

	/* Right trim */
	while (end >= start && (*end == ' ' || *end == '\t' ||
		*end == '\r' || *end == '\n'))
		--end;

	/* Forward a char after trimming */
	++end;

	/* Store value */
	if (end > start) {
		if (pool) {
			token = (char*)pj_pool_alloc(pool, end - start);
			pj_ansi_strncpy(token, start, end - start);
		}
		else {
			token = start;
		}
		pj_strset(&fmtp->param[fmtp->cnt++].val, token, end - start);
	} else {
		++fmtp->cnt;
	}

	/* Next */
	++p;
    }

    return PJ_SUCCESS;
}

### Steps to reproduce

process sdp with fmtp

### PJSIP version

2.12

### Context

process sdp with fmtp

### Log, call stack, etc

```shell
a=fmtp:100 profile-level-id=42C01E;sprop-parameter-sets=Z0LAHtqHgUSagwCCg8IBCoA=,aM48gA==;packetization-mode=1;max-br=974
like this
```

**Comment by silentindark** [comment]
@zbyslb Would you be able to create a pull request for this, then pjproject team can review it.
