### ISSUE TITLE
Support for emergency calls

### ISSUE THREAD

**Issue by martin-flaska** [pjsip/pjproject#3036]
I want to make an emergency call using pjsip library. What I know, it should probably set some header in INVITE request or so .

I briefly checked [RFC 5031](https://datatracker.ietf.org/doc/html/rfc5031) what seems to be related to this.

So I miss some function to make a such call or at least some option for [Call::makeCall](https://www.pjsip.org/docs/book-latest/html/call.html#_CPPv4N2pj4Call8makeCallERK6stringRK11CallOpParam) method.
Is this somehow already possible in the pjsua2/pjsip or is this functianality missing?

**Comment by wosrediinanatour** [comment]
Using call::makeCall(...) adding headers should work.

**Comment by martin-flaska** [comment]
@wosrediinanatour Thanks for suggestion, this works for me:

```
pj::SipHeader hdr;
hdr.hName = "Priority";
hdr.hValue = "emergency";
call_param.txOption.headers.push_back(hdr);
```
