### ISSUE TITLE
PJSUA2: exceptions

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#3039]
### Describe the bug

When re-throwing the PJSUA2's error exception, clang-tidy prints two errors. They can be ignored by
```cpp
// NOLINTNEXTLINE(hicpp-exception-baseclass,-warnings-as-errors): intentionally
         throw exception; // NOLINT(cert-err60-cpp,-warnings-as-errors):  intentionally
```
Reference:
* https://clang.llvm.org/extra/clang-tidy/checks/hicpp-exception-baseclass.html
* https://clang.llvm.org/extra/clang-tidy/checks/cert-err60-cpp.html

It would be good, if the std::exception was the pj::Error's base class.

### Steps to reproduce

see "Describe the bug"

### PJSIP version

2.12

### Context

Linux
Clang-Tidy 12

### Log, call stack, etc

```shell
--
```

**Comment by sauwming** [comment]
So, I assume this information is provided for PJSIP users, correct?

Because when I tried running `clang-tidy` here, it only gives initialisation warnings, no errors. And the warning can be suppressed by specifying options, such as:
```
clang-tidy ../src/pjsua2/call.cpp -checks=-clang-analyzer-optin.cplusplus.UninitializedObject -- -I/opt/local/include -I../include -I../../pjlib/include -I../../pjlib-util/include -I../../pjnath/include -I../../pjmedia/include  -I/opt/local/include -I../include -I../../pjlib/include -I../../pjlib-util/include -I../../pjnath/include -I../../pjmedia/include -I/opt/local/include/SDL2 -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1   -g -O0 -Wno-unused-label -Wno-deprecated-declarations -g -O0 -Wno-unused-label -Wno-deprecated-declarations
```

I will close this since no library modification seems to be needed. Let me know if I'm wrong.
