### ISSUE TITLE
PJSUA2's documentation

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#3040]
### Describe the bug

Documentation https://www.pjsip.org/docs/book-latest/html/intro_pjsua2.html had been generate in 2014. I think that an update would be easy, simple, and useful.

### Steps to reproduce

--

### PJSIP version

2.12

### Context

--

### Log, call stack, etc

```shell
--
```

**Comment by sauwming** [comment]
pjsua2 book is actually generated for every release, so if there is outdated info, it's because the documentation source is not updated yet. If that's the case, let us know which part(s) needs revision and will try to do it.

**Comment by wosrediinanatour** [comment]
@sauwming : 

At the bottom the copyrigh says 2014 and the version is shown as [PJSUA2 Documentation 1.0-alpha documentation](https://www.pjsip.org/docs/book-latest/html/index.html): This is the reason I come up with the issue.

I now checked whether the new endpoint callback onCredAuth in https://www.pjsip.org/docs/book-latest/html/endpoint.html#class-reference is present: it issn't.

**Comment by sauwming** [comment]
Thanks for pointing it out, our documentation generator script turns out to be broken indeed.
We are currently migrating to readthedocs, so the new location would be at: https://docs.pjsip.org . It has contained more updated documentation, but still currently a work in progress, so please be patient :)

**Comment by sauwming** [comment]
The migration is nearly complete, although still not 100% yet. So please check our new doc https://docs.pjsip.org. Thanks.
