### ISSUE TITLE
--auto-play-hangup hangsup before call was connected

### ISSUE THREAD

**Issue by BenasPaulikas** [pjsip/pjproject#3041]
### Describe the bug

I'm implementing simple solution to call number, play audio, hangup (It's not yet another scam call :)

Command bellow works fine but I don't need to loop audio file to user. I need to play it once and hangup.

Therefore I add  --auto-play-hangup however it starts playing audio file before user picks up phone.

### Steps to reproduce

1. ./pjsua --id sip:***@*** --registrar sip:*** --username *** --password *** --realm \* --play-file haustuer.wav sip:***@*** --auto-play

### PJSIP version

2.12

### Context

Linux

### Log, call stack, etc

```shell
14:17:39.654            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
14:17:39.654           inv0x1dc1fd8  ....SDP negotiation done: Success
14:17:39.655          pjsua_media.c  .....Call 0: updating media..
14:17:39.655          pjsua_media.c  .......Media stream call00:0 is destroyed
14:17:39.655           udp0x1d2c430  ......UDP media transport started
14:17:39.655            pjsua_aud.c  ......Audio channel update..
14:17:39.655     strm0x7f93fc00a518  .......VAD temporarily disabled
14:17:39.655           udp0x1d2c430  .......UDP media transport attached
14:17:39.655     strm0x7f93fc00a518  .......Encoder stream started
14:17:39.655     strm0x7f93fc00a518  .......Decoder stream started
14:17:39.655          pjsua_media.c  ......Audio updated, stream #0: PCMA (sendrecv)
14:17:39.655            pjsua_app.c  .....Call 0 media 0 [type=audio], status is Active
14:17:39.655            pjsua_aud.c  .....Conf connect: 1 --> 4
14:17:39.655           conference.c  ......Port 1 (haustuer.wav) transmitting to port 4 (sip:***@***)
14:17:40.285     strm0x7f93fc00a518  VAD re-enabled
14:17:44.305           sound_port.c  EC suspended because of inactivity
14:17:46.066           pjsua_call.c !Hangup all calls..
14:17:46.066           pjsua_call.c  .Call 0 hanging up: code=0..
14:17:46.066          pjsua_media.c  ..Call 0: deinitializing media..
14:17:46.066          pjsua_media.c  ...
```

**Comment by BenasPaulikas** [comment]
@trengginas thank you. Any way to execute that .wav playing after user picks up (13:31:08.646            pjsua_app.c  .....Call 0 state changed to CONFIRMED) ?

**Comment by mc510** [comment]
@BenasPaulikas I am trying to do _exactly_ the same thing as you; did you find a way to do it?

**Comment by sauwming** [comment]
It already correctly behaves as specified: "Automatically hangup the call after file play completes".
