### ISSUE TITLE
Build for Android

### ISSUE THREAD

**Issue by dvjdjvu** [pjsip/pjproject#3042]
### Describe the bug

I try to build for android (https://trac.pjsip.org/repos/wiki/Getting-Started/Android)
And then use python (kivy) + pjsip for building apk pakage. When I am starting my app in a phone when loading pjsip libs, I get error.

How can I build pjsip for android?

### Steps to reproduce

export ANDROID_NDK_ROOT=/home/djvu/Downloads/android-ndk-r23b
TARGET_ABI=armeabi-v7a LDFLAGS="-Wl,-hash-style=sysv" ./configure-android --use-ndk-cflags --enable-shared --disable-gsm-codec --disable-ilbc-codec --disable-g722-codec --disable-g7221-codec --disable-resample --disable-libyuv --disable-libwebrtc

### PJSIP version

2.11.1

### Context

Android 5.0
python (kivy)
Ubuntu 5.13.0-35-generic

### Log, call stack, etc

```shell
I/python  (14354): Traceback (most recent call last):
I/python  (14354):   File "/home/djvu/workspace/qq/.buildozer/android/app/main.py", line 8, in <module>
I/python  (14354):   File "/home/djvu/workspace/qq/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/ctypes/__init__.py", line 451, in LoadLibrary
I/python  (14354):   File "/home/djvu/workspace/qq/.buildozer/android/platform/build-armeabi-v7a/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/ctypes/__init__.py", line 373, in __init__
I/python  (14354): OSError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libpj.so"...
I/python  (14354): Python for android ended.
```

**Comment by sauwming** [comment]
Most likely you build for an unsuitable API level.
Google around for the solution.

**Comment by dvjdjvu** [comment]
I have forgotten tI have decided this problem. I don't remember what happened. Thx.hat problem have. But I decided it.
