### ISSUE TITLE
A memory access error was received at the end of the recording

### ISSUE THREAD

**Issue by ArsTrety** [pjsip/pjproject#3043]
### Describe the bug

Hi, I'm developing a softphone.
The problem arose with recording conversations in mp3 format. After upgrading from version 2.9 to version 2.12, we get a memory access error. When the call ends, the application crashes. Using dumps, it was possible to establish that a memory access error occurs when calling methods pjsua_conf_disconnect->pjmedia_conf_disconnect_port->pj_array_erase. 

Also, if config_site_samples.h is disabled, the recording completes correctly. 
I also attach the code of our end and start recording methods. 
`void PJSipRecorderManager::startRecording(const QString &filename)
{
    ActionProvider::instance().changeRecordingAudioFileStatus(AppConfigUtils::RecordAudioFileStatus::Status::StartRecording);

    if (recorderId == PJSUA_INVALID_ID) {

        pj_str_t pjsuaRecordName = QStringLocal8BitToPJStr(filename);
        pj_status_t status = pjsua_recorder_create(&pjsuaRecordName, 0, NULL, 0, 0, &(recorderId));

        if (status != PJ_SUCCESS) {
            AppLogger::Error(QString("%1: can't create recorder. Status code - %2")
                             .arg(this->name(), QString::number(status)));
            ActionProvider::instance().changeRecordingAudioFileStatus(AppConfigUtils::RecordAudioFileStatus::Status::RecordingError);
            return;
        }

        AppLogger::Debug(QString("%1: got recorder id %2")
                         .arg(this->name(), QString::number(recorderId)));
    }

    AppLogger::Info(QString("%1: start recording").arg(this->name()));
    ActionProvider::instance().changeRecordingAudioFileStatus(AppConfigUtils::RecordAudioFileStatus::Status::RecordingEnabled);

    pjsua_conf_port_id recorderPort = pjsua_recorder_get_conf_port(recorderId);
    pjsua_conf_connect(0, recorderPort);
    return;
}

void PJSipRecorderManager::stopRecording()
{
    AppLogger::Info(QString("%1: stop recording").arg(this->name()));

    pjsua_conf_port_id recorderPort = pjsua_recorder_get_conf_port(recorderId);
    pjsua_conf_disconnect(0, recorderPort);

    pj_status_t status = pjsua_recorder_destroy(recorderId);

    if (status != PJ_SUCCESS) {
        AppLogger::Warning(QString("%1: Can't destroy recorder. Status code - %2").
                           arg(this->name(), QString::number(status)));
    }
    ActionProvider::instance().changeRecordingAudioFileStatus(AppConfigUtils::RecordAudioFileStatus::Status::RecordingIsStopped);
    recorderId = PJSUA_INVALID_ID;
    return;
}`
Can you tell me what the problem might be? Thank you in advance, Ars
![image](https://user-images.githubusercontent.com/102797377/161246523-39e33ff3-333b-470f-b9fc-b370cfacd70d.png)

### Steps to reproduce

1. Build pjsip with our config_site.h
2. Build application on qt 5.9.2 with compiler ms vc 2015
3. create a call and call recording
4. end the call and record the call

### PJSIP version

2.12

### Context

-the issue happens on Windows  10 desktop
-App is built by qt 5.9.2 with the msvc 2015 compiler
-The error appeared after updating to 2.12
-config_site.h
`#define PJ_CONFIG_MAXIMUM_SPEED 1
#define PJ_HAS_SSL_SOCK 1

#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS		     101
#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS_STR		"101"

#define PJMEDIA_HAS_G729_CODEC 1

// if you want to increase max sip acc count
// change PJSUA_MAX_ACC 
// Also do not forget to update PJSUA_MAX_ACC
// if they differ because app will crash
#define PJSUA_MAX_ACC 32
#define PJSUA_ACC_MAX_PROXIES 8

#include "config_site_sample.h"

#ifdef __APPLE__

#ifdef PJ_IOQUEUE_MAX_HANDLES
#undef PJ_IOQUEUE_MAX_HANDLES
#endif

#define PJ_IOQUEUE_MAX_HANDLES    256

#endif`

### Log, call stack, etc

```shell
Only the line [2022-04-01 15:40:17.675 +05:00] [info] PJSipCall(id 1, account 0): stop recording
```

**Comment by sauwming** [comment]
- Try reproducing it with our sample app.
- You mention that if `config_site_sample.h` is disabled, everything works fine. You need to find out which exact setting that causes the issue.
