### ISSUE TITLE
Outgoing call does ring on the receiver side but no voice ?

### ISSUE THREAD

**Issue by martsa** [pjsip/pjproject#3064]
### Describe the bug

I am implementing voice call using pjsip pjsua2 android sample app. It does work very well without any issue on Android version 8,9,10. but on Android version 5.1 Lollipop, I do receive call without issue, On making outgoing call from Android phone ,it does ring on receiver site , but on picking call ,I cannot hear any thing on both site. Any help would be highly appreciated 

### Steps to reproduce

using Pjsua2 android 

### PJSIP version

2.11

### Context

when I make outgoing call from Android Tablet  to any sip number, it does ring but no voice heard on both site. iT does receive call from soft sip phone without any issue. 

### Log, call stack, etc

```shell
-12 16:17:42.320 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.320   pjsua_call.c !Making call with acc #0 to sip:+xyz22@xyzcom
04-12 16:17:42.321 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.320    pjsua_aud.c  .Set sound device: capture=-1, playback=-2
04-12 16:17:42.321 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.321    pjsua_aud.c  ..Opening sound device (speaker + mic) PCM@16000/1/20ms
04-12 16:17:42.321 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.321   opensl_dev.c  ...Creating OpenSL stream
04-12 16:17:42.322 4922-4922/org.pjsip.pjsua2 W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
04-12 16:17:42.322 4922-4922/org.pjsip.pjsua2 I/AudioTrack: minFrameCount: 1857, afFrameCount=1024, minBufCount=5, sampleRate=16000, afSampleRate=44100, afLatency=115
04-12 16:17:42.323 4922-4922/org.pjsip.pjsua2 W/AudioRecord: AUDIO_INPUT_FLAG_FAST denied by client
04-12 16:17:42.336 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.335   ec0xb8b41d98  ...Speex AEC created, clock_rate=16000, channel=1, samples per frame=320, tail length=200 ms, latency=0 ms
04-12 16:17:42.336 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.336   opensl_dev.c  ...Starting OpenSL stream..
04-12 16:17:42.347 4922-4922/org.pjsip.pjsua2 I/System.out: 16:17:42.347   opensl_dev.c  ...OpenSL stream started
```

**Comment by Truong-Thanh-Quang** [comment]
You should capture SIP message at both ends to detect protocol error. Wireshark for example.

**Comment by SebaLedesma** [comment]
Remember that solving the other party IP it's done by the Registrar server, but the audio goes directly between parties. So in some cases the router can block the audio, for example if you are using a cellphone connected to wifi, and the other user it's a PC connected to the LAN, the router could be configured to block the traffic between WIFI and LAN. 
Also note that some other routers can have the SIP ALG option, and this can be problematic in some cases, see: https://enreach.es/blog/sip-alg-fallos-desactivarlo/

**Comment by sauwming** [comment]
https://trac.pjsip.org/repos/wiki/sound-problems
