### ISSUE TITLE
ioqueue_create performance

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3077]
### Describe the bug

```c
pj_ioqueue_create( pj_pool_t *pool, pj_size_t max_fd, pj_ioqueue_t **p_ioqueue)
```
When use epoll/kqueue, max_fd may be a large number , eg. 30000

In this case,  pj_ioqueue_create() will take a long time (several seconds, 5 seconds or more) !

The reason is that:  it'll alloc max_fd times memory, which is so slow. 

It can be optimized to apply for contiguous memory only once.

### Steps to reproduce

1.  build pjproject with ioqueue use epoll/kqueue (--enable-epoll / --enable-kqueue)
2. write a simple test, set max_fd to a large number

The main code as follow:
```c
pj_pool_t *pool = pj_pool_create(pf, "tst", 1000, 1000, NULL);
pj_ioqueue_t *ioq;

// set max_fd to  a large number,  here is 30000,  will be slow
pj_ioqueue_create(pool, 30000,  &ioq);
```
3. run test, which  take a long time

### PJSIP version

2.12-dev

### Context

In platform: linux / macos / freebsd

### Log, call stack, etc

```shell
None
```

**Comment by jimying** [comment]
I give a pull request #3078 

I had tested it on linux-x86_64/ macos-x86_64/freebsd-amd64

**Comment by sauwming** [comment]
Actually `pj_pool` is designed to achieve a better performance than regular memory allocation, it's just here it's configured suboptimally.
`pj_pool_create(..., 1000, 1000, ...)` means that the initial size is 1 KB and the increment is also 1 KB, which is definitely insufficient if app already knows that it wants to handle 30K max_fd (not only the initial size is not enough, the pool has to be reallocated so many times which is a very expensive operation).

So perhaps you can try larger numbers, a minimum of `30K * (sizeof(pj_ioqueue_t) + sizeof(pj_mutex_t)) + some allowances` for the initial size and a reasonable increment size.

As for the fix in the PR, if the above works, then a solution is for ioqueue to create its own internal pool, i.e.
```
// Make sure that pool_size can hold max_fd memory requirement
pool_size = ...
ioq->pool = pj_pool_create(pool.factory, , ...)
```
And later in ioq destroy: `pj_pool_release(ioq->pool)`.

Alternatively, leave it to the app to configure the pool with more optimal setting.

**Comment by jimying** [comment]
@sauwming 
Configure the app pool initial size to an estimated value to:

> 30K * (sizeof(pj_ioqueue_t) + sizeof(pj_mutex_t)) + some allowances 

( in app side， not know sizeof(pj_ioqueue_t) and sizeof(pj_mutex_t) )


It works fine, run quickly.

I will close this issue && pull request
