### ISSUE TITLE
hangup/answer decline  in incomming callback , crash. How to  auto hangup incomming call 

### ISSUE THREAD

**Issue by tjyuanxi** [pjsip/pjproject#3079]
### Describe the bug

There is a calling comming. but I want to auto hangup in incomming call. But it crashed, I tried hangup and answer decline.

00:02:11.295   pjsua_call.c  ...Answering call 1: code=603
00:02:11.295   pjsua_call.c  ....Pending answering call 1 upon completion of media transport
00:02:11.295   pjsua_call.c  ...Call 1 hanging up: code=0..
00:02:11.295   pjsua_call.c  ....Will continue call 1 hangup upon completion of media transport
zkgui: ../src/pjsip-ua/sip_inv.c:2805: pjsip_inv_end_session: Assertion `tdata != ((void *)0)' failed.

### Steps to reproduce

There is a calling comming. but I want to auto hangup in incomming call. But it crashed, I try hangup and answer decline

### PJSIP version

2.12

### Context

00:02:11.295   pjsua_call.c  ...Answering call 1: code=603
00:02:11.295   pjsua_call.c  ....Pending answering call 1 upon completion of media transport
00:02:11.295   pjsua_call.c  ...Call 1 hanging up: code=0..
00:02:11.295   pjsua_call.c  ....Will continue call 1 hangup upon completion of media transport
zkgui: ../src/pjsip-ua/sip_inv.c:2805: pjsip_inv_end_session: Assertion `tdata != ((void *)0)' failed.

### Log, call stack, etc

```shell
00:02:11.295   pjsua_call.c  ...Answering call 1: code=603
00:02:11.295   pjsua_call.c  ....Pending answering call 1 upon completion of media transport
00:02:11.295   pjsua_call.c  ...Call 1 hanging up: code=0..
00:02:11.295   pjsua_call.c  ....Will continue call 1 hangup upon completion of media transport
zkgui: ../src/pjsip-ua/sip_inv.c:2805: pjsip_inv_end_session: Assertion `tdata != ((void *)0)' failed.
```

**Comment by trengginas** [comment]
This should be fix on #3026.
