### ISSUE TITLE
Can I port the pjsip to ESP32?

### ISSUE THREAD

**Issue by CAIJUN111** [pjsip/pjproject#3091]
I dou't know how to port the project to the esp32 for vscode,who can give me some advice?

I want to build a client for sip mobile phone with 4g module .I except it has the STUN function,which can communicate with other spi client.

thanks in advance.

**Comment by jimying** [comment]
pjsip already support cross compile

- cross compile
```
./configure  --host=xtensa-esp32-elf --disable-video
make dep
make -j 4
```
should compile successfully

- have fun with pjsua
check if pjsua demo work (test sip register , make sip call, audio sound device  )
```
# how to run pjsua
cd pjsip-apps/bin
./pjsua-xtensa-esp32-elf
```
