### ISSUE TITLE
pj_ioqueue_register_sock2 Assertion free_list empty failed

### ISSUE THREAD

**Issue by feanoer** [pjsip/pjproject#3098]
### Describe the bug

I want to establish 2 rtp streams connections customizable (in some field as ipaddress,port,codec,ecc) from the the user throught a web interface at runtime. Whenever the user edit some rtp stream, my backend application save the new data, tear down the old streams (closing the rtp e rtpc transport/socket) and then it will create the new streams selected.
It seems to work for a large number of times, until my application crashes and reports this error due to the source ioqueue_select.c

pj_ioqueue_register_sock2: Assertion !pj_list_empty(&ioqueue->free_list)' failed.

### Steps to reproduce

1. create 2 rtp streams 
2. tear down the 2 rtp streams (closing the pjmedia_transport)
3. recreate the same 2 rtp streams
4. Repeat the steps from 1 to 3  for many times until the assertion !pj_list_empty(free_list) doesn't fail

### PJSIP version

2.5.5

### Context

The issue happen on Linux embedded system armv7

### Log, call stack, etc

```shell
../src/pj/ioqueue_select.c:363: pj_ioqueue_register_sock2: Assertion `!pj_list_empty(&ioqueue->free_list)' failed.
```

**Comment by jimying** [comment]
when tear down, do you call  pjmedia_transport_media_stop() and pjmedia_transport_close() ?

**Comment by feanoer** [comment]
Yes, I called both stop_transport first and then close_transport for the transport that i have created.
While testing i noticed this behaviour:
Let's assume at the beginning that the user wants to create 2 rtp streams with same transport
i.e. 
```
st1 ->ip.addr=192.168.11.50 port=3000
st2 ->ip.addr=192.168.11.55 port=3000 
```
so i'll call pjmedia_transport_create for the first st1, while i'll call pjmedia_transport_attach for the next st2.

Subsequently, the user will press the button to change the configuration of stream (it mean close transport ,stream ecc and rising up the new streams) even if he does not effectivly change them but confirms the same ipaddress and port value.

Doing this operations for N times I noticed that, at the n-th time, the pjmedia_transport_attach function for st2 will call pj_ioqueue_register_sock2 and will go into failed assertion.
So actually I don't call pjmedia_transport_media_stop () and pjmedia_transport_close () for all streams, because st2 "attaches" to the media transport of st1, and then I close only the latter (the various N times)

**Comment by jimying** [comment]
What is the value of macro PJ_IOQUEUE_MAX_HANDLES？
```
If the value is small,
You can set PJ_IOQUEUE_MAX_HANDLES a bigger value,  rebuild pjproject library , and test again
Notice:
PJ_IOQUEUE_MAX_HANDLES is not greater than FD_SETSIZE
```

**Comment by feanoer** [comment]
Thanks jimying.
PJ_IOQUEUE_MAX_HANDLES was def to 64. So I have increase it to 256 and now i can do the steps about 128 times: so the ioqueue have more capacity and it can register the new fd sockets for rtp and rtcp.
Why does my ioqueue fill its space indefinitely? It seems as if the unregister rtp stream socket fd of pjmedia_transport_close () doesn't work.

**Comment by jimying** [comment]
```
pjmedia_transport_udp_create() :   create a  rtp stream (register rtp/rtcp two socks to ioqueue)
pjmedia_transport_stop():   close a rtp stream ( unregister rtp/rcp twosocks from ioqueue)
pjmedia_transport_attach():   Attach callbacks of rtp/rtcp receive data event
```
Only pjmedia_transport_udp_create()/pjmedia_transport_stop() will change ioqueue's used size

Please check your code again.

or You can share code, let others review it.

**Comment by feanoer** [comment]
I looked at my code and noticed that ioqueue grows out of control because both the pjmedia_transport_udp_create and pjmedia_transport_udp_attach functions add their own rtp and rtcp sockets (total +4 each turn).
I can only do pjmedia_transport_close for stream1 with the created transport, because in the case of stream 2 with the transport attached, the pjmedia_transport_op->destroy value is inconsistent and my application crashes.
How can I get rid of the additional sockets of stream 2?

**Comment by jimying** [comment]
@feanoer 
```
You should use pjmedia_transport_attach() replace pjmedia_transport_udp_attach()
```
pjmedia_transport_udp_attach() create rtp/rtcp two socks
pjmedia_transport_udp_create()  has called pjmedia_transport_udp_attach() internal, 
if you call  pjmedia_transport_udp_attach() once,  will create another two rtp/rtcp sockets, 
which will leak two sockts!

**Comment by feanoer** [comment]
I replaced pjmedia_transport_udp_attach() with pjmedia_transport_attach() and it's correct that ioqueue don't register another couple of socket unwanted, but in this way, considering always the example that i made before
`st1 ->ip.addr=192.168.11.50 port=3000
st2 ->ip.addr=192.168.11.55 port=3000 ` 
when i call pjmedia_transport_attach() for the st2 with the transport of st1 attached, the st1 seem stopped (from wireshark there isn't any transaction of rtp rtcp packets with 192.168.11.50) while the st2 seems start to work.
I want to establish 2 rtp streams that works at the same time, so if st1 and st2 ports are different there isn't problem because i can use  pjmedia_transport_udp_create() for both, but assuming that the ports are the same, can i use pjmedia_transport_attach() to attach the transport of st1 to st2 and use them simultaneously? (despite the problems it entailed, pjmedia_transport_udp_attach seemed to work for this purpose)

**Comment by feanoer** [comment]
Looking in the src of pjmedia i see that in transport_udp.c the function
`static pj_status_t transport_attach`
has this line
`/* Must not be "attached" to existing application */
    PJ_ASSERT_RETURN(!udp->attached, PJ_EINVALIDOP);`
The behavior suggest by the comment seems to contradict my purpose
