### ISSUE TITLE
Add wildcard certificate support

### ISSUE THREAD

**Issue by kharwell** [pjsip/pjproject#3113]
**Is your feature request related to a problem? Please describe.**
Yes, pjsip rightly disallows the use of wildcards in certificates in accordance with [RFC5922](https://datatracker.ietf.org/doc/html/rfc5922#section-7.2). However, projects/companies do use them so it would be nice to have a way to enable such functionality within pjsip.

**Describe the solution you'd like**
Create a new setting for TLS transports called "allow_wildcard_certs". It defaults to false to maintain current behavior, but when true certificate names that start with "*." will match as a wildcard. This can be done in accordance with [RFC2818](https://datatracker.ietf.org/doc/html/rfc2818#section-3.1) for subject alt names of type dNSName. Also, since this behavior will be selectable allowing the match on the common name would also be ideal.

**Describe alternatives you've considered**
Don't use wildcard certificates.

**Comment by shooding** [comment]
See [Issue comment](https://github.com/pjsip/pjproject/pull/2328#issuecomment-595004025)
after tracing code in sip_transport_tls.c 
verify_status is bitwise OR operation of all kinds of verification errors,
which means if verify_status == PJ_SSL_CERT_EIDENTITY_NOT_MATCH, means this is the only error discovered during verification of sip_transport_tls.c, checking wildcard cert can be done in App outside pjsip.
