### ISSUE TITLE
Crash on pjmedia_vid_dev_refresh() after deinitialization of video device factory

### ISSUE THREAD

**Issue by half-left** [pjsip/pjproject#3122]
### Describe the bug

I build pjproject with v4l2 support  
But sometimes i need to use another factory and deinit v4l2 factory. I call pjmedia_vid_driver_deinit() for v4l2 driver, then pjmedia_vid_dev_refresh to exclude v4l2 devices, but app crashes.

### Steps to reproduce

Code:  
`pjmedia_vid_subsys *vs = pjmedia_get_vid_subsys(); ` 
`    for(i=0; i<vs->drv_cnt; i++) {`
`    if(strcmp(vs->drv[i].name, "v4l2") == 0) {`
`        pjmedia_vid_driver_deinit(i);`
`        pjmedia_vid_dev_refresh();`
`        break;`
`    }`
`}`

### PJSIP version

2.10

### Context

linux, v4l2 support enabled( adding `#define PJMEDIA_VIDEO_DEV_HAS_V4L2 1` to config_site.h )

### Log, call stack, etc

```shell
Trace:  
pjmedia_vid_driver_init (drv_idx=drv_idx@entry=0, refresh=refresh@entry=1) at ../src/pjmedia/videodev.c:221
221         dev_cnt = f->op->get_dev_count(f);
(gdb) bt
#0  0x00007fffe8f5f1ba in pjmedia_vid_driver_init (drv_idx=drv_idx@entry=0, refresh=refresh@entry=1) at ../src/pjmedia/videodev.c:221
#1  0x00007fffe8f5f4b3 in pjmedia_vid_dev_refresh () at ../src/pjmedia/videodev.c:316
```

**Comment by sauwming** [comment]
After deinit, of course you're not supposed to use it. You need to initialise it again if you intend to do so.

**Comment by half-left** [comment]
i dont want to use v4l2 devices, i want to unregister v4l2 factory and enumerate video devices after it, but i have crash in pjmedia_vid_dev_refresh
