### ISSUE TITLE
Crash in pjmedia_stream_get_stat

### ISSUE THREAD

**Issue by Oscarworld** [pjsip/pjproject#3124]
### Describe the bug

Hi,

We have a large number of crashes on iOS.

### Steps to reproduce

Can't be reproduced in debug.

### PJSIP version

2.11

### Context

Crashes happen on both 2.10.0 and 2.11.0, on different versions of iOS and on different devices

### Log, call stack, etc

```shell
From Crashlytics.
Stack trace:
`Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x29334 __pthread_kill + 8
1  libsystem_pthread.dylib        0x2a9c pthread_kill + 272
2  libsystem_c.dylib              0x77b84 abort + 124
3  libsystem_c.dylib              0x77004 err + 290
4  Wakie                          0x142fa94 pjmedia_stream_get_stat + 4127080
5  Wakie                          0x1695f0c pjsua_call_get_stream_stat + 6643168
....`

Keys:
Key: crash_info_entry_0
Value: Assertion failed: (stream && stat), function pjmedia_stream_get_stat, file stream.c, line 3117.
```

**Comment by FredWH** [comment]
Before call pjmedia_stream_get_stat, have checked media status? Is media active?

**Comment by Oscarworld** [comment]
Managed to fix the problem. The problem was when deallocate pjsip object.
