### ISSUE TITLE
.net MAUI support

### ISSUE THREAD

**Issue by maestro-oc** [pjsip/pjproject#3134]
Have you got any plans to add support for .net MAUI?

**Comment by sauwming** [comment]
Unfortunately, not at the moment.

**Comment by weslleymurdock** [comment]
Hi folks
I know this issue is closed, but i've done a sample app with maui for both android and ios.
How can i submit a PR with the code?

**Comment by sauwming** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
