### ISSUE TITLE
pjsip and openssl 1.1.1+ problems

### ISSUE THREAD

**Issue by Maledictus** [pjsip/pjproject#3147]
### Describe the bug

1. If openssl 1.1.1+ was build without `no-dso` flag pjsip can't use it because lss and lcrypto checks hasn't '-ldl' linker option

### Steps to reproduce

1. Build openssl: `./config no-shared --prefix=<PREFIX> && make && make install_sw`
2. Build pjsip: `./aconfigure --prefix=<PREFIX> --target=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu \
--host=x86_64-pc-linux-gnu --disable-libwebrtc --enable-epoll CFLAGS="-g -D_GNU_SOURCE -DLINUX  -W -m64" \
--with-ssl=<PATH_TO_OPENSSL> && make dep && make && make install` 

### PJSIP version

2.12

### Context

CentOS7

### Log, call stack, etc

```shell
Using SSL prefix... /usr/local/rtcctl64/openssl_1_1_1o
checking for OpenSSL installations..
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking for ERR_load_BIO_strings in -lcrypto... no
checking for SSL_CTX_new in -lssl... no
** OpenSSL libraries not found **
```

**Comment by sauwming** [comment]
With a lot of build options for a third party library, it may not be possible to support/accommodate all of the possible configurations. But please feel free to submit a patch to fix the issue.
