### ISSUE TITLE
Crush when mute video during video conference call on android application

### ISSUE THREAD

**Issue by ivgvard** [pjsip/pjproject#3153]
### Describe the bug

During video conference call if creator invoke vidSetStream(PJSUA_CALL_VID_STRM_STOP_TRANSMIT, new CallVidSetStreamParam());, app crash.

### Steps to reproduce

1. Set for all codecs same media format(enc and dec) height and width for all conference participant.
          encMediaFormatVideo.setHeight(size.getHeight());
2. Create video conference.
3. Invoke vidSetStream(PJSUA_CALL_VID_STRM_STOP_TRANSMIT, new CallVidSetStreamParam()); on conference creator.

### PJSIP version

2.10

### Context

Android version 12
NDK version 13 
SWIG version 4.0.2

### Log, call stack, etc

```shell
A/libc: ../src/pjmedia/vid_conf.c:1078: render_src_frame: assertion "src->get_buf_size <= sink->put_buf_size" failed
 A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21211 (SipService), pid 20721 (demoapplication)
```

**Comment by sauwming** [comment]
PJSIP 2.10 is quite old. Please try with the latest version, and reopen if the issue persists.
