### ISSUE TITLE
Set thread display name (on unix)

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3157]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
pj_thread_create()  create  thread with thread_name argment, but i can't use command:
```
#  linux/freebsd
top -H -p pid

#  htop ( Setup:  F2(setup)->Display options->show custom thread names)
htop -p pid
```
to see the thread name that has setup in code.

We can use pthread api to set thread display name:
```
pthread_setname_np()  linux/darwin  pthread.h
pthread_setname_np()/pthead_set_name_np()   bsd   pthead_np.h
```
The api can make "top" command display thread name correctly.
This can be useful for debugging.

**Comment by jimying** [comment]
#3156

**Comment by andreas-wehrmann** [comment]
This would indeed be very helpful;
On Windows, according to MSDN, one can use SetThreadDescription() to set the name of a thread; see:
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription

**Comment by jimying** [comment]
@andreas-wehrmann 

Here an useful link:
[win32: how-to-set-a-thread-name-in-native-code](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2022)
supply two methods:
1. Set a thread name by using SetThreadDescription
2. Set a thread name by throwing an exception

Please go to the link to compare two methods.

The 1st method only work with “Visual Studio 2017 version 15.6 and later versions” and "Windows 10 version 1607, Windows Server 2016 or later versions of Windows"

I think the 2th method can "Works in all versions of Visual Studio" and no windows version limit.

**So if i add this feature to win32,  i will use the 2th method. **

**Comment by jimying** [comment]
@andreas-wehrmann 
```
#if  IF_HAS_SetThreadDescription
       // TODO
#else
      // Use throwing an exception，already added 
#endif
```
The two do not conflict. 
Some tests should be done  before adding SetThreadDescription branch.
I have no no development environment now，hope someone can help to add this branch later.

**Comment by jimying** [comment]
@andreas-wehrmann 
I have added SetThreadDescription() support , 
Could you go to pull request #3156 to help review and test it？
