### ISSUE TITLE
2.12 introduced a bug in SSL version check in pjlib/src/pj/ssl_sock_ossl.c causing builds to fail on systems with openssl 1.1.0

### ISSUE THREAD

**Issue by ffloimair** [pjsip/pjproject#3159]
### Describe the bug

Release 2.12 has added code that is guarded by an ifdef, however the version in this ifdef is for openssl greater or equal to 1.1.0, but the code uses a method (SSL_SESSION_is_resumable) that has been introduced with openssl 1.1.1 causing libpj to fail on build on systems with openssl 1.1.0 (e.g. Debian 9 "stretch").

However the fix is easy:

Change the openssl version macro string itself to check against 1.1.1 or greater (instead of 1.1.0)

I have already prepared a patch for this and will create a pull-request shortly.

### Steps to reproduce

Checkout pjsip 2.12 or newer
Try building on a distro that has 1.1.0 as default -> e.g. Debian 9 "stretch"
Build will fail in linking stage as symbol SSL_SESSION_is_resumable cannot be found

### PJSIP version

2.12

### Context

Any OS that uses openssl with at least 1.1.0 but earlier than 1.1.1 (e.g. Debian 9 "stretch")

### Log, call stack, etc

```shell
(issue and solution already described above)
```

**Comment by seanbright** [comment]
There is an open PR for this #3120

**Comment by ffloimair** [comment]
thanks. I missed this. Closing
