### ISSUE TITLE
as tcp server ,when use multi-thread (select or epoll),  on_accept_complete may cause  crash

### ISSUE THREAD

**Issue by wahjrzd** [pjsip/pjproject#3161]
### Describe the bug

file :
sip_transport_tcp.c
function: on_accept_complete
code:
status = tcp_create( listener, NULL, sock, PJ_TRUE, &tmp_dst_addr, &tmp_src_addr, &tcp);
    if (status == PJ_SUCCESS) {
        status = tcp_start_read(tcp);
        if (status != PJ_SUCCESS) {
            PJ_LOG(3,(tcp->base.obj_name, "New transport cancelled"));
            tcp_destroy(&tcp->base, status);
        } else {
            if (tcp->base.is_shutdown || tcp->base.is_destroying) {
                return PJ_TRUE;
            }
            //pj_thread_sleep(1000);
            /* Start keep-alive timer */
            if (pjsip_cfg()->tcp.keep_alive_interval) {
                pj_time_val delay = { 0 };
we known cpu timeslice,  use multi-thread select or epoll,  when i connect server succ ,A thread do tcp_create, I immediately close connection, so B thread do tcp_destroy release all resourse,  if A thread cpu do "if (tcp->base.is_shutdown || tcp->base.is_destroying)" then switch ,then do next,  call state_cb = pjsip_tpmgr_get_state_cb(tcp->base.tpmgr); get cb , call it will crash ,because lock has release.

### Steps to reproduce

status = tcp_create( listener, NULL, sock, PJ_TRUE, &tmp_dst_addr, &tmp_src_addr, &tcp);
    if (status == PJ_SUCCESS) {
        status = tcp_start_read(tcp);
        if (status != PJ_SUCCESS) {
            PJ_LOG(3,(tcp->base.obj_name, "New transport cancelled"));
            tcp_destroy(&tcp->base, status);
        } else {
            if (tcp->base.is_shutdown || tcp->base.is_destroying) {
                return PJ_TRUE;
            }
            pj_thread_sleep(1000);
            /* Start keep-alive timer */
            if (pjsip_cfg()->tcp.keep_alive_interval) {
                pj_time_val delay = { 0 };

we use pj_thread_sleep simulation timeslice switch . use two or more thread select(epoll), client connect it and immediately close connection,then crash

### PJSIP version

2.11.1 /  2.12.1

### Context

 os: centos7

### Log, call stack, etc

```shell
../src/pj/lock.c:179: pj_lock_acquire: Assertion `lock != ((void *)0)' failed.
```

**Comment by wahjrzd** [comment]
is there anyone can respond to me      v_v  v_v

**Comment by sauwming** [comment]
It seems like this is application issue.
You need to utilise synchronisation mechanism, such as group lock, to prevent accessing object that is being/has already been destroyed.

If you think there's something I miss, please provide the complete stack trace, so I can understand where exactly the crash occurred.
