### ISSUE TITLE
Build fails with PJ_CONFIG_MAXIMUM_SPEED enabled in pj/config_site_sample.h

### ISSUE THREAD

**Issue by msehnout** [pjsip/pjproject#3162]
### Describe the bug

I'm trying to build pjsua2 for Python with support for multiple (preferably hundreds) of parallel calls. I found the `PJ_CONFIG_MAXIMUM_SPEED` config option in `config_site_sample.h` but it fails to build with `error: #error "PJ_IOQUEUE_MAX_HANDLES cannot be greater than FD_SETSIZE"`. As far as my understanding goes, FD_SETSIZE cannot be increased (https://access.redhat.com/solutions/488623). Is it ok to decrease `PJ_IOQUEUE_MAX_HANDLES` and still expect pjsua2 to handle hundreds of calls?

### Steps to reproduce

1. Create config_site.h:
```c
#define PJ_CONFIG_MAXIMUM_SPEED

#include <pj/config_site_sample.h>
```
 2. Create Dockerfile
```Dockerfile
FROM python:3.10

RUN apt-get update
# Install dependencies of pjsua2
RUN apt-get install libopus0 libasound2 -y
RUN apt-get install git -y
# Install build requirements for pjsua2
RUN apt-get install build-essential swig python3-all-dev -y
WORKDIR /tmp
RUN git clone https://github.com/pjsip/pjproject.git
WORKDIR /tmp/pjproject
RUN CFLAGS=-DNDEBUG CXXFLAGS=-DNDEBUG ./configure --enable-shared
COPY config_site.h pjlib/include/pj/config_site.h
RUN make dep
RUN make
RUN make install
```
 3. Try the build with `docker build .`

### PJSIP version

latest git checkout

### Context

Linux container, Python3.10 image, the config_site.h is above, I believe glibc with the default 1024 limit of FD_SETSIZE is used inside of the container

### Log, call stack, etc

```shell
gcc -c -Wall -DPJ_AUTOCONF=1 -DNDEBUG -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1 -fPIC    -I../include \
        -o output/pjlib-x86_64-unknown-linux-gnu/ioqueue_select.o \
        ../src/pj/ioqueue_select.c 
../src/pj/ioqueue_select.c:48:5: error: #error "PJ_IOQUEUE_MAX_HANDLES cannot be greater than FD_SETSIZE"
   48 | #   error "PJ_IOQUEUE_MAX_HANDLES cannot be greater than FD_SETSIZE"
      |     ^~~~~
make[2]: *** [/tmp/pjproject/build/rules.mak:163: output/pjlib-x86_64-unknown-linux-gnu/ioqueue_select.o] Error 1
make[2]: Leaving directory '/tmp/pjproject/pjlib/build'
make[1]: *** [Makefile:106: libpj-x86_64-unknown-linux-gnu.a] Error 2
make[1]: Leaving directory '/tmp/pjproject/pjlib/build'
make: *** [Makefile:14: all] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
```

**Comment by jimying** [comment]
./configure --enable-epoll

default use select() has limit fd size to FD_SETSIZE

**Comment by msehnout** [comment]
@jimying Thanks! I've totally missed there is a support for epoll.

Configure still reports epoll support as experimental. Is it ready to be used? I believe I don't have any special use case. Just plain audio phone calls.

**Comment by msehnout** [comment]
Ok, thanks for the quick replies :-)
