### ISSUE TITLE
Incoming call request verification fails and sends 488 response when using TLS and SRTP

### ISSUE THREAD

**Issue by daholino** [pjsip/pjproject#3176]
### Describe the bug

When using TLS transport with libsrtp 2.x built manually the incoming call request generates a 488 response. This happens because when comparing local SDP that is created with `create_temp_sdp()` has media transport **RTP/AVP** and the transport from server's SDP has transport **RTP/SAVP**. I will now provide a more detailed description:

When receiving an incoming call inside the: 

- `pj_bool_t pjsua_call_on_incoming(pjsip_rx_data *rdata)`

and then when verifying the incoming request inside:

- `static pj_status_t verify_request(const pjsua_call *call,
				  pjsip_rx_data *rdata,
				  pj_bool_t use_tmp_sdp,
				  int *sip_err_code,
				  pjsip_tx_data **response)`

the flag for `use_tmp_sdp` is set to **PJ_TRUE**. This creates the new SDP inside `create_temp_sdp()` function. After that our local SDP is being compared with the remote (offer) SDP. After some functions we end up inside: `pjmedia_sdp_neg_negotiate()`. After that the code ends up in `create_answer()` function. Create answer starts comparing local and remote SDP and in particular it compares the media from SDP. 

This if branch fails when SDP is created as temporary:

```c
if (pj_strcmp(&om->desc.media, &im->desc.media)==0 &&
		pj_strcmp(&om->desc.transport, &im->desc.transport)==0 &&
		media_used[j] == 0)
```

... because when comparing transports local transport is **RTP/AVP** and remote is **RTP/SAVP**. I didn't find any options that check if `use_srtp` is set when generating local SDP.

I've made sure that these two lines are set in the client side of the app:
```c
config.use_srtp = PJMEDIA_SRTP_MANDATORY;
config.srtp_secure_signaling = 1;
```

PJProject is used on the server inside Asterisk and SRTP option is also set to mandatory.

We are currently using PJProject version 2.7.2. I've tried 2.8 and it works good. I experienced this issue when using 2.12.1 and 2.10 versions. I think that this change (the creation of local temp sdp) is introduced in this code change: https://github.com/pjsip/pjproject/issues/2173

When using TCP transport everything works as it should.

If I add this code in `create_temp_sdp()` after creating the media for that SDP everything works normally:
```c
if (pjsua_var.ua_cfg.use_srtp) {
	pj_str_t srtp_transport = {"RTP/SAVP", 8};
	m->desc.transport = srtp_transport;
}
```

When making an outgoing call SDP is created with **RTP/SAVP** transport and everything works ok.

I've not seen a similar issue and I would like to ask if I am doing something wrong or did I stumble on a bug?

### Steps to reproduce

1. Make sure that the server uses TLS and SRTP as mandatory.
2. Build any version of PJProject 2.9 or later for iPhone
3. Receive an incoming call on the iPhone and inspect if 488 request is generated

### PJSIP version

2.12.1

### Context

I am testing on an iPhone XS with iOS 15.5. In my build I am including Opus codec, libssl with 1.1.1l version and libsrtp with 2.2 version.

This is the config_site:
```
#define PJ_CONFIG_IPHONE            	1
#define PJSIP_ENCODE_SHORT_HNAME    	1
#define PJ_HAS_SSL_SOCK             	1
#define PJSIP_HAS_TLS_TRANSPORT     	1
#define PJSIP_TCP_KEEP_ALIVE_INTERVAL   30
#define PJSIP_TLS_KEEP_ALIVE_INTERVAL   30
#define PJ_ENABLE_EXTRA_CHECK			0
#define PJ_HAS_IPV6 					1
#define PJMEDIA_SRTP_HAS_AES_CM_256     0 
#define PJ_GETADDRINFO_USE_CFHOST 0
#define NDEBUG 1

#include <pj/config_site_sample.h>
```

### Log, call stack, etc

```shell
# I have some logs where I logged the local and remote SDP.

# Local SDP:
v=0

o=- 3866258545 3866258545 IN IP4 127.0.0.1

s=pjmedia

t=0 0

m=audio 50123 RTP/AVP 96 9 0 8 120 121

c=IN IP4 127.0.0.1

b=TIAS:96000

a=rtcp:50124 IN IP4 127.0.0.1

a=sendrecv

a=rtpmap:96 opus/48000/2

a=fmtp:96 useinbandfec=1

a=rtpmap:9 G722/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:120 telephone-event/48000

a=fmtp:120 0-16

a=rtpmap:121 telephone-event/8000

a=fmtp:121 0-16

# Remote SDP:
v=0

o=- 533061789 533061789 IN IP4 x.x.x.x

s=Asterisk

c=IN IP4 x.x.x.x

t=0 0

m=audio 12120 RTP/SAVP 107 0 9 101

a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:Veaap2MJs2vIxdPuzYD7xhHnFSTe3layGAvlkny8

a=rtpmap:107 opus/48000/2

a=fmtp:107 useinbandfec=1

a=rtpmap:0 PCMU/8000

a=rtpmap:9 G722/8000

a=rtpmap:101 telephone-event/8000

a=fmtp:101 0-16

a=ptime:20

a=maxptime:20

a=sendrecv

===================================

# This is the error that is logged to the console:

10:42:25.336           pjsua_call.c  ..Request verification failed: Not Acceptable Here [status=170488]
10:42:25.336         dlg0x1550262a8  ...Sending Response msg 488/INVITE/cseq=13654 (tdta0x155064ea8)
10:42:25.336         tsx0x1550616a8  ...Sending Response msg 488/INVITE/cseq=13654 (tdta0x155064ea8) in state Trying
10:42:25.336           pjsua_core.c  ....TX 557 bytes Response msg 488/INVITE/cseq=13654 (tdta0x155064ea8) to TLS x.x.x.x:5061:
SIP/2.0 488 Not Acceptable Here

v: SIP/2.0/TLS x.x.x.x:5061;rport=5061;received=x.x.x.x;branch=z9hG4bKPj2a90a4cc-bd8e-4a33-ae1d-6ed7055696bd;alias

i: 93fc3bc1-70bb-4ced-8b40-ce697fb6ee9e

f: "Tarik iPhone" <sip:xxxx@x.x.x.x>;tag=928b2fb4-108e-4e06-b721-8215203ecf69

t: <sip:xxxx@x.x.x.x;x-ios-1657269744.968347;ob>;tag=7A13D479-F644-4AAF-AA4F-FB8E829A1599

CSeq: 13654 INVITE

Warning: 399 iPhone-XS "No active media stream after negotiation (PJMEDIA_SDPNEG_ENOMEDIA)"

Accept: application/sdp

l:  0
```

**Comment by vanishiess** [comment]
faced exactly the same problem, it helped to disable PJ_CONFIG_MAXIMUM_SPEED from config_site.h

my config:

//#define PJ_CONFIG_MAXIMUM_SPEED 1
#define PJ_HAS_SSL_SOCK 1

#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS		     101
#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS_STR		"101"

#define PJMEDIA_HAS_G729_CODEC 1
#define PJMEDIA_HAS_OPUS_CODEC 1

#define PJSUA_MAX_ACC 32
#define PJSUA_ACC_MAX_PROXIES 8

#include "config_site_sample.h"

**Comment by sauwming** [comment]
This should be fixed by https://github.com/pjsip/pjproject/commit/319bbab0870e115cdc39853b9ecc91455020b27e#diff-3981710a639e7fa1e83963a5dac4cb6a05cffb2da2179a4bd891c11f790de3beR1472

if `pjmedia_sdp_validate(offer)` returns PJ_SUCCESS, `create_answer()` will return PJ_SUCCESS.
