### ISSUE TITLE
PJ_HAS_TCP=0 build fail

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3177]
### Describe the bug

As title

### Steps to reproduce

config_site.h   set macro PJ_HAS_TCP to 0, and build

### PJSIP version

2.12-dev

### Context

-

### Log, call stack, etc

```shell
-
```

**Comment by sauwming** [comment]
Unfortunately you're right. But TCP usage has been so pervasive there's no way to fix this now. The only solution is to deprecate the setting and always set it to 1.
