### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by yuexiajiayan** [pjsip/pjproject#3186]
### Describe the bug

when run :
cd pjsip-apps/src/swig=> make 
return :
"/opt/jdk1.8.0_152/bin/javac" -d output android/pjsua2/src/main/java/org/pjsip/pjsua2/*.java android/app/src/main/java/org/pjsip/pjsua2/app/MyApp.java
android/pjsua2/src/main/java/org/pjsip/pjsua2/pjmedia_event_type.java:25: error: illegal start of expression
  public final static int PJMEDIA_EVENT_CALLBACK = (((  << 24)|(  << 16))|(B << 8))|C;
                                                        ^
android/pjsua2/src/main/java/org/pjsip/pjsua2/pjmedia_event_type.java:25: error: illegal start of expression
  public final static int PJMEDIA_EVENT_CALLBACK = (((  << 24)|(  << 16))|(B << 8))|C;
                                                                  ^
android/pjsua2/src/main/java/org/pjsip/pjsua2/pjmedia_format_id.java:18: error: illegal start of expression
  public final static int PJMEDIA_FORMAT_AMR = (((R << 24)|(M << 16))|(A << 8))| ;
                                                                                 ^
android/pjsua2/src/main/java/org/pjsip/pjsua2/pjmedia_format_id.java:25: error: illegal start of expression
  public final static int PJMEDIA_FORMAT_DIB = (((  << 24)|(B << 16))|(I << 8))|D;
                                                    ^
4 errors
Makefile:202: recipe for target 'android/pjsua2/src/main/java/org/pjsip/pjsua2/Error.class' failed
make[1]: *** [android/pjsua2/src/main/java/org/pjsip/pjsua2/Error.class] Error 1
Makefile:27: recipe for target 'java' failed
make: *** [java] Error 2

### PJSIP version

2.11

### Context

 (((  << 24)|(  << 16))|(B << 8))|C 
can  change to  ((( ' ' << 24)|(' '  << 16))|('B' << 8))|'C'?

### Log, call stack, etc

```shell
 
```

**Comment by sauwming** [comment]
I am unable to reproduce this.
Please try with the latest version, and reopen if the issue persists.

**Comment by VelproHHH** [comment]
I also have this problem, please how to solve it
