### ISSUE TITLE
Does it work? I have a crash when add .p12 certificate with password and execute pjsua_transport_create(): "Thread 1: EXC_BAD_ACCESS (code=1, address=...)"

### ISSUE THREAD

**Issue by elfortitude** [pjsip/pjproject#3194]
On iOS (sample project ipjsua-swift) I'm trying to use TSL and I have a crash when add .p12 certificate with password and execute pjsua_transport_create(): "Thread 1: EXC_BAD_ACCESS (code=1, address=...)". 

_Originally posted by @elfortitude in https://github.com/pjsip/pjproject/issues/2482#issuecomment-1195501861_

**Comment by sauwming** [comment]
For Apple/Darwin SSL backend, you need to add the private key into the Keychain, like what we do in our pjlib-test here:
https://github.com/pjsip/pjproject/blob/master/pjlib/src/pjlib-test/ssl_sock.c#L761

**Comment by elfortitude** [comment]
But I tried on iOS, not on Mac. My app doesn't have access to general keychain. What about?

**Comment by henlund** [comment]
I have the same issue iOS. I'm adding a .p12 certificate containing cert, ca list and private key, and I get a crash inside ssl_sock_apple.m at 

*p_identity = sec_identity_create(identity);

Please provide an example of how to use the keychain on iOS.
