### ISSUE TITLE
Encoding format changed between 2.12, 2.11 on sip_multipart?

### ISSUE THREAD

**Issue by AmarOk1412** [pjsip/pjproject#3198]
### Describe the bug

Hi,

we're currently checking to bump from 2.11 to 2.12, all rebase were successful, and every scenario seems ok so far, however we observed a changes in the strings

We use `pjsip_multipart_get_first_part` and `pjsip_multipart_get_next_part` and only pjsip changed. With pjsip 2.12, it seems that some "=" we have in the Content-Type part are encoded via some Percent-encoding.

There is 2 patches in sip_multipart but it's not this, neither the latest Miscellaneous fixes I see in the backtrace, so I'm wondering from what patch it comes from (Else I guess I'll have to bisect). It's not a big deal as it's done somewhere during the reception of the message, but I want to understand what potential changes we will have or if it will cause any other bug. 

### Steps to reproduce

N/A

### PJSIP version

2.12

### Context

At least Linux

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
The one that I can remember off the top of my head is https://github.com/pjsip/pjproject/pull/2933.

**Comment by AmarOk1412** [comment]
Seems related, but it's indeed not this.

This is what I see `Content-Type: x-ring/ring.profile.vcard;id=983447750%2cpart%3d22%2cof%3d22` for 

```
Via: SIP/2.0/TLS IP:33368;rport=33368;received=IP;branch=z9hG4bKPjba278dab-f48d-4f8b-9c75-197b56971214;alias
Max-Forwards: 70
From: <sips:ID@IP>;tag=15e9fa88-7c9d-44c9-830a-bb4ad0958eea
To: "TEST" <sip:ID@IP>;tag=4188e3fc-9652-4ab6-9ebf-a9fcdc9bcb4d
Call-ID: 64501dca-9f5d-4483-a9d1-2c132805c5dd
CSeq: 1212 MESSAGE
Content-Type: x-ring/ring.profile.vcard;id=983447750%2cpart%3d22%2cof%3d22
Content-Length: 884
Content-Type: x-ring/ring.profile.vcard;id=983447750%2cpart%3d22%2cof%3d22
Content-Length:     
```

**Comment by AmarOk1412** [comment]
@sauwming in fact, you're right, it's indeed related to #2933 ; in the receiver, this is what I see before the patch (so if I rebase on 88b7e0f12e3b17cc7fba28a0546b7ca120059b59): `"x-ring/ring.profile.vcard;id=1591270544;part=1;of=22"`

This is what I see after: `"x-ring/ring.profile.vcard;id=1591270544%2cpart%3d1%2cof%3d22"`

**Comment by AmarOk1412** [comment]
So yeah it's fine for me, the original message is `id=1591270544%2cpart%3d1%2cof%3d22` and should not be un-escaped as the RFC specify.

It's just a bug fix from an old thing that was working.

Thank you for the fast reply
