### ISSUE TITLE
Compile fail on git master

### ISSUE THREAD

**Issue by gene-git** [pjsip/pjproject#3203]
### Describe the bug

I've started getting this fail in "make dep" building git master (commit d4dc67706bccb03eba697377be7bf34cf1bdcd10)

In dir pjnath/build :
.pjnath-x86_64-unknown-linux-gnu.depend:1075: *** missing separator.  Stop.

Line 1075 is the last line in the file and contains:
output/pjnath-x86_64-unknown-linux-gnu/

It could have started with commit 8861441ec8ea3fc7bf70d40ec3a1efec9dc65a1a 

Toolchain:
Linux (archlinux)
gcc 12.1.1
make 4.3
binutils 2.39

### Steps to reproduce
git fetch ; git pull origin
git clean -fddx

./configure --prefix=/usr --enable-shared --enable-ext-sound  --disable-opencore-amr --with-external-yuv --with-external-speex  CFLAGS="-O2"

make dep

### PJSIP version

git master

### Context

Linux

### Log, call stack, etc

```shell
N/A
```

**Comment by jimying** [comment]
delete .pjnath-x86_64-unknown-linux-gnu.depend and try again

**Comment by gene-git** [comment]
the git -fddx should have done that. Did a fresh git pull - configure, make dep, make and now I get:

gcc -c -Wall -DPJ_AUTOCONF=1    -O2 -DNDEBUG -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1 -fPIC -DPJNATH_HAS_UPNP=1     -I../include -I../../pjlib/include -I../../pjlib-util/include \
	-o output/pjnath-x86_64-unknown-linux-gnu/upnp.o \
	../src/pjnath/upnp.c 
../src/pjnath/upnp.c:31:10: fatal error: upnp/upnpdebug.h: No such file or directory
   31 | #include <upnp/upnpdebug.h>

**Comment by jimying** [comment]
@gene-git 
set marcro  PJNATH_HAS_UPNP to 0
please see upnp.c, which is control by this macro

**Comment by gene-git** [comment]
libupnp is installed but there is no file called upnpdebug.h 

$ pacman -Ss libupnp
extra/libupnp 1.14.13-1 [installed]

$ ls -l /usr/include/upnp/upnp*h
  8 -rw-r--r-- 1 root root   5143 Aug  3 12:37 /usr/include/upnp/upnpconfig.h
112 -rw-r--r-- 1 root root 112294 Aug  3 12:37 /usr/include/upnp/upnp.h
 12 -rw-r--r-- 1 root root  10041 Aug  3 12:37 /usr/include/upnp/upnptools.h

**Comment by sauwming** [comment]
> libupnp is installed but there is no file called upnpdebug.h

Right, it looks like your libupnp installation was not built with debug enabled. So I fixed this in #3213.
