### ISSUE TITLE
In Asterisk, incoming MESSAGE dialplan cannot invoke PJSIP_HEADER

### ISSUE THREAD

**Issue by nathanielhourt** [pjsip/pjproject#3211]
### Describe the bug

I have an Asterisk instance configured to connect to a SIP trunking ITSP via pjsip, and I am attempting to receive SMS messages to my DIDs coming through that trunk. I have configured the endpoint to route messages to the appropriate dialplan context with the `message_context` option in `pjsip.conf`.

Unfortunately, the ITSP does not set the incoming DID in the SIP message `To` field, but instead puts it in the `X-sentto_did` header. It would seem that I could simply query this header from my dialplan using `PJSIP_HEADER(read, X-sentto_did)` and route the message accordingly; however, this fails with an error:
`[Aug 10 00:34:58] ERROR[18][C-00000001]: res_pjsip_header_funcs.c:621 func_read_header: This function requires a PJSIP channel.`

I believe this function should work, as the dialplan is being invoked by PJSIP in the process of handling a SIP request, but at least I expect there to be some way to read this header.

### Steps to reproduce

Using PJSIP 2.12.1 in Asterisk 19.5.0, set up endpoint in `pjsip.conf` like so:

```ini
[My-ITSP]
type = endpoint
aors = My-ITSP
outbound_auth = ITSP-auth
context = DID-ITSP
message_context = SMS-ITSP
transport = ipv4
send_rpid = yes
send_pai = yes
allow = !all,ulaw

; [Other-Sections]
; clipped = true
```

Then with dialplan like so:
```ini
[SMS-ITSP]
exten => s,1,Verbose(Incoming SMS from ITSP)
 same => n,Set(Destination=${PJSIP_HEADER(read, X-sentto_did)})
 same => n,NoOp(To ${MESSAGE(to)})
 same => n,NoOp(From ${MESSAGE(from)})
 same => n,NoOp(Body ${MESSAGE(body)})
 same => n,Hangup()
```

Send SMS to incoming DID, and observe the response from Asterisk. With PJSIP verbose logging, we see the full incoming SIP request looks like so:
```http
<--- Received SIP request (678 bytes) from UDP:192.159.66.3:5060 --->
MESSAGE sip:s@<my-IP>:5060 SIP/2.0
Via: SIP/2.0/UDP 192.159.66.3;rport;branch=z9hG4bKcKyyBp62jyaBj
Route: <sip:s@<my-IP>:5060>
Max-Forwards: 70
From: sip:+19876543210@192.159.66.3;tag=jQ3gtZKp095rc
To: sip:s@<my-IP>:5060
Call-ID: 48ac5fce-1844-11ed-81b8-b775a7612324
CSeq: 54709454 MESSAGE
Contact: <sip:192.159.66.3>
User-Agent: SIPStation 2.11.3
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, UPDATE, INFO, REGISTER, REFER, NOTIFY
Supported: timer, path, replaces
Content-Type: text/plain;charset=utf-8
Content-Length: 9
X-FS-Sending-Message: 072af7c6-0940-11ed-a1f9-b775a7612324
X-sentto_did: <my-DID>
X-MessageID: None
 
yet again
```

And furthermore, the dialplan processing logging:
```
    -- Executing [s@SMS-ITSP:1] Verbose("Message/ast_msg_queue", "Incoming SMS from ITSP") in new stack
Incoming SMS from ITSP
[Aug 10 00:34:58] ERROR[18][C-00000001]: res_pjsip_header_funcs.c:621 func_read_header: This function requires a PJSIP channel.
    -- Executing [s@SMS-ITSP:2] Set("Message/ast_msg_queue", "Destination=") in new stack
    -- Executing [s@SMS-ITSP:3] NoOp("Message/ast_msg_queue", "To pjsip:s@<my-IP>") in new stack
    -- Executing [s@SMS-ITSP:4] NoOp("Message/ast_msg_queue", "From <sip:+19876543210@192.159.66.3>") in new stack
    -- Executing [s@SMS-ITSP:5] NoOp("Message/ast_msg_queue", "Body yet again") in new stack
    -- Executing [s@SMS-ITSP:6] Hangup("Message/ast_msg_queue", "") in new stack
```

### PJSIP version

2.12.1

### Context

The issue is reproducible using the following Docker container:

```Dockerfile
FROM archlinux:latest
MAINTAINER Nathaniel Hourt <nat.hourt@gmail.com>

RUN /bin/bash -ec "pacman -Syu --noconfirm git make clang patch libedit pkgconfig jansson diffutils; \
    git clone https://github.com/asterisk/asterisk src -b 19.5.0; \
    cd src; \
    mkdir dlcache; \
    ./configure --prefix=/opt/asterisk --localstatedir=/var --sharedstatedir=/var/lib/asterisk/shared --with-externals-cache=/src/dlcache; \
    cd src; \
    make -j16; \
    make install; \
    cd /; \
    #rm -rf src;
    useradd -rmP /var/lib/asterisk asterisk; \
    chown -R asterisk:asterisk /var/*/asterisk"

USER asterisk:asterisk

VOLUME /opt/asterisk/etc/asterisk
EXPOSE 5060

ENTRYPOINT ["/opt/asterisk/sbin/asterisk", "-vc"]
```

### Log, call stack, etc

```shell
-- Executing [s@SMS-ITSP:1] Verbose("Message/ast_msg_queue", "Incoming SMS from ITSP") in new stack
Incoming SMS from ITSP
[Aug 10 00:34:58] ERROR[18][C-00000001]: res_pjsip_header_funcs.c:621 func_read_header: This function requires a PJSIP channel.
    -- Executing [s@SMS-ITSP:2] Set("Message/ast_msg_queue", "Destination=") in new stack
    -- Executing [s@SMS-ITSP:3] NoOp("Message/ast_msg_queue", "To pjsip:s@<my-IP>") in new stack
    -- Executing [s@SMS-ITSP:4] NoOp("Message/ast_msg_queue", "From <sip:+19876543210@192.159.66.3>") in new stack
    -- Executing [s@SMS-ITSP:5] NoOp("Message/ast_msg_queue", "Body yet again") in new stack
    -- Executing [s@SMS-ITSP:6] Hangup("Message/ast_msg_queue", "") in new stack
```

**Comment by jcolp** [comment]
This is not the Asterisk issue tracker, and pjproject has nothing to do with this. This is purely Asterisk and a help issue. In the future using the [Asterisk community forum](https://community.asterisk.org/) would yield a better result.

The [MESSAGE_DATA dialplan function](https://wiki.asterisk.org/wiki/display/AST/Asterisk+20+Function_MESSAGE_DATA) is used to retrieve header values.

**Comment by nathanielhourt** [comment]
Well, Asterisk issue or not, it was the pjproject people who knew how to resolve it! The good folks I found in the Asterisk community thought the header should be queried using PJSIP_HEADER, and the documentation backed this up.

Apologies for the misplaced issue; the architectural boundaries between Asterisk and pjproject are as yet unclear to me. I will strive to show greater care in the future.

For now, thank you for your help! That function does indeed read the header value. I will remember that "custom data attached to a message" is implemented, at least in this context, as SIP headers.

**Comment by jcolp** [comment]
I'm not with pjproject. I'm the Asterisk Project Lead. I chimed in here so the pjproject people didn't have to deal with it.
