### ISSUE TITLE
Can't use the certificate for TLS, from Air Watch SDK 

### ISSUE THREAD

**Issue by dankhap98** [pjsip/pjproject#3214]
I write for Android and due to security rules, I can't store the certificate in the application files.
It can only come to me through the AirWatch SDK in the form of "Array<KeyManager"
Is there any functionality for working with SSLContext now or will there be one in the future?

**Comment by dankhap98** [comment]
> Я пишу для Android и из-за правил безопасности не могу хранить сертификат в файлах приложения. Мне он может прийти только через AirWatch SDK в виде "Array<KeyManager>" Есть ли какой-то функционал для работы с SSLContext сейчас или будет в будущем?

**Comment by sauwming** [comment]
We support loading from memory buffer: `pj_ssl_cert_load_from_buffer()`
