### ISSUE TITLE
transfer_status callback called for other call when original call ends before transfer is complete

### ISSUE THREAD

**Issue by ozgurakcali** [pjsip/pjproject#3216]
### Describe the bug

When an outgoing REFER is initiated for a call, and the call is hung up before the transfer is complete, the subscription for the call is kept alive. PJSIP then sends a SUBSCRIBE request for the call after the time set in expires value either in the original REFER request, or the latest NOTIFY request.

If, at this point, another call is up that is using the same index, and it has transfer status callback configured, PJSIP calls this callback, as if the status is for the current call.

### Steps to reproduce

1 - run a pjsua app with transfer_status callback configured for calls
2 - answer an incoming call
3 - initiate a transfer with REFER, don't answer the call on destination, and hang up the call before transfer completes
4 - before the REFER / NOTIFY expires, answer a new call that is using the same pjsua call index 
5 - wait for the timer to expire, after which a SUBSCRIBE request will be sent for the original incomplete transfer, and transfer_status callback will be called as if it is for the current call

### PJSIP version

2.10

### Context

- This issue happens on Linux, but I suspect it would happen on all platforms

### Log, call stack, etc

```shell
SUBSCRIBE address SIP/2.0
Max-Forwards: 70
From: from
To: to
Contact: contact
Call-ID: a1b04459f4090fc9dacecd51677eb67e@0.0.0.0
CSeq: 1016 SUBSCRIBE
Event: refer
Expires: 600
Supported: replaces, 100rel, timer, norefersub
Accept: message/sipfrag;version=2.0
Allow-Events: presence, message-summary, refer
Content-Length: 0


SIP/2.0 100 Trying
To: to
From: from
Call-ID: a1b04459f4090fc9dacecd51677eb67e@0.0.0.0
CSeq: 1016 SUBSCRIBE
Content-Length: 0


evsub0x7f93c006f318 ...Subscription state changed ACCEPTED --> TERMINATED
pjsua_call.c .....Xfer client subscription terminated
evsub0x7f93c006f318 ...Subscription destroyed
```

**Comment by sauwming** [comment]
I tried it with the latest version and it seems to be okay, subscriptions on both sides correctly destroyed.

So my recommendation is to test with the latest version, and if the issue persists, can you update the above scenario with more details? (i.e. use names such as Alice, Bob and call A, call B, etc, to avoid confusion).

To answer your question, yes, it should be fine to destroy the subscription.
