### ISSUE TITLE
VS 2019 build python_pjsua

### ISSUE THREAD

**Issue by CraftedCat** [pjsip/pjproject#3227]
### Describe the bug

Can't build python_pjsua in VS 2019, Python 3.9

### Steps to reproduce

1. Open python_pjsua.vcxproj
2. Release x86
3. Run Build

### PJSIP version

2.12.1

### Context

Windows 10
Pjsua building - OK

### Log, call stack, etc

```shell
[https://prnt.sc/ih5_EfkEC8Zj](https://prnt.sc/ih5_EfkEC8Zj)
```

**Comment by trengginas** [comment]
The Python module for pjsip has been deprecated see [doc](https://trac.pjsip.org/repos/wiki/Python_SIP/Build_Install), and for you to use PJSUA2 and Python SWIG binding.
The error probably because you are using python 3.x, as the doc stated you need to use 2.x.
