### ISSUE TITLE
cannot find -lpjsua2-x86_64-apple-darwin20.3.0

### ISSUE THREAD

**Issue by kyhong222** [pjsip/pjproject#3228]
### Describe the bug

hello

i'm using pjsua2 latest with swig on m1 mac mini

i followed these steps,

1. install pjproject
2. swig it with this script
`swig -c++ -go -cgo -intgosize 64 \
     -outcurrentdir \
     -I/usr/local/include \
     /root/pjproject/pjsip-apps/src/swig/pjsua2.i`
3. go build

but after build command, i got error logs
`/usr/local/go/pkg/tool/darwin_arm64/link: running clang++ failed: exit status 1
ld: library not found for -lpjsua2-x86_64-apple-darwin20.3.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

what should i do?

### Steps to reproduce

1. move to pjproject, execute configure, make dep, make clean, make, make prefix=../libs/libpjsip install
2. swig it with this script
`swig -c++ -go -cgo -intgosize 64 \
     -outcurrentdir \
     -I/usr/local/include \
     /root/pjproject/pjsip-apps/src/swig/pjsua2.i`
3. go build
4. error occured

### PJSIP version

2.12 (latest)

### Context

this issue happened on m1(mac mini)

### Log, call stack, etc

```shell
$ go build
# vgua
/usr/local/go/pkg/tool/darwin_arm64/link: running clang++ failed: exit status 1
ld: library not found for -lpjsua2-x86_64-apple-darwin20.3.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by sauwming** [comment]
You can follow the standard build procedure instead as described in https://docs.pjsip.org
