### ISSUE TITLE
Xcode building error

### ISSUE THREAD

**Issue by elfortitude** [pjsip/pjproject#3232]
### Describe the bug

I write a framework with pjsip static libraries and Swift wrapper. When I try to build it I get some errors:

Declaration of 'jmp_buf' must be imported from module 'Darwin.C.setjmp' before it is required (in file: pj/compat/setjmp.h)
Could not build module CoreFoundation
Could not build module Foundation
Could not build module UIKit
Could not build module CoreGraphics

### Steps to reproduce

I have a modulemap with description of pjsip module, but it can't compile Foundation library. It worked before, but not now( It happened sometimes before yet. Idk(

There is the same problem:
https://developer.apple.com/forums/thread/132878
I'm not only one.

### PJSIP version

2.11.1

### Context

Related third-party lib: OpenSSL 1.1.1d
Xcode 13.4.1

### Log, call stack, etc

```shell
Declaration of 'jmp_buf' must be imported from module 'Darwin.C.setjmp' before it is required
Could not build module CoreFoundation
Could not build module Foundation
Could not build module UIKit
Could not build module CoreGraphics
```

**Comment by sauwming** [comment]
Let us know if there's anything to be fixed inside PJSIP itself.
