### ISSUE TITLE
配置ICE 不生效

### ISSUE THREAD

**Issue by xuan6zm** [pjsip/pjproject#3240]
### Describe the bug

Assertion failed: (cfg->ioqueue && cfg->pf && cfg->timer_heap && cfg->rto_msec && cfg->res_cache_msec), function pj_stun_config_check_valid, file stun_config.h, line 122.

### Steps to reproduce

    pj_ice_strans_cfg ice_Cfg;
    pj_ice_strans_cfg_default(&ice_Cfg);
    

    pj_status_t status_ice =  pj_ice_strans_create(NULL, &ice_Cfg, 1, NULL,
                  &on_ice_complete, NULL);

    if (status_ice != PJ_SUCCESS) {

            NSLog(@"ice 失败了 %d",status_ice);

        }else{

            NSLog(@"ice 成功");
        }

### PJSIP version

2.12.1

### Context

iPhone 6 Plus

### Log, call stack, etc

```shell
Assertion failed: (cfg->ioqueue && cfg->pf && cfg->timer_heap && cfg->rto_msec && cfg->res_cache_msec), function pj_stun_config_check_valid, file stun_config.h, line 122.
```
如下配置也不生效
  cfg.ice_cfg.ice_always_update = YES;
  cfg.ice_cfg.enable_ice = YES;

**Comment by jimying** [comment]
The assert log is clearly

in pj_ice_strans_cfg.stun_cfg
the ioqueue,pf,timer_heap must not NULL

**Comment by xuan6zm** [comment]
pj_ice_strans_cfg_default(&ice_Cfg);这个地方已经初始化了，应该是有值的；我不太清楚这些值我在哪里可以拿到？
还有一个问题，我在设置了启用ICE :
cfg.ice_cfg.ice_always_update = YES;
cfg.ice_cfg.enable_ice = YES;
在信令中未发现sip.ice相关信息。是我设置错了吗，还是需要其他辅助方法

**Comment by xuan6zm** [comment]
很高兴收到您的回复，现在我还有点不明白，还希望您能指点一下
> pj_ice_strans_cfg_default(&ice_Cfg);这个地方已经初始化了，应该是有值的；我不太清楚这些值我在哪里可以拿到？
> 还有一个问题，我在设置了启用ICE :
> cfg.ice_cfg.ice_always_update = YES;
> cfg.ice_cfg.enable_ice = YES;
> 在信令中未发现sip.ice相关信息。是我设置错了吗，还是需要其他辅助方法

**Comment by jimying** [comment]
There is a sample in pjproject,   [icedemo.c](https://github.com/pjsip/pjproject/blob/master/pjsip-apps/src/samples/icedemo.c)

**Comment by xuan6zm** [comment]
谢谢，问题解决了
那个设置ICE ，要在 pjsua_media_config media_cfg;里面设置
我在用户里面设置是不管用的！
