### ISSUE TITLE
reset calls from java

### ISSUE THREAD

**Issue by 3achour007** [pjsip/pjproject#3244]
### Describe the bug

I would like to know how can I reset the calls count from java pls

### Steps to reproduce

Here's the method in java

if (ci.getState() == pjsip_inv_state.PJSIP_INV_STATE_DISCONNECTED) {
            currentCall.delete();
            currentCall=null;
}

### PJSIP version

2.12.1

### Context

Issue happened on Ubuntu 20.04
IntelliJ as IDE
Compiled with 400 max calls
app for pc not android
openjdk 17

### Log, call stack, etc

```shell
No log to provide as I have no error
```

**Comment by sauwming** [comment]
You can't abruptly reset call count. What you can do is either delete the call (as you have done) or hang it up and wait until the hangup process completes, and then the call will be removed.

Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
