### ISSUE TITLE
Undocumented TELNET/CLI command speakertog

### ISSUE THREAD

**Issue by SebaLedesma** [pjsip/pjproject#3247]
### Describe the bug

At https://trac.pjsip.org/repos/wiki/PJSUA-CLI the subcommand audio speakertog it's not documented.
Accoding to the source code [/pjsip-apps/src/pjsua/pjsua_app_cli.c](https://github.com/pjsip/pjproject/blob/master/pjsip-apps/src/pjsua/pjsua_app_cli.c) it changes the routing from PJMEDIA_AUD_DEV_ROUTE_LOUDSPEAKER to PJMEDIA_AUD_DEV_ROUTE_DEFAULT and viceversa.

### Steps to reproduce

open a telnect connection with pjsua and enter:
audio speakertog
it will execute the command. No error will be reported as the command it's recognized but it's not listed in the documentation of the CLI interface.

### PJSIP version

2.12.1

### Context

Linux/Windows/OSX/all

### Log, call stack, etc

```shell
MyTest01> audio speakertog
16:18:49.460            pjsua_aud.c !Opening sound device to get initial settings
16:18:49.460            pjsua_aud.c  Set sound device: capture=-3, playback=-3, mode=0
16:18:49.460            pjsua_aud.c  .No sound device, mode setting is ignored
16:18:49.460        pjsua_app_cli.c  Warning: unable to retrieve route setting: Invalid or unsupported audio capability (PJMEDIA_EAUD_INVCAP)
16:18:49.460        pjsua_app_cli.c  Setting output route to loudspeaker anyway
16:18:49.460        pjsua_app_cli.c  Result: Success
```

**Comment by sauwming** [comment]
Fixed in https://docs.pjsip.org/en/latest/specific-guides/other/cli_cmd.html
