### ISSUE TITLE
Add "audio quality" to the TELNET/CLI interface

### ISSUE THREAD

**Issue by SebaLedesma** [pjsip/pjproject#3248]
In pjsua I want to change the --quality param without re-start. So the next call can use an updated value of the quality.

This can be done by adding the subcommand 'quality' to pjsua_app_cli.c.

This is specially important for codec that accept several types of quality, ie opus / speex.

**Comment by sauwming** [comment]
Currently we don't have any plan to add the command. Please feel free to submit a PR if you happen to have a chance to implement it.
