### ISSUE TITLE
while working as an UAS in TLS, the UAS dosen't respond Client Hello

### ISSUE THREAD

**Issue by MileWay** [pjsip/pjproject#3254]
### Describe the bug

Use pjsip-apps/bin/pjsua-x86_64-unknown-linux-gnu to make an UAS with the following config:

### Steps to reproduce

Use pjsip-apps/bin/pjsua-x86_64-unknown-linux-gnu to make an UAS with the following config:

Peer Tom's config:

--log-file=tom_pjsip.log
--log-level=6
--bound-addr=192.168.56.103
--local-port=7160
--no-udp
--id=sip:tom@192.168.56.103:7161;transport=TLS
--realm=*
--username=tom
--password=tompassword
--null-audio
--use-tls
--tls-neg-timeout
--tls-verify-client
--tls-verify-server
--tls-ca-file=ca-certificates.crt
--tls-cert-file=client.crt
--tls-privkey-file=private.key.pem

Peer Jack's config:

--log-file=jack_pjsip.log
--log-level=6
--bound-addr=192.168.56.200
--local-port=6160
--no-udp
--id=sip:jack@192.168.56.200:6161;transport=TLS
--realm=*
--username=jack
--password=jackpassword
--null-audio
--use-tls
--tls-neg-timeout
--tls-verify-client
--tls-verify-server
--tls-ca-file=ca-certificates.crt
--tls-cert-file=client.crt
--tls-privkey-file=private.key.pem

UAS Tom: ./pjsua-x86_64-unknown-linux-gnu --config-file tom.cfg
UAS Jack: ./pjsua-x86_64-unknown-linux-gnu --config-file jack.cfg "sip:tom@192.168.56.103:7161;transport=TLS"
To make a call from jack to tom, we can see there's a TLS Client Hello to tom, without TLS Server Hello from tom
I found that this is OK when pjsip uses GnuTLS, but failed when uses OpenSSL

### PJSIP version

the latest, b9a947791346e3132cb647f7b3479a9674c67c42

### Context

I've tested Ubuntu 18.04 with OpenSSL 1.1.1 and Win10 with OpenSSL 3.0

### Log, call stack, etc

```shell
Client:
>>> 13:38:37.921        ssl_sock_ossl.c !OpenSSL version : 1010100f
13:38:37.927      ssl0x55d8df6ae260  CA certificates loaded from 'ca-certificates.crt'
13:38:37.927      ssl0x55d8df6ae260  Certificate chain loaded from 'client.crt'
13:38:37.927      ssl0x55d8df6ae260  Private key loaded from 'private.key.pem'
13:38:37.934      ssl0x55d8df6ae260  CA certificates loaded from ca-certificates.crt
13:38:37.939      ssl0x55d8df6b20a0  CA certificates loaded from 'ca-certificates.crt'
13:38:37.939      ssl0x55d8df6b20a0  Certificate chain loaded from 'client.crt'
13:38:37.939      ssl0x55d8df6b20a0  Private key loaded from 'private.key.pem'
13:38:37.952      ssl0x55d8df6b6bb0  CA certificates loaded from 'ca-certificates.crt'
13:38:37.952      ssl0x55d8df6b6bb0  Certificate chain loaded from 'client.crt'
13:38:37.952      ssl0x55d8df6b6bb0  Private key loaded from 'private.key.pem'
13:38:38.911            pjsua_aud.c  Closing sound device after idle for 1 second(s)
13:38:38.911            pjsua_app.c  .Turning sound device -99 -99 OFF
13:38:38.911            pjsua_aud.c  .Closing null sound device..
13:39:09.928          pjsua_media.c  ....Call 0: deinitializing media..
13:39:09.928          pjsua_media.c  .....
  [DISCONNCTD] To: sip:jack@192.168.56.200
    Call time: 00h:00m:00s, 1st res in 32018 ms, conn in 0ms
13:39:09.928          pjsua_media.c  .....Call 0: cleaning up provisional media, prov_med_cnt=1, med_cnt=0
13:39:09.928      udp0x55d8df6b95f0  .....UDP media transport destroyed
13:39:09.928            pjsua_app.c  ....Call 0 is DISCONNECTED [reason=408 (Request Timeout)]
13:39:10.931     tlsc0x55d8df6b7e08  TLS transport destroyed normally
13:39:10.931      ssl0x7fcaec000d30  Handshake failed in accepting 192.168.56.103:51247: End of file (PJ_EEOF)

Server:
>>> 13:38:37.834 ssl_sock_ossl.  OpenSSL version : 101010e0
13:38:37.857 ssl000001E7AF9 !CA certificates loaded from 'ca-certificates.crt'
13:38:37.859 ssl000001E7AF9  Certificate chain loaded from 'client.crt'
13:38:37.860 ssl000001E7AF9  Private key loaded from 'private.key.pem'
13:38:37.878 ssl000001E7AF9 !CA certificates loaded from ca-certificates.crt
```

**Comment by MileWay** [comment]
@sauwming Would you mind to help ?

**Comment by pekkaar** [comment]
Hi, the context of this issue is pretty similar to this other problem: https://github.com/pjsip/pjproject/issues/2706
Where PJSIP is acting up when it is the UAS in a TLS trunk and wants to disconnect -- it can not send the BYE in such cases, however it works fine when acting as UAC in the same trunk.

Something is fishy with PJSIP UAS operation on TLS.

**Comment by sauwming** [comment]
It worked fine here.
[tls1.txt](https://github.com/pjsip/pjproject/files/10809626/tls1.txt)
[tls2.txt](https://github.com/pjsip/pjproject/files/10809627/tls2.txt)

Run: `./pjsua --conf=tls1.txt` and `./pjsua --conf=tls2.txt`

Result:
```
09:44:46.853        ssl_sock_ossl.c  ..OpenSSL version : 30000070
09:44:53.053         ssl0x153f2a5d0 !CA certificates loaded from 'rootCA.crt'
09:44:53.053         ssl0x153f2a5d0 !Certificate chain loaded from 'domain.crt'
09:44:53.054         ssl0x153f2a5d0  Private key loaded from 'domain.key'
09:44:53.055         ssl0x153f2a5d0  SSL DH initialized, PFS cipher-suites enabled
09:44:53.062            pjsua_app.c  TLS cipher used: 0x00C030/ECDHE-RSA-AES256-GCM-SHA384
09:44:53.062            pjsua_app.c  TLS cert info of 192.168.1.5:6161:
  Version    : v1
  Serial     : 7A D7 67 F5 FE 72 6B 31 70 6D 87 30 16 AE C9 AE B2 A8 AB DA
  Subject    : ming
  Issuer     : ming
  Valid from : Mon 2022-01-17 12:24:19.000 GMT
  Valid to   : Thu 2032-01-15 12:24:19.000 GMT

09:44:53.061            pjsua_app.c  TLS cert verification result of 192.168.1.5:62038:
...
```
