### ISSUE TITLE
Correct IP interface to be placed in the SDP connection line

### ISSUE THREAD

**Issue by half-left** [pjsip/pjproject#3269]
**Describe the problem.**
My PC has 2 network interfaces. I launch UA, add UDP transport with default transport config(obtained with `pjsua_transport_config_default()`) and account without registration with default rtp_cfg.
The problem is to get suitable host address in sdp connection line. [pj_gethostip()](https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua-lib/pjsua_media.c#L506) is used regardless of the destination address. Some UA may be confused with inaccessible rtp address.

**Describe the solution you'd like**
I suppose `pjsip_tpmgr_find_local_addr2()` may be used to obtain host address for connection line in sdp

**Describe alternatives you've considered**
Give me advice what should i do to get it worked

**Comment by half-left** [comment]
Is my solution correct? I can try to fix it. There is a problem: [create_rtp_rtcp_sock](https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua-lib/pjsua_media.c#L254) has not memory pool in args. It's nessesary for `pjsip_tpmgr_find_local_addr2()`. Through call_med->call->inv we have access to pjsip_inv_session, wich has `pool`, `pool_prov` and `pool_active`. Please tell what pool should be used?

**Comment by sauwming** [comment]
You can set the address in `rtp_cfg`, instead of leaving it at default value.

Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.

**Comment by half-left** [comment]
So, if i need to use booth network interfaces i should add two accounts with the same username and different rtp_cfg. I think it's unnecessary complication and it has already solved for SIP messages.

**Comment by sauwming** [comment]
Alternatively, you can use one account, decide which interface you want to use, and call `pjsua_acc_modify()`. The choice is up to you.

Or you can enable ICE, which will list both host addresses as candidates.
