### ISSUE TITLE
pjsua crash when --jb-max-size=20 or more

### ISSUE THREAD

**Issue by SebaLedesma** [pjsip/pjproject#3271]
### Describe the bug

I'm trying to increase the jitter buffer, but when pjsua.conf contains:
--jb-max-size 20 
the application will crash when accepting a call.
Values less than 20 works fine.
The crash is due an ASSERT at pjmedia/src/pjmedia/jbuf.c, around line 672 the function:
pjmedia_jbuf_set_adaptive will trigger the assert as  min_prefetch <= max_prefetch returns false.
min_prefetch has the value of 1 while max_prefetch = 0.

The error originates at pjmedia/src/pjmedia/stream.c, at function pjmedia_stream_create
```
 if (info->jb_min_pre >= stream->codec_param.info.frm_ptime)
        jb_min_pre = info->jb_min_pre / stream->codec_param.info.frm_ptime;
    else
        //jb_min_pre = 60 / stream->codec_param.info.frm_ptime;
        jb_min_pre = 1;
```
This will be evaluated as false, so jb_min_pre  will receive 1 as value.

```
  if (info->jb_max_pre >= stream->codec_param.info.frm_ptime)
        jb_max_pre = info->jb_max_pre / stream->codec_param.info.frm_ptime;
    else {
        //jb_max_pre = 240 / stream->codec_param.info.frm_ptime;
        jb_max_pre = jb_max * 4 / 5;
    }
```
Also will be evaluated as false, but it will assing jb_max_pre = jb_max * 4 / 5;
As jb_max has the value of 1, then jb_max_pre will receive 0.

Suggested fix (I wll try to make a PR if everythings ok)
```
    if (info->jb_max_pre >= stream->codec_param.info.frm_ptime)
        jb_max_pre = info->jb_max_pre / stream->codec_param.info.frm_ptime;
    else {
        //jb_max_pre = 240 / stream->codec_param.info.frm_ptime;
        jb_max_pre = jb_max * 4 / 5;
        if  (jb_max_pre<jb_min_pre)
             jb_max_pre=jb_min_pre;
    }
```

### Steps to reproduce

Set/add into pjsua.conf 
--jb-max-size 20 

and then run
pjsua --config-file=pjsua.conf 

it will crash when a call it's accepted

### PJSIP version

2.12.1 

### Context

Tested on Linux but it should also fail on Windows, OSX, etc

### Log, call stack, etc

```shell
.
```

**Comment by sauwming** [comment]
Setting jitter buffer size to only one frame seems rather extreme.
And since `jb_max_pre` is specified to be 80% of jb_max, the calculation seems okay.
So I prefer the fix to be:
`jb_max_pre = max(1, jb_max * 4 / 5);`

Alternatively, I would suggest to fix the sample app instead, i.e. to put some validation and reject such value.

**Comment by SebaLedesma** [comment]
I've studied a little more the code and as I see there is a bug in the logic that calculates **jb_max**.
According to the manual of pjsua ( https://www.pjsip.org/pjsua.htm ) this value it's expressed in count of frames
  --jb-max-size       Specify jitter buffer maximum size, in frames (default=-1)
  
  So around lines 2279 ( https://github.com/chakrit/pjsip/blob/master/pjmedia/src/pjmedia/stream.c#L2219 ) jb_max it's calculated according this expression:
```
  /* Init jitter buffer parameters: */
    if (info->jb_max >= stream->codec_param.info.frm_ptime)
	jb_max = (info->jb_max + stream->codec_param.info.frm_ptime - 1) /
		 stream->codec_param.info.frm_ptime;
    else
	jb_max = 500 / stream->codec_param.info.frm_ptime;
```
so, the 'if' it's comparing a count vs milliseconds. It should be bytes vs bytes or milliseconds vs milliseconds, but not a count of frames vs the large in time of a frame.
Normally this expression it's false. ie: in opus and speex@32000  the frame duration it's 20ms, so any value of info->jb_max less than 20 will result in a jb_max of 500 / stream->codec_param.info.frm_ptime; (in our example 20).

When trying higher values (I'm trying to connect to a software that has a little to much of jitter) it will crash.

**Comment by SebaLedesma** [comment]
Ok, I've did a BLAME on the source and analyzed the ticket #730 and the associated commit https://github.com/pjsip/pjproject/commit/7c3659f39db4e9fd098c90064642706809a2fcd2
So udpate in the issue:
1 - info->jb_max it's expressed in mseconds, so the if it's correct. However it will crash if the value it's betwen stream->codec_param.info.frm_ptime and stream->codec_param.info.frm_ptime*2.
2 - the user manual it's wrong/outdated, it say that this value it's defined in frames ( https://www.pjsip.org/pjsua.htm ) but it should say that's defined in milliseconds.

**Comment by sauwming** [comment]
Thanks for your help tracing back the source of the problem.

You're right, the user manual is incorrect (point 2), it should be in msec.
I don't understand though why the crash would happen in point 1. I tried making a call here with `--jb-max-size=x` with x=[21,39] (ptime 20 ms) and it's fine.

**Comment by SebaLedesma** [comment]
Hi! Trying not to be pedantic here:
At stream_create (stream.c), when info->jb_max has the same value than stream->codec_param.info.frm_ptime (for example 20 ms)
then     if (info->jb_max >= stream->codec_param.info.frm_ptime)
will be evaluated as true and jb_max will be calculated as:
jb_max = (20 + 20 - 1) / 20 = 1.95 -> 1 (as we are using integer division).

info->jb_min_pre has the initial value of -1, so it will receive directly:
jb_min_pre =1;

and finally info->jb_max_pre also has the initial value of -1, (original 2.12.1 code) so:
jb_max_pre = jb_max * 4 /5 = 1 * 4/5 -> 0

So far everything seems ok, but when calling pjmedia_jbuf_set_adaptive at jbuf.c
the ASSERT will be triggered as  jb_min_pre doesnt comply to be less or equal than  jb_max_pre
and the application will be closed.

In a Release built the ASSERT will be dissapear and pjsua wont crash (I've didnt analyzed the behaviour of the allocations and so). 

By changing the formula of jb_max_pre to:
   if (info->jb_max_pre >= stream->codec_param.info.frm_ptime)
        jb_max_pre = info->jb_max_pre / stream->codec_param.info.frm_ptime;
    else {
        //jb_max_pre = 240 / stream->codec_param.info.frm_ptime;
        int aux =  jb_max * 4 / 5;
        jb_max_pre = aux > 1 ? aux : 1; //perhaps we can use a bigger value like 2..4 blocks/frames 
    }
the crash/ASSERT will be avoided.

**Comment by sauwming** [comment]
Yes, it only happens when `info->jb_max == stream->codec_param.info.frm_ptime`, and the fix `jb_max_pre = max(1, jb_max * 4 / 5)` looks okay, at least for me. Do you want to create a PR for this?
