### ISSUE TITLE
Pjsua does not cancel the call in EARLY state on incorrect SDP

### ISSUE THREAD

**Issue by vasilevalex** [pjsip/pjproject#3287]
### Describe the bug

If pjsua receives SDP offer or answer in EARLY state with completely wrong SDP, it detects the error, but does not cancel the call.
It happens, because `inv_on_state_early` calls `inv_check_sdp_in_incoming_msg` and does not check return status. If SDP is completely wrong and it can be detected with `pjmedia_sdp_parse` the call will not be cancelled.

### Steps to reproduce

sips tests attached
[uac-183-wrong-version.py.txt](https://github.com/pjsip/pjproject/files/9952763/uac-183-wrong-version.py.txt)
[uac-183-wrong-version.xml.txt](https://github.com/pjsip/pjproject/files/9952764/uac-183-wrong-version.xml.txt)
[uas-answer-183-wrong-attr.py.txt](https://github.com/pjsip/pjproject/files/9952766/uas-answer-183-wrong-attr.py.txt)
[uas-answer-183-wrong-attr.xml.txt](https://github.com/pjsip/pjproject/files/9952767/uas-answer-183-wrong-attr.xml.txt)
[uas-answer-183-wrong-version.py.txt](https://github.com/pjsip/pjproject/files/9952769/uas-answer-183-wrong-version.py.txt)
[uas-answer-183-wrong-version.xml.txt](https://github.com/pjsip/pjproject/files/9952770/uas-answer-183-wrong-version.xml.txt)

### PJSIP version

all

### Context

standard build on Rocky 8.

### Log, call stack, etc

```shell
pjsua0: 15:44:58.608           pjsua_call.c  .Incoming Request msg INVITE/cseq=1 (rdata0x1115c58)
pjsua0: 15:44:58.609                  sdp.c  ..Error parsing SDP in line 1 col 0: Invalid SDP version line (PJMEDIA_SDP_EINVER)
pjsua0: 15:44:58.609              sip_inv.c  ..Error parsing/validating SDP body: Invalid SDP version line (PJMEDIA_SDP_EINVER)
pjsua0: 15:44:58.609           pjsua_call.c  ..Bad SDP in incoming INVITE: Invalid SDP version line (PJMEDIA_SDP_EINVER) [status=220021]
pjsua0: 15:44:58.609           pjsua_core.c  ...TX 361 bytes Response msg 400/INVITE/cseq=1 (tdta0x7f03c8003b68) to UDP 127.0.0.1:50070:

pjsua0: 15:48:46.474            pjsua_app.c  .....Call 0 state changed to EARLY (183 Session Progress)
pjsua0: 15:48:46.474                  sdp.c  ....Error parsing SDP in line 1 col 0: Invalid SDP version line (PJMEDIA_SDP_EINVER)
pjsua0: 15:48:46.474              sip_inv.c  ....Error parsing/validating SDP body: Invalid SDP version line (PJMEDIA_SDP_EINVER)
pjsua0: 15:48:46.474              sip_inv.c  ....Error parsing SDP in Response msg 183/INVITE/cseq=2499 (rdata0x7fc3f8000b88): Invalid SDP version line (PJMEDIA_SDP_EINVER)
pjsua0: 15:48:48.474           pjsua_core.c  .RX 582 bytes Response msg 183/INVITE/cseq=2499 (rdata0x7fc3f8000b88) from UDP 127.0.0.1:50070:
```

**Comment by sauwming** [comment]
I can't find the recommendation in the RFC for this.

But in my opinion, since the error happens in a provisional response, there is still a chance that the subsequent response(s) (either provisional or final one) is valid and the call may successfully go through. So cancelling it right away seems rather harsh.

**Comment by vasilevalex** [comment]
Sorry, I didn't describe the issue properly. The issue is the pjsua behavior is different in similar scenarios.
1) For example, you can check 2 tests `uac-183-wrong-codec` and `uac-183-wrong-media` (they are already in the master) and compare with attached one `uac-183-wrong-version`. Normal behavior: pjsua receives INVITE with SDP, that it can't process and answers `488 Not Acceptable Here`. But in the last case, pjsua answers with `400 Bad SDP`, receives ACK, and continues sending `400 Bad SDP`, not dropping the call. This looks like wrong behavior.
2) Please check `uas-answer-183-wrong-codec` and `uas-answer-183-wrong-media` (they are in the master) and compare with attached `uas-answer-183-wrong-attr`, `uas-answer-183-wrong-version`. In first 2 tests pjsua sends INVITE, got 183 with problematic SDP, the call is cancelled by pjsua. But in the case of attached tests, pjsua receives 183 Session Progress with wrong SDP and just keeps silence. 
Maybe cancelling is not perfect in EARLY, but what can happen? After 183 with SDP pjsua can get only 200 OK with the same SDP or without SDP at all, so remote UAS is evil, because it sent SDP answer incompatible with SDP offer. Correct behavior is UAS responds with 488. So cancelling call as fast as possible looks like not so bad idea.
Anyway, I think, the behavior should be consistent in similar scenarios.
