### ISSUE TITLE
Get 'Reason' header inside a CANCEL message

### ISSUE THREAD

**Issue by marcocapetta** [pjsip/pjproject#3295]
We have an iOS client that uses pjsip.
We need to detect and check the "Reason" header inside a CANCEL message to differentiate a normal cancelled call from a call answered by another user. In fact in the second case I get the additional header Reason: SIP;cause=200;text=“Call completed elsewhere”

We have looked in to
      void (*on_call_tsx_state)(pjsua_call_id call_id, pjsip_transaction *tsx, pjsip_event *e);
and
      void (*on_call_state)(pjsua_call_id call_id, pjsip_event *e);
In the pjsip_event and in to pjsip_transaction but we could not find text=“Call completed elsewhere”

Is this feature already available in pjsip?
If yes, can you please suggest how to implement it?

Thanks

**Comment by marcocapetta** [comment]
Hi All,

it would be very important for us to get a feedback on this issue, in order to understand if we have to develop something on our own, or if everything can be already implemented using pjsip standard library.

Thank you

**Comment by sauwming** [comment]
You can use `on_call_tsx_state()`:
``` 
if (e && e->type == PJSIP_EVENT_TSX_STATE &&
    e->body.tsx_state.type == PJSIP_EVENT_RX_MSG)
{
    pjsip_msg *msg = e->body.tsx_state.src.rdata->msg_info.msg;
    if (msg && pjsip_method_cmp(&msg->line.req.method,
                                &pjsip_cancel_method) == 0)
    {
        pj_str_t reason = pj_str("Reason");
        pjsip_hdr *hdr = pjsip_msg_find_hdr_by_name(msg, &reason, NULL);
```

Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
