### ISSUE TITLE
Deadlock while performing pjmedia_clock_stop

### ISSUE THREAD

**Issue by bjptwist** [pjsip/pjproject#3298]
### Describe the bug

In **clock_thread.c** file, if **_pjmedia_clock_stop_** is invoked from the clock's own thread, the property **_clock->quitting_** will be set with _PJ_FALSE_ (else clause in the snippet below) making any previous invocation of **_pjmedia_clock_stop_** that's waiting on **_pj_thread_join_**, to become stuck.

```
PJ_DEF(pj_status_t) pjmedia_clock_stop(pjmedia_clock *clock)
{
    PJ_ASSERT_RETURN(clock != NULL, PJ_EINVAL);

    clock->running = PJ_FALSE;
    clock->quitting = PJ_TRUE;

    if (clock->thread) {
	if (pj_thread_join(clock->thread) == PJ_SUCCESS) {
	    pj_thread_destroy(clock->thread);
	    clock->thread = NULL;
	    pj_pool_reset(clock->pool);
	} else {
	    clock->quitting = PJ_FALSE;
	}
    }

    return PJ_SUCCESS;
}
```

### Steps to reproduce

Here are some possible steps that can lead to the deadlock:

1. **_dtls_media_stop_** method (from **transport_srtp_dtls.c**) is invoked
2. as a consequence, the method **_pjmedia_clock_stop_** is also invoked
3. before the while loop in clock's thread (method **_clock_thread_** from **clock_thread.c**) ends:
```
while (!clock->quitting) {

	pj_get_timestamp(&now);

	/* Wait for the next tick to happen */
	if (now.u64 < clock->next_tick.u64) {
	    unsigned msec;
	    msec = pj_elapsed_msec(&now, &clock->next_tick);
	    pj_thread_sleep(msec);
	}

	/* Skip if not running */
	if (!clock->running) {
	    /* Calculate next tick */
	    clock_calc_next_tick(clock, &now);
	    continue;
	}

       ...
    }
```
4. another invocation of **_pjmedia_clock_stop_** is triggered, this time from method  **_ssl_flush_wbio_** (**transport_srtp_dtls.c**)
5. this second invocation of **_pjmedia_clock_stop_** sets **_clock->quitting_** to PJ_FALSE and immediately returns
6. the clock's thread keeps running
7. the waiting thread from the first invocation of **_pjmedia_clock_stop_** (triggered within **_dtls_media_stop_**) never returns 

### PJSIP version

2.12.1

### Context

This was testes on Android and iOS devices.

### Log, call stack, etc

```shell
Given the description and the steps to reproduce described above I think logs are not relevant here.
```

**Comment by bjptwist** [comment]
My proposal for the fix is adding the following validation to the **_pjmedia_clock_stop_** method:

```
PJ_DEF(pj_status_t) pjmedia_clock_stop(pjmedia_clock *clock)
{
    PJ_ASSERT_RETURN(clock != NULL, PJ_EINVAL);

    if (clock->quitting)
    return PJ_SUCCESS;

   ...   
```

I've also attached a patch file with the modification.
[fix.txt](https://github.com/pjsip/pjproject/files/10115433/fix.txt)

**Comment by sauwming** [comment]
Thanks for the detailed analysis.

Am I correct to assume that `ssl_flush_wbio()` in step 4 is called from `clock_cb()`? If yes, then I suppose it's better to prevent the call to `pjmedia_clock_stop()` (patch attached).
[dlts_clock_race.txt](https://github.com/pjsip/pjproject/files/10119387/dlts_clock_race.txt)

As for your proposed fix, it looks interesting indeed and can probably handle general race problem to `pjmedia_clock_stop()` but I believe we'll need `pj_atomic_t` instead of simple integer.

**Comment by bjptwist** [comment]
`ssl_flush_wbio()` is indeed being called by `ssl_on_recv_packet()`. My proposal is a more generic one like you said. I think it would be better to do the fix in the clock_thread since it can be used by other modules later on instead of limiting the fix to the **transport_srtp_dtls.c** file.

I agree with you that my patch must use an atomic instead. 
Also speaking of concurrency, can you clarify what's the purpose of `pj_lock_acquire(clock->lock)` being invoked within `clock_thread()` method, since we don't have any other call to `pj_lock_acquire(clock->lock)` elsewhere within this file?

**Comment by sauwming** [comment]
After rechecking the code and #3299, I believe the fix can be to simply remove the line `clock->quitting = PJ_FALSE`:
```
    if (clock->thread) {
        if (pj_thread_join(clock->thread) == PJ_SUCCESS) {
             ....
        } else {
            // clock->quitting = PJ_FALSE;
            return PJ_EBUSY;
        }
```

Let me know if it works.

**Comment by sauwming** [comment]
Forgot to answer your question. The lock is just a null mutex:
https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia/clock_thread.c#L189

**Comment by bjptwist** [comment]
Your proposal works and seems to be more clean and simple than mine :).

Regarding the mutex question, based on your response, it seems the invocations to lock/unlock the mutex could be removed right? It's a bit strange having mutexes being locked immediately before invoking external callbacks when there is not absolutely necessary.

**Comment by sauwming** [comment]
Thanks for the feedback. I have created PR #3304 for this. 

As for the mutex, yes, it can be removed, but since it's a no-op currently, we'll just leave it as it is. Perhaps we need it in the future.
