### ISSUE TITLE
jack server is not running or cannot be started

### ISSUE THREAD

**Issue by amitleiba** [pjsip/pjproject#3307]
### Describe the bug

Hello,

I tried many different settings but I definitely cannot get jack to be started with pjsip (pjsua2).

this is what I got when I tried to run libInit on Endpoint.

this is the code:

```
#include <pjsua2.hpp>
#include<iostream>

int main()
{
    pj::Endpoint *ep = new pj::Endpoint;
    try {
        ep->libCreate();
    } catch(pj::Error& err) {
        std::cout << "Startup error: " << err.info() << std::endl;
    }
    try {
    pj::EpConfig ep_cfg;
    // Specify customization of settings in ep_cfg
    ep->libInit(ep_cfg);
    }   catch(pj::Error& err) {
        std::cout << "Initialization error: " << err.info() << std::endl;
    }
}
```
this is the log

> 21:45:50.786         os_core_unix.c !pjlib 2.12-dev for POSIX initialized
> 21:45:50.786         sip_endpoint.c  .Creating endpoint instance...
> 21:45:50.787                  pjlib  .select() I/O Queue created (0x55cabb842e20)
> 21:45:50.787         sip_endpoint.c  .Module "mod-msg-print" registered
> 21:45:50.787        sip_transport.c  .Transport manager created.
> 21:45:50.787           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
> 21:45:50.787         sip_endpoint.c  .Module "mod-pjsua-log" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-tsx-layer" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-stateful-util" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-ua" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-100rel" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-pjsua" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-invite" registered
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> 21:45:50.898             alsa_dev.c  ..ALSA driver found 26 devices
> 21:45:50.898             alsa_dev.c  ..ALSA initialized
> 21:45:50.898                  pjlib  ..select() I/O Queue created (0x55cabb85f9b8)
> 21:45:50.905         sip_endpoint.c  .Module "mod-evsub" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-presence" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-mwi" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-refer" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-pjsua-pres" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-pjsua-im" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-pjsua-options" registered
> 21:45:50.906           pjsua_core.c  .1 SIP worker threads created
> 21:45:50.906           pjsua_core.c  .pjsua version 2.12-dev for Linux-5.15.0.56/x86_64/glibc-2.35 initialized
> 21:45:50.906           pjsua_core.c  .PJSUA state changed: CREATED --> INIT

makefile
#---QUICK GUIDE---

#In order to initialize the project with the required directories, use 'make init'.
#This command will generate the source and header directories.
#The default values of each variable below may be altered to your preference.
#Editing the internal makefile is at your own risk.

#In order to compile your project, use 'make' or 'make all'

#*****START OF MAKEFILE*****

#---TARGET EXECUTABLE / LIBRARY NAME---

TARGET	:=	app

#---AUTO GENERATED DIRECTORIES

SRC_DIR	:=	src
INC_DIR	:=	include
OBJ_DIR	:=	build
BIN_DIR	:=	bin

#---FILE EXTENSIONS---

OBJ_EXT	:=	o
DEP_EXT	:=	d
SRC_EXT	:=	cpp

#---COMPILER---

CC	:=	g++

#*****START OF USER DATA*****

PJSIP := /home/amit/Documents/Libaries/pjproject/
include $(PJSIP)/build.mak

#*****END OF USER DATA*****

#*****START OF FLAGS*****

#---WARNING FLAGS--- (-W<flag name>)

WFLAGS	:=

#---COMPILER FLAGS--- (-I<include path>, Example: -I/usr/local/include)

CFLAGS := -I$(INC_DIR) $(PJ_CXXFLAGS)

#---LINKER FLAGS--- (-L<library path>, Example: -L/usr/local/lib)

LDFLAGS := $(PJ_LDXXFLAGS)

#---LIBRARIES--- (-l<lib name>, Example: -lPcap++, -lmongocxx.so)

LDLIBS := $(PJ_LDXXLIBS) `pkg-config --libs libpjproject`

#*****END OF FLAGS*****

#*****START OF INTERNAL MAKEFILE*****

COMPILE	:=	-c
OUTPUT	:=	-o

#---RECURSIVE WILDCARD FUNCTION---

recursive_wildcard=$(foreach d,$(wildcard $(1:=/*)),$(call recursive_wildcard,$d,$2,)	$(filter $(subst *,%,$2),$d))

#---GETTING ALL SOURCE FILES USING THE RECURSIVE WILDCARD FUNCTION---

SRCS	:=	$(call recursive_wildcard,$(SRC_DIR),*.$(SRC_EXT))
OBJS	:=	$(patsubst $(SRC_DIR)/%,$(OBJ_DIR)/%.$(OBJ_EXT),$(basename $(SRCS)))
DEPS	:=	$(patsubst $(SRC_DIR)/%,$(OBJ_DIR)/%.$(DEP_EXT),$(basename $(SRCS)))

GENERATED_DIRS	:=	$(OBJ_DIR)	$(BIN_DIR)

#---DEPENDENCY FLAGS---

DEPFLAGS	:=	-MMD	-MP

#---COMPILE & BUILD RULE---

.PHONY: all
all:	$(SRCS)	$(GENERATED_DIRS)	$(TARGET)

#---INIT RULE---

.PHONY: init
init:
	@echo "Building source directory: $(SRC_DIR)"
	@mkdir	$(SRC_DIR)
	@echo "Building include directory: $(INC_DIR)"
	@mkdir	$(INC_DIR)
	@echo "Created base directories!"

#---OUTPUT DIRECTORIES CREATION RULE---

$(GENERATED_DIRS):
	@mkdir $@

#---LINK RULE---

$(TARGET):	$(OBJS)
	@echo "Building target: $(BIN_DIR)/$@"
	@$(CC)	$(WFLAGS)	$(LDFLAGS) $^ $(OUTPUT) $(BIN_DIR)/$@ $(LDLIBS)
	@echo "Done!"

.PRECIOUS:	$(OBJ_DIR)/.	$(OBJ_DIR)%/.

$(OBJ_DIR)/.:
	@mkdir -p $@

$(OBJ_DIR)%/.:
	@mkdir -p $@	

.SECONDEXPANSION:

#---COMPILE RULE---

$(OBJ_DIR)/%.$(OBJ_EXT):	$(SRC_DIR)/%.$(SRC_EXT) | $$(@D)/.
	@echo "Building file: $@"
	@$(CC)	$(WFLAGS)	$(DEPFLAGS)	$(CFLAGS)	$(COMPILE)	$< $(OUTPUT)	$@

#---CLEAN RULE---

clean:
	@echo "Cleaning.."
	$(foreach dir,$(GENERATED_DIRS),@rm -rf $(dir))
	@echo "Done!"
-include $(DEPS)

#*****END OF INTERNAL MAKEFILE*****

#*****END OF MAKEFILE*****

### Steps to reproduce

make clean & make
./bin/app

### PJSIP version

2.12.1

### Context

Linux 22.04.1

### Log, call stack, etc

```shell
> 21:45:50.786         os_core_unix.c !pjlib 2.12-dev for POSIX initialized
> 21:45:50.786         sip_endpoint.c  .Creating endpoint instance...
> 21:45:50.787                  pjlib  .select() I/O Queue created (0x55cabb842e20)
> 21:45:50.787         sip_endpoint.c  .Module "mod-msg-print" registered
> 21:45:50.787        sip_transport.c  .Transport manager created.
> 21:45:50.787           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
> 21:45:50.787         sip_endpoint.c  .Module "mod-pjsua-log" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-tsx-layer" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-stateful-util" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-ua" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-100rel" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-pjsua" registered
> 21:45:50.787         sip_endpoint.c  .Module "mod-invite" registered
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
> 21:45:50.898             alsa_dev.c  ..ALSA driver found 26 devices
> 21:45:50.898             alsa_dev.c  ..ALSA initialized
> 21:45:50.898                  pjlib  ..select() I/O Queue created (0x55cabb85f9b8)
> 21:45:50.905         sip_endpoint.c  .Module "mod-evsub" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-presence" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-mwi" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-refer" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-pjsua-pres" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-pjsua-im" registered
> 21:45:50.906         sip_endpoint.c  .Module "mod-pjsua-options" registered
> 21:45:50.906           pjsua_core.c  .1 SIP worker threads created
> 21:45:50.906           pjsua_core.c  .pjsua version 2.12-dev for Linux-5.15.0.56/x86_64/glibc-2.35 initialized
> 21:45:50.906           pjsua_core.c  .PJSUA state changed: CREATED --> INIT
```

**Comment by sauwming** [comment]
So, without pjsip, jack server is running just fine?

It seems that there may be a conflict with the alsa driver.
Unfortunately, I am not familiar with jack to recommend a solution. Googling around, there seems to be some suggestions that you can try, so check it out. If there's anything to be done from PJSIP, please let us know.
