### ISSUE TITLE
AMR compatibility issue

### ISSUE THREAD

**Issue by mscdex** [pjsip/pjproject#3327]
### Describe the bug

We've recently encountered SIP clients that send a currently unsupported AMR fmtp value, which causes the call setup to fail.

Specifically the incoming SDP has:

```
a=rtpmap:113 AMR-WB/16000
a=fmtp:113 mode-change-capability=2
```

but PJSIP only includes in its response:

```
a=rtpmap:113 AMR-WB/16000
```

According to [RFC 4867](https://www.rfc-editor.org/rfc/rfc4867.html), this parameter means:

>       mode-change-capability: Specifies if the client is capable to
>               transmit with a restricted mode change period.  The
>               parameter may take value of 1 or 2.  A value of 1
>               indicates that the client is not capable of restricting
>               the mode change period to 2, and that the codec mode may
>               be changed at any point.  A value of 2 indicates that the
>               client has the capability to restrict the mode change
>               period to 2, and thus that the client can correctly
>               interoperate with a receiver requiring a mode-change-
>               period=2.  If this parameter is not present, the mode-
>               change restriction capability is not supported, i.e.
>               mode-change-capability=1.  To be able to interoperate
>               fully with gateways to circuit switched networks (for
>               example, GSM networks), transmissions with restricted
>               mode changes (mode-change-capability=2) are required.
>               Thus, clients RECOMMENDED to have the capability to
>               support transmission according to
>               mode-change-capability=2.

That explains why the call was unable to be successfully established:

> If this parameter is not present, the mode-change restriction capability is not supported, i.e.
>               mode-change-capability=1.

### Steps to reproduce

Use a SIP client that sends the missing parameter?

### PJSIP version

2.12.1

### Context

I am using the opencore AMR codecs.

### Log, call stack, etc

```shell
n/a
```

**Comment by sauwming** [comment]
In my understanding, `mode-change-capability` is actually just to indicate capability, not a requirement:
```
The mode-change-period will indicate what the offerer or
         answerer requires of data it receives, while the mode-change-
         capability indicates its transmission capabilities.
```
So, the offerer says that it supports mode-change-period of 2, but doesn't require it. Then the answer implies that it wants a period of 1, which is valid. So both should proceed successfully with 1.

**Comment by mscdex** [comment]
Perhaps it's this bit then:

> The mode-change-capability SHOULD be included in answers.

and the remote party is being strict and requiring it be in the answer in order for codecs to match up.

All I know is the call fails and that's the only thing different when comparing the SDPs. The Q.850 code sent in the SIP BYE sent afterward by the remote party has `cause=47`, which is a codec negotiation issue (at least in the Cisco world, which is where this is occurring).

**Comment by sauwming** [comment]
Since there doesn't seem to be anything wrong with the answer, I would suggest to fix the remote.

If that's not possible, a workaround is to modify the SDP (such as via the callback on_call_sdp_created()) and make it compatible with the remote.
