### ISSUE TITLE
在2.13 使用视频通话，打电话预览视频变形，展示模糊

### ISSUE THREAD

**Issue by xuan6zm** [pjsip/pjproject#3328]
### Describe the bug

在打电话前设置设备方向，会有两种场景：
1.打电话开启预览打电话，发出去的视频为变形的;
2.打电话接通后再开启预览，视频正常，远端回传view 会有两个；
问：如何才能保证我开启预览不变形，远端video保持一个View视频

下面是我使用的代码：
下面是我使用的方法：编码：
//设置H264视频编码const pj_str_t codec_id = {"H264", 4};int bitrate_avg；int bitrate_max；pjmedia_vid_codec_param param；pjsua_vid_codec_get_param(&codec_id, &param);param.enc_fmt.det.vid.size.w = 480; //656x656param.enc_fmt.det.vid.size.h = 640;param.enc_fmt.det.vid.fps.num = 25;param.enc_fmt.det.vid.fps.denum = 1;bitrate_avg = 1000 * atoi("512");bitrate_max = 1000 * atoi("1024");param.enc_fmt.det.vid.avg_bps = bitrate_avg;param.enc_fmt.det.vid.max_bps = bitrate_max;// 解码-设为最高预期的想要远方传来的分辨率大小param.dec_fmt.det.vid.size.w = 480;param.dec_fmt.det.vid.size.h = 640;param.dec_fmt.det.vid.fps.num = 25;param.dec_fmt.det.vid.fps.denum = 1;param.dec_fmtp.cnt = 2;param.dec_fmtp.param[0].name = pj_str("profile-level-id");param.dec_fmtp.param[0].val = pj_str("42801F");param.ignore_fmtp = PJ_FALSE;//设置为YES，指定分辨率必须设置此值，否则将双方通信协商

预览：
  pj_bool_t bool_t = pj_thread_is_registered();
    if (!bool_t) {
        pj_thread_desc desc;
        pj_thread_t* thed;
        pj_thread_register(NULL,desc,&thed);
    
    }
    //    //设置设备方向
        pjmedia_orient orient = PJMEDIA_ORIENT_ROTATE_90DEG;
        pjsua_vid_dev_set_setting(PJMEDIA_VID_DEFAULT_CAPTURE_DEV, PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, PJ_TRUE);

 pjsua_vid_win_info wi;
        pjsua_vid_preview_param pre_param;
        pj_status_t status;

        pjsua_vid_preview_param_default(&pre_param);
//        pre_param.rend_id = PJMEDIA_VID_DEFAULT_RENDER_DEV;
        pre_param.wnd_flags = PJMEDIA_VID_DEV_WND_BORDER |
                            PJMEDIA_VID_DEV_WND_RESIZABLE;
        pre_param.show = PJ_TRUE;
        pre_param.format.det.vid.size.w = 0;
        pre_param.format.det.vid.size.h = 0;
        status = pjsua_vid_preview_start(PJMEDIA_VID_DEFAULT_CAPTURE_DEV, &pre_param);
        arrange_window(pjsua_vid_preview_get_win(PJMEDIA_VID_INVALID_DEV));

现在不清楚是哪一步出问题了，还请大佬指点

### Steps to reproduce

预览问题

### PJSIP version

2.13

### Context

手机型号:iphone 6s
手机版本:15.4
pjsip版本:2.13

### Log, call stack, etc

```shell
2023-01-11 10:40:00.620820+0800 VCallDemo[4273:2079036] H264/97       128   25.00   512/1024  480x640
 Video conference has 4 ports:
 id name                   format               rx-from      tx-to 
 ------------------------------------------------------------------
  0 Front Camera           BGRA 352x288@15.0                 
  1 OpenGL renderer        I420 976x976@37.0                 
  2 vstdec0x11c0efc28      I420 976x976@37.0                 
  3 vstenc0x11c0efc28      I420 480x640@25.0                 
2023-01-11 10:40:00.620987+0800 VCallDemo[4273:2079036] 视频所有Window ID 2
2023-01-11 10:40:00.621037+0800 VCallDemo[4273:2079036] Video device list:
2023-01-11 10:40:00.621081+0800 VCallDemo[4273:2079036] 6 device(s) detected:
2023-01-11 10:40:00.621129+0800 VCallDemo[4273:2079036] OpenGL renderer [OpenGL][render] (default renderer device)
2023-01-11 10:40:00.623525+0800 VCallDemo[4273:2079036] Supported capabilities: format, window, resize, position, hide, orientation
2023-01-11 10:40:00.623614+0800 VCallDemo[4273:2079036] Supported formats: BGRA
2023-01-11 10:40:00.623762+0800 VCallDemo[4273:2079036] Front Camera [AVF][capture] (default capture device)
2023-01-11 10:40:00.623811+0800 VCallDemo[4273:2079036] Supported capabilities: format, window, resize, position, hide, preview, orientation, switch
2023-01-11 10:40:00.623850+0800 VCallDemo[4273:2079036] Supported formats: BGRA, BGRA, BGRA, BGRA, BGRA, BGRA, I420, I420, I420, I420, I420, I420
2023-01-11 10:40:00.623916+0800 VCallDemo[4273:2079036] OpenGL renderer [OpenGL][render]
2023-01-11 10:40:00.624558+0800 VCallDemo[4273:2079036] Supported capabilities: format, window, resize, position, hide, orientation
```

**Comment by sauwming** [comment]
There's a recent video conference fix in https://github.com/pjsip/pjproject/commit/d3f79e7a5b9e84117b3d1b3f6f85df20b8f4215d.
Please check whether it fixes your issue.

**Comment by xuan6zm** [comment]
你好！我用了最新的版本，没有解决我的问题； 
我代码中没有使用多人会议，我在二人视频通话；

场景1、我在账户注册A后开启的视频预览，拨打视频电话给B,接通后我的预览视频是拉伸变形的，对方视频为正常的；【Opening device Front Camera [AVF] for capture: format=BGRA, size=352x288 @15:1 fps】我的视频源一直是这个，我无法修改这个

        pjmedia_orient orient = PJMEDIA_ORIENT_ROTATE_90DEG;
        pjsua_vid_dev_set_setting(dev_id, PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, PJ_TRUE);
if([capName isEqualToString:@"Front Camera"]){
        dev_id = vdi.id;
         pjsua_vid_win_info wi;
        pjsua_vid_preview_param pre_param;
        pj_status_t status;

        pjsua_vid_preview_param_default(&pre_param);
        
        pre_param.rend_id = PJMEDIA_VID_DEFAULT_RENDER_DEV;
        pre_param.wnd_flags = PJMEDIA_VID_DEV_WND_BORDER |
                            PJMEDIA_VID_DEV_WND_RESIZABLE;
        pre_param.wnd.type = PJMEDIA_VID_DEV_HWND_TYPE_IOS;
        pre_param.show = PJ_TRUE;
        pre_param.format.det.vid.size.w = 6400;
        pre_param.format.det.vid.size.h = 480;
        pre_param.format.det.vid.fps.num = 30;
        pre_param.format.det.vid.fps.denum = 30;
        pre_param.format.det.vid.max_bps = 2048000;
        pre_param.format.det.vid.avg_bps = 1024000;

        
        CGFloat fitP = 288.0/352.0;

        CGFloat videoP = 150.0/fitP;

        wi.size.w = 150.0;
        wi.size.h = videoP;

        pre_param.format.det.vid.size.h = videoP;
        pre_param.format.det.vid.size.w = 150.0;

        status = pjsua_vid_preview_start(dev_id, &pre_param);

        pjsua_vid_win_id wid = pjsua_vid_preview_get_win(PJMEDIA_VID_DEFAULT_CAPTURE_DEV);
        pjsua_vid_win_get_info(wid, &wi);
场景2、我在账户注册A后未开启视频预览，拨打电话给B,接通的时候开启视频预览，此时我的预览窗口是正常的，远端视频view显示的是（远端视频源、本地采集的预览源）,我并不想要本地的采集预览源

我想要的效果：我拨打视频电话开启视频预览（显示我的视频等比例），接通后仅显示一个远端视频源；
现在遇到问题了，我翻阅了Pjsip视频在IOS上的源码文章；并没有找到正确的解决办法，还请您能指点一下

**Comment by xuan6zm** [comment]
> There's a recent video conference fix in [d3f79e7](https://github.com/pjsip/pjproject/commit/d3f79e7a5b9e84117b3d1b3f6f85df20b8f4215d). Please check whether it fixes your issue.

你好！我用了最新的版本，没有解决我的问题； 
我代码中没有使用多人会议，我在二人视频通话；

场景1、我在账户注册A后开启的视频预览，拨打视频电话给B,接通后我的预览视频是拉伸变形的，对方视频为正常的；【Opening device Front Camera [AVF] for capture: format=BGRA, size=352x288 @15:1 fps】我的视频源一直是这个，我无法修改这个

        pjmedia_orient orient = PJMEDIA_ORIENT_ROTATE_90DEG;
        pjsua_vid_dev_set_setting(dev_id, PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, PJ_TRUE);
if([capName isEqualToString:@"Front Camera"]){
        dev_id = vdi.id;
         pjsua_vid_win_info wi;
        pjsua_vid_preview_param pre_param;
        pj_status_t status;

        pjsua_vid_preview_param_default(&pre_param);
        
        pre_param.rend_id = PJMEDIA_VID_DEFAULT_RENDER_DEV;
        pre_param.wnd_flags = PJMEDIA_VID_DEV_WND_BORDER |
                            PJMEDIA_VID_DEV_WND_RESIZABLE;
        pre_param.wnd.type = PJMEDIA_VID_DEV_HWND_TYPE_IOS;
        pre_param.show = PJ_TRUE;
        pre_param.format.det.vid.size.w = 6400;
        pre_param.format.det.vid.size.h = 480;
        pre_param.format.det.vid.fps.num = 30;
        pre_param.format.det.vid.fps.denum = 30;
        pre_param.format.det.vid.max_bps = 2048000;
        pre_param.format.det.vid.avg_bps = 1024000;

        
        CGFloat fitP = 288.0/352.0;

        CGFloat videoP = 150.0/fitP;

        wi.size.w = 150.0;
        wi.size.h = videoP;

        pre_param.format.det.vid.size.h = videoP;
        pre_param.format.det.vid.size.w = 150.0;

        status = pjsua_vid_preview_start(dev_id, &pre_param);

        pjsua_vid_win_id wid = pjsua_vid_preview_get_win(PJMEDIA_VID_DEFAULT_CAPTURE_DEV);
        pjsua_vid_win_get_info(wid, &wi);
场景2、我在账户注册A后未开启视频预览，拨打电话给B,接通的时候开启视频预览，此时我的预览窗口是正常的，远端视频view显示的是（远端视频源、本地采集的预览源）,我并不想要本地的采集预览源

我想要的效果：我拨打视频电话开启视频预览（显示我的视频等比例），接通后仅显示一个远端视频源；
现在遇到问题了，我翻阅了Pjsip视频在IOS上的源码文章；并没有找到正确的解决办法，还请您能指点一下

**Comment by xuan6zm** [comment]
> There's a recent video conference fix in [d3f79e7](https://github.com/pjsip/pjproject/commit/d3f79e7a5b9e84117b3d1b3f6f85df20b8f4215d). Please check whether it fixes your issue.

你好！我用了最新的版本，没有解决我的问题； 
我代码中没有使用多人会议，我在二人视频通话；

场景1、我在账户注册A后开启的视频预览，拨打视频电话给B,接通后我的预览视频是拉伸变形的，对方视频为正常的；【Opening device Front Camera [AVF] for capture: format=BGRA, size=352x288 @15:1 fps】我的视频源一直是这个，我无法修改这个

        pjmedia_orient orient = PJMEDIA_ORIENT_ROTATE_90DEG;
        pjsua_vid_dev_set_setting(dev_id, PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, PJ_TRUE);
if([capName isEqualToString:@"Front Camera"]){
        dev_id = vdi.id;
         pjsua_vid_win_info wi;
        pjsua_vid_preview_param pre_param;
        pj_status_t status;

        pjsua_vid_preview_param_default(&pre_param);
        
        pre_param.rend_id = PJMEDIA_VID_DEFAULT_RENDER_DEV;
        pre_param.wnd_flags = PJMEDIA_VID_DEV_WND_BORDER |
                            PJMEDIA_VID_DEV_WND_RESIZABLE;
        pre_param.wnd.type = PJMEDIA_VID_DEV_HWND_TYPE_IOS;
        pre_param.show = PJ_TRUE;
        pre_param.format.det.vid.size.w = 640;
        pre_param.format.det.vid.size.h = 480;
        pre_param.format.det.vid.fps.num = 30;
        pre_param.format.det.vid.fps.denum = 30;
        
   
        status = pjsua_vid_preview_start(dev_id, &pre_param);

        pjsua_vid_win_id wid = pjsua_vid_preview_get_win(PJMEDIA_VID_DEFAULT_CAPTURE_DEV);
        pjsua_vid_win_get_info(wid, &wi);
场景2、我在账户注册A后未开启视频预览，拨打电话给B,接通的时候开启视频预览，此时我的预览窗口是正常的，远端视频view显示的是（远端视频源、本地采集的预览源）,我并不想要本地的采集预览源

我想要的效果：我拨打视频电话开启视频预览（显示我的视频等比例），接通后仅显示一个远端视频源；
现在遇到问题了，我翻阅了Pjsip视频在IOS上的源码文章；并没有找到正确的解决办法，还请您能指点一下

**Comment by sauwming** [comment]
Please check https://github.com/pjsip/pjproject/pull/3350 and let us know if you have any feedback.

Also, pay attention to the sample app as the mechanism to display the local preview is now different.

**Comment by xuan6zm** [comment]
非常感谢，我的问题得到修复

**Comment by xuan6zm** [comment]
> Please check #3350 and let us know if you have any feedback.
> 
> Also, pay attention to the sample app as the mechanism to display the local preview is now different.

非常感谢，我的问题得到修复
