### ISSUE TITLE
"name-addr" instead of URI in PJSUA(2) documentation

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#3345]
### Describe the bug

Even that RFC 3261 uses the term URI, if you look at the details, the RFC mentions "name-addr".
```
name-addr      =  [ display-name ] LAQUOT addr-spec RAQUOT
```
i.e. in general we have e.g "NAME <URI>". Cf. RFC 3261:
> [20.39](https://www.rfc-editor.org/rfc/rfc3261#section-20.39) To
   The optional "display-name" is meant to be rendered by a human user
   interface.  A system SHOULD use the display name "Anonymous" if the
   identity of the client is to remain hidden.  Even if the "display-
   name" is empty, the "name-addr" form MUST be used if the "addr-spec"
   contains a comma, question mark, or semicolon.  Syntax issues are
   discussed in [Section 7.3.1](https://www.rfc-editor.org/rfc/rfc3261#section-7.3.1).

Why is that important? Because the stack has to differentiate between header-parameters and URI parameters. There is a difference between `To: <sip:alice@sip.org;param=abc>; tag=1234` and `To: <sip:alice@sip.org;param=abc; tag=1234`. In later case, `param` is a header parameter and not part of the URI.

Hence,  in PJSUA2's `makeCall()`, the URI for making a call is "name-addr" instead. URIs work as well, as long no URI parameter ist used. The same applies for `CallOpParam::txOption::targetUri` and `CallOpParam::txOption::localUri`.

### Steps to reproduce

It is documentation only. 

### PJSIP version

2.13

### Context

SIP

### Log, call stack, etc

```shell
Not needed.
```

**Comment by sauwming** [comment]
PJSIP accepts **both** `name-addr` and URI as the parameter of `makeCall()`, so if we want to make the doc more complete, shouldn't we mention both instead?
such as: 
```
    /**
     * Make outgoing call to the specified URI/name-addr.
     * @param dst_uri       URI/name-addr to be put in the To header (normally is the same
     *                      as the target URI/name-addr).
     ...
     */
    void makeCall(...)
```

Having said that, the changes can be a lot (I count 51 occurrences in pjsua header alone), so a more practical option would probably be to add in the doc somewhere in https://docs.pjsip.org that the URIs (and the URI parameters) passed to PJSIP APIs can be enclosed in "<" and ">", which, together with `the display-name`, constitute as `name-addr` forms.

**Comment by sauwming** [comment]
I have added the doc here: https://docs.pjsip.org/en/latest/pjsua2/using/account.html#creating-account
and here: https://docs.pjsip.org/en/latest/pjsua2/using/call.html#making-outgoing-calls

**Comment by wosrediinanatour** [comment]
Thank you - that looks good.

In a perfect world, it would be good to rename localUri/local_uri etc. But I see that this changes the interface, which is most probably not wanted.
