### ISSUE TITLE
How to receive call on android + pjsip when phone in deep sleep

### ISSUE THREAD

**Issue by maxdianwei** [pjsip/pjproject#3363]
### Describe the bug

I'm trying to build voip app based on PJSIP on Android. I decided to use TCP for connection to make the connection be persistent. And app right now has background service (same process) which is responsible for all interactions with SIP server. TCP keep alive timeout is set to 1 minute (just for testing purposes). Everything works fine until the moment when phone goes into a deep sleep mode

### Steps to reproduce

NA

### PJSIP version

2.1.1

### Context

NA

### Log, call stack, etc

```shell
NA
```

**Comment by maxdianwei** [comment]
help！！！

**Comment by sauwming** [comment]
Use push notification service. Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
