### ISSUE TITLE
Segmentation fault upon invalid READ access

### ISSUE THREAD

**Issue by Kexin6** [pjsip/pjproject#3366]
### Describe the bug

The issue is a segmentation fault in the `create_answer()` function in sipecho.c caused by an invalid read access of a null pointer. 

### Steps to reproduce

1. Compile PJSIP binaries under pjproject directory: .`/configure --disable-strip CFLAGS=-g && make dep && make clean && make`

2. Compile Baresip binary under baresip directory: `make -C deps/re install PREFIX=$PWD/bin && make -C deps/rem install PREFIX=$PWD/bin LIBRE_MK=$SIP_FUZZER_DIR/baresip/deps/re/mk/re.mk && make PREFIX=$PWD/bin LIBRE_MK=deps/re/mk/re.mk LIBRE_INC=bin/include/re/ LIBRE_SO=bin/lib/ LIBREM_PATH=bin/ install`

3. Launch SIP Echo service: .`/pjproject/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/sipecho`

4. Launch Baresip client: `./baresip -f docs/examples -e \"d test@127.0.0.1:5060\" -n 127.0.0.1"
`
5. Baresip sends the following INVITE message to the SIP Echo application:

```
	INVITE sip:test@127.0.0.1:5060 SIP/2.0\r\n
	Via: SIP/2.0/UDP 127.0.0.1:41937;branch=z9hG4bK27e3f61708de5539;rport\r\n
	Contact: <sip:user-0x805010@127.0.0.1:41937>\r\n
	Max-Forwards: 70\r\nTo: <sip:test@127.0.0.1:5060>\r\n
	From: <sip:user@example.com>;tag=0435ab00f8256ef0\r\n
	Call-ID: 5bc68ea866c3ccf0\r\n
	CSeq: 4261 INVITE\r\n
	User-Agent: baresip v0.6.2 (x86_64/linux)\r\n
	Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER\r\n
	Supported: gruu\r\n
	Content-Type: application/sdp\r\n
	Content-Length: 411\r\n\r\n
	v=0\r\n
	o=- 4179833163 558260718 IN IP4 127.0.0.1\r\n
	s=-\r\n
	c=IN IP4 127.0.0.1\r\n
	t=0 0\r\n
	a=tool:baresip 0.6.2\r\n
	m=audio 46640 RTP/AVP 0 8 101\r\n
	a=rtpmap:0 PCMU/8000\r\n
	a=rtpmap:8 PCMA/8000\r\n
	a=rtpmap:101 telephone-event/8000\r\n
	a=fmtp:101 0-15\r\n
	a=sendrecv\r\n
	a=label:1\r\n
	a=rtcp-rsize\r\n
	a=ssrc:3089433414 cname:sip:user@example.com\r\n
	a=ptime:20\r\n
	a=ebuacip:version 0\r\n
	a=ebuacip:jb 0\r\n
	a=ebuacip:jbdef 0 fixed 200\r\n
	a=ebuacip:qosrec 46\r\n
```

6. SIP Echo application hits the segmentation fault.

### PJSIP version

2.13, 2.8

### Context

The cause of this SEGV is a READ memory access to a zero page when PJSIP receives the incoming INVITE message and creates an echoing response based on this offer message. Specifically, the trigger is that the SDP connection variable `c` is a NULL pointer. Logging its attributes such as `c->addr.slen` with `PJ_LOG` in sipecho.c:374 is an invalid READ of NULL address, raising the SEGV signal.

This finding indicates that the SIP Echo service's source code has flaws. The echo message's connection is assigned (i.e., executing `c = m->conn ? m->conn : answer->conn` in sipecho.c:371) before the SDP parser scans the connection attribute in the SDP body (i.e., calling pjmedia_sdp_parse() function).

To address this issue, we recommend implementing a status check in the `create_answer()` function. We have included a patch for this proposed fix and would appreciate your review. You can also find the log after the application of this patch below. Thank you!

[proposed_fix.txt](https://github.com/pjsip/pjproject/files/10669181/proposed_fix.txt)
(There is something wrong with submitting .patch file on GitHub. I apologize for this inconvenience.) 

### Log, call stack, etc

```shell
ASAN:DEADLYSIGNAL
=================================================================
==11==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000028 (pc 0x0000004f18ba bp 0x61b0000000a8 sp 0x7f228b4eb5d0 T1)
==11==The signal is caused by a READ memory access.
==11==Hint: address points to the zero page.
    #0 0x4f18b9 in create_answer /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/sipecho.c:374:2
    #1 0x4f29cc in on_rx_request /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/sipecho.c:505:11
    #2 0x553e11 in pjsip_endpt_process_rx_data /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_endpoint.c:893:13
    #3 0x55212a in endpt_on_rx_msg /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_endpoint.c:1043:5
    #4 0x56f9a9 in pjsip_tpmgr_receive_packet /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transport.c
    #5 0x577069 in udp_on_read_complete /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_transport_udp.c:192:3
    #6 0x5f6394 in ioqueue_dispatch_read_event /root/server-afl/programs/sip/pjproject/pjlib/build/../src/pj/ioqueue_common_abs.c:605:6
    #7 0x5fdd9d in pj_ioqueue_poll /root/server-afl/programs/sip/pjproject/pjlib/build/../src/pj/ioqueue_select.c:1070:7
    #8 0x55328c in pjsip_endpt_handle_events2 /root/server-afl/programs/sip/pjproject/pjsip/build/../src/pjsip/sip_endpoint.c:744:6
    #9 0x4f0c3e in worker_proc /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/sipecho.c:167:2
    #10 0x600c1e in thread_main /root/server-afl/programs/sip/pjproject/pjlib/build/../src/pj/os_core_unix.c:541:27
    #11 0x7f228e9af6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #12 0x7f228e2cb51c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10751c)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/sipecho.c:374:2 in create_answer
Thread T1 created by T0 here:
    #0 0x4aa696 in pthread_create /scratch/llvm/clang-4/xenial/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:305:3
    #1 0x6005b5 in pj_thread_create /root/server-afl/programs/sip/pjproject/pjlib/build/../src/pj/os_core_unix.c:634:10
    #2 0x4ef3ff in init_stack /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/sipecho.c:289:14
    #3 0x4ef3ff in main /root/server-afl/programs/sip/pjproject/pjsip-apps/build/../src/samples/sipecho.c:607
    #4 0x7f228e1e483f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

==11==ABORTING

************************************Log Before Patch************************************
Ready for incoming calls. Press ENTER to quit...

Menu:
  h    Hangup all calls
  l    Enable message logging
  q    Quit

************************************Log After Patch************************************
Ready for incoming calls. Press ENTER to quit...

Menu:
  h    Hangup all calls
  l    Enable message logging
  q    Quit

14:28:48.373              sipecho.c !.RX INVITE from 127.0.0.1
14:28:48.874              sipecho.c  .RX INVITE from 127.0.0.1
14:28:48.874              sipecho.c  .Call 0: creating answer:
answer's media count: 1
14:28:48.879              sipecho.c  ..Call 0: state changed to CONFIRMED
14:28:48.880              sipecho.c  .....Call 0: DISCONNECTED [reason=200 (OK)]
```

**Comment by trengginas** [comment]
I tested using Sipp with the same SDP, and the `sipecho` didn't crash. 
```
c=IN IP4 127.0.0.1\r\n
```
The SDP contains the connection field, so
```
c = m->conn ? m->conn : answer->conn
```
should not be NULL.
Note that `pjmedia_sdp_parse()` is called by `pjsip_rdata_get_sdp_info()` (https://github.com/pjsip/pjproject/blob/master/pjsip-apps/src/samples/sipecho.c#L466).

**Comment by Kexin6** [comment]
That's interesting. When I tested it with Baresip, I checked that both `m->conn` and `answer->conn` are null.

**Comment by Kexin6** [comment]
Hi, I replayed the messages in a clean docker without address sanitizer and I was still able to see the SEGV. I listened to the ports and generated .pcap file. Please check out [any.pcap](https://github.com/Kexin6/pjproject/blob/master/pcap_files/any.pcap) and see the attachment for human-readable version. 

To recap, I suspect that SEGV was triggered by both media and answer connection field == NULL. As shown in the `any.pcap` file, the client sent a packet with this media field:
```
Media Description, name and address (m): au\177\357\277\275\357\277\275\357\277\27534718 RTP/AVP 0 8 101
                Media Type: au\177\377\377\37734718
                Media Port: RTP
                Media Port Count: AVP
                Media Protocol: 0
                Media Format: 8
                Media Format: 101
```
where the media type is invalid. Instead of assertion, probably a more proper handler would be better?
I hope these additional information would help! I appreciate your help.

[beautiful_any.txt](https://github.com/pjsip/pjproject/files/10702054/beautiful_any.txt)
