### ISSUE TITLE
Is libpjsua2-2v5 moved out from Pjproject 2.12+ versions ?

### ISSUE THREAD

**Issue by CpServiceSpb** [pjsip/pjproject#3376]
There is no libpjsua2-2v5 in Pjproject 2.12.
Is it moved out by developers ?
What was libpjsua2-2v5 intended for ?
And what are differences between libpjsua2-2v5 and libpjsua2 ?

**Comment by sauwming** [comment]
There was never `libpjsua2-2v5` within PJSIP.
