### ISSUE TITLE
iOS Swift random crashes 

### ISSUE THREAD

**Issue by eduardothiesen** [pjsip/pjproject#3378]
### Describe the bug

When initializing the pjsip lib on swift, randomly it crashes with the following error:

malloc: Incorrect checksum for freed object 0x107693430: probably modified after being freed.
Corrupt value: 0x0
GCF_SoftPhone(1901,0x16b24b000) malloc: *** set a breakpoint in malloc_error_break to debug
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libgmalloc.dylib:/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
GCF_SoftPhone(1901,0x16b24b000) malloc: Incorrect checksum for freed object 0x107693430: probably modified after being freed.
Corrupt value: 0x0

### Steps to reproduce

Could not figure out exact steps to reproduce since it appears to happen randomly.

### PJSIP version

2.13

### Context

iOS 15.1, iPhone 7s

### Log, call stack, etc

```shell
malloc: Incorrect checksum for freed object 0x107693430: probably modified after being freed.
Corrupt value: 0x0
GCF_SoftPhone(1901,0x16b24b000) malloc: *** set a breakpoint in malloc_error_break to debug
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/usr/lib/libgmalloc.dylib:/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
GCF_SoftPhone(1901,0x16b24b000) malloc: Incorrect checksum for freed object 0x107693430: probably modified after being freed.
Corrupt value: 0x0
```

**Comment by sauwming** [comment]
With the provided info, it's difficult to tell whether it's app bug or something else.

Try to reproduce it with the iOS swift pjsua or pjsua2 sample app, and reopen the issue if you have  more definite information.
