### ISSUE TITLE
pjsua is memory leak when video is tramsmited.

### ISSUE THREAD

**Issue by feihualuomeng** [pjsip/pjproject#3380]
### Describe the bug

pjsua enable video function, when video is transmited, memory is increace always

### Steps to reproduce

pjsua enable video function, when video is transmited, memory is increace always

### PJSIP version

2.13

### Context

linux

### Log, call stack, etc

```shell
cat /proc/pid/status
```

**Comment by sauwming** [comment]
I just created a fix in #3395 which may be relevant for this issue.

If the issue persists, we need to isolate where the leak occurs:
- Try with minimal setup:
    * use colorbar instead of camera (run pjsua with option `vcap=[colorbar_dev_id]`)
    This is to check if the leak is not in the video device
    * disable remote outgoing video (use command `vid acc autotx off` in remote pjsua).
    This is to rule out if the leak is in the incoming direction.
- Dump the pool to know whose pool keeps growing.
  In pjsua, you can use the command `dd`.  Alternatively you can call `pjsua_dump(PJ_TRUE)`. Compare the results between two pool dumps.
