### ISSUE TITLE
Remove extra spaces in code

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3387]
I use vscode search extra spaces 
（use regex to search:the number of consecutive spaces to the end of every line is greater than 1)
![09](https://user-images.githubusercontent.com/12636246/219315154-1b8a7858-ea71-468b-8af9-01119c640ec7.PNG)

so many match files.
(this just in c/c++ file,  there also some in *.py, *.m, *.java files)

We'd better find time to remove them.

（I'm a bit obsessive ^_^)

PS:
methods can use:
- use vscode to replace
- use gnu sed command
  ```bash
   find ./pj* ./tests -name "*.[chm]" -o -name "*.[ch]pp" -o -name "*.cc"  \
     -o -name "*.py" -o -name "*.java" -o -name "*.cs" -o -name Makefile | xargs sed -ri "s/\s{1,}$//g"
  ```

PS:
vscode display whitespace:   Settings -> search "Render WhiteSpace" and set to "all"

**Comment by bennylp** [comment]
IMO this is opinion based, and (as you have realized) our opinion has been that trailing whitespaces are not important enough to do something about it. Especially fixing it, not only that would create commit noise, but without adding **significant** extra effort to prevent trailing whitespaces to appear in the future, that fix would be useless. 

I do remove trailing whitespaces in my PR when I realize their presence, but it is not part of my workflow to consciously try to remove them, and I don't think we want to suggest that to everyone either. 

Thanks.
