### ISSUE TITLE
android video rotate black

### ISSUE THREAD

**Issue by yudongdong12306** [pjsip/pjproject#3400]
### Describe the bug

I am an Android application developer. After I rotate the front camera by calling the setCaptureOrient method, the video received by the other party will have black borders. What should I do?
sdk version: 2.13

### Steps to reproduce

preview

### PJSIP version

2.13

### Context

google pixelXL4

### Log, call stack, etc

```shell
as title
```

**Comment by sauwming** [comment]
This is to be expected due to aspect ratio differences.
Check android_dev.c `MAINTAIN_ASPECT_RATIO`.

Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
