### ISSUE TITLE
Better to use while in pj_event_wait to avoid deadlocks

### ISSUE THREAD

**Issue by ycaibb** [pjsip/pjproject#3409]
### Describe the bug

Hi, is it better to use while to replace the if while using pj_event_wait? For example, accroding to [this](https://stackoverflow.com/questions/33186280/why-we-must-use-while-for-checking-race-condition-not-if), one reason is the "spurious wakeup", which means the wait method can return without the thread having been notified: it's not valid to infer, based on the thread exiting the wait method, that it must have gotten notified. This may not happen a lot but it is a possibility that has to be handled.

https://github.com/pjsip/pjproject/blob/5ac9104514499d648f68991ef796368c51b4dfec/pjnath/src/pjnath-test/concur_test.c#L123-L126

### Steps to reproduce

None

### PJSIP version

The master

### Context

None

### Log, call stack, etc

```shell
None
```

**Comment by sauwming** [comment]
The `if` is just to check whether we should do the wait or not.

Inside the `pj_event_wait()` itself, will be the `while` loop done to do the waiting:
https://github.com/pjsip/pjproject/blob/master/pjlib/src/pj/os_core_unix.c#L1980

Besides, the code above is only a part of unit tests, so it should not be involved in a scenario that can cause deadlock.
