### ISSUE TITLE
How to change “Contact” in SIP INVITE header

### ISSUE THREAD

**Issue by Hynsen** [pjsip/pjproject#3410]
Hi team,

I want to change the “Contact” in SIP header.
currently we are getting
Contact: <sip:phoneNum@129.0.164.11:6443;transport=tls>

but we need as like below
Contact: <sip:phoneNum@129.0.164.11:7443;transport=tls>

please suggest me

**Comment by trengginas** [comment]
You can use AccountSipConfig::contactForced
