### ISSUE TITLE
PJSIP setting DF flag but not detecting PMTU

### ISSUE THREAD

**Issue by hb9eue** [pjsip/pjproject#3416]
### Describe the bug

Hi

Here is an issue that showed up with Asterisk 16.28, so not sure if this might have been fixed already.

Asterisk behind VDSL using JPSIP. UDP Invite packet after being challenged, contains SDP with credentials, ice, crypto and a couple codecs being shy of 1500 bytes long and having DF (don't fragment) flag set.
Link is VDSL MTU 1472, router replies with an ICMP, indicating max-packet-size to sender and drops packet.
Asterisk keeps sending too large packets with DF bit set.

Tested with another SIP client which does not set DF on same machine. Router fragments packets. Recipient OS re-assembles this and passes to the application. So it is quite clear, that the sending OS is not the culpit, but DF is being set by the sending application.

Contacted Asterisk-Devs who reckon the DF bit is hardcoded by PJSIP and can not be changed from within Asterisk.

Is this a known issue? Is there an easy fix?

-Benoît-

### Steps to reproduce

Fiddle with the PJSIP options to get a UDP INVITE packet which is a bit smaller than 1500 bytes but larger than the MTU of an in transit router (Like in VDLS set-ups).

### PJSIP version

2.12.1

### Context

Asterisk 16.28 on Debian 11

magma*CLI> pjsip show version 
PJPROJECT version currently running against: 2.12.1
magma*CLI> core show version 
Asterisk 16.28.0~dfsg-0+deb11u1

### Log, call stack, etc

```shell
If desired, I could attach a trace. But I suppose the issue is clear from the description.
```

**Comment by trengginas** [comment]
PJSIP doesn't send/set the DF flag. However according to [this](https://stackoverflow.com/questions/973439/how-to-set-the-dont-fragment-df-flag-on-a-socket), it is possible to set it using `setsockopt()`. You can try using `pjsip_udp_transport_cfg::sockopt_params` for UDP. Haven't tried it myself.
