### ISSUE TITLE
Small library that uses PJSIP project

### ISSUE THREAD

**Issue by oliverepper** [pjsip/pjproject#3440]
I've built something on top of PjSIP project that may be useful for some here:

https://github.com/oliverepper/libphone

libphone is a library that sits on top of PJSIP pjproject and tries to make it very simple to build a softphone. Build instructions for macOS and Linux might be useful in itself. To be able to create a libphone DSO that contains all that's needed of pjproject I needed to change the libpjproject.pc file. Details in the README.

**Comment by sauwming** [comment]
Thank you for the library. It's great work and I hope it can be useful for others.

Unfortunately, the issue page is not the place to list/advertise projects, but I believe with the right keywords, people should be able to find your project using Github search.

Anyway, I will keep this open for now to allow people to read it, but I will close it in the near future.

**Comment by oliverepper** [comment]
You're right. Close it anytime you want. The idea of posting this here was born out of the troubles I had building for linux. (see: https://github.com/pjsip/pjproject/issues/3418). I really wanted to create one DSO that bundles everything (pjsua2, pjsua, pjlib, ...) and that was not possible without a bit of tweaking.

It is mainly this part of the build instructions from libphone that I thought would be helpful, here:

---
Once installed into `~/installed/pjproject` you need to change two things:

```shell
pushd ~/installed/pjproject
ar -rcT lib/libpjproject.a lib/*.a
cp lib/pkgconfig/libpjproject.pc lib/pkgconfig/libpjproject.orig
popd
```

Please edit the file `~/installed/pjproject/lib/pkgconfig/libpjproject.pc` to contain the following (example from my build-docker):

```text
prefix=/home/oliver/installed/pjproject
libdir=${prefix}/lib
includedir=${prefix}/include

Name: libpjproject
Description: Multimedia communication library
URL: http://www.pjsip.org
Version: 2.13
Libs: -L${libdir} -lpjproject -lcrypto -lssl -lasound -lopus
Cflags: -I${includedir} -DPJ_AUTOCONF=1  -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1
```
---

Maybe you could comment on that? I'd gladly close this issue and maybe contribute to PJSIP pjproject documentation, if that is helpful?

The real issue is that with the upstream build I could link against pjsua2 dynamically, but not statically.

**Comment by sauwming** [comment]
I haven't managed to test with linux aarch64 platform, so I can't comment. But as far as I know, there's no problem with other architectures.

But feel free to submit a patch or create a PR to improve PJSIP and/or its documentation, we will certainly review it.
