### ISSUE TITLE
Undefined reference to `__gxx_personality_v0'

### ISSUE THREAD

**Issue by andrealmeidati** [pjsip/pjproject#3451]
### Describe the bug

Hello guys, I need your help

When we'll building pjproject-2.10 :

./configure OK

make dep  OK

make : 

/usr/src/nxt3000-install/programas/pjproject-2.10/third_party/lib/libwebrtc-x86_64-unknown-linux-gnu.a(cpu_features.o):(.eh_frame+0x12): undefined reference to `__gxx_personality_v0'
collect2: ld returned 1 exit status
make[2]: ** [../bin/pjmedia-test-x86_64-unknown-linux-gnu] Erro 1
make[2]: Saindo do diret�rio `/usr/src/nxt3000-install/programas/pjproject-2.10/pjmedia/build'
make[1]: ** [pjmedia-test-x86_64-unknown-linux-gnu] Erro 2
make[1]: Saindo do diret�rio `/usr/src/nxt3000-install/programas/pjproject-2.10/pjmedia/build'
make: ** [all] Erro 1

Before we running ./contrib/scripts/install_prereq install 

We are using Asterisk 13 and we need to use webrtc. Someone help us ?

### Steps to reproduce

./configure OK

make dep  OK

make : 

### PJSIP version

2.10

### Context

Centos 6.9
Asterisk 13

### Log, call stack, etc

```shell
/usr/src/nxt3000-install/programas/pjproject-2.10/third_party/lib/libwebrtc-x86_64-unknown-linux-gnu.a(cpu_features.o):(.eh_frame+0x12): undefined reference to `__gxx_personality_v0'
collect2: ld returned 1 exit status
make[2]: ** [../bin/pjmedia-test-x86_64-unknown-linux-gnu] Erro 1
make[2]: Saindo do diret�rio `/usr/src/nxt3000-install/programas/pjproject-2.10/pjmedia/build'
make[1]: ** [pjmedia-test-x86_64-unknown-linux-gnu] Erro 2
make[1]: Saindo do diret�rio `/usr/src/nxt3000-install/programas/pjproject-2.10/pjmedia/build'
make: ** [all] Erro 1
```

**Comment by sauwming** [comment]
- Use the latest PJSIP version
- Use the latest C++ compiler

Currently the issue page is for bug report or feature request only.
