### ISSUE TITLE
how to implement video call in pjsip2

### ISSUE THREAD

**Issue by shubham795** [pjsip/pjproject#3455]
i don't know how to implement video call in your document can you please provide the demo of video call implementation in swift

**Comment by sauwming** [comment]
#3381, #3342.

**Comment by shubham795** [comment]
thanks for your reply sir, 

1) The video appears horizontally on the opposite sides while streaming the video, is there any way to rotate the view?

2) I can't set my preview during a video call

if you can help me with this it would mean alot
