### ISSUE TITLE
Python pjsua2 examples

### ISSUE THREAD

**Issue by TerehinAV** [pjsip/pjproject#3463]
**Is your feature request related to a problem? Please describe.**
In pjsua2 python bindings in pjsua.py there is not much description of methods implementation (in comparison with pjsua v2.9). This creates difficulties in understanding how exactly to use the functionality of the library in python3 (because there are some differences, starting from the registration of the account, and continuing with reactions to callbacks of calls).

**Describe the solution you'd like**
Please add some examples with using pjsua2 (registration, simple_call, dtmf, different answer options for incoming_call callback, etc.

**Describe alternatives you've considered**
The second option is to add some python documentation for modern version of pjsua lib.

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/pjsua2/samples.html
