### ISSUE TITLE
Create attribute within attribute for PIDF file

### ISSUE THREAD

**Issue by IWaheed** [pjsip/pjproject#3465]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IWaheed** [comment]
Hello,

in PIDF files, one can add attributes using `xml_create_attr` function. However, as XML is known for its flexibility, it should be possible to add attributes within attributes. I think that this feature will add to PJSIP's support of PIDF documents.

**Comment by sauwming** [comment]
Currently we don't have any plan to support this. Please feel free to submit a PR if you happen to have a chance to implement it.
