### ISSUE TITLE
pjproject's copy of sockaddr_in6 is missing a field on solaris-derived systems.

### ISSUE THREAD

**Issue by Bill-Sommerfeld** [pjsip/pjproject#3469]
### Describe the bug

I'm running asterisk 16 on illumos, a community fork of opensolaris.   Solaris and its derivatives have an extra field, [`__sin6_src_id`](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/netinet/in.h#L430), at the end of [`struct sockaddr_in`](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/netinet/in.h#L421-L431)

I discovered this with the version pjproject embedded in asterisk 16 (at the end of a bug hunt that started with noticing an error from asterisk: "Could not create DNS resolver(120022), resorting to system resolution" but it appears that the code in question is unchanged at HEAD.

The pjproject code passes a `pj_sockaddr_in6` instead of a `struct sockaddr_in6` to kernel socket calls and gets `EINVAL` or similar because the structure is 4 bytes short.

I worked around with a non-portable patch:

```
--- source/pjlib/include/pj/sock.h.~1~  Sat Mar  4 15:21:19 2023
+++ source/pjlib/include/pj/sock.h      Mon Mar  6 14:36:58 2023
@@ -594,6 +594,7 @@
     pj_uint32_t        sin6_flowinfo;      /**< IPv6 flow information      */
     pj_in6_addr sin6_addr;         /**< IPv6 address.              */
     pj_uint32_t sin6_scope_id;     /**< Set of interfaces for a scope  */
+    pj_uint32_t        __sin6_src_id;  /* Impl. specific - UDP replies */
 } pj_sockaddr_in6;

``` 
 
Fixing this for real will require some configure work to add a feature test to detect this field.   I'll be happy to work on a patch that does this when my time permits.

### Steps to reproduce

1. Build asterisk 16 on the openindiana distribution of illumos; 
2. configure it to use pjsip.
3. See a "Could not create DNS resolver" log message and investigate.

### PJSIP version

2.8

### Context

Observed on the OpenIndiana Hipster distribution of illumos with the pjsip 2.8 present in asterisk 16, but likely affects Solaris and all of its derivatives.

### Log, call stack, etc

```shell
Asterisk logs:

[2023-03-20 10:50:32] ERROR[27] res_pjsip/config_system.c: Could not create DNS resolver(120022), resorting to system resolution

Digging with system call traces quickly found a failing call to `bind` due to a short `address_len`.
```

**Comment by sauwming** [comment]
Due to my unfamiliarity with the platform, we would much appreciate if you can create a patch for this.

**Comment by sauwming** [comment]
Temporarily closing this due to lack of recent update. Feel free to reopen whenever you're ready. Thanks.
