### ISSUE TITLE
ioq_stress_test.c fails spuriously if non-blocking connect() doesn't return EINPROGRESS

### ISSUE THREAD

**Issue by Bill-Sommerfeld** [pjsip/pjproject#3472]
### Describe the bug

On illumos, I see non-blocking loopback calls to `connect` routinely complete immediately rather than returning `EINPROGRESS`.

Code in (for instance) [sip_transport_tcp.c](
https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsip/sip_transport_tcp.c#L1062-L1070) handles this case, but the corresponding code in [ioq_stress_test.c](https://github.com/pjsip/pjproject/blob/340a1b21e422ba49be185ad30d456ed773fd5ef2/pjlib/src/pjlib-test/ioq_stress_test.c#L617-L621):
```
        } else {
            test->state.connect_status = pj_ioqueue_connect(test->state.keys[CLIENT],
                                                            &addr, namelen);
            CHECK(45, test->state.connect_status);
        }
```
just plows on without ever calling `on_connect_complete(...)` and the reader side of the test gets stuck because no data ever gets written to the socket.

This also affects the `reject_connect` and `failed_connect` code paths in the test.

I'm working on a patch for this.   (I'm also going to investigate why these calls complete synchronously, as this means the test isn't exercising the `EINPROGRESS` path on my system; as best as I can tell the socket is correctly set non-blocking)

### Steps to reproduce

Build pjproject on a recent openindiana install
Run pjlib-test; watch it hang in the ioq stress test.

### PJSIP version

checkout of HEAD at 2ec664fcb2349a5c6ea4b02cf1c28d47132c80c4 with WIP porting patches

### Context

I'm seeing this on illumos (autoconf identifies this as "x86_64-pc-solaris2.11").

### Log, call stack, etc

```shell
Logs were not captured during debugging; I can recreate if necessary.
```

**Comment by sauwming** [comment]
Just FYI, there's some similarity with https://github.com/pjsip/pjproject/pull/3499. There, the polling can return immediately and also cause the test to fail.
Also, it will be helpful if you mention which ioq backend you're using.

**Comment by sauwming** [comment]
Temporarily closing this due to lack of recent update. Feel free to reopen whenever you're ready. Thanks.
