### ISSUE TITLE
illumos builds need -pthread in CFLAGS

### ISSUE THREAD

**Issue by Bill-Sommerfeld** [pjsip/pjproject#3474]
### Describe the bug

While testing other patches to pjsip on illumos I noticed that the `transport_test.c` `multithreaded round-trip test` in `pjsip-test` loops, repeatedly printing:
```
13:58:46.347              udp7a1ea0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
```
A first look showed that the underlying `recvfrom()` system call had returned -1 and that `errno` was zero.  Subsequent investigation found that the code hadn't been built with `-D_REENTRANT` which (among other things) causes the thread-safe version of  `errno` to be defined by `<errno.h>`; the code running in the thread was looking at the main thread's `errno` instead of its own.

(As an aside, gcc documents the `-pthread` flag to enable this and it might make sense to add that flag to CFLAGS on any platform using the `os_core_unix.c` module).  

### Steps to reproduce

Build pjproject on illumos.
Run pjsip-test
Watch it get stuck spewing the aforementioned error.

### PJSIP version

checkout of HEAD at 2ec664f with WIP porting patches

### Context

I see this with a build on a system running the openindiana version of illumos but it's likely to be the case on any solaris derivative.

I'm working on a patch for this and will send a pull request when it's ready for review.

### Log, call stack, etc

```shell
$ ./pjsip-test-x86_64-pc-solaris2.11
...
14:01:20.577       transport_test.c   single message round-trip test...
14:01:20.577       transport_test.c     round-trip = 41 usec
14:01:20.577       transport_test.c   single message round-trip test...
14:01:20.577       transport_test.c     round-trip = 41 usec
14:01:20.577       transport_test.c   single message round-trip test...
14:01:20.577       transport_test.c     round-trip = 41 usec
14:01:20.577       transport_test.c   multithreaded round-trip test (4 threads)...
14:01:20.577       transport_test.c     this will take approx 10 seconds, please wait..
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
14:01:20.588              udp7a2ef0 Warning: pj_ioqueue_recvfrom: [err -1] Unknown error -1
...
```

**Comment by sauwming** [comment]
Temporarily closing this due to lack of recent update. Feel free to reopen whenever you're ready. Thanks.
