### ISSUE TITLE
iOS - kCFStreamNetworkServiceTypeVoip Deprecated

### ISSUE THREAD

**Issue by ecionini** [pjsip/pjproject#3484]
### Describe the bug

Greetings,
Is there a reason why it was preferred to disable multitasking in case the iOS version is >= 16 instead of replacing the deprecated const "kCFStreamNetworkServiceTypeVoip" with "kCFStreamNetworkServiceTypeBackground"?

Activesock.c file in pjlib.

```
static void activesock_create_iphone_os_stream(pj_activesock_t *asock)
{
    if (ios_bg_support && asock->bg_setting && asock->stream_oriented) {
	activesock_destroy_iphone_os_stream(asock);

	CFStreamCreatePairWithSocket(kCFAllocatorDefault, asock->sock,
				     &asock->readStream, NULL);

	if (!asock->readStream ||
	    CFReadStreamSetProperty(asock->readStream,
				    kCFStreamNetworkServiceType,
				    kCFStreamNetworkServiceTypeBackground) //<-substituted for kCFStreamNetworkServiceTypeVoip
	    != TRUE ||
	    CFReadStreamOpen(asock->readStream) != TRUE)
	{
	    PJ_LOG(2,("", "Failed to configure TCP transport for VoIP "
		      "usage. Background mode will not be supported."));
	    
	    activesock_destroy_iphone_os_stream(asock);
	}
    }
}
```

The change seems to work without problems, but since I'm not a SIP expert, so I ask to avoid making a mistake.

### Steps to reproduce

Build PJSip for iOS with Xcode 14

### PJSIP version

Any

### Context

iOS 16
Xcode 14

### Log, call stack, etc

```shell
application crash because kCFStreamNetworkServiceTypeVoip is no longer usable.
```

**Comment by sauwming** [comment]
According to the doc, `kCFStreamNetworkServiceTypeBackground` is for background download, so yes, technically it may serve as a hackish workaround to make the background stream work.

But since Apple will require you to use push notification for VoIP, you will eventually have to disable it in your release/production app.
