### ISSUE TITLE
PJSUA CLI: im bud_list, sub_pre and others use buddy index from 1 to N, but real id (and logs) are ranged 0 to N-1

### ISSUE THREAD

**Issue by SebaLedesma** [pjsip/pjproject#3485]
### Describe the bug

When using the CLI the bud_list, sub_pre and unsub_pre are ranged from 1 to N, but when executing for example:

```
im bud_list
Buddy list:
 [ 1] <?>  sip:carlos@sip.linphone.org
 [ 2] <?>  sip:ana@sip.linphone.org
 [ 3] <?>  sip:john@mydomain.onsip.com
 [ 4] <?>  sip:taylor@mydomain.onsip.com
```

```
im sub_pre 4    //want to subscribe to Taylor
16:01:40.262           pjsua_pres.c !.Buddy 3: updating presence..
16:01:40.262           pjsua_pres.c  ..Buddy 3: subscribing presence,using account 2..
```

### Steps to reproduce

connect to pjsua using telnet, ie:
putty -telnet 192.168.0.128 2323
and run the commands (after a buddy list its loaded).
im bud_list
and then subscribe to any of them

### PJSIP version

2.13 and master

### Context

All OS

### Log, call stack, etc

```shell
im sub_pre 4
16:01:40.262           pjsua_pres.c !.Buddy 3: updating presence..
16:01:40.262           pjsua_pres.c  ..Buddy 3: subscribing presence,using account 2..
16:01:40.263           pjsua_core.c  .....TX 715 bytes Request msg SUBSCRIBE/cseq=8584 (tdta0x7f94007348) to UDP 51.89.71.129:5060:
...
```

**Comment by sauwming** [comment]
Yes the printed index, for human readability, is different.
The behavior is observable in regular, non CLI, pjsua app as well.

**Comment by SebaLedesma** [comment]
Yes, the functionally works, but it can be misleading. 
In the other hand, for example the accounts are 0-index based.
Not big deal, I've discovered while I've trying to understand why linphone server sometimes behaves strangely.
