### ISSUE TITLE
add PJMEDIA_VID_DEV_CAP_ORIENTATION for ffmpeg_stream_set_cap

### ISSUE THREAD

**Issue by whitetreebug** [pjsip/pjproject#3489]
I want to rotate video size on PC  just like phone;

I try to add this feature by myself but met some problem.
eg: 
- how to change the `ffmpeg_vid_codecs: codec_desc` when encoding (It seems that it is need to change the `codec_desc` and 
reopen `AVCODEC_OPEN`).
- I rotate the video by  `sws_scale` . Is this method feasible?

**Comment by sauwming** [comment]
If you want to change it from the sender side:
https://docs.pjsip.org/en/latest/specific-guides/video/users_guide.html#setting-video-capture-orientation
If you want to rotate it on the receiver's side:
simple rotate the receiving view/window

Currently the issue page is for bug report or feature request only.
