### ISSUE TITLE
iOS 16.4 AudioUnitInitialize timeout 9s

### ISSUE THREAD

**Issue by Yeastar-PBX** [pjsip/pjproject#3502]
### Describe the bug

On the latest iOS 16.4 system, multiple calls to AudioUnitInitialize interface in coreaudio_dev.m will result in a fixed timeout of 9 seconds

### Steps to reproduce

Continuously making phone calls

### PJSIP version

2.8

### Context

It was found on iOS16.4 that other systems do not.

### Log, call stack, etc

```shell
XPC connection interrupted
[default] Initialize posting message to kill mediaserverd (1470)
[aurioc]            AURemoteIO.cpp:1151  failed: 268451843 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
[as_client]     AVAudioSession_iOS.mm:3928  Failed to get reporterIDs: -50
[aurioc]            AURemoteIO.cpp:1151  failed: 561210739 (enable 3, outf< 1 ch,  44100 Hz, Int16> inf< 1 ch,  44100 Hz, Int16>)
[aurioc]            AURemoteIO.cpp:1151  failed: -50 (enable 3, outf< 1 ch,  48000 Hz, Int16> inf< 1 ch,  48000 Hz, Int16>)
[aurioc]            AURemoteIO.cpp:1151  failed: -50 (enable 3, outf< 1 ch,  32000 Hz, Int16> inf< 1 ch,  32000 Hz, Int16>)
[aurioc]            AURemoteIO.cpp:1151  failed: -50 (enable 3, outf< 1 ch,  16000 Hz, Int16> inf< 1 ch,  16000 Hz, Int16>)
[aurioc]            AURemoteIO.cpp:1151  failed: -50 (enable 3, outf< 1 ch,   8000 Hz, Int16> inf< 1 ch,   8000 Hz, Int16>)
```

**Comment by sauwming** [comment]
I tried it with 16.4.1 and it seems to be okay.
So:
- test with the latest iOS 16.4.1
- use the latest PJSIP version, 2.8 is rather old
- try with our sample app, in case that you haven't.

Also if the issue still persists, please let us know how many calls on average do you usually encounter this issue.
