### ISSUE TITLE
Error SSL certificate

### ISSUE THREAD

**Issue by andrealmeidati** [pjsip/pjproject#3512]
### Describe the bug

Hi ,

Asterisk 13.38....+ PJSIP_2.5.5

When we try authtenticate endpoint PJSIP with tls, web recive this messages:

[Apr 19 10:24:47] ERROR[10177]: tcptls.c:753 handle_tcptls_connection: Problem setting up ssl connection with peer '192.168.9.131:46496': error:00000001:lib(0):func(0):reason(1), Internal SSL error
[Apr 19 10:24:47] WARNING[10177]: tcptls.c:845 handle_tcptls_connection: FILE * open failed from peer '192.168.9.131:46496'!
[Apr 19 10:24:47] ERROR[10231]: tcptls.c:753 handle_tcptls_connection: Problem setting up ssl connection with peer '192.168.9.131:46508': error:00000001:lib(0):func(0):reason(1), Internal SSL error
[Apr 19 10:24:47] WARNING[10231]: tcptls.c:845 handle_tcptls_connection: FILE * open failed from peer '192.168.9.131:46508'!

Someone can help us?
Thanks

### Steps to reproduce

1 - Make (OK)
2- pjsip.conf (OK)

### PJSIP version

2.5

### Context

Asterisk 13.38

### Log, call stack, etc

```shell
[Apr 19 10:24:47] ERROR[10177]: tcptls.c:753 handle_tcptls_connection: Problem setting up ssl connection with peer '192.168.9.131:46496': error:00000001:lib(0):func(0):reason(1), Internal SSL error
[Apr 19 10:24:47] WARNING[10177]: tcptls.c:845 handle_tcptls_connection: FILE * open failed from peer '192.168.9.131:46496'!
[Apr 19 10:24:47] ERROR[10231]: tcptls.c:753 handle_tcptls_connection: Problem setting up ssl connection with peer '192.168.9.131:46508': error:00000001:lib(0):func(0):reason(1), Internal SSL error
[Apr 19 10:24:47] WARNING[10231]: tcptls.c:845 handle_tcptls_connection: FILE * open failed from peer '192.168.9.131:46508'!
```

**Comment by sauwming** [comment]
2.5 is rather old, try with the latest version (2.13).
And try it with pjsua sample app.
For Asterisk related enquiries, it should be directly addressed to them.
