### ISSUE TITLE
Documentation of TransportConfig::publicAddress unclear

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#3514]
### Describe the bug

The documentation says: "Optional address to advertise as the address of this transport".

It is not clear from the documentation what advertise actually mean, e.g. whether this will be used in the contact header of SIP messages.

### Steps to reproduce

(documentation only)

### PJSIP version

2.13

### Context

Does this setting influence the contact header of SIP messages?

### Log, call stack, etc

```shell
(documentation only)
```

**Comment by sauwming** [comment]
In the context of network communication, "advertising" refers to making a network address or endpoint known to other entities on the network to allow them to reach/communicate with you using that address.

The field `publicAddress` you mention is a generic transport config, it can be used for SIP or media transport. So If you configure it for SIP transport, then yes, it means that the Contact address will be using that address. If for media transport, then it will be advertised in the SDP to allow remote endpoint to send media to you using that address.

**Comment by wosrediinanatour** [comment]
@sauwming: Hence, if I set the `TransportConfig`'s `publicAddress` to an IP and apply it via `Endpoint::transportCreate(PJSIP_TRANSPORT_UDP, tcfg);`, it should be used in the contacts header of outgoing SIP REGISTERs and SIP INVITEs? If yes, I have to make a bug report...

**Comment by sauwming** [comment]
It looks like you're right. #2205 only checks and uses the bound address if configured, but doesn't check for public address.

**Comment by sauwming** [comment]
@wosrediinanatour , please check #3595 and let us know if it resolves the issue.

**Comment by wosrediinanatour** [comment]
> @wosrediinanatour , please check #3595 and let us know if it resolves the issue.

I will! (continuing in https://github.com/pjsip/pjproject/pull/3595)

**Comment by wosrediinanatour** [comment]
Follow-up question: @sauwming, is there a reason the contact header is of a SIP response is not set to the `publicAddress`? Or is it only  missing?
