### ISSUE TITLE
How to change the packetization-mode of H264,thank

### ISSUE THREAD

**Issue by chenmingdu** [pjsip/pjproject#3525]
My server needs h264 data with a packetization-mode of 0, but when I use my android demo for video calls, my packetization-mode is 1, so I was wondering how to change that,THANK.

**Comment by sauwming** [comment]
You can set the decoding fmtp, for an example how, you can check https://docs.pjsip.org/en/latest/specific-guides/video/users_guide.html#size-or-resolution

Please note that currently the issue page is for bug report or feature request only, not for asking enquiries.
