### ISSUE TITLE
Add close-on-exec flag

### ISSUE THREAD

**Issue by jimying** [pjsip/pjproject#3550]
### Describe the bug

This is an new feature:

In unix(linux/bsd), there has close-on-exec flag for file descriptor,
which is very useful when start child process by exec functions.
If a file descriptor has close-on-exec flag,
 child process will auto close file descriptors that parent process opened ( not inherit) when start.

Now pjlib has no way to set this flag for ioqueue/socket/openfile.

Points that need to be modified：
1.  ioqueue
epoll_create()/kqueue() file descriptor,  use fcntl() to set flag
```c
fcntl(fd, F_SETFD, FD_CLOEXEC);
```

2. socket/socketpair/activesock
set the arg 'type'  with value SOCK_CLOEXEC
```c
socket(AF_INET, SOCK_STREAM | SOCK_CLOEXEC, 0)
socketpair(AF_LOCAL, SOCK_STREAM | SOCK_CLOEXEC, 0, sv)
```
3.  open file
By set  fopen() arg 'mode'  with value  'e'
```c
fopen(path, 'w+e')
fopen(path, 're')
fopen(path, 'ae')
```

Can we add this new feature？

This is just a suggestion， to make pjlib more general useful.

### Steps to reproduce

- none

### PJSIP version

2.13-dev

### Context

- none

### Log, call stack, etc

```shell
- none
```

**Comment by sauwming** [comment]
I have read the manual of the flag.

I still don't understand though, how this could be useful for us.

**Comment by jimying** [comment]
Suppose a small server:  
a module use pjsip/pjmedia/pjnath/pjlib, which open some sockets and files; 
another module in some cases will use fork&exec/system to create sub processes to run external  cmd.
If no close-on-exec,  the sub process will inherit the file descriptors that opened
This may lead to security issues：
1. file decriptors count is too many,  the left available count to the sub process is too few
2. sub process may has long life cycle, the sockets file handle will long time not release 
(udp/tcp ports are occupied ), which may cause main process can't alloc ports resources.


So we'd better add close-on-exec flag

**Comment by sauwming** [comment]
I don't have any strong objection, my only concern is the platform (and version) specific availability.
`SOCK_CLOEXEC` only since Linux 2.6.27
`e (since glibc 2.7)
              Open the file with the O_CLOEXEC flag.`

What do you think, @nanangizz ?

**Comment by nanangizz** [comment]
When an app using PJSIP creates a subprocess, PJSIP will suddenly lose all of its file handles as they are closed automatically, so PJSIP may not work (properly) anymore and if the parent app wants to continue working with PJSIP, it need to restart the PJSIP. Is this correct?

**Comment by sauwming** [comment]
Also, are there any use cases where users will prefer the close-on-exec flag to be not set?

**Comment by jimying** [comment]
> When an app using PJSIP creates a subprocess, PJSIP will suddenly lose all of its file handles as they are closed automatically, so PJSIP may not work (properly) anymore and if the parent app wants to continue working with PJSIP, it need to restart the PJSIP. Is this correct?

No. 
When a file handle has close-on-exec flag.  child process will just auto close file handle in child own process space,
 which is not affect parent process.

Here simple test code. 
udp server listen on port 5000, the udp socket has close-on-exec flag (SOCK_CLOEXEC),
system() will start child process which will auto close the socket handle.
The main process udp server still work fine (can read data).

```c
#include <stdio.h>
#include <strings.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#define PORT 5000

int main(int argc, char **argv)
{
    int udpfd;
    fd_set rset;
    struct sockaddr_in cliaddr, servaddr;

    /* udp server init */
    bzero(&servaddr, sizeof(servaddr));
    servaddr.sin_family = AF_INET;
    servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
    servaddr.sin_port = htons(PORT);

    udpfd = socket(AF_INET, SOCK_DGRAM | SOCK_CLOEXEC, 0); 
    bind(udpfd, (struct sockaddr*)&servaddr, sizeof(servaddr));

    /* use system() create sub process, run cmd: 'sleep xx' */
    system("sleep 600 &");

    /* udp server read */
    for (;;) {
        FD_ZERO(&rset);
        FD_SET(udpfd, &rset);
        select(udpfd + 1, &rset, NULL, NULL, NULL);

        if (FD_ISSET(udpfd, &rset)) {
            char buf[1000];
            char peer[80];
            socklen_t addr_len = sizeof(cliaddr);
            int n;

            n = recvfrom(udpfd, buf, sizeof(buf), 0, (struct sockaddr*)&cliaddr, &addr_len);
            if (n > 0)
            {
                buf[n] = '\0';
                printf("recv from %s: %s\n", inet_ntop(AF_INET, &cliaddr.sin_addr, peer, sizeof(peer)), buf);
            }
        }
    }   

    return 0;
}
```
PS:
Modify the sample code, without SOCK_CLOEXEC, run again
in linux, use bash cmd to list the child process info:
```bash
# first find sleep process id
ps aux |grep sleep

#  use lsof to show info,  if  has close-on-exec,  child-process also bind udp port 5000; else  no udp port info
lsof -nPp  $sleep_pid
```

**Comment by jimying** [comment]
> Also, are there any use cases where users will prefer the close-on-exec flag to be not set?

Yes.
a simple sample: 
parent process use socketpair() create two sock fd,
In child process: keep one fd open, and close the other one.
In this case, child process can use fd send message  to parent process.


I think:
1. In pjlib, the api pj_file_open()/pj_sock_socket()/pj_activesock_create_udp() 
should  provide setting close-on-cloexec flag

- pj_file_open()   add new flag PJ_O_CLOEXEC
- pj_sock_socket()  add new type PJ_SOCK_CLOEXEC simillar to PJ_SOCK_STREAM/PJ_SOCK_DGRAM
- pj_activesock_create_udp() , pj_activesock_cfg  add new attribute : 'pj_bool_t  sock_cloexec' 

2. in pjsip/pjmedia/pjnath, for the sock and file,  can default enable close-on-exec flag.

**Comment by jimying** [comment]
@sauwming 
@nanangizz 
https://github.com/pjsip/pjproject/issues/3550#issuecomment-1536022818  sample code is update
