### ISSUE TITLE
cross-compile pjsua2 for python for use on armv7l

### ISSUE THREAD

**Issue by aparsaeeyan** [pjsip/pjproject#3574]
### Describe the bug

When I try to cross-compile pjsua2 for python for use in armv7l, the error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)" occurs.

### Steps to reproduce

1. In the pjproject-2.13 folder, I type the following command:
./configure --prefix=$HOME/libpjsipArm --host=arm-linux-gnueabihf --disable-libwebrtc
it's OK!
2. make dep && make clean && make PROCESSOR=ARM
3. cd pjsip-apps/src/swig/python
4. make PROCESSOR=ARM
5. give me error: 
python3 setup.py build 
In file included from /home/parsaeeyan/anaconda3/envs/ENV/include/python3.10/Python.h:50:0,
                 from pjsua2_wrap.cpp:179:
/home/parsaeeyan/anaconda3/envs/ENV/include/python3.10/pyport.h:746:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^~~~~
error: command '/opt/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
make: *** [Makefile:37: _pjsua2.so] Error 1

### PJSIP version

2.13

### Context

laptop model: ASUS K555L
OS: Ubuntu 20.04

### Log, call stack, etc

```shell
In file included from /home/parsaeeyan/anaconda3/envs/ENV/include/python3.10/Python.h:50:0,
                 from pjsua2_wrap.cpp:179:
/home/parsaeeyan/anaconda3/envs/ENV/include/python3.10/pyport.h:746:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  ^~~~~
```

**Comment by sauwming** [comment]
I wonder where you get the build instruction from, since it contains unsupported option such as `make PROCESSOR=ARM`.
Note that the official instruction is here: https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

Having said that, your error seems to be related to incorrect Python variation installation. Google around for more details.
