### ISSUE TITLE
Stop Request after a set amount of retries

### ISSUE THREAD

**Issue by ODCA117** [pjsip/pjproject#3579]
### Describe the bug

Is it possible to stop a REGISTER Request after a set amount of retries
The use case is that the application want to register to a PBX. The PBX is out of service and does not reply and therefore pjsip will resend the REGISTER in a set interval (0, 0.5s, 1s, 2s, 4s,...) until the timeout (64*T1) is reached. 
Is it possible for the application to count the amount of retries sent and after, let's say 4 retries sent, stop the transmission?
So instead of letting the transmission timeout, it will stop it early.

### Steps to reproduce

Not a bug, more of a question

### PJSIP version

2.11.1

### Context

Linux

### Log, call stack, etc

```shell
nothing
```

**Comment by sauwming** [comment]
You can disable the auto registration entry using the setting `pjsua_acc_config.reg_retry_interval` and handle it on your application.
