### ISSUE TITLE
how to Stop incoming calling after we can block that contact number

### ISSUE THREAD

**Issue by shubhamparekh2000** [pjsip/pjproject#3581]
### Describe the bug

I Want to Stop the incoming calling after blocking the contact number

### Steps to reproduce

go to ContactNUmber-> block the contact number

### PJSIP version

2.13

### Context

N/A

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
If you block the number from the phone/server, it should prevent the call from reaching PJSIP.
