### ISSUE TITLE
PJSIP DON'T SEND UDP BLANK KEEP ALIVE LIKE CHAN_SIP DID

### ISSUE THREAD

**Issue by rafaelkoslop** [pjsip/pjproject#3585]
### Describe the bug

I Can't look at wireshark capture, keep alive packets after migrate chan_sip to pjsip. On chan_sip, I set up keepalive=10, and it send blank udp packets to the host and port on 10 seconds frequency.

### Steps to reproduce

.

### PJSIP version

2.10

### Context

.

### Log, call stack, etc

```shell
.
```

**Comment by sauwming** [comment]
In PJSIP, keep-alive is only sent for connection-oriented transports (TCP/TLS).
