### ISSUE TITLE
PJSIP- How to stop merge capture view in remote view in swift?

### ISSUE THREAD

**Issue by PMCME** [pjsip/pjproject#3586]
### Describe the bug

I want to display remote view in full screen and local capture view in bottom of view like whatsapp video call.
Local Capture view is started using this method - let status = pjsua_vid_preview_start(media[Int(mi)].stream.vid.cap_dev, &previewWindow)
But this view is also merge in remote view by automatically in PJSIP lib. How to stop merge remote and local video?
if i'm stop preview then also not getting capture [view.](url)
![Screen Shot 2023-06-01 at 1 12 41 PM](https://github.com/pjsip/pjproject/assets/102298201/8b762c79-1c3d-44ad-a6eb-408c4a3a2278)

### Steps to reproduce

1. run Pjsua app-> src->pjsua-> ios-swift project.
2. start preview of local capture. 

### PJSIP version

2.13

### Context

Not customize remote and local preview view. I want to display remote view in full screen and local capture view in bottom of view like whatsapp video call.

### Log, call stack, etc

```shell
No log.
```

**Comment by sauwming** [comment]
Should have been fixed by https://github.com/pjsip/pjproject/pull/3350.
Let us know if this is not the case.

**Comment by PMCME** [comment]
@sauwming  
How to change orientation of self preview view?
I'am written this code but it is not working
pjsua_vid_dev_set_setting(PJMEDIA_VID_DEFAULT_CAPTURE_DEV.rawValue,
                                          PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, pj_bool_t(PJ_TRUE.rawValue));
                                          
  Thank you!

**Comment by PMCME** [comment]
> Should have been fixed by #3350. Let us know if this is not the case.

How to change orientation of self preview view?
I'am written this code but it is not working
pjsua_vid_dev_set_setting(PJMEDIA_VID_DEFAULT_CAPTURE_DEV.rawValue,
PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, pj_bool_t(PJ_TRUE.rawValue)


@sauwming
How to change orientation of self preview view?
I'am written this code but it is not working
pjsua_vid_dev_set_setting(PJMEDIA_VID_DEFAULT_CAPTURE_DEV.rawValue,
PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, pj_bool_t(PJ_TRUE.rawValue));

Thank you!

**Comment by PMCME** [comment]
@sauwming 
Hi,
When we call IOS to IOS that time self preview is not render.
Working fine with IOS to web.

Please help me.
Thank you!
