### ISSUE TITLE
ErrorCode:520004  Invalid video device 

### ISSUE THREAD

**Issue by Riton2013** [pjsip/pjproject#3587]
### Describe the bug

My project is C# Winform program.
When I start a call with Android device, if I change default capDev like below code, the error occur

**My code:**

CallVidSetStreamParam cvssp = new CallVidSetStreamParam () ;
cvssp.capDev = 1:
this.vidSetStream(pjsua call vid strm op.PJSUA CALL VID STRM START TRANSMI, cvssp);

//vidPreview = new VideoPreview((int)pjmedia_vid_dev_std_index.PJMEDIA_VID_DEFAULT_CAPTURE_DEV);
vidPreview = new VideoPreview(1);
var isNative = vidPreview.hasNative();
VideoPreviewOpParam vidPreviewOpParam = new VideoPreviewOpParam();
vidPreviewOpParam.show = false;
//vidPreviewOpParam.rendId = (int)pjmedia_vid_dev_std_index.PJMEDIA_VID_DEFAULT_CAPTURE_DEV;
 vidPreviewOpParam.rendId = 1;
vidPreviewOpParam.window = new VideoWindowHandle();
 vidPreviewOpParam.window.handle = new WindowHandle();
 //Trace.WriteLine(this.pnlLocalView.Handle.ToString()+"   "+this.pnlLocalView.Handle.ToInt64());
 vidPreviewOpParam.window.handle.setWindow(this.CurVideoViewInfo.LocalPanelHandle);
 vidPreview.start(vidPreviewOpParam);

Android device side can see the picture, but is freezing。I try to get all camera info, and device with ID 1 exists。I test camera as well, device is good. BTW, If I set capDev = 0, everything going well.

Can anyone help me?

### Steps to reproduce

run my project and start a call

### PJSIP version

2.10

### Context

System:Windows 10
Tool:VS2019
.Net:4.7.2

### Log, call stack, etc

```shell
C++ pj::Error:
Title:       pjsua_vid_preview_start(devId, &prm)
Code:        520004
Description: Invalid video device (PJMEDIA_EVID_INVDEV)
Location:    D:\liuzhx\project\pjproject-2.10-gb2312-ok\pjsip\src\pjsua2\media.cpp:1354
```

**Comment by sauwming** [comment]
PJSIP 2.10 is quite old, so try with the latest version and check if the issue is still valid.

Also, test with the sample app to check if the problem is reproducible.
