### ISSUE TITLE
Reconduct pjsua method on_rx_notify in pjsua2

### ISSUE THREAD

**Issue by meta11ica** [pjsip/pjproject#3589]
### Describe the bug

Hello,
I'm building an application in Python with pjsua2 that supervises the state of phones (busy, idle..) in CUCM.
I'm instantiating the Buddy class and the subscription is successful. I can see the NOTIFY messages in the console logs coming from CUCM to update the application of the phones statuses.

Yet, I seeing that only two callbacks onBuddyState and onBuddyEvSubState for Buddy Class.
And unfortunately both are only triggered after the SUBSCRIBE state change. So these two methods are triggered after my app sends a TX SUBSCRIBE or TX 200OK following a received NOTIFY message. And the application always shows the monitored phones as "Online".

The method onCallState is not useful for me because it doesn't return the SIP raw message. And the method onBuddyEvSubState will never let me analyze the content of the NOTIFY message which actually contains the useful information regarding the phone's state.

I saw that in pjsua there's a method called on_rx_notify which could be the answer to my query but it seems  that it's not implemented in PJSUA2.

Is there a possibility that the on_rx_notify method in pjsua2 ?
Because the  useful information is wrapped in an XML file inside the received NOTIFY message. This is the message that my application needs to analyze to make the business logic.

Or is there a method to analyze sollicited RX SIP NOTIFY with pjsua2 ? I also tried onMwiInfo method doesn't seem to be triggered by incoming NOTIFY messages.

Thanks a lot.

### Steps to reproduce

Defined 
class MyBuddy (pj.Buddy):
   def __init__(self):
      pj.Buddy.__init__(self)
   def onBuddyState(self)
      bi = self.getInfo()
      print(" *** Buddy ", bi.uri, " is ",bi.presStatus.statusText)
   def onBuddyEvSubState(self,prm):
      bi = self.getInfo()
      print(prm.e.type) # Always returns 5 - PJSIP_EVENT_TSX_STATE
      print(prm.e.body.tsxState.tsx.lastTx.wholeMsg) # returns the TX SUBSCRIBE or TX 200OK following NOTIFY

### PJSIP version

2.13

### Context

Need to analyze sollicited SIP NOTIFY message.
However the onCallEvSubState callback is triggered only on TX SUBSCRIBE and TX 200 OK.
Need a callback on incoming NOTIFY message.
Like on_rx_notify for pjsua, but implemented in pjsua2.

### Log, call stack, etc

```shell
OnBuddyEvSubState shows the content of Transmitted SUBSCRIBE and 200 OK.
Unable to callback or analyze incoming NOTIFY message with pjsua2.
```

**Comment by sauwming** [comment]
Check `prm.e.body.tsxState.type`. If it's `PJSIP_EVENT_RX_MSG`, you can get the rdata.
