### ISSUE TITLE
about PJSUA2 get and put frame interface

### ISSUE THREAD

**Issue by pc121502806** [pjsip/pjproject#3591]
### Describe the bug

I refer to this [requests](https://github.com/pjsip/pjproject/pull/3569), pygui and test.py to build a simple sip client (using python)，and I want to get audio frame from other side, but only get myself frame when connecting, i not sure something setting wrong, these is my code:

call.py
`import pjsua2 as pj
import endpoint as ep
from audioMediaPort import AMP

class Call(pj.Call):
    def __init__(self, acc, peer_uri='', call_id = pj.PJSUA_INVALID_ID):
        pj.Call.__init__(self, acc, call_id)
        self.acc = acc
        self.peerUri = peer_uri
        self.connected = False
        
        self.amp = AMP()
        self.fmt = pj.MediaFormatAudio()
        self.fmt.type = pj.PJMEDIA_TYPE_AUDIO
        self.fmt.clockRate = 16000				# sr
        self.fmt.channelCount = 1				# mono
        self.fmt.frameTimeUsec = 30*1000			# frameSize(microseconds)
        self.fmt.bitsPerSample = 16
        self.amp.createPort("amp", self.fmt)

    def onCallState(self, prm):
    	
    	ci = self.getInfo()
    	print("==================onCallState:" + str(ci.state) + "=====================")
    	if ci.state == pj.PJSIP_INV_STATE_DISCONNECTED:
    		del self.amp

    def onCallMediaState(self, prm):
    	print("==================onCallMediaState:=====================")
    	ci = self.getInfo()
    	for mi in ci.media:
    		if mi.type == pj.PJMEDIA_TYPE_AUDIO and (mi.status == pj.PJSUA_CALL_MEDIA_ACTIVE or pj.PJSUA_CALL_MEDIA_REMOTE_HOLD):
    			m = self.getMedia(mi.index)
    			am = pj.AudioMedia.typecastFromMedia(m)
    			
    			ep.Endpoint.instance.audDevManager().getCaptureDevMedia().startTransmit(am)
    			am.startTransmit(ep.Endpoint.instance.audDevManager().getPlaybackDevMedia())
    			ep.Endpoint.instance.audDevManager().getCaptureDevMedia().startTransmit(self.amp)
    			self.amp.startTransmit(ep.Endpoint.instance.audDevManager().getPlaybackDevMedia())
`

audioMediaPort.py
`
import pjsua2 as pj
from collections import deque
import struct

class AMP(pj.AudioMediaPort):
    
    frames = deque()
    
    def onFrameRequested(self, frame):
    	
        if frame.buf.size():
            print("get frame!!")
    	"""
    	if frame.buf.size():
        	print("======onFrameRequested======")
        	# Get a frame from the queue and pass it to PJSIP
        	frame_ = self.frames.popleft()
        	frame.type = pj.PJMEDIA_TYPE_AUDIO
        	frame.buf = frame_
        	#self.process1(frame_)
		"""

    def onFrameReceived(self, frame):

        frame_ = pj.ByteVector()
        
        if frame.buf.size():
            for i in range(frame.buf.size()):
                if (i % 2 == 1):
                    #print(frame.buf[i])
                    #print(type(frame.buf[i]))
                    # Convert it to signed 16-bit integer (-32768~32767)
                    x = frame.buf[i] << 8 | frame.buf[i-1]
                    x = struct.unpack('<h', struct.pack('<H', x))[0]
                    """
                    x = int(x * 1.5)
                    if (x > 32767):
                        x = 32767
                    else:
                        if (x < -32768):
                            x = -32768
                    """
                    # Convert it to unsigned 16-bit integer (0~65536)
                    x = struct.unpack('<H', struct.pack('<h', x))[0]
                    
                    # Put it back in the vector in little endian order
                    frame_.append(x & 0xff)
                    frame_.append((x & 0xff00) >> 8)
                    
            self.frames.append(frame_)
`

### Steps to reproduce

null

### PJSIP version

2.13

### Context

os="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

### Log, call stack, etc

```shell
null
```

**Comment by sauwming** [comment]
You're connecting the media incorrectly, check pjsua2_demo for example.

Note that the Github issue is not for asking questions. Future enquiries will be immediately closed.
