### ISSUE TITLE
Imprecise documentation for functions pjsip_create_sdp_body and pjsip_create_multipart_sdp_body

### ISSUE THREAD

**Issue by lco38** [pjsip/pjproject#3593]
### Describe the bug

Documentation for pjsip_create_sdp_body and pjsip_create_multipart_sdp_body doesn't explain that second parameter (pjmedia_sdp_session *) must point to data that remains valid for the duration of the INVITE session.

### Steps to reproduce

In a function : 
- create sdp body in a stack variable
- obtain sdp session object with validate_sdp
- pass this sdp session object to pjsip_create_multipart_sdp_body
- send INVITE and return from function

When we receive remote reply with SDP, negociation engine use initial offer from tx_data and there is an error because data in stack are not longer valid.

Solution : call function pjmedia_sdp_session_clone before pjsip_create_multipart_sdp_body to get a valid sdp object.

### PJSIP version

2.13

### Context

All platforms.

### Log, call stack, etc

```shell
/**
 * This is a utility function to create SIP body for SDP content.
 *
 * @param pool          Pool to allocate memory.
 * @param sdp           SDP session to be put in the SIP message body.
 * @param p_body        Pointer to receive SIP message body containing
 *                      the SDP session.
 *
 * @return              PJ_SUCCESS on success.
 */
```

**Comment by sauwming** [comment]
I don't think that's an issue with the function documentation, since `pjsip_create_sdp_body()` is not aware what you are going to use the SDP body for.

If you put the SDP body inside a tdata, such as `tdata->msg->body = sdp_body`, it is in that moment that you need to be aware that the body will naturally need to be available during the lifetime of the `tdata`.

**Comment by lco38** [comment]
You are right. Thank you for your reply.
