### ISSUE TITLE
Unresolved external symbol _pj_ssl_cipher_get_availables

### ISSUE THREAD

**Issue by mnik17** [pjsip/pjproject#3606]
### Describe the bug

Hello,

I have a problem building the solution. I am using Visual Studio 2019 and opening `pjproject-vs14.sln` as described in the documentation. I have compiled OpenSSL from source, targeting 32-bit Windows (`VC-WIN32`). I have linked to it from the projects, which need it. When I try to build using `Release` and `Win32` build settings I get the following errors: 

```
Error	LNK2019	unresolved external symbol _pj_ssl_cipher_get_availables referenced in function _dtls_init	pjsystest	.\pjproject-master\pjsip-apps\build\libpjproject-i386-Win32-vc14-Release.lib(transport_srtp.obj)
Error	LNK1120	1 unresolved externals	pjsystest	.\pjproject-master\pjsip-apps\bin\pjsystest-i386-Win32-vc14-Release.exe	
Error	LNK2019	unresolved external symbol _pj_ssl_cipher_get_availables referenced in function _dtls_init	pjsua	.\pjproject-master\pjsip-apps\build\pjmedia-i386-Win32-vc14-Release.lib(transport_srtp.obj)
Error	LNK1120	1 unresolved externals	pjsua	.\pjproject-master\pjsip-apps\bin\pjsua-i386-Win32-vc14-Release.exe
Error	LNK2019	unresolved external symbol _pj_ssl_cipher_get_availables referenced in function _dtls_init	pjmedia_test	.\pjproject-master\pjmedia\build\pjmedia-i386-Win32-vc14-Release.lib(transport_srtp.obj)
Error	LNK1120	1 unresolved externals	pjmedia_test	.\pjproject-master\pjmedia\bin\pjmedia-test-i386-Win32-vc14-Release.exe
```

I have replaced parts of the paths with '.' for privacy reasons. I am using the latest release - `pjproject-2.13`, but the same behavior was observed by using the master branch (downloaded a few days ago).

### Steps to reproduce

1. Use Visual Studio 2019 to open pjproject-vs14.sln
2. Add OpenSSL/include as additional include dependency for the projects `pjsua` and `pjmedia`
3. Add OpenSSL/lib as additional lib directories
4. Add libcrypto.lib and libssl.lib as additional dependencies. 
5. Build with `Win32` `Release` settings

### PJSIP version

2.13

### Context

Platform is Windows 10. 

### Log, call stack, etc

```shell
See description.
```

**Comment by sauwming** [comment]
`pj_ssl_cipher_get_availables()` is defined in `pjlib/src/ssl_sock_imp_common.c`

Follow the guides:
https://docs.pjsip.org/en/latest/get-started/windows/build_instructions.html#installing-openssl
https://docs.pjsip.org/en/latest/specific-guides/security/ssl.html

**Comment by mnik17** [comment]
Apparently not defining or setting PJ_HAS_SSL_SOCK to 0 was the cause. After setting it to 1, I managed to compile it.
