### ISSUE TITLE
How to change orientation of self preview?

### ISSUE THREAD

**Issue by PMCME** [pjsip/pjproject#3607]
@sauwming  
How to change orientation of self preview view?
I'am written this code but it is not working
pjsua_vid_dev_set_setting(PJMEDIA_VID_DEFAULT_CAPTURE_DEV.rawValue,
                                          PJMEDIA_VID_DEV_CAP_ORIENTATION, &orient, pj_bool_t(PJ_TRUE.rawValue));
                                          
  Thank you!

_Originally posted by @PMCME in https://github.com/pjsip/pjproject/issues/3586#issuecomment-1588691810_

**Comment by sauwming** [comment]
If you just want to change the local view, you can simply rotate your UI view.
If you want to change the orientation of the camera, check the sample app.

Github issue is not for asking enquiries, future questions will be immediately closed.

**Comment by PMCME** [comment]
@sauwming 
Thank you!
