### ISSUE TITLE
Unable to build and install for python

### ISSUE THREAD

**Issue by bekirrr40** [pjsip/pjproject#3611]
### Describe the bug

I am trying to install pjsua2 on my windows 10 machine, I have python 2 and 3 installed. I tried to build python_pjsua with Visual Studio 2022 on my machine so I can install it and use it with python but I get this error `cannot open include file: Python.h: No such file or directory`. 
What do I need to do I need to do to be able to install it? What am I doing wrong? 

### Steps to reproduce

I tred to build the python_pjsua file on visual studio 22. I right clicked on the python_pjsua file and clicked build. 

### PJSIP version

PJSIP2

### Context

I am trying to build pjsua for python on my machine. I was trying to build the python_pjsua file on visual studio 22 

### Log, call stack, etc

```shell
`cannot open include file: Python.h: No such file or directory`
```

**Comment by sauwming** [comment]
See #3227

**Comment by omokehinde** [comment]
> See #3227

The issue is not the same. He is unable to build the python_pjsua so that he can run `python setup-vc.py install` to install it on his machine with python.
