### ISSUE TITLE
pjsua2 Concurrent upper limit for single account media

### ISSUE THREAD

**Issue by haozxuan** [pjsip/pjproject#3613]
### Describe the bug

I integrated pjsua2 on the server side for sip client. Recently, I found that when the concurrency is large (such as 100+ concurrency), [Unable to find appropriate RTP/RTCP ports combination] will appear. I read the source code, in pjsua_media.c [Line 347](https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua-lib/pjsua_media.c#L347) locates the parameter RTP_RETRY. According to my understanding, for the same account, no matter how big the port and portRange are, such as (port:4000 portRange:1000), in fact, RTP_RETRY limits the maximum port available range to only +100 (because RTP&RTC + 2), the actual available ports are only 50, if I want to increase the number of single account and concurrently send to 512, can I just adjust RTP_RETRY to 1024, or is there any hidden danger in this operation, any ideas or suggestions are welcome, thank you very much again

### Steps to reproduce

Prepare two accounts A & B, and register them with the SIP server, then use the same account, initialize 100 instances, and make an outbound call from A->B, you will see [Unable to find appropriate RTP/RTCP ports combination ]

### PJSIP version

2.13

### Context

Platform: Centos7.4
Config：config_site.h

```markdown
// for dtmf
#define PJMEDIA_TELEPHONE_EVENT_ALL_CLOCKRATES 0
// for maximum performance
#define PJ_SCANNER_USE_BITWISE       0
#undef PJ_OS_HAS_CHECK_STACK
#define PJ_OS_HAS_CHECK_STACK        0
#define PJ_LOG_MAX_LEVEL             6
#define PJ_IOQUEUE_MAX_HANDLES       1024
#define PJSIP_MAX_TSX_COUNT          ((640*1024)-1)
#define PJSIP_MAX_DIALOG_COUNT       ((640*1024)-1)
#define PJSIP_UDP_SO_SNDBUF_SIZE     (24*1024*1024)
#define PJSIP_UDP_SO_RCVBUF_SIZE     (24*1024*1024)
#define PJ_DEBUG                     1
#define PJSIP_SAFE_MODULE            0
#define PJ_HAS_STRICMP_ALNUM         0
#define PJSIP_UNESCAPE_IN_PLACE      1
#define PJSUA_MAX_CALLS              512
#define PJSUA_MAX_ACC                512
#define PJSUA_MAX_PLAYERS            512
#define PJSUA_MAX_RECORDERS          512
#define PJSUA_MAX_CONF_PORTS         (PJSUA_MAX_CALLS+2*PJSUA_MAX_PLAYERS)
```
build：./configure --enable-epoll
swig：-c++ -go -cgo -intgosize 64 -outcurrentdir -I/usr/local/include /data/pjproject-2.13/pjsip-apps/src/swig/pjsua2.i
golang : 1.20

### Log, call stack, etc

```shell
2023-06-27T10:39:40.967+0800    ERROR   class/logger.go:56              {"": "10:39:40.967          pjsua_media.c         SIP6 !..RTP socket bind() at 0.0.0.0:4192 error: Address already in use"}
2023-06-27T10:39:40.967+0800    ERROR   class/logger.go:56              {"": "10:39:40.967          pjsua_media.c         SIP6 !..RTP socket bind() at 0.0.0.0:4194 error: Address already in use"}
```

**Comment by sauwming** [comment]
Yes, you can adjust it.

The reason why it's set to that number is that because pjsua-lib is mostly designed for client side, not for server.
https://trac.pjsip.org/repos/wiki/FAQ#pjsua-lib-perf
For server apps, it's recommended to use the lower level pjsip API directly.
