### ISSUE TITLE
pjsua_transport_create() crashes when using a .p12 certificate on iOS

### ISSUE THREAD

**Issue by henlund** [pjsip/pjproject#3617]
### Describe the bug

Application crashes when setting up transport with TLS and providing a .p12 certificate containing cert, ca list and private key.

### Steps to reproduce

1. Configure transport with TLS using a .p12 certificate containing cert, ca list and private key in Swift:

let url = Bundle.main.path(forResource: "certificate", ofType: "p12")
var tlsSetting = pjsip_tls_setting()
pjsip_tls_setting_default(&tlsSetting)
tlsSetting.cert_file = pj_str(strdup(url))
tlsSetting.password = pj_str(strdup("password"))
transportConfig.tls_setting = tlsSetting
let status = pjsua_transport_create(PJSIP_TRANSPORT_TLS, &transportConfig, &transportId)

2. Application chrashes inside ssl_sock_apple.m at

*p_identity = sec_identity_create(identity);

### PJSIP version

2.13

### Context

- This issue happens on iOS 16.5.1

### Log, call stack, etc

```shell
ssl_sock_apple.m  "Ignoring supplied private key. Private key must be placed in the keychain instead."
```

However it's not clear how the private key should be added to the keychain in order for pjsip to read it. An example in the documentation would be very much appreciated.

**Comment by sauwming** [comment]
Try the steps in:
https://stackoverflow.com/questions/9418661/how-to-create-p12-certificate-for-ios-distribution

**Comment by henlund** [comment]
That link refers to how to use p12 certificates for push notifications when distributing iOS apps. I'm looking for an example how to configure pjsip for iOS using the native TLS support added here https://github.com/pjsip/pjproject/pull/2482.
