### ISSUE TITLE
Multiple SIP accounts wrong contact header in 200 OK on answer

### ISSUE THREAD

**Issue by troutkilroy** [pjsip/pjproject#3622]
### Describe the bug

PJSIP 2.12/PJSUA

1. Two active SIP account registrations - sip.domain1.com & sip.domain2.com. They were added (pjsua_acc_add) 1 then 2 on program start.
2. Call comes in on sip:DNIS@sip.domain2.com. Account 2 answers as expected.
3. PJSUA sets contact header in 200 OK to account 1 - i.e. sip:account1_name@{IP and port of account 1}. Expect account 2.
4. If you reverse the order in which the accounts are added on program start (account 2 then account 1), then 200 OK contains expected contact header for account 2.

In the attached logs, call was answered with account sip:store2_user@sip.telnyx.com, however the 200 OK contains contact address for different account (store1_user):

Contact: "Store1" <sip:store1_user@71.205.995.12:53489;ob>

### Steps to reproduce

1. Using pjsua, add two SIP registrations on two SIP accounts 1 then 2 (e.g., pjsua_acc_add())
2. Send inbound call on DID for domain 2
3. 200 OK contact header points at account 1 - expect account 2.

### PJSIP version

2.12

### Context

PJSIP 2.12/Linux

### Log, call stack, etc

```shell
 0
18:11:22.393            pjsua_acc.c  Adding account: id=Store1 <sip:store1_user@inbound65.vitelity.net>
REGISTER sip:inbound65.vitelity.net SIP/2.0
Via: SIP/2.0/UDP 71.205.995.12:53489;rport;branch=z9hG4bKPj6c527280-0fce-4af4-a433-ad87cf078bb4
Max-Forwards: 70
From: "Store1" <sip:store1_user@inbound65.vitelity.net>;tag=3ca2c355-d078-437f-8d73-d138cb99fc2b
To: "Store1" <sip:store1_user@inbound65.vitelity.net>
Call-ID: fd903a7f-4bd9-460e-bd33-6ae63d783a39
CSeq: 27523 REGISTER
Contact: "Store1" <sip:store1_user@71.205.995.12:53489;ob>
Expires: 3600
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0


REGISTER sip:sip.telnyx.com;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 192.168.52.128:60567;rport;branch=z9hG4bKPjf64b6b3c-3ef9-4fd0-9196-54262c2a3a1f;alias
Max-Forwards: 70
From: "Store2" <sip:store2_user@sip.telnyx.com>;tag=6bfbd040-3eb1-4d80-ba3f-99ef6f5f46fe
To: "Store2" <sip:store2_user@sip.telnyx.com>
Call-ID: 9841d654-d67e-475a-889b-1b6b93b8ab5f
CSeq: 40536 REGISTER
Supported: outbound, path
Contact: "Store2" <sip:store2_user@192.168.52.128:60567;transport=TCP;ob>;reg-id=1;+sip.instance="<urn:uuid:00000000-0000-0000-0000-0000a4557f11>"
Expires: 3600
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0


INVITE sip:7194444444@71.205.995.12:51752;transport=TCP;ob SIP/2.0
Record-Route: <sip:192.76.120.10;transport=tcp;r2=on;lr;ftag=6pj5DygjXm3vc>
Record-Route: <sip:10.255.0.1;transport=tcp;r2=on;lr;ftag=6pj5DygjXm3vc>
Record-Route: <sip:10.13.245.8:6050;transport=tcp;r2=on;lr;tnx=272.574>
Record-Route: <sip:10.13.245.8:6050;r2=on;lr;tnx=272.574>
Via: SIP/2.0/TCP 192.76.120.10;branch=z9hG4bKae5f.2e0ecc48b6c9e16c3516f15a6249fc1e.0;i=965
Via: SIP/2.0/TCP 10.13.245.8:6050;rport=42910;branch=z9hG4bKae5f.6147a02b9a1009825b35ec6f75ce4469.0
v:SIP/2.0/UDP 10.13.149.4:6000;received=10.13.149.4;rport=6000;branch=z9hG4bKr09K60aNv3H0D
Max-Forwards:66
f:"7199999999"<sip:7193579667@sip.telnyx.com>;tag=6pj5DygjXm3vc
t:<sip:7194444444@10.13.245.8>
i:f92ed62a-d552-4a72-8a77-b9cc405240e4
CSeq:69648359 INVITE
m:<sip:mod_sofia@10.13.149.4:6000>
Allow:INVITE,ACK,BYE,CANCEL,OPTIONS,MESSAGE,INFO,UPDATE,REFER,NOTIFY
k:timer,path
u:talk,hold,conference,refer
Privacy:none
c:application/sdp
Content-Disposition:session
l:353

**Comment by troutkilroy** [comment]
I think I understand this, and it's probably not a bug. Invite sip:7194444444@71.205.995.12:51752 simply doesn't match the domain (sip.telnyx.com) of the account it's associated with so it's defaulting to first account. I noticed that PJSUA has an on_acc_find_for_icoming() callback that can be used to add more control over account determination for inbound calls, so that will address my issue.

**Comment by wosrediinanatour** [comment]
There is an default account you can specify.
Note that the decision might be difficult in some cases. There is an order where parts if the SIP URI are checked. The user part ihas the highest prio. How should PJSUA know, that 7194444444 matches store2_user?

You could use userless accounts, but yhen the host part is crucial.

**Comment by trengginas** [comment]
What account is the incoming call assigned to? The `acc_id` of the `on_incoming_call()` callback will show this.
Once it is assigned, then it should use the the contact of that account. The complete log will show us more information.

**Comment by wosrediinanatour** [comment]
PS: Skim over ```3196 PJ_DEF(pjsua_acc_id) pjsua_acc_find_for_incoming(pjsip_rx_data *rdata)```
 in `pjsip/src/pjsua-lib/pjsua_acc.c` for more information on how incoming calls are assigned to accounts.
