### ISSUE TITLE
Unable to build on ubuntu 22.04

### ISSUE THREAD

**Issue by shubhamt619** [pjsip/pjproject#3634]
### What I've tried

I have tried following the exact steps, but I was not able to build the PJSIP library even once.

`git clone https://github.com/pjsip/pjproject.git`
`cd pjproject`
`./configure --enable-shared`
`make`
`make dep`
`sudo make install`

Now when I enter `pjsua` in the terminal, I get "Command not found"

Can someone please provide me the exact steps or a link for tutorial thats working ?

Because I have passed days and I am not able to Install this amazing work of art. I've heard and seen about all the great things It is able to do.

Please help me 🙏 

### Steps to reproduce

`git clone https://github.com/pjsip/pjproject.git
cd pjproject
./configure --enable-shared
make
make dep
sudo make install`

### PJSIP version

2.13

### Context

The issue happens on Ubuntu 22.04

### Log, call stack, etc

```shell
pjsua - Command not found.
```

**Comment by sauwming** [comment]
`ls pjsip-apps/src/bin`
