### ISSUE TITLE
Cannot install pjsua2 using pip

### ISSUE THREAD

**Issue by freakyLuffy** [pjsip/pjproject#3635]
### Describe the bug

Cannot install pjsua2 using pip

### Steps to reproduce

pip install pjsua

### PJSIP version

latest

### Context

 I am using windows 11.

### Log, call stack, etc

```shell
[freakyLuffy/Python-3.10.12-Windows] C:\Users\Himanshu\Python-3.10.12-Windows>pip install pjsua2
Collecting pjsua2
  Using cached pjsua2-2.12.tar.gz (329 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Himanshu\AppData\Local\Temp\pip-install-kq2xbi8h\pjsua2_4d64a1aed0764e6dbd818b04c3746141\setup.py", line 33, in <module>
          f = open('../../../../version.mak', 'r')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '../../../../version.mak'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by tmancill** [comment]
This issue also impacts Linux users.  Here is the output when trying to install via `pip` into a clean virtualenv on Debian `trixie` (testing):

```
(venv) (trixie-amd64-sbuild)root@lark:/tmp# pip3 install pjsua2
Collecting pjsua2
  Downloading pjsua2-2.12.tar.gz (329 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 329.8/329.8 kB 5.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/tmp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1ksartvi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-1ksartvi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-1ksartvi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-1ksartvi/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '../../../../version.mak'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(venv) (trixie-amd64-sbuild)root@lark:/tmp# 

```

**Comment by rodrigomartins806** [comment]
I was able to install PJSIP and I can enter its command line in Linux, I followed these steps here that worked for me
1) I gave a wget to the file that is on the official page https://www.pjsip.org/download.htm
 wget https://github.com/pjsip/pjproject/archive/refs/tags/2.13.1.tar.gz

 2) Then I gave the following commands

 tar -xzf 2.11.tar.gz
cd pjproject-2.11

3) Configure and compile
./configure CFLAGS="-DNDEBUG -DPJ_HAS_IPV6=1" --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --enable-shared --disable-sound --disable-video
make dep
make up
sudo make install

Environment Setting:
Open a terminal. You can do this by pressing Ctrl + Alt + T.

Run the following command to open the .bashrc file in the nano text editor:

bash
Copy code
nano ~/.bashrc
Navigate to the end of the file and add the following line:

bash
Copy code
export LD_LIBRARY_PATH=/usr/local/lib
Press Ctrl+O to save the file, then press Enter.

Press Ctrl + X to exit the nano editor.

To apply the changes to your environment, run the following command:

bash
Copy code
source ~/.bashrc
Your environment is now configured to find the PJSIP libraries.

But when I try to run my python code it complains that the pjsua library is not installed, I believe that a small detail is missing, I tried to install it with pip and I got the following error

`Defaulting to user installation because normal site-packages is not writeable
Collecting pjsua2
  Using cached pjsua2-2.12.tar.gz (329 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pjsua2
  Building wheel for pjsua2 (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      copying pjsua2.py -> build/lib.linux-x86_64-3.10
      running build_ext
      building '_pjsua2' extension
      creating build/temp.linux-x86_64-3.10
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c pjsua2_wrap.cpp -o build/temp.linux-x86_64-3.10/pjsua2_wrap.o
      In file included from /usr/local/include/pj/limits.h:27,
                       from /usr/local/include/pj/types.h:33,
                       from /usr/local/include/pjsip/sip_config.h:26,
                       from /usr/local/include/pjsip/sip_types.h:33,
                       from /usr/local/include/pjsip.h:23,
                       from /usr/local/include/pjsua-lib/pjsua.h:29,
                       from /usr/local/include/pjsua2/config.hpp:25,
                       from /usr/local/include/pjsua2/types.hpp:30,
                       from /usr/local/include/pjsua2/persistent.hpp:25,
                       from /usr/local/include/pjsua2/endpoint.hpp:25,
                       from /usr/local/include/pjsua2.hpp:21,
                       from pjsua2_wrap.cpp:3475:
      /usr/local/include/pj/compat/limits.h:38:4: warning: #warning "limits.h is not found or not supported. LONG_MIN and LONG_MAX " "will be defined by the library in pj/compats/limits.h and " "overridable in config_site.h" [-Wcpp]
         38 | #  warning "limits.h is not found or not supported. LONG_MIN and LONG_MAX " \
            |    ^~~~~~~
      pjsua2_wrap.cpp:8940:10: fatal error: pjsua2_wrap.h: Arquivo ou diretório inexistente
       8940 | #include "pjsua2_wrap.h"
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pjsua2
  Running setup.py clean for pjsua2
Failed to build pjsua2
Installing collected packages: pjsua2
  Running setup.py install for pjsua2 ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for pjsua2 did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      make: helper.mak: Arquivo ou diretório inexistente
      make: *** Sem regra para processar o alvo 'helper.mak'.  Pare.
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      copying pjsua2.py -> build/lib.linux-x86_64-3.10
      running build_ext
      building '_pjsua2' extension
      creating build/temp.linux-x86_64-3.10
      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c pjsua2_wrap.cpp -o build/temp.linux-x86_64-3.10/pjsua2_wrap.o
      In file included from /usr/local/include/pj/limits.h:27,
                       from /usr/local/include/pj/types.h:33,
                       from /usr/local/include/pjsip/sip_config.h:26,
                       from /usr/local/include/pjsip/sip_types.h:33,
                       from /usr/local/include/pjsip.h:23,
                       from /usr/local/include/pjsua-lib/pjsua.h:29,
                       from /usr/local/include/pjsua2/config.hpp:25,
                       from /usr/local/include/pjsua2/types.hpp:30,
                       from /usr/local/include/pjsua2/persistent.hpp:25,
                       from /usr/local/include/pjsua2/endpoint.hpp:25,
                       from /usr/local/include/pjsua2.hpp:21,
                       from pjsua2_wrap.cpp:3475:
      /usr/local/include/pj/compat/limits.h:38:4: warning: #warning "limits.h is not found or not supported. LONG_MIN and LONG_MAX " "will be defined by the library in pj/compats/limits.h and " "overridable in config_site.h" [-Wcpp]
         38 | #  warning "limits.h is not found or not supported. LONG_MIN and LONG_MAX " \
            |    ^~~~~~~
      pjsua2_wrap.cpp:8940:10: fatal error: pjsua2_wrap.h: Arquivo ou diretório inexistente
       8940 | #include "pjsua2_wrap.h"
            |          ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pjsua2

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by sauwming** [comment]
Please use the recommended guide instead:
https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

**Comment by tmancill** [comment]
Hi @sauwming .  Would it be possible to take down the pjsua page on PyPi (https://pypi.org/project/pjsua/)?   That may prevent others from running into the same issues.

**Comment by sauwming** [comment]
As you can probably see from the version and the year (2.2.1 year 2014), the page is very outdated. It was created by a third party and not by us so I'm not sure how to take it down.

If you know how to contact the maintainer, please feel free to do so, citing this PR as a reference.

**Comment by rodrigomartins806** [comment]
Hello, even following the link provided previously, I am having this error here when I try to import the library in Python

>>> import pjsua2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pjsua2'


I'm in a Debian 11 environment, Python3.9, and I have FreeSwitch installed on this same machine,

**Comment by rodrigomartins806** [comment]
Hello, thank you for the guidance on the correct documentation link, this really needs to be corrected as it caused confusion in the installation process, thank you for your help.

**Comment by rodrigomartins806** [comment]
Where can I post a question and request for help about answering and making calls using pjsua2 and python?

**Comment by semirke** [comment]
> Please use the recommended guide instead: https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

Hi,
this method fails miserably. Using Ubuntu.

pjproject/pjsip-apps/src/swig/python$ python setup.py install
helper.mak:2: /build/common.mak: No such file or directory
make: *** No rule to make target '/build/common.mak'.  Stop.
helper.mak:2: /build/common.mak: No such file or directory
make: *** No rule to make target '/build/common.mak'.  Stop.
helper.mak:2: /build/common.mak: No such file or directory
make: *** No rule to make target '/build/common.mak'.  Stop.
helper.mak:2: /build/common.mak: No such file or directory
make: *** No rule to make target '/build/common.mak'.  Stop.
/home/andras/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/dist.py:289: InformationOnly: Normalizing '2.15-dev' to '2.15.dev0'
  self.metadata.version = self._normalize_version(self.metadata.version)
running install
/home/andras/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/andras/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating pjsua2.egg-info
writing pjsua2.egg-info/PKG-INFO
writing dependency_links to pjsua2.egg-info/dependency_links.txt
writing top-level names to pjsua2.egg-info/top_level.txt
writing manifest file 'pjsua2.egg-info/SOURCES.txt'
file pjsua2.py (for module pjsua2) not found
reading manifest file 'pjsua2.egg-info/SOURCES.txt'
writing manifest file 'pjsua2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file pjsua2.py (for module pjsua2) not found
file pjsua2.py (for module pjsua2) not found
running build_ext
building '_pjsua2' extension
creating build
creating build/temp.linux-x86_64-cpython-310
gcc -pthread -B /home/andras/miniconda3/envs/whisperx/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/andras/miniconda3/envs/whisperx/include -fPIC -O2 -isystem /home/andras/miniconda3/envs/whisperx/include -fPIC -I/home/andras/miniconda3/envs/whisperx/include/python3.10 -c pjsua2_wrap.cpp -o build/temp.linux-x86_64-cpython-310/pjsua2_wrap.o
cc1plus: fatal error: pjsua2_wrap.cpp: No such file or directory
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by semirke** [comment]
> Please use the recommended guide instead: https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

Hi there,
the recommended method seems to fail miserably:
```

pjproject/pjsip-apps/src/swig/python$ python setup.py install
/home/andras/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/dist.py:289: InformationOnly: Normalizing '2.15-dev' to '2.15.dev0'
  self.metadata.version = self._normalize_version(self.metadata.version)
running install
/home/andras/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/andras/miniconda3/envs/whisperx/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing pjsua2.egg-info/PKG-INFO
writing dependency_links to pjsua2.egg-info/dependency_links.txt
writing top-level names to pjsua2.egg-info/top_level.txt
file pjsua2.py (for module pjsua2) not found
reading manifest file 'pjsua2.egg-info/SOURCES.txt'
writing manifest file 'pjsua2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file pjsua2.py (for module pjsua2) not found
file pjsua2.py (for module pjsua2) not found
running build_ext
building '_pjsua2' extension
gcc -pthread -B /home/andras/miniconda3/envs/whisperx/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/andras/miniconda3/envs/whisperx/include -fPIC -O2 -isystem /home/andras/miniconda3/envs/whisperx/include -fPIC -I/home/andras/miniconda3/envs/whisperx/include/python3.10 -c pjsua2_wrap.cpp -o build/temp.linux-x86_64-cpython-310/pjsua2_wrap.o -g -O2 -DPJ_AUTOCONF=1 -O2 -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1 -DPJMEDIA_USE_OLD_FFMPEG=1 -DPJMEDIA_USE_OLD_FFMPEG=1 -I/home/andras/agent/pjproject/pjlib/include -I/home/andras/agent/pjproject/pjlib-util/include -I/home/andras/agent/pjproject/pjnath/include -I/home/andras/agent/pjproject/pjmedia/include -I/home/andras/agent/pjproject/pjsip/include
cc1plus: fatal error: pjsua2_wrap.cpp: No such file or directory
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
```
