### ISSUE TITLE
PJSUA Android Preview SurfaceView is not showing as Mirrored

### ISSUE THREAD

**Issue by CommuniG8** [pjsip/pjproject#3645]
### Describe the bug

This is my first PJSIP Issue and I accept that it my be better on a discussion forum but I cant seem to find one.

I have an Android App that has been using PJSIP/PJSUA2 for some time but only with Voice calls. I am adding Video support, which is working perfect OK with the exception of one small issue. When using an Android SurfaceView for a VideoPreview with the local front facing Camera, the video is not left-right mirrored as I would normally expect for a preview. I could not find a method to change this behaviour. Applying changes such as the orientation, e.g. rotating through 90 degrees works fine.

### Steps to reproduce

Java Code snippet used...

VideoWindowHandle vidPrevWH = new VideoWindowHandle();
vidPrevWH.getHandle().setWindow(surfacePreview.getHolder().getSurface());
VideoPreviewOpParam videoPreviewOpParam = new VideoPreviewOpParam();
videoPreviewOpParam.setWindow(vidPrevWH);
videoPreviewOpParam.setShow(true);
VideoPreview vidPreview = new VideoPreview(1);
vidPreview.start(videoPreviewOpParam);

I have exclude try/catch code for clarity.

### PJSIP version

2.10

### Context

Android 10 Tablet

### Log, call stack, etc

```shell
No errors are logged
```

**Comment by trengginas** [comment]
You can use TextureView instead of SurfaceView to be able to mirror the preview image. 
See : https://stackoverflow.com/questions/10388789/how-to-keep-android-from-inverting-the-image-from-the-front-facing-camera/17570037

**Comment by CommuniG8** [comment]
Yes, I've seen the info on TextureView but I don't get why the preview is not mirrored anyway from that start. That post is really about unmirroring.

**Comment by trengginas** [comment]
The library is using the image captured from the camera (not mirrored). If you want to show unmirrored image, you need to do it on the preview side.

**Comment by trengginas** [comment]
The main thing is, the library will get the image provided by the camera (either it's mirrored or not). There's no modification on the library side, so this is not a bug. If you want to show it differently, it should be done on the preview side.
