### ISSUE TITLE
IOS- Not getting busy  status  in on_call_state callback function if call is busy or connected with some one.

### ISSUE THREAD

**Issue by PMCME** [pjsip/pjproject#3647]
### Describe the bug

we implement below callback method but not getting busy status.

func on_call_state(call_id: pjsua_call_id, e: UnsafeMutablePointer<pjsip_event>?) {
    var ci = pjsua_call_info();
    pjsua_call_get_info(call_id, &ci);
    print("on call state: \(ci.state_text)")
    print("on call state code :\(ci.last_status.rawValue)")
    if ci.last_status == PJSIP_SC_BUSY_HERE {
        print("call is busy")
    }
}

### Steps to reproduce

N/A

### PJSIP version

2.13

### Context

NA

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
I tested it with our sample app and it seems to work fine.
`09:29:23.336            pjsua_app.c  .....Call 0 is DISCONNECTED [reason=486 (Busy Here)]`
