### ISSUE TITLE
IOS Application is crash when Queue call

### ISSUE THREAD

**Issue by PMCME** [pjsip/pjproject#3654]
### Describe the bug

if i'm dial specific number it is automatically redirect particular number  that time application crash on media.

<img width="1643" alt="image_2023_08_09T04_34_33_320Z" src="https://github.com/pjsip/pjproject/assets/102298201/c9ec7f3e-30b8-4ca4-9d4c-eb677a0fc6e4">

### Steps to reproduce

1: When Dial number which is forwarding to another call that time crash application

### PJSIP version

2.13

### Context

N/A

### Log, call stack, etc

```shell
Bad access on thread
```

**Comment by sauwming** [comment]
Test with the sample app.
Enable debugging info (build PJSIP with `-g`) and give us the stack trace within `on_clock_tick()` to show us exactly at which line the crash occurred.

If you have test accounts that we can use, let us know so we can try it here.

**Comment by PMCME** [comment]
ok

**Comment by phamsontm9x** [comment]
Hi @sauwming , i have same isssue. 
I have log:
Assertion failed: (dst_port && dst_port->port && dst_port->port->put_frame), function op_connect_ports, file vid_conf.c, line 829.

**Comment by phamsontm9x** [comment]
Hi @sauwming , when i answered video call in background. Application crash in file vid_conf.c

**Comment by sauwming** [comment]
> @sauwming How to test with -g option any reference document?

https://docs.pjsip.org/en/latest/get-started/posix/build_instructions.html#build-customizations
```
export CFLAGS += -g
export LDFLAGS += -g
```

**Comment by sauwming** [comment]
> Hi @sauwming , i have same isssue.
> I have log:
> Assertion failed: (dst_port && dst_port->port && dst_port->port->put_frame), function op_connect_ports, file vid_conf.c, line 829.

Your issue seems to be different.
Video doesn't work in the background, so you should only enable video when in the foreground.

**Comment by PMCME** [comment]
> on_clock_tick



> > @sauwming How to test with -g option any reference document?
> 
> https://docs.pjsip.org/en/latest/get-started/posix/build_instructions.html#build-customizations
> 
> ```
> export CFLAGS += -g
> export LDFLAGS += -g
> ```

Hi @sauwming 
if add this 2 flag in .mak file make call function is not working.

**Comment by PMCME** [comment]
> > @sauwming How to test with -g option any reference document?
> 
> https://docs.pjsip.org/en/latest/get-started/posix/build_instructions.html#build-customizations
> 
> ```
> export CFLAGS += -g
> export LDFLAGS += -g
> ```

Hi @sauwming 
 i test with add flag but  not working call method.
 on_call_media_state callback is not execute and also video is  not display.

**Comment by PMCME** [comment]
@sauwming 
Here, sample code attach: https://drive.google.com/file/d/1iLvN9yyy4ifBn1wBTFyupmqJw_pFA2Qn/view?usp=sharing.

Please follow below step:
1. Login with 1001  in this website https://vid.dics.se/jssip
2. Run application  and login with 1013
3. Call with Destination 4500
4. after crash application.

**Comment by sauwming** [comment]
For security issue, I did not use your app, but I tested it with our own sample app, and the same setup seemed to work fine (i.e. no crash).
```
  [CONFIRMED] To: sip:4500@fs.dics.se;tag=Zj1NS6pBr6yKH
    Call time: 00h:00m:36s, 1st res in 821 ms, conn in 2158ms
    #0 audio opus @48kHz, sendrecv, peer=16.16.85.22:27268
       RX pt=96, last update:00h:00m:00.471s ago
          total 1.8Kpkt 197.8KB (270.6KB +IP hdr) @avg=41.5Kbps/56.8Kbps
       TX pt=96, ptime=20, last update:00h:00m:00.629s ago
          total 1.9Kpkt 200.0KB (276.2KB +IP hdr) @avg=42.0Kbps/58.0Kbps
    #1 video H264, sendrecv, peer=16.16.85.22:23526
       RX pt=98, size=192x128, fps=15.00, last update:00h:00m:02.904s ago
          total 580pkt 198.3KB (221.5KB +IP hdr) @avg=41.7Kbps/46.6Kbps
       TX pt=98, size=720x480, fps=15.00, last update:00h:00m:00.311s ago
          total 1.5Kpkt 1.63MB (1.69MB +IP hdr) @avg=344.3Kbps/357.4Kbps
```

I would suggest to try to reproduce it with our sample app, and you need to find out what you do differently in your app that triggers the issue.

**Comment by PMCME** [comment]
@sauwming 
Can you provide me sample app link? i'm using sample app which is attach in git.
did you added this two flag?
export CFLAGS += -g
export LDFLAGS += -g

or any other configuration do you implement?
Thank You.

**Comment by sauwming** [comment]
Just try to reproduce it with the sample app, if you can do so,  you don't need to worry about the debugging flag (-g). 

Yes, the sample app is the one provided in the git. Refer to the doc for more details.

**Comment by PMCME** [comment]
@sauwming 
App will be crash when 2 call establish successfully after call is added in conference that time app is crash.

**Comment by PMCME** [comment]
@sauwming 
Using ESL bridge we are connect  in  as conference call that time app will be crash.
Please follow step:

 1. Login in this website  https://dev.dics.se/ with below credential:
       Username : dipesh.cmexpertise@gmail.com
       Password:  123456
 2.  Run application and login with 1014
 3.  Call with Destination 919723840340
 4. App will crash after 15 seconds.

<img width="1728" alt="Screenshot 2023-09-04 at 11 39 41 AM" src="https://github.com/pjsip/pjproject/assets/102298201/aa66b698-2907-4c7c-ac15-8b29bf41e386">
    
Thank you

**Comment by PMCME** [comment]
Hi @sauwming 
any update for this issue, i.m stuck in this crash.
Please check it.

Any help will be highly appreciated.
Thank you.

**Comment by sauwming** [comment]
I just got back from my leave.
The account is now Forbidden, so I can't use it.

But from your latest log, it seems that it may not be ready to receive high res video (1920x1080). You need to modify this:
https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia-codec/vid_toolbox.m#L46

Make sure you check the doc as well:
https://docs.pjsip.org/en/latest/specific-guides/video/users_guide.html

**Comment by PMCME** [comment]
@sauwming 
Thank you so much!

**Comment by PMCME** [comment]
@sauwming 
I set this res video (1920x1080) in vid_toolbox.m but still crash application.
here attach my log file.

[CrashReport.pdf](https://github.com/pjsip/pjproject/files/12673239/CrashReport.pdf)

Please check this report.
Thank you.

**Comment by sauwming** [comment]
> Make sure you check the doc as well: https://docs.pjsip.org/en/latest/specific-guides/video/users_guide.html

**Comment by PMCME** [comment]
@sauwming 
is it FPS rate issue? i changed and check but still not working.

Any help will be highly appreciated.
Thank you.

**Comment by PMCME** [comment]
@sauwming 
I am stuck on this issue, I Tried everything needed in library, 
If you can help with this, It's really very helpful.
Thanks.

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/specific-guides/video/users_guide.html#size-or-resolution
