### ISSUE TITLE
PJSIP 2.11.1 echo issue on speaker

### ISSUE THREAD

**Issue by askari01** [pjsip/pjproject#3657]
### Describe the bug

When AVAudioSession is used with default mode the echo is unbearable. Even PJSIP software echo cancellation is of no use.
When AVAudioSession is used with voicechat mode the echo is not there but the speaker looses it potential loudness. 

### Steps to reproduce

1. ensure AVAudioSession category is .playAndRecord, and .default is the mode, with the option .defaultToSpeaker.

### PJSIP version

2.11.1

### Context

- the issue occurs when call AVSession is put to speaker

### Log, call stack, etc

```shell
can be provided. but it doesn't log any error.
```

**Comment by askari01** [comment]
hi, can you provide input regarding the approach for setting up rx/tx level as it still doesn't solve the problem. @sauwming

**Comment by sauwming** [comment]
You need to elaborate further about "no desired result". Is the volume not loud enough (but is there any difference in the volume or not at all)? Or is it about the echo?

**Comment by askari01** [comment]
echo is our issue, with pjsip 2.11.1 on iOS
- we are using AVAudioSession with default mode and it causes echo in the call.
- we used AVAudioSession with voice chat mode, it removes the echo but this causes the microphone to become insensitive / not work properly. 
so as per your advice we tried amplifying the input and output signals on pjsip, also increase the input grain to max value of 1 on iOS but this doesn't solve our problem. 
we have tried using pjsip software echo cancellation and using different bands priorities for the call but none has help us to get rid of the echo from the call.

**Comment by sauwming** [comment]
> * we used AVAudioSession with voice chat mode, it removes the echo but this causes the microphone to become insensitive / not work properly. So as per your advice we tried amplifying the input and output signals on pjsip, also increase the input grain to max value of 1 on iOS but this doesn't solve our problem. No audio on the out door station when call is placed between mobile and an intercom. for call between mobiles the user needs to place phone microphones to his lips on speaker turned on.

The max value is not 1.0. In fact, as the doc says, 1 means no level adjustment.

No audio is a completely different problem. Check the docs: docs.pjsip.org for troubleshooting.
