### ISSUE TITLE
Consider renaming branch 2.13.1 different from tag 2.13.1 in this repo

### ISSUE THREAD

**Issue by space88man** [pjsip/pjproject#3658]
### Describe the bug

Having a branch (2.13.1) named the same as a tag (2.13.1) does cause difficulty in tooling.

For 2.11.x and 2.12.x the branches were named support-2.11.1 and support-2.12.1 to differentiate them from the tags.

If we mirror and host on gitlab this describes some tooling issues: https://gitlab.com/gitlab-org/gitlab/-/issues/219583

### Steps to reproduce

1. checkout git repo
2. observe there is a branch 2.13.1 with the same name as tag 2.13.1

This causes difficulty in some tooling that is not expecting this.

Previously we had support-2.11.1 / support-2.12.1 for other tags

### PJSIP version

2.13.1

### Context

Development from GH repo

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
Done. Thanks for the suggestion.
