### ISSUE TITLE
Android ANR in pjsua_transport_create

### ISSUE THREAD

**Issue by ArtsemKurantsou** [pjsip/pjproject#3665]
### Describe the bug

In some cases, pjsua_transport_create takes 20-40 seconds or more which leads to ANR on Android if called from the main thread (as it is done in a sample application).

It seems like the issue is with TLS6 transport creation and TLS transport created quickly enough. 

### Steps to reproduce

Call `pjsua_transport_create` for _TLS_ and _TLS6_ and port **443** from the main thread.

### PJSIP version

2.13

### Context

A router that an Android device is connected to has dual-stack IP (IPv4 and IPv6) enabled.

Platform - Android (no specific version)
Device - No specific device
ABIs - both arm64-v8a and armeabi-v7a

NDK - 13b
OpenSSL - 1.1.1t
OpenH264 - 2.1.0
Opus - 1.2.1

config_site.h
```C
#define PJ_CONFIG_ANDROID 1
#define PJMEDIA_HAS_VIDEO 1
#define PJ_HAS_IPV6 1
#define PJMEDIA_CODEC_OPUS_DEFAULT_BIT_RATE 32000
#define PJMEDIA_RTP_PT_TELEPHONE_EVENTS 121
#define SIP_USE_ICE 1
#define PJSUA_MAX_ACC 50
#define PJSUA_MAX_CALLS 75
#define PJSIP_TRANSPORT_IDLE_TIME 100
#define PJMEDIA_RTCP_FB_INTERVAL 500
#define PJMEDIA_VID_STREAM_SKIP_PACKETS_TO_REDUCE_LATENCY 1
#define PJ_MAX_HOSTNAME (512)
#define PJSIP_MAX_URL_SIZE 1024
#define PJSIP_MAX_PKT_LEN 8000
#define PJMEDIA_STREAM_ENABLE_KA PJMEDIA_STREAM_KA_USER

#include <pj/config_site_sample.h>
```

### Log, call stack, etc

Stacktrace from Crashlytics
```shel
main (native):tid=1 systid=25539 
#00 pc 0xdc0b8 libc.so (read + 8) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#01 pc 0xe7f34 libc.so (__sread + 48) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#02 pc 0xe7e18 libc.so (__srefill + 264) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#03 pc 0xec4ac libc.so (fread_unlocked + 208) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#04 pc 0xec394 libc.so (fread + 76) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#05 pc 0xa70e8 libc.so (android_getaddrinfo_proxy + 336) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#06 pc 0xa6d64 libc.so (android_getaddrinfofornetcontext + 1620) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#07 pc 0xa667c libc.so (getaddrinfo + 56) (BuildId: 2f03e284efbab0171cd8e23648eb35f3)
#08 pc 0x551be0 split_config.arm64_v8a.apk (pj_getaddrinfo + 604) (BuildId: bd55a2dfd3e2826c9fcafbd2a5b6eba43ae8683b)
#09 pc 0x55f5b0 split_config.arm64_v8a.apk (pj_gethostip + 284) (BuildId: bd55a2dfd3e2826c9fcafbd2a5b6eba43ae8683b)
#10 pc 0x3c0b34 split_config.arm64_v8a.apk (update_factory_addr + 22704128) (BuildId: bd55a2dfd3e2826c9fcafbd2a5b6eba43ae8683b)
#11 pc 0x3c0388 split_config.arm64_v8a.apk (pjsip_tls_transport_lis_start + 456) (BuildId: bd55a2dfd3e2826c9fcafbd2a5b6eba43ae8683b)
#12 pc 0x3c0138 split_config.arm64_v8a.apk (pjsip_tls_transport_start2 + 1008) (BuildId: bd55a2dfd3e2826c9fcafbd2a5b6eba43ae8683b)
#13 pc 0x3536bc split_config.arm64_v8a.apk (pjsua_transport_create + 1812) (BuildId: bd55a2dfd3e2826c9fcafbd2a5b6eba43ae8683b)
```

**Comment by nanangizz** [comment]
It looks like it stucks in resolving local hostname (`pj_getaddrinfo(gethostname())`). Unfortunately currently there is no configurable setting to set the timeout. However, the library has some alternatives to get the local IPv6 address and the `pj_getaddrinfo()` can be skipped by setting `PJ_GETHOSTIP_DISABLE_LOCAL_RESOLUTION` to `1` in `config_site.h`. Another workaround is that app manually resolves the local IPv6 address and using it in creating the transport (for [pjsua_transport_config.bound_addr](https://docs.pjsip.org/en/latest/api/generated/pjsip/group/group__PJSUA__LIB__TRANSPORT.html#_CPPv4N22pjsua_transport_config10bound_addrE) and/or [pjsua_transport_config.public_addr](https://docs.pjsip.org/en/latest/api/generated/pjsip/group/group__PJSUA__LIB__TRANSPORT.html#_CPPv4N22pjsua_transport_config11public_addrE)).
