### ISSUE TITLE
IOS- Remote video stream is black after app goes to background

### ISSUE THREAD

**Issue by PMCME** [pjsip/pjproject#3667]
### Describe the bug

Remote video stream is black or pause a video while app open from the background.

### Steps to reproduce

Steps:
 1. Start a call
 2. Move to app in background
 3. Open app from the background
   or
 4. Lock device and open app from the background.
 

### PJSIP version

2.13

### Context

N/A

### Log, call stack, etc

```shell
N/A
```

**Comment by kevinkouketsu** [comment]
Maybe you should send a keyframe right after the app comes to the foreground. This is likely happening because the keyframes are lost while the app is in the background. Try placing your finger in front of the camera to see if it generates the keyframe and if the image shows up again.

**Comment by PMCME** [comment]
@kevinkouketsu  Can you share me reference document or link?

**Comment by PMCME** [comment]
@kevinkouketsu 
I written below code but not getting success.
var ci = pjsua_call_info();
        pjsua_call_get_info(incomingCallID, &ci);
        if ci.id >= 0 {
            print("encoding video")
            let operation =  PJSUA_CALL_VID_STRM_SEND_KEYFRAME
            var param = pjsua_call_vid_strm_op_param()
            pjsua_call_vid_strm_op_param_default(&param)
            param.med_idx = pjsua_call_get_vid_stream_idx(ci.id)
            param.dir =  PJMEDIA_DIR_ENCODING_DECODING
            let success =  pjsua_call_set_vid_strm(ci.id, operation, &param)
            if success == PJ_SUCCESS.rawValue {
                print("Start to Stream")
                
            }
        }

**Comment by sauwming** [comment]
Disable video when app goes to bg, and re-enable it when in fg.
