### ISSUE TITLE
Undefined behavior in Rust bindings

### ISSUE THREAD

**Issue by JRazek** [pjsip/pjproject#3670]
### Undefined behavior in Rust bindings

https://github.com/pjsip/pjproject/blob/d51e2471352bfb6fff216ec536a5aec907e1fc01/pjsip-apps/src/rust/demo/src/main.rs#L27-L28
This is undefined behavior. 
Borrow checker wont help you in this unsafe case.

Once calling `uninit()`, variable should be stored somewhere, then `as_ptr_mut()` result  may be dereferenced ONLY as long as this `uninit()` result is alive. Here it is not.

Even though it works and runs as desired (at least on my machine), this is purely by luck.

This holds for all the usages after dropping in the #3275

**Comment by JadKHaddad** [comment]
would you like to fix it?
