### ISSUE TITLE
Sample iOS apps not working with Xcode 14.3.1

### ISSUE THREAD

**Issue by brianomchugh** [pjsip/pjproject#3682]
### Describe the bug

I am able to compile PJSIP according to the iOS instructions, but I can't get any of the sample apps to work (PJSIP is not linked/set up properly). See the attached image when I try to run the Swift/pjsua2 sample app:
<img width="550" alt="Screenshot 2023-09-01 at 10 50 13 AM" src="https://github.com/pjsip/pjproject/assets/921750/2fe61917-b9aa-492b-8214-1c9e4112aa4b">

I have similar issues with the other iOS sample apps. Can anyone confirm that these are up to date for Xcode 14.3.1?

### Steps to reproduce

1. compile PJSIP from source and then open ios-swift-pjsua2.xcodeproj in Xcode 14.3.1.
2. Try to build app

### PJSIP version

2.13

### Context

MacOS Desktop
Xcode 14.3.1

### Log, call stack, etc

```shell
Undefined symbol: __nw_content_context_default_message
Undefined symbol: __nw_parameters_configure_protocol_default_configuration
Undefined symbol: _nw_connection_copy_current_path
```
```

**Comment by ednt** [comment]
You need to set the header search path and the lib search path in xcode under Target ->  Build Settings -> Search Paths and add the compiled binary under Target ->  Build Phases -> Link Binary With Library.

**Comment by brianomchugh** [comment]
> You need to set the header search path and the lib search path in xcode under Target -> Build Settings -> Search Paths and add the compiled binary under Target -> Build Phases -> Link Binary With Library.

Thanks for the reply. The values were both already set up in the sample app(as shown below), and the paths do seem to point to the right place (since I did not change the directory structure or anything after compiling).
![Screenshot 2023-09-01 at 12 12 06 PM](https://github.com/pjsip/pjproject/assets/921750/fd1ddceb-382c-47a0-9334-d5c13955a0de)
