### ISSUE TITLE
How to enable calling in Background mode for iOS swift project

### ISSUE THREAD

**Issue by Washyl** [pjsip/pjproject#3688]
### Describe the bug

Hello everyone.
I have built simple SIP client iOS app.
I need only outbound call feature only and it is working well in foreground.
But calling is stopped when app is in background.
How to solve this problem?
I am a beginner swift and pjsip library.
Please help me 

### Steps to reproduce

void threadFunction(void* arg) {
    CallOpParam prm(true); // Use default call settings
    try {
    call = new MyCall(*acc);
    call->makeCall(destURI, prm);
//    call->makeCall(dest_uri, prm);
    } catch(Error& err) {
    std::cout << err.info() << std::endl;
    }
}

void PJSua2::outgoingCall(std::string dest_uri) {
//    pthread_t callThread;
//    pthread_create(&callThread, nullptr, &threadWrapper, NULL);
    destURI = dest_uri;
    pj_caching_pool cp;
    pj_thread_t* thread = NULL;
    pj_thread_desc desc;

    pj_status_t status;

    status = pj_init();
    if (status != PJ_SUCCESS) {
        // Handle initialization error
    }

    pj_caching_pool_init(&cp, NULL, 0);
    pj_thread_register(NULL, desc, &thread);
    
    **pj_thread_create(NULL, "new", (pj_thread_proc*)threadFunction, NULL, 0, 0, &thread);//Thread 1: signal SIGABRT**

}

### PJSIP version

2.9

### Context

- iPhone 14
- PJSIP with Cocoa POD

### Log, call stack, etc

```shell
02:19:51.141         os_core_unix.c !Info: possibly re-registering existing thread
Assertion failed: (pool && proc && ptr_thread), function pj_thread_create, file ../src/pj/os_core_unix.c, line 570.
```

**Comment by sauwming** [comment]
Use the latest version, and try with the sample app.

**Comment by Washyl** [comment]
Hi sauming
Thanks for your reply. 
Yes, it is working on background mode
i have a question too.
Does not pjsip support the apple watch os?
if not, how can build the sip client app in watch os without iphone app

**Comment by Washyl** [comment]
Hi sauming
Thanks for your reply. 
Yes, it is working on background mode
i have a question too.
Does not pjsip support the apple watch os?
if not, how can build the sip client app in watch os without iphone app?

**Comment by Washyl** [comment]
> Use the latest version, and try with the sample app.

Hi sauming
Thanks for your reply.
Yes, it is working on background mode
i have a question too.
Does not pjsip support the apple watch os?
if not, how can build the sip client app in watch os without iphone app
