### ISSUE TITLE
Sometimes pure IPv6 network and no decision of transport/uri fails to set transport

### ISSUE THREAD

**Issue by ednt** [pjsip/pjproject#3689]
### Describe the bug

We can access the PBX via IPv4 and IPv6.
Our company WLAN uses only IPv6.
We don't set the transport in the account and the uri uses a name and no ip address.

At start we create 2 transports: one for IPv4 and one for IPv6

PJSUA fails to set the contact when we are in the pure IPv6 network, because it will always use the udp4 transport.
Even if we set the transport_id in the account to the udp6 transport it fails.

But in general I don't want to do this, because if later the IP changes to an IPv4 network, I think this account will fail
cause of the fixed transport.

How can this be handled?
Why pjsua don't try all transports until it find a working one?

### Steps to reproduce

Build, for example, an iOS app with IPv6 enabled and choose a pure IPv6 WLAN and disable mobile data.
Set the sip uri to a name and not an ip address. Then start the programm.

### PJSIP version

2.13.1

### Context

iPhone XS MAX
iOS 16

### Log, call stack, etc

```shell
Not possible at the moment.
```

**Comment by sauwming** [comment]
In 2.13.1, you have to set a fixed transport in order to use IPv6 (https://docs.pjsip.org/en/latest/specific-guides/network_nat/ipv6.html#enabling-ipv6-support-in-application-using-pjsua-lib) .

Only recently, in #3590, we add a dual stack feature, so I'd recommend you try it out and let us know if it works per your expectation.

**Comment by sauwming** [comment]
Closing this due to lack of update. The implementation of #3590 should also help with this issue. Please feel free to reopen if you still have any problem even with #3590.
