### ISSUE TITLE
Endpoint#handleIpChange crash

### ISSUE THREAD

**Issue by JQueue92** [pjsip/pjproject#3696]
### Describe the bug

I call Endpoint#handleIpChange when the network changed of the device,but it crashed (Occasionally appears)

### Steps to reproduce

call Endpoint#handleIpChange

### PJSIP version

2.13

### Context

device:vivo-V2055A 
sdk int :33

### Log, call stack, etc

```shell
java.lang.Exception: Title:       pjsua_handle_ip_change(&ip_change_param)
Code:        171001
Description: Object is busy (PJSIP_EBUSY)
Location:    ../src/pjsua2/endpoint.cpp:2634

	at org.pjsip.pjsua2.pjsua2JNI.Endpoint_handleIpChange(Native Method)
	at org.pjsip.pjsua2.Endpoint.handleIpChange(Endpoint.java:15)
```

**Comment by sauwming** [comment]
It seems to be an exception, not a crash.
