### ISSUE TITLE
DTMF does't detect as PJSIP Ignores telephony event type from remote SDP

### ISSUE THREAD

**Issue by darshan-verkada** [pjsip/pjproject#3700]
### Describe the bug

`PJSIP` unable to detect `DTMF` tone sent from Cisco Phones. As Cisco Phone is sending `DTMF` as RTP EVENT packet with payload type `122`. But `PJSPIP` expect this to be `121` as published in local SDP.

https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia/stream_info.c#L307-L320 lines refer to `local_m` instead of `rem_m` for `si->rx_event_pt`

### Steps to reproduce

not sure how to reproduce this locally without Cisco CUCM setup

### PJSIP version

2.13

### Context

Bug is platform independent

### Log, call stack, etc

```shell
SDP Published from `PJSIP`

`PJSIP` -> Phone


INVITE sip:3254@10.255.160.3 SIP/2.0
a=rtpmap:120 telephone-event/16000
a=fmtp:120 0-16
a=rtpmap:121 telephone-event/8000
a=fmtp:121 0-16
a=rtpmap:122 telephone-event/32000
a=fmtp:122 0-16
```

Phone Replay to `PJSIP`

```
SIP/2.0 200 OK
a=rtpmap:122 telephone-event/8000
a=fmtp:122 0-15
a=content:main
a=inactive
```
```

**Comment by sauwming** [comment]
This seems to be remote bug. As per the SDP, the DTMF should be sent by remote as PT 122.

The patch in #3661 should help though, you can overwrite `rx_event_pt` there.

**Comment by darshan-verkada** [comment]
@sauwming  Remote does send it as Payload Type `122`. 

But https://github.com/pjsip/pjproject/blob/master/pjmedia/src/pjmedia/stream_info.c#L307-L320 lines refer to `local_m` ( Payload type 121 ) instead of `rem_m` for `si->rx_event_pt`

would prefer to avoid overriding from application with https://github.com/pjsip/pjproject/pull/3661 if it can work out of box with payload type mentioned by Remote in `SDP` itself.

**Comment by sauwming** [comment]
The remote has behaved incorrectly by sending PT 122.

https://datatracker.ietf.org/doc/html/rfc3264
`For sendrecv RTP
   streams, the payload type numbers indicate the value of the payload
   type field the offerer expects to receive, and would prefer to send.`

So it should send 121, we are the one that should send 122 to remote as per the remote's answer.

**Comment by darshan-verkada** [comment]
@sauwming late follow up. The fact that `PJSIP` offers multiple types of Payload type ( 120, 121, 122 ) in it's `SDP` . That seems like giving an option to Cisco Phone to choose one of them.  Or is it clock rate dependent ?


I checked the commit you shared, But like to understand more on root cause of this problem. Whether it's the Cisco Phone is a culprit.


Sharing SDP 

Generated by `PJSIP`

```
v=0
o=- 3902474644 3902474644 IN IP4 10.18.30.190
s=pjmedia
b=AS:84
t=0 0
a=X-nat:0
m=audio 4010 RTP/AVP 96 97 98 99 3 0 8 9 120 121 122
c=IN IP4 10.18.30.190
b=TIAS:64000
a=rtcp:4011 IN IP4 10.18.30.190
a=sendrecv
a=rtpmap:96 speex/16000
a=rtpmap:97 speex/8000
a=rtpmap:98 speex/32000
a=rtpmap:99 iLBC/8000
a=fmtp:99 mode=30
a=rtpmap:3 GSM/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:120 telephone-event/16000
a=fmtp:120 0-16
a=rtpmap:121 telephone-event/8000
a=fmtp:121 0-16
a=rtpmap:122 telephone-event/32000
a=fmtp:122 0-16
a=ssrc:743229029 cname:36556d8d4761d07a
```


Reply from Cisco Phone


```
v=0
o=CiscoSystemsCCM-SIP 302729513 1 IN IP4 10.255.160.3
s=SIP Call
c=IN IP4 10.18.30.163
b=AS:64
t=0 0
m=audio 17450 RTP/AVP 9 122
b=TIAS:64000
a=ptime:20
a=rtpmap:9 G722/8000
a=rtpmap:122 telephone-event/8000
a=fmtp:122 0-15

```

**Comment by darshan-verkada** [comment]
```
If multiple formats are listed, it
   means that the offerer is capable of making use of any of those
   formats during the session.  In other words, the answerer MAY change
   formats in the middle of the session, making use of any of the
   formats listed, without sending a new offer.
```


furthermore,

```
   However, for sendonly and sendrecv streams, the answer might indicate
   different payload type numbers for the same codecs, in which case,
   the offerer MUST send with the payload type numbers from the answer.
```

**Comment by sauwming** [comment]
As per the negotiation, we need to send with PT 122, as the remote indicated, and remote has to send with PT 121.
