### ISSUE TITLE
Google still finds and leads to old documentation

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#3712]
### Describe the bug

Googling for PJSIP topics still leads to https://www.pjsip.org/pjsip/docs/html/index.htm

### Steps to reproduce

Googling for PJSIP topics still leads to https://www.pjsip.org/pjsip/docs/html/index.htm

### PJSIP version

2.13

### Context

Documentation

### Log, call stack, etc

```shell
not needed
```

**Comment by sauwming** [comment]
Yes, but the main result correctly points to docs.pjsip.org
<img width="918" alt="Screenshot 2023-09-20 at 6 07 17 PM" src="https://github.com/pjsip/pjproject/assets/17044930/167d7c0e-c0c8-4aea-857f-4446942f2d06">

**Comment by wosrediinanatour** [comment]
If you search for functions etc. more often old documentation pops up.

**Comment by sauwming** [comment]
I have removed the old documentation and the page can no longer be accessed. But I presume it will take a while before the update is reflected in Google.

**Comment by wosrediinanatour** [comment]
I come still to old documentation...

**Comment by sauwming** [comment]
Not sure what you're referring to.
I have removed the entire `docs` folder.
<img width="620" alt="Screenshot 2023-09-21 at 3 50 01 PM" src="https://github.com/pjsip/pjproject/assets/17044930/112741d7-03e2-4975-8e1b-c3f09aa33c22">
