### ISSUE TITLE
Having an Error of Indentation

### ISSUE THREAD

**Issue by mishraranjan** [pjsip/pjproject#3713]
### Describe the bug

After giving all the commands I have mentioned below, the indentation error is coming.

### Steps to reproduce

#install depencies
apt install python-dev gcc make gcc binutils build-essential
#get pjsip
wget -O pjproject.tar.gz https://github.com/pjsip/pjproject/archive/2.13.1.tar.gz
tar -xvzf pjproject.tar.gz && mv pjproject-2.13.1 pjproject
cd pjproject
#configure
export CFLAGS="$CFLAGS -fPIC"

#build pjsip
./configure && make dep && make
#build python modules
cd pjsip-apps/src/python/
sudo python3 setup.py install

### PJSIP version

 2.13.1

### Context

Happen on Ubuntu Linux

### Log, call stack, etc

```shell
File "~/pjproject/pjsip-apps/src/python/setup.py", line 35
    if len(tokens)>1:
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

Note that Github issue is for bug report only.
Future enquiries will be directly closed.
