### ISSUE TITLE
transport_srtp_dtls RTP/RTCP handshaking

### ISSUE THREAD

**Issue by hrc-amilcar** [pjsip/pjproject#3724]
### Describe the bug

Hello, I'm working with PJSIP using SRTP/DTLS.

Commit a0ac247 introduces separate RTP and RTCP channels for DTLS handshaking.

However, I noticed that when the remote address changes during the handshake, the `dtls_on_recv` function reattaches the member transport with potentially incorrect RTCP information (when multiplexing is not enabled).

Since there are now two channels, `dtls_on_recv` gets called separately for RTP and RTCP in no particular order. The logic that handles the transport reattachment only applies to the RTP channel. And when it detects an address change, it attempts to fill in the RTCP address in the attach parameters, but that address is not yet (ever?) valid.

This is the code I'm referring to inside `dtls_on_recv`:
```
if (idx == RTP_CHANNEL && !ds->use_ice && !ds->nego_completed[idx]) {
    pjmedia_transport_info info;
    pjmedia_transport_get_info(ds->srtp->member_tp, &info);
    if (pj_sockaddr_cmp(&ds->rem_addr, &info.src_rtp_name)) {
        pjmedia_transport_attach_param ap;
        pj_status_t status;

        pj_bzero(&ap, sizeof(ap));
        ap.user_data = ds->srtp;
        pj_sockaddr_cp(&ds->rem_addr, &info.src_rtp_name);
        pj_sockaddr_cp(&ap.rem_addr, &ds->rem_addr);
        ap.addr_len = pj_sockaddr_get_len(&ap.rem_addr);
        if (pj_sockaddr_cmp(&info.sock_info.rtp_addr_name,
                            &info.sock_info.rtcp_addr_name) == 0)
        {
            /* Using RTP & RTCP multiplexing */
            pj_sockaddr_cp(&ds->rem_rtcp, &ds->rem_addr);
            pj_sockaddr_cp(&ap.rem_rtcp, &ds->rem_rtcp);
        } else if (pj_sockaddr_has_addr(&ds->rem_rtcp)) {
            pj_sockaddr_cp(&ap.rem_rtcp, &ds->rem_rtcp);
        } else {
            pj_sockaddr_cp(&ap.rem_rtcp, &ds->rem_addr);
            pj_sockaddr_set_port(&ap.rem_rtcp,
                                    pj_sockaddr_get_port(&ds->rem_addr)+1);
        }

        status = pjmedia_transport_attach2(&ds->srtp->base, &ap);
```

From the caller's point of view, the `else if (pj_sockaddr_has_addr(&ds->rem_rtcp))` line is never true, and falls through to adding +1 to the port, which may not be the actual originating RTCP port coming from the callee.

This seems to cause a lot of a delay in the handshake as both sides attempt to renegotiate.

Perhaps `ds->rem_rtcp` needs to be set when `idx == RTCP_CHANNEL` and only when `rem_rtcp` is fully valid, should the main `RTP_CHANNEL` reattach the member transport. Again, only when multiplexing is disabled.

Maybe I'm misinterpreting this mechanism, but in attempt to fix it, I modified this function to set `rem_rtcp` during RTCP recv and for the RTP channel to reattach the transport only when both remote addresses are valid. The handshke now completes a lot more quickly.

Perhaps this is not a critical bug, but more so a discussion on this negotiation mechanism. Please let me know if there is a better place to discuss this.

### Steps to reproduce

1. Connect two endpoints using SRTP/DTLS.
2. Notice a longer delay in SSL handshaking after a0ac247.

### PJSIP version

a0ac247

### Context

- Custom embedded device.

### Log, call stack, etc

```shell
N/A
```

**Comment by silentindark** [comment]
@hrc-amilcar Would you be able to create a pull request for this, then pjproject team can review it.

**Comment by hrc-amilcar** [comment]
Ok. I'll try to put one together.

**Comment by sauwming** [comment]
I have created a patch in #3732. From my local testing, it seems to work.

Please let us know if it works with your setup as well.
