### ISSUE TITLE
pjsua2 folder does not exist in SimplePjsua2CS

### ISSUE THREAD

**Issue by aparsaeeyan** [pjsip/pjproject#3728]
### Describe the bug

at the address
pjsip-apps/src/swig/csharp/sample/
And in the SimplePjsua2CS project, the pjsua2 folder and the files inside it do not exist, such as Account.cs, AccountCallConfig.cs and...
And when I try to build the solution, it gives an error that the mentioned files do not exist.

### Steps to reproduce

1. open pjproject-vs14.sln solution file in visual studio 2022
2. Set pjsua as Active or Startup Project
3. Set Win32 as the platform
4. build the solution
5. give following errors: 
Error reading content of source file 'D:\Projects\pjproject-master\pjproject-master\pjsip-apps\src\swig\csharp\sample\SimplePjsua2CS\pjsua2\Account.cs' -- 'Could not find file 'D:\Projects\pjproject-master\pjproject-master\pjsip-apps\src\swig\csharp\sample\SimplePjsua2CS\pjsua2\Account.cs'.'.	SimplePjsua2CS	D:\Projects\pjproject-master\pjproject-master\pjsip-apps\src\swig\csharp\sample\SimplePjsua2CS\pjsua2\Account.cs	1	Active

And it gives another 296 error like the above error for other files in the same address.

### PJSIP version

2.13

### Context

- Windows 11

### Log, call stack, etc

```shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	IDE1100	Error reading content of source file 'D:\Projects\pjproject-master\pjproject-master\pjsip-apps\src\swig\csharp\sample\SimplePjsua2CS\pjsua2\Account.cs' -- 'Could not find file 'D:\Projects\pjproject-master\pjproject-master\pjsip-apps\src\swig\csharp\sample\SimplePjsua2CS\pjsua2\Account.cs'.'.	SimplePjsua2CS	D:\Projects\pjproject-master\pjproject-master\pjsip-apps\src\swig\csharp\sample\SimplePjsua2CS\pjsua2\Account.cs	1	Active
```

**Comment by sauwming** [comment]
#3217
