### ISSUE TITLE
pygui sample project error when attempting to add buddy

### ISSUE THREAD

**Issue by mufucaw** [pjsip/pjproject#3737]
### Describe the bug

Using the out-of-the-box sample pygui application, everything appears to work as expected until I try to add a buddy.

### Steps to reproduce

1. Create an account. I used my SIP user/pass and registrar URI. I left the "Register on add" box checked, which is the default. This appears to work fine, I don't see any errors in the console log.
2. Right-click on the account you just created and select "Add Buddy". This shows the "Buddy settings" window.
3. Enter the URI of the buddy. In my case, it was sip:1-my_area_code-my_phone_number@seattle1.voip.ms. I left the "Subscribe presence" box unchecked, but checking it doesn't make a difference either.
4. Click the "Ok" button.

### PJSIP version

2.13.1

### Context

Firing up the application after it is freshly built and walking through the steps to reproduce will result in the error described.

### Log, call stack, etc

```shell
Exception in Tkinter callback
22:10:36.415            pjsua_acc.c  Deleting account 0..

22:10:36.415            pjsua_acc.c  .Account id 0 deleted

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/opt/btm/pygui/buddy.py", line 141, in onOk
    self.cfg.subscribe = self.cfgSubscribe.get()
    ^^^^^^^^^^^^^^^^^^
TypeError: in method 'BuddyConfig_subscribe_set', argument 2 of type 'bool'
```

**Comment by sauwming** [comment]
https://github.com/pjsip/pjproject/pull/3371
