### ISSUE TITLE
Electric noise in iPhone14 and higher devices

### ISSUE THREAD

**Issue by rjvishnu87** [pjsip/pjproject#3740]
### Describe the bug

We are using the PJSIP 2.10 version in our iOS application. 
We have integrated PJSIP library(static library .a) for VoIP audio calls and messages. 
We have observed the electric noise during ringback tone and after answering the audio calls. This issue is happening only on iPhone 14, iPhone 14pro and iPhone 15 and not happening on iPhone 13, iPhone 12 etc. 

Note: We have recorded the audio using     **int status = pjsua_recorder_create(&wav_file, 0, NULL, 0, 0, &RecordID);**.\
We are not able to observe the electric sound, if we use pjsua_recorder_create. But the issue is happening only while playing from iPhone device. 

I have attached audio file which is recorded in the iPhone (with electric noise) for the reference. 
Please advise us on the next steps. 

### Steps to reproduce

1. Make a audio call. 
2. Listen the ring back tone , observe the electric sound. 
3. Answer the call from other party, observe the electric sound after every word. 

### PJSIP version

2.10

### Context

iOS, iPhone14, iPhone15.

### Log, call stack, etc

```shell
no logs collected since this is related to audio issue.
```
[noise-file.zip](https://github.com/pjsip/pjproject/files/12917158/noise-file.zip)

**Comment by guru2010j** [comment]
I am also the same part of the team.
Electric noise is nothing but, it’s kind of crunching a plastic paper over the call.  Any quick suggestion will help us.

**Comment by trengginas** [comment]
Here are some suggestions:
1. Use different sound device clockrate : [ref](https://docs.pjsip.org/en/latest/api/generated/pjsip/group/group__PJSUA__LIB__MEDIA.html#_CPPv4N18pjsua_media_config14snd_clock_rateE)
2. Disable ec : [ref](https://docs.pjsip.org/en/latest/specific-guides/perf_footprint/performance.html#echo-canceller)
