### ISSUE TITLE
Require SIPS on TLS calls is mandatory?

### ISSUE THREAD

**Issue by vsedyshev-intermedia** [pjsip/pjproject#3746]
### Describe the bug

We set up the next settings:

- `secure_signaling=1` (TLS required, SIPS not),
- `rtp_secure_audio=2` (SRTP mandatory).

When we receive incoming INVITE on PJSIP which uses SIP+TLS, we get an error "SIPS required".
If we set `secure_signaling=0`, then there is no error. 

as per description: "1 - SRTP requires secure transport such as TLS", so in our opinion secure_signaling=1 should not require "SIPS".

Can you look into this?

### PJSIP version

2.13

**Comment by nanangizz** [comment]
Tried to reproduce using pjsua param `--use-srtp 2 --srtp-secure 1 --use-tls` and register to a SIP server via TLS so incoming call will arrive via TLS. A call with SRTP mandatory (e.g: using SDP media transport `RTP/SAVP`) can be accepted just fine.

Can you provide log file and/or reproducing steps using pjsua app?

**Comment by sauwming** [comment]
Unable to reproduce. Reopen if you have any update.

**Comment by vsedyshev-intermedia** [comment]
Excuse, I unable permission to re-open issue. But my contractor 
provide `pjsua.log`
[pjsua_log.log](https://github.com/pjsip/pjproject/files/13205443/pjsua_log.log)
 with debug message. Could you please see an
hronology and make expert decisions about root cause of their
errors?

**Comment by nanangizz** [comment]
Looks like call target was not using TLS transport (no `transport=tls` param in the URI target), in such case UDP transport will be used, so this should be the cause. An alternative solution is to configure a SIP proxy with TLS transport.

Btw, the log is an outgoing call scenario instead of incoming call as in description.

**Comment by vsedyshev-intermedia** [comment]
The contractor reported the success of the call. Thank you for your cooperation. I think the issue can be closed.
