### ISSUE TITLE
pjsip2.14 invoke System.loadLibrary("openh264")？？

### ISSUE THREAD

**Issue by LoyaiHai** [pjsip/pjproject#3761]
### Describe the bug

pjsip2.14 said in the introduction that you can directly use native codec, why in the swig of the source code, in pjsua2JNI.java, will also call: System.loadLibrary("openh264")?

### Steps to reproduce

jniLibs path: pjproject-2.14/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a/libpjsua2.so
source code:  pjproject-2.14/pjsip-apps/src/swig/java/android/pjsua2/src/main/java/.....

build step:  1、export ANDROID_NDK_ROOT=/home/lhs/pjsip/pjsip-install/android-ndk-r22b
                   2、TARGET_ABI=arm64-v8a APP_PLATFORM=android-21 ./configure-android
                   3、make dep && make clean && make
                   4、cd pjsip dir/pjsip-apps/src/swig
                   5、sudo make

### PJSIP version

2.14

### Context

jniLibs path: pjproject-2.14/pjsip-apps/src/swig/java/android/pjsua2/src/main/jniLibs/arm64-v8a/libpjsua2.so
source code:  pjproject-2.14/pjsip-apps/src/swig/java/android/pjsua2/src/main/java/.....

build step:  1、export ANDROID_NDK_ROOT=/home/lhs/pjsip/pjsip-install/android-ndk-r22b
                   2、TARGET_ABI=arm64-v8a APP_PLATFORM=android-21 ./configure-android
                   3、make dep && make clean && make
                   4、cd pjsip dir/pjsip-apps/src/swig
                   5、sudo make

### Log, call stack, etc

```shell
package org.pjsip.pjsua2;
public class pjsua2JNI {
  static {
    try {
	System.loadLibrary("openh264");
    } catch (UnsatisfiedLinkError e) {
	System.err.println("Failed to load native library openh264\n" + e);
	System.out.println("This could be safely ignored if you " +
			   "don't use OpenH264 video codec.");
    }
    try {
	System.loadLibrary("pjsua2");
    } catch (UnsatisfiedLinkError e) {
	System.err.println("Failed to load native library pjsua2\n" + e);
    }
  }
}
```

**Comment by sauwming** [comment]
```
	System.out.println("This could be safely ignored if you " +
			   "don't use OpenH264 video codec.");
```
