### ISSUE TITLE
pjsip2.14 preVideo displays a screen with a green filter recover

### ISSUE THREAD

**Issue by LoyaiHai** [pjsip/pjproject#3764]
### Describe the bug

When I use a customized Android device, by loading the compiled openh264, Openh264/97 is no problem, but in the use of the latest pjsip2.14, no openh264 can be overcompiled. Instead of using native openh264 codec, the obtained device is OpENH264/99, and this problem occurs，pjsip2.14 preVideo displays a screen with a green filter

If you suspect that there is a problem with my custom Android device, then why is pjsip2.10 displayed normally on my device? Is it possible to suspect that pjsip2.14 has compatibility issues when using native codec?

### Steps to reproduce

run pjsip2.10
MyApp {
        ......
         CodecInfoVector2 codecs = ep.videoCodecEnum2();
        String codecId = codecs.get(index).getCodecId();
        VidCodecParam vidCodecParam = ep.getVideoCodecParam(codecId);// "H264/97"
	MediaFormatVideo codecFmtpVector = vidCodecParam.getDecFmt();
	MediaFormatVideo mediaFormatVideo = vidCodecParam.getEncFmt();
        ......
        ep.setVideoCodecParam(codecId, vidCodecParam);// "H264/97"
        ......
}

run pjsip2.14
MyApp {
        ......
        CodecInfoVector2 codecs = ep.videoCodecEnum2();
        String codecId = codecs.get(index).getCodecId();
        VidCodecParam vidCodecParam = ep.getVideoCodecParam(codecId );// "H264/99"
	MediaFormatVideo codecFmtpVector = vidCodecParam.getDecFmt();
	MediaFormatVideo mediaFormatVideo = vidCodecParam.getEncFmt();
        ......
        ep.setVideoCodecParam(codecId, vidCodecParam);// "H264/99"
        ......
}

### PJSIP version

2.10 VS 2.14

### Context

pjsip2.10:
openh264-2.1.0

AndroidStudio:
Android Studio Dolphin | 2021.3.1 Patch 1
Windows:
windows11

### Log, call stack, etc

```shell
pjsip2.10:
try {

			CodecInfoVector2 codecInfoVector2 = ep.videoCodecEnum2();
			if (codecInfoVector2 != null) {
				Log.e("023===>", "codecInfoVector2 != null");
			} else {
				Log.e("023===>", "codecInfoVector2 == null");
			}
			Log.e("023===>", "这里的: " + codecInfoVector2.size());
			for (int i = 0; i < codecInfoVector2.size(); i++) {
				Log.e("203===>", "这里的集合里面为===>getDesc：" + codecInfoVector2.get(i).getDesc());
				Log.e("203===>", "这里的集合里面为===>getCodecId：" + codecInfoVector2.get(i).getCodecId());
				Log.e("203===>", "这里的集合里面为===>getPriority：" + codecInfoVector2.get(i).getPriority());
			}

			VidCodecParam vidCodecParam = ep.getVideoCodecParam("H264/97");

			MediaFormatVideo codecFmtpVector = vidCodecParam.getDecFmt();
			MediaFormatVideo mediaFormatVideo = vidCodecParam.getEncFmt();

			/**
			 * 视频分辨率
			 */
//			public static class VideoResolution {
//				public static final int RESOLUTION_320X240 = 0;
//				public static final int RESOLUTION_640X480 = 1;
//				public static final int RESOLUTION_1280X720 = 2;
//				public static final int RESOLUTION_1920X1080 = 3;
//				public static final int RESOLUTION_DEFAULT = RESOLUTION_640X480;
//			}
			codecFmtpVector.setWidth(240);// 视频宽度
			codecFmtpVector.setHeight(320);// 视频高度
			codecFmtpVector.setFpsNum(15);// 每秒帧数

			codecFmtpVector.setFpsDenum(1);// 每秒帧数
			codecFmtpVector.setAvgBps(512000);// 平均比特率
			codecFmtpVector.setMaxBps(512000);// 最大比特率
			vidCodecParam.setDecFmt(codecFmtpVector);

			mediaFormatVideo.setWidth(240);// 视频宽度
			mediaFormatVideo.setHeight(320);// 视频高度
			mediaFormatVideo.setFpsNum(15);// 每秒帧数
			mediaFormatVideo.setFpsDenum(1);// 每秒帧数
			mediaFormatVideo.setAvgBps(256000);// 平均比特率
			mediaFormatVideo.setMaxBps(256000);// 最大比特率
			vidCodecParam.setEncFmt(mediaFormatVideo);

			CodecFmtpVector decFmtp = vidCodecParam.getDecFmtp();

			for (int i = 0; i < decFmtp.size(); i++) {
				if ("profile-level-id".equals(decFmtp.get(i).getName())) {
					decFmtp.get(i).setVal("42e00B");
					break;
				}
			}
			vidCodecParam.setDecFmtp(decFmtp);

			ep.setVideoCodecParam("H264/97", vidCodecParam);

		} catch (Exception e) {
			e.printStackTrace();
		}

pjsip2.14:
 /* Also adjust encoding size in H264 to portrait 240x320 */
        try {
            CodecInfoVector2 codecs = ep.videoCodecEnum2();
            String codecId = "H264/";
            for (CodecInfo c : codecs) {
                if (c.getCodecId().startsWith(codecId)) {
                    codecId = c.getCodecId();
                    break;
                }
            }
            VidCodecParam vcp = ep.getVideoCodecParam(codecId);// openh264/99
            vcp.getEncFmt().setWidth(240);
            vcp.getEncFmt().setHeight(320);
            ep.setVideoCodecParam(codecId, vcp);// openh264/99
        } catch (Exception e) {
            System.out.println(e);
        }
```

**Comment by trengginas** [comment]
Please check the codec you are using (e.g: "H264/99"). Since 2.11 (#2552), android support H264 codec from Mediacodec (native video android). Probably you are using "H264" from mediacodec. You can disable mediacodec by using `--disable-android-mediacodec` when executing `configure-android`. Or prioritize OpenH264 by increasing the codec priority using `Endpoint::codecSetPriority`.
