### ISSUE TITLE
Android recording file quality is poor

### ISSUE THREAD

**Issue by ChenGuoqing1001** [pjsip/pjproject#3765]
### Describe the bug

The client uses Android pjsip pjsua2, and the back-end service uses freeswitch. The call process is very clear, but the recording file saved on freeswitch is not clear. There is no problem with ios pjsip. When using other client libraries, linphone and portsip recording files are very clear. This problem occurs only in the android pjsip library. What's going on?

### Steps to reproduce

APP calls real mobile phone number

### PJSIP version

2.13

### Context

Android all devices

### Log, call stack, etc

```shell
null
```

**Comment by trengginas** [comment]
What did you use to record the audio?
