### ISSUE TITLE
pjmedia_wav_player_port_create() does not close the file when successfull.

### ISSUE THREAD

**Issue by ednt** [pjsip/pjproject#3775]
### Describe the bug

pjmedia_wav_player_port_create() does not close the file when successfull.

I try to delete the directory where also the wav files are stored in Windows 10 after pjsua_destroy() before I leave the program.
(Needed when I want to reset the program configuration)

I was not able to delete the wav files which I used via pjmedia_wav_player_port_create()
After a look in the source code I found that in 

pjproject/pjmedia/src/pjmedia/wav_player.c

the function

pjmedia_wav_player_port_create()

is left without

pj_file_close(fport->fd)

in the case it has read in the file successfully.
In my opinion this is a bug, since the file is read into a memory buffer and the file itself is not needed anymore.

At least after pjsua_destroy() it should be closed.

### Steps to reproduce

At the end of a running pjsua program and use of a wav file, try to delete the wav file after pjsua_destroy().

### PJSIP version

2.13.1

### Context

Windows 10

### Log, call stack, etc

```shell
08 12:47:22 PJSUA Level: 4 Data: 12:47:22.582 sip_endpoint.c  .Endpoint 048C00AC destroyed
08 12:47:22 PJSUA Level: 4 Data: 12:47:22.582            wav  .Pool is not released by application, releasing now
08 12:47:22 PJSUA Level: 4 Data: 12:47:22.582            wav  .Pool is not released by application, releasing now
08 12:47:22 PJSUA Level: 4 Data: 12:47:22.582   pjsua_core.c  .PJSUA state changed: CLOSING --> NULL
08 12:47:22 PJSUA Level: 4 Data: 12:47:22.582   pjsua_core.c  .PJSUA destroyed...
```

**Comment by trengginas** [comment]
You need to destroy the port (using `pjmedia_port_destroy()`) if you create the wav player using `pjmedia_wav_player_port_create()`. Alternatively you can use `pjsua_player_create()` to create the player and destroy it using `pjsua_player_destroy()` when it is no longer used. The file closing is done when the the port is destroyed. 
https://github.com/pjsip/pjproject/blob/ca5255795a330f88d72a0504d902de8bbddcdfeb/pjmedia/src/pjmedia/wav_player.c#L853

**Comment by nanangizz** [comment]
Actually `pjsua_destroy()` should automatically destroy player & recorder ports created using `pjsua_player_create()/pjsua_playlist_create()/pjsua_recorder_create()`, but not ports created using the lower level API PJMEDIA such as `pjmedia_wav_player_port_create()`. For ref, the relevant lib code (for version 2.13.1) should be [here](https://github.com/pjsip/pjproject/blob/bb2287b3a85b17cd60bada94bb91319fb2926e8e/pjsip/src/pjsua-lib/pjsua_aud.c#L512-L528).
