### ISSUE TITLE
Problem for compiling a Example

### ISSUE THREAD

**Issue by eliakimfelmorais** [pjsip/pjproject#3779]
### Describe the bug

I'm trying to compile the example in a Macbook pro M2 machine:

The file is inside of the repository is pjsua2_demo.cpp

When I compile I get this error

/usr/local/include/pj/config.h:265:9: error: Endianness must be declared for this processor
#       error Endianness must be declared for this processor

I tried to compile the lib using this flags:

CFLAGS="-arch arm64" LDFLAGS="-arch arm64"

### Steps to reproduce

The build that I tried were with this command:

usr/bin/g++ -fdiagnostics-color=always -g /Users/eliakim/Documents/PjSip/pjproject/pjsip-apps/src/samples/pjsua2_demo.cpp -o /Users/eliakim/Documents/PjSip/pjproject/pjsip-apps/src/samples/pjsua2_demo

### PJSIP version

2.14

### Context

The issue happen in a Mac Book Pro 2023 M2 

My config_site.h is this one:

#define PJ_IS_LITTLE_ENDIAN 1
#define PJ_IS_BIG_ENDIAN    0

### Log, call stack, etc

```shell
.
```

**Comment by jimying** [comment]
please go to [Build Instructions with GNU Build Systems](https://docs.pjsip.org/en/latest/get-started/posix/build_instructions.html#id2)
```
$ cd pjproject
$ ./configure
$ make -j 8
```
when build complete,   the binary is in the path:  pjproject/pjsip-apps/bin/samples/aarch64-xxx/pjsua2_demo
