### ISSUE TITLE
We know that the client registration session also will keep the TCP connection active throughout the registration session. Now we create a non-actually registered account and call it directly. How can we keep the TCP connection active like the real registration mode?

### ISSUE THREAD

**Issue by yudongdong12306** [pjsip/pjproject#3780]
### Describe the bug

We know that the client registration session also will keep the TCP connection active throughout the registration session.
Now we create a non-actually registered account and call it directly. How can we keep the TCP connection active like the real registration mode?

### Steps to reproduce

1. Create an account through accountConfig.getRegConfig().setRegistrarUri("")
2. Use tcp transmission method to call mobile phone number A
3. Hang up phone A after 100 seconds, and the client did not hang up.

### PJSIP version

2.13.1

### Context

android and ios:
We know that the client registration session also will keep the TCP connection active throughout the registration session.
Now we create a non-actually registered account and call it directly. How can we keep the TCP connection active like the real registration mode?
We try to modify this value PJSIP_TCP_KEEP_ALIVE_INTERVAL, but it does not work.

### Log, call stack, etc

```shell
We try to modify this value PJSIP_TCP_KEEP_ALIVE_INTERVAL, but it does not work.
```

**Comment by andreas-wehrmann** [comment]
If I understand you correctly, you want to keep the TCP connection open and are not registering.
It shouldn't matter actually, but you can force reuse of an existing connection by sending something to the target regularly;
an OPTIONS request comes to mind; that way you'd also know whether the other endpoint is available.

**Comment by yudongdong12306** [comment]
I finally solved this problem by modifying PJSIP_TRANSPORT_IDLE_TIME to a relatively large value, that is, setting the tcp idle timeout to a very long time.

**Comment by andreas-wehrmann** [comment]
Be aware that the remote endpoint might choose to close the connection as well.

**Comment by yudongdong12306** [comment]
thanks

> Be aware that the remote endpoint might choose to close the connection as well.

Thank you so much

**Comment by yudongdong12306** [comment]
> Be aware that the remote endpoint might choose to close the connection as well.

Thank you so much!
