### ISSUE TITLE
Worker threads and ioqueue_select timeouts

### ISSUE THREAD

**Issue by amubiera** [pjsip/pjproject#3786]
### Describe the bug

Hello,

I'm working with pjsip running on an embedded device backed by FreeRTOS. I wrote an os_core layer that provides the required sync primitives. I have a couple of issues when using pjsip in this environment.

### Issue 1: Non-idle threads
I noticed a couple of subsystems create worker threads that have quick timeouts. The `pjmedia/endpoint.c - worker_proc` wakes up every 10ms when nothing is going on (rfdset/wfdset/xfdset are empty). The `pjsua_core.c - worker_thread` also wakes up every 10ms. It gets a further with one entry in the fdsets, but there are no fd events to handle most of the time.

For example, setting breakpoints in ioqueue_select.c:
* Line 988: Hits every 10ms during idle for pjmedia/endpoint.c
* Line 1026: Hits every 10ms during idle for pjsua_core.
* Line 1034: Hits only when SIP call activity begins for both endpoint and pjsua_core.

Is there a particular reason that these threads must wake up so often to check for IO events? I would think select/poll would be set to block infinitely while waiting for IO or socket shutdown. This would minimize CPU usage while idle.

It’s working ok as it is, but this embedded device is unable to sleep. On this device, sleep mode handling works when threads block on a sync primitive or an IO operation. Would it be safe to set those timeouts to infinite or something very long? Would it handle shutdown properly? I will do some testing but I wonder about the ramifications of a change or the rationale for using 10ms.

This is further exacerbated by continuous mutex lock/unlocks happening every 10ms. (see level 6 logs below)

### Issue 2: Lockup due to cooperative threading
In one case during a DTLS call, the pjmedia ioqueue had a pending socket read event, but some other thread had ownership of the key lock. So the `pj_ioqueue_trylock_key` attempted by `ioqueue_dispatch_read_event` returns failure. Since FreeRTOS is typically configured as cooperative task system, the worker thread spins forever without letting other threads execute, so pjsip practically hogs the CPU. I added a sleep when a try-lock fails to allow the locked condition to release. Perhaps this is due to the way `transport_srtp_dtls` handles locking or some priority inversion phenomenon, but would there be a better way to handle this symptom without sleep/yielding when a trylock fails?

I'm still investigating these two issues. I would greatly appreciate any insight.

Thanks.

### Steps to reproduce

1. Bring up a pjsua application.
2. Register an endpoint to a SIP server.
3. Set breakpoints in ioqueue_select for various conditions (no FD, no event, events received).
4. Notice that threads are waking up when the system is idle.

### PJSIP version

2.14

### Context

All systems (MacOS, Linux, Windows), but most notable on embedded devices using FreeRTOS.

### Log, call stack, etc

```shell
12:18:47.506         ioq0x15a8875c0 !Mutex: thread media is waiting (mutex owner=)
12:18:47.506         ioq0x15a8875c0 !Mutex acquired by thread media (level=1)
12:18:47.506         ioq0x15a8875c0  Mutex released by thread media (level=0)
12:18:47.518         sip_endpoint.c !pjsip_endpt_handle_events()
12:18:47.518        edpt0x15917a680 !Mutex: thread pjsua_0 is waiting (mutex owner=)
12:18:47.518        edpt0x15917a680  Mutex acquired by thread pjsua_0 (level=1)
12:18:47.518        edpt0x15917a680  Mutex released by thread pjsua_0 (level=0)
12:18:47.518         ioq0x15916d128  Mutex: thread pjsua_0 is waiting (mutex owner=)
12:18:47.518         ioq0x15916d128  Mutex acquired by thread pjsua_0 (level=1)
12:18:47.518         ioq0x15916d128  Mutex released by thread pjsua_0 (level=0)
12:18:47.518         ioq0x15a8875c0 !Mutex: thread media is waiting (mutex owner=)
12:18:47.518         ioq0x15a8875c0 !Mutex acquired by thread media (level=1)
12:18:47.518         ioq0x15a8875c0  Mutex released by thread media (level=0)
...
<repeats forever>
```

**Comment by sauwming** [comment]
Issue 1:
The short timeout is not ideal indeed, but it's there to minimize latency/processing time for newly added sockets. Check #3086.
Feel free to experiment with a value that you think more suitable for your app, but I won't suggest setting it too large.

Issue 2:
The proper way is of course to find out why DTLS takes some time to release the lock.
But I believe adding sleep may also be needed to avoid the busy loop. We already employ something like this in epoll:
https://github.com/pjsip/pjproject/blob/master/pjlib/src/pj/ioqueue_epoll.c#L1057
but there's no such mechanism in ioq select (perhaps because it was never needed before).

**Comment by amubiera** [comment]
### Issue 1:
Ah, yes. Adding sockets would be affected by this delay. I followed the #3086 conversation.

I've implemented an IO socket pool for a different project using pipe2 in Linux, where select/poll wait on all FDs plus an extra socket pair that can be signaled to wakeup the infinite poll and add a new socket. It's nice that epoll has that feature built in, so we ended up switching to infinite epoll. But alas, I don't have pipe2, socketpair, or epoll available on this embedded device.

I suppose socketpair could be implemented by hand as jimying attempted, but it seems like that code was not adopted. Sounds like it was a complicated enough feature to add for not much real benefit on platforms that don't need to block all threads.

For now, maybe I can set it back to 500ms to see how it behaves. Perhaps a configurable #define for that timeout would be good? Thanks for the pointers.

### Issue 2:
The fix in `ioqueue_epoll.c` seems like a slightly different situation. In my case, there was one pending read event. The worker thread would make it all the way down to handle the readable event `ioqueue_dispatch_read_event` then `pj_ioqueue_trylock_key` would fail inside `ioqueue_dispatch_read_event`. And repeat forever without giving the DTLS thread a chance to unlock it.

I added the sleep to my own version of `pj_mutex_trylock` for this device which seemed least invasive. But maybe it would be beneficial to add some sleep logic to the three dispatch functions when trylock fails in `ioqueue_common_abs.c` and not have the os_core layer assume that a sleep is needed. Though, I think it's a non-issue for platforms that use true preemptive multitasking.

I'll keep looking into why DTLS transport was holding the lock and the system decided to context switch to the endpoint worker thread.

Thanks for the reply sauwming. I think this can be closed.
