### ISSUE TITLE
pjsua2: player cannot be destroyed when Normal call clearing

### ISSUE THREAD

**Issue by xhit** [pjsip/pjproject#3787]
### Describe the bug

When user closes the call while wav is playing, I received the `PJSIP_INV_STATE_DISCONNECTED` event with reason `Normal call clearing`, but when I need to make another call I can't because I received `PJ_ETOOMANY`

When I receive the event, when I tried to stop the transmission an error invalid sink happens in pjsua_conf_disconnect.

Debugging I found that player is not destroyed in this case in function `processStateChange` https://github.com/pjsip/pjproject/blob/9287ac21e6dda91f68a0e30dea88e846c960a549/pjsip/src/pjsua2/call.cpp#L983 when call is disconnected.

Adding this code at the end of the if condition helps because I'm using only one max call and one player in config_site:

```c
/* Destroy file players */
        for (i=0; i<PJ_ARRAY_SIZE(pjsua_var.player); ++i) {
            if (pjsua_var.player[i].port) {
                PJ_LOG(6,(THIS_FILE, "!!!!!!!!!!!!!! Destroying player id %d", i));
                pjsua_player_destroy(i);
            }
        }
```

But not safe with multiple calls.

### Steps to reproduce

1. Compile pj with config_site.h with:
```
#define PJSUA_MAX_CALLS 1
#define PJSUA_MAX_ACC 1
#define PJSUA_MAX_PLAYERS 1
#define PJSUA_MAX_RECORDERS 1
```
2. make call with pjsua2
3. Close the call when audio is playing
4. Try to stop transmission, destroy player and AudioMedia (this it's not possible)
5. Try to make another call

In 5 I have the problem: PJ_ETOOMANY is received because previous player was not destroyed, also I can't destroy it when Normal call clearing happens.

### PJSIP version

2.14 commit 6157218806094deeab818cee721484906b3219fe

### Context

Using Ubuntu 22.04

I compile pjsua2 wrapper for c#

config_site.h as above, to allow one call and one player.

### Log, call stack, etc

```shell
Pending...
```

**Comment by sauwming** [comment]
A couple of notes:
- Destroying player is not Call's responsibility.
- Call disconnection event doesn't mean that the call slot will be immediately available. It may take some time for the call resources to be cleaned up. I suggest to increase the configured library's max number of calls, but to still limit it to one active call within your own app.

**Comment by xhit** [comment]
I know destroying player is not Call's responsibility, the code was a simple and fast workaround for my case.

I fixed completely this issue, leaving to the developer the option to close a specific player from AudioMediaPlayer instead leave this responsibility to Call. With this fix the player will be available immediately when developer needs.
