### ISSUE TITLE
[PJSUA][ACC] Service-Route header not cleared

### ISSUE THREAD

**Issue by andreas-wehrmann** [pjsip/pjproject#3790]
### Describe the bug

I recently encountered a call routing problem, which prevented outgoing calls to be made.
The scenario is this:

- UA registers to registrar via SIP proxy (actually a bunch of proxies (A, B, C), one of which is selected via DNS SRV lookup).
For this, there is an outbound proxy configured for the account.
Please note, the proxies have different priorities: A (high), B (middle), C (low).

- UA is registered to Proxy A, no Service-Route headers received in the response
- Everything working fine
- For some reason, registration fails and UA registers via Proxy B
- Registration is ok, but this time the response contains a "Service-Route" header which contains the IP address of proxy B
- The Service-Route header is then added to the "Route" header list of the account
The account now has two route header: The preconfigured outbound proxy and the Route learned with Service-Route.

All outgoing calls via this account will carry these two Route headers.

**The problem I encountered:**

- After a while the DNS-SRV lookup returns a new set of proxies in which A is different (A-new, B, C) (though it doesn't matter that A is different now, I think)
- PJSUA send register to A-new
- Registration is ok, but this time the registrar does NOT send any Service-Route headers

- Outgoing call attempts fail from this point on because the account still injects the Route header learned from the other proxy

**The general problem seems to be:**

The route learned via Service-Route in REGISTER is NOT updated \
in subsequent REGISTER responses/results (be they success or failure).

A failure or UNREGISTER should clear the learned Route headers and a successful response should ALWAYS update the header list,
this includes the case above, where a route has been learned through Service-Route but subsequent responses didn't contain any Service-Route headers.

I'm sorry I don't have a PR handy; I've just analyzed this issue and it's not so easy for me to reproduce this at the moment;
I'm putting this here so this issue gets documented.

### Steps to reproduce

1. Register to a registrar where the DNS SRV lookup returns two entries (registrar A (high prio), registrar B (low prio))
2. Let UA register to A (A must not send Service-Route headers in its response)
3. Kill Registrar A and wait for UA to refresh the registration
4. UA should register to B now; B sends Service-Route header in its response
5. Resurrect A and wait for UA to refresh its registration
6. UA should register to A now (A must not send Service-Route headers in its response)
7. Outgoing calls still carry the Route header entry learned via Service-Route in 4

### PJSIP version

2.14

### Context

Any platform

### Log, call stack, etc

```shell
Sorry, I cannot share the log I've got at hand because it contains private data.
```

**Comment by sauwming** [comment]
According to the RFC (https://datatracker.ietf.org/doc/html/rfc3608.html#section-6.1), you are correct:
```
If
   the UA refreshes the registration, the stored value of the Service-
   Route is updated according to the Service-Route header field of the
   latest 200 class response.  If there is no Service-Route header field
   in the response, the UA clears any service route for that address-
   of-record previously stored by the UA.  If the re-registration
   request is refused or if an existing registration expires and the UA
   chooses not to re-register, the UA SHOULD discard any stored service
   route for that address-of-record.
```

And we already did more or less the above, with the exception that we don't clear the outbound proxies:
https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua-lib/pjsua_acc.c#L1993
- /* Find and parse Service-Route headers */
- /* Update account's route set
- /* First remove all routes which are not the outbound proxies */
- /* Then append the Service-Route URIs */

Not sure if we should remove the outbound proxies here.

**Comment by TheQue42** [comment]
IMHO, since the Service-Route and outbound proxy config are two separate functions, I don't see why you would want to clear the outbound routes. At least since the original purpose of the service-route was to find the S-CSCF in an IMS network, and that shouldn't mean that you should all-of-sudden disregard the configuration on how to get "out of the local network".  
In my mind, if a "roaming" client received a "SIP default route" from a local/roaming network via DHCP, then that is the local network saying "you have to use this to get out of this network", and then having the home network override this with a service-route, seems counter-intuitive.

**Comment by sauwming** [comment]
@TheQue42 , your explanation makes sense.

Based on the above description, I have tried to create a PR to fix the issue in #3823.

**Comment by andreas-wehrmann** [comment]
So I've been running some more tests; the issues are:

- Service-Route headers previously added are not removed if a subsequent response doesn't contain Service-Route headers. That is because of the check here: https://github.com/pjsip/pjproject/blob/ca0c4403ec1bcf655ee21278a7b7453a33a24dd8/pjsip/src/pjsua-lib/pjsua_acc.c#L2057
I believe this check can be removed altogether?

- The other issue is: update_service_route() is only called if the request returns with a 2XX code, which means the Service-Route headers aren't cleared in this case either; see:
https://github.com/pjsip/pjproject/blob/ca0c4403ec1bcf655ee21278a7b7453a33a24dd8/pjsip/src/pjsua-lib/pjsua_acc.c#L2421

Also, thanks for your explanation @TheQue42

**Comment by sauwming** [comment]
Thank you @andreas-wehrmann . I have updated the PR based on your findings.
