### ISSUE TITLE
build.mak file missing when building PJSUA2 SWIG Python module

### ISSUE THREAD

**Issue by TheoCap** [pjsip/pjproject#3798]
### Describe the bug

I compiled and built the pjsua project from pjproject-vs14.sln with VS 2022.
When I then try to build the SWIG Python module pjsua2 the makefile does not find the file _build.mak_.
I have a _build.mak.in_ file in the folder pointed to by the makefile but no _build.mak_.
I assume that the following python error in the logs is caused by the missing file.

### Steps to reproduce

I followed the instructions in your documentation:
1. https://docs.pjsip.org/en/latest/get-started/windows/build_instructions.html
2. https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module

The error appears at this stage:
```
cd pjsip-apps/src/swig/java
make
```

### PJSIP version

2.14

### Context

I use :
- Windows 11
- Python 3.12.0
- PJSIP version 2.14 (latest release)
- Microsoft Visual Studio Community 2022 - Version 17.8.2

### Log, call stack, etc

```shell
C:\Users\a914487\Documents\pjproject-2.14\pjsip-apps\src\swig\python>make
swig -I../../../../pjlib/include -I../../../../pjlib-util/include -I../../../../pjmedia/include -I../../../../pjsip/include -I../../../../pjnath/include -c++  -w312 -threads -DSWIG_NO_EXPORT_ITERATOR_METHODS -python -o pjsua2_wrap.cpp ../pjsua2.i
gcc -o gcc.exe cc_mingw.c
cp gcc.exe g++.exe
python setup.py build --compiler=mingw32
helper.mak:1: ../../../../build.mak: No such file or directory
make[1]: *** No rule to make target '../../../../build.mak'.  Stop.
helper.mak:1: ../../../../build.mak: No such file or directory
make[1]: *** No rule to make target '../../../../build.mak'.  Stop.
helper.mak:1: ../../../../build.mak: No such file or directory
make[1]: *** No rule to make target '../../../../build.mak'.  Stop.
helper.mak:1: ../../../../build.mak: No such file or directory
make[1]: *** No rule to make target '../../../../build.mak'.  Stop.
Traceback (most recent call last):
  File "C:\Users\a914487\Documents\pjproject-2.14\pjsip-apps\src\swig\python\setup.py", line 101, in <module>
    if platform.system()=='Windows' and os.environ["MSYSTEM"].find('MINGW')!=-1:
                                        ~~~~~~~~~~^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'MSYSTEM'
make: *** [Makefile:40: _pjsua2.so] Error 1
```

**Comment by sauwming** [comment]
`build.mak` is created by `configure`.
