### ISSUE TITLE
while changing the network video call are stuck

### ISSUE THREAD

**Issue by shubhamparekh2000** [pjsip/pjproject#3808]
### Describe the bug

while changing the network video call are stuck

### Steps to reproduce

while changing the network video call are stuck

### PJSIP version

latest version 2.13

### Context

the app is built into ios
test device: iPhone XR
language: swift
use PJsua 2 In C++
macOS

### Log, call stack, etc

```shell
14:33:49.973        strm0x10b048c28 !Error sending RTP: Network is unreachable
14:33:50.038       vstrm0x10c033028 !Error sending RTCP: Network is unreachable
nw_proto_tcp_route_init [C19.1.1:3] no mtu received
Connection 19: encountered error(1:53
```

**Comment by sauwming** [comment]
It's to be expected. Invoke the network change procedure to reinit the media.
