### ISSUE TITLE
I have a new discovery for #3803;

### ISSUE THREAD

**Issue by xuan6zm** [pjsip/pjproject#3810]
### Describe the bug

I have done several tests and found that in each failed call, the ip address of via in the signaling is the original address when the invite is sent over the switch network, but does not point to the IP address after network cutting.

In addition, I was surprised to find that when you establish a call for about 35 seconds, and then do the network cutting operation, initiate the invite at this time, the via ip address in the signaling is the new ip, then the two sides will be normal

Guess the unregistered tcp outbound call switching network should have something to do with this ip address change and 35 seconds or so

### Steps to reproduce

n non-registered mode, set reg_uri to empty 】

1, non-registered mode TCP G711 call; Call less than 35 seconds; Switch from wifi to 4G, after successfully connecting to the network; When the pjsua_handle_ip_change method is triggered by the client, the invite message is correctly sent after the local log is checked. The via ip address in the invite indicates the old IP address.
Result: Both sides lost contact, neither can hear

2, non-registered mode TCP G711 call; The call is longer than 35 seconds; Switch from wifi to 4G, after successfully connecting to the network; When the pjsua_handle_ip_change method is triggered by the client, the invite message is correctly sent and the IP address is correctly changed.
Result: The call between the two parties is normal

### PJSIP version

2.14

### Context

This problem occurs in pjsip2.14
The application is built using xcode14.3

The configuration parameters in config_site are
 #define PJ_CONFIG_IPHONE 1
#include <pj/config_site_sample.h>

### Log, call stack, etc

```shell
。。。
```

**Comment by sauwming** [comment]
You need to stop opening a new Github issue for the same issue.
The reason you received no response so far is due to Github issue being currently for bug report only, and based on your description, there is no *strong* indication that this is a PJSIP issue.

if `pjsua_ip_change_acc_cfg.reinvite_flags` contains `PJSUA_CALL_UPDATE_VIA`, it should be updated accordingly. If not, you can debug into the function and find out why it's not the case.
The duration of the call (shorter or longer than 35 seconds) should be irrelevant to this case.

**Comment by xuan6zm** [comment]
> You need to stop opening a new Github issue for the same issue. The reason you received no response so far is due to Github issue being currently for bug report only, and based on your description, there is no _strong_ indication that this is a PJSIP issue.
> 
> if `pjsua_ip_change_acc_cfg.reinvite_flags` contains `PJSUA_CALL_UPDATE_VIA`, it should be updated accordingly. If not, you can debug into the function and find out why it's not the case. The duration of the call (shorter or longer than 35 seconds) should be irrelevant to this case.

I just modified this value in the project, and its function is only to modify the printed information in the log, but it still can not solve the problem that the call is less than 35 seconds and the two parties lose contact;

Example: 
1. Do not contain this value ->> The IP address will not change in the via of the invite sent by network switching.

2. Contain this value >> Switch network when the call is less than 35 seconds; The address remains unchanged; The two sides are still out of contact
                             >> Switch network when the call is longer than 35 seconds; The address has changed; Normal communication between two parties

3. I tried to modify other values; The problem of double disconnection exists

Conclusion: The modification of this value can not correct the above problems;
Would this 35-second period affect the user re-invite request? There is currently no way to fix this problem

**Comment by xuan6zm** [comment]
> You need to stop opening a new Github issue for the same issue. The reason you received no response so far is due to Github issue being currently for bug report only, and based on your description, there is no _strong_ indication that this is a PJSIP issue.
> 
> if `pjsua_ip_change_acc_cfg.reinvite_flags` contains `PJSUA_CALL_UPDATE_VIA`, it should be updated accordingly. If not, you can debug into the function and find out why it's not the case. The duration of the call (shorter or longer than 35 seconds) should be irrelevant to this case.

Hello, I now find that the 35-second problem is caused by one of the values

I set PJSIP_TRANSPORT_IDLE_TIMETCP to 2. In this case, I only need to hold the call for more than 2 seconds to set up a connection

Ask if there are any problems with changing this value to less than 33

**Comment by xuan6zm** [comment]
PJSIP_TRANSPORT_IDLE_TIME
