### ISSUE TITLE
SIP acc not registering (VOIP)

### ISSUE THREAD

**Issue by addyuchiha** [pjsip/pjproject#3812]
### Describe the bug

previously when I was running the code below it was working well and was showing registration successful, but idk now I am running it its showing registratio unsuccessful.

`import pjsua2 as pj
import time

# Subclass to extend the Account and get notifications etc.
class Account(pj.Account):
  def onRegState(self, prm):
      print("***OnRegState: " + prm.reason)

# pjsua2 test function
def pjsua2_test():
  # Create and initialize the library
  ep_cfg = pj.EpConfig()
  ep = pj.Endpoint()
  ep.libCreate()
  ep.libInit(ep_cfg)

  # Create SIP transport. Error handling sample is shown
  sipTpConfig = pj.TransportConfig();
  sipTpConfig.port = 5060;
  ep.transportCreate(pj.PJSIP_TRANSPORT_UDP, sipTpConfig);
  # Start the library
  ep.libStart();

  acfg = pj.AccountConfig();
  acfg.idUri = "sip:xxxxx@sip.plusnet.de";
  acfg.regConfig.registrarUri = "sip:sip.xxxx.de";
  cred = pj.AuthCredInfo("digest", "*", "xxxx", 0, "xxxxxx");
  acfg.sipConfig.authCreds.append( cred );
  # Create the account
  acc = Account();
  acc.create(acfg);
  # Here we don't have anything else to do..
  while True:
    time.sleep(0.001);
  

  # Destroy the library
  ep.libDestroy()

#
# main()
#
if __name__ == "__main__":
  pjsua2_test()`

### Steps to reproduce

issue happened on Ubuntu 22.04.3 LTS, it was working previously

### PJSIP version

4.0.2

### Context

issue happened on Ubuntu 22.04.3 LTS, it was working previously

### Log, call stack, etc

```shell
cant provide full logs but this much,

09:33:07.533           pjsua_core.c  .TX 549 bytes Request msg REGISTER/cseq=27831 (tdta0x7fec3800b958) to UDP 92.xxx.xxx.17:5060:
REGISTER sip:sip.xxxxxxx.de SIP/2.0
Via: SIP/2.0/UDP 192.xxx.xx.120:5060;rport;branch=z9hG4bKPj50c9c192-bddf-42c3-8453-9c9cf9845f0f
Max-Forwards: 70
From: <sip:xxxxxx@sip.plusnet.de>;tag=49bdbd5c-f0ca-41c0-95c5-1e5eb55bdb38
To: <sip:xxxxxxx@sip.plusnet.de>
Call-ID: 5e559a28-f1d6-4375-875d-7544dd4fae63
CSeq: 27831 REGISTER
Contact: <sip:xxxxxxx@192.xxxxx.xxxx:5060;ob>
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0


--end msg--
09:33:11.533           pjsua_core.c  .TX 549 bytes Request msg REGISTER/cseq=27831 (tdta0x7fec3800b958) to UDP 92.197.182.17:5060:
REGISTER sip:sip.plusnet.de SIP/2.0
Via: SIP/2.0/UDP 192.xxx.xx.120:5060;rport;branch=z9hG4bKPj50c9c192-bddf-42c3-8453-9c9cf9845f0f
Max-Forwards: 70
From: <sip:xxx@sip.xxx.de>;tag=49bdbd5c-f0ca-41c0-95c5-1e5eb55bdb38
To: <sip:xxx@sip.xx.de>
Call-ID: 5e559a28-f1d6-4375-875d-7544dd4fae63
CSeq: 27831 REGISTER
Contact: <sip:xxxx@192.xx.xx:5060;ob>
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0


--end msg--
09:33:12.033            pjsua_acc.c  ...SIP registration failed, status=408 (Request Timeout)
09:33:12.033            pjsua_acc.c  ...Scheduling re-registration retry for acc 0 in 298 seconds..
***OnRegState: Request Timeout
```

**Comment by sauwming** [comment]
The registration timed out. Check if the registration is: - sent correctly, - received by the server, - and properly responded by the server.

**Comment by addyuchiha** [comment]
tell me more specifically how can I do these steps, I mean I have a voip provider, so what to do?


> The registration timed out. Check if the registration is: - sent correctly, - received by the server, - and properly responded by the server.
