### ISSUE TITLE
Android sample app crashes: Cannot locate symbol "__sendto_chk" referenced by "libpjsua2.so"

### ISSUE THREAD

**Issue by je3f0o** [pjsip/pjproject#3816]
### Describe the bug

I'm trying to run sample app for Android and it crashes. I don't think this is a bug, but I'm very sorry. I cannot find any useful information about this a whole day and night. In my research it seems like related with `bionic libc` for android. Because I find only reference `__sendto_chk` is Google android `bionic fortify libc`. Also I'm in MacOS and cannot use `lld`, `nm` etc for arm64 binary file... please help

### Steps to reproduce

1. `$ ./configure-android --use-ndk-cflags`
2. `$ make dep && make clean && make`
3. `$ cd pjsip-apps/src/swig`
4. `$ make`
5. Open Android studio with sample app.
6. Build succeeded.
7. Run it and it crashes...

### PJSIP version

i tried versions `2.12.1`, `2.13.1`, `2.14`

### Context

I'm in MacOS and tried with NDK version 21, 23, 25, 26.
TARGET_ABI: arm64-v8a

### Log, call stack, etc

```shell
W  Failed to load native library pjsua2
W  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__sendto_chk" referenced by "/data/app/org.pjsip.pjsua2.app_kotlin-1/base.apk!/lib/arm64-v8a/libpjsua2.so"...
E  No implementation found for void org.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_org_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__)
```

**Comment by je3f0o** [comment]
I opened `Android/sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/socket.h` file and saw:

<img width="1207" alt="Screenshot 2023-12-30 at 13 09 53" src="https://github.com/pjsip/pjproject/assets/1854769/31dd7808-f360-4d97-9cb8-fa1bf8faef1c">

So I recompiled with `APP_PLATFORM=23 ./configure-android --use-ndk-cflags` and it works. Please update documentation. Because some older android phones cannot run Android API 26 or higher...

**Comment by xreleven** [comment]
Hi,je3f0o,Have you addressed this problem? I also came across the same error, and now still have no clue yet.
![Uploading 1712108931172.jpg…]()
