### ISSUE TITLE
Is there any way to connect to websocket kotlin/java ?

### ISSUE THREAD

**Issue by datpt11** [pjsip/pjproject#3820]
### Describe the bug

crash app when i register with server 

### Steps to reproduce

1. Register with registrar Url contains "wss://"

### PJSIP version

2.14

### Context

MacOS - android

### Log, call stack, etc

```shell
pjsua_acc.c  ..Unable to generate suitable Contact header for registration: Unsupported transport (PJSIP_EUNSUPTRANSPORT) [status=171060]            
pjsua_acc.c  ..Unable to create registration: Unsupported transport (PJSIP_EUNSUPTRANSPORT) [status=171060]
```

**Comment by sauwming** [comment]
You need to implement your own Web Socket transport first.
