### ISSUE TITLE
c# wrapper issue

### ISSUE THREAD

**Issue by akshitagupta2** [pjsip/pjproject#3824]
### Describe the bug

when I build c# wrapper of pjproject with blank config_site.h file, sample project of c# works fine but when I add video configurations in config_site.h and add all the paths of x86 architecture for win32 application in sample project if shows one exception pjsua2.dll not found

### Steps to reproduce

1. added this code to config_site.h file
#define PJMEDIA_HAS_VIDEO             1
#define PJMEDIA_HAS_OPENH264_CODEC    1
#define PJMEDIA_HAS_LIBYUV            1
#define PJMEDIA_VIDEO_DEV_HAS_SDL     1
#define PJMEDIA_VIDEO_DEV_HAS_DSHOW   1
2. added all the paths of x86 architecture of all the packages from vcpkg.
3. set pjsua as startup project and build using debug-dynamic and win32 .
4. build swig_csharp_pjsua2 using debug-dynamic and win32.
5. when pjsua2.dll file and all the cs classes that are generated in output folder use it in simpjua2cs project 
6. then this exception come pjsua2.dll not found.
7. please tell how to resolve this?

### PJSIP version

2.14

### Context

windows

### Log, call stack, etc

```shell
DllNotFoundException: Unable to load DLL 'pjsua2': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Exception thrown: 'System.DllNotFoundException' in SimplePjsua2CS.exe
Exception thrown: 'System.TypeInitializationException' in SimplePjsua2CS.exe
Exception thrown: 'System.TypeInitializationException' in SimplePjsua2CS.exe
Exception thrown: 'System.TypeInitializationException' in SimplePjsua2CS.exe
```

**Comment by sauwming** [comment]
Test with the C/C++ sample app first to make sure the config works before trying with C#.

**Comment by akshitagupta2** [comment]
how to register two accounts simultaneously in pjsua client
