### ISSUE TITLE
speex  warning: Had to discard a playback frame (your application is buggy and/or got xruns)

### ISSUE THREAD

**Issue by TheoCap** [pjsip/pjproject#3826]
### Describe the bug

I use the pjsua library and when a media is played during a call (to a vxml application) it is of very bad quality with a lot of logs:
```
alsa_dev.c  pb_thread_func: underrun!
Master/sound  Underflow, buf_cnt=0, will generate 1 frame
speex  warning: Had to discard a playback frame (your application is buggy and/or got xruns)
```

I'm pasting the logs here as they are very long:
[issue.log](https://github.com/pjsip/pjproject/files/13886043/issue.log)

### Steps to reproduce

I built the librairy with config_site_sample.h following your documentation: https://docs.pjsip.org/en/latest/
I used your simple_pjsua code to call the vxml application: https://github.com/pjsip/pjproject/blob/master/pjsip-apps/src/samples/simple_pjsua.c

### PJSIP version

2.14

### Context

The call is initiated from a linux VM (ubuntu 22.04.3) to the vxml application that receives the call (and play the audio) on the Windows 11 host machine.

### Log, call stack, etc

```shell
Logs are in "Describe the bug" section
```

**Comment by sauwming** [comment]
Refer to the doc for audio troubleshooting.

**Comment by TheoCap** [comment]
For those who might experience the same problem with audio drop-outs on VMs, consider increasing the resources allocated to the VM, especially the CPU. 
See: https://docs.pjsip.org/en/latest/specific-guides/audio-troubleshooting/problems/audio_dropouts.html
Btw, thanks to the maintainers of this project
