### ISSUE TITLE
PJSUA2 SWIG JAVA on MacOS - error when opening sound device

### ISSUE THREAD

**Issue by dni1337** [pjsip/pjproject#3829]
### Describe the bug

I have an Java application which is using PJSUA SWIG JAVA wrapper.
All is working perfectly on Windows and Linux!
But on MacOs it is not possible to open any sound device.
Error:
`pjsua_aud.c !.Error opening sound device: Unknown error -1969730734 [status=-1969730734]
media.cpp   pjsua_conf_connect(id, sink.id) error: Unknown error -1969730734 (status=-1969730734) [../src/pjsua2/media.cpp:218]`

If i compile with Portaudio and disable Coreaudio, then it is working, but the Sound quality is not good.

The Pjsua executable is working with coreaudio on MacOS, but the SWIG JAVA Module not!

### Steps to reproduce

1. compile pjproject and the java swig module on macos with standard settings
2. use a simple java app to open the pjsua swig library and try to play a wav file or connect a sip phone call.
3. opening the audio device fails with the following error:
`pjsua_aud.c !.Error opening sound device: Unknown error -1969730734 [status=-1969730734]
media.cpp   pjsua_conf_connect(id, sink.id) error: Unknown error -1969730734 (status=-1969730734) [../src/pjsua2/media.cpp:218]`

### PJSIP version

2.14

### Context

Only happens on macos
On windows and linux it is working like a chram.

### Log, call stack, etc

```shell
`pjsua_aud.c !.Error opening sound device: Unknown error -1969730734 [status=-1969730734]
media.cpp   pjsua_conf_connect(id, sink.id) error: Unknown error -1969730734 (status=-1969730734) [../src/pjsua2/media.cpp:218]`
```

**Comment by sauwming** [comment]
Check the complete log:
- during init, check if audio devices were correctly listed
- during opening, check which device it tried to open.
