### ISSUE TITLE
iOS sample apps building error

### ISSUE THREAD

**Issue by muhammadjon-swift** [pjsip/pjproject#3834]
### Describe the bug

After building PJSIP itself for iOS tried to work with iOS sample apps none of them builds successfully.
The problem is "Undefined symbols: Linker command failed with exit code 1"

### Steps to reproduce

Just build pjsip for iOS using Xcode 15.1  
Also I found a tip to add "-ld64" on Other Linking Flags but then I get like 36 more errors:
<img width="1274" alt="Screenshot 2024-01-18 at 16 59 18" src="https://github.com/pjsip/pjproject/assets/22303129/6f8e679a-e62f-48f5-ae3d-218de65478b3">

### PJSIP version

2.14

### Context

Xcode 15.1
iOS 17.2
pjsip 2.14
MackBook Pro Apple M2 

min_ios_version = 12.0
architecture = arm64

config_site.h configs
    #define PJ_CONFIG_IPHONE 1
    #define PJMEDIA_HAS_VIDEO 1
    #define PJMEDIA_HAS_VID_TOOLBOX_CODEC 1

    #define PJ_HAS_SSL_SOCK 1
    #define PJ_SSL_SOCK_IMP PJ_SSL_SOCK_IMP_APPLE

    #include <pj/config_site_sample.h>

### Log, call stack, etc

```shell
----
```

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/get-started/ios/build_instructions.html#tls-openssl-support
