### ISSUE TITLE
Problem with incoming calls with italian provider "Tiscali"

### ISSUE THREAD

**Issue by gabrieleturchi** [pjsip/pjproject#3836]
### Describe the bug

The incoming calls are using a full (international) phone number with prefix "00" (italian international prefix) and not the standard "+". At least in the past these calls where of course rejected. I was able to patch the sip channel handler in asterisk to solve this problem (a single line patch), but I was never able to find the right place in pjsip to make a similar patch. Now I wish to move to a more recent asterisk version, but the sip channel is no more available.

### Steps to reproduce

Receive a call in Italy form "Tiscali" provider, or any provider who use a prefix different from "+".

### PJSIP version

asterisk 18

### Context

Asterisk

### Log, call stack, etc

```shell
...
```

**Comment by sauwming** [comment]
I don't think there's anything needs fixing within PJSIP itself. I may be mistaken though, so if there is an issue, please test it with our sample app and provide us the PJSIP log, and I'll work on a patch.

**Comment by andreas-wehrmann** [comment]
To me this sounds like a number formatting issue.
If you experience this in Asterisk with a certain provider, you need to deal with this inside of the dialplan, there should be no need for patching anything whatsoever.
