### ISSUE TITLE
Failed to send Request msg INVITE/cseq=20069 (tdta0x55d4d14c80c8)! err=120022 (Invalid argument)

### ISSUE THREAD

**Issue by chenfengfeng123** [pjsip/pjproject#3851]
### Describe the bug
Hello!

I'm running siprtp demo under the "pjproject-2.14/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu" directory in ubuntu 20.04. The cmd is as follows:
./siprtp "sip:peer-to-peer@192.168.0.111"

Howerver I meet the error:   
siprtp.c  Making 1 calls to sip:peer-to-peer@192.168.0.111.. tsx0x55d4d14d91a8  ...Failed to send Request msg INVITE/cseq=20069 (tdta0x55d4d14c80c8)! err=120022 (Invalid argument)
![image](https://github.com/pjsip/pjproject/assets/103178236/38dbaaf6-3a75-4b2e-bd3e-443f74f0fc39)

siprtp demo is normal in windows by Microsoft Visual Studio, see the following picture:
![image](https://github.com/pjsip/pjproject/assets/103178236/b781aa21-a3be-4b7c-97e2-ce3f8688ec3d)

Do you have any clues on how to slove this errror?

### Steps to reproduce

1. cd pjproject-2.14/pjsip-apps/bin/samples/x86_64-unknown-linux-gnu
2. ./siprtp "sip:peer-to-peer@192.168.0.111"

### PJSIP version

2.14

### Context

Ubuntu 20.04

### Log, call stack, etc

```shell
./pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/siprtp "sip:peer-to-peer@192.168.0.111"
00:45:55.355         os_core_unix.c !pjlib 2.14-dev for POSIX initialized
00:45:55.357               siprtp.c  SIP UDP listening on 127.0.1.1:5060
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
00:45:55.867               siprtp.c  Making 1 calls to sip:peer-to-peer@192.168.0.111..
00:45:55.867      tsx0x558d6019a1a8  ...Failed to send Request msg INVITE/cseq=13285 (tdta0x558d601890c8)! err=120022 (Invalid argument)
00:45:55.868               siprtp.c  .....Call #0 disconnected. Reason=503 (Invalid argument)
siprtp: ../src/samples/siprtp.c:578: make_call: Assertion `status == PJ_SUCCESS' failed.
```

**Comment by nanangizz** [comment]
Looking at this "SIP UDP listening on 127.0.1.1:5060", the error code may be returned by network/socket, have you checked if the target address is reachable from that machine?

**Comment by chenfengfeng123** [comment]
ping 192.168.0.111 is successful in ubuntu @nanangizz 
![image](https://github.com/pjsip/pjproject/assets/103178236/ed43d256-e7b2-4a1d-9140-822175dd5aac)

**Comment by chenfengfeng123** [comment]
Sure enough, the problem is "127.0.0.1". After specifying the ip of the machine with "--ip-addr" param, the voice communication is successful. Thanks very much.  @nanangizz 
![image](https://github.com/pjsip/pjproject/assets/103178236/5a55a99e-d512-45f1-84fb-2946cd8f26fa)
