### ISSUE TITLE
Is there any way to check the call is active or not in PJMEDIA confrence.c file?

### ISSUE THREAD

**Issue by ckss2k21** [pjsip/pjproject#3855]
### Describe the bug

I want to check call is active or not in conference.c file. How can i check ? I have tried using the  pjsua_call_is_active() but it fails in compilation. Showing undefined reference. Tried multiple thing to solve this out in Makefile but not able to do that. Please suggest a solution. 

This need to be checked becuase we are facing a problem during the confernce join. We have send the JOIN request to and call the function pjsua_add_conf_port() and at the same time (millisecond) user disconnect the call in this case system is crashing. 

Below is the core stack : - 
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-164.el8.x86_64 libgcc-8.5.0-4.el8_5.x86_64 libuuid-2.8.el8.x86_64 openssl-libs-1.1.1k-5.el8_5.x86_64 zlib-1.2.11-17.el8.x86_64
(gdb) bt
#0  0x00000000004fb1fd in pjmedia_codec_encode (codec=0x0, input=0x7f0eb8576af0, out_size=1468, output=0x7f0eb8576b30)
    at ../include/pjmedia/codec.h:1069
#1  0x00000000004fcb6f in put_frame_imp (port=0x7f0e85dead10, frame=0x7f0eb8576bf0) at ../src/pjmedia/stream.c:1291
#2  0x00000000004fd11b in put_frame (port=0x7f0e85dead10, frame=0x7f0eb8576bf0) at ../src/pjmedia/stream.c:1522
#3  0x00000000004f0f6c in pjmedia_port_put_frame (port=0x7f0e85dead10, frame=0x7f0eb8576c90) at ../src/pjmedia/port.c:11
#4  0x00000000004ea9b0 in write_port (conf=0x25d0e48, cport=0xab2dbb8, timestamp=0x7f0eb8576e08, frm_type=0x7f0eb8576d14
    at ../src/pjmedia/conference.c:2123
#5  0x00000000004eb758 in get_frame (this_port=0x25dcc58, frame=0x7f0eb8576df0) at ../src/pjmedia/conference.c:2588
#6  0x00000000004f0ee2 in pjmedia_port_get_frame (port=0x25dcc58, frame=0x7f0eb8576df0) at ../src/pjmedia/port.c:97
#7  0x00000000004f0152 in clock_callback (ts=0x2609e40, user_data=0x2609c08) at ../src/pjmedia/master_port.c:231
#8  0x0000000000510b84 in clock_thread2 (arg=0x2609e20) at ../src/pjmedia/clock_thread.c:634
#9  0x000000000056b684 in thread_main (param=0x260ce68) at ../src/pj/os_core_unix.c:523
#10 0x00007f0ed77f417a in start_thread () from /lib64/libpthread.so.0
#11 0x00007f0ed536fdc3 in clone () from /lib64/libc.so.6

Please suggest.     

### Steps to reproduce

NA

### PJSIP version

2.2.1

### Context

NA

### Log, call stack, etc

```shell
NA
```

**Comment by andreas-wehrmann** [comment]
The confbridge itself doesn't have a concept of "calls", it's merely an audiomatrix.
Are you really using pjproject 2.2.1?
This is quite old, I suggest updating to a newer version and checking again.
