### ISSUE TITLE
Python: garbage collection can prematurely hang up calls 

### ISSUE THREAD

**Issue by dbuschtoens** [pjsip/pjproject#3856]
### Describe the bug

In the pjsua2 python library, the native instances of `pj::Call` are destroyed when the associated python pjsua2.Call object is garbage collected. The destructor calls `pjsua_call_hangup` with the call's id if the call is still active. This can lead to the unexpected termination of active calls if the call id has already been reused for a new call.

### Steps to reproduce

As an example, Consider if `PJSUA_MAX_CALLS` is `4` and 4 callers make a call, hang up and call again.
If all references to the `pjusa2.Call` objects are dropped on hangup, but the 4 new calls are made before the garbage collector runs, there are now
8 `pj::Call` instances, the first 4 with ids `0, 1, 2, 3` that correspond to the calls that are already terminated, and the second 4 with ids `0, 1, 2, 3` for the 4 active calls.
When the garbage collector now runs, the first 4 `pjsua2.Call` objects are destroyed, leading to the destructor `pj::Call::~Call` being called.
Each destructor then determines that the call with their id is still active and must be hung up, leading to the unexpected termination of the active calls.

The attached log shows this happening with 2 calls being dropped. It
contains python garbage collection debug logs generated using 
```python
gc.set_debug(gc.DEBUG_STATS)
```
The garbage collection of the python `Call` objects is logged using
```python
import pjsua2 as pj

class SipCall(pj.Call):
    def __init__(self, acc: pj.Account, call_id: int):
        super().__init__(acc, call_id)
        self.call_id = call_id
        
    def __del__(self):
        logger.warning("Call %s deleted", self.call_id)
```
and the pjsua library was built with a modified `call.cpp` file containing
```cpp

Call::~Call()
{
    PJ_LOG(1, (THIS_FILE, "!!!! destructing Call %d", id));
//...
void Call::hangup(const CallOpParam &prm) PJSUA2_THROW(Error)
{
    PJ_LOG(1, (THIS_FILE, "!!!! Hangup call %d", id));
```

### PJSIP version

2.14

### Context

This happened in a docker container based on the `python:3.11.4-buster` docker image, as well as on MacOS.

### Log, call stack, etc

```shell
2024-02-08T12:29:21.099511756Z gc: collecting generation 1...
2024-02-08T12:29:21.131789756Z gc: objects in each generation: 1017 2146 42775
2024-02-08T12:29:21.131833131Z gc: objects in permanent generation: 0
2024-02-08T12:29:21.134691673Z WARNING - Call 0 deleted
2024-02-08T12:29:21.134923131Z WARNING - Call 1 deleted
2024-02-08T12:29:21.135367048Z WARNING - Call 2 deleted
2024-02-08T12:29:21.137092798Z WARNING - Call 3 deleted
2024-02-08T12:29:21.137109214Z WARNING - Call 0 deleted
2024-02-08T12:29:21.137112506Z WARNING - Call 1 deleted
2024-02-08T12:29:21.137550131Z 12:29:21.135               call.cpp  !!!! destructing Call 0
2024-02-08T12:29:21.137561548Z 12:29:21.136               call.cpp  !!!! destructing Call 1
2024-02-08T12:29:21.139707256Z 12:29:21.139               call.cpp  !!!! destructing Call 2
2024-02-08T12:29:21.139741048Z 12:29:21.139               call.cpp  !!!! Hangup call 2
2024-02-08T12:29:21.152044964Z 12:29:21.151               call.cpp  !!!! destructing Call 3
2024-02-08T12:29:21.152342048Z 12:29:21.151               call.cpp  !!!! Hangup call 3
2024-02-08T12:29:21.153024089Z 12:29:21.152               call.cpp  !!!! destructing Call 0
2024-02-08T12:29:21.155037381Z 12:29:21.154               call.cpp  !!!! destructing Call 1
2024-02-08T12:29:21.159727256Z gc: done, 1012 unreachable, 0 uncollectable, 0.0271s elapsed
```

**Comment by sauwming** [comment]
Refer to the docs.

**Comment by dbuschtoens** [comment]
I assume you are referring to [Problems with garbage collection](https://docs.pjsip.org/en/latest/pjsua2/general_concept.html#problems-with-garbage-collection).

>  - it delays the destruction of objects (including PJSUA2 objects), causing the code in object’s destructor to be executed out of order
> - the GC operation may run on different thread not previously registered to PJLIB, causing assertion
> 
> Due to problems above, application ‘’’MUST immediately destroy PJSUA2 objects using object’s delete() method (in Java)’’’, instead of relying on the GC to clean up the object.

The problem in python however is that there is no built in way to delete an object.
You can do 
```python
del call
```
but that only deletes a reference to the actual call object. The finalizer _should_ be called precisely when the final reference is removed, but it seems to be common wisdom that it should be avoided to rely on that. I also tried calling `call.__del__()` directly, but that didn't cause the destruction of the native call object either.

I wasn't able to exactly replicate the issue that I encounter in my codebase and I can't justify putting any more time in this. Instead, here's a different case where an unexpected delay in object deletion causes the same problem, cyclic references:
 
```python
import gc
import os
import time
import pjsua2 as pj
import logging

SIP_ID_URI = os.environ["SIP_ID_URI"]
SIP_REGISTRAR_URI = os.environ["SIP_REGISTRAR_URI"]
SIP_USERNAME = os.environ["SIP_USERNAME"]
SIP_PASSWORD = os.environ["SIP_PASSWORD"]

MAX_CALLS = 2
MAX_THREADS = 0
CONSOLE_LOG_LEVEL = 1
MAX_CALLS_PER_ENDPOINT = 2
DISABLE_VAD = True
TRANSPORT_PORT = 5060

CALL_DURATION_SECONDS = 5
GC_INTERVAL = 30

gc.set_debug(gc.DEBUG_STATS )

logger = logging.Logger(__name__)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("\033[34m%(asctime)s - %(levelname)s - %(message)s\033[0m"))
handler.setLevel(logging.DEBUG)
logger.setLevel(logging.DEBUG)
logger.addHandler(handler)

call_index = 0
active_calls = {}

def delete_call(call_id):
  del active_calls[call_id]

def get_ok():
  response = pj.CallOpParam()
  response.statusCode = pj.PJSIP_SC_OK
  return response


class CyclicRefNode:
  def __init__(self, ref):
    self.ref = ref

class Call(pj.Call):
  def __init__(self, acc, call_id, index):
    super().__init__(acc, call_id)
    self.id = call_id
    self.index = index
    self.cyclic_ref = CyclicRefNode(self)
    self.start_time = time.time()

  def __del__(self):
    logger.warning("Call %s (%s) __del__ called" % (self.index, self.id))

  def onCallState(self, prm):
    info = self.getInfo()
    logger.debug("Call %s (%s) state: %s" % (self.index, self.id, info.stateText))
    if info.state == pj.PJSIP_INV_STATE_DISCONNECTED:
      age = time.time() - self.start_time
      logger.info("Call %s (%s) disconnected after %s s" % (self.index, self.id, age))
      delete_call(self.index)
      del self

class Account(pj.Account):
  def __init__(self):
    super().__init__()

  def onIncomingCall(self, prm: pj.OnIncomingCallParam):
    global call_index
    index = call_index
    call_index += 1
    call = Call(self, prm.callId, index)
    active_calls[index] = call
    call.answer(get_ok())


def init_pjsua():
  endpoint_config = pj.EpConfig()
  endpoint_config.uaConfig.threadCnt = MAX_THREADS
  endpoint_config.uaConfig.mainThreadOnly = True
  endpoint_config.logConfig.consoleLevel = CONSOLE_LOG_LEVEL
  endpoint_config.medConfig.maxCalls = MAX_CALLS_PER_ENDPOINT
  endpoint_config.medConfig.noVad = DISABLE_VAD

  transport_config = pj.TransportConfig()
  transport_config.port = TRANSPORT_PORT

  endpoint = pj.Endpoint()
  endpoint.libCreate()
  endpoint.libInit(endpoint_config)
  endpoint.libStart()

  endpoint.transportCreate(pj.PJSIP_TRANSPORT_UDP, transport_config)

  account_config = pj.AccountConfig()
  account_config.idUri = SIP_ID_URI
  account_config.regConfig.registrarUri = SIP_REGISTRAR_URI
  cred = pj.AuthCredInfo("digest", "*", SIP_USERNAME, 0, SIP_PASSWORD)
  account_config.sipConfig.authCreds.append(cred)
  account = Account()
  account.create(account_config)

  audio_device_manager: pj.AudDevManager = endpoint.audDevManager()
  audio_device_manager.setNullDev()

  return endpoint, account

if __name__ == "__main__":
  endpoint, account = init_pjsua()
  logger.info("PJSUA started")
  last_gc = time.time()
  while True:
    endpoint.libHandleEvents(10)
    if time.time() - last_gc > GC_INTERVAL:
      last_gc = time.time()
      logger.info("Calling gc.collect()")
      gc.collect()
```

To see the unexpected behavior, call as many times as necessary to loop through all possible call IDs (2 in my example) between two GC invocations and then once more. Now the active call has the same ID as one of the calls that have yet to be garbage collected. You will notice the call being dropped suddenly without any callStateChange callback on the active call object.

Here's the log output I got from this experiment:
```
2024-02-16 11:18:04,209 - INFO - PJSUA started
2024-02-16 11:18:07,224 - DEBUG - Call 0 (0) state: INCOMING
2024-02-16 11:18:07,227 - DEBUG - Call 0 (0) state: CONNECTING
2024-02-16 11:18:07,269 - DEBUG - Call 0 (0) state: CONFIRMED
2024-02-16 11:18:08,543 - DEBUG - Call 0 (0) state: DISCONNECTED
2024-02-16 11:18:08,544 - INFO - Call 0 (0) disconnected after 1.3212065696716309 s
2024-02-16 11:18:10,362 - DEBUG - Call 1 (1) state: INCOMING
2024-02-16 11:18:10,371 - DEBUG - Call 1 (1) state: CONNECTING
2024-02-16 11:18:10,401 - DEBUG - Call 1 (1) state: CONFIRMED
2024-02-16 11:18:11,387 - DEBUG - Call 1 (1) state: DISCONNECTED
2024-02-16 11:18:11,387 - INFO - Call 1 (1) disconnected after 1.02671217918396 s
2024-02-16 11:18:13,021 - DEBUG - Call 2 (0) state: INCOMING
2024-02-16 11:18:13,022 - DEBUG - Call 2 (0) state: CONNECTING
2024-02-16 11:18:13,050 - DEBUG - Call 2 (0) state: CONFIRMED
2024-02-16 11:18:31,212 - INFO - Calling gc.collect()
gc: collecting generation 2...
gc: objects in each generation: 422 1104 17048
gc: objects in permanent generation: 0
2024-02-16 11:18:31,248 - WARNING - Call 0 (0) __del__ called
2024-02-16 11:18:31,249 - WARNING - Call 1 (1) __del__ called
11:18:31.249               call.cpp  !!!! destructing Call 0
11:18:31.249               call.cpp  !!!! Hangup call 0
11:18:31.251               call.cpp  !!!! destructing Call 1
gc: done, 6 unreachable, 0 uncollectable, 0.0193s elapsed
```

Now whether or not this should be considered a bug that needs to be fixed I can't say. From an outside perspective, a relying on object deletion to be executed at an exact time in a language where this can't be precisely controlled seems like something that at the very least bears mention in the documentation. Even calling `gc.collect` manually right after `del call` isn't a surefire way since there might be a surprising reference still active in the current context, in my experimentations I saw this happen because the call was referred to in a local closure.
