### ISSUE TITLE
PJMEDIA_EAUD_NODEFDEV (Unable to find default audio device) on Rasbian 6.1.21 (Raspberry Pi 3A+)

### ISSUE THREAD

**Issue by alxx** [pjsip/pjproject#3858]
### Describe the bug

Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) even though test executable can list the audio devices present.

### Steps to reproduce

$ cd pjproject/pjsip-apps/bin/
$ ./pjsystest-armv7l-unknown-linux-gnueabihf 

Choose menu option 02 (Play Tone)

### PJSIP version

2.14-dev

### Context

Raspberry Pi 3 A+
Raspbian GNU/Linux 11 (bullseye) without GUI
libasound2-dev installed, also portaudio 1.9
PJSip configured using `./aconfigure --disable-video`
`aplay` works fine, other software using the on-board sound card also works fine

Using the system test executable `pjsip-apps/bin/pjsystest-armv7l-unknown-linux-gnueabihf` I can enumerate the audio devices:

$ ./pjsystest-armv7l-unknown-linux-gnueabihf 
10:08:16.045 sip_endpoint.c !.Module "mod-pjsua-log" registered
10:08:16.045 sip_endpoint.c  .Module "mod-tsx-layer" registered
10:08:16.046 sip_endpoint.c  .Module "mod-stateful-util" registered
10:08:16.046 sip_endpoint.c  .Module "mod-ua" registered
10:08:16.046 sip_endpoint.c  .Module "mod-100rel" registered
10:08:16.046 sip_endpoint.c  .Module "mod-pjsua" registered
10:08:16.046 sip_endpoint.c  .Module "mod-invite" registered
10:08:16.138     alsa_dev.c  ..ALSA driver found 11 devices
10:08:16.138     alsa_dev.c  ..ALSA initialized
10:08:16.138          pjlib  ..select() I/O Queue created (0x14cea8c)
10:08:16.151 sip_endpoint.c  .Module "mod-evsub" registered
10:08:16.151 sip_endpoint.c  .Module "mod-presence" registered
10:08:16.151 sip_endpoint.c  .Module "mod-dlg_even" registered
10:08:16.151 sip_endpoint.c  .Module "mod-mwi" registered
10:08:16.152 sip_endpoint.c  .Module "mod-refer" registered
10:08:16.152 sip_endpoint.c  .Module "mod-pjsua-pres" registered
10:08:16.152 sip_endpoint.c  .Module "mod-pjsua-im" registered
10:08:16.152 sip_endpoint.c  .Module "mod-pjsua-options" registered
10:08:16.152   pjsua_core.c  .1 SIP worker threads created
10:08:16.152   pjsua_core.c  .pjsua version 2.14-dev for Linux-6.1.21/armv7l/glibc-2.31 initialized
10:08:16.152   pjsua_core.c  .PJSUA state changed: CREATED --> INIT
10:08:16.152   pjsua_core.c  PJSUA state changed: INIT --> STARTING
10:08:16.152 sip_endpoint.c  .Module "mod-unsolicited-mwi" registered
10:08:16.152   pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
M E N U :
0: Tests
  00: Run test wizard
  01: Device Test
  02: Play Tone
  03: Play WAV File1
  04: Play WAV File2
  05: Record Audio
  06: Latency Test
  07: AEC/AES Test

  09: Exit
1: Options
  10: View Devices
  11: View Settings

Enter the menu number: 10
10:08:18.923      systest.c  Running Audio Device List
Audio Device List
Found 11 devices
  0: ALSA [default] (0/0)
  1: ALSA [output] (0/0)
  2: ALSA [hw:CARD=Headphones,DEV=0] (0/1)
  3: ALSA [plughw:CARD=Headphones,DEV=0] (0/1)
  4: ALSA [sysdefault:CARD=Headphones] (0/1)
  5: ALSA [dmix:CARD=Headphones,DEV=0] (0/1)
  6: ALSA [hw:CARD=vc4hdmi,DEV=0] (0/0)
  7: ALSA [plughw:CARD=vc4hdmi,DEV=0] (0/0)
  8: ALSA [sysdefault:CARD=vc4hdmi] (0/0)
  9: ALSA [hdmi:CARD=vc4hdmi,DEV=0] (0/0)
 10: ALSA [dmix:CARD=vc4hdmi,DEV=0] (0/0)

1:OK  

But trying to generate a sound fails:

Enter the menu number: 02
Audio Tone Playback Test
This test will play simple ringback tone to the speaker. Please listen carefully for audio impairments such as stutter. You may need to let this test running for a while to make sure that everything is okay. Press OK to start, CANCEL to skip
1:OK  9:Cancel  
1
10:09:07.861      systest.c  Running Audio Tone Playback Test
10:09:07.862    pjsua_aud.c  Conf connect: 1 --> 0
10:09:07.862    pjsua_aud.c  .Set sound device: capture=-1, playback=-2, mode=0, use_default_settings=0
10:09:07.862    pjsua_aud.c  ..Error retrieving default audio device parameters: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) [status=420006]
10:09:07.862    pjsua_aud.c  .Error opening sound device: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) [status=420006]
Error
Sorry we encounter error when initializing the tone generator: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV)
1:OK 

This behaviour is reproduced if I try for example to place a SIP call using the other executable samples.

However, using the `playfile` util works fine:

~/pjproject/pjsip-apps/bin/samples/armv7l-unknown-linux-gnueabihf $ ./playfile ~/pjproject/tests/pjsua/wavs/input.11.wav 
10:11:49.259 os_core_unix.c !pjlib 2.14-dev for POSIX initialized
10:11:49.310     alsa_dev.c  Added sound device default
10:11:49.313     alsa_dev.c  Added sound device output
10:11:49.314     alsa_dev.c  Added sound device hw:CARD=Headphones,DEV=0
10:11:49.315     alsa_dev.c  Added sound device plughw:CARD=Headphones,DEV=0
10:11:49.325     alsa_dev.c  Added sound device sysdefault:CARD=Headphones
10:11:49.333     alsa_dev.c  Added sound device dmix:CARD=Headphones,DEV=0
10:11:49.336     alsa_dev.c  Added sound device hw:CARD=vc4hdmi,DEV=0
10:11:49.338     alsa_dev.c  Added sound device plughw:CARD=vc4hdmi,DEV=0
10:11:49.341     alsa_dev.c  Added sound device sysdefault:CARD=vc4hdmi
10:11:49.344     alsa_dev.c  Added sound device hdmi:CARD=vc4hdmi,DEV=0
10:11:49.348     alsa_dev.c  Added sound device dmix:CARD=vc4hdmi,DEV=0
10:11:49.348     alsa_dev.c  ALSA driver found 11 devices
10:11:49.348     alsa_dev.c  ALSA initialized
10:11:49.349          pjlib  select() I/O Queue created (0x1a6b944)
10:11:49.350   wav_player.c  File player '/home/pi/pjproject/tests/pjsua/wavs/input.11.wav' created: samp.rate=11025, ch=1, bufsize=4KB, filesize=92KB
10:11:49.350     alsa_dev.c  open_playback: Open playback device 'hw:CARD=Headphones,DEV=0'
10:11:49.351     alsa_dev.c  Opened device alsa(hw:CARD=Headphones,DEV=0) for playing, sample rate=11025, ch=1, bits=16, period size=219 frames, latency=140 ms
Playing /home/pi/pjproject/tests/pjsua/wavs/input.11.wav..

Press <ENTER> to stop playing and quit
10:11:53.444   wav_player.c !File port /home/pi/pjproject/tests/pjsua/wavs/input.11.wav EOF
10:11:53.444   wav_player.c  File port /home/pi/pjproject/tests/pjsua/wavs/input.11.wav rewinding..
^C

Any help would be highly appreciate, thank you!

### Log, call stack, etc

```shell
Nothing relevant that I can find and isn't already mentioned above.
```

**Comment by sauwming** [comment]
The reason is that no audio input device found

**Comment by alxx** [comment]
What? Wait, why would no audio input device prevent a tone from playing? How do I resolve this? On what grounds did you close this ticket? What's my solution?

**Comment by sauwming** [comment]
`pjsystest` is for testing purpose and requires both capture and playback devices.

If your goal is to play tonegen, then you can simply do so in your own app.
