### ISSUE TITLE
SIP Message

### ISSUE THREAD

**Issue by shubhamparekh2000** [pjsip/pjproject#3859]
### Describe the bug

you are adding a pjsip message in pjsua but you are not adding pjsip message in pjsua 2 

### Steps to reproduce

if you have any knowledge about how to add pjsip message in pjsua 2.0 

### PJSIP version

2.14

### Context

N/A

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
Currently the issue page is not for asking enquiries.
