### ISSUE TITLE
Renegotiating SDP after negotiation in early media affects later reinvite

### ISSUE THREAD

**Issue by ajvignaux** [pjsip/pjproject#3862]
### Describe the bug

We have some code that has been running for quite a while, but recently an external provider started responding to an INVITE in a way that causes outgoing calls to fail.

We have been trying to track down the issue and I think I have distilled the negotiation sequence into a negotiator test program which demonstrates the situation.

We have applied a workaround so this is not affecting calls at the moment.

_(It is certainly possible that we have bugs in our code that is triggering the issue. And we are not really sure what the PJSIP code is intended to do in certain cases.)_

We work with AMR-WB (and AMR) but are operating using the pjmedia `passthrough` codec. One of the aspects of that, is that during initialization the codec_mgr is loaded with the AMR codec strings e.g. `"AMR-WB/16000/1"`, `"AMR/8000/1"`.

We send an INVITE to the remote side with several audio options (BTW: PRACK and 100rel are not mentioned in the headers). In the example, some of the SDP lines are (with other lines omitted for brevity):

```
m=audio 49170 RTP/AVP 116 107 9 118 119 8 0 18 96 110
a=rtpmap:116 AMR-WB/16000/1
a=fmtp:116 mode-set=0,1,2; mode-change-capability=2; max-red=220
a=rtpmap:107 AMR-WB/16000/1
a=fmtp:107 octet-align=1; mode-set=0,1,2; mode-change-capability=2; max-red=200
...
a=rtpmap:118 AMR/8000/1
a=fmtp:118 mode-set=7; mode-change-capability=2; max-red=120
a=rtpmap:119 AMR/8000/1
a=fmtp:119 octet-align=1; mode-set=7; mode-change-capability=2; max-red=100
...
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
a=rtpmap:110 telephone-event/8000
a=fmtp:110 0-15
```

The remote side responds with:

- `100 Trying`
- `183 Session Progress` (with an SDP)
- `180 Ringing`
- `200 OK` (with a copy of the SDP)

In our pjproject library build, we have the (default) value of `PJ_TRUE` for the `accept_multiple_sdp_answers` configuration variable. So, the PJSIP library proceeds to handle the copy of the SDP and emits the log message:

`Received final response after SDP negotiation has been done in early media. Renegotiating SDP..`

On the surface, it appears that everything is still ok - here's an example of what was negotiated:

```
m=audio 49170 RTP/AVP 116 96
a=rtpmap:116 AMR-WB/16000/1
a=fmtp:116 mode-set=0,1,2; mode-change-capability=2; max-red=220
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
```

However, when we decide to send a re-invite to change network addresses, the `pjmedia_sdp_neg_modify_local_offer2()` call in `pjsip_inv_reinvite()` modifies the SDP in the INVITE to:

```
m=audio 49170 RTP/AVP 107 96
a=rtpmap:107 AMR-WB/16000/1
a=fmtp:107 mode-set=0,1,2; mode-change-capability=2; max-red=220
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
```

N.B. The `116` has been re-written as `107`.

### Possible Analysis:

The code chooses `107` because `assign_pt_and_update_map()` uses the `aud_dyn_codecs[]` table and the related `codec_to_pt[]` map indicates that `107` should be used for `"AMR-WB/16000/1"`.

```
aud_dyn_codecs[]
    0: "AMR-WB/16000/1",
    1: "AMR/8000/1",
    2: "telephone-event/16000/1",
    3: "telephone-event/8000/1"

codec_to_pt[0][]
    0: pt=107
    1: pt=119
    2: pt=96
    3: pt=110

pt_to_codec[0][]
    pt= 96: 2
    pt=107: 0
    pt=110: 3
    pt=116: 0
    pt=118: 1
    pt=119: 1
```

_(I am not sure how the data structure is meant to work if the SDP can mention `"AMR-WB/16000/1"` twice.)_

That `codec_to_pt[]` mapping was created because the SDP was in both the 183 and the 200 messages. A necessary condition for the rewrite is that the library performs that SDP renegotiation which loads the codec mapping.

Another necessary condition for the `116`/`107` rewrite is the `"AMR-WB/16000/1"` etc. codec strings are in the codec_mgr table.

### Steps to reproduce

The following source is a standalone version of `sdp_neg_test.c` with the example SDP sequence included:
[neg_test.c](https://github.com/pjsip/pjproject/files/14304849/neg_test.c.txt)

The test program has two #define entries:

  #define USE_CODEC_MGR
  #define MULTIPLE_SDP

If both are defined, then the test will fail. If either one is #undef then the test program will succeed.

### PJSIP version

2.14 and the latest git clone

### Context

Linux (ubuntu) build.

In production, our `config_site.h` includes definitions to enable the PASSTHROUGH codecs and we have applied several additional patches to the library source.

However, for this negotiation test, no site configuration is necessary - `config_site.h` is empty.

### Log, call stack, etc

```shell
02:41:52.104         os_core_unix.c !pjlib 2.14-dev for POSIX initialized
02:41:52.104 enum_codecs
02:41:52.104 CODEC ----
02:41:52.104 CODEC 0 [AMR-WB/16000/1]
02:41:52.104 CODEC 1 [AMR/8000/1]
02:41:52.104 CODEC 2 [telephone-event/16000/1]
02:41:52.104 CODEC 3 [telephone-event/8000/1]
02:41:52.104 CODEC ----
02:41:52.104   test 0: AMR-WB clash
02:41:52.104 ..test 0, stage 0
02:41:52.104 ..test 0, stage 1
02:41:52.104 ..test 0, stage 2
02:41:52.104    error: active local comparison mismatch: Format in SDP media descriptor not equal (PJMEDIA_SDP_EFORMATNOTEQUAL)
02:41:52.104 Logical cmp after negotiation remote answer mismatch: Format in SDP media descriptor not equal (PJMEDIA_SDP_EFORMATNOTEQUAL)
Active local sdp from negotiator:
v=0
o=alice 2890844526 2890844527 IN IP4 host.anywhere.com
s=alice 
c=IN IP4 other.example.com
t=0 0
m=audio 49170 RTP/AVP 107 96
a=rtpmap:107 AMR-WB/16000/1
a=fmtp:107 mode-set=0,1,2; mode-change-capability=2; max-red=220
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
a=sendrecv
a=ptime:20
a=maxptime:40

The correct active local sdp:
v=0
o=alice 2890844526 2890844527 IN IP4 host.anywhere.com
s=alice 
c=IN IP4 other.example.com
t=0 0
m=audio 49170 RTP/AVP 116 96
a=rtpmap:116 AMR-WB/16000/1
a=fmtp:116 mode-set=0,1,2; mode-change-capability=2; max-red=220
a=rtpmap:96 telephone-event/16000
a=fmtp:96 0-15
a=sendrecv
a=ptime:20
a=maxptime:40


02:41:52.104   test 0 offer answer 2 failed with status -110
02:41:52.104 ..ERROR(-110)
02:41:52.104 deinit_codec
```

**Comment by sauwming** [comment]
Thanks for analysing the issue in great details.

Unfortunately, such behavior is to be expected since we only record the codec name and not its properties (such as mode etc). So `AMR-WB/16000/1` can use either 107 and 116.
