### ISSUE TITLE
Can fax function be added based on pjsip？

### ISSUE THREAD

**Issue by arrhel** [pjsip/pjproject#3870]
### Describe the bug

Can fax function be added based on pjsip

### Steps to reproduce

pjlib can be not found reference api

### PJSIP version

2.10

### Context

linux

### Log, call stack, etc

```shell
...
```

**Comment by andreas-wehrmann** [comment]
The short answer is "yes".
The longer answer is: Are you talking about T.38 and/or pure audio fax?
pjsip offers the pieces for enabling the signaling needed for this; but you would have to implement fax specific signaling yourself.
Asterisk uses pjsip and also implements fax functionality; maybe you can get some ideas from there.
