### ISSUE TITLE
Is there any way to calculate MOS and QOS score of the call in the pjproject?

### ISSUE THREAD

**Issue by ckss2k21** [pjsip/pjproject#3874]
### Describe the bug

Hi Team, 

We have a dialer using the pjproject version 2.2.1. I need to develop the getting the mos and qos score of the call and print into my CDR. So is there any way to calculate these parameters?

Please help me into this.

### Steps to reproduce

NA

### PJSIP version

2.2.1

### Context

NA

### Log, call stack, etc

```shell
NA
```

**Comment by sauwming** [comment]
I believe you can get the call stats and use the data to perform the calculation.
For some references, perhaps you can check:
https://sillycodes.com/mean-opinion-score-or-mos-calculation-asterisk-voip-calls/
https://www.pingman.com/kb/article/how-is-mos-calculated-in-pingplotter-pro-50.html
