### ISSUE TITLE
Video quality

### ISSUE THREAD

**Issue by azizconi** [pjsip/pjproject#3879]
### Describe the bug

When I work with video call how to I need adaptive quality video by network quality. How I can adaptive video quality. Which algorithm I need use. 

### Steps to reproduce

I change quality like this: 
``` call.vidStreamModifyCodecParam(call.medIdx, codecParam) ```
But I think this is very bad practice

### PJSIP version

2.13.1

### Context

Android

### Log, call stack, etc

```shell
Android kotlin
```

**Comment by sauwming** [comment]
> I change quality like this: `call.vidStreamModifyCodecParam(call.medIdx, codecParam)` But I think this is very bad practice

Unfortunately this is the only way right now. Any reason why you believe that's bad practice?
If you have other suggestions or ideas, feel free to let us know.

**Comment by azizconi** [comment]
``` call.vidStreamModifyCodecParam(call.medIdx, codecParam) ```

I would like there to be a special method, for example autoAdaptiveVideo(true) so that video adaptation is done by pjsua2 based on network connection based on network connection, hardware and system requirements (OS)

**Comment by sauwming** [comment]
We had this in our wish list a while ago, but there is no straightforward way to do such adjustment (i.e. there's no one size fits all), since user requirements and preferences differ. And that's why we chose the current approach, which is to let the user assess the condition on their own and adjust accordingly.

So currently we don't have any plan to offer just a single boolean setting for adaptive media (audio/video).

**Comment by azizconi** [comment]
```
codecParam.width = widthValue
codecParam.height = heightValue
codecParam.autoAdaptiveVideo(true)
````

What I mean is let's say we have a ```autoAdaptiveVideo(bool)``` method, and if it is set to true than quality of video is managed by pjsip, we're only able to in this case change ```width``` and ```height```. This adjustment is done while setting codecs before calling

And if we assign ```codecParam.autoAdaptiveVideo(false)``` then control over adaptation remains with the developer. 
By default, let it always be ```codecParam.autoAdaptiveVideo(false)``` so that the developer himself can control the adaptation, otherwise if we assign ```codecParam.autoAdaptiveVideo(true)``` then a parameter such as ```call.vidStreamModifyCodecParam(call.medIdx, codecParam)``` will not work

**Comment by sauwming** [comment]
I understand your point, but as mentioned previously, we have no plan to add such feature at the moment.

Feel free to implement it on your own and create a pull request if you wish so.
