### ISSUE TITLE
Support for user parameters

### ISSUE THREAD

**Issue by jay293874** [pjsip/pjproject#3881]
### Describe the bug

It looks like pj do not parse user parameters in URIs (sip_parser.c and int_parse_user_pass) ?
The following URI

<sip:+1234;bla=ble;more@example.com;transport=tcp>

becomes number
+1234;bla=ble;more
when it should be
+1234

### Steps to reproduce

This behaviour is seen in Asterisk 20

### PJSIP version

2.13.1

### Context

Linux x64
Asterisk 20 with pjsip with incoming calls and ${EXTEN} channel variable

### Log, call stack, etc

```shell
An incoming call with Asterisk + chan_pjsip puts caller 
+1234;bla=ble;more
in the ${EXTEN} variable.
It looks like this variable is parsed and set by pjsip.
```

**Comment by andreas-wehrmann** [comment]
This is absolutely according to specification.
See the 'user' production in the [RFC](https://www.rfc-editor.org/rfc/rfc3261.html#page-219).

What exactly do you mean by "user parameters"?
Are you talking about URI parameters or header parameters?
In any case, these parameters probably don't belong in the userpart of the URI.
If you've got a system that transmits parameters in this way and can't change it, then unfortunately you'll need to parse them out of the userpart yourself.
This is not an issue with PJ.

**Comment by jay293874** [comment]
I'm talking about the SIP/SIPS URIs used in To, From and Contact SDP header.

I'm not sure if I understand all of this, but
at page 219 / 25.1 basic rules it mentions parameters and semicolon as separator.
At section 19.1.6 there are listed examples doing exactly this. It is called telephone-subscriber fields as a part of the userinfo part.

I though this was strange when I saw it, but these parameters are used nation wide in my country.

**Comment by jay293874** [comment]
Ah ok. Ill take it up with Asterisk.
Thank you
