### ISSUE TITLE
Is it possible to use pjsip with standalone media server?

### ISSUE THREAD

**Issue by alfedotov** [pjsip/pjproject#3882]
### Describe the bug

I have custom standalone media server that implements RTP and other stuff. Is it possible to disable internal pjsip SDP message generation and ask standalone media server for this functionality via some interface?
Probably there is some how to guide exists...

### Steps to reproduce

none

### PJSIP version

2.14

### Context

none

### Log, call stack, etc

```shell
none
```

**Comment by TheQue42** [comment]
You wont be able to use the PJSUA layers, since they are tightly integrated with the PJMEDIA (SDP, RTP) stuff, but using the lower layers make it possible to let pjsip manage the SIP stuff, while you provide/analyse the SDP in your application.

https://docs.pjsip.org/en/latest/overview/intro.html

**Comment by wosrediinanatour** [comment]
It is possible: https://docs.pjsip.org/en/latest/specific-guides/media/3rd_party_media.html

**Comment by alfedotov** [comment]
> You wont be able to use the PJSUA layers, since they are tightly integrated with the PJMEDIA (SDP, RTP) stuff, but using the lower layers make it possible to let pjsip manage the SIP stuff, while you provide/analyse the SDP in your application.
> 
> https://docs.pjsip.org/en/latest/overview/intro.html

you mean to implement custom SDP parser modules that must process them in order before standard pjsip implementation handles it?

**Comment by TheQue42** [comment]
> > You wont be able to use the PJSUA layers, since they are tightly integrated with the PJMEDIA (SDP, RTP) stuff, but using the lower layers make it possible to let pjsip manage the SIP stuff, while you provide/analyse the SDP in your application.
> > https://docs.pjsip.org/en/latest/overview/intro.html
> 
> you mean to implement custom SDP parser modules that must process them in order before standard pjsip implementation handles it?

The way we use it in our SIP conference server (loosely based on pjsip/pjsip-apps/src/samples/simpleua.c but without the pjmedia stuff), pjsip will _validate_ SDP that is received (on a _very_ basic level), but we generate our own SDP, and there is no RTP logic that PjSIP is used for.
I haven't bothered figuring out whether I could get rid of ALL of the SDP validation as well, since I actually like additional validation.
