### ISSUE TITLE
potential issue in android_jni_dev.c

### ISSUE THREAD

**Issue by videoparkdelta** [pjsip/pjproject#3891]
### Describe the bug

In android_jni_dev.c, 
sampleFormat can be ENCODING_PCM_8BIT or ENCODING_PCM_16BIT. 
[android documentation link](https://developer.android.com/reference/android/media/AudioRecord#read(byte[],%20int,%20int,%20int))
read method has signature "([BII)I", but we probably need to use the read method with short array as param. 
Similar for write method.

### Steps to reproduce

N/A

### PJSIP version

2.13.1

### Context

android platform

### Log, call stack, etc

```shell
N/A
```

**Comment by nanangizz** [comment]
I think you're right, from [AudioRecord.read()](https://developer.android.com/reference/android/media/AudioRecord#read(byte[],%20int,%20int,%20int)) and [AudioTrack.write()](https://developer.android.com/reference/android/media/AudioTrack#write(byte[],%20int,%20int)), using byte array for 16 bit PCM seems to be deprecated. Well, it is actually very practical to be able to use byte array for both 8 bit PCM & 16 bit PCM. PJMEDIA uses mostly (if not all) 16 bit PCM only, so perhaps we can drop the 8 bit PCM in Android JNI device.

> The format can be [AudioFormat#ENCODING_PCM_16BIT](https://developer.android.com/reference/android/media/AudioFormat#ENCODING_PCM_16BIT), but this is deprecated.
