### ISSUE TITLE
Handling Disconnection in Android Using PJSIP

### ISSUE THREAD

**Issue by ccalywm** [pjsip/pjproject#3903]
### Describe the bug

I am using PJSIP for VoIP calling in an Android application. However, I noticed that when one party (e.g., the remote party) disconnects from the network, the other party (e.g., my side) does not receive any callback indicating that the remote party has disconnected from the network. This leads to the call being maintained indefinitely until the remote party reconnects to the network.

I would like to automatically end the call within a certain time period (e.g., 8 seconds) after the remote party disconnects from the network, instead of waiting for the remote party to reconnect. How can I implement this functionality? Are there any relevant APIs or callback functions that can help me achieve this?

### Steps to reproduce

    1.Initiate a call using PJSIP on Android device A with the following format: sip:172.16.27.250:6000.
    2.Disconnect the network connection on Android device B.
    3.Observe the call status and notice that the call does not automatically end.

### PJSIP version

2.14.1

### Context

    PJSIP Version: 2.14.1
    Android Version: Android 11
    Other relevant information: (If any other relevant information is available, please provide it here)

### Log, call stack, etc

```shell
PJSIP Version: 2.14.1
    Android Version: Android 11
    Other relevant information: (If any other relevant information is available, please provide it here)
```

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/api/generated/pjsip/group/group__PJSUA__LIB__BASE.html#_CPPv419pjsua_sip_timer_use

https://datatracker.ietf.org/doc/html/rfc4028.html

**Comment by ccalywm** [comment]
Thank you
