### ISSUE TITLE
Cross-compilation with --host=arm-none-eabi  aconfigure: error is reported

### ISSUE THREAD

**Issue by zhoujimmyg** [pjsip/pjproject#3907]
### Describe the bug

**When I execute ./configure --host=arm-none-eabi，an aconfigure: error is reported。The error information is as follows:**
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-none-eabi
checking target system type... arm-none-eabi
checking for arm-none-eabi-gcc... arm-none-eabi-gcc
checking whether the C compiler works... no
aconfigure: error: in `/home/jg/siptest/pjproject-2.14.1':
aconfigure: error: C compiler cannot create executables
See `config.log' for more details
**Then I check the config.log found those:**
/home/jg/siptest/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /home/jg/siptest/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
exit.c:(.text.exit+0x2c): undefined reference to `_exit'
collect2: error: ld returned 1 exit status

I even try the command: ./configure --host=arm-none-eabi --specs=nano.specs , it do not work  even a new error  "aconfigure: error: unrecognized option: `--specs=nano.specs'" 

### Steps to reproduce

1、Copy pjproject-2.14.1.tar.gz to Ubuntu 18.04(x86_64)
2、Configure the cross-compilation environment（gcc-arm-none-eabi-10.3-2021.10） 
3、 Unzip pjproject-2.14.1.tar.gz and enter “pjproject-2.14.1” directory 
4、Run the command: ./configure --host=arm-none-eabi 

### PJSIP version

2.14.1（2.10）

### Context

Cross-compilation  pjproject using the ubuntu18.04 system
Both pjproject-2.14.1 and pjproject-2.10 versions have been tried  

### Log, call stack, etc

```shell
compilation terminated.
aconfigure:2973: $? = 1
aconfigure:2993: checking whether the C compiler works
aconfigure:3015: arm-none-eabi-gcc -O2   conftest.c  >&5
/home/jg/siptest/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: /home/jg/siptest/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/lib/libc.a(lib_a-exit.o): in function `exit':
exit.c:(.text.exit+0x2c): undefined reference to `_exit'
collect2: error: ld returned 1 exit status
aconfigure:3019: $? = 1
aconfigure:3057: result: no
aconfigure: failed program was:
| /* confdefs.h */
```

**Comment by sauwming** [comment]
For custom cross compilation, you may need to set other variables too, such as CFLAGS and LDFLAGS.
Google around for more details.
