### ISSUE TITLE
Android UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xreleven** [pjsip/pjproject#3912]
### Describe the bug

I made app with this gradle library.
but it's not working
App is crashed with this error:
![1712108931172](https://github.com/pjsip/pjproject/assets/18528984/7d064da8-7b19-4f94-85d9-ee7d76d4f1d6)pjsua2 loaded

### Steps to reproduce

Import the so file into the project, and an exception is reported when starting to setAccount.
![1712119234793](https://github.com/pjsip/pjproject/assets/18528984/11ecdf5a-6942-451b-8fcb-a567e9f399de)

### PJSIP version

2.11 and 2.14.1

### Context

android api 34 JavaVersion.VERSION_17

### Log, call stack, etc

```shell
No implementation found for void sip.pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_sip_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_sip_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__) - is the library loaded, e.g. System.loadLibrary?
```

**Comment by sauwming** [comment]
Check if the device supports API 34

**Comment by MicroX-Hub** [comment]
> 检查设备是否支持 API 34

FATAL EXCEPTION: main
                                                                                                    Process: com.airnet.call.free.global.im, PID: 27914
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for void pjsip.pjsua2.pjsua2JNI.swig_module_init() (tried Java_pjsip_pjsua2_pjsua2JNI_swig_1module_1init and Java_pjsip_pjsua2_pjsua2JNI_swig_1module_1init__) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at pjsip.pjsua2.pjsua2JNI.swig_module_init(Native Method)
                                                                                                    	at pjsip.pjsua2.pjsua2JNI.<clinit>(pjsua2JNI.java:2835)
                                                                                                    	at pjsip.pjsua2.Endpoint.<init>(Endpoint.java:69)
