### ISSUE TITLE
Unknown Error 

### ISSUE THREAD

**Issue by PiotrZychski** [pjsip/pjproject#3914]
### Describe the bug

 C++ pj::Error:
Title:       pjsua_call_make_call(acc.getId(), &pj_dst_uri, param.p_opt, this, param.p_msg_data, &id)
Code:        450001
Description: Nie zdefiniowany błąd zewnętrzny.
Location:    D:\inContact-Git\Other\pjsip\pjproject\pjsip\src\pjsua2\call.cpp:679

### Steps to reproduce

After successfull connection with server I do :
using (CallOpParam callPrm = new CallOpParam())
{
    callPrm.opt.audioCount = 1;
    callPrm.opt.videoCount = 0;
    ObiektRozmowy = new Rozmowa(ObiektKonta);
    string ParametryTelelefonu = "sip:" + Telefon.Trim() + "@" + Serwer.Trim();
    ObiektRozmowy.makeCall(ParametryTelelefonu, callPrm);
}

### PJSIP version

2.14

### Context

I'm using it in C#. 

### Log, call stack, etc

```shell
After starting I've got error
```

**Comment by sauwming** [comment]
Check the PJSIP log. It will tell you what the error is.

**Comment by PiotrZychski** [comment]
Where is this log ?
