### ISSUE TITLE
where is log of library?

### ISSUE THREAD

**Issue by PiotrZychski** [pjsip/pjproject#3918]
### Describe the bug

Where is this log ?

### Steps to reproduce

Where is this log ?

### PJSIP version

Where is this log ?

### Context

Where is this log ?

### Log, call stack, etc

```shell
Where is this log ?
```

**Comment by shubhamfuloria** [comment]
Can you please elaborate the issue ?
You can set log file path in `Endpoint` configurations.
```cpp
  ep = new Endpoint;
  ep->libCreate();
  EpConfig ep_config;
  ep_config.logConfig.filename = LOG_FILE_PATH; // LOG_FILE_PATH should be file path where you want logs
  // other configurations here
  ep->libInit(ep_config);     
```
