### ISSUE TITLE
How use PjCamera2.java

### ISSUE THREAD

**Issue by azizconi** [pjsip/pjproject#3922]
### Describe the bug

When I wanted use PjCamera2 I didnt find tutorial for using 
Write please how we can use PjCamera2 for android 

### Steps to reproduce

Android Video

### PJSIP version

2.13.1

### Context

Android

### Log, call stack, etc

```shell
Android PjCamera2
```

**Comment by sauwming** [comment]
Check the sample app

**Comment by azizconi** [comment]
I'm checked sample app, but sample don't use PjCamera2. Sample only have class  PjCamera2.java. 
Can you help me. How I can use PjCamera2
