### ISSUE TITLE
Start and stop VideoPreview 

### ISSUE THREAD

**Issue by azizconi** [pjsip/pjproject#3923]
### Describe the bug

when I ```start`` the ```preview``` the video is shown correctly, but if I ```stop``` the preview the video changes its ```orientation```
![screen](https://github.com/pjsip/pjproject/assets/76108391/e3d4c218-c9d2-4b5a-86ed-1c98407a37af)
![screen2](https://github.com/pjsip/pjproject/assets/76108391/b5294bdb-2a5e-4f0c-a24f-8da8b6f9b4ed)

```
if (videoCallParams.isCameraShow) {
                    getService()?.getCurrentCall()?.startPreview(binding.surfacePreviewCapture.surfaceTexture)
                } else {
                    getService()?.getCurrentCall()?.stopPreview()
                }
                
                
                fun startPreview(surfaceTexture: SurfaceTexture?) {
        surfaceTexture ?: return
        val videoWindowHandle = VideoWindowHandle()
        videoWindowHandle.handle.setWindow(Surface(surfaceTexture))
        val videoPreviewOpParam = VideoPreviewOpParam()
        videoPreviewOpParam.window = videoWindowHandle

        try {
            vidPrev.start(videoPreviewOpParam)
        } catch (ex: Exception) {
        }
    }

    fun stopPreview() {
        try {
            vidPrev.stop()
        } catch (_: Exception) {}
    }
                ```

### Steps to reproduce

video android 

### PJSIP version

2.13.1

### Context

Android 13 Samsung A51 

### Log, call stack, etc

```shell
VideoPreview
```

**Comment by sauwming** [comment]
Since there's no benefit of stopping video preview during video call (because the camera will not be closed anyway), I would advise against doing so.

If you have no use for the preview, you can hide it from the user instead (i.e. not show the preview window/view in your app).
