### ISSUE TITLE
how to use PjCamera2

### ISSUE THREAD

**Issue by azizconi** [pjsip/pjproject#3931]
### Describe the bug

I don't find tutorial how can I use PjCamera2.java in android app and in sample project don't find too. Can you explain how to use PjCamera in project. Because VideoPreview lagged during video call. I need to use native methods.

### Steps to reproduce

org.pjsip.PjCamera2

### PJSIP version

2.13.1

### Context

Android

### Log, call stack, etc

```shell
PjCamera2
```

**Comment by sauwming** [comment]
Not sure what you're trying to do. By default, PJSIP will use Camera2, check `pjmedia-videodev/android_dev.c`.

Currently the issue page is for bug report or feature request only, not for asking enquiries.
