### ISSUE TITLE
importerror: module use of python24.dll conflicts with this version of python.

### ISSUE THREAD

**Issue by shubhamkar2104** [pjsip/pjproject#3932]
### Describe the bug

I builded the pjsua for python successfully and install it in python 2.8.10 version but when I am importing the pjsua there is an error "importerror: module use of python24.dll conflicts with this version of python." And _/pjsua.py giving error like 
Import _pjsua
importerror: module use of python24.dll conflicts with this version of python.
Does anyone has idea how to resolve it

### Steps to reproduce

Run the setup.py in visual studio community version 2022
Followed instructions from pjsua documentation 
Successfully installed without any error 

### PJSIP version

2.11

### Context

I have problem not bug

### Log, call stack, etc

```shell
Na
```

**Comment by sauwming** [comment]
Clean everything, uninstall the previous PJSIP and Python installations if necessary, and rebuild.

**Comment by shubhamkar2104** [comment]
I have 64 bit pc so it will run on that
Or this error occurs due to I used latest version of python.. can u guide
me please
