### ISSUE TITLE
I want to build pjsua for python 3 i tried different ways can you guide me how to do this.......

### ISSUE THREAD

**Issue by shubhamkar2104** [pjsip/pjproject#3933]
### Describe the bug

I tried to build by official documentation but builded the pjsua for python 2 as I want to build it for the python 3 for some project... I am not getting anywhere to do this so can you guide me to do this 

### Steps to reproduce

I builded it successfully for python for version 2.4 . I want to build it for 3.4 cause I am not able to use 2.4 python version in visual studio code as a compiler...
Can you guide me how to build pjsua for python 3 please 

### PJSIP version

2.14.1

### Context

Building pjsua for the python version 3. Can you give me guidence to do that and build and install it successfully 

### Log, call stack, etc

```shell
Na
```

**Comment by nanangizz** [comment]
Hi, currently the Python binding is only via SWIG and using PJSUA2, see the instruction [here](https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module). I am afraid that other Python bindings are deprecated already.

**Comment by shubhamkar2104** [comment]
I am building the softphone for windows platform so what suggestions you will give me how to use this lib in my softphone.....  Should I try another language for it.... If yes how can I use this lib to create softphone for windows

**Comment by nanangizz** [comment]
Actually what I tried to say was that the library currently has about three Python bindings, two are already deprecated (`pjsip-apps/src/python` & `pjsip-apps/src/py_pjsua`, both may only support Python 2), only one is officially supported, i.e: via SWIG previously pointed out, this allows you using Python 3.

**Comment by shubhamkar2104** [comment]
I tried your suggestion but not able to get the pjsua or pjsua2 lib as
output can I get any reference so that I can build it and use of for
another application for windows i want to build it in windows as it is a
requirement...thaks in advance and your help is appreciated....
