### ISSUE TITLE
Build android error

### ISSUE THREAD

**Issue by Malone-5334** [pjsip/pjproject#3936]
### Describe the bug

if i use ./configure-android,error code :
	-c -o output/pjmedia-audiodev-x86_64-unknown-linux-gnu/android_jni_dev.o \
	../src/pjmedia-audiodev/android_jni_dev.c 
../src/pjmedia-audiodev/android_jni_dev.c:35:10: fatal error: jni.h: No such file or directory
   35 | #include <jni.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [/home/ma/pjproject-2.14.1/build/rules.mak:163: output/pjmedia-audiodev-x86_64-unknown-linux-gnu/android_jni_dev.o] Error 1
make[2]: Leaving directory '/home/ma/pjproject-2.14.1/pjmedia/build'
make[1]: *** [Makefile:232: libpjmedia-audiodev-x86_64-unknown-linux-gnu.a] Error 2
make[1]: Leaving directory '/home/ma/pjproject-2.14.1/pjmedia/build'
make: *** [Makefile:14: all] Error 1
ma@malone:~/pjproject-2.14.1$ 

if i use ./configure,then make dep and make, the error code:
	-c -o output/pjmedia-audiodev-x86_64-unknown-linux-gnu/android_jni_dev.o \
	../src/pjmedia-audiodev/android_jni_dev.c 
../src/pjmedia-audiodev/android_jni_dev.c:35:10: fatal error: jni.h: No such file or directory
   35 | #include <jni.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [/home/ma/pjproject-2.14.1/build/rules.mak:163: output/pjmedia-audiodev-x86_64-unknown-linux-gnu/android_jni_dev.o] Error 1
make[2]: Leaving directory '/home/ma/pjproject-2.14.1/pjmedia/build'
make[1]: *** [Makefile:232: libpjmedia-audiodev-x86_64-unknown-linux-gnu.a] Error 2
make[1]: Leaving directory '/home/ma/pjproject-2.14.1/pjmedia/build'
make: *** [Makefile:14: all] Error 1

### Steps to reproduce

./configure-android

./configure
make dep
make

### PJSIP version

2.14.1

### Context

lscpu
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual

arm64-v8a  ndk24.3  android-32

[u(29)_2024-04-23_16_28_35.log](https://github.com/pjsip/pjproject/files/15073813/u.29._2024-04-23_16_28_35.log)

### Log, call stack, etc

```shell
log file is upload
```

**Comment by sauwming** [comment]
Check the Getting Started doc
