### ISSUE TITLE
Loading the so file crashed in android5.1

### ISSUE THREAD

**Issue by chenmingdu** [pjsip/pjproject#3937]
### Describe the bug

It crashed when booted on android5.1

### Steps to reproduce

It crashed when booted on android5.1

### PJSIP version

2.13

### Context

android5.1     android-ndk-r20b   pjsip2.13
 
 TARGET_ABI=armeabi-v7a APP_PLATFORM=android-23 ./configure-android --use-ndk-cflags

### Log, call stack, etc

```shell
2024-04-26 09:56:10.021 28640-28640/com.unionbroad.app E/art: dlopen("/data/app-lib/com.unionbroad.app-1/libpjsua2.so", RTLD_LAZY) failed: dlopen failed: empty/missing DT_HASH in "libpjsua2.so" (built with --hash-style=gnu?)
2024-04-26 09:56:10.022 28640-28640/com.unionbroad.app E/SipService: Error while loading PJSIP pjsua2 native library
    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libpjsua2.so" (built with --hash-style=gnu?)
```

**Comment by nanangizz** [comment]
Never experienced this myself, so tried to search around about the error and found [this](https://stackoverflow.com/questions/28638809/android-ndk-unsatisfiedlinkerror-dlopen-failed-empty-missing-dt-hash).

Perhaps you can try to insert `--hash-style=both` into [this line](https://github.com/pjsip/pjproject/blob/4f3df90a3eb7e732283a4e312c7a3a003d791bd3/pjsip-apps/src/swig/java/Makefile#L150)?

**Comment by chenmingdu** [comment]
> 我自己从未经历过这种情况，所以尝试搜索该错误并发现了[这个](https://stackoverflow.com/questions/28638809/android-ndk-unsatisfiedlinkerror-dlopen-failed-empty-missing-dt-hash)。
> 
> 也许你可以尝试插入`--hash-style=both`到[这一行](https://github.com/pjsip/pjproject/blob/4f3df90a3eb7e732283a4e312c7a3a003d791bd3/pjsip-apps/src/swig/java/Makefile#L150)？

Hello, after I added this line, I got an error executing make
![1714440358384](https://github.com/pjsip/pjproject/assets/21030515/6d52f252-6ef7-4963-923d-4d6119657bfb)
![1714440411739](https://github.com/pjsip/pjproject/assets/21030515/9b3763ca-33d8-4995-b079-fa5fce14de76)

**Comment by nanangizz** [comment]
Oops, note that `-Wl,-soname,libpjsua2.so` cannot be separated. So try:
```
MY_JNI_LDFLAGS+= -Wl,-soname,libpjsua2.so --hash-style=both
```

**Comment by chenmingdu** [comment]
> 哎呀，注意`-Wl,-soname,libpjsua2.so`不能分开。所以尝试：
> 
> ```
> MY_JNI_LDFLAGS+= -Wl,-soname,libpjsua2.so --hash-style=both
> ```

Hello, I used your writing method, recompile, there is another error...
![333](https://github.com/pjsip/pjproject/assets/21030515/664bff70-f6fc-44aa-942d-58760d4167da)
