### ISSUE TITLE
send Dtmf does not work in pjsip 2.14.1

### ISSUE THREAD

**Issue by muhammadjon-swift** [pjsip/pjproject#3944]
### Describe the bug

dialing Dtmf from call. I get the error "Remote does not support RFC 2833" but the thing is remote does support it. 
It works fine in pjsip 2.14

### Steps to reproduce

just run call->dialDtmf(digit);

### PJSIP version

2.14.1

### Context

Xcode 15.3
iOS 17.2
Mac OS Sonoma 14.4.1

### Log, call stack, etc

```shell
18:10:45.771            pjsua_aud.c !Call 0 dialing DTMF 1
18:10:45.771               call.cpp  pjsua_call_dial_dtmf(id, &pj_digits) error: Remote does not support RFC 2833 (PJMEDIA_RTP_EREMNORFC2833) (status=220107) [../src/pjsua2/call.cpp:789]
```

**Comment by nanangizz** [comment]
The error is raised when the remote SDP does not indicate rfc2833 support, e.g: no tel-event payload type. Please check the tel-event format negotiation in SDP offer/answer.

**Comment by muhammadjon-swift** [comment]
> The error is raised when the remote SDP does not indicate rfc2833 support, e.g: no tel-event payload type. Please check the tel-event format negotiation in SDP offer/answer.

I understand nevertheless as I mentioned above it works fine in the previous version of pjsip (2.14) so the only reasonable deduction would be that something is wrong in this version.

**Comment by muhammadjon-swift** [comment]
> The error is raised when the remote SDP does not indicate rfc2833 support, e.g: no tel-event payload type. Please check the tel-event format negotiation in SDP offer/answer.

I guess the problem might be in my end because my last build with pjsip 2.14 I had OpenSSL now in this build I'm using Native TLS backend for iOS. You see I've built the pjsip 2.14 with native TLS backend and I'm getting the same error "Remote does not support RFC 2833"

**Comment by muhammadjon-swift** [comment]
> > The error is raised when the remote SDP does not indicate rfc2833 support, e.g: no tel-event payload type. Please check the tel-event format negotiation in SDP offer/answer.
> 
> Important addition my last build with pjsip 2.14 I had OpenSSL now in this build I'm using Native TLS backend for iOS. You see I've built the pjsip 2.14 with native TLS backend and now I'm getting the same error "Remote does not support RFC 2833"

Problem resolved all I had to do is disable a couple of codecs. Thanks guys
