### ISSUE TITLE
sip parser memory overflow

### ISSUE THREAD

**Issue by qqzhou2018** [pjsip/pjproject#3948]
### Describe the bug

we use pj_strdup to copy the contact(sip_url）
in function int_parse_sip_url, code line: "if (parse_params && *scanner->curptr == '?')" 
do not check the boarder of the scanner->curptr which means when the *(scanner->curptr)+1 random to '?', following procedure is unexpectable.

we use pj_strdup_with_null instead of pj_strudup to work-around this issue.

### Steps to reproduce

1. run gdb pjsip-app/bin/pjsua-xxx
2. b int_parse_sip_url
3. r
4. press c to continue until see the command screen
5. make call
6. type dest_uri as : sip:gw+jiangsu_1015_0001496d@1.1.1.1:5060;transport=tcp;tport=tcp;gw=1015_0001496d
7. p scanner->ptr[84] will get 'd'
8. s scanner->ptr[85]='?'
9. c
10. now the function will run in unexpectable way and stack of function has been modified to wrong routing.

### PJSIP version

2.14.1

### Context

linux centos 7.4

### Log, call stack, etc

```shell
we found that scanner has pointer to end, but do no use in parser function.
```

**Comment by qqzhou2018** [comment]
change code to :
    if (parse_params && scanner->curptr<scanner->end &&*scanner->curptr == '?')

**Comment by sauwming** [comment]
`pjsip_parse_*()` API requires buffer to be NULL terminated indeed.

**Comment by qqzhou2018** [comment]
in function int_parse_msg, 
code : "if (ctype_hdr && scanner->curptr!=scanner->end)" 
seems correct for iterating over string :scanner->curptr
