### ISSUE TITLE
i am not able to install pjsua for python in windows

### ISSUE THREAD

**Issue by Vigh24** [pjsip/pjproject#3957]
### Describe the bug

i want to build pjsua 2 but there is not proper documentation for python can you guide me or give me the reference thanks in advance.

### Steps to reproduce

i already saw the pjsua2 documentation but there is only build for linux but i have to build it for windows as i need the final output in windows

### PJSIP version

2.11.1

### Context

i want to build pjsua 2 but there is not proper documentation for python can you guide me or give me the reference thanks in advance.

### Log, call stack, etc

```shell
na
```

**Comment by nanangizz** [comment]
Right, currently you need to use [GNU tools on Windows](https://docs.pjsip.org/en/latest/get-started/posix/build_instructions.html), e.g: mingw/mingw-w64, and follow the instructions of building Python SWIG for GNU/Linux. Note that some video features may not work such as DirectShow renderer.

**Comment by Vigh24** [comment]
i already went through this but there are only the linux command not for mysys32....can i get any help for that or other alternative that might work for building the pjsua for python...?

**Comment by Vigh24** [comment]
> i already went through this but there are only the linux command not for mysys32....can i get any help for that or other alternative that might work for building the pjsua for python...?

can you please help??

**Comment by nanangizz** [comment]
Building commands generally should be the same. For installing dependencies (swig, python, etc), you can always search around. Which commands you have problem with?

**Comment by Vigh24** [comment]
File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module> import _pjsua ImportError: DLL load failed: %1 is not a valid Win32 application. PS C:\Users\Administrator\Desktop\om> & C:/Python27/python.exe c:/Users/Administrator/Desktop/om/test.py Traceback (most recent call last): File "c:/Users/Administrator/Desktop/om/test.py", line 1, in <module> import pjsua File "C:\Python27\lib\site-packages\pjsua.py", line 59, in <module> import _pjsua ImportError: DLL load failed: %1 is not a valid Win32 application.

tried for both the versions of python 3 and python 2.7 and facing this error
