### ISSUE TITLE
Mitigating High Video Call Latency in Android Using PJSIP

### ISSUE THREAD

**Issue by ccalywm** [pjsip/pjproject#3968]
### Describe the bug

I am currently encountering high latency in video calls reaching up to 1000 milliseconds in an Android application utilizing PJSIP for VoIP calling. This significant latency negatively impacts user experience and real-time communication quality.
I am seeking guidance on how to effectively reduce video call latency to improve overall performance. Are there specific optimizations, settings, or strategies within PJSIP that can be implemented to mitigate latency in video calls? Additionally, are there any best practices or recommended approaches for addressing latency issues in Android applications utilizing PJSIP?

### Steps to reproduce

    1.Initiate a call using PJSIP on Android device A with the following format: sip:172.16.27.250:6000.
    2.Android device B answers the call.
    3.Measure and observe the latency during the ongoing call on both devices.

### PJSIP version

2.14.1

### Context

PJSIP Version: 2.14.1
Android Version: Android 11
Other relevant information: (If any other relevant information is available, please provide it here)

### Log, call stack, etc

```shell
PJSIP Version: 2.14.1
Android Version: Android 11
Other relevant information: (If any other relevant information is available, please provide it here)
```

**Comment by sauwming** [comment]
Identify the cause of the latency (such as network, video setup, high resolution, etc) and work from there.

Currently the issue page is for bug report or feature request only. For further questions, please use any other means such as StackOverflow.
