### ISSUE TITLE
using pjsua2 nodes with pw-link of pipewire fails because nodes of pjsua2 are not recognized

### ISSUE THREAD

**Issue by hstig** [pjsip/pjproject#3993]
### Describe the feature

Established call hold via pjsua2 in python and checked via 
```bash
$pw-cli ls Nodes
```

**Comment by sauwming** [comment]
More details are needed as to why this is a PJSIP issue and what needs to be fixed.

**Comment by sauwming** [comment]
I still don't see how this is a pjsip issue.

**Comment by sauwming** [comment]
I'm not familiar with pw and I don't think this is the right place to ask the question.
If there's anything to do from the PJSIP side , you can let us know.
