### ISSUE TITLE
Cannot get confsample.c to work properly

### ISSUE THREAD

**Issue by LucasCvjetkovic** [pjsip/pjproject#4002]
### Describe the bug

After building the pjsip project using default settings on ubuntu 22 confsample produces thread priority error. 

### Steps to reproduce

After building pjsip, run ./confsample in pjsip-apps/bin/samples/

### PJSIP version

2.14

### Context

This thread priority error message occurs in the sample project and the project I am working on

### Log, call stack, etc

```shell
10:50:51.854             alsa_dev.c !ca_thread_func(891897): Set thread priority for audio capture thread.
10:50:51.854             alsa_dev.c  Unable to increase thread priority, root access needed.
```

**Comment by sauwming** [comment]
As the log says, thread priority increase requires root access.
You can either run it with `sudo` or simply ignore the warning.
