### ISSUE TITLE
Unable to Install and Use pjsua2 with Python on macOS

### ISSUE THREAD

**Issue by LehmanDavid** [pjsip/pjproject#4010]
### Describe the bug

Hi there,

I'm having trouble installing and using the pjsua2 module with Python on my macOS system. Here are the details of my environment and the steps I followed, along with the issues I encountered. I would appreciate any help in resolving these issues.

Environment:

macOS version: 14.3 
Python version: 3.9
PJSIP version: latest

### Steps to reproduce

Clone PJSIP Project:
1. git clone https://github.com/pjsip/pjproject.git
2. cd pjproject

Configure and Build PJSIP:
3. ./configure --enable-shared --with-python
4. make dep
5. make
6. sudo make install

Generate SWIG Bindings:
7. cd pjsip-apps/src/swig
8. make
9. make install

Test pjsua2:
10. cd python
11. python3
12. > import pjsua2

### PJSIP version

2.14.1

### Context

I am trying to build pjsua2 python client for MacOS, but face an errors with installation, please could you provide me with the details what I've done wrong 

### Log, call stack, etc

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/david/Desktop/pjproject/pjsip-apps/src/swig/python/pjsua2.py", line 12, in <module>
    import _pjsua2
ImportError: dlopen(/Users/david/Library/Python/3.9/lib/python/site-packages/_pjsua2.cpython-39-darwin.so, 0x0002): Library not loaded: ../lib/libpjsua.dylib.2
  Referenced from: <0102D392-2380-3F62-B6D9-2090EE8E7D41> /Users/david/Library/Python/3.9/lib/python/site-packages/_pjsua2.cpython-39-darwin.so
  Reason: tried: '../lib/libpjsua.dylib.2' (no such file), '/System/Volumes/Preboot/Cryptexes/OS../lib/libpjsua.dylib.2' (no such file), '../lib/libpjsua.dylib.2' (no such file)
```

**Comment by sauwming** [comment]
Check the doc
