### ISSUE TITLE
Streaming audio after accepting the call

### ISSUE THREAD

**Issue by ahmed-troido** [pjsip/pjproject#4011]
### Describe the feature

I'm building a project to build a simple sip client to accept user calls and stream the voice to another service to do some  stuff, but I searched a lot in the official doc and Github to find a sample or something related to my case (I didn't find any result till now)

- Python version: 3.9
- Pjsua2: 2.14.1

I found something interesting called **PJMED_STRM** but I have no idea about it.
Also my actual scenario is posted over 4 years ago on [SOF](https://stackoverflow.com/questions/60129894/pjsua2-pjsip-python-real-time-audio-streams)

Snippet of my code:

```
class SipClient:

    ep = None  # Static member to hold the Endpoint object
    
    @staticmethod
    def initialize():
        # Create and initialize the library
        ep_cfg = pj.EpConfig()
        ep_cfg.uaConfig.threadCnt = 0
        ep_cfg.uaConfig.mainThreadOnly = True
        SipEndpoint.ep = pj.Endpoint()
        SipEndpoint.ep.libCreate()
        SipEndpoint.ep.libInit(ep_cfg)

        # Create SIP transport. Error handling sample is shown
        sipTpConfig = pj.TransportConfig()
        sipTpConfig.port = 5060
        tp=SipEndpoint.ep.transportCreate(pj.PJSIP_TRANSPORT_UDP, sipTpConfig)

        # Start the library
        SipEndpoint.ep.libStart()
        acfg = pj.AccountConfig()
        acfg.idUri = "sip:"+SIP_ID_URI
        acfg.regConfig.registrarUri = "sip:"+SIP_REGISTRAR_URI
        cred = pj.AuthCredInfo("digest", "*", SIP_USERNAME, 0, SIP_PASSWORD)
        acfg.sipConfig.authCreds.append( cred )

        # Create the account
        acc = Account()
        acc.create(acfg)

        while True:    
            SipEndpoint.ep.libHandleEvents(10)

        ep.libDestroy()
        del SipClient.ep
```

```
class Call(pj.Call):
    
    def __init__(self, acc, peer_uri='', chat=None, call_id=pj.PJSUA_INVALID_ID):
      
    def onCallState(self, prm):       

    def onCallMediaState(self, prm):
```

**Comment by sauwming** [comment]
what you're looking for seems to be connecting the call media port.
for an example, check the sample app on how to connect the call media to another media port, such as WAV recorder. The principle should be the same.

Note that currently the issue page is for bug report or feature request only, not for asking enquiries.

**Comment by cumthxy** [comment]
> what you're looking for seems to be connecting the call media port. for an example, check the sample app on how to connect the call media to another media port, such as WAV recorder. The principle should be the same.
> 
> Note that currently the issue page is for bug report or feature request only, not for asking enquiries.

but wav recorder only write to a wav file .how to get streams?
