### ISSUE TITLE
PRACK is not stopping retransmission 183 session progress

### ISSUE THREAD

**Issue by onir76** [pjsip/pjproject#4012]
### Describe the bug

We use PJSIP embedded with Asterisk.

We receive calls from an operator who requests prack support (we have set the parameter 100rel=peer_supported in the related section of pjsip.conf).

Asterisk receives the INVITE and reply with 183 session progress with header "Require: 100rel" than the source send PRACK and Asterisk reply with 200 OK to the PRACK.

Up to here everything is ok.

The problem is that after this first exchange of messages, asterisk continues to send the 183 progess to the source, always inserting the same RSeq as the first 183.

Below are the logs of SIP messages exchanged between source and asterisk and also the graph of the call.

![grafico](https://github.com/pjsip/pjproject/assets/175004095/d9026178-6021-431f-8c5c-cb295e459df7)

[debug_log_794.txt](https://github.com/user-attachments/files/16130819/debug_log_794.txt)

Please take a look starting line 874:

INVITE sip:+390244332310@operator5.it

The call involved has Call-ID : c17fc5f2df65452-0017-0002-0000-0000@10.5.46.168

### Steps to reproduce

To reproduce the problem I don't know how to do it since I use the PJSIP module inside Asterisk and the problem occurs on incoming calls.

### PJSIP version

2.13.1

### Context

Asterisk 20.6.0 on Ubuntu 24.04 LTS

### Log, call stack, etc

```shell
Attached the log of Asterisk with pjsip logger on.
```

**Comment by onir76** [comment]
Hi, has anyone had the opportunity to review what is indicated in this bug report? In practice it is not possible to use the function 100rel=peer_supported in case of incoming traffic where there is support for the prack in the invite (Supported: 100rel).

This bug is blocking.

**Comment by sauwming** [comment]
We have a similar test case here in https://github.com/pjsip/pjproject/blob/master/tests/pjsua/scripts-sipp/uac-prack-sdp-offer.xml and it seems to work fine.

So perhaps you need to check with the Asterisk side first.
I will close this issue for now, feel free to post an update here if there's an issue on our side.
