### ISSUE TITLE
Send audio frames or chunks for the caller instead of WAV

### ISSUE THREAD

**Issue by ahmed-troido** [pjsip/pjproject#4016]
### Describe the feature

I'm using this snippet of code to playback a wav file to the caller using pjsua2 `AudioMediaPlayer`

How to send a chunk by chunk (audio frames) to the caller instead of playing a wav file ?

**I need a way to send chunks instead of playing a WAV**

```
    def onCallState(self, prm):
        ci = self.getInfo()
        self.connected = ci.state == pj.PJSIP_INV_STATE_CONFIRMED
        if(self.connected ==True):
            player=pj.AudioMediaPlayer()
            #Play welcome message
            player.createPlayer('./welcomeFull.wav')
            i=0
            for media in ci.media:
                if (media.type == pj.PJMEDIA_TYPE_AUDIO):
                    self.aud_med = self.getMedia(i)
                    break
                i=i+1
            if self.aud_med!=None:
                mym= pj.AudioMedia.typecastFromMedia(self.aud_med)
                player.startTransmit( mym)
                mym.startTransmit( self.recorder);    
```

**Comment by andreas-wehrmann** [comment]
You could create a memplayer and supply the buffer yourself or you could create your own media port, insert it into the confbridge and then connect it to the call. The confbridge will then repeatedly call into your media port to get frames.

**Comment by ahmed-troido** [comment]
Thanks for your help
Could you please provide me with some resources or documentation about both ways (specially the `memplayer`)?

**Comment by andreas-wehrmann** [comment]
Sure, take a look at the PJ docs here:
- [memplayer](https://docs.pjsip.org/en/latest/api/generated/pjmedia/group/group__PJMEDIA__MEM__PLAYER.html)
- [memrecorder](https://docs.pjsip.org/en/latest/api/generated/pjmedia/group/group__PJMEDIA__MEM__CAPTURE.html)

**Comment by ahmed-troido** [comment]
Thanks but I tried to search the whole documentation to find a sample that using `memplayer` but I didn't find one.

also I tried to call this but there is no fun called `pjmedia_mem_player_create` in pj
`pj.pjmedia_mem_player_create()`

**I'm using python 3.9**

**Comment by andreas-wehrmann** [comment]
Ah sorry I didn't notice it was Python.
I'm not sure these "low level" functions are exported to Python...
I don't really have any experience in using pj from Python;
If there are no exports of these functions you might need to write and export them yourself I'm afraid.

**Comment by andreas-wehrmann** [comment]
Not really no, sorry.
