### ISSUE TITLE
When an industrial mobile phone with Android 7.1.1 system makes an outbound call using pjsip, the other party cannot hear the sound.

### ISSUE THREAD

**Issue by yudongdong12306** [pjsip/pjproject#4021]
### Describe the bug

When an industrial mobile phone with Android 7.1.1 system makes an outbound call using pjsip, the other party cannot hear the sound.
Log findings have been printed in the following logs:
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data

The hangup statistics log is as follows, showing that very little audio data is sent locally.
    Call time: 00h:00m:13s, 1st res in 99 ms, conn in 17659ms
    #0 audio PCMA @8kHz, sendrecv, peer=x.x.x.x:xxxx
       SRTP status: Not active Crypto-suite: 
       RX pt=8, last update:00h:00m:04.527s ago
          total 1.4Kpkt 236.4KB (295.6KB +IP hdr) @avg=61.6Kbps/77.1Kbps
          pkt loss=32 (2.1%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period: 640.000 640.000 640.000 640.000   0.000
          jitter     :   0.000 43550.746 536131.000 249601.000   4.216
       TX pt=8, ptime=20, last update:never
          total 37pkt 5.9KB (7.4KB +IP hdr) @avg=1.5Kbps/1.9Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.000   0.000   0.000   0.000
       RTT msec      :   0.000   0.000   0.000   0.000   0.000

### Steps to reproduce

pjsip versin 2.14
1. My outbound phone call operation(Android 7.1.1 system)
2. The other party answers
3. The other party can’t hear my voice

### PJSIP version

2.14

### Context

industrial mobile phone with Android 7.1.1 system

### Log, call stack, etc

```shell
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data
android_jni_de  Record thread : error 0 reading data

Call time: 00h:00m:13s, 1st res in 99 ms, conn in 17659ms
    #0 audio PCMA @8kHz, sendrecv, peer=x.x.x.x:xxxx
       SRTP status: Not active Crypto-suite: 
       RX pt=8, last update:00h:00m:04.527s ago
          total 1.4Kpkt 236.4KB (295.6KB +IP hdr) @avg=61.6Kbps/77.1Kbps
          pkt loss=32 (2.1%), discrd=0 (0.0%), dup=0 (0.0%), reord=0 (0.0%)
                (msec)    min     avg     max     last    dev
          loss period: 640.000 640.000 640.000 640.000   0.000
          jitter     :   0.000 43550.746 536131.000 249601.000   4.216
       TX pt=8, ptime=20, last update:never
          total 37pkt 5.9KB (7.4KB +IP hdr) @avg=1.5Kbps/1.9Kbps
          pkt loss=0 (0.0%), dup=0 (0.0%), reorder=0 (0.0%)
                (msec)    min     avg     max     last    dev 
          loss period:   0.000   0.000   0.000   0.000   0.000
          jitter     :   0.000   0.000   0.000   0.000   0.000
       RTT msec      :   0.000   0.000   0.000   0.000   0.000
```

**Comment by sauwming** [comment]
The log indicates there are issues with getting the data from the mic/input device. Try to test if the input device works fine by running local loopback test (refer to the doc for how).
