### ISSUE TITLE
Stop loop back for list of WAVs files

### ISSUE THREAD

**Issue by ahmed-troido** [pjsip/pjproject#4022]
### Describe the bug

I'm using `AudioMediaPlayer` to play a list of WAVs files `createPlaylist` but there is no option to stop loop back like `createPlayer` which takes `options` parameter 

**I'm using python**

```
class AudioMediaPlayer(AudioMedia):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        if self.__class__ == AudioMediaPlayer:
            _self = None
        else:
            _self = self
        _pjsua2.AudioMediaPlayer_swiginit(self, _pjsua2.new_AudioMediaPlayer(_self, ))

    def createPlayer(self, file_name, options=0):
        return _pjsua2.AudioMediaPlayer_createPlayer(self, file_name, options)

    def createPlaylist(self, *args):
        return _pjsua2.AudioMediaPlayer_createPlaylist(self, *args)
```

### Steps to reproduce

Try run this snippet :

wav_file_paths = ["123.wav", "xyz.wav"]
self.player = pj.AudioMediaPlayer()
self.player.createPlaylist(wav_file_paths)

### PJSIP version

2.14.2

### Context

OS : Linux - Fedora
Python: 3.9

### Log, call stack, etc

```shell
..
```

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/api/generated/pjsip/group/group__PJSUA2__MED.html#_CPPv4N2pj16AudioMediaPlayer14createPlaylistERK12StringVectorRK6stringj
