### ISSUE TITLE
Set payload Type for Codec AMR

### ISSUE THREAD

**Issue by ecionini** [pjsip/pjproject#4023]
### Describe the bug

To be able to connect correctly with a "strange" Asterisk SIp server it is necessary to force the payload type of a codec (AMR) to a precise value, but when I try to do so it seems that what is configured is ignored.

CodecParam cp = CodecParam();
    cp.info.avgBps = 4750;
    cp.info.maxBps = 16000;
    cp.info.clockRate = 8000;
    cp.info.channelCnt = 1;
    cp.info.pcmBitsPerSample = 16;
    cp.info.frameLen = 20;
    //cp.info.pt = PJMEDIA_RTP_PT_AMR;
    cp.info.pt = 114; // CONFIGURE STATIC PAYLOAD TYPE
    
    cp.setting.frmPerPkt = 1;
    cp.setting.plc = 1;
    cp.setting.vad = 1;
    
    cp.setting.decFmtp.clear();
    
    CodecFmtp dfmtp = CodecFmtp();
    dfmtp.name = "octet-align";
    dfmtp.val = "1";
    cp.setting.decFmtp.push_back(dfmtp);
    cp.setting.encFmtp.push_back(dfmtp);
    ep->codecSetParam("AMR/8000/1", cp);

I use PJSUA2.
Am I doing something wrong, shouldn't I do the configuration there?

### Steps to reproduce

Set CodecParam.info.pt = PT

### PJSIP version

2.14.1

### Context

iOS  17 - iphone 14 

### Log, call stack, etc

```shell
No crash occurs, the payload type of the AMR codec is configured dynamically (97) without considering my configuration.
```

**Comment by ecionini** [comment]
if I modify the SDP from the "transport_encode_sdp" callback, everything works as expected. If there isn't a more binding way to do it I can close the issue.

**Comment by ecionini** [comment]
I think it's even better to modify the sdp inside the "PWCall::onCallSdpCreated" callback (pjsua2).

void PWCall::onCallSdpCreated (OnCallSdpCreatedParam &prm){
  
    pjmedia_sdp_session * s = (pjmedia_sdp_session *)prm.sdp.pjSdpSession;
    pjmedia_sdp_media *m = s->media[s->media_count-1];
    
    pjmedia_sdp_attr *amr_attr1 = pjmedia_sdp_attr_find2(m->attr_count, m->attr, "rtpmap", &m->desc.fmt[1]);
    amr_attr1->value = {strdup("114 AMR/8000"),12};
    pjmedia_sdp_attr *amr_attr2 = pjmedia_sdp_attr_find2(m->attr_count, m->attr, "fmtp", &m->desc.fmt[1]);
    amr_attr2->value = {strdup("114 octet-align=1"),17};
    
    m->desc.fmt[1] = {strdup("114"),3};
}

is there a way to know what value (PT) has been dynamically assigned to the AMR codec?
I'm waiting to see if there are better ways, thanks.

**Comment by sauwming** [comment]
Dynamic Payload Type is not meant to be configurable since the value are supposed to be decided by endpoints via the SDP negotiation.
But if you're forced to do it, yes, onCallSdpCreated() can be used.
