### ISSUE TITLE
RTP timeout detection

### ISSUE THREAD

**Issue by martin-flaska** [pjsip/pjproject#4030]
### Describe the feature

I would like to have an easy way how to detect a SIP call is inactive (no audio data in RTP) and terminate it after reaching certain timeout. I did not find anything in pjsip/pjproject library related to this, only some solution mentioned below. I would expect some built-in callback function for indicating the call is inactive - no audio being received for specified time.

### Describe alternatives you've considered

[Here is some related issue #2844](https://github.com/pjsip/pjproject/issues/2844#issuecomment-949563037) cca 3 years old, which is kind of a workaround - adding a timer to check RTP rx count. Has something changed since that or is there another simple way how to do that?

### Additional context

There is ["rtp_timeout" configuration value in Asterisk](https://github.com/asterisk/asterisk/blob/master/configs/samples/pjsip.conf.sample#L830) pjsip.conf.sample file, but it seems to be not implemented in pjproject itself.

**Comment by amubiera** [comment]
I do a similar thing as in #2844. Start a timer and in the timeout:
- Get call info.
- Find the `PJMEDIA_TYPE_AUDIO` stream in the media list.
- Get the stats using `pjsua_call_get_stream_stat`.
- Compare `stats.rtcp.rx.pkt` against a stored value.
- End the call if `stats.rtcp.rx.pkt` hasn't changed in X seconds.

I used to compute a bytes/sec rate using `stats.rtcp.rx.bytes` and checked for less-than some KB/sec, but that was overkill for what I needed.

Re: Asterisk. If I'm interpreting correctly, it looks like Asterisk is handling it themselves in [res_pjsip_sdp_rtp.c - rtp_check_timeout](https://github.com/asterisk/asterisk/blob/master/res/res_pjsip_sdp_rtp.c#L146)

**Comment by andreas-wehrmann** [comment]
I'm not aware of a ready-to-use solution by PJ and I don't think it can provide one because there
are use cases where RTP streams can be stopped/paused without the signalling layer (in this case SIP) being involved
(I'm thinking about radio applications here, where this is not uncommon).
This is complicated by the fact, that a call can actually have more than one audio stream (though this is probably not the usual case for "normal" calls, except for some kind of conference calls maybe).

You said you wanted to detect _no audio data in RTP_ but I think what you actually want to detect is the _lack_ of RTP (audio) packets over a certain period of time.

I'm still going with the solution you mentioned above and it's still working fine for me; did you give it a try?
It's not too hard to implement (which is why I posted it as pseudo code);
also if you don't bring along your own timer implementation you should be able to make use of PJ timers just fine.
Maybe it works just as well for you.

Also, since you mentioned Asterisk:
Asterisk brings its own media/RTP implementation.
I think what they use from pjmedia is limited to the SDP part of the library.

**Comment by martin-flaska** [comment]
> I do a similar thing as in #2844. Start a timer and in the timeout:
> 
> * Get call info.
> * Find the `PJMEDIA_TYPE_AUDIO` stream in the media list.
> * Get the stats using `pjsua_call_get_stream_stat`.
> * Compare `stats.rtcp.rx.pkt` against a stored value.
> * End the call if `stats.rtcp.rx.pkt` hasn't changed in X seconds.
> 
> I used to compute a bytes/sec rate using `stats.rtcp.rx.bytes` and checked for less-than some KB/sec, but that was overkill for what I needed.
> 

Thank you Andreas for your ideas. I am using C++ part (PJSUA2), but the logic is more or less same.

* get call info (pj::CallInfo) in `MyCall::onCallMediaState` (derived from `pj::Call`) to get the audio audioMediaIdx (based on PJMEDIA_TYPE_AUDIO)
* start a timer (CallManager::utilTimerSchedule - derived from pj::Endpoint) in `CallManager::OnCallState` when receiving `PJSIP_INV_STATE_CONFIRMED` state
* check RTP data in the timer callback - `MyCall::getStreamStat(audioMediaIdx)` - `stat.rtcp.rxStat.bytes`
* hang up if not receiving data for specified timeout


> Re: Asterisk. If I'm interpreting correctly, it looks like Asterisk is handling it themselves in [res_pjsip_sdp_rtp.c - rtp_check_timeout](https://github.com/asterisk/asterisk/blob/master/res/res_pjsip_sdp_rtp.c#L146)

true, the Asterisk is calculating this timeout on its own.

**Comment by martin-flaska** [comment]
Thank you Andreas for you reply,

> I'm not aware of a ready-to-use solution by PJ and I don't think it can provide one because there are use cases where RTP streams can be stopped/paused without the signalling layer (in this case SIP) being involved (I'm thinking about radio applications here, where this is not uncommon). This is complicated by the fact, that a call can actually have more than one audio stream (though this is probably not the usual case for "normal" calls, except for some kind of conference calls maybe).
> 

yeah, my use case is just to handle a normal call, with one audio stream. I can realize there are many cases as you mentiond, but  can be maybe handled for each stream separately - so the callback could inform that a stream is stalled.

> You said you wanted to detect _no audio data in RTP_ but I think what you actually want to detect is the _lack_ of RTP (audio) packets over a certain period of time.

exactly, the goal is to auto hang up a stalled call.

> 
> I'm still going with the solution you mentioned above and it's still working fine for me; did you give it a try? It's not too hard to implement (which is why I posted it as pseudo code); also if you don't bring along your own timer implementation you should be able to make use of PJ timers just fine. Maybe it works just as well for you.

Yes, I tried that proposed above solution, works fine, but it required quite a lot of probably boilerplate code, as this seems to pre pretty common feature for normal calls at least. I do not think my implementation has sense to upstream, as IMO it should be not done in the C++ part, which is IMO kind of a wrapper of the C part.

If you, or anyone else, has some idea how and where it could be implemented, please comment. We could implement it sooner or later.

> 
> Also, since you mentioned Asterisk: Asterisk brings its own media/RTP implementation. I think what they use from pjmedia is limited to the SDP part of the library.

**Comment by sauwming** [comment]
The only thing I want to add is that we currently don't have any plan to implement this within PJSIP (but patch is welcome).
So, you can implement it in the application level as suggested above.
