### ISSUE TITLE
pcaputil: Failure when decoding silk

### ISSUE THREAD

**Issue by orgads** [pjsip/pjproject#4034]
### Describe the bug

I'm trying to convert a pcap file with SILK to wav. I built pjproject with silk enabled.

```
$ pjsip-apps/bin/samples/x86_64-unknown-linux-gnu/pcaputil --codec=SILK/16000 capture-silk-1.pcap capture-silk-1.wav
```

And got this error:
```
Error: pjmedia_codec_decode(app.codec, &frames[i], (unsigned)pcm_frame.size, &pcm_frame): Codec internal creation error (PJMEDIA_CODEC_EFAILED)
```

### Steps to reproduce

Run:
```
pcaputil --codec=SILK/16000 capture-silk-1.pcap capture-silk-1.wav
```
with [this pcap file](https://github.com/user-attachments/files/16579767/capture-silk-1.zip)

### PJSIP version

2.14.1

### Context

Linux

### Log, call stack, etc

```shell
os_core_unix.c !pjlib 2.14.1 for POSIX initialized
          pjlib  select() I/O Queue created (0x5b4b4138a948)
     endpoint.c  Warning: no worker thread is created in media endpoint for internal ioqueue
         silk.c  SILK codec version 1.0.9 initialized
          rtp.c  pjmedia_rtp_session_init: ses=0x5b4b40310da8, default_pt=0, ssrc=0x0
   wav_writer.c  File writer 'capture-silk-1.wav' created: samp.rate=16000, bufsize=4KB
         silk.c  Output size is 0
Error: pjmedia_codec_decode(app.codec, &frames[i], (unsigned)pcm_frame.size, &pcm_frame): Codec internal creation error (PJMEDIA_CODEC_EFAILED)
Written: 0m:00s.020
```

**Comment by sauwming** [comment]
Silk is part of Opus now, so since you seem to have success already with Opus (as shown in the recent PR you created), I believe this is no longer an issue?

**Comment by orgads** [comment]
Not really. I cannot decode this file with opus. Can you suggest how?

**Comment by sauwming** [comment]
I tested it here with https://github.com/collects/silk
I did not encounter any error, and the WAV file was successfully created although it contains only silence.
```
09:10:20.499                 silk.c  SILK codec version 1.0.9 initialized
09:10:20.499                  rtp.c  pjmedia_rtp_session_init: ses=0x104df7188, default_pt=0, ssrc=0x0
09:10:20.500           wav_writer.c  File writer 'capture-silk.wav' created: samp.rate=16000, bufsize=4KB
Written: 0m:14s.560
```

**Comment by orgads** [comment]
I never claimed it doesn't work at all, my problem is with the pcap attached to the message. This is a sample call from a real SIP provider - Voxbone IIRC.

**Comment by sauwming** [comment]
I tested with your pcap file.

**Comment by orgads** [comment]
What arguments did you pass? Did it convert successfully? Do you hear sound?

**Comment by sauwming** [comment]
I used the same arguments.
```
I did not encounter any error, and the WAV file was successfully created although it contains only silence.
```

[capture-silk-1.wav.zip](https://github.com/user-attachments/files/16668539/capture-silk-1.wav.zip)

**Comment by orgads** [comment]
I'm using flp silk. Maybe that's the difference? You can take it from https://github.com/audiocodes/silk/tree/decoder

**Comment by sauwming** [comment]
It's possible.
In any case, I don't think there's any issue with the pcaputil nor the codec wrapper itself.

**Comment by orgads** [comment]
But the decoder util in silk does work for the same file. Can you suggest how to debug this?

**Comment by sauwming** [comment]
From your log output `silk.c  Output size is 0`, I believe you already have the right idea.
So, `silk_codec_decode()` seems to fail to decode the frame, you need to find out why.

**Comment by orgads** [comment]
I ran a debugger and found that the failure is at:
```c
        /* We have already decoded this packet. */
        if (frm_info == 0 || silk->dec_buf_size[frm_info-1] == 0) {
            /* The decoding was a failure. */
            output->size = 0;
        }
```

Then the following condition is:
```c
    if (output->size == 0) {
        output->type = PJMEDIA_FRAME_TYPE_NONE;
        output->buf = NULL;
        return PJMEDIA_CODEC_EFAILED;
    }
```

But I'm unsure how to proceed from this point...

**Comment by sauwming** [comment]
After testing it with a SILK audio call using pjsua sample app, I think our SILK codec wrapper may no longer be working properly.
I saw a lot of logs printing:
`21:03:01.201        strm0x10f39b128  codec parsed 0 frames`
and there is no audio.

Unfortunately, we don't have a plan to fix this since nowadays, everybody planning to use SILK will use the one in Opus anyway.

So, if you still insist on making it work, my suggestion would be to test it with an audio call, run it under a debugger, and hopefully you can figure out what's wrong and fix it.

I will close this issue however due to the above reason.
