### ISSUE TITLE
Concerns about using getaddrinfo to obtain local IP in pj_gethostip

### ISSUE THREAD

**Issue by SamuraiAnderson** [pjsip/pjproject#4040]
### Describe the bug

Hello pjproject team,

I have concerns regarding the use of `getaddrinfo` in the `pj_gethostip` function. According to a discussion on StackOverflow ([link](https://stackoverflow.com/questions/2146191/obtaining-local-ip-address-using-getaddrinfo-c-function)), there are recommendations against using `getaddrinfo` for retrieving local IP addresses due to potential issues with DNS lookups in certain environments.

Additionally, there have been reports of long delays caused by `getaddrinfo` when DNS servers are not accessible in LAN environments, as discussed in [issue #3952](https://github.com/pjsip/pjproject/issues/3952) on this repository.

Could you please clarify the rationale behind the current implementation? Also, are there any considerations or plans to address these concerns in future updates?

Thank you for your attention to this matter.

Best regards,

### Steps to reproduce

Not applicable as the issue concerns internal architectural decisions rather than a runtime bug.

### PJSIP version

2.10 (observed that the issue persists in the latest release, version 2.14)

### Context

- The issue is relevant across all platforms where `getaddrinfo` might be used for local IP resolution in non-DNS-resolvable environments.
- This is particularly critical in embedded or isolated network environments where DNS is not reliable or accessible.

### Log, call stack, etc

```shell
Not applicable as this is a configuration and architectural concern rather than a specific runtime error.
```

**Comment by sauwming** [comment]
You can disable it via the setting `PJ_GETHOSTIP_DISABLE_LOCAL_RESOLUTION`.
