### ISSUE TITLE
Transfer failed

### ISSUE THREAD

**Issue by UaenaSone-William** [pjsip/pjproject#4050]
### Describe the bug

I'm trying to write a sip client to handle a physical ip phone incoming call.  It can normally make call and answer the incoming call.  But hen I want to transfer a call to another physical ip phone through a certain manufacturer's SIP server, It failed the transfer and receives a return code of 480 or 487, and the code i transferred uses "pjsua2.call.xfer".

I also tried transferring through a physical ip phone and it worked, so I think the server and phone from this manufacturer should be fine.  I captured the network packets when sending referrals in the above two situations as below.

The refer packet sent from my code (which failed):
```
REFER sip:10.0.0.108:5070 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.122:5066;rport;branch=z9hG4bKPj64eebfaa-9bb5-4280-8106-d4c9eeebbe02
Max-Forwards: 70
From: <sip:106@10.0.0.122>;tag=23e22f21-53c4-4dc5-8ec4-d4115ab4a711
To: "100" <sip:100@10.0.0.108>;tag=D73632463135364148528100
Contact: <sip:106@10.0.0.122:5066;ob>
Call-ID: 0218D1194C8140000000024D@10.0.0.108
CSeq: 15358 REFER
Event: refer
Expires: 600
Supported: replaces, 100rel, timer, norefersub
Accept: message/sipfrag;version=2.0
Allow-Events: presence, message-summary, refer
Refer-To: sip:104@10.0.0.108:5070
Referred-By: <sip:106@10.0.0.122>
Content-Length:  0
```

and the refer packet sent from the physical ip phone (which success):
```
REFER sip:100@10.0.0.108:5070 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.23:5060;branch=z9hG4bK1215831282;rport
From: <sip:104@10.0.0.23>;tag=1032007546
To: "100" <sip:100@10.0.0.108>;tag=2F343246313536419E6B8100
Call-ID: 0218D11BE881400000000251@10.0.0.108
CSeq: 3 REFER
Contact: <sip:104@10.0.0.23:5060>
Max-Forwards: 70
Supported: replaces, path, timer
User-Agent: NEC ITX-1615 1.0.4.152
Refer-To: <sip:103@10.0.0.108:5070>
Referred-By: <sip:104@10.0.0.108:5070>
Allow: INVITE, ACK, OPTIONS, CANCEL, BYE, SUBSCRIBE, NOTIFY, INFO, REFER, UPDATE, MESSAGE
Content-Length: 0
```

I'm also attaching my code for reference as follow.
[sip_client.txt](https://github.com/user-attachments/files/16689434/sip_client.txt)
Is there something I haven't noticed, or how should I handle this situation?
Hope you can help me, thanks!

### Steps to reproduce

1. run pjsua2.call.xfer
2. receive the return code 480 from one server and 487 from another

### PJSIP version

2.10

### Context

ubuntu 20.04 in docker container

### Log, call stack, etc

```shell
t
17:23:41.178           pjsua_call.c !Transferring call 0 to sip:1175@211.21.33.57:19064
17:23:41.178           pjsua_core.c  ...TX 670 bytes Request msg REFER/cseq=4666 (tdta0x1371958) to UDP 211.21.33.57:19064:
REFER sip:211.21.33.57:19064 SIP/2.0
Via: SIP/2.0/UDP 211.72.230.170:41732;rport;branch=z9hG4bKPj53962f6b-242f-43a3-961b-c85052032ba1
Max-Forwards: 70
From: <sip:1173@192.168.88.101;ob>;tag=97a7c1a5-1571-44f5-869d-873eddbe9ad3
To: <sip:1171@192.168.88.101>;tag=1315807509
Contact: <sip:1173@211.72.230.170:41732;ob>
Call-ID: 61f35c0b-1683782e06620a162195080023ab625b@211.21.33.57
CSeq: 4666 REFER
Event: refer
Expires: 600
Supported: replaces, 100rel, timer, norefersub
Accept: message/sipfrag;version=2.0
Allow-Events: presence, message-summary, refer
Refer-To: sip:1175@211.21.33.57:19064
Referred-By: <sip:1173@192.168.88.101;ob>
Content-Length:  0


--end msg--
17:23:41.178         evsub0x1375818  .....Subscription state changed NULL --> SENT
Enter command (c: call, h: hangup, a: answer, r: reject, t: transfer, q: quit): 17:23:41.229           pjsua_core.c  .RX 512 bytes Response msg 480/REFER/cseq=4666 (rdata0x7f9f34002248) from UDP 211.21.33.57:19064:
SIP/2.0 480 Temporarily Unavailable
Via: SIP/2.0/UDP 211.72.230.170:41732;rport=41732;branch=z9hG4bKPj53962f6b-242f-43a3-961b-c85052032ba1;received=211.72.230.170
Call-ID: 61f35c0b-1683782e06620a162195080023ab625b@211.21.33.57
From: <sip:1173@192.168.88.101;ob>;tag=97a7c1a5-1571-44f5-869d-873eddbe9ad3
To: <sip:1171@192.168.88.101>;tag=1315807509
CSeq: 4666 REFER
Allow: INVITE,ACK,CANCEL,BYE,INFO,OPTIONS,REGISTER,SUBSCRIBE,REFER
Server: Panasonic-MPR16-V009.00013/VSIPEXT-V3.0000
Content-Length: 0


--end msg--
17:23:41.229         evsub0x1375818  ....Subscription state changed SENT --> TERMINATED
17:23:41.230           pjsua_call.c  ......Xfer client subscription terminated
```

**Comment by sauwming** [comment]
I believe you should check with the remote or the server as to why they generated such response (480 or 487).

Alternatively, you can test it with our pjsua sample app to test the transfer feature.
You can use the command:
```
  x  Xfer call                
  X  Xfer with Replaces    
```

**Comment by UaenaSone-William** [comment]
> I believe you should check with the remote or the server as to why they generated such response (480 or 487).
> 
> Alternatively, you can test it with our pjsua sample app to test the transfer feature. You can use the command:
> 
> ```
>   x  Xfer call                
>   X  Xfer with Replaces    
> ```

Sorry, I would like to ask how to use your sample app or where can I refer to it?
