### ISSUE TITLE
Custom Call-ID to call_setting

### ISSUE THREAD

**Issue by austinkottke** [pjsip/pjproject#4051]
### Describe the feature

Ive added in the ability to pass in a custom call id to pjsua2 and pjsua. Affects the CPP api as well. This modifies the CallSetting structure. I use a professional paid pjsip license and would like to get this into the future releases. I realize this request was rejected earlier but if possible Id like to get it done.

If you would not like to include it in future releases that's fine. Other sip stacks have this ability and I will keep patching the pjsip releases for our software.

The good news is Ive rewritten the changes to be minimal. 

Shall I submit a PR? This touches two files. Tested on OSX/Win

**Comment by austinkottke** [comment]
pjsua_call.c

```
if( opt->user_call_id.slen >= 0 ){
        PJ_LOG(4,(THIS_FILE, "User defined call-id - copy to dialog ") );
        pj_strcpy(&dlg->call_id->id, &opt->user_call_id);
    }
```
...

pjsua.h: 

```
{
    pjmedia_dir	     media_dir[PJMEDIA_MAX_SDP_MEDIA];

    pj_str_t        user_call_id;

} pjsua_call_setting;
```


And call.cpp

```
pjsua_call_setting CallSetting::toPj() const
{
    pjsua_call_setting setting;
    unsigned mi;

    /* This is important to initialize media_dir array. */
    pjsua_call_setting_default(&setting);

    setting.flag                = this->flag;
    setting.req_keyframe_method = this->reqKeyframeMethod;
    setting.aud_cnt             = this->audioCount;
    setting.vid_cnt             = this->videoCount;
    for (mi = 0; mi < this->mediaDir.size(); mi++) {
        setting.media_dir[mi] = (pjmedia_dir)this->mediaDir[mi];
    }
 
    if( ! this->user_call_id.empty()) {
        setting.user_call_id = str2Pj(this->user_call_id);
        PJ_LOG(4, (THIS_FILE, "call_setting - set user_call_id (%s) ", this->user_call_id.c_str() ));
    }
     
    return setting;
}

```

**Comment by sauwming** [comment]
Yes, feel free to create a PR and we will review it.

**Comment by austinkottke** [comment]
Ok great PR is here: https://github.com/pjsip/pjproject/pull/4052

**Comment by austinkottke** [comment]
Thank you @sauwming and the team for the review, This is a great feature!
