### ISSUE TITLE
Commenting out pjsua_transport_set_enable broke the python3-pjsip

### ISSUE THREAD

**Issue by serbanman** [pjsip/pjproject#4063]
### Describe the bug

This commit in main:
https://github.com/pjsip/pjproject/commit/22b78f901a42fc5ac4120de764a17e8a832e220e
results in this dependency repo:
https://github.com/mgwilliams/python3-pjsip
raising an exception:

> ...
> pjsua  |   File "/usr/local/lib/python3.11/site-packages/pjsua-2.14.dev0-py3.11-linux-x86_64.egg/pjsua.py", line 60, in <module>
> pjsua  |     import _pjsua
> pjsua  | ImportError: /usr/local/lib/python3.11/site-packages/pjsua-2.14.dev0-py3.11-linux-x86_64.egg/_pjsua.cpython-311-> x86_64-linux-gnu.so: undefined symbol: pjsua_transport_set_enable

It's not obvious that this is the responsibility of this repository, but the dependency repository hadn't been updated for 5 years, was very stable, and was used by many people. I've opened an issue in this python3-pjsip repo: https://github.com/mgwilliams/python3-pjsip/issues/16
But I am not sure if it is still maintained.

### Steps to reproduce

1) Get and install latest https://github.com/pjsip/pjproject.git:
>RUN cd /tmp && \
>    git clone https://github.com/pjsip/pjproject.git && \
>    cd pjproject && \
>    ./configure --enable-shared && \
>    make dep && make && \
>    make install

2) Get and install latest https://github.com/mgwilliams/python3-pjsip (from the repo's docs):
> $ sudo apt install python3-dev
> $ cd pjproject-x.x/pjsip-apps/src/
> $ git clone https://github.com/mgwilliams/python3-pjsip.git
> $ cd python3-pjsip
> $ python3 setup.py build
> $ sudo python3 setup.py install
3) Try to use it:
> import pjsua as pj

### PJSIP version

latest

### Context

It looks like it is not platform-specific.

### Log, call stack, etc

```shell
pjsua  | Traceback (most recent call last):
...
pjsua  |   File "/app/sip/lib_manager.py", line 8, in <module>
pjsua  |     import pjsua as pj
pjsua  |   File "/usr/local/lib/python3.11/site-packages/pjsua-2.14.dev0-py3.11-linux-x86_64.egg/pjsua.py", line 60, in <module>
pjsua  |     import _pjsua
pjsua  | ImportError: /usr/local/lib/python3.11/site-packages/pjsua-2.14.dev0-py3.11-linux-x86_64.egg/_pjsua.cpython-311-x86_64-linux-gnu.so: undefined symbol: pjsua_transport_set_enable
```

**Comment by sauwming** [comment]
Thank you for the report, but we have decided to remove the API since it caused confusion to our users who expect it to work as specified.

Sorry for the inconvenience, we hope the repo maintainer can merge your suggested fix.
