### ISSUE TITLE
Contact Header Displays Internal IP After Network Switching

### ISSUE THREAD

**Issue by NetMobileDev** [pjsip/pjproject#4065]
### Describe the bug

During an ongoing call, when the user switches to a different cellular network, the contact header in the SIP messages sent by the pjsip client displays the internal IP address instead of the external IP. This discrepancy is observed despite using Google's STUN server and properly handling network changes with the handleipchange method followed by a reinvite. The c= header correctly reflects the external IP, but the contact header remains with the internal IP, which can lead to issues with call termination if the server requires the external IP for this purpose.

### Steps to reproduce

- Configure pjsip
- Set up pjsip with Google's STUN server. Initiate the call with wifi network and implement the handleipchange method to handle network changes before the re-invite method and it will only be call during the network switch from wifi to cellular.
- Initiate a call: Start a SIP call using pjsip.
- Switch networks: While the call is in progress, switch the device to a different cellular network.
- Observe headers: After the network switch, examine the SIP messages sent by pjsip to verify that the contact header contains the internal IP and the c= header contains the external IP.

### PJSIP version

2.14.1

### Context

The goal is to ensure that the contact header in SIP messages sent by pjsip always reflects the external IP, even after network switches. This is crucial for proper call termination and other functions that rely on the external IP.

### Log, call stack, etc

```shell
To provide more detailed information, adding the relevant log entries from pjsip application, focusing on the time around the network switch and the subsequent SIP message exchanges.
During the call started:
INVITE sip:whisper@g-fs-dev1.phoneic.com SIP/2.0

Via: SIP/2.0/UDP 182.73.214.30:63315;rport;branch=z9hG4bKPjCB1FDD36-B96A-452A-AFA9-9B87B68E02EC

Max-Forwards: 70

From: sip:1000@g-fs-dev1.phoneic.com;tag=105B0443-B5AF-4C26-BE24-23A8283AFD8A

To: sip:whisper@g-fs-dev1.phoneic.com

Contact: <sip:1000@182.73.214.30:63315;ob>[EXTERNAL IP]

Then Network switched to cellular:
Via: SIP/2.0/UDP 192.168.2.65:5060;rport;branch=z9hG4bKPjDE120C01-C1F2-4B87-9216-B47B2E247E44

Max-Forwards: 70

From: sip:1000@g-fs-dev1.phoneic.com;tag=862C27A7-B44D-4DC0-A345-25678D2F804F

To: sip:whisper@g-fs-dev1.phoneic.com;tag=e60D0aQZKX2vp

Contact: <sip:1000@192.0.0.2:5060;ob>
```

**Comment by sauwming** [comment]
Have you used the flag UPDATE_CONTACT? 

Check the complete log if everything is successful  or if there's any failure during the IP change process.
