### ISSUE TITLE
Redundant RTP Streams (RFC 7198)

### ISSUE THREAD

**Issue by GitHubIsShortOnUsernames** [pjsip/pjproject#4076]
### Describe the feature

Would it be possible to support RTP stream duplication as described in RFC 7198? It allows transmitting a redundant duplicate stream over a separate path or interface to increase resilience.

### Describe alternatives you've considered

Stream duplication could be handled on the network layer, but no standard exists for it, and without appropriate signaling, interoperability would be difficult. Existing solutions are proprietary.

### Additional context

Apparently it's becoming a big thing in the media industry as it transitions to SIP for audio connections.

**Comment by trengginas** [comment]
We don't have any plan to implement this. 
However, when using PJSUA/PJSUA2 you can specify the number of audio/video stream using `pjsua_call_setting::aud_cnt` or `pjsua_call_setting::vid_cnt`.

**Comment by hoene** [comment]
What else needs to be considered to implement it?

**Comment by sauwming** [comment]
Well, it depends whether you want to be fully compliant with the RFC.
If you only want redundant RTP streams over multiple paths as described in the RFC, adding the number of audio/video streams described above should be quite close.
