### ISSUE TITLE
Accessing Media Bi Directional RTP Stream using pjsua2 (python)

### ISSUE THREAD

**Issue by dmittal77** [pjsip/pjproject#4085]
### Describe the feature

Is it possible to gain access to bi-directional audio stream in some standard streaming format. 

The method frameRequested is apparently called only if you attach a source to an AudioPort, however it would be useful to have a capability to plugin a stream from an external speech engine for instance to one of the attached ports to the conf bridge so that the audio can infact be handled by an external speech engine. In case this is already possible, its not apparent in any documentation or examples.   Request inputs or references in case this is already possible with pjsua2 (python)

**Comment by nanangizz** [comment]
Not really sure what you want to achieve, `AudioMedia.startTransmit()` will setup for one direction only indeed, to have bidirectional audio flow, you'd just need to call it twice, one for each direction, e.g:
```
AudioMedia a, b;
a.startTransmit(b); // a -> b
b.startTransmit(a); // b -> a
```
Please check [the docs](https://docs.pjsip.org/en/latest/pjsua2/using/media_audio.html) in case you haven't.

**Comment by dmittal77** [comment]
Thank you @nanangizz . 
The situation we have is that we only have access to a streaming audio, no wav or mp3 files and neither do we want to capture the audio from the mic. How do we patch that to the remote party? We can do any streaming format so thats not an issue. 

Thank you.
