### ISSUE TITLE
Replace a call in PJSUA2: `call::onCallTsxState()` not called in state `PJSIP_TSX_STATE_PROCEEDING` when 

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#4087]
### Describe the bug

Function `call:onCallTsxState()` was not called in state `PJSIP_TSX_STATE_PROCEEDING` and/or `PJSIP_TSX_STATE_TRYING`. The first call back is in state `PJSIP_TSX_STATE_COMPLETED`.

Functions `call::onCallReplaced()` and `call::onCallReplaceRequest()` were not implemented, but this should not be a reason.

* As far as I know, there is also no `call::onCallTsxState()` called for a _new_ incoming INVITE.  Would be good to add this information to the documentation of `onCallTsxState()` in `call.hpp`. 
* Shouldn't be `call::onCallTsxState()` at least called in state `PJSIP_TSX_STATE_PROCEEDING`?

### Steps to reproduce

Was not done with a example / test app. 

### PJSIP version

2.14.1

### Context

This happens when Functions call::onCallReplaced() and call::onCallReplaceRequest() are not implemented.
Should be independent on OS and platform.

### Log, call stack, etc

```shell
Incoming INVITE with Replaces: 35df40da-f9d1-484c-929f-d8c9ff07a385;to-tag=fe982681-43d9-419f-b7d3-e80f53a07d1f;from-tag=971112669-337510680-1727162393208

Incoming Request msg INVITE/cseq=1 (rdata0x631001f40828)
Warning: application has not created new Call instance for call replace request (call ID:140)
Incoming Request msg INVITE/cseq=1 (rdata0x631001f40828) in state Null
State changed from Null to Trying, event=RX_MSG
...
Call 141: media transport initialization complete: Success
Response msg 100/INVITE/cseq=1 (tdta0x6210013561a8) created
Initial answer Response msg 100/INVITE/cseq=1 (tdta0x6210013561a8)
Sending Response msg 100/INVITE/cseq=1 (tdta0x6210013561a8)
Sending Response msg 100/INVITE/cseq=1 (tdta0x6210013561a8)
Sending Response msg 100/INVITE/cseq=1 (tdta0x6210013561a8) in state Trying

SIP/2.0 100 Trying

State changed from Trying to Proceeding, event=TX_MSG
Transaction tsx0x61d0001cb728 state changed to Proceeding
State changed from NULL to INCOMING, event=TSX_STATE
Warning: application has not created new Call instance for call replace (old call ID:140, new call ID:141)"
```

**Comment by sauwming** [comment]
Unfortunately there will be complications with the Call lookup if the callbacks are unimplemented (and that's why the warning):
https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua2/endpoint.cpp#L1505

**Comment by wosrediinanatour** [comment]
I see... 

Just a question: why is an Invite with Replaces header not "declined" by default, i.e. if the callbacks are not implemented?

So...I guess the ticket can be closed.

**Comment by sauwming** [comment]
For backward compatibility (no behavioral change vs older version), and consistency of behavior between pjsua and PJSUA2.
