### ISSUE TITLE
hangup api Timed-out trying to acquire dialog mutex (possibly system has deadlocked) in pjsua_call_send_request

### ISSUE THREAD

**Issue by zhuangguangkang0013** [pjsip/pjproject#4088]
### Describe the bug

IP CALL IP.
14:10:32 call hangup api, : 14:10:32.39  join CONFIRMED,  pjsip in  14:10:34.431  - 14:13:29.949 while  print time-out mutex.while to  14:13:29.960   RX remote hangup,in 14:13:29.984 join DISCONNCTD, in 14:13:30.190 RX remote bye.in   14:13:30.194 send remote ok while. see log info ,It seems that a deadlock has been triggered and I cannot actively hang up.

行 2489: 14:10:32.300   889  1146 D pjsip-PjsipService: 14:10:32.300   pjsua_call.c !Call 6 hanging 
行 2522: 14:10:32.395   889  1146 D pjsip-PjsipService:   [CONFIRMED] To: <sip:400882706172481536@19
行 2846: 14:10:34.431   889  1063 D pjsip-ev_thread: 14:10:34.429   pjsua_call.c !.Timed-out trying to acquire dialog mutex (possibly system has deadlocked) in pjsua_call_send_request
行 6715: 14:13:29.949   889  1063 D pjsip-ev_thread: 14:13:29.948  pjsua_media.c  Failed requesting keyframe via SIP INFO: Operation timed out (PJ_ETIMEDOUT)
行 6720: 14:13:29.960   889  1064 D pjsip-pjsua_0: 14:13:29.959   pjsua_core.c  .RX 410 bytes Request msg BYE/cseq=9223 (rdata0xd0991014) from UDP 192.168.1.107:5060:
行 6757: 14:13:29.984   889  1064 D pjsip-pjsua_0:   [DISCONNCTD] To: <sip:400882706172481536@192.16
行 6864: 14:13:30.190   889  1064 D pjsip-pjsua_0: 14:13:30.190   pjsua_core.c !.RX 410 bytes   Request msg BYE/cseq=9223 (rdata0xd0991014) from UDP 192.168.1.107:5060:
行 6878: 14:13:30.194   889  1064 D pjsip-pjsua_0: 14:13:30.193   pjsua_core.c  ..TX 385 bytes Response msg 200/BYE/cseq=9223 (tdta0xd2f9d064) to UDP 192.168.1.107:5060:

### Steps to reproduce

unkonw,may be next  sip talk .

### PJSIP version

2.12

### Context

os:android
os-verision:8.1
pjsip-versio:2.12.（sip:444424267241754624@192.168.1.105）
remote device pjsip version:2.10.（sip:400882706172481536@192.168.1.107）

### Log, call stack, etc

```shell
this is log .log max long.please see log file.
```

**Comment by zhuangguangkang0013** [comment]
this is log file 
[Uploading deadlockedLog.txt…]()

**Comment by sauwming** [comment]
We need the stack trace so we can know what caused the threads to get stuck.
Also, I would recommend trying the latest version, in case that the issue has been fixed there.

**Comment by sauwming** [comment]
Post here if there's an update.
