### ISSUE TITLE
Transmitting and Receiving RTP Stream without any Call involved

### ISSUE THREAD

**Issue by raj17ce** [pjsip/pjproject#4090]
### Describe the feature

in PJSUA2 API, I could not find feature to easily achieve the above task. I want to transmit and receive Audio/Video without making a call between 2 clients. Also there are not many samples related to it.
Is it possible to use Media transport standalone?? if yes, how ?

**Comment by sauwming** [comment]
Not PJSUA2, you need to use lower level APIs directly. Check the sample app.
