### ISSUE TITLE
read Video frames before being rendered in window

### ISSUE THREAD

**Issue by khaledJanky** [pjsip/pjproject#4096]
### Describe the feature

Hello everyone,

I am working on implementing Picture-in-Picture (PiP) functionality for video calls in an iOS app. However, I’ve encountered an issue: PiP in iOS only supports AVPlayer and doesn’t allow adding a custom UIView for video rendering.

To work around this, I want to capture video frames in a callback and feed them into AVSampleBufferDisplayLayer. 
is this supported?

Thank you in advance for your help!

**Comment by sauwming** [comment]
Try connecting a media port to the video conference. 

Alternatively, just extract the image from the UIView.

**Comment by khaledJanky** [comment]
thanks @sauwming  for your reply
ended with calling this function in On_call_media_state in order to connect a new port with exist video Conference 
`
pj_status_t create_port_for_call (pjsua_call_id call_id) {

    pj_pool_t *pool;
    my_vid_port *vid_port;
    pjsua_conf_port_id port_id;
    pj_status_t status;
    pool = pjsua_pool_create("vid_port", 1024, 1024);
    vid_port = PJ_POOL_ZALLOC_T(pool, my_vid_port);

    pjmedia_format format;
    pjmedia_format_init_video(&format, PJMEDIA_FORMAT_I420, 720, 1280, 15, 1);
    
    pj_str_t port_name = pj_str("MyCustomPort");
    pjmedia_port_info_init2(&vid_port->base.info, &port_name, 1, PJMEDIA_DIR_DECODING, &format);

    
    vid_port->base.get_frame = NULL;
    vid_port->base.put_frame = &my_vid_port_put_frame;
    vid_port->base.on_destroy = &on_port_destroy;

    
    status = pjsua_vid_conf_add_port(pool, &vid_port->base, NULL, &port_id);
    if (status != PJ_SUCCESS) {
        return status;
    }

    pjsua_conf_port_id capture_port = pjsua_call_get_vid_conf_port(call_id, PJMEDIA_DIR_ENCODING);
    if (capture_port == PJSUA_INVALID_ID) {
        return PJMEDIA_ERROR;
    }

    status = pjsua_vid_conf_connect(capture_port, port_id, NULL);

    return status;
}
`


but pjsua_vid_conf_connect show this log:
`
 vid_conf.c !.....Connect ports 3->4 requested
16:09:16.883             vid_conf.c  .....Failed connecting video ports, make sure that source has get_frame() & sink has put_frame():
`

did I miss something?
