### ISSUE TITLE
Support atypical SRV naming for TLS

### ISSUE THREAD

**Issue by troutkilroy** [pjsip/pjproject#4103]
### Describe the feature

Support SRV lookup for TLS SIP domains that use something other than a _sips._tcp prefix namely:

_sips._tls
_sip._tls

### Describe alternatives you've considered

Implementing our own SRV resolution for TLS transport instead of specifying a nameserver in PJSIP.

### Additional context

We've need to support SIP providers that prefix TLS SRV records as _sips._tls or _sip._tls. PJSIP always assumes _sips._tcp. is the TLS domain prefix for SRV lookup.

**Comment by sauwming** [comment]
The proper way is to use NAPTR, which we haven't supported.

But for a workaround, if your TLS SIP domain always translates to `_sips._tls`, I suppose you can change the hardcoded part in `sip_resolve.c`.
