### ISSUE TITLE
PJSUA2 endpoint.cpp !instance error: Not found (PJ_ENOTFOUND) (status=70006) [../src/pjsua2/endpoint.cpp:606]

### ISSUE THREAD

**Issue by datalin** [pjsip/pjproject#4104]
### Describe the bug

I am using the python pjsua2 library, i have installed it following the guideline here https://docs.pjsip.org/en/latest/pjsua2/building.html

pjsua2 import in python works, also the python hello world code here works https://docs.pjsip.org/en/latest/pjsua2/hello_world.html

I want to play a audio file when someone calls to the pjsua client, so i have setup a wav file in the code and wrote the code from the suggestion of chatgpt o1-mini But when i am trying to create an endpoint instance like the following

```
ep = pj.Endpoint.instance()
```

it gives me the error

```
endpoint.cpp !instance error: Not found (PJ_ENOTFOUND) (status=70006) [../src/pjsua2/endpoint.cpp:606]
Traceback (most recent call last):
```

This happens before i am trying to configure instantiated endpoint, so it should not be an issue with wav file location config, log config or tcp/tls config

chatgpt o1-mini suggested i build from setup.py file in pjproject repo, but they are in python2 and that instruction is conflicting with official doc plus im using python3 so avoided it. o1-mini also suggested that i verify pjsua2.so file is in the same directory as pjsua2.py in python site-packages, i found  _pjsua2.cpython-310-x86_64-linux-gnu.so to exist in the same directory, when i tried copying and renaming it to pjsua2.so, i cant import pjsua2 python module anymore.

What am i doing wrong?

### Steps to reproduce

Use this test code to check if ednpoint instantiation is supported. It checks if the modules are present then tries to instantiate Endpoint.

```
import pjsua2 as pj

def test_pjsua2():
    # Check for essential classes
    has_endpoint = hasattr(pj, 'Endpoint')
    has_account = hasattr(pj, 'Account')
    has_call = hasattr(pj, 'Call')
    has_audio_media_player = hasattr(pj, 'AudioMediaPlayer')

    print(f"Endpoint class exists: {has_endpoint}")
    print(f"Account class exists: {has_account}")
    print(f"Call class exists: {has_call}")
    print(f"AudioMediaPlayer class exists: {has_audio_media_player}")

    # Check if you can create an Endpoint instance
    try:
        ep = pj.Endpoint.instance()
        ep_cfg = pj.EpConfig()
        ep.libInit(ep_cfg)
        print("Endpoint initialized successfully.")
        ep.libDestroy()
        print("Endpoint destroyed successfully.")
    except pj.Error as e:
        print(f"Error initializing Endpoint: {e}")

if __name__ == "__main__":
    test_pjsua2()
```

### PJSIP version

2.14

### Context

Im in Linux Mint 21.1, using python3-dev as instructed on the official doc

### Log, call stack, etc

```shell
Endpoint class exists: True
Account class exists: True
Call class exists: True
AudioMediaPlayer class exists: True
13:48:32.650           endpoint.cpp !instance error: Not found (PJ_ENOTFOUND) (status=70006) [../src/pjsua2/endpoint.cpp:606]
Error initializing Endpoint: 
```
```

**Comment by nanangizz** [comment]
```ep = pj.Endpoint.instance()``` is for querying any existing instance, not creating one. To create one, you can use ```ep = pj.Endpoint()```, please check the sample code [here](https://docs.pjsip.org/en/latest/pjsua2/hello_world.html#python3).
