### ISSUE TITLE
Use TURN server configuration based on NAT type

### ISSUE THREAD

**Issue by YogatBear** [pjsip/pjproject#4106]
### Describe the feature

I am using PJSUA 2.14.1 for Android, and have noticed that setting TurnEnabled will always set c=IN to the TURN server IP, essentially always forcing traffic through it, even when on networks that work without it (for example NAT type 8).

### Describe alternatives you've considered

I tried checking for the NAT type while creating the account, but I occasionally get a PJ_EPENDING error since I sometimes create the account right after starting the application. For now I have to store the account configuration and modify it before sending an invite/registering to receive an invite.

### Additional context

I am unsure if this is the desired behavior or if I'm doing something wrong in my implementation, since from my understanding of the documentation and the use of TURN servers in general, they should be inserted into the ICE candidates and only be used when sending RTP through conventional methods fail. I would just like to avoid using it when it is not required, but again it seems that as long as I set it to enabled in the account configuration, it is always used.

**Comment by sauwming** [comment]
You can check the log for the ICE negotiation process in order to know why TURN was selected.
