### ISSUE TITLE
PJSIP Video Support for Python3

### ISSUE THREAD

**Issue by ahmedFarouk2020** [pjsip/pjproject#4111]
### Describe the feature

Is it even possible to use video calls on python! After building, I tested the pjsua-x86_64-w64-mingw32.exe and video calls works fine but after creating the python extension using swig I still cannot use video calls and error message "Assertion failed: call->opt.vid_cnt == 0, file ../src/pjsua-lib/pjsua_call.c, line 682" appears after setting pj.CallOpParam.videoCount to 1 and make a call.

I used [pjsip doc](https://docs.pjsip.org/en/latest/specific-guides/build_int/mingw.html) for building using MSYS2.

Thanks

### Describe alternatives you've considered

Nothing

### Additional context

Nope

**Comment by sauwming** [comment]
Yes, Python video is possible. Check the sample.
