### ISSUE TITLE
Configure for Asterisk on Raspberry PI

### ISSUE THREAD

**Issue by martinpmanuel** [pjsip/pjproject#4112]
### Describe the bug

I am receiving this error message when running ./configure for my asterisk server on a raspberry PI.

checking for embedded pjproject (may have to download)... configuring
[pjproject]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.14.1/pjproject-2.14.1.tar.bz2 to /tmp/pjproject-2.14.1.tar.bz2
[pjproject]  Retrying download
[pjproject]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.14.1/pjproject-2.14.1.tar.bz2 to /tmp/pjproject-2.14.1.tar.bz2
make: *** [Makefile:102: /tmp/pjproject-2.14.1.tar.bz2] Error 4
failed
configure: Unable to configure third-party/pjproject
configure: error: Re-run the ./configure command with 'NOISY_BUILD=yes' appended to see error details.
![error2](https://github.com/user-attachments/assets/849b3be6-0006-4df7-8625-7d0fd7239ed6)

### 1. Install Opus dev files:
apt-get install xmlstarlet libopus-dev libopusfile-dev

### 2. Exit root:
exit

### 3. Wget the Asterisk source:
$ wget https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-20-current.tar.gz

### 5. Change to Asterisk Folder
$ cd aster[tab]

### 6. Going to install again, so go back to root:
$ sudo su

### 7. Install the prerequisites:
contrib/scripts/install_prereq install

### 8. Configure Asterisk:
./configure --with-pjproject-bundled
Gets the error code after this.

### PJSIP version

2.14.1

### Context

I am trying to install the configuration for my asterisk server and it is having trouble downloading the pjsip configuration. Using the command prompt: ./configure. I am using a raspberry PI/OS and using Asterisk 20.Current.

### Log, call stack, etc

```shell
checking for embedded pjproject (may have to download)... configuring
[pjproject]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.14.1/pjproject-2.14.1.tar.bz2 to /tmp/pjproject-2.14.1.tar.bz2
[pjproject]  Retrying download
[pjproject]  Downloading https://raw.githubusercontent.com/asterisk/third-party/master/pjproject/2.14.1/pjproject-2.14.1.tar.bz2 to /tmp/pjproject-2.14.1.tar.bz2
make: *** [Makefile:102: /tmp/pjproject-2.14.1.tar.bz2] Error 4
failed
configure: Unable to configure third-party/pjproject
configure: error: Re-run the ./configure command with 'NOISY_BUILD=yes' appended to see error details.
```

**Comment by sauwming** [comment]
Wrong place to post this?
