### ISSUE TITLE
How to get incoming audio data?

### ISSUE THREAD

**Issue by Riton2013** [pjsip/pjproject#4123]
### Describe the feature

PJSIP version: 2.13

Language:C#

Q: I need get incoming audio data to do something, how can I get data ? Do I need to modify the source code？

Anyone who can help me will be very grateful.

**Comment by sauwming** [comment]
Check:
- on_aud_prev_play_frame()
- https://docs.pjsip.org/en/latest/api/pjmedia/pjmedia.html#media-components-ports
