### ISSUE TITLE
pjsip - python  error: Unable to find vcvarsall.bat

### ISSUE THREAD

**Issue by laithmoha** [pjsip/pjproject#4125]
### Describe the bug

After installing the PJSIP
Implementing orders, and ensuring that they work properly
I want to implement writing programs through Python and use the PJSIP
After implementing
.
Make
In the PJProject-2.14.1 \ PJSIP-Apps \ SRC \ Python \

Upon implementation
C: \ python27 \ python.exe setup.py instal
An error shows

C: \ pjproject-2.14.1 \ pjsip-Apps \ SRC \ Python> C: \ python27 \ python.exe setup.py install
Running Install
Running Build
Running Build_PY
Running Build_Ext
Building '_PJSUA' EXTENSION
Error: unable to find vcvarsall.bat

### Steps to reproduce

pjsua

### PJSIP version

2.14.1

### Context

windows , python

### Log, call stack, etc

```shell
none
```

**Comment by sauwming** [comment]
`vcvarsall` is part of Visual Studio Build Tools.

Also check:
https://docs.pjsip.org/en/latest/pjsua2/building.html#building-python-swig-module
