### ISSUE TITLE
Can HarmonyOS support it

### ISSUE THREAD

**Issue by tonychen0924** [pjsip/pjproject#4128]
### Describe the feature

I would like to know if this open-source framework supports usage on HarmonyOS.

### Describe alternatives you've considered

Looking at the information provided, it supports usage on Android. Given the similarities between the two, I would like to know if it can also run on HarmonyOS. If not, what are the limitations, and is there any plan for future support?

**Comment by sauwming** [comment]
Here's our porting doc:
https://www.pjsip.org/porting.htm

In short, to port PJSIP to another platform, you only need to make sure that PJLIB can successfully run. The first step to do this is by running pjlib-test on the target platform.
