### ISSUE TITLE
No more sndinfo binary in the pjsip-app/src/samples

### ISSUE THREAD

**Issue by IvanRibakov** [pjsip/pjproject#4138]
### Describe the bug

PJSUA CLI app tells you to use `sndinfo` application to list all available system devices in order to find value to supply to `--capture-dev` flag. However upon exploring this repository it appears that `sndinfo.c` has been removed. 

How can I find valid values for supplying to `--capture-dev` flag?

### Steps to reproduce

1. Build repo by running `make`
2. Observe lack of `sndinfo` binary under `pjsip-apps/bin/samples`

### PJSIP version

2.14.1

### Context

PopOS 20LTS x64 system

### Log, call stack, etc

```shell
N/A
```

**Comment by sauwming** [comment]
Right, sndinfo is obsolete.

I've done a grep search on the entire PJSIP and there seems to be no longer any reference to sndinfo in the current codebase in master. Please let me know if I miss something.

**Comment by IvanRibakov** [comment]
Not sure how come it was appearing in the help text for me. Might have been an outdated PJSUA build. I can confirm that help text no longer mentions `sndinfo`. Ok to close it as it's more of a documentation issue than a bug, (Still curious to know what the recommended ways to obtain device IDs are).
