### ISSUE TITLE
How to use AudioMediaPort in andriod

### ISSUE THREAD

**Issue by xscconan** [pjsip/pjproject#4158]
### Describe the feature

How to use AudioMediaPort in andriod?
How to use onFrameReceived and onFrameRequested?

Can you give a sample for the developer? 

Thank you very much

**Comment by sauwming** [comment]
Check the sample for C++ and Python, and try to do the same thing on Java.

**Comment by xscconan** [comment]
> Check the sample for C++ and Python, and try to do the same thing on Java.

Thanks for reply，so far my app always crushed when running to the new AudioMediaPort() step.

I am using 2.14.1, is a  issue or not.  Is it building problem? Should I change to 2.14 version? 

Regards
