### ISSUE TITLE
Outgoing call puts ipv6 in sdp offer

### ISSUE THREAD

**Issue by Matan-Fridman** [pjsip/pjproject#4163]
### Describe the bug

When i try to make a call using only specific service providers' mobile data, the sdp offer contains ipv6 address in every possible field, even though the request is coming through ipv4. This happens when i run the pjsua2 swift sample app as well as my own app in which i have tried and failed many 'solutions'. This does not happen on android. How can i fix this issue?

### Steps to reproduce

1. Run pjsua2 with certain service provider (kpn for me)
2. sdp shows ipv6 
3. since my server does not support ipv6 calls don't connect

### PJSIP version

2.14

### Context

when runnning on iphone

### Log, call stack, etc

```shell
sdp offer shows ipv6 addresses
```

**Comment by sauwming** [comment]
Check #3835 and #4067

**Comment by Matan-Fridman** [comment]
i have put:
        ```
acfg.mediaConfig.ipv6Use = PJSUA_IPV6_DISABLED;
        acfg.sipConfig.ipv6Use = PJSUA_IPV6_DISABLED;
        MyAccount *newAcc = new MyAccount;
        newAcc->create(acfg, `true);
```
and even in my register it shows ipv6:

Via: SIP/2.0/UDP [2a02:a420:23e:558c:186b:4ca8:20e2:f94d]:56949
Contact: <sip:972797001034@[2a02:a420:23e:558c:186b:4ca8:20e2:f94d]:56949;ob>;+sip.ice

Can i provide any more details to get some help?

**Comment by Matan-Fridman** [comment]
i have put:
```
acfg.mediaConfig.ipv6Use = PJSUA_IPV6_DISABLED;
acfg.sipConfig.ipv6Use = PJSUA_IPV6_DISABLED;
MyAccount *newAcc = new MyAccount;
newAcc->create(acfg, `true);
```
and even in my register it shows ipv6:

```
Via: SIP/2.0/UDP [2a02:a420:23e:558c:186b:4ca8:20e2:f94d]:56949
Contact: <sip:972797001034@[2a02:a420:23e:558c:186b:4ca8:20e2:f94d]:56949;ob>;+sip.ice

```
Can i provide any more details to get some help?
