### ISSUE TITLE
Incoming call crashes app.

### ISSUE THREAD

**Issue by erwiower2** [pjsip/pjproject#4170]
### Describe the bug

/Users/user/Desktop/pjproject-2.14.1/pjsip-apps/src/pjsua2/ios-swift-pjsua2/ios-swift-pjsua2.xcodeproj crashes by accepting incoming call with 

`20:11:26.410           pjsua_call.c  Answering call 1: code=200
20:11:26.410         inv0x11c3cf0a8  ..SDP negotiation done: Success
20:11:26.412          pjsua_media.c  ...Call 1: updating media..
20:11:26.412          pjsua_media.c  .....Media stream call01:0 is destroyed
20:11:26.412         udp0x11c270c00  ....UDP media transport started
20:11:26.412            pjsua_aud.c  ....Audio channel update..
20:11:26.413        strm0x11c358028  .....VAD temporarily disabled
20:11:26.413         udp0x11c270c00  .....UDP media transport attached
20:11:26.413        strm0x11c358028  .....Encoder stream started
20:11:26.413        strm0x11c358028  .....Decoder stream started
20:11:26.414          pjsua_media.c  ....Audio updated, stream #0: speex (sendrecv)
20:11:26.414            pjsua_aud.c  ...Conf connect: 1 --> 0
20:11:26.414            pjsua_aud.c  ....Set sound device: capture=-1, playback=-2, mode=0, use_default_settings=0
20:11:26.414            pjsua_aud.c  .....Error retrieving default audio device parameters: Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV) [status=420006]`

### PJSIP version

2.14.1

### Plattform
iOS 17.5

Don't know how to resolve. None of the pjsip projects works in 2024

**Comment by sauwming** [comment]
From your information, it didn't look like a crash. The log indicated an error in finding audio device, probably due to permission issue. If there's a crash or an assertion, please provide the stack trace.

**Comment by erwiower2** [comment]
Thanks. Could you tell me how to disable pjsip logs in xcode console?
