### ISSUE TITLE
How can I save a video call ?

### ISSUE THREAD

**Issue by SmWork78** [pjsip/pjproject#4185]
### Describe the feature

I'm writing a video call server in C++ that allows video calls, and I want to save the video. How can I do that?
 Note: I'm testing the program on a virtual machine ubuntu server that doesn't have a webcam.
 ```
     virtual void onCallMediaState(OnCallMediaStateParam& params)
    {
        CallInfo callInfo = getInfo();
        for (unsigned media_index = 0; media_index < callInfo.media.size(); media_index++)
        {
            if (callInfo.media[media_index].type == PJMEDIA_TYPE_AUDIO)
            {
                AudioMedia audioMedia = getAudioMedia(media_index);
                saveAudioMedia(audioMedia, media_index);
            }
            if (callInfo.media[media_index].type == PJMEDIA_TYPE_VIDEO)
            {
               // Error
                VideoMedia videoMedia = getEncodingVideoMedia(media_index);
            }
        }
    }
 ```
 And I got this error:
 ```
 call.cpp  .....getEncodingVideoMedia() error: no encoding slot (recvonly?) (status=70004) [../src/pjsua2/call.cpp:630]
 ```
 
1. What should I do to be able to save a video call on a server that doesn't have a webcam?
2. How can I save a video call?

**Comment by SmWork78** [comment]
Can you help me?

**Comment by sauwming** [comment]
You need to implement the video recorder yourself.
Check `avi_player` for video player implementation, now you need to do something similar for recording.
Check also `wav_writer` which does the same but for audio.
