### ISSUE TITLE
Getting error while running command make dep on windows (Building PJSUA python bindings)

### ISSUE THREAD

**Issue by shubhm2303** [pjsip/pjproject#4190]
### Describe the feature

Steps followed

1. Installed MinGW (added bin folder path in environment variables)
2. Cloned PJSIP
3. Executed below commands
     a. ./configure
     b. make dep
     c. make
     
While executing command **make dep**, I got the below error

`/usr/bin/sh: -c: line 2: syntax error: unexpected end of file
C:/Users/GS-3346/Downloads/pjproject-2.14.1/pjproject-2.14.1/build/rules.mak:227: recipe for target 'depend' failed
make[3]: *** [depend] Error 2
make[3]: Leaving directory 'C:/Users/GS-3346/Downloads/pjproject-2.14.1/pjproject-2.14.1/third_party/build/webrtc'
Makefile:100: recipe for target 'depend' failed
make[2]: *** [depend] Error 2
make[2]: Leaving directory 'C:/Users/GS-3346/Downloads/pjproject-2.14.1/pjproject-2.14.1/third_party/build/webrtc'
Makefile:7: recipe for target 'dep' failed
make[1]: *** [dep] Error 1
make[1]: Leaving directory 'C:/Users/GS-3346/Downloads/pjproject-2.14.1/pjproject-2.14.1/third_party/build'
Makefile:14: recipe for target 'dep' failed
make: *** [dep] Error 1
`

**Comment by sauwming** [comment]
I tested it here with the current master and didn't encounter such error, so not sure why.
As a workaround, just disable webrtc.
