### ISSUE TITLE
How to use PJSUA2 Python binding outside the MSYS2 MinGW64 environment, making it portable and accessible for standalone projects

### ISSUE THREAD

**Issue by shubhm2303** [pjsip/pjproject#4197]
### Describe the bug

How can I use the PJSUA2 Python binding outside the MSYS2 MinGW64 environment, making it portable and accessible for standalone projects

### Steps to reproduce

NA

### PJSIP version

2.14.1

### Context

I have build the PJSUA@ python binding. Now I want to use the PJSUA2 Python binding outside the MSYS2 MinGW64 environment, making it portable and accessible for standalone projects

### Log, call stack, etc

```shell
NA
```

**Comment by sauwming** [comment]
Once you already install pjsua2 into python, I believe you can use it anywhere outside the MinGW environment. Just make sure that the Python path and its site-packages is correct.
