### ISSUE TITLE
android_get_dev_info() method hardcoded？

### ISSUE THREAD

**Issue by happyfsyy** [pjsip/pjproject#4204]
### Describe the bug

Hello, @sauwming

I have discovered that the android_get_dev_info() method does not seem to distinguish between specific Android devices, returning the same result regardless of whether I am connected to a Bluetooth device or a USB headset. 
This poses a challenge for me in managing multiple audio devices simultaneously (for example, answering two calls at the same time).

Below is the source code of the android_get_dev_info() method in the android_jni_dev.c file located in the pjmedia-audiodev directory, along with the log results I have recorded.
``` c
static pj_status_t android_get_dev_info(pjmedia_aud_dev_factory *f,
                                        unsigned index,
                                        pjmedia_aud_dev_info *info)
{
    PJ_UNUSED_ARG(f);
    
    pj_bzero(info, sizeof(*info));
    
    pj_ansi_strxcpy(info->name, "Android JNI", sizeof(info->name));
    pj_ansi_strxcpy(info->driver, DRIVER_NAME, sizeof(info->driver));
    info->default_samples_per_sec = 8000;
    info->caps = PJMEDIA_AUD_DEV_CAP_OUTPUT_VOLUME_SETTING |
                 PJMEDIA_AUD_DEV_CAP_INPUT_SOURCE;
    info->input_count = 1;
    info->output_count = 1;
    info->routes = PJMEDIA_AUD_DEV_ROUTE_CUSTOM;
    
    return PJ_SUCCESS;
}
```
![image](https://github.com/user-attachments/assets/479a8fb1-dbb8-4afa-a106-8c4cb42b0d6a)

To enable the simultaneous management of two audio devices on Android (i.e., answering two calls concurrently), I believe it would be necessary for you to obtain a list of devices and, when calling the android_create_stream() method in android_jni_dev.c, specify the audio device using AudioRecord.setPreferredDevice() and AudioTrack.setPreferredDevice() as needed. 
Would such a change be complicated or infeasible?

I would like to ask if there are any plans to update or optimize this part of the code in future releases.

Additionally, if there are no immediate plans to modify the AndroidJNI source code, I still hope to implement the functionality of conducting two phone calls simultaneously on two audio devices.
Based on the response in #4199, you mentioned that it could be achieved using the ExtraAudioDevice class, but its constructor requires ‘Playback device ID’ and ‘Record device ID’, which I am currently unable to obtain from PJSIP. 
May I ask if I can directly use the IDs obtained from the Android system's AudioManager API to create an ExtraAudioDevice instance (e.g., ExtraAudioDevice(playdev, recdev))?

Thank you for your attention and assistance!

### Steps to reproduce

1

### PJSIP version

2.14.1

### Context

android

### Log, call stack, etc

```shell
1
```

**Comment by sauwming** [comment]
Unfortunately, we don't have such plan for the moment. One of the main reasons is that we already have Oboe, which is what I have suggested to you in #4199.
But if for some reasons, you don't wish/can't use Oboe, feel free to add the feature into Android JNI.

**Comment by happyfsyy** [comment]
@sauwming ,Thank you very much for your reply.

Well, the key reason is that I don't know oboe, and I don't know how to connect oboe with pjsip calls.

Or did I misunderstand you and should I open oboe in config_site_sample.h and recompile? 
And then I can get the list of devices in Android, right?
The code for config_site_sample.h is as follows:
```
#define PJMEDIA_AUDIO_DEV_HAS_PORTAUDIO     0
#define PJMEDIA_AUDIO_DEV_HAS_WMME          0
#define PJMEDIA_AUDIO_DEV_HAS_OPENSL        0
#define PJMEDIA_AUDIO_DEV_HAS_ANDROID_JNI   0
#define PIMEDIA AUDIO DEV HAS OBOE          1
```
The code for config_site.h is as follows:
```
#define PJ_CONFIG_ANDROID 1
#include <pj/config_site_sample.h>
```

**Comment by sauwming** [comment]
https://docs.pjsip.org/en/latest/get-started/android/build_instructions.html#enable-oboe
