### ISSUE TITLE
Getting an error in makeCall (pjsua2 python)

### ISSUE THREAD

**Issue by shubhm2303** [pjsip/pjproject#4207]
### Describe the bug

I am trying to make a call between two agents using pjsua2 python. Account creation is successful for both agents. But when one agent calls another agent using makCall function. I am getting an error.

### Steps to reproduce

1. Create two accounts
2. makeCall

### PJSIP version

2.14.1

### Context

Running script on windows 11

### Log, call stack, etc

```shell
16:07:52.072          sip_resolve.c  ....Failed to resolve '**************.com': gethostbyname() has returned error (PJ_ERESOLVE)
16:07:52.076    tsx000002938f7324d8  ....Failed to send Request msg INVITE/cseq=24416 (tdta000002938f7314c8)! err=70018 (gethostbyname() has returned error (PJ_ERESOLVE))
```

**Comment by sauwming** [comment]
I believe the error is self-explanatory.
