### ISSUE TITLE
Implementing secure VoIP calls using PJSIP with external SRTP configured to use WolfSSL

### ISSUE THREAD

**Issue by MahipalChalla** [pjsip/pjproject#4210]
### Describe the feature

I'm working on Project about implementing secure VoIP calls using PJSIP with external SRTP configured to use WolfSSL in windows, Here’s a summary of my progress and the challenges I'm facing:
 
1. Current Setup:
   - I have compiled PJSIP v2.14.1 with internal SRTP (the one present in the `thirdparty/` directory in the PJSIP project).
   - I am using OpenSSL v1.1.1w and have successfully made SIP calls with the help of OpenSSL.
   - following flags/Macro I define in the pjsip config_site.h file. and hence able to Make Secure sip call.
      PJ_SSL_SOCK_IMP_OPENSSL
      PJ_HAS_TLS_SOCK
      PJSIP_HAS_TLS_TRANSPORT
      PJ_HAS_SSL_SOCK
 
2. Objective:
   - My goal is to make secure calls with external SRTP using WolfSSL. Here are the steps I’ve followed so far:
     1. Compiled the WolfSSL v5.7.2 library.
     2. Compiled the libSRTP library (external SRTP).
     3. Linked the external SRTP with WolfSSL and disabled OpenSSL in SRTP.
3. Challenges:
   - I am facing some issues linking PJSIP v2.14.1 with external SRTP that has WolfSSL support. Specifically:
     1. How can I enable WolfSSL support in PJSIP for providing TLS support, given that there is no specific flag for WolfSSL in PJSIP v2.14.1?
     2. Currently, SRTP supports both OpenSSL and WolfSSL, but this feature has not been officially released yet.
     3. When will SRTP officially release their code to support WolfSSL, and will PJSIP update to include this support? If yes, is there an approximate timeline for this?

**Comment by amubiera** [comment]
I almost have this working with mbedTLS. I may submit a pull request for it at some point. I got lucky that the libSRTP included with PJSIP already supports mbedTLS. But sounds like you've already upgrade it to the latest libSRTP with support for WolfSSL.

This is basically what you would have to do:
- Add a new `#define PJ_SSL_SOCK_IMP_WOLFSSL` to `pjlib/include/pj/config.h` with the next available index.
- Set `PJ_SSL_SOCK_IMP` to `PJ_SSL_SOCK_IMP_WOLFSSL` in your configuration.
- Add a new `pjlib/src/pj/ssl_sock_wssl.c` that fully implements the API expected by `ssl_sock_imp_common.c`. i.e. `ssl_create`, `ssl_do_handshake`, `ssl_renegotiate`, etc...
- For media, SDES will work if you don't need DTLS .
- But if you need DTLS:
  - Define `PJMEDIA_SRTP_HAS_DTLS` in your configuration.
  - Rename `pjmedia/src/pjmedia/transport_srtp_dtls.c` to `transport_srtp_dtls_ossl.c`.
  - Add a new `transport_srtp_dtls_wssl.c` that fully implements the API expected by `transport_srtp.c`. e.g. `dtls_init`, `dtls_create`, the ops in `dtls_op`, etc...
  - Modify the `#if` directives in `transport_srtp.c` to include the proper `transport_srtp_dtls_xxx.c` by checking `PJ_SSL_SOCK_IMP`.

Alternatively to writing everything by hand, you can try enabling [WolfSSL's OpenSSL compatibility](https://www.wolfssl.com/documentation/manuals/wolfssl/chapter13.html) and make sure PJSIP's include paths can find `wolfssl/openssl/ssl.h`, but I'm not sure if the OpenSSL functionality used in PJSIP will be emulated by WolfSSL.

It's worth a shot, though!

I'm sure the maintainers will have other suggestions.

**Comment by sauwming** [comment]
Great writeup, @amubiera , thanks! Couldn't have said it better myself.

The only thing I can add is that as of right now, we don't have plan to support WolfSSL (unless there's popular demand). So feel free to implement the above suggestion and submit a patch (if you wish so).

**Comment by MahipalChalla** [comment]
As per the above suggestion, I've developed a wolfSSL interface application for both the server and client with reference of ssl_sock_imp_common.c. One instance is assumed to be the server and the other the client, running in parallel in Visual Studio. During secure call testing we found that the client-side connect-related APIs are not being called, instead the accept API is being called. However wolfSSL initialization and other APIs are working as expected. I have investigated and added basic PJ logs at each API level but those logs are not being triggered as we expected for the client and server API calls. These APIs are called from sip_transport_tls.c.
I am unsure how to test this scenario. Do you have any documentation on implementation and testing? It would be very helpful. I've attached the developed wolfSSL interface skeleton code for your reference. If you have any similar reference code, it would be greatly appreciated

[ssl_sock_wolSSL.txt](https://github.com/user-attachments/files/18801275/ssl_sock_wolSSL.txt)

**Comment by sauwming** [comment]
You can test it using the unit test in pjlib-test ssl_sock_test(), so you don't need to involve pjsip level, such as sip_transport_tls.

Recently we just merged a contributed Mbed TLS implementation in https://github.com/pjsip/pjproject/pull/4295, so you can use it as a reference.

**Comment by PrajapatiMP** [comment]
I tried to develop the ssl_sock_wolfssl.c interface with the help of ssl_sock_ossl.c and ssl_sock_mbedtls file.
But we encountered a couple of issue like: 
1. Wolfssl_new () is failing return error code : -173 "BAD Argument"
2. Handshake issue return error -308 and -344. (Here I used the certs that is available in wolfssl/certs/ directpry)

attached file consist the code for ssl_create () and init_wolfssl().

[ssl_create and init_wolfssl.txt](https://github.com/user-attachments/files/19547754/ssl_create.and.init_wolfssl.txt)

If you have any suggestion/ input on this please let us know.

**Comment by amubiera** [comment]
Hi @PrajapatiMP, I'm not too familiar with WolfSSL, but they do have a lot of [comprehensive examples](https://github.com/wolfSSL/wolfssl-examples/blob/master/tls/client-tls.c) that you could try to model your pjsip code after.

**Comment by PrajapatiMP** [comment]
Hi PJSIP Community/Team,

Regarding: Issues with WolfSSL Interface Integration in PJSIP (Handshake and Related Errors)

Thank you for your response and suggestions.

Following your advice, I referred to the examples provided in the wolfssl/tls/client-tls.c and server-tls.c files. Based on those, I developed the WolfSSL interface for PJSIP by running the PJSUA app with my custom WolfSSL implementation. However, I am encountering the following issues:

1. WolfSSL_write() Error:
   21:33:13.845   SSL_sock_imp  Writing 256 bytes to SSL buffer
   Preparing to call wolfSSL_write:
     wlssock  = 000001C7EE141E58
     src      = 000001C7EE15E6E8
     len      = 256
     src data = 16 03 03 00 FB 01 00 00 F7 03 03 4D EA 45 1D 8D ...
   21:33:13.845   SSL_sock_imp  After wolfSSL_write: -1 bytes written, 256 : (int)len
   
2. Handshake Errors:
   - Error on accepting connection: 
     21:33:13.845 ssl000001C7EE1  Handshake failed on 127.0.0.1:5061 in accepting 127.0.0.1:50425: Pending operation (PJ_EPENDING)
   - Error on connecting:  
     21:33:13.845 ssl000001C7EE1  Handshake failed on 127.0.0.1:50425 in connecting to 127.0.0.1:5061: End of file (PJ_EEOF)

To provide more context:
- I used the certificates available in the wolfssl/certs/ directory during development.
- Attached are the logs I gathered during the process and my developed WolfSSL interface file (ssl_sock_wolfssl.c).

It would be great if you could review these files and share any insights or suggestions to resolve these issues.

Looking forward to your input.

Thank you for your time and guidance.

Best regards,  
Monu Prajapati.

[ssl_sock_wolfssl_interface.txt](https://github.com/user-attachments/files/19872485/ssl_sock_wolfssl_interface.txt)

[caller.log](https://github.com/user-attachments/files/19872493/caller.log)
