### ISSUE TITLE
Callback onCallTsxChanged is not consistent

### ISSUE THREAD

**Issue by wosrediinanatour** [pjsip/pjproject#4211]
### Describe the bug

Callback `onCallTsxChanged (...)` is called differently for incoming and outgoing INVITE transactions:

Outgoing INVITE transaction:
- when request sent: state: PJSIP_TSX_STATE_CALLING  type: PJSIP_EVENT_TX_MSG
- when provisional response received: state: PJSIP_TSX_STATE_PROCEEDING  type: PJSIP_EVENT_RX_MSG
- when final response received:  state: PJSIP_TSX_STATE_TERMINATED  type: PJSIP_EVENT_RX_MSG

Incoming INVITE transaction:
- (when request received:  state: PJSIP_TSX_STATE_TRYING  type: PJSIP_EVENT_RX_MSG  <-- _from https://github.com/pjsip/pjproject/issues/3605 I know that that is okish_.)
- when provisional response sent:  state: PJSIP_TSX_STATE_PROCEEDING  type: PJSIP_EVENT_TX_MSG
- when final response sent:  state: PJSIP_TSX_STATE_COMPLETED  type: PJSIP_EVENT_TX_MSG
- when final response sent:  state: PJSIP_TSX_STATE_TERMINATED  type:  PJSIP_EVENT_USER

It is the same for initial INVITEs and Re-INVITEs.

### Steps to reproduce

1. Make a call to/from an account and log arguments of `onCallTsxState(...)`.
2. Have a ongoing call, and make a reinvite in both directions, and log arguments of `onCallTsxState(...)`.

### PJSIP version

2.14.1

### Context

Follow-up of https://github.com/pjsip/pjproject/issues/3605.

### Log, call stack, etc

```shell
For outgoing INVITE transaction:

Incoming Response msg 200/INVITE/cseq=651 (rdata0x5310000dc828) in state Proceeding 
State changed from Proceeding to Terminated, event=RX_MSG
Received Response msg 200/INVITE/cseq=651 (rdata0x5310000dc828)
Transaction tsx0x51d000002928 state changed to Terminated
State changed from EARLY to CONNECTING, event=TSX_STATE 
Got SDP answer in Response msg 200/INVITE/cseq=651 (rdata0x5310000dc828)
...
 Received Response msg 200/INVITE/cseq=651 (rdata0x5310000dc828), sending ACK
```
```

**Comment by sauwming** [comment]
Can you highlight where the inconsistencies are, or what it should be?

As a reference, here are the INVITE client and server transaction states as per the RFC:
UAC: https://datatracker.ietf.org/doc/html/rfc3261.html#section-17.1.1.2
UAS: https://datatracker.ietf.org/doc/html/rfc3261.html#section-17.2.1

**Comment by wosrediinanatour** [comment]
In both block diagrams, State Completed takes part. But this state is not signaled by PJSUA(2).

**Comment by sauwming** [comment]
No, state Completed do not always have to happen.
And I don't think you can expect the state flow and the state change reason (i.e. RX/TX/USER) to be exactly the same between UAC and UAS.

**Comment by sauwming** [comment]
I will close this for now. If you think that there's any specific PJSIP tsx state that doesn't seem to be in accordance with the RFC, please let us know.

As an additional note, there's a newer RFC 6026 (https://www.rfc-editor.org/rfc/rfc6026.html) that updates this tsx state machine, which unfortunately slightly complicates things. We try to incorporate this as well, but since it introduces a new state (`Accepted`), it can potentially causes backward incompatibility for users who do not expect to receive this, so we opted not to fully implement it. In summary, our current tsx machine is a mix between the older RFC 3261 and the updated 6026.

**Comment by wosrediinanatour** [comment]
Thank you very much for explaining the internals! I was so focused on the API that I ignored parts of the RFCs...
