### ISSUE TITLE
WebRtcAec3 get "Bus Error" on ARMv7 processor

### ISSUE THREAD

**Issue by heretic13** [pjsip/pjproject#4217]
### Describe the bug

The implementation of WebRtcAec3 support contains an error (appears on ARM processors).

When using the WebRtcAec3 algorithm in a release build, you can get a "Bus Error" and the program terminates. For a debug build, this does not occur.

### Steps to reproduce

1. Build pjsip with WebRtcAec3 support for Linux ARM v7 platform (Release Build with optimizations).
2. Build your program using pjsip.
3. Run the program selecting WebRtcAec3.
4. Get "Bus Error" and program crush.

### PJSIP version

2.15

### Context

OS: Linux
CPU: ARMv7 (Little Endian)
AEC Algorithm: WebRtcAec3

### Log, call stack, etc

```shell
syslog some lines:

2024-12-09T18:18:48.152352+00:00 NanoPi-NEO-Core kernel: [358643.587283] Alignment trap: not handling instruction f9008adf at [<0064026e>]
2024-12-09T18:18:48.152474+00:00 NanoPi-NEO-Core kernel: [358643.594582] Unhandled fault: alignment exception (0xa21) at 0x00ebc824
2024-12-09T18:18:48.152495+00:00 NanoPi-NEO-Core kernel: [358643.601258] pgd = d63034c0
2024-12-09T18:18:48.162083+00:00 NanoPi-NEO-Core kernel: [358643.604155] [00ebc824] *pgd=5b269003, *pmd=54228003, *pte=e000005fe74f5f
```

**Comment by heretic13** [comment]
ARM processors are very sensitive to data alignment.
For the "Bus Error" error, one of the reasons is unaligned data.
The debugging result showed that the problem is in the webrtc_aec3_create function.
![photo_2024-12-10_10-51-09](https://github.com/user-attachments/assets/04c0355b-043c-4203-8cce-9aec4c1dccda)
![photo_2024-12-10_10-50-55](https://github.com/user-attachments/assets/6aa018c6-808e-4d74-a182-508dd1a469c5)
![photo_2024-12-10_10-50-35](https://github.com/user-attachments/assets/6247e123-be66-414e-96e0-220be73259f5)

**Comment by heretic13** [comment]
Detailed error description.

The basic data alignment for the ARM v7 processor is 4 bytes (32 bits).

The webrtc_aec3_create function allocates memory for the webrtc_ec structure using the memory pool. The memory pool allocates memory blocks aligned to PJ_POOL_ALIGNMENT (in my case, 4 bytes). Everything is correct here.

But then the C++ optimizer comes into play.
This is what it did:

1. It swapped the data copy commands in the previously allocated webrtc_ec echo structure.
2. It used the vstl.64 assembler instruction to transfer the contents of several registers to the memory block. The special properties of this assembler instruction are that it requires an aligned data block (specified in the assembler text after the colon). In the example above, 64 bits, that is, 8 bytes.

But the problem is that the memory was allocated by another allocator (which allocated memory aligned to 4 bytes, not 8 bytes). The C++ compiler does not know about this and creates such optimized code.

Thoughts on this matter:

1. Set PJ_POOL_ALIGNMENT equal to 8. But I saw on the Internet that the vstl.64 command can be used to transfer the contents of a larger number of registers to a block of memory. And then the required data alignment can be different (for example, 128 bits).
2. Using operator new to allocate memory for the webrtc_ec echo structure. Do not forget to do "delete echo" in the webrtc_aec3_destroy function. This information will allow the C++ compiler to allocate memory as it needs, with the alignment it needs.

**Comment by sauwming** [comment]
Can you let us know your Linux machine name?
Specifically, here:
https://github.com/pjsip/pjproject/blob/3accf04a42662f8146caf7cc89ad56175883bc55/aconfigure.ac#L2835-L2840

Is it using the neon instruction set?
If we add the compilation flag: `-DPJ_POOL_ALIGNMENT=8` there, does it solve the issue there?

**Comment by heretic13** [comment]
Some lines from current config.log:

Target: arm-linux-gnueabihf

ac_webrtc_aec3_cflags='-DWEBRTC_ARCH_ARM_V7 -mfloat-abi=hard -mfpu=neon -DWEBRTC_LINUX=1 -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_POSIX=1'
ac_webrtc_aec3_instset='neon'

----
I will check DPJ_POOL_ALIGNMENT=8 later.

**Comment by heretic13** [comment]
Very strange.

I change file pjproject/aconfigure.ac. Line 2839  (pjproject 2.15) to
ac_webrtc_aec3_cflags="-DWEBRTC_ARCH_ARM_V7 -DSOME_TEST -DPJ_POOL_ALIGNMENT=8 -mfloat-abi=hard -mfpu=neon"

after configure I get this line in config.log
ac_webrtc_aec3_cflags='-DWEBRTC_ARCH_ARM_V7 -mfloat-abi=hard -mfpu=neon -DWEBRTC_LINUX=1 -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_POSIX=1'

It looks like the changes in the settings are not applied.
And of course after building the library and my application I get a "bus error".

**Comment by sauwming** [comment]
After modifying `aconfigure.ac`, you need to run: `autoconf aconfigure.ac > aconfigure`. Then rebuild PJSIP: `make realclean`, `./configure`, `make dep`, `make`.

**Comment by heretic13** [comment]
After this.

line in config.log:
ac_webrtc_aec3_cflags='-DWEBRTC_ARCH_ARM_V7 -DPJ_POOL_ALIGNMENT=8 -mfloat-abi=hard -mfpu=neon -DWEBRTC_LINUX=1 -DWEBRTC_APM_DEBUG_DUMP=0 -DWEBRTC_POSIX=1'

After compiling the library and the program, "Bus error" again.

gdb again shows the use of the "vst1.64" command and a pointer multiple of 4 (but not 8).

In the source code you can see that the memory pool that is used to allocate memory for "webrtc_ec" is created inside the pjmedia_echo_create2 function (file echo_common.c). I am not sure if the `ac_webrtc_aec3_cflags` compilation rules apply to this file.

**Comment by sauwming** [comment]
Ah you're right, sorry.
It should be added to `CFLAGS` instead of `ac_webrtc_aec3_cflags`, i.e. `CFLAGS="-DPJ_POOL_ALIGNMENT=8 $CFLAGS"`.

**Comment by heretic13** [comment]
`
./configure --disable-video --with-external-pa --enable-libwebrtc-aec3 --host=arm-linux-gnueabihf --target=armv7l-unknown-linux-gnueabihf --prefix=/mnt/Hell/Projects/nanopi/sysrootDeb12i/usr CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ CFLAGS="-DPJ_POOL_ALIGNMENT=8 --sysroot=/mnt/Hell/Projects/nanopi/sysrootDeb12i -mfpu=neon -march=armv7-a -DPJ_HAS_LIMITS_H=1" LDFLAGS="--sysroot=/mnt/Hell/Projects/nanopi/sysrootDeb12i"
`


Multiple warnings when compile pjsip:

`
arm-linux-gnueabihf-gcc -DPJ_AUTOCONF=1 -DPJ_POOL_ALIGNMENT=8 --sysroot=/mnt/Hell/Projects/nanopi/sysrootDeb12i -mfpu=neon -march=armv7-a -DPJ_HAS_LIMITS_H=1 -DPJ_IS_BIG_ENDIAN=0 -DPJ_IS_LITTLE_ENDIAN=1                 -I/mnt/Hell/Projects/nanopi/pjproject-2.15/pjlib/include -I/mnt/Hell/Projects/nanopi/pjproject-2.15/pjlib-util/include -I/mnt/Hell/Projects/nanopi/pjproject-2.15/pjnath/include -I/mnt/Hell/Projects/nanopi/pjproject-2.15/pjmedia/include -I/mnt/Hell/Projects/nanopi/pjproject-2.15/pjsip/include                  \
	-c -o output/sample-armv7l-unknown-linux-gnueabihf/aviplay.o \
	../src/samples/aviplay.c 
In file included from /mnt/Hell/Projects/nanopi/pjproject-2.15/pjlib/include/pj/config.h:61,
                 from /mnt/Hell/Projects/nanopi/pjproject-2.15/pjmedia/include/pjmedia/config.h:26,
                 from /mnt/Hell/Projects/nanopi/pjproject-2.15/pjmedia/include/pjmedia/types.h:27,
                 from /mnt/Hell/Projects/nanopi/pjproject-2.15/pjmedia/include/pjmedia/alaw_ulaw.h:22,
                 from /mnt/Hell/Projects/nanopi/pjproject-2.15/pjmedia/include/pjmedia.h:26,
                 from ../src/samples/aviplay.c:19:
/mnt/Hell/Projects/nanopi/pjproject-2.15/pjlib/include/pj/compat/os_auto.h:182: warning: "PJ_POOL_ALIGNMENT" redefined
  182 | #define PJ_POOL_ALIGNMENT 4
      | 
<command-line>: note: this is the location of the previous definition
`

And my recompiled program get "bus error" in the same location.

**Comment by sauwming** [comment]
After checking the code, we actually already allocate AEC3 objects using new and delete:
https://github.com/pjsip/pjproject/blob/cb8536872d509115e25f553849431161687d1c1e/pjmedia/src/pjmedia/echo_webrtc_aec3.cpp#L94-L100

So that's why modifying pool alignment won't help.
Unfortunately, I don't know how to fix this, and since I don't have access to Linux arm machine, I can't test it as well (all I know is that it seems to works without issues on other ARM machines, such as on Mac ARM, and ARM mobile devices).

Some suggestions to try/test:
- Add compilation flags such as `-fno-strict-aliasing` or `-malign-double` or `-munaligned-access` and see if it helps.
- Compile with `-O0` to avoid optimisation.
- Try with the generic instruction set (instead of neon).

**Comment by heretic13** [comment]
I meant this line. This is memory allocation.

https://github.com/pjsip/pjproject/blob/cb8536872d509115e25f553849431161687d1c1e/pjmedia/src/pjmedia/echo_webrtc_aec3.cpp#L79

**Comment by sauwming** [comment]
> My fast solution is
> `echo = new webrtc_ec{};` and
> `delete echo;` in `webrtc_aec3_destroy`.

And this can run fine without crash?

**Comment by heretic13** [comment]
Yes. It works without any problems.
